### ISSUE TITLE
site streaming lopav

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#100]
j'ai essayé de créer cette sources (similaire du site vanoz) pour lopav.com ça marche bien appar la section nouveauté

http://pastebin.com/3KvFwz7g

**Comment by FreeFighter77** [comment]
Bonjour,tu t es pris la tete pour rien ce site a exactement les memes films que vanoz. lopav,vanoz,poploz sont tous des copie conforme ....

**Comment by arzaz** [comment]
Bonjour FreeFighter77,

Je ne trouve nulle part la source vanoz, avec la dernière mise a jour 2.9.
Est-il possible d'avoir cette source sous format .py?

Merci

**Comment by FreeFighter77** [comment]
elle n a pas ete ajouté car lord venom ne veut pour l instant pas utiliser urlresolver.Si tu veux l ajouter regarde sur le github section meilleur source hd (il y a 3 manip a faire)

**Comment by arzaz** [comment]
Je suis complément noyé, je ne sais pas ou trouver la section meilleur source hd?

Merci de ton aide FreeFighter77

**Comment by FreeFighter77** [comment]
https://github.com/LordVenom/venom-xbmc-addons/issues/88

**Comment by arzaz** [comment]
Merci beaucoup FreeFighter77
