### ISSUE TITLE
Recuperation des pochettes

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#101]
Bonjour LordVenom,

Merci de régler le problème de récupération des pochettes de certains films.

Salutations

**Comment by TmpName** [comment]
Essaye de donner le site en question, car dans certain cas c'est normal, le site scrappé ne les affiche pas forcement.

**Comment by arzaz** [comment]
Exemple de films sans pochettes  sur tous les sites

TAKEN 3
LA FRENCH
IMITATION GAME
......

**Comment by TmpName** [comment]
La pochette, c'est quoi ? L'affiche qui se met en bas a droite, le truc en fond d'ecran ?
Si c'est l'affiche, je vient de tester taken 3 avec un des site et je l'ai eu.
