### ISSUE TITLE
Voulez-vous un github bêta ?

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons#102]
Bonjour,

Tout et dit dans le titre que pensez vous d'un github bêta ouvert a tous a la modification.Je garde le principale fermer car c'est lui qui envoie les mises a  jour a tous les utilisateurs.
Si j'ouvre un github bêta ouvert a tous en écriture je pourrais tester et comme d'habitude envoyer une mise a jour par mois.

**Comment by arzaz** [comment]
OUI

**Comment by TmpName** [comment]
Oui. Impossible de savoir ou on en est sinon, pas mal de motivés pour ce pluggin.

**Comment by FreeFighter77** [comment]
Pourquoi pas ;)
