### ISSUE TITLE
divers bug constatés

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons#104]
-J'ai vu que quand on veut marquer un episode comme vu,on a une erreur de script.
-La source vos animes.com est morte.
- Le hoster vk bug sous fullstream.me (ex:http://vkontakte.ru/video_ext.php?oid=205452121&amp;id=171080073&amp;hash=e60f4d5c7551bb13&amp;hd=1).Voila c est un peu pres tt ce que j ai pu constater

**Comment by TmpName** [comment]
Tu aurais un exemple de titre de film stp, meme en specifiant vk player en recherche je ne trouve pas de film valides sur leur site.

**Comment by FreeFighter77** [comment]
alors,ce n est pas via xbmc, je regardais fullstream.me sur xbmc par genres et categorie walt disney, la beaucoup de films n ont pas de lien,donc suis allez voir sur le site et:  http://full-stream.me/movies/films-en-streaming/animation/8579-clochette-et-lexpdition-ferique.html    
il y en a plein d autre en lecteur vk

**Comment by TmpName** [comment]
Ok, alors pour resoudre ce probleme, editer le fichier gui/hosters.py
Rajouter
if ('vkontakte' in sHosterUrl):
return cHosterHandler().getHoster('vk')

**Comment by LordVenom** [comment]
Bonjour,

Le bug marquer lus sera corrigé dans la prochaine version merci.
