### ISSUE TITLE
site streamzzz 

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons#105]
j'ai crée ces 2 sites operationnel a par l onglet next que je n arrive pas a inserer quand une serie a beaucoup d episodes ... 

-streamzzz: http://pastebin.com/zHEDu8zW
-regarder films.com: http://pastebin.com/yG3mpRC9

PS: il est normal qu'il n yest pas de pochette cela vient des sites ... d'ailleur a ce propos il serait interessant que pour des sites comme ci dessus ou adkami par exemple de pouvoir activer juste pour ces sites les metadonnés (moviedatabase)

**Comment by TmpName** [comment]
Tu t es loupé sur le premier, tu as mit streamzer au lieu de streamzzz en faisant le c/c sur pastebin.

**Comment by FreeFighter77** [comment]
Re effectivement un loupe de ma part voici le .py de streamzzz: http://pastebin.com/XWHJABLe
Et tmpName tu as l'air plus calé que moi,si tu peux regarder l histoire du bouton next dans showseries, car pour regarder films et streamzzz le bouton suivant doit etre la (ex: alf il manque l episode 1 qui se situe sur la page suivante.

**Comment by FreeFighter77** [comment]
j'ai vu que ton hoster videott impossible de le faire fonctionner,tu l as testé toi ? http://www.video.tt/e/7vNhraTGs  
ou peux etre as tu modifié la pattern de showhoster ? bref j ai mi les fichiers ici car pas terminer une fois fini,on les passeras ds centralisation. (la prochaine mise a jour va pas rigoler avec tt les modif et ajout).Content qu il y est autant de monde qui participe.

**Comment by TmpName** [comment]
Je t'ai fait une modif pour regarder-film pour le lien "suivant", je pense que pour l'autre site c'est pareil vu que un des sites est une extension de l'autre, ils ont meme les liens de l'autres site sur leur propre page d'acceuil.

>> http://pastebin.com/Jrrby0aY

J'ai du egalement finir de desactiver les images, ca me provoquait un bug.

Oui, je l'ai testé et effectivement il faut editer le fichier gui/hosters, mais je fais des tests rapides, je ne garantis pas n'avoir rien oublié, tient moi au courant si il buggue encore.

**Comment by FreeFighter77** [comment]
chez moi videott n apparait nul part pour regarder-films.com idem pour streamzzz.com (je l ai bien configuré dans lib/...) autant playreplay nickel mais lui ne veut rien savoir

**Comment by TmpName** [comment]
Retesté, c'est fonctionnel.
Testé avec 24h chrono Saisons 9 ep 12.
Si tu veux jetter un oeuil sur mon fichier hosters.py > http://pastebin.com/CkiJzvZx
Mais evite le copier/coller, il y a des trucs qui ne fonctionneront pas chez toi.

Attention : je supprime les "." en debut de fichier (meme si ca nsert a rien , je sais ^^).

L'odre est important aussi, si tu teste Speedvid avant speedvideo les videos speedvideo ne marcheront pas (si tu omet l'extension)

**Comment by FreeFighter77** [comment]
ne marche pas je ne comprends pas,j ai vu que tu a resolu vk en m etant juste vkontakte ... tt ca il faudrait le consigne pour venom pour la prochaine mise a jour...
ET purevid ??? :)

**Comment by TmpName** [comment]
PureVid c'est perso, ca ne marchera pas sans abonnement ou debrideur c'est pour cela que je ne donne pas le fichier host, et en plus je passe par UrlResolver qui gere les login.

Si le lien ne s'affiche pas sans message d'erreur c'est qu'il n'est pas geré par le hosters.py

Moi je teste "videott" mais j'ai supprimé les "." toi tu devrais tester "video.tt"

**Comment by FreeFighter77** [comment]
Alors après avoir testé dans tout les sens possible la seul facon de faire fonctionner videott c comme ca (tt les autres hosters fonctionnent)  def checkHoster(self, sHosterUrl): 
 http://pastebin.com/e0pY1wnS
avec le fichier videott suivant:
http://pastebin.com/fWXvJZaU
