### ISSUE TITLE
Fenetre chargement video qui reste au dessus de la video.

### ISSUE THREAD

**Issue by madrippeur** [LordVenom/venom-xbmc-addons#106]
Bonjour,
je suis sur le dernier kodi stable, ainsi que le vstream 0.2.9. Lors du lancement d'une vidéo par vstream, la fenêtre de chargement de la vidéo se bloque à 80% (95% de temps en temps), la vidéo se lance tout de même dessous cette fenêtre mais elle ne se ferme jamais.
Au bout de quelques secondes (variables apparemment)la vidéo se coupe avec un message d'erreur : echec de la lecture d'un ou plusieurs éléments.

![kodi-vstream](https://cloud.githubusercontent.com/assets/4814664/6996643/137698d2-db94-11e4-8c83-d230b97e5d9a.jpg)

Log xbmc : http://sarah.caiveau.fr/kodi-vstream.txt

**Comment by LordVenom** [comment]
Bonjour, Je pense que tu devrais tenter un réinstaller propre de vStream. (Désinstaller , réinstaller)

**Comment by madrippeur** [comment]
Bonjour,
Avant de vous contacter, j'avais déjà tenté de désinstaller et réinstaller proprement vstream. Le problème n'étend pas résolu je vous ai contacté. Entre temps, j'ai tenté d'effacer mon dossier /home/utilisateur/kodi, mais aucun résultat.
En désespoir, j'ai fait un apt-get remove --purge kodi et fait une réinstallation. Le problème est résolu, désolé pour le dérangement du coup. En tout cas merci pour la réponse et pour la réactivité !

**Comment by LordVenom** [comment]
Merci pour le retour ça pourras aider d'autre personnes.

Bon films
