### ISSUE TITLE
Petite wishlist

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#107]
Quelques propositions d'idées, qui simplifierait la vie (du moins la mienne)

Quand on telecharge un fichier
- Coriger le nom en mettant nom_de _la_serie_Saison_episode plutot que ___video___.mp4
- memoriser le dernier repertoire pour le telechargement, ou un pour les films et un pour les videos.

Reduire la liste de liens de la page d'acceuil, en faisant des sous categories, y en a quand meme une vingtaine, et en affichant les icones, il y a trop peu de difference pour les distinger facilement.

(A suivre)

**Comment by TmpName** [comment]
Bon les deux premier point, c'est maintenant reglé.
Pour la page d’accueil, j'ai vraiment des problemes, il y a trop de liens en mode "liste" et en mode "vignette" j'ai du mal a deviner si c'est "film" ou "serie"
Y a pas moyen de faire quelque chose, une couleur d'image pour les films, et une autre pour les series, ou faire un regroupement ?

**Comment by LordVenom** [comment]
Bonjour, on peux dèja changer la couleur du texte pour chaque catégorie.System que je pense sérieusement supprimer.Grouper pk pas mais ça fait beaucoup de click pour arriver a son film.Améliorer les images pour le moment j'ai rien trouver de bien beau, mais je cherche toujours.

**Comment by TmpName** [comment]
Ca alourdi le code le systeme de couleur ? Parce que je ne sais pas si je suis le seul qui a ce probleme, mais de loin sans les couleurs c'est encore pire.

Sinon tu peux garder les memes images mais juste changer la couleur dominante.

**Comment by LordVenom** [comment]
Alourdir le code, pas vraiment mais je trouve pas ça utile.Oui pour changer la couleur par catégorie et si c'est simple changer le fanart serais pas mal aussi.

**Comment by LordVenom** [comment]
J'ai grouper les films, series, animes. Je finirais plus tard pour les fanarts y a plus cas les faires le code et ecrit.

**Comment by LordVenom** [comment]
![vstreamfanart](https://cloud.githubusercontent.com/assets/4380112/8020148/ce49df7e-0c6e-11e5-9f84-579e45ac37c9.jpg)

**Comment by TmpName** [comment]
Ha nice ^^, me tarde de voir le resultat,

Ha oui j'ai la sale habitude de foutre des couleurs au pif dans les pluggins, de faire 2/3 couleurs memorisées dans les options et reutilisée pour afficher la qualitée ou l'année ou autre (histoire d'uniformiser tout en laissant du choix), mais vu que tu penses supprimer une option semblable pour l'affichage du "home" ...

Edit:
Ou alors faire une reconvertion de code, garder le code mais au lieu de customiser les couleurs du menu "home" vu que tu pensais le virer ca servira au couleurs dans les dialogs ?

**Comment by LordVenom** [comment]
Pour le moment je vais laisser comme ça je pensé mettre des couleurs en fanart mais ça pique les yeux.Donc l'icone change toujours et l'icone du fanart aussi.dit moi ceux que t'en pense.

Pour armoniser fait plutot une fonction simple a apeller pour avoir la même couleur.

**Comment by TmpName** [comment]
Pour la fonction, j'ai commencé sur ca justement, elle repere toute seule les qualitées, ou les saisons ,et met des couleurs toutes seules sur les titres, me faut juste la developper.

Alors le regroupement nickel, du coup je ne vois plus trop l'utilité des titres en couleurs non plus. Franchement tu passes en mode vignette direct, c'est plus ergonomique. Tu distingues plus facilement si tu es sur les films ou les series.

Sinon vais faire le boulet mais tu changes le fanart sur le "home" et pas une fois que tu as selectionné "films" ou "recherche" ou "Serie", C'est fait expres ? C'est plus commode pour les autres modes que vignette, mais du coup on ne voit plus le "fan art principal" de Vstream en arrivant.

Autre chose lors de tes mise a jour tu as viré une petite mise a jour a frenchstream_org.py ou je recuperais quelques infos de plus (année,commentaires, qualitées) ca bugait, ou ralentissait ?

En tout cas, pour les modif visuelles, je prefere comme ca, c'est plus vivant, et surtout plus facile a gerer du fond du canapé si on a une vision de taupe.

**Comment by LordVenom** [comment]
J'ai renvoyer ton fichier dsl.
