### ISSUE TITLE
Comment créez votre propre liste iptv sur vstream

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#108]
bonjour ... pour créer votre list iptv avec des liens m3u ...ex, il suffit d'ajouter deux lignes sur la source freebox

URL_USER = 'https://ia601408.us.archive.org/30/items/urllist_201412/userlink.txt'

    
    oOutputParameterHandler = cOutputParameterHandler()
    oOutputParameterHandler.addParameter('siteUrl', URL_USER)
    oGui.addDir(SITE_IDENTIFIER, 'showWeb', 'User link', 'tv.png', oOutputParameterHandler)

pour avoir un lien direct il faut créer un compte sur le site american archive.org
ou vous avez la possibilité d'avoir des liens de telechargement direct en plus vous pouver les modifiers
avec les meme liens

pour tester voilla freebox.py modifier:*
http://pastebin.com/Xp3f8FFc
 je voulai mettre une liste de mes films favoris ça fonctionne jusqu'a le moment de la lecture ou ça déconne .

**Comment by LordVenom** [comment]
Bonjour il serais intéressant de créer un system qui fait ça mais en automatique.

**Comment by mino60** [comment]
il ya un system mais sur enigma2 pour userlist plugin 1channel

http://pastebin.com/wqDnXNrY
