### ISSUE TITLE
Nouvelle source (Debut)

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#109]
Bon la je fais un break pour quelques jours donc je laisse pour les motivés un debut de site.

Le site c'est cacastream, ouais je sais le nom fait pas rever, mais ils ont tout repiqué a dpstream.net, la liste de films est impressionnante.

Je n'ai fais que les films.
Recherche ok
Next page ok
Resumé ok, Nettoyé et remit en place, aucun caractere a la con dedans.
Vignette ok.

La liste de host est bridé a 100, pour lucy y a plus de 1000 host, le truc qui sert a rien.

Leur lien sont protegés, il y a la fonction pour virer la protection, elle dure 10s, c'est fait expres, les liens ne sont valides qu'au bout de 10s exactement.

> http://pastebin.com/WTj58yh2

Sinon je suis tombé sur my-free-anime.fr, 100/100 legal et sur des hebergeur qui depotent, mais la j'ai rien fais du tout.

Have fun.

**Comment by FreeFighter77** [comment]
pour cacastream je peux juste t aider avec la patern serie et manga: '<a style="font-family:Verdana, Geneva, sans-serif;font-size:10px;font-weight:bold;" href="(.+?)" class="b"(.+?)</a>'

je n'ai jamais ete dans le cas ou il y a 2 patern differentes donc peux pas t aider

**Comment by TmpName** [comment]
J'ai pas compris "2 patern differents" ?

Pour le moment je n'ai pas le temps de m y replonger dedans, je repasse juste en coup de vent pour finir les sources "officielles", d'ailleurs fullstream.me marche mieux now avec la derniere modif ? Moi il me manquait meme 50% des films, je m'en suis rendu compte en comparant avec le site.

Apres il y a rien d'urgent, j'ai mis le debut ici pour les motivés, ou pour que les debutants ait un debut de code, mais VStream tourne tres bien sans ^^.

**Comment by FreeFighter77** [comment]
fullstream.me j'ai test dans films nouveautés impeccable le compte est bon,et dans par rapport au 2 pattern je veux dire par la que cacastream ta pattern qui recupere les films dans showmovies et differentes pour les series et mangas vu qu'il n y a pas les pochettes ...

**Comment by TmpName** [comment]
ha wi, je vois le probleme, en fait je vois 2 solutions

1 - Faire tout en double dans le meme fichier showmovies pour les films et showserie pour les series
eg
SERIE_SERIES = ('http://www.cacastream.com/series-en-streaming.html', 'showSerie')

Probleme la recherche ne marche que pour 1 cas, vais voir ce qu'il est possible de faire ce WE.

2 - Faire 2 sources Cacastream_Film et Cacastream_Serie, plus de probleme mais ca rajoute des sites.

Je valide les modif de fullstream.me

**Comment by FreeFighter77** [comment]
J ai fais le necessaire pour full_stream_me,c est un gros bordel quand meme le github a comprendre ^^ J'ai vérifié a 3 fois avanr de faire la modif,veux pas faire de conneries.Pour cacastream 2 fichiers je pense non ?

**Comment by TmpName** [comment]
Donne moi 24h pour voir si Venom a prevu le truc ou pas avant, je preferais eviter d'avoir trop de sources (y en a deja trop pr moi ^^)

**Comment by FreeFighter77** [comment]
Le mieux c est d avoir peu de source mais fiable, apres ce genre de source cours pas les rues ...
Je pense qu il devrait mettre en avant la recherche visuel,que l addon fonctionne pour tt le reste dans l'ordre moviedatabase/films/et tt les liens de tout les sites. ca se serait le top

**Comment by TmpName** [comment]
Ben perso j'aime bien savoir la source, certains site gerent mieux leur lien, moins de lien mort.
Et la quand je tape le nom d'une serie, je vois de suite quels sites ont toute les saisons ou la version VF.

Bon j'avou j'ai encore jamais testé la recherche visuelle.

Sinon j'ai regardé le code de Venom et faudrait connaitre ses projets avant de continuer.

Actuellement seule la fonction showMovies est appelle pour les recherches.

Pour les recherches tu peux choisir film/serie/animé pour activer tel ou tel site mais seule la fonction showmovies fonctionnera.

Donc impossible actuellement de faire une recherche film + une recherche serie dans le meme fichier site, ou j'ai pas trouvé comment sans refaire le code de Vstream.

Le top serait de faire par fichier site une (ou plusieurs) fonction SearchXXXX et si la personne recherche dans la categorie XXXX ca utilise ce fichier site ou pas, et ca supprime du menu parametre la partie recherche.

XXXX etant serie films doc ou autre.

Je sais pas si j'ai été assez clair ....

**Comment by FreeFighter77** [comment]
Si tu peux faut parametrer les sites que tu veux pour la recherche serie par exemple.sur l icone vstream parametre extension/recherche/recherche_2(pour les series)et tu coches les sites que tu veux ...

**Comment by TmpName** [comment]
Oui mais dans le fichier site tu n'as qu'une seule fonction showmovies() comme savoir si tu veux chercher les films ou les series ?

**Comment by LordVenom** [comment]
Comment feras tu dans l'admin de l'addon pour avoir 1 recherche sur les films et 1 recherche sur les series sur la même source, faut tous refaire fait plutot 2 source une film et une serie.

**Comment by TmpName** [comment]
En fait y aurait meme plus besoin de reglage sur cette partie.

L'user selectionne "recherche" puis "serie" et Vstream passe tout les fichier site a la recherche de fonction "Showserie" si fonction presente ca marche sinon ca continu, un epu comme ca marche actuellement.

Mais le probleme justement c'est ca, y a une grosse partie du code a refaire, c'est pour ca que je voulais savoir si tu avis des projets sur ca, ou si tu etais sur autre chose.

Bon vendu, on part sur 2 sources du coup.

**Comment by mino60** [comment]
essaye ce site il ya la platforme Flashx , Aserfile en plus

http://pastebin.com/ya0cQ9uV

**Comment by TmpName** [comment]
C'est le meme site, il y a les memes films.

**Comment by TmpName** [comment]
Bon c'est bon j'ai trouvé une methode toute con pour pouvoir gerer avec 1 seul fichier Animes/Series et Films sans avoir  bidouiller le code de venom.

La personne choisit "recherche" puis "film" "serie" ou "anime" et avec 1 seul fichier on a les bon resultats testé avec cacastream
http://pastebin.com/iPBQUupq

Les films marchent a 100/100, les series affichent juste la liste des series recherchée, et les animés ne sont pas commencés du tout.

**Comment by TmpName** [comment]
Grosse mise a jour
> http://pastebin.com/TBtZP4RZ

Tout marche, film serie et manga, mais pas testé a fond.

**Comment by TmpName** [comment]
Bon j'ai perdu ma source pour kakastream, et le pastebin ne l'a plus en memoire !
Quelqu'un aurait eu la bonne idée d'en faire une copie chez lui ?

**Comment by TmpName** [comment]
Beta dispo https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/trash/cacastream_com.py
