### ISSUE TITLE
fullstream.me

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons#112]
Je cree cette issue car il manque des pochettes: (il y a la qualité que j ai rajoute dans la pattern dvdrip,screener ...)
http://pastebin.com/XyAX3mM7

je recupere les pochettes avec URL_main+aentry,mais de temps en temps il y a juste aentry tt cours
Je ne suis pas assez cale pour ca mais il faudrait indiquer a xbmc qu'il y a 2 sortes d adresse pour les pochettes:
<img src="/uploads/posts/covers/6b308982c5c43a0bb5cb1e76d921628b.jpg"
ou
<img src="http://i.imgur.com/GBVqLxi.jpg"

**Comment by TmpName** [comment]
Ha oui il y a un gros probleme ici, moi il me manque meme des films.

**Comment by arzaz** [comment]
Problème avec fullstream.me, aucun lien ne s'affiche?

**Comment by TmpName** [comment]
Le site est encore HS ^^.
Faut voir si ca dure.

**Comment by FreeFighter77** [comment]
J'ai corrigé fullstream-me sur la beta,normalement c bon (testé serie,films recherche,manga)
