### ISSUE TITLE
Les information sur les films vanoz.com

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#113]
Bonjour...

Est ce que on peut ajouter les information sur la source vanoz son metadata avec le code source de la page spécifier pour cela

exemple :
les information sur un film on utilisant metadata

http://upload-pics.org/images/98368096126357105551.png ( ici les information son en anglais )

les information sur le même film son metadata

http://upload-pics.org/images/69483617712822660773.png ( pas d'information )

les information du film sur le site vanoz.com
http://pastebin.com/rGJMervj
Le film se passe pendant la seconde guerre de Tchétchénie, en 1999. Il raconte, à échelle humaine, quatre destins que la guerre va amener à se croiser. Après l’assassinat de ses parents dans son village, un petit garçon fuit, rejoignant le flot des réfugiés. Il rencontre Carole, chargée de mission pour l’Union Européenne. Avec elle, il va doucement revenir à la vie. Parallèlement, Raïssa, sa grande sœur, le recherche activement parmi des civils en exode. De son côté, Kolia, jeune Russe de 20 ans, est enrôlé dans l’armée. Il va petit à petit basculer dans le quotidien de la guerre.

**Comment by TmpName** [comment]
Dsl, j'ai pas tout compris, me suis encore jamais servis des metadatas.

C'est pas un truc automatique, ca marche pas tout seul si activé dans les options ? Puis c'est sauvegardé non ?
Apres perso je suis pas fan d'aller recuperer les infos en direct (donc sans utiliser la fonction metadata de kodi) durant l'utilisation de vStream dans le fichier python car ca va multiplier les requetes, si c'est ce que tu veux dire.

**Comment by mino60** [comment]
je veux dire que quand j'active le metadata le resumé du film et en englais en plus l'afichage de la liste des films et trés long , ce que je veux c'est le resumé original du film sur le site vanoz son passé par le metadata c'est un peu comme l'afichage des poster

**Comment by TmpName** [comment]
Ok, donc ca c'est possible mais sur la deuxieme page, Vanoz affiche juste une liste de titre sur la premiere page. Mais ferais ca demain la je bataille encore sur github.

**Comment by TmpName** [comment]
Essaye ca http://pastebin.com/b0ZtMtuD
Ca les affichera sur le dialog ou tu choisis la qualitée

**Comment by FreeFighter77** [comment]
Impeccable par contre dans 720p il indique aussi le lien 360p
on peut ajouter aussi les categories animations,documetaires et spectacle:
http://pastebin.com/Mic6dFNg

**Comment by mino60** [comment]
Merci boucoup Tmpname ..si tu permet voila un petit corectif pour afficher la deuxième fenetre du resumé

http://pastebin.com/esZ8MAHj

**Comment by TmpName** [comment]
Merci, je viens de les rajouter sur le trucBeta.


Apres pour la double selection je l'ai laissé comme ca par flemme, explication :

La premiere fois ou tu as un dialog pour selectionner la qualitee tu as par exemple 720p et 360p
Vanoz fourni 1 nouvelle page pour chaque qualitée, dans la nouvelle page tu as le lien en 360p sur la page du 360p mais tu as encore les 2 sur celle du 720p.

Au debut je pensais cacher la qualitée non  selectionnée mais il se trouve que les valeurs ne sont pas exactes.
1ere selection 720p et 360
mais sur la page 720p tu vas avoir 720p et 400p
Du coup je prend le risque de cacher la 720p ou de voir la 400p car ce n'est plus la 360p
Et aucune garantie si je vais direct a la plus grosse qualitée pour n'afficher qu'un dialog de selection, certaines peuvent ne plus apparaitre.

Du coup j'ai laissé le double dialog de selection pour eviter les bugs.

**Comment by mino60** [comment]
TmpName merci pour l'ajout du résumé , pour la qualité noublier pas il ya sur la 2'' page de 720p la qualitée 1080p .

**Comment by TmpName** [comment]
???
Put1 je l'avais meme pas vu ca !!
