### ISSUE TITLE
Host flashx

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#114]
Bonjour

j'ai essyée de créer le host flashx mais toujour ce ce maudit message de kodi fichier introuvable?!!!

les liens flashx sur dpstreaming.org

http://pastebin.com/CuEA4yUb

http://pastebin.com/jykdehFw

**Comment by TmpName** [comment]
J y jete un oeuil de suite.
Par contre si tu as 5 mn on hesite pour le fichier hosters.py pour le host speedvideo, va jeter un oeuil sur la version beta y a une issue dessus, si tu pouvais tester celle qui est proposé sur le github pour les 2 sites en question sur une version de VStream moins bidouillée que la mienne.

**Comment by TmpName** [comment]
FlashX en place a tester sur le beta.

**Comment by FreeFighter77** [comment]
Tres beau boulot comme d ab,par contre dans lib/gui hoster de la beta tu te serais pas gourer ?
if ('playreplay' in sHosterUrl):
-            return cHosterHandler().getHoster('playreplay') 
+            return cHosterHandler().getHoster('playreplay')

**Comment by TmpName** [comment]
XD

Si, j'espere que du coup j'en ai pas oublié un autre.

**Comment by FreeFighter77** [comment]
streaminto qu'est ce que sais que cette espece :) ?

**Comment by FreeFighter77** [comment]
au passage video.tt ne fonctionne plus pour moi

**Comment by mino60** [comment]
speedvideo(beta) ne fonctionne pas le fichier du film existe mais toujour le message fichier introuvable
par contre pour speedvid je ne sai pa ou trouver les liens pour ce host.

streaminto sur urlresolver

http://pastebin.com/duX4fWbs

**Comment by TmpName** [comment]
Ha merde en fait C'est streamin.to le host est deja fait mais j'ai oublié de le mettre.
Je crois que c'est a cause de lui que j avais viré les "."

**Comment by TmpName** [comment]
Bon alors j'ai un soucis.
Pour tester speedvideo j'ai été dans streamzer.net, Fast and furious et ca a marché.
C'est ou que ce deconne mino60 ?

**Comment by mino60** [comment]
j'ai testé sur 'Les soldats de l'ombre' frenchstream.org
pour le host j'ai utilisé celui de la version beta

**Comment by TmpName** [comment]
Trouvé, merci.
Le pattern du host etait mauvais, correction sur le beta.
