### ISSUE TITLE
comment trouver le code source pour affiché les films cinemay.com

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#115]
j'ai essyé de trouver le code cinemay.com mai j ai echoué toujours

http://pastebin.com/LmNhV2kB

**Comment by FreeFighter77** [comment]
<img class=".+?" src="([^<]+)" title="(.+?)".+?<a href="(.+?)"

**Comment by mino60** [comment]
ça n'affiche pas la liste des films

spattern = '<img class=".+?" src="([^<]+)" title="(.+?)".+?<a href="(.+?)" '
