### ISSUE TITLE
corectif pour dpstreaming.org

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#116]
j'ai remarqué que la section mangas ne fonctionne pas sur la source dpstreaming.org j'ai mit un corectif pour ça ,  maintenant la page suivante afiche les hosts la troisième page mène a un lien "linkbuck" pour avoire les liens des épisodes , le probleme c'est que je peux voire que la première épisode et les autres épisode ne s'affiche pas

http://pastebin.com/PUKndBXX

**Comment by TmpName** [comment]
J'ai un epu modifier ton code (j'ai laissé manga et serie regroupé car c'est la meme methode) , celui la marche pas mal
>> http://pastebin.com/LAVq4E43

Jete un oeuil au pattern

Mais par contre je me suis arrété a la partie dl-protect car celle ci demande un capcha et il me faut faire un systeme qui demande le captcha a l'user donc cette partie est encore en attente, le reste devrait fonctionner.

Par contre comment vous faites pour tracer vos code, je ne vois jamais un "print" ?

**Comment by FreeFighter77** [comment]
Hello,sur dpstreaming.otg le probleme des mangas (ex:naruto) c est qu il y a un beau dl-protect.com ^^

**Comment by mino60** [comment]
j'ai essyée ton code mais il ne marche pas regarder celui la

http://pastebin.com/ZGBVuA1n

je ne comprends pas pourquoi je peux voire par exemple naruto shippuden la première épisode malgré la protection dl-protect

**Comment by mino60** [comment]
j'ai tester sur plusieurs video manga sur firefox , jje n'ais pas trouvé de captcha sur dl-protect!??

**Comment by TmpName** [comment]
Nope, exact. Ca y est dans le code mais il ne le demande pas. Il ne doit le faire qu'en cas de forte demandes.
Je suis en trin de chercher comment bypasser la protection, j'ai presque tout reproduis me manque plus que la valeur "i" du formulaire, mais j'arrive pas a trouver d'ou ca vient.

Apparement y'aurait une astuce en virant le "www" au debut de l'adresse mais je vois pas la difference.

**Comment by TmpName** [comment]
C'est bon, viré la protection dl-protect.

A tester, j'ai pas fini >> http://pastebin.com/hLVa2n3b

Je crois qu'il y a un decalage dans l affichage. Mais je me sauve pour today.

**Comment by TmpName** [comment]
Nouvelle correction > http://pastebin.com/5EjhfewZ

Tout devrait marcher.
Correction des caracteres a la con dans les commentaires
Correction d'un pattern supprimant des liens
Ajout d'un dialog pour la selection des hosts pour les lien dl-protect

Now les Mangas sont operationnel.

**Comment by mino60** [comment]
j'ai testé vautre modif mais les liens n'apparaît pas sur la deuxième page just streaming vf et streaming vo on rouge.

**Comment by TmpName** [comment]
XD, bon ca commence bien.
Tu as pris quel animé pour tester ?

**Comment by FreeFighter77** [comment]
J ai testé en vite fais (les mangas pas mon truc ^^) je peux te dire qu'il manque a chaque fois le premiere episode du lien dl-protect,et que quen tu stoppes une video tu reviens sur choose a link,tu clicques sur la croix pour fermer et ca crash l app vstream

**Comment by mino60** [comment]
TmpName j'ai tout les video vf vostfr et le choix entre lire la video avec Flashx.tv et Exashare appré que j'ai fais une modification sur ton fichier ( tu a fais un conflit entre serieHoster et mangaHoster et des erreurs d'entrées don la fonction showMovies...)
par contre j'ai testé sur naturo don une autre manga les liens n'apparait pas ?!!!

http://pastebin.com/DEC8xW9h

**Comment by TmpName** [comment]
Merci je mis met de suite.
La j'ai un gros probleme avec le code recupéré, des caracteres qui vont bugger le pattern, visible sur "serie " "Revenge – Saison 4"

**Comment by TmpName** [comment]
Bon nouvelle source a tester, mais la je pense que c'est bon >> http://pastebin.com/hFb73Ze7

En fait j'ai supprime la partie mangahoster vu que j'utilise la meme pour les mange et les series, je pense meme a fusionner seriehoster et hostertout court car ca deconne encore quand il n 'y a qu'un seul oav comme manga (et oui c'est gere comme un film pas comme une serie ou un animé.

**Comment by TmpName** [comment]
Bon y aura deja une nouvelle modif.
Pour limiter la taille du titre l'expression "Episode : ? (nombre total inconnu)" a été pris en compte dans ghost in the shell,, ca devrait passer en limitant cette chaine dans le pattern.

**Comment by mino60** [comment]
dpstreaming tout marche manga et series mais avec double titre sur la meme video

http://pastebin.com/EMpW3XRr

**Comment by TmpName** [comment]
J'ai pas compris le bug que tu as vu ?
Ton fichier est trop eloigné du mien j'ai pas trouvé la modif que tu as faite pour le corriger.
