### ISSUE TITLE
Plusieurs soucis

### ISSUE THREAD

**Issue by bobynou** [LordVenom/venom-xbmc-addons#118]
Bonjour,

-Telecharger-films.ws ne fonctionne pas (erreur script)
-Fullstream.me la recherche ne fonctionne pas (dossier vide à chaque fois)
-Marque page ne fonctionne pas avec la v0.2.9 je n'ai plus la fonction pour marqué dans film ou série....! Et tout ceux que j'avais marqués avant ont disparus. 

Merci

**Comment by FreeFighter77** [comment]
Bonjour bobynou,pour films-ws c'est normal le site n existe plus,pour le marque page venom est au courant.Tout ça sera réglé dans la prochaine mise a jour.

**Comment by FreeFighter77** [comment]
Par contre pour fulstream.me j'ai constaté le probleme aussi
