### ISSUE TITLE
Freemoviz.com

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#119]
je voulais créer cette source ( freemoviz.com ) mais malheureusement je reste toujour bloqué sur sPattern

http://pastebin.com/1mqaq6yC

**Comment by TmpName** [comment]
Pour trouver plus facilement tu copie le code source du site ou la partie qui t'interesse dans un site comme ceux la
https://regex101.com/
http://www.regexr.com/
http://pythex.org/

Le dernier gere dotall ca aidera en cas de saut de ligne.
