### ISSUE TITLE
Zdstream

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#120]
Zdstream.org toujour problème pour affiché les poster... voila le fichier de cette source

affichage des films...................    ok
afichage des series..................    ok
next page.................................    ok
affichage des hosts..................    ok
poster.......................................    no
streaming.................................    ok

http://pastebin.com/iKfAaa3r

**Comment by TmpName** [comment]
En fait leurs images sont protegeés, il faut se demerder pour que kodi envois en meme temps un Referer = 'http://zdstream.org/' pour faire croire que la requete vient de leur site.

**Comment by mino60** [comment]
désolé j'ai pas compris ce que tu veux dire

**Comment by LordVenom** [comment]
oRequestHandler = cRequestHandler(sUrl)
      oRequestHandler.addHeaderEntry('Referer', 'http://www.google.com/')
      sHtmlContent = oRequestHandler.request();

**Comment by TmpName** [comment]
Ou plus simple en rajoutant "|Referer=http://zdstream.org/"
Teste ca http://pastebin.com/9rHjjxtE

Je sais pas pkoi les gens perdent autant de temps a pourrir leur site de protections a 10 balles, ca fait chier tout le monde et ca sert a rien. Ils ont juste qu'a garder leur site en local.

Bon ceci dis je galere encore pr dl-protect.....

**Comment by TmpName** [comment]
Il n 'y est pas sur la beta celui la, il est pas encore fini ?

**Comment by mino60** [comment]
oui effict effectivement j'ai un probleme pour le host netu

**Comment by arzaz** [comment]
Bonjour mino60,

Tu peux rajouter la source dans la beta?
