### ISSUE TITLE
Replay TV

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons#121]
Bon a force les divers site de films et series,je pense qu on a fait le tour. J ai commencé a faire ce site qui je pense peux enrichir vstream (replay TV).c'est vraiment le début un peu brouillon diras t'on ! ;)
-recuperation pochette,url,nom ok
-bouton next page ok
http://pastebin.com/ph87L4Np
Le pb c pour les hosters,je suis pas assez calé ^^,et également pour créer les mêmes catégories que sur le sites (telerealites,divertissement...) Apres je fais apparaitre le site dans series et films,je pense que venom une fois tt bien fais peu le mettre dans television ou créer un liens replay ...

**Comment by FreeFighter77** [comment]
Bon j ai bien avancé les hosters fonctionnent reste plus qu'a creer des genres ...
http://pastebin.com/W46ipdmF#

**Comment by spmjc** [comment]
Je viens de decouvrir le pluging vstream et il est top, je vais aussi poster des suggestions.
Je pense qu'il vaut mieux separer les foctionalites, mais c'est au developpeur de decider..

Je travaille sur un plugin de replay (le git est pas a jour) mais tu peux le trouver ici:
http://passion-xbmc.org/add-ons-video/freplay-french-replay/

**Comment by FreeFighter77** [comment]
Bon pour creer les categories je seche,je pense c du a l histoire tag et des espaces dans l'url, need help ^^

**Comment by TmpName** [comment]
@spmjc
Salut, je me sert egalement de Fr-Replay mais chez moi la derniere mise a jour date du 10 avril 2015, on parle bien du meme ? 

Sinon par contre completement abandonné il y a le pluggin "livestreampro" (c'est pas lui qui est abandonné ^^) configuré avec le fichier lescigalesmachintruc > http://forum.kodi.tv/showthread.php?tid=207746.
Extremement avancé et facile a modifier (juste un fichier xml a editer), mais je crois qu'on a perdu la trace de l'auteur ??

Sinon perso je pense comme toi, il vaut mieux separer le stream du replay/direct, pas la peine de sortir une usine a gaz.

Si tu as besoin d'un coup de main, je suis plutot pas mauvais pour recuperer des flux sur des sites ou le webmaster essaye de compliquer la tache de recuperation, si tu as un site compliqué ca peux m'interesser.

**Comment by spmjc** [comment]
Oui ca doit etre la derniere version. Elle date pas de si longtemps!! :)

J'ai contacte captvty, pour voir si ils veulent partager les connaissances, on verra.

Pour les chaines a ajouter, si tu aimes les defis... M6?

Je me suis essaye aux regex hier pour sujet dnas pargraphe suivant, donc je comprends mieux comment ca marche et j'essaierai d'integrer d'autres chaines qui n'ont pas d'API. (Ma MAJ Android ne me permet plus de faire tourner l'outil que j'aimais bien pour faire du wireshark.. :( )

Je voulais ajouter sokrostream a freplay, donc je piochais du code chez feu mashup.
Et j'ai decouvert vstream. Donc ca ne valait plus le coup d'ajouter le code dans mon projet.
Je m'essaierai a vstream en ajoutant sokrostream.
Meme sis ce n'est pas la fonctionalite que j'aimerai voir (cf mon autre post), ca m'aidera a mieux integrer le projet.

**Comment by FreeFighter77** [comment]
tmp le pb est le suivant,je voulais classer par genre infos,telerealités ... comme sur le site,mais j'ai fais un essaye
http://pastebin.com/ysr8e7ZW
reportages fonctionne mais pas l'ile des verités (j ai pris au pif hein !! ;) je pense que ca viens des espaces dans l'url du premier (%20) donc je ne sais pas quoi faire.De plus sur le sites ca donne 
INFOS ET MAGAZINES=special investigation,sept a 8,reporatges ....

**Comment by TmpName** [comment]
Dsl me suis loupé hier, en ce moment je bosse h24 donc j'ai pas trop les idées claire je voulais parler de replay pas de direct en fait c'etait de "francetv pluzz" que je voulais parler.

Pour moi la fonction replay comme la fonction direct merite un addon complet, chacun gerant son projet a sa maniere. L'interface, la maintenance, la maniere de gerer les services, ect ... ne sont pas pareil pour des listes de films que des direct ou des replays.

Sinon pour M6 ca ne doit pas etre compliqué.
 1 - j'ai été sur la page http://www.m6.fr/emission-les_reines_du_shopping/videos/11477336-le_defile_de_melanie.html
2 - dans le code tu trouves <iframe src="//player.m6web.fr/v1/player/v3_m6/11477336.html
3 - dans le code de cette page tu trouves  http:\/\/lb.cdn.m6web.fr\/p\/c\/1\/5c42df77b6686be5236df3a68979140d\/552fca31\/u\/videonum\/lesreinesdushop\/lesreinesdushop__Rendez-vous-gal__20150414__552d46a273a89_hq.mp4
4 - en envoyant une requete a ce lien en GET mode tu recois une redirection avec en location un lien direct http://e202.cdn.m6web.fr/u/videonum/lesreinesdushop/lesreinesdushop__Rendez-vous-gal__20150414__552d46a273a89_hq.mp4/26c44a0ff8c2ce33c988da683ef3c20b/552fca31

Marche sans cookies, surement sans java

**Comment by spmjc** [comment]
Ça a l'air d'être une des vidéos bonus.
Ce sont les intégrales qui posent problème..
Mais je vais regarder la piste ;) merci

**Comment by TmpName** [comment]
Ha ouais c'est les petites, je vais voir pr les integrales

**Comment by spmjc** [comment]
Ca serait super si tu arrives a le decoincer..
Et ca voudrait dire M6 + W9 + 6Ter +... 
C'est un probleme de DRM surtout.

Le lien vers le catalogue M6.
Pour demarrer
http://static.m6replay.fr/catalog/m6group_ipad/m6replay/catalogue.xml

(je ne trouve plus le reste, dsl)

**Comment by TmpName** [comment]
He beh ce sera pas pr ce soir ^^.
C'est hallucinant le traffic de fou, tu as des redirections toute les 4/5s, le fichier est en petits bout dans un m3u, la moitié des requetes je vois meme pas a quoi elle servent, et j'ai pas encore trouvé de lien non codé. Je sent que ca va m'occuper ce Week End.

Mais c'est des malades, juste pr proteger une pauvre emission TV ....

Rien a voir avec les petites videos, je te tient au courant si j'arrive deja au fichier m3u proprement.

**Comment by spmjc** [comment]
Je vais essaye de t'envoyer des infos. Je regarde de mon cote avant.
J'arrivais au fichier hls a l'epoque..

**Comment by spmjc** [comment]
J'ai retrouve mon fichier pcap de l'annee derniere..
Il me manque encore des infos, mais une bonne partie est retrouvee.

1 Catalogue
http://static.m6replay.fr/catalog/m6group_ipad/m6replay/catalogue.xml
2 Liste des videos par programmes
http://static.m6replay.fr/catalog/m6group_androidmob/m6replay/program/getvideos-1857.xml
(id est dans catalogue : <pgmListItem t="a" id="1857">)
3 Manquant..

4 Lien video (j'avais garder celui de l'epoque)
http://vod-and.llnw.cdn.m6web.fr/phls-vod/Bones_c11359058_Saison-9-episode-11_600k.mp4.m3u8

Ce sont des HLS cryptes.
J'ai lu recemment que Kodi savait gerer si on avait la cle de decryptage
Je viens de voir ces 2 requetes GET, qui pourraient aider.. ou pas :)
http://time.6cloud.fr/
http://auth.estat.com/240040208132 (Theoriquement c'est mediametrie)

Je vais essayer de retrouver comment on passe de etape 2 a 4 :)

**Comment by TmpName** [comment]
@FreeFighter77 
Essaye ca http://pastebin.com/fixLEbd7

Cela marche comme ca, mais il faudrait utiliser la fonction en commentaire, seulement celle ci fonctionne sans le host (sinon elle change aussi le ":" dans http:// et du coup ca marche pas)

**Comment by TmpName** [comment]
@spmjc 
Bon je laisse tomber pr le moment je cherche la meme chose que toi, d'ou vient le nom du fichier m3u8 pour que le client puisse faire la requete, ca fait 1 h que je me defonce les yeux a lire les packets, et rien.
A chaque fois que le serveur prononce le mot "m3u8" le client avait deja le nom complet.

Me faudrait refaire un test en eteignant le max d'appli utilisant le reseau, mais la ca pique ...

**Comment by spmjc** [comment]
Alors...

1-http://static.m6replay.fr/catalog/m6group_ipad/m6replay/catalogue.xml
(j'ai selectionne un telefilm)
Tu trouves le code 11338400

2 Tu continues sur la page
http://static.m6replay.fr/catalog/m6group_web/m6replay/clip/00/84/clip_infos-11338400.json (00/84.. 00 et 84 sont repetes ;) )
Il y a des liens hdl et hls...

**Comment by TmpName** [comment]
Ben ca ressemble a mes liens pour jingles et pubs, tu en a regardé un pour voir si c'etait un vrai flux pour une emission complete ?

Moi les liens que je recherche ressemble plutot a http://lb.cdn.m6web.fr/s/cu/prime/vod/protected/3/e/e/Les-Reines-du-Shopp_c11338548_Ronde-sexy-et-s/Les-Reines-du-Shopp_c11338548_Ronde-sexy-et-s_800k.mp4.m3u8.

L'id "11338548" correspond bien a une emmision "reines du shopping" mais pour le reste j'aimerais bien trouver d'ou viennent les parametres, il y a forcement a un moment les params "3" ou "e" qui devrait apparaitre quelque part.

**Comment by TmpName** [comment]
Bon je lache l'affaire, pas assez de connaissances.
Autant les pub et le jingle aucun probleme, autant l'emmision quedale, je recupere de tout (fichier (mp2t,m3ua, ...) mais j'arrive pas a lancer le moindre morceaux de fichier avec aucun lecteur.

**Comment by spmjc** [comment]
haha. Merci d'avoir essayer.

De ton cote tu avais fait quoi? un wireshark sur le site web de M6 depuis ton PC?

**Comment by FreeFighter77** [comment]
TmpName j ai teste ton truc pour les genres avec l adresse qui a des espaces,mais marche pas ...

**Comment by TmpName** [comment]
Yep, mais en fait les outils de base de firefox (firebug/httpfox/Tamper data) aurait suffit dans mon cas.

Il y a beacoup trop de "discutions" sur wireshark sur ce site, je ne sais pas du tout comment fonctionne ce type de media, mais toutes les requetes sont redirigées et le fichier est vraiment trop morcelé.

Sur wireshark, sans savoir ce que tu cherches ce n'est vraiment pas la peine, faudrait trouver un site/tutorial de quelqu'un ayant deja reussi a lire ce type de media, moi perso je nage completement.

**Comment by FreeFighter77** [comment]
Impeccable merci TmpName ;) une derniere question comment creer une sous liste ?

**Comment by TmpName** [comment]
Il y a des exemples deja fait, perso je suis pas sur a 100/100 de faire ca proprement vu que j'utilise les fonctions de Venom sans meme savoir comment elle fonctionnent.

Tu as par exemples "showmovies" qui amene a "showSerie" qui amene a "showepisode" pour un des sites

**Comment by TmpName** [comment]
@spmjc 
Je viens de tomber par hazard sur un truc peut etre utile, l'addon pour netflix utilise aussi les DRM et pour cela il utiliserait "Chrome Launcher" pour le video playback.

**Comment by TmpName** [comment]
@FreeFighter77 Je sais pas ou tu en etais de ta source, mais je l'ai continué par la https://github.com/LordVenom/venom-xbmc-addons/issues/181
