### ISSUE TITLE
Site de streaming Fullmoviz.org

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#122]
Bonjour ...

je voullé créer cette source fullmoviz.org contient plusieurs possibilitées pour lire les films multi-hosts, mais j'ai pas trouvé le pattern exact pour afficher les films
le site fullmoviz.org.py

http://pastebin.com/cCEqM1Dv

**Comment by FreeFighter77** [comment]
Bonjour mino ce site est déjà dans vstream ;) (fullmoviz_org),cela dit tu peux comparer ta pattern avec le fichier du site pour voir ton erreur ...

**Comment by mino60** [comment]
A oui!!!..mon vstream c'est un champ d'essai sur le terrain je l'ai supprimer son me rendre compte !!!
