### ISSUE TITLE
Fonctionalite du plugin Genesis que je recomende d'integrer

### ISSUE THREAD

**Issue by spmjc** [LordVenom/venom-xbmc-addons#123]
J'utilise Genesis depuis quelques temps et le plugin est vraiment bien.
J'ai decouvert le tien hier qui me semble excellent pour les sites francais.
En plus ton code est super lisible!! ca fait plaisir.

Bref, il pourrait etre interessant d'ajouter 

-une fonction "AutoPlay": Passes les sources dispo en revue et essaie de les lire, si cela ne fonctionne pas, on passe a la suivante.
-Integration Trakt: Marquer les videos comme lues. Afichage des episodes de series non vues mais diffuses..

Je peux aider aussi. J'ai un peu d'experience sur les dev XBMC

**Comment by TmpName** [comment]
Il y a actuellement un bug sur le "marquage" qui sera corrigé a la prochaine version, si tu veux filer un coup de main il y a une version beta de l'addon ou on peut se defouler pr les test https://github.com/LordVenom/venom-xbmc-addons-beta
