### ISSUE TITLE
Nouvelle source Lopav... 

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#124]
Bonjour....

depuis hier le site vanoz.com ne marche plus vous pouvez trouver tout les films sur le site similaire Lopav.com
remarque : il manque next page et la fonction recherche

http://pastebin.com/PfWXjKCF

Poploz

http://pastebin.com/VvPng8PE

**Comment by mino60** [comment]
sur le sit vanoz.com ;

Le site est en maintenance suite a une attaque qui s'est deroule hier a 1h du matin, Retour de Vanoz encore plus puissant a 20h00

**Comment by mino60** [comment]
Bonjour , je voulais ajouter les numero cote a cote avec les titres des films
 sur la section genre mai je nais pas parvenu 

    else :
        oInputParameterHandler = cInputParameterHandler()
        sUrl = oInputParameterHandler.getValue('siteUrl')
        
        if (sUrl == 'http://www.poploz.com/dco/') :
            sPattern = '<a href="(.+?)" class="latestnews">(\t|\n)+(.+?)<.a>'            
        else:
            sPattern = '<td headers="count">[0-9]+<.td>(\t|\n)+<td headers="tableOrdering">(\t|\n)+<a href="(.+?)>(\t|\n)+(.+?)<.a>'

**Comment by TmpName** [comment]
Tu aurait un lien sur la page en question ?
Je trouve pas "<td headers="count">" sur le site de poploz

**Comment by mino60** [comment]
oui le voila ; http://www.poploz.com/dco/index.php?option=com_content&view=category&id=1:action-&Itemid=6&layout=default

sur dpstreaming j'ai testé ton fichier sur naruto les lien n'apparait pas voila ton fichier py :
http://pastebin.com/SyQAA5Vj

on revanche voila mon fichier mai avec 2 fonction (showSeries, showManga) j'ai les lien sur la video naruto vf vostfr les series avec 2 titre a chaque video

http://pastebin.com/EMpW3XRr

**Comment by TmpName** [comment]
Houla, j etais sur la source mangacity.org, je viens juste de voir le post mais la je dois repartir bosser, je regarde ca demain, te dit tout ca demain.

**Comment by mino60** [comment]
désolé j'ai retesté ton fichier  il n'a pas mal du tout , quelque mangas il n'ya pas des lien je croix qu'il manque cette ligne don la pattern


<div align="center"><span style="color: #000000;">.</span></div>

**Comment by arzaz** [comment]
Vanoz change de nom et devient Poypi.
Est-il possible de rajouter cette source sur la beta.

**Comment by arzaz** [comment]
Bonjour mino60,
Je ne trouve toujours pas la source zdstream sur la beta?
Est-il possible de la rajouter stp.

**Comment by mino60** [comment]
non vanoz.com le site a était attaqué le 15 avril 2015 à 01h
le retour de vanoz aujourd'hui 17 avril 2015 avant 23h
zdstream je l'ai mit sur beta mais elle n'ai pas encore sur master tu peux la trouver sur dossier trach sur beta.

**Comment by arzaz** [comment]
mino60,
Essai d'accéder sur vanoz.com, tu seras redirigé directement sur poypi.com

**Comment by mino60** [comment]
Vanoz est en maintenance, nous allons prendre un peu plus de temps que prévu avant de remettre le site en ligne. Nous en sommes désole. Merci de votre fidélité. Retour de Vanoz le 17 avril avant 23h.

**Comment by arzaz** [comment]
mino60, ou se trouve le dossier trach sur beta?

**Comment by arzaz** [comment]
moi quand j'accede au site vanoz.com je suis automatiquement redirigé a la page http://www.drepmobil.com/, puis http://www.poypi.com/rgc/

**Comment by mino60** [comment]
moi non j'ai ce message : 
Vanoz est en maintenance, nous allons prendre un peu plus de temps que prévu avant de remettre le site en ligne. Nous en sommes désole. Merci de votre fidélité. Retour de Vanoz le 17 avril avant 23h.

**Comment by arzaz** [comment]
Je n'arrive pas a trouver le dossier trach sur beta, merci de me guider stp.

**Comment by TmpName** [comment]
https://github.com/LordVenom/venom-xbmc-addons-beta/tree/master/plugin.video.vstream/resources/sites/trash

**Comment by arzaz** [comment]
Merci TmpName

**Comment by TmpName** [comment]
@mino60 
Pour le lien "suivant" sur popoz c'est facile il suffit de recuperer le lien du lien appelle "suivant" c'est le cas le plus facile http://pastebin.com/CU4Jxahd

>> je voulais ajouter les numero cote a cote avec les titres des films
sur la section genre
Pourquoi tu te prend la tete avec ca, ca va te servir a quoi, laisse comme c'est, c'est parfait.

zdstream.org et HS en ce moment je regarderais plus tard.

Je corrige dpstreaming et je le met sur le beta ce soir, merci.

**Comment by mino60** [comment]
voila l'alternative de la source vanoz qui ce nome poploz tout et parfait just la fonction recherche
http://pastebin.com/fTz0hGGu

**Comment by TmpName** [comment]
Avec la recherche http://pastebin.com/HcF4xWGz
Sinon les pattern pour les regex sont a simplifier
Vire les tabulations du code html avec replace('\t','') et supprime tout les '\t' des Regex.

**Comment by mino60** [comment]
désolé mais rien ne marche avec ton code , j'ai pas comprie pour quoi je doit supprimer '/t' du pattern

**Comment by TmpName** [comment]
C'est quoi rien ? Chez moi j'ai les nouveautées, les genres, la recherche et j'ai meme lancé une video.
Si tu as testé mon code, tu as du voir un decalage dans les titres, c'est a causes des tabulations, et le plus simple c'est de les virer des le debut, ca simplifit les regex, mais il faut les virer du code html aussi pas juste de la regex.

**Comment by mino60** [comment]
j'ai toujour le message "erreur script" si vous pouvez mettre un autre lien pour le fichier et merci

**Comment by TmpName** [comment]
J'ai resteté, pas de soucis, tu prend bien l'integralité du script, pas juste la partie recherche ?
Et la partie ' RAW Paste Data ' ?

**Comment by mino60** [comment]
re TmpName est ce que la fonction recherche fonctionne avec toi ?!!

**Comment by TmpName** [comment]
Pour poploz, oui, c'etait d'ailleurs le but de la derniere version que j'ai donné.
