### ISSUE TITLE
vstream et enigma2

### ISSUE THREAD

**Issue by samkooke** [LordVenom/venom-xbmc-addons#125]
bonjour mino utilise tu vstream sur enigma2 car moi ca ne fonctionne plus et comment par tsmedia ou kodidirect merci.

**Comment by mino60** [comment]
Bonjour ...non car l'affichage des films hosters est trés long avec la version 0.2.1 tu peux utiliser TSmedia 9.2 il y'a c'est plus rapide 
vstream sur enigma2 fonctionne avec la version 0.2.1 instalation TSmedia et kodi obligatoire
regarder ici :
http://www.dzsat.org/forum/f437/tuto-comment-rajouter-des-liens-iptv-sur-enigma-2-avec-dreamboxedit-388643.html

**Comment by samkooke** [comment]
bonsoir merci .
