### ISSUE TITLE
3 meilleurs sites de streaming

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#128]
1/ http://www.streamiz-filmze.net/
2/ http://www.streamingvfr.com/
3/ http://www.filmstreaming2015.com/

**Comment by TmpName** [comment]
Mouais faut se mefier de leur top a la con. Moi perso pour voir si c'est un bon site je teste
1 - un vieux film mais culte comme "blade runner"
2 - un film rare comme "interstella 555"
3 - le nombre d'herbergeurs proposé par film , et lequels (youwatch ca vaut rien)

Tout les 15 jours y a un nouveau site qui sort avec rien de plus que les precedents.

**Comment by xavierposlo** [comment]
http://www.streampremiere.com/ Peut être un des meilleurs sites pour regarder des films en français. Streampremiere restera un trés bon site pour longtemps! Regardez tout vos films et séries ici sans limite. Parfois l'accès est un peu lent - Mais un très très bon site de streaming gratuit!

**Comment by TmpName** [comment]
1 Seul hebergeur, meme pas 200 films au catalogue et fait sauter mon anti virus dans tout les sens.
