### ISSUE TITLE
Nouvelle source, Mangacity.org

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#130]
Ici > http://pastebin.com/dymW4GZE

Alors on oublis pr les films et serie, trop a la masse.
Site inutilisable sans adblock
Par contre niveau animes propose 2 hosters pour des series qui n'en ont qu'un en general.

Juste un probleme, il y a une protection cloudflare sur leur serveur, peut etre desactivé ATM.
En fait si il y a trop de requetes, le serveur redirige sur une page pour verifier si on est pas un robot, je n'ai eu cette page qu'une fois, et je n'ai pas eu le temps de stopper le navigateur (ca prend 4/5s), donc je n'ai pas pu recuperer le code.
Si quelqu'un est soudainement bloqué, il y a dans le code une partie a reactiver, pour creer un log a me faire passer. Mais si il retourne sur le site via navigateur, c'est foutu, la protection est virée.

Pas encore sur le beta,

**Comment by TmpName** [comment]
Update > http://pastebin.com/4HbSDxS0

**Comment by LordVenom** [comment]
Ajouter a la bêta mais il reste du boulot dessus.

**Comment by TmpName** [comment]
Ben y a encore des tests a faire, mais tu as vu quoi comme boulot a faire ?

De memoire il manque juste le resumé, virer le code inutile, et beacoup de tests, m'en sert souvent et je trouve regulierement des animes n'apparaissant pas a cause de leurs protections a dix balles.
