### ISSUE TITLE
AsThumb

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#131]
Est ce que en peux ajouté la fonction AsThumb sur vstream cette fonction utilisé par mediaportal pluguin enigma2 , comme une option on peux la activer ou d'ésactiver avec l'outie des parametres de system

voila le fichier pour enigma2 :

showAsThumb.py

http://pastebin.com/Lvg9LaXb

image 

![1_0_1_200b_430_1_c00000_0_0_0](https://cloud.githubusercontent.com/assets/11494048/7217397/97651724-e628-11e4-98d1-409036d16895.jpg)

**Comment by LordVenom** [comment]
Bonjour, j'ai bien peur que cette function mette le bazars pour les autres utilisateur, je ne sais pas a quoi ça sers et les import ne me parle même pas. 
Pour le moment non, si par contre tu t'y connais asse je t'invite a tester sur la bêta. Si ça tourne et que l'ors des tests rien ne me choque elle seras dans une mise a jour.
