### ISSUE TITLE
site pour streaming hd "papystreaming.com"

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#134]
Bonjour papystreaming.com connu comme l'un des meilleur site du streaming hd multi hosters
plus 10 liens du streaming

http://streamfilm.fr/

le streaming sur ce site n'ai pas disponible pour certain pays?

**Comment by TmpName** [comment]
C'est pas plutot http://papystreaming.com ?
Sinon wé, je confirme, il vaut le coup d oeuil ton site.

**Comment by TmpName** [comment]
Par contre, j'ai trouvé comment recuperer les liens des videos mais ou sont elles hebergées ?
A certain moment j'ai eu un "temps limite de 30mn depassé" et a d'autres moment rien, cacaoweb fonctionne comme un proxy vers d'autres hebergeurs ?

**Comment by TmpName** [comment]
Personne a plus d'infos ?
Bridé au bout de 2 h (si c'est ca ca vaut le coup de le garder)
Abonnement de moins de 5 Euros (Y en a qui peuvent le vouloir du coup, vu le nbre de source)

Pour le peu que j'en vois, le bridage est nouveau et pas au point.

**Comment by samkooke** [comment]
bonjour mino je l'avais dit a Mfaraj de le rajouter a tsmedia il ma repondue que c'etais pas possible.
