### ISSUE TITLE
cacaoweb

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#135]
cacaoweb est une application révolutionnaire pour communiquer et échanger avec d'autres, regarder des vidéos en ligne, partager, organiser et rechercher ...

http://127.0.0.1:4001/#/fr

**Comment by TmpName** [comment]
Ben justement papystreaming passe par eux, et j'ai des question sur ca justement https://github.com/LordVenom/venom-xbmc-addons/issues/134

Par contre fais gaffe, tu peux obtenir leurs films sans installer leur appli, et il y a beacoup de doutes sur ce que bricole leur appli sur ton PC une fois installé.

**Comment by mino60** [comment]
j'ai besoin d'aide pour la pattern fifostream.tv qui ressemble à cacastream mais avec plus de hosters ( nowvideo , novamov videoweed, videonan, laravid, duckdtreaming, youtube...

http://pastebin.com/W3Z0JRtV

**Comment by mino60** [comment]
j'ai trouver se site qui a la fonction dibridage ; http://www.enstreaming.com/

**Comment by TmpName** [comment]
Pr fifostream, il y a deja quelqu'un qui en a parlé, mais ce site est tjours fermé, je n'ai encore jamais pu le voir en fonctionnement.

**Comment by mino60** [comment]
Bonjour ...non fifostream ce site marche depuis long temps voila le lien

http://www.fifostream.tv/films.html

**Comment by TmpName** [comment]
???
Moi j'ai droit a adresse introuvable !!
Faut que j'essaye avec un autre navigateur.

**Comment by TmpName** [comment]
Bon en fait mon FAI bloque via DNS, y a un moyen de contourner ca via python de maniere invisible mais pour ceux qui utilisent ce site, est ce que cela en vaut la peine ?

Je trouve pas plus de site que sur cacastream ou dpstream.net, 3 hebergeurs par films en general, 1 seul gratuit a chaque fois et le pire : youwatch.

**Comment by bobynou** [comment]
Salut,

Je suis en france et fifostream.tv, fonctionne chez moi. Sinon pour des liens  pour "taken 3" par exemple, il en propose 466 différents.
