### ISSUE TITLE
fonction _create_tables(self):

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#138]
def _create_tables(self):

D'apres le code cette fonction ne sert que a creer les tables de base si inexistantes pour Favoris/historique/vu/ect ...

Mais cette fonction est appellée des dizaines de fois a chaque mouvement, et en cas de recherche groupé une centaine de fois sans probleme.

Ne l'appeller qu'une seule fois au demarrage de l'addon ne serait pas suffisant ?

**Comment by LordVenom** [comment]
Si tu voie comment solutionner le problème tu est libre de changer, sinon je regarderais pas fait gaffe.

**Comment by LordVenom** [comment]
Résolut
