### ISSUE TITLE
Posters avec Version 0.3.0

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#139]
Bonjour LordVenom,

Merci pour cette nouvelle version, mais j'ai remarqué que le problème de récupération des posters n'est toujours pas résolu?
Pour info, quand je change Poster size de W342 a W92, je récupère pas mal de posters mais de mauvaises qualités?
Ce problème a réapparu depuis la version 0.2.9
J'espère que ce problème sera fixé lors de la prochaine version.

**Comment by LordVenom** [comment]
Bonjour, Je ne comprend pas l'erreur pouvez vous être plus precis ? merci

**Comment by arzaz** [comment]
Bonjour LordVenom,

Je m'explique, 
Exemple --> Films Nouveautés --> FrenchStream.org --> Good Kill (sans poster) - You're Not You (avec poster) - Badge of Fury (avec poster) - Batman Unlimited (sans poster)......etc
Quand je change les parametres de Vstream --> General --> Parametres des Metadonnés --> TMDB (Movies) --> Poster Size "Actuellement il est a w342" et quand je change a "w92" surprise les posters des films Good Kill et Batman Unlimited s'affichent mais la qualité des vignettes sont médiocres.

J'espère que c'est claire maintenant.

**Comment by LordVenom** [comment]
Bonjour, Je suis dsl mais chez moi aucun soucis effectivement en w92 les poster sont moche mais c'est du à la qualité choisis.En w342 aucun soucis.
