### ISSUE TITLE
Installation Vstream

### ISSUE THREAD

**Issue by DeathRdr** [LordVenom/venom-xbmc-addons#14]
Bonjour,
J'ai téléchargé et installé XBMC sans problèmes, mais lorsque je j'ajoute vstream à partir du fichier zip; je me rends sur vidéos, extensions, v stream et rien ne se passe, juste un message d'erreur qui me dit :  Echec, erreur du script: vstream.
Y a t'il une solution ?
Cordialement, 

DeathRdr

**Comment by menad88** [comment]
Bonjour, 
j'ai installé vstream sur mon android et sur mon pc (win7). quand je me connecte avec ma connexion 3g, tout marche à merveille. Mais avec ma connexion ADSL, il me dit Vstream Failed ... un truc comme ça. j'arrive pas à comprendre.
Pourriez-vous m'aider S.V.P !!!!!!
