### ISSUE TITLE
Correctif Streaming_series.org

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#140]
bonsoir  

la source streamingseries.org problème avec showhosters le correctif 

http://pastebin.com/Cqy51B89

**Comment by TmpName** [comment]
J'ai essayé de mettre a jour le fichier, mais ta source est trop vielle, il y a trop de difference avec le fichier mit sur la beta.
Essaye la version sur le beta, a mon avis il y a le meme bug, je vois que quelqu'un a mit la bonne ligne en commentaire, mais je sais pas si ca marche.

**Comment by TmpName** [comment]
ok je pense que c'est le meme prb que https://github.com/LordVenom/venom-xbmc-addons/issues/141

**Comment by FreeFighter77** [comment]
Pr streaming series t en a trop supprimé ;)

**Comment by TmpName** [comment]
C'est la version de la beta, j'ai juste viré 5/6 lignes qui viennent d'un copier/coller raté a mon avis, pkoi j'aurais du laisser quoi ?

**Comment by FreeFighter77** [comment]
Non c bon,mais question pourquoi le site apparait uniquement dans toute les sources et pas dans series nouveautés ...

**Comment by TmpName** [comment]
Il a pas du etre rajouté dans le fichier xml

**Comment by LordVenom** [comment]
C'est écrit dans ajouter_source.py

SERIE_SERIES = 'http://url' # serie nouveautés #30106
SERIE_VFS = 'http://url' # serie VF #30107
SERIE_VOSTFRS = 'http://url' # serie Vostfr #30108

Pas les bon nom de variable. J'ai corriger.
