### ISSUE TITLE
[VSTREAM] BLOQUE A 97%

### ISSUE THREAD

**Issue by dpcinfo** [LordVenom/venom-xbmc-addons#142]
Bonjour, tout d’abord merci Venom pour cette extension génial 😉

Par contre j’ai un problème assez gênant, quand je lance un flux, le flux se lance bien mais jai une petite fenêtre en superposition qui m’indique « VSTREAM -97% ouverture du Flux » et si je clique sur annuler le flux se coupe :( une idée ?
Ca me le fais aussi bien sur le rasbpery py2 que sur Kodi pour IPad, a l’exception que sur iPad il bloque à 83%. Ce qui est bizarre c’est que le flux est Hyper fluide

**Comment by TmpName** [comment]
Tu n'es pas le premier a avoir ce probleme
https://github.com/LordVenom/venom-xbmc-addons/issues/80

A chaque fois il a recu comme conseil de reinstaller le pluggin, et la personne n'est jamais revenue.
Donc soit ca marche, soit il a laissé tomber.

**Comment by lorenzo06974** [comment]
bonjour, je viens vers vous car j'ai le également ce .problème..j'ai essayer de ré installer le pluggin, mais le problème est toujours présent.. j'ai installé kodi et vstream sur mon pc windows et sur ma raspberry pi2 ...Le soucis est présent sur les 2 plateformes..S'agit il d'un problème de débrideur ou compte premium pour les sites hebergeurs ou cela vient il d'autres choses..merci d'avance pour votre aide...

**Comment by TmpName** [comment]
Salut, ca te le fait sur tout les sites/sources ?

**Comment by lorenzo06974** [comment]
salut, merci de prendre le temps de me répondre....oui ça me le fait sur 100% des vidéos/sites/sources... Toutes les vidéos fonctionnent très bien, mais j'ai cette fenêtre en plein milieu de l'ecran, impossible de la déplacer et si je la ferme, la vidéo s’arrête également....j'aimerais vraiment pouvoir trouver une solution car je trouve ce pluggin génial a part ce soucis...

**Comment by lorenzo06974** [comment]
version de kodi helix

**Comment by LordVenom** [comment]
Bonjour, merci de faire le retour c'est important pour nous.

avez vous les metadonnée activer ? pouvais vous ouvrir le fichier python plugin.video.vstream\resources\lib\gui/gui.py et me dire ceux que vous avez a la ligne 225.

**Comment by lorenzo06974** [comment]
bonjour LordVenom, oui j'ai bien les metadonnées activées et pour le fichier python plugin.video.vstream\resources\lib\gui/gui.py, je ne le trouve pas, ou je n'ai pas compris comment y acceder, désolé...

**Comment by LordVenom** [comment]
Sur votre  rasbpery c'est un openelec ? si oui le dossier ce trouve dans  ~/.xbmc/addons/

**Comment by lorenzo06974** [comment]
Oui je viens de changer mon dernier com, j'ai fini par trouver...je vous renvoi la ligne 225 de ce ficher
oListItem = xbmcgui.ListItem(oGuiElement.getTitle(), oGuiElement.getTitleSecond(), oGuiElement.getIcon())

**Comment by LordVenom** [comment]
Mince ont pas les meme ligne celle qui m'interesse juste en dessous 

vous avez 
#oListItem.setProperty("IsPlayable", "true")
ou 
oListItem.setProperty("IsPlayable", "true")

avec ou sans le #

**Comment by lorenzo06974** [comment]
ligne 230 chez moi, avec #

**Comment by LordVenom** [comment]
Mince je suis vert la donc 2eme idée
plugin.video.vstream\resources\lib\gui\hoster.py ligne 86 ou pas lol

Modifier 

oGui.addFolder(oGuiElement, oOutputParameterHandler, False)
par
oGui.addFolder(oGuiElement, oOutputParameterHandler)

sauvegarder et tester.

**Comment by lorenzo06974** [comment]
j'essaye ça et je vous tiens au courant, merci de votre aide et de votre patience....

**Comment by LordVenom** [comment]
Merci a vous pour le rapport.
Je quit pour aujourd'hui merci d'avance pour le retour.

**Comment by lorenzo06974** [comment]
Bonsoir LordVenom, j'ai fait la modification proposée plus tôt dans la journée. Résultat, il n'y a quasiment plu de problème.En détails, j'ai essayer plusieurs séries et films provenant de plusieurs sites différents, elles sont toute passées sans soucis (la fenêtre n'apparaissant plu au milieu de l’écran). Il reste cependant un nouveau problème: toutes les vidéos provenant du site Adkami ne s'ouvre pas (Erreur: échec du script vstream) qui apparaît en bas a gauche quand je lance une vidéo.

Vous m'avez déjà tellement aidé que je n'ose plus vous déranger juste pour ce petit détail.Je vous remercie beaucoup, je vais pouvoir profiter au maximum de cette superbe application...

P.S. Si vous vouliez aller au fond des choses et proposer une solution sur le problème Adkami, je reste a votre disposition. Un Grand MERCI..

**Comment by LordVenom** [comment]
La prochaine mise a jour tiendras compte de cette modif merci.
Pour adkami la seul solution c'est que sont webmaster face le menage sur son site web.

**Comment by MusashiAnti** [comment]
Bonjour,
même problème que lorenzo06974. Pour visionner la fenêtre de chargement reste bloquée a 75% sur toutes les videos qui fonctionnent pourtant parfaitement. J'utilise la version Isengard sous W8.
Rechercher les métadonnées est activé. Auriez vous une solution. SVP.
Merci

**Comment by MusashiAnti** [comment]
Merci :)
