### ISSUE TITLE
Poypi et fadoz fonctionne pas

### ISSUE THREAD

**Issue by poto25** [LordVenom/venom-xbmc-addons#143]
Bonjour tout est dans le titre ,  fadoz et poypi marche pas sur vstream une solution ? Merci d'avance

**Comment by TmpName** [comment]
Fadoz a l'air de remarcher a ce moment par contre tjours pas de poypi.

**Comment by mino60** [comment]
j'ai trouver ce lien gkplugin pour les hosters

http://gkplugins.com/download1/

j'avai un problème de connexion et j ai constaté que fadoz passe par gkplugins

http://www.fadoz.com/rva/plugins/01bfgg4f8dh715cvb4gh87df/gkplugins_license.swf  Not found

**Comment by mino60** [comment]
Si ils passent par gk pluguins pour coder leurs liens comment se fait que IDM detect les liens pour le telechargement et pour le streaming

https://r4---sn-5abxgpxuxaxjvh-vgoe.googlevideo.com/videoplayback?requiressl=yes&shardbypass=yes&cmbypass=yes&id=91efea1c8a70a915&itag=22&source=picasa&ip=105.111.20.60&ipbits=0&expire=1433503622&sparams=cmbypass,expire,id,ip,ipbits,itag,mm,mn,ms,mv,pl,requiressl,shardbypass,source&signature=1FEC36873693F4320E8EAA5B8FB1AA860A7EBD0F.53C15EE532A062DEDD0AB33D65B4BA42F86C6CD1&key=cms1&cms_redirect=yes&mm=31&mn=sn-5abxgpxuxaxjvh-vgoe&ms=au&mt=1430911830&mv=m&pl=17

**Comment by mino60** [comment]
j'ai trouvé sur le ghithub le plugins gk 

https://github.com/greenteadigital/stj-podcasts/blob/master/podcasts-full-page.html#L254

**Comment by TmpName** [comment]
Tu peux toujours detecter les liens pr les recuperer ou les telecharger.

En fait ils utilisent proxy.swf qui lui meme utilise plusieurs pluggin dont gkplugins_picasaweb et un autre que je n'ai plus en tete.
Tu peux telecharger le pluggin sans probleme, il y a meme une version gratuite.
Les fichiers communiquent entre eux et c'est "gkplugins_encode.swf" qui assure le decodage.
Une fois le lien decodé, tu peux le recuperer comme un lien classique.

Pour contourner ce systeme, je vois 3 solutions pour le moment.
1 - trouver comment faire executer du flash a kodi, et recuperer le lien apres les bidouilles
2 - decrypter le lien, je suis dessus, j'ai un code pour une vielle version de ce pluggin, mais il me faut decompiler le fichier flash pour recuperer la cle, apparement la cle serait dans le fichier flash, il me faudrait trouver un site avec le meme fichier mais une autre license pr comparer les 2 fichiers.
3 - trouver le site qui leur piquait les liens, il n'ont pas fait a cause de nous (pas assez nombreux), il y a forcement sur le net un site qui propose les meme liens volés sur leurs sites.

**Comment by mino60** [comment]
sur opraz je ne sais pas si ca peut t'aider

http://pastebin.com/EqYzUB1f

http://pastebin.com/BbGrx51U

**Comment by TmpName** [comment]
Merci, j'ai pu recuperer 2 fois le fichier de meme version mais avec une cle differente, vais voir si je peux en tirer quelque chose.

**Comment by mino60** [comment]
le plugin JW Player

https://github.com/jwplayer/jwplayer

**Comment by mino60** [comment]
le script pour gkplugins est ce que on peut l'utiliser
<script src="/iwv/%67%6B%70%6C%75%67%69%6E%73%41%50%49.js"></script>

http://www.lapza.com/iwv/gkpluginsAPI.js

**Comment by mino60** [comment]
Est ce que on peut utiliser ce script?

http://pastebin.com/zE0ZfEEP
http://www.lapza.com/iwv/gkpluginsAPI.js

**Comment by TmpName** [comment]
Kodi ne peut pas utiliser un flash. C est d'ailleurs mon probleme pr recuperer les video du site livestream, pour le moment j'ai pas trop avancé sur ce sujet, ca risque de prendre du temps, mais meme si ca doit prendre des mois, un jour ou l'autre poypi devrait revenir sur Vstream.

En fait ce pluggin est surtout répandu en asie, et je connais que 2 addon de kodi l'ayant contourné, mais vu qu'il commence a se developper ici, ca devrait motiver des gens a le contourner.
