### ISSUE TITLE
elite-streaming.net Full HD 1080p

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#144]
c'est un nouveaux site pour streaming hd le lien streaming ne marche pas c'est bizard!!!?.. par contre on peut telecharger les films.

http://www.elite-streaming.net

**Comment by TmpName** [comment]
Il n'y a pas de streaming sur ce site, a part un lien externe vers un autre site payant.
Apres je ne l'ai pas testé mais un film en 1080p de moins de 700 M, c'est louche.
