### ISSUE TITLE
Solution provisoire pour Fadoz

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#145]
Bonjour  , vue que le site fadoz et compagnie à changé son systèm pour le streaming , ils sont codé leurs liens avec le plugins (gkplugins)
mais les liens apparait aprés le flash c'est qui veux dire quand peut créer notre propre site ou une source avec c'est liens, l'inconvénient de cette méthode c'est quand dois faire la mise à jour manuellement apré chaque sortie des films sur le site fadoz

Fadoz_com.py : 
http://pastebin.com/w4phmGvZ
cover : recources/art/film/
http://www.mediafire.com/download/e6lbg17cg6oconb/film.rar

le fichier cover et de 53 Mo je cherche une solution pour le mettre don le site archive.org son passé par vstream
https://archive.org/details/urllist_201412
user = dzsat19@yahoo.fr 
 pass = dzsat 

cette manipe et provisoire le temps de cherché une solution pour décodé les liens que le site fadoz à crypté avec le plugins (GKplugin)  il y aura des mise a jour chaque jour just les dernier sortie
si vous l'apprécier je la mit sur beta.

**Comment by mino60** [comment]
update : d'ici deux jours ou trois vous aurait tout les films et leurs liens

http://pastebin.com/KZ53B8Ku

**Comment by arzaz** [comment]
Bonjour mino60,
Je viens de télécharger fadoz_com.py,mais et après l'avoir rajouter dans le dossier ressources --> sites du plugin.video.vstream  celui n'apparait pas dans Vstream?
C'est quoi le problème?

**Comment by mino60** [comment]
effectivement comme c'est notre propre source j'ai changé le nom cherche "Cinema" sur tout les sources.

**Comment by poto25** [comment]
Personne peut me faire un zip comme vstream avec tout sa car je suis novice merci d'avance

**Comment by arzaz** [comment]
merci mino60,
Pour info quand je lance cinéma seuls Films et Action marchent par contre les autres genres Drame Aventure Horreur.....etc j'ai l'erreur "echec du script vStream!!!

**Comment by mino60** [comment]
par ce que il n'existe pas encore sur archive.org ce soir je vais finir avec action et drame
et demain les autre

**Comment by arzaz** [comment]
Excellent mino60
Merci encore

**Comment by mino60** [comment]
vstream 

http://www.mediafire.com/download/w11wg391u2hv9tq/plugin.video.vstream.zip

**Comment by poto25** [comment]
Merci beaucoup

**Comment by TmpName** [comment]
La vache, tres bon boulot, mais du boulot de titan.

**Comment by arzaz** [comment]
Bonjour mino60,
J'au remarqué, que la connexion n'est plus fluide comme par le passé? Est ce un problème de host?

**Comment by mino60** [comment]
j'ai mit à jour tout la categorie action par contre j'ai pas fini la catégorie drame j'avais un probleme de connexion hier soir
fichier poster 138 Mo

http://www.mediafire.com/download/e6lbg17cg6oconb/film.rar

**Comment by TmpName** [comment]
Par contre je le trouves pas le fichier "cinema" pr y acceder ?

**Comment by mino60** [comment]
Pour l'instant j'ai accomplie la moitier du travail mais le fichier film qui contient les posters fichier a gros volume depasse le volume du plugin vstream lui meme 
le modifier un peu le script : archive.org.py
http://pastebin.com/b54HnEwd
sur la ligne 26 le chemin pour les posters , je cherche comment mettre le path vers archive.org plutôt que
sRootArt/film, pour cela j'ai crée un fichier film sur archive.org qui contient deux posters pour le test
![film](https://cloud.githubusercontent.com/assets/11494048/7573238/9bd0dbe6-f824-11e4-9fe0-dac9aea2e36b.png)

sRootArt = cConfig().getRootArt()

**Comment by arzaz** [comment]
Bonjour mino60

Ou dois je placer le script archive_org.py?

**Comment by TmpName** [comment]
Je ne vois pas ce que tu essaye de faire mino60, mais c'est normal que si tu remplaces cette partie du code par un lien fixe, tu auras la meme image partout.
Le telechargment de l'image doit se faire dans def parseWebM3U(infile):

Sinon je viens de voir, tu peux garder les lien des sites poypi/vanoz pour les images, ils ne sont pas hebergé sur leur site, donc ils restent fixes, pas besoin de telecharger toutes les images.

**Comment by mino60** [comment]
il il ya moin d'une heur le fadoz à ajouté 3 films sur leurs site j'ai mit a jour le fichier fadoz qui contient c'est 3 film mais son les posters je cherche comment faire un chemin pour le fichier posters sur ce lien
'https://ia601408.us.archive.org/30/items/urllist_201412/film/'

archive.org.py don le dossier site

**Comment by mino60** [comment]
merci TmpName le problème est reglé avec les " posters "
new : archive_org.py
http://pastebin.com/FStdhuun

**Comment by arzaz** [comment]
Bonjour mino60,

Avec les liens ci-dessous, j'ai toujours l'erreur échec vStream? même en se connectant vers ces liens on a le message Page not found?

https://ia601408.us.archive.org/30/items/urllist_201412/aventure.txt
https://ia601408.us.archive.org/30/items/urllist_201412/fantastique.txt
https://ia601408.us.archive.org/30/items/urllist_201412/horreur.txt

**Comment by mino60** [comment]
tout les films son disponible maintenant , j'ai remarqué que tout les lien marche sauf deux films
run et ange et demon (2009) j'ai mit un lien Flashx pour ce film je ne sait pas si ça marche

**Comment by TmpName** [comment]
Je sais pas si Venom va valider le smilblik mais propose le sur le beta, vu le boulot que tu as tombé c'est con de pas en profiter.

**Comment by mino60** [comment]
just sur la qualité 1080p j'ai trouvé 4 parties de 1.69 Go sur le film ( A Most Violent Year (2014) [HD] )
alors j'ai choisie la qualité 720p

**Comment by mino60** [comment]
pour info la mise à jour pour les derniers films ajoutés se fais manuellement pour l'instant c'est moi qui fais la mise à jour si quelqu'un veut faire la mise à jour c'est simple il suffit qu'il rentre le site archive.org avec user et pass que j'ai mit en haut puis my library choisir urllist avec le logo image exodus telechager
ou copie le fichier fadoz apré edit suprimer fadoz et le remplacer le avec le meme mais avec les dernier films ajouté sur le site zoupap.com (Classic uploader) pour validé Updat item!

**Comment by TmpName** [comment]
M'en occuperais si tu pars en congés ^^.
Mais c'est bon une mise a jour par semaine suffit, par contre fais des backup de temps en temps, vu que les accées sont public tu es pas a l'abri que quelqu'un vire tout.

**Comment by mino60** [comment]
En n'ai pas les seul pour trouver une solution pour contourné le gkplugins sur le web j'ai trouvé cette page mais j'ai pas comprie comment faire pour le décompilateur swf
la page et en englais traduction google

http://translate.googleusercontent.com/translate_c?depth=1&hl=fr&prev=search&rurl=translate.google.fr&sl=en&u=http://stackoverflow.com/questions/22402176/weird-url-encryption-decryption-how-does-this-work&usg=ALkJrhgUs6RC9eg5yqQuV_KgY1xVSBL6Xw

**Comment by TmpName** [comment]
En fait moi j'ai deja commencé a decompiler le fichier flash, et j'ai meme trouvé quelqu'un qui m'a commencé le boulot, le seul probleme c'est que cela va demander du temps pour convertir le fichier flash en python, et qu'il suffit d'une erreur pour que le resultat soit completement differents (et faux evidement).
En fait je n'ai pas moyen de voir ma progression, il me faut y passer beacoup de temps et seulement a la fin je saurais si ca marche, et dans le cas contraire j'aurais perdu mon temps.

Franchement pour le moment j'ai pas trop envie de me lancer la dedans, car ton pluggin fonctionne, et ca me demandera moins de taff de le mettre a jour moi meme que de decoder leurs liens.
Je cherche aussi a "me servir" du fichier flash pour decoder les liens, mais la ca deconne au niveau de la license, mais la c'est beacoup plus facile a faire.

**Comment by mino60** [comment]
meme si on trouve la clé il se peut qu'il change la vertion du plugin (gkplugins) ai on se retrouvera avec un autre problème?!!!

**Comment by TmpName** [comment]
La cle je l'ai deja, c'est vraiment la version du plugin qui me freine (et oui si la version change tout est a refaire), vais peut etre tenter ma chance ce Week end. Apres le plugin est payant et limité a 4 sites pour leur license, donc je ne pense pas qu'ils changent avant un moment.

**Comment by mino60** [comment]
est ce que on peut utilisé l'encien code pour vanoz la (fonction showMovie à la place showWeb) sur mon code de façon que kodi detect le host googlevideo?.

**Comment by TmpName** [comment]
Je vois pas pquoi tu pourrais pas mettre le nom que tu veux, tu y ai meme obligé car sinon ton addon ne marchera que en passant par "toutes les sources"

Y a un gros boutton vert si Venom t as rajouté, mais je ne vois pas le fichier dans la liste des "pulls requests"

**Comment by arzaz** [comment]
Bonjour mino60,

Est ce que tu peux mettre a jour le film PROJET ALMANAC dans le fichier archive_org, car il est passé en HD.
Merci

**Comment by mino60** [comment]
merci pour l'info c'est fait

**Comment by mino60** [comment]
j'ai ajouté une nouvelle rubrique "cinema" sur archive.org pour des video qui ne son pas sur le site zopap.com et compagnies , vous pouvez ajouté des films soit des films uploadés sur google video soit sur youtube , dailymotion ,...ext mais avant vous devez s'enregistrer sur google puis editer votre profile
apré vous pouvé partagé des video films youtube sur inporter une video la vous avez le chois des video sur votre pc ou introduire une url utilisé idm pour detecté les lien googlevideo


http://pastie.org/10191713

**Comment by arzaz** [comment]
Bonjour mino60,
Je viens de faire le test avec la nouvelle rubrique "Cinema" j'ai trouvé 03 films Apocalypto (2006) 720HD et 1080HD + Ninja Apocalype, mais a chaque fois je lance un de ces films j'ai l'erreur de lecture?
C'est quoi le problème?
Merci

**Comment by mino60** [comment]
ça marche trés bien pour moi avec 720p mais j'ais une erreur sur 1080p c'est du à la connexion je crois
avec un fichier de plus de 3 Go la vitesse de ma connexion et de 2 Mo

**Comment by poto25** [comment]
salut mino60 merci pour le travaille que tu fait pour nous , voila j'avais télécharger ton lien http://www.mediafire.com/download/w11wg391u2hv9tq/plugin.video.vstream.zip

mais depuis quelque temp j'ai plus les jaquette c'est normal ou pas merci de me répondre

**Comment by mino60** [comment]
essayé la nouvelle version archive.org mais avant tu dois supprimer vstream 0.3.0

http://www.mediafire.com/download/w11wg391u2hv9tq/plugin.video.vstream.zip

**Comment by poto25** [comment]
Ok merci beaucoup

**Comment by TmpName** [comment]
Bon bonne nouvelle, j'ai trouvé un moyen de decoder les liens crypté, mais pour le moment on est forcé d'utiliser une application flash, a voir si je peux en faire un executable qui marcherait en ligne de commande.

En fait j'ai modifié son propre flash pour pouvoir l'utiliser moi meme, en local.

**Comment by arzaz** [comment]
Y a t-il un moyen de rajouter des liens pour le téléchargement?

**Comment by poto25** [comment]
bravo TmpName

**Comment by TmpName** [comment]
Oui,arzaz, mino60 a donné toute les infos sur ce topic, pass, user , url et methode.

**Comment by mino60** [comment]
A oui !! c'est une bonne nouvelle pour flash player tu peu mettre 
from resources import flash player

pour ajouté des liens sur "cinema"
vous devez télécharger et installer idm  ( majax31.com) sur votre pc
créer un compte sur google
aller sur https://picasaweb.google.com
vous avez 15360 Mo d' éspasse libre
uploadé votre film à partir de votre pc 
l'opération va durer pendant des heurs voir meme des jours selon la vitesse de votre internet
et le volume de la video uploadé
clic sur diaporama vous serait on mode plein écran la video ce lance idm detect le lien de téléchargement clic sur l'incon idm pour lancé le telechargement puis anuller
entrer apré sur IDM vous trouverez l'adresse et la mettre sur le fichier "cinema".

**Comment by TmpName** [comment]
Bon c'est bon j'ai fini, on va pouvoir reprendre comme avant, j'ai la totale : Le code utilisé, l'algorythme, la technique pr le bypass, et meme la cle, me reste plus qu'a le re incorporer dans un des site de vanoz et ca repart comme avant.

En plus vu que le cryptage et payant et valide pr 4 sites, je ne pense pas qu'ils rechnagent toute les semaines.

**Comment by arzaz** [comment]
Bravo TmpName,

Quand aura t'on accès a belle surprise?

**Comment by TmpName** [comment]
A l'instant; mais va falloir tester car j'ai pas mal changé le host googlevideo/picassaweb, pas sur de ne pas avoir cassé autre chose.
Pour le faire fonctionner mettre a jour poypi, le host googlevideo et rajouter le fichier gkdecode dans les libs

**Comment by arzaz** [comment]
Extraordinaire tout est OK

Merci infiniment TmpName

**Comment by mino60** [comment]
super travail , j'ai fait les 4 changement mais il y'a une erreur script
je ne voi pas la deuxième page ou on choisi la qualité 720p d80p just [???]

**Comment by TmpName** [comment]
Pour les  ??? c'est normal, je corigerais plus tard mais en fait a l'origine il y avait plusieurs qualitées sectionnable sur poypi puis apres piccassaweb proposait encore un choix. Ils ont changé de methode, maintenant il n'y a plus que picassaweb qui propose un choix, donc tu ne l'auras que apres avoir cliqué sur le lien googlevideo/picassaweb.

Pour ton bug essaye de remettre a jour ton fichier hosters.py, je ne vois pas comment les autres pourraient te provoquer ce message d'erreur.

**Comment by mino60** [comment]
j'ai réinitialisé tout j'ai mit à jour le fichier hoster.py poypi ..ext mais j'ai toujour le meme problem?

**Comment by TmpName** [comment]
Essaye en mettant a jour le fichier config.py mais c'est bizarre que ca deconne uniquement pour ce site.

Essaye de coller des "print cConfig().getlanguage(30202)" un peu partout dans la fonction showHoster du fichier cHosterGui.
Normallement ca doit t'afficher un texte
Essaye deja en en mettant un juste au debut de la fonction pour voir si le probleme vient de la.

**Comment by mino60** [comment]
j'ai résolu le problème avec l'ancien fichier hosters.py maintenant ça marche nickel bon boulot  félicitation
juste une question ; pourquoi google resolve affiche 536 p au lieu 720p? et combien t'a fallu de temps pour convertire le fichier flache var on python

en conséquence de ce travail fini les mise à jour pour archive.org !!!.

**Comment by mino60** [comment]
update archive.org  j'ai fait quelque modification 

http://pastebin.com/7Rj1t6xm

**Comment by poto25** [comment]
la mise a jour se fait automatiquement ou il faut retélécharger le zip , merci et bravo pour le travaille

**Comment by mino60** [comment]
pour la mise à jour automatique tu doit installé repositorie

tuto installation

http://tv-tuto-info.com/tutoriel-xbmc-vstream-filmsseriesdocumentaireschaines-tv-en-streaming-xbmc/
