### ISSUE TITLE
vstream erreur script pour dpstream 

### ISSUE THREAD

**Issue by donsai007** [LordVenom/venom-xbmc-addons#146]
Bonjour lord venom je tiens à vous remercier pour votre magnifique addon. Jai  un soucis avec votre addon qui tourne sur joli avec dpstream J’arrive  Pas a ouvrir les recherches ou même chercher par film nouveautés les autres liens marche que dpstream il me met erreur script 

Je voudrais aussi savoir si c'est possible d'ajouter des liens pour d'autres sites ? 
Exemple : http://www.hindilinks4u.to

Merci d'avance

**Comment by TmpName** [comment]
Salut, alors tout d'abord parles tu de dpstream.net ?
Dans la version officielle il n'y a que dpstreaming.org qui marche au moment de mes tests (il y a 10 mn), il y a egalement la source dpstream.net mais qui n'est pas officielle (encore en test) et ou effectivement la recherche deconne mais je ne sais pas ou tu as trouvé le fichier.

Sinon oui tu peux tres facilement creer tes propres sources, il te suffit d'avoir des bases en python ou assez de logique pour comprendre le systeme, il te suffit de prendre le code prevu pour cela, et l'adapter au site que tu veux scrapper, puis le mettre dans le meme repertoire que les autres sites et pas plus.

https://github.com/LordVenom/venom-xbmc-addons/blob/master/ajouter_une_source.py

**Comment by donsai007** [comment]
Salut merci pour le tuyau 

Moi le vstream 3.0 j'ai et c'est dpstream.org qui déconné mais la j'ai essayer ça marche 

Pour le version vstream j'ai aussi recherche visuelles je sais pas si c'est inclut dans a version stable ou pas sinon tu peux me donner le lien exacte pour la version stable stp 

Merci

**Comment by donsai007** [comment]
Et aussi m'indiquer où se trouve le répertoire pour ajouter le fichier .py j'ai créé 

Merci pour tout

**Comment by TmpName** [comment]
Si tu ne sais pas si tu as la version stable ou beta c'est que tu as la stable ^^.
La "recherche visuelles " est encore en developpement sur la version beta aussi donc t'inquiete pas pr ca.

Une fois que tu as fini ton fichier *.py il te faut le mettre dans le meme repertoire que les autres plugin.video.vstream/ressources/sites
Et relancer Vstream.

**Comment by donsai007** [comment]
Je viens de vérifier sa marche pour ouvrir la premier page après quand je fais next pour voir l'autre page j'ai un message d'erreur du script

**Comment by donsai007** [comment]
Sur dpstream.org

**Comment by donsai007** [comment]
Sur onglet film nouveautés - dpstream.org

**Comment by TmpName** [comment]
Je crois que c'est deja corigé pour la prochaine version car je n'ai pas le probleme, remplace ton fichier par celui la
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/dpstreaming_org.py

**Comment by west2811** [comment]
bonjour lord venom j'ai une erreur de script pour la source dpstream.org dans vstream je suis sous kodi 14.2 Touranat sous windows 8.1 y 'a t il une solution

**Comment by TmpName** [comment]
As tu essayé la manip du precedent post ?

**Comment by west2811** [comment]
n'étant pas un expert de l'informatique je n'ai pas vraiment compris la manipulation a faire......

**Comment by west2811** [comment]
je ne sais pas ou se trouve le fichier dpstreaming_org.py à remplacer

**Comment by TmpName** [comment]
Dans ton repertoire c:\........\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites

**Comment by west2811** [comment]
ok merci pour tout et chapeau pour ton iniative j'attendrai la mise à jour merci beaucoup

**Comment by west2811** [comment]
ou sera t-il possible d'etre tenu informer des nouvelles mises à jours pour vstream?

**Comment by LordVenom** [comment]
Les mises a jour sont automatique si vous avez installer le repository, sinon vous pouvez me suivre sur twittter je poste a chaque nouvelle mise a jour. 

https://twitter.com/LordVenom57

**Comment by west2811** [comment]
pouvez vous me donner le liens pour le repository svp

**Comment by LordVenom** [comment]
https://github.com/LordVenom/venom-xbmc-addons/releases?after=v0.2.1

 Dernier lien :)

**Comment by west2811** [comment]
merci bcp
