### ISSUE TITLE
installation plante sur Raspberry pi 2 avec Openelec

### ISSUE THREAD

**Issue by gigi1970** [LordVenom/venom-xbmc-addons#147]
bonjour 
l'install plante sur openelec ( materiel : Raspberry pi 2 )

merci d'avance pour l'aide

**Comment by TmpName** [comment]
Je suis pas le mieux placé pour te repondre, mais je crois que tout simplement il n'est pas supporté sur cette plateforme.
Il ne marche pas non plus sur la version anterieure a helix.

**Comment by gigi1970** [comment]
pour info, la 0.2.9 passe bien

**Comment by LordVenom** [comment]
Bonjour,

Y a pas de gros changement entre la 0.2.9 et la 3 juste les sources. il faudrait me fournir votre log que je puisse me faire une idée.

**Comment by oserin** [comment]
Bonjour est il prévu un support sur openelec ? J utilise perso le rpi avec la version openelec 5.0.8 ie kodi helix 14.2. Lorsque j essaye de télécharger la derniere version depuis le repo ça plante. Par contre comme l indique gigi la version 0.2.9 passe .

**Comment by LordVenom** [comment]
Bonjour, perso je suis aussi sur openelec sans soucis.donnez moi plus d'info quel erreur ? un log à me montrer peux être.

**Comment by LordVenom** [comment]
Pas de nouvelle, merci de nous prévenir mais si y aucun suivit du bug pour nous y en a pas !!!

**Comment by oserin** [comment]
Bonjour désolé pour le délai et merci pour la réponse. Lorsque j ai installé la version 0.2.9 il m a installé un paquet de librairies...depuis j ai installé le repo et la mise à jour s est faite à la version 0.3.4 et ça fonctionne parfaitement. Maintenant étant parti d une nouvelle configuration je ne sais pas si précédemment un autre plugin a pu posé problème... Il faudrait que je reessaye sur une conf vierge en installant le repo et essayé d installer le plugin pour voir si le problème revient mais maintenant que ça marche ...si je repars d une conf vierge, je m en donnerai la peine. En tout cas merci pour ce plugin c est carrément intéressant !
