### ISSUE TITLE
site streaming hd multi-hosters : libre-stream.org

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#148]
j'ai trouvé ce site libre-stream.org/ HD 720p avec boucoup de platformes comme vkstreaming HD ,MaiRu HD ,Netu HD

contien des films et series

**Comment by FreeFighter77** [comment]
Je suis decu ;)

**Comment by FreeFighter77** [comment]
J'ai un peu avancé:
http://pastebin.com/cV2UPbXc
les films c ok ,les series manquent bcp de hosters a creer,j ai pu faire un test,mais j ai un bug que j'arrive pas a resoudre pour les series,il y a un lien youwatch par episode sur le site,mais dans vstream il m en affiche une 15 (c le meme x15)

**Comment by TmpName** [comment]
Lol, dsl, ce site m'a pas trop motivé, il est trop lent pr moi et il n'y a qu'un hebergeur pour les series
Pour ton bug "sHosterUrl = sUrl"
En fait tu initialises sUrl en dehors de la boucle et reutilises cette meme valeur a chaque tour de la boucle.

**Comment by mino60** [comment]
j'ai trouvé égalemment le site  filmvfvk.com avec des video film 720p HD.

**Comment by TmpName** [comment]
Ha wi un systeme de survey, vais y jeter un oeuil cet apres midi, mais pr le moment j'arrive pas a voir combien de films ils ont en stock.

Tu as deja pu acceder a un lien ?
