### ISSUE TITLE
Impossible de mettre les liens en favoris

### ISSUE THREAD

**Issue by rygelmedia** [LordVenom/venom-xbmc-addons#149]
Bonjour,

Il est impossible de mettre les liens en favoris. Lorsque le menu contextuel s'affiche, il apparaît 3 items: 1 item "Marquer vu/Non vu" et 2 items vides.

Cdt

**Comment by TmpName** [comment]
???
A quel moment tu appelles le menu contextuel ?
Meme sur la page d'acceuil j'ai "Voir marque page" "ajouter au favoris"
 et "parametre extension"

Le menu contextuel apparait en appuyant sur "c" ce n'est pas le menu deroulant de gauche.

**Comment by rygelmedia** [comment]
oui nous parlons du même menu contextuel (en appuyant sur le "c").
D'ailleurs j'ai remarqué autre chose d'étrange en le faisant apparaître à
la page d'accueil: les deux autres items ("ajouter au favoris"
et "parametre extension") apparaissent cette fois mais pas le 1er item.
J'ai mis ci-joints deux snapshots (menu contextuel en page d'accueil et
menu contextuel en page tv du web. J'espère que ça aidera ...

2015-05-16 21:32 GMT+02:00 TmpName <notifications@github.com>:

**Comment by TmpName** [comment]
J'ai pas trouvé comment acceder a tes snaps, mais je ne comprend pas ton probleme, tu as essaye de tout supprimer et reinstaller ?
Je ne pense pas trouver d'infos dans tes logs, et vu que tu n'as meme pas de message d'erreur, la je patauge complet.

Apres je n'ai jamais regardé les conditions d'affichage de cette option dans le code.

**Comment by LordVenom** [comment]
Bonjour, verifier que xbmc soit en langue française sinon il ne trouve pas certaine traduction de langue.
pour avoir la bande annonce ll faut activer les meta donnée.
