### ISSUE TITLE
Streamingvfvk

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#150]
Bonjour ,  un site intéressant qui propose des films haut qualités le site c'est streamingvfvk.com
j'ai regardé un film 1080p c'est t'es super.

**Comment by arzaz** [comment]
Bonjour mino60,

Merci de confirmer si le lien de ce site est correct: www.streamingvfvk.com
Car j’accède a une page web qui n'a rien avoir avec le streaming?

**Comment by FreeFighter77** [comment]
as tu vraiment regarder un film entier !!?? car le site est tres tres louche ....

**Comment by mino60** [comment]
effet c'est hdstreaming.com ou j'ai vue la video 1080p mais il ya boucoup de liens mort sur 1080p
par contre ça va bien sur Bluray 720p j'ai mème regardé un film en 3D HD sur ce site !!.

**Comment by TmpName** [comment]
Tu peux mettre l'adresse complete stp, j'arrive pas a y aller, soit mon FAI bloque le site, soit y a une faute de frappe.

**Comment by mino60** [comment]
effectivement c'est filmstreaming.com
