### ISSUE TITLE
Host Videomega

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#151]
Les liens avec le host Videomega sont vides?
Une solution svp

**Comment by TmpName** [comment]
J'ai fais une mise a jour il y a 3 jours sur le beta, as tu essayé le nouveau fichier ?
https://github.com/LordVenom/venom-xbmc-addons-beta/tree/master/plugin.video.vstream/resources/hosters

**Comment by arzaz** [comment]
Bonjour TmpName,

J'ai fait le test avec le nouveau host, mais le problème persiste.
Les films testés: Les Nouveaux sauvages, Ex Machina et Adaline

**Comment by TmpName** [comment]
Si c'est sur frenchstreaming_org, je n'ai meme pas pu tester, je n'ai aucun film qui s'affiche mais il ya bien ce host.
J'y jete un oeuil de suite.

**Comment by arzaz** [comment]
Je viens de constater aujourd'hui aucun film ne s'affiche sur frenchstream, je crois qu'il est out?

**Comment by TmpName** [comment]
C'est bon je pense avoir corrigé les deux.
Nouveau fichier pr videomega et frenchstream, dis moi si c'est mieux.

**Comment by arzaz** [comment]
Désolé de revenir encore vers toi TmpName, car le host videomega ne marche toujours pas, j'ai l'erreur échec de lecture?
J'ai remarqué aussi que les hosts "OK.RU" et "videoraj" sont vides?
Merci encore pour ton excellent travail

**Comment by TmpName** [comment]
Tu es sur quel site ?

**Comment by arzaz** [comment]
Oui sur Frenchstream

**Comment by TmpName** [comment]
Alors pour videomega, verifis de n'avoir rien oublié (Mise a jour + modif dans hosters.py) je viens de tester pr le premier de la liste "Crime broker" et il fonctionne, peut etre ausi que ton lien est mort.

Pour les 2 autres, je m y met de suite.
