### ISSUE TITLE
Site de streaming 720p marche avec debrideur

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#152]
Le site et www.film-streaming.ws/
Le seul site de streaming en HD 720p 100% Gratuit, regardez tous les films que vous desirez en streaming HD en illmité sur film streaming.ws. plus de 10000 films le site marche avec 3 ou 4 debrideurs.

il ya aussi ;
cinemaviz.net
hdfilmstreaming.com

**Comment by TmpName** [comment]
J'ai testé, ca marche pas mal et c'est du vrai 720p, par contre tu m'as pas repondu pr celui la https://github.com/LordVenom/venom-xbmc-addons/issues/150

**Comment by sahir23** [comment]
Je trouvai ce site cool i espère que vous aimez http://www.film-streamingx.com
