### ISSUE TITLE
Bug recherche générale

### ISSUE THREAD

**Issue by bobynou** [LordVenom/venom-xbmc-addons#153]
Bonjour,

Quand je fait une recherche, "collar" par exemple, sur l'ensemble des sources "full stream.me" ne trouve pas ce que je cherche. Par contre si je fait la recherche directement dans dans le dossier source sur "full-stream.me" là il trouve ce que je cherche. (je n'ai pas cherché sur chaque source individuellement pour voir si cela le faisait avec d'autre source)
 
Merci

**Comment by TmpName** [comment]
Salut, alors la le probleme c'est que l'on arrive en fin de mois donc ca fait 25 jours qu'on a bidouillé les fichiers.
Je viens de tester chez moi, "recherche generale"/"serie"/"collar" et je tombe sur les 6 saisons de FBI duo tres special de "full stream me" donc je pense que ce bug a deja été resolu.

Normallement tu seras fixé d'ici une semaine je pense.
