### ISSUE TITLE
Cinemavit

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#154]
TmpName, mino60 bonjour

Merci de voir si ce lien est intéressant: cinemavit.com

Merci

**Comment by TmpName** [comment]
Salut, en ce qui me concerne j'ai mis le hola sur les nouvelle sources, car Venom juge (et suis d'accord avec ca) que pour les films on est deja ras la gueule, j'ai passé pas mal de temps pr trouver la cle de vanoz et les corrections de mes sites deja en place ca me prennent encore pas mal de temps, donc en resumé plus trop de temps pr des nouvelles sources

Mino60 a aussi trouvé pas mal de site en HD qui valent le coup d'oeuil mais pareil je n'ai pas assez de temps pr le moment.

Apres rien ne t'empeche de t y mettre aussi, tu pourras trouver de l'aide ou des conseils ici.

**Comment by TmpName** [comment]
Site fermé
