### ISSUE TITLE
Vstream Repo

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#155]
Bonjour LordVenom,

Que se passe t-il avec le repository, impossible d'installer Vstream, car le dépôt est vide?

**Comment by arzaz** [comment]
C'est une catastrophe, après avoir essayer d'installer manuellement cette nouvelle version mon demo ne fait que rebooter, et j'ai du la désinstaller pour qu'il reprenne vie.
Prière de voir c'est quoi exactement le problème avec cette MAJ?

**Comment by LordVenom** [comment]
Bonjour, le problème devrais etre corriger.
