### ISSUE TITLE
vstream stoppe kodi depuis la dernière mise à jour

### ISSUE THREAD

**Issue by jslmiatb** [LordVenom/venom-xbmc-addons#156]
Bonjour LordVenom, Bonjour TmpName ,

Tout d'abord, merci pour le fantastique travail réalisé autour de Vstream. Nous avons découvert cette add-on il y a une grosse semaine et nous l'utilisons sur notre RPI 2 (OpenElec 5.0.8). En tant qu'expatrié, quel bonheur...

Nous avons voulu utiliser Vstream cet après-midi et d'un coup il a disparu des extensions installées (après une mise à jour automatique). J'ai essayé de le réinstaller et cela a planté OpenElec (écran noir). Impossible d'ailleurs de redémarrer OpenElec qui reste figé sur un écran noir.

J'ai réinstallé OpenElec depuis le début, réinstallé la dernière version de Vstream (publiée il y a peu de temps) et même résultat : à la fin de l'installation, l'écran devient noir et tout plante.

Après avoir dis ça, j'ai bien conscience que ça ne fait pas bien avancer les choses, mais c'était pour le signaler.

Je vais essayer de réinstaller la version 0.3.0 et de bloquer les mises à jour et je posterai le résultat pour voir si ce dysfonctionnement provient de la nouvelle version 0.3.1

Merci et bonne journée.

**Comment by TmpName** [comment]
A mon avis evite la version 3.1 avant le feu vert de Venom, arzaz a le meme probleme que moi, enfin si on peut appeller ca un probleme, on ne peut pas installer la V 0.3.1, du coup on a pas eu ton crash mais il y a quelques soucis avec la mise a jour.
La je debarque juste mais c'est peu etre venom qui a bloque les mises a jours le temps de regler ton probleme.

**Comment by jslmiatb** [comment]
OK. Merci pour ce retour. Quand j'ai réinstallé OpenElec et Vstream, je suis passé par le SuperRepo et non par une installation depuis le zip de la release officiellle. Et l'installation ne s'est pas terminée correctement a geler mon RPI 2. Mais je n'ai pas fait attention à la version qui a été installée via le Super Repo (3.0 ou 3.1).

J'en profite pour poser une question bête : pourquoi dans la liste des chaînes TV WEB il n'y a pas TF1 ?

Je tente une réinstallation en 3.0 depuis le zip de la release.

**Comment by jslmiatb** [comment]
Bon en fait impossible de réinstaller Vstream depuis les sources. Il cherche toujours à mettre à jour. J'ai vendu la peau de l'ours avant de l'avoir tué ou je ne suis pas doué, ce qui est tout à fait possible. Je vais attendre des nouvelles. En tout cas merci.

**Comment by mino60** [comment]
effictivement la version vstream 0.3.1 ne fonctionne pas pour le moment , erreurs adddon.xml ,hoster.py
il faut attendre la version finale demain si vous vous voulez la version vstream 0.3.0 les principaux changement de la version beta 0.3.1 (fichiers hosters,site) voila le lien de téléchargement

http://www.mediafire.com/download/w11wg391u2hv9tq/plugin.video.vstream.zip

**Comment by TmpName** [comment]
Lol, dsl pour ce soir, mais des que venom repassera ce sera rapide.
Sinon je ne pense pas que tu ais besoin de desinstaller openelec, j'ai aussi un RPI et je comprend l'horreur, en supprimant juste le repertoire de Vstream dans le repertoire de l'addon, ca devrait suffiire a redemarrer kodi.

Je n'ai jamais testé SuperRepo, mais Vstream a son propre repository, il ne fait pas tout planter mais empeche les mise a jour pr nous en ce moment. Tu devrais pouvoir l'installer en passant directement par ici https://github.com/LordVenom/venom-xbmc-addons/releases et en prennant la V 0.3.0 mais franchement si tu peux attendre le retour de Venom, ce sera plus simple et garanti sans prise de tete.

Apres pr les chaines de TV, a mon avis le lien TF1 venais de mourrir quand il a fait la mise a jour et il a preferé supprimer le lien que mettre un lien foireux. Moi je ne me sert jamais de cette partie, j'ai un autre addon pour les IPTV. C'est facilement corirgeable et sans modif pour toi, vu que l'addon vient lire les adresse sur le repo justement. J'ai trouvé un lien pr TF1, ca devrait remarcher un peu apres le retour de Venom.

Edit : Tu peux aussi tester l'archive de mino60, c'est carrement un backup en direct de son ordi totallement fonctionnelle (a pars poypi qui deconne encore je crois ^^)

**Comment by mino60** [comment]
le zip fonctionne tres bien avec poypi le problème que j'ai rencontré c'etait avec le hoster.py de la beta je l'ai remplacé de celui de la version vstream 0.3.0 et du coup le problème à régler.

**Comment by jslmiatb** [comment]
Bonsoir et merci à tous les deux. J'ai testé avec l'archive de mino60 et tout fonctionne parfaitement. Merci beaucoup. Pour la mise à jour 3.1 je vais attendre patiement. Bonne soirée.

**Comment by LordVenom** [comment]
Bonjour, le problème et régler normalement.

**Comment by lobofi** [comment]
Il have Still  problem with vstream  3.31 on kodi i have thé message installation failed

**Comment by hawwach** [comment]
@LordVenom vstream 0.3.1 is working now but missing a lot of texts. Main menu icons without texts.

**Comment by lobofi** [comment]
I have thé same  problem on kodi not avalaible or faled installation

**Comment by TmpName** [comment]
For theses one who have instal problem, try to uninstall completely Vstream before.
I have made my update 2 hours ago with the option "check update" in "system/extension" (not sure It's exactly this name, I have the french version) and ATM it's works perfectly.

@hawwach wich one language are you using ?

**Comment by hawwach** [comment]
@TmpName I am using English language.
Thank you all for the Great effort @TmpName @LordVenom @mino60

**Comment by hawwach** [comment]
@TmpName When switching to French, it appears correctly.

**Comment by TmpName** [comment]
Right, there is some missing string in other languages.
Lol, the update is really hard this time.

**Comment by hawwach** [comment]
@TmpName Oh I see, gonna stick with French till next update.
Thanks a lot.

**Comment by lobofi** [comment]
i use french where is the right version of vstream 3.31 for kodi which works please

**Comment by TmpName** [comment]
@hawwach I don't think you need to wait for the next update, you will find the correction here in some hours I think.

@lobofi If you don't use repo, delete your previous folder and use this link https://github.com/LordVenom/venom-xbmc-addons/releases/download/v0.3.1/plugin.video.vstream-0.3.1.zip

**Comment by lobofi** [comment]
Thank you it works  but there 's no titles no matter great  job and thank you

**Comment by TmpName** [comment]
Yes, we have a traduction bug, for the moment it work only in french, try to wait some days.

**Comment by jslmiatb** [comment]
Bonjour,

Désolé de mes non-réponses de ce week-end. Toujours le même problème pour moi sur mon RPI 2. Quand Vstream ce met à jour ça me plante totalement OpenElec....

Merci à vous tous pour les échanges de ce week-end.

**Comment by LordVenom** [comment]
Bonjour, Je suis aussi sous openelec et la mise a jour c'est passer sans problème.Je te proprose de supprimer le dossier temporaire de vStream et de faire une installation propre depuis le repository.

/storage/.kodi/addons/plugin.video.vstream

**Comment by jslmiatb** [comment]
Merci du retour. J'ai fait une install de zéro et tout fonctionne. Merci. En fait j'ai l'impression que la mise à jour faite depuis le dépôt SuperRepo à l'air de poser un problème.

Un grand merci en tout cas.

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
bonjour
Depuis hier j'ai erreur connection impossible en wifi mais j'arrive à me connecter en 4G

**Comment by lobofi** [comment]
Désolé pour le message  en multiexemplaires pas fait exprès

**Comment by lobofi** [comment]
Nobody for  helping me with vstream i have à error message connection impossible with thé net il can  connect  only in 4 G with my smartphone

**Comment by TmpName** [comment]
Lol, c'est clair que tu as des prb de reseaux, ca se voit ^^
Par contre la je ne pense pas que l'on puisse t'aider, je ne pense meme pas que le probleme vienne de kodi.
Tu arrives a te connecter sur google par exemple via Wifi ?

**Comment by lobofi** [comment]
oui tout fonctionne sauf vstream

**Comment by garcimouche** [comment]
Je suis un nouvel utilisateur Kodi/VStream. Exactement même problème pour moi. Boîte android 5 matricom q2. Merci pour la solution de désactiver fullmoviz ça marche parfaitement maintenant. Incroyable plugin au passage.

**Comment by TmpName** [comment]
Yep, c'etait ca, mais il y a eu au moins 3 post avec le meme probleme et y a pas eu de reponse ici, normallement la source a ete corrigee depuis.
