### ISSUE TITLE
Problème pour afficher les posters 

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#157]
Bonjour....

problème pour afficher les posters sur full-streaming.com est ce que je opte pour refairé google.com

http://pastebin.com/eaaBSisF

**Comment by TmpName** [comment]
J'ai pas compris "refaire google.com" ?

Sinon pour ton probleme l'image n'est pas dans aEntry[0] mais aEntry[2].
Mais le pattern est foireux meme si il marche, il contient du cote html au debut

Tu fais un "print aResult", tu as regardé le resultat que ca te donne dans le debug log ?

**Comment by mino60** [comment]
merci les posters s'affiche maintenent apré la modification sur aEntry[0] vert aEntry[2]
j'ai trouvé encore un autre problème pour le play de la video le site utilise une seul plateforme sur la majorité des films avec Mai.ru ce host s'affiche sur mon ecran mais je ne trouve pas la video just un message fichier introuvable par contre il exist sur le site mait il faux cliqué sur Watch video pour aller direct et trouvé la video sur l'hébergeur Mai.ru.

**Comment by mino60** [comment]
<div class="b-player__background">
            <div class="b-player__content">
                <div class="b-player__video-not-available">This video is only available on Mail.Ru</div>
                <a href="http://r.mail.ru/clb15944866/my.mail.ru/mail/striker.kiko/video/_myvideo/1316.html?from=watchonmailru" class="b-player__button" target="_blank">Watch video</a>

**Comment by TmpName** [comment]
Le lien r.mail.ru/clb15944866/my.mail.ru/mail/striker.kiko/video/_myvideo/1316.html?from=watchonmailru
Mais le lien videoapi.my.mail.ru/videos/embed/mail/striker.kiko/video/_myvideo/1316.html a l'air de fonctionner.

Donc essaye http://pastebin.com/vhwKZYE8

Tu as corrigé le regex ?

**Comment by mino60** [comment]
j'ai essyé avec ton code mais ça marche pas il faux mettre à jour le host Mail.ru il ne fonctionne pas sur frenchstream.org et mème sur les autres sources, je vais essyé avec urlresolver 
pour regex  C'est un vrai casse-tête! ...je suis dedans!!!

**Comment by TmpName** [comment]
Je viens de tester mail.ru sur fullstream.me et frenchstream.org, aucun probleme.
Tu as testé quel film ?

**Comment by mino60** [comment]
Mai.ru! n'existe mème pas sur urlresolver j'ai testé sur prise on otage avec le host Mai.ru son modification. en faite sur frenchstream.org il ya deux  tâches a faire si tu veux bien

- ajouté les information ( nombre de vues anné de sortie ) à côté des titres comme streamfilms.fr
- ajouter la qualité 1080p

**Comment by arzaz** [comment]
Bonjour a vous tous,

J'ai remarqué que sur Dpstream, les affiches des films (Posters) ne s'affichent pas?
Merci de voir c'est quoi le probleme.
Autre chose quand j'active les métadonnées dans le menu Vstream, toutes les affiches de tous les sites disparaissent?

**Comment by TmpName** [comment]
Rajout sur la beta des commentaires année et qualité pr frenchstream
Par contre Dpstream n'est pas encore officiel, si tu voulais dire Dpstreaming, ca marche chez moi, donc je peux pas trop te dire.

**Comment by arzaz** [comment]
Bonjour TmpName,

Je voulais dire Dpstreaming, car chez sur ma box Prismcube aucun poster ne s'affiche?
Je ne comprend rien avec les autres sites 90% des posters s'affichent !!!!!!

**Comment by TmpName** [comment]
J'ai pas trop d'idées, je n'ai pas fais de modifs perso sur ce fichier, peut etre le mode d'affichage que tu as choisi. Je n'ai jamais touché aux metadonnées, peut etre un cache a vider ?

Si quelqu'un d'autre peut dire comment c'est chez lui ?

**Comment by LordVenom** [comment]
Quand j'ai des soucis avec les posters je virer la base de donnée associer AppData\Roaming\Kodi\userdata\Database\Textures13.db

**Comment by arzaz** [comment]
Bonjour LordVenom,
Malgré avoir supprimé Texures13.db, le problème persiste.
Ci-joint le debug log si tu peux faire quelque chose.
![debug log](https://cloud.githubusercontent.com/assets/9026875/8019698/ef59d572-0c53-11e5-8f04-f7f652c838c9.JPG)

Salutations

**Comment by LordVenom** [comment]
Impossible de lire le log.

**Comment by arzaz** [comment]
Essai avec celui-ci

Il est a note que depuis que j'ai supprimé le fichier Textures13.db, tous les posters et fanarts des sites ont disparus?

![xbmc log](https://cloud.githubusercontent.com/assets/9026875/8020225/ead33236-0c68-11e5-88de-6ab4b385f272.JPG)

**Comment by LordVenom** [comment]
Toujours pas possible.Ca vas revenir les posters.

**Comment by TmpName** [comment]
Mais comment tu fais tes logs ? c'est des fichiers jpg ? Essayes par pastebin.

**Comment by arzaz** [comment]
Ok TmpName,

Voici le fichier: http://pastebin.com/5T2TGqW8

**Comment by TmpName** [comment]
Alors je ne peux pas trop te dire, je n'ai pas du tout la meme config que toi mais
DEBUG: Dll libopenmaxil.so was not found in path
Openmax est une librairie specifique au raspberry pouvant servir au decodage jpeg.
