### ISSUE TITLE
zone-telechargement.com

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#158]
Bonjour
zone-telechargement.com c'est un bon site de streaming ou vouz trouvez tout les films 
le seul lien pour le streaming c'est uptobox.

**Comment by arzaz** [comment]
Je suis d'accord avec toi mino60
C'est un site très complet.

**Comment by spiralemystik** [comment]
Peut-on également rajouter libertyland.tv ?
Très complet et vraiment à jour

**Comment by mimoune23** [comment]
pas compris
on peux mettre zone-telechargement sous KODI ?

**Comment by Brahimbaz** [comment]
Bonjour LordVenom, Comment peut-on ajouter http://www.zone-telechargment.com dans vos source de streaming? Merci

**Comment by TmpName** [comment]
Il faut que quelqu'un veuille faire le fichier python pour ce site, ou tu peux tenter toi meme.
Tu as un fichier exemple ici : https://github.com/LordVenom/venom-xbmc-addons/blob/master/ajouter_une_source.py

**Comment by TmpName** [comment]
Je viens de voir ton code sur le beta.
Il vaudrais mieux le mettre dans "resources/sites/trash" vu que le code n'est pas fini.
Chnages le nom du fichier en "zone-telechargement_com"

Par contre pour la suite du code, si tu cherches de l'aide, ca risque de prendre du temps vu que ce n'est pas une periode creuse en ce moment pour le pluggin, pas mal de monde sont deja sur d'autres sources.

**Comment by TmpName** [comment]
Site rajoute officiellement.

**Comment by zombiB** [comment]
trés beau travail fait sur zone telechargement +1 
bravo man !

**Comment by TmpName** [comment]
J'etais pas seul, et la base a été faite par chataigne73.

**Comment by Brahimbaz** [comment]
Merci 1000fois pour zone-telechargement!!!!!! Ça marche nikel pour mon compte uptobox donc streaming à volonté!
