### ISSUE TITLE
Vkstreamingfilm Nouvelle source

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#159]
Bonjour...

j'ai créer une nouvelle source Vkstreamingfilm tout marche bien sauf la partie play video , je croix que le problème et dans les entrées.

vkstreamingfilm_biz.py : 

http://pastebin.com/U8KkAfEd

pour le dévloppement et à partir de la liberté d'oppen source j'ai créer un nouveau plugin.video et je cherche à l'integrer dans le plugin vstream les import ne son pas les mème vkstreamingfilm tout marche nickel mais j'ai un decalage dans les titres , streamviz pas encore terminé

voilà quelque images : 
![sans](https://cloud.githubusercontent.com/assets/11494048/8020319/cc946162-0c74-11e5-8442-69f1cbf8324e.png)
![sans 2](https://cloud.githubusercontent.com/assets/11494048/8020512/af20dd5c-0c7b-11e5-9980-2d06bc3f8bf1.png)

![arts](https://cloud.githubusercontent.com/assets/11494048/8020327/0f9c7d82-0c75-11e5-983c-298eaf7a142d.png)
![streamviz](https://cloud.githubusercontent.com/assets/11494048/8020490/cd8fdc76-0c7a-11e5-852e-22c17c576b8a.png)
![play](https://cloud.githubusercontent.com/assets/11494048/8020359/cf9a6022-0c75-11e5-8dc1-70003d875a0d.png)

le plugin : 

http://www.mediafire.com/download/f3a113rxvc4xm44/plugin.video.nstream.zip

mettre le dossier plugin dans : 
c : user/AppData/Roaming/Kodi/addons/

**Comment by arzaz** [comment]
Bonjour mino60

Ni la source, ni le plugin fonctionnent chez moi.
Avec la source j'ai l'erreur de connexion (Aucun hoster)
Pour le plugin j'ai l'erreur de connexion a nstream

**Comment by mino60** [comment]
effectivement pour le host et play video pas encore terminé par contre le pluguin fonctionne chez moi j'ai désinstaller le pluguin et installer a nouveaux je trouve qui marche nickel!!!!.

**Comment by TmpName** [comment]
Il nous manque un import que toi tu dois avoir.

ImportError: No module named TheYid.common.addon

**Comment by arzaz** [comment]
TmpName,

Merci de revenir avec les fichiers corrigés.

**Comment by mino60** [comment]
pour le module TheYid.common.addon sur c  : user/AppData/Roaming/Kodi/addons/......#  de mon ordi

http://www.mediafire.com/view/raqgjdddwxqkmcu/

pour la version 1.1.2
http://mirror.cinosure.com/superrepo/v5/addons/script.module.TheYid.common/

**Comment by TmpName** [comment]
La modif pr afficher les images manquantes http://pastebin.com/HkWJaf0a

**Comment by arzaz** [comment]
TmpName, mino60 bonjour

Je suis complètement confus, si je comprend bien je dois installer le plugin nstream et le module TheYid dans c : user/AppData/Roaming/Kodi/addons/?
Mais je ne sais pas ou mettre La modif pr afficher les images manquantes http://pastebin.com/HkWJaf0a?

**Comment by TmpName** [comment]
La modif est pour mino60 c'est une correction du fichier vkstreamingfilm_biz.py pour les posters.

**Comment by mino60** [comment]
j'ai éssyé de trouvé une solution pour activer play video mais toujour connexion impossible 

show Hoster
http://pastebin.com/Mn4VdmFD

**Comment by arzaz** [comment]
Après avoir mis  le plugin nstream et le module TheYid dans c : user/AppData/Roaming/Kodi/addons
j'ai l'erreur echec du script nstream!!!!!!

**Comment by mino60** [comment]
@arzaz désolé si ça marche pas avec toi noté bien que c'est pas une source officielle mais c'est just une idé d'un projet pour le developpement du plugin vstream, essyé une autre fois avec ce zip: 

http://www.mediafire.com/download/f3a113rxvc4xm44/plugin.video.nstream.zip

**Comment by TmpName** [comment]
Le probleme ne vient pas de showhoster mais du regex de showMovies, il recupere des '#' a la place des liens.

**Comment by mino60** [comment]
j'ai trouvé la solution pour regex maintenant tout marche bien j'ai la video original anglais VOSTFR et en français sauf il ya une longue lingne "src" a la place du hoster

http://pastebin.com/7K6Sg0JF

**Comment by arzaz** [comment]
Bonjour mino60,
Je viens de faire le test avec 02 films AVENGER & SAN ANDREAS, ca se connecte pendant quelques secondes avec écran noir et un son bizarre puis ca se déconnecte?

**Comment by mino60** [comment]
correction des entrées , pour le film Avenger je ne sais pas ou ai le problème?

http://pastebin.com/E658y3yL

**Comment by mino60** [comment]
Pour le lire le film AVENGER & SAN ANDREAS, c'est corigé la partie hosters

http://pastebin.com/L6PjNjtu

il reste next page et la recherches

**Comment by arzaz** [comment]
Bonjour mino60,

Le plugin tourne seulement sur Kodi Hélix? Qu'en est-il de Gotham 13.2?

Merci

**Comment by mino60** [comment]
j'ai installer kodi Gotham 13.2 sur disque (d : /xbmc.gotham 13.2) et j'ai istaller super repo helix v7
all. puis nstream et ça marche trés bien voila comment installer super repo sur YouTube.

https://www.youtube.com/watch?v=Wof0iZsqsJw

**Comment by mino60** [comment]
Cette fois ça devrait fonctionner avec toi @arzaz le problème c'était le systèm argv je crois

http://www.mediafire.com/download/f3a113rxvc4xm44/plugin.video.nstream.zip

**Comment by arzaz** [comment]
Bonjour mino60,
Désolé mais ça ne veut toujours pas marché j'ai l'erreur échec du script?
Je viens d'installer super repo, mais je n'arrive pas a trouver ton plugin nstream? il est dans quelle catégorie et sous quel nom?

**Comment by mino60** [comment]
Alors essyé ce zip je les testé sur gotham 13.2 

http://www.mediafire.com/download/if998bwk16zqrn7/plugin.video.nstream.zip

**Comment by arzaz** [comment]
Même erreur "échec du script nstream"

Voir le debug file: http://xbmclogs.com/pesccks49

Apparemment le problème est: Error Contents: No module named urlresolver

**Comment by mino60** [comment]
tu doit mettre le fichier urlresolver sur  c: AppData/Roaming/XBMC/addons/

si tu veux l le mode d'affichage sThumbnail a la guauche il ya une fenetre choisir sThumbnail ou Vignette puis par Default

voila une image pour frenchstream.org

![32](https://cloud.githubusercontent.com/assets/11494048/8068715/f1dd5446-0ef5-11e5-9d31-06af10f65e67.png)

**Comment by arzaz** [comment]
Merci de revenir avec le lien pour télécharger urlresolver

**Comment by mino60** [comment]
apparament tu ne utilise pas un PC le log affiche des problèmes pour affiché les image icon ...

url resolver

http://www.mediafire.com/download/bic322c7uucd2yq/script.module.urlresolver.rar

@TmpName ...est ce que en peux afficher sur la dexième page hosters titres et la langue original vostfr français vf sur vkstreamingfilm?

**Comment by arzaz** [comment]
Oui mino60 j'utilise Prismcube, d'ailleurs même avec le script urlresolver je n'arrive toujours pas a tourner ton plugin j'ai toujours cette fameuse erreur échec du script nstream.

Merci comme même d'avoir essayer de régler ce problème

**Comment by mino60** [comment]
le script et presque fini reste la recherche et le resumé

http://pastebin.com/CHDQ8CHf

pour frenchstream
corigé de next page le regex
    sPattern = '<a class="page larger" href="(.+?)">'
hd1080p
    liste.append( ['720p','http://frenchstream.org/qualites/1080p/'] )

**Comment by TmpName** [comment]
Une modif pour la qualitée et la langue
http://pastebin.com/ww7p5deh

Mais fait des tests car c'est une usine a gaz et j'ai pu zapper un truc.

Ne touche pas aux couleurs, je suis sur une fonction qui rajoute toute seule les couleurs.

**Comment by mino60** [comment]
testé ok tres bon travail merci les langues s'affiche en rouge [vo] [VOSTFR] [vf]
pour le next page il ya un problème j'ai seulement la première et la deuxieme page la recherche et trs compliqué a faire

**Comment by TmpName** [comment]
Vais pas pouvoir ce soir mais pr le next page c'est tout con, il te suffit de recupere le lien du symbole ">>" en base de la page
le regex va ressembler a un truc comme ca a class="nextpostslink" rel="next" href="(.+?)">»<a>

J'ai viré les slash, a toi de les remettre.

**Comment by mino60** [comment]
le problème et dans troisieme page <span>3</span> c'est pourquoi que j'ai seulement les deux pages
j'ai esséyé avec Suivant et ça pas fonctionné.

**Comment by TmpName** [comment]
Alors j'ai pas compris, j'ai du me rater hier soir, car ce soir je n'ai pas vu le lien "suivant" sur le site

Un truc qui marche chez moi
http://pastebin.com/h1snnc7N

J'ai du virer un .replace('</span>','') , pas vu a quoi ca te servait.

**Comment by mino60** [comment]
merci maintenant page suivante fonctionne pour la recherche j'ai esseyé mait au lieu d'avoir le titre de la recherche je me trouve sur la première page du site et le résumé pour mettre le script sur vstream beta.

**Comment by mino60** [comment]
j'ai corigé le problème de décalage mais les posters ne s'affiche pas et probleme pour lire la video

URL_BASE = http://www.full-streamvk.com

http://pastebin.com/DMh6hbMp

**Comment by TmpName** [comment]
Pour les poster si c'est le meme site que la derniere fois, tu auras le meme probleme car il n'y toujours pas la correction, cf 4 eme post.

**Comment by santana75** [comment]
Moi aussi J'ai le problème d'affiché plusieur video player Ex : Arrow S1 > E1 >E2

URL_BASE = http://www.vf-streaming.ch

**Comment by TmpName** [comment]
Tu parles de quel site ? full-streamvk.com ou vf-streaming.ch ?
Pour le deuxieme je ne vois pas la source ?
