### ISSUE TITLE
Vstream vide

### ISSUE THREAD

**Issue by spiralemystik** [LordVenom/venom-xbmc-addons#160]
Bonjour,

Tout d'abord un grand merci à toute l'équipe, ce plugin est vraiment top.
Voici mon problème, lorsque j'ouvre Vstream la liste est totalement vide.

Actions déjà réalisées: reboot, uninstall/reinstall plugin et repos, rien y fait.

Ma config: Raspberry B+, Linux xbian 3.18.8+, Kodi 14.2, vstream 0.3.1

Voici ce qui apparaît dans le le log lorsque je lance vstream:

15:21:07 T:2695885840  NOTICE: Thread BackgroundLoader start, auto delete: false
15:21:07 T:3024520208  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
 

Merci d'avance pour votre aide.

**Comment by mino60** [comment]
Bonjour ,,essyé de telecharger le pluguin v 3.1.0 a nouveaux par ce que il a était modifier
supprimer le plugin et installer le nouveau.

**Comment by LordVenom** [comment]
Bonjour, comme le dit mino installer direct par le zip 0.3.1

https://github.com/LordVenom/venom-xbmc-addons/releases/tag/v0.3.1

Ou decompresse direct dans ton dossier addon.

**Comment by spiralemystik** [comment]
Oui, le plugin fonctionne, par contre, a la première page du plugin quand je l'ouvre, la liste est bien la, mais il manque juste les lettres sur chaque ligne, seul les logos apparaissent, c'est pas bien méchant, juste genant

**Comment by mino60** [comment]
si le problème persiste je te propose de désinstaller kodi 14.2 carrément et de le  réinstaller de nouveaux
et compléter le processus d'installation du plugin vstream (pour le but d'éffacer les fichier data) ,
j'espère que ça t'aidera pour résoudre votre probleme.

**Comment by TmpName** [comment]
Tu utiliserais pas une autre langue que le francais ?

**Comment by mino60** [comment]
effectivement le probleme c'était la langue j'ai changé la langue (englais) et j ai un le meme problème
en choisissant la langue french system Appearance international langue french le problème disparaît.

**Comment by spiralemystik** [comment]
La méthode du string ne change rien, par contre, en changeant la langue ça fonctionne.
