### ISSUE TITLE
installation vstream j'y arrive pas

### ISSUE THREAD

**Issue by mimoune23** [LordVenom/venom-xbmc-addons#163]
si quelqu'un peux prendre quelque minute

 j'ai telecharger le repository repository.vstream puis je l'ai installer
j'ai systematiquement une liste vide

comment faire ?

**Comment by TmpName** [comment]
Tu as quelle langue sur kodi ?

**Comment by mino60** [comment]
Tu doit mettre la langue (french) sur le system Apparance, il ya un problème avec la langue.

**Comment by mimoune23** [comment]
Merci

effectivement avec ce paramètre cela fonctionnne

merci encore
