### ISSUE TITLE
REGEX Film-streaming.ws

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#164]
je cherche le regex de film-streaming.ws pour affiché les films

http://pastebin.com/8sJhhV3V

**Comment by TmpName** [comment]
http://pastebin.com/Gy1Kn4eC

**Comment by mino60** [comment]
j'ai essyé avec votre code mais il marche pas?.

**Comment by mino60** [comment]
j'ai trouvé beaucoup de films blu ray 720p sur zonne.de.telechargement (uptostream) , mais je n'arrive pas a comprendre cette héberjeur des fois les liens fonctionne et des fois ne marche pas, just un message que vous n'ete pas premuim?

**Comment by TmpName** [comment]
C'est normal, cet hebergeur est limité en temps.
1.5h sans enregistrement 2 ou 3 h enregistré, illimité pr premium (ou un truc comme ca, c'est de memoire), mais il vaut le coup car la durée est suffisante pr un film.

Teste en ne copiant que le regex, et pas le reste du code.

**Comment by mino60** [comment]
la liste des films s'affiche par contre la section tout les films erreur connection impossible
j'ai utilisé print sTimb mais les posters ne s'affiche pas ?
sur la s'ection genre la valeur </a> a coté des titres ?
j'ai utilisé pour Next page la fonction Suivant mais ça ne fonctionne pas
derniere question est ce que on peu lire les video de ce site vue qu'il utilise jwPlayer vertion pro et des lien swf et le debrideur?
http://pastebin.com/Nvc68Xd7

**Comment by mino60** [comment]
j'ai ajeuté la valeur a sur le regex le problème a disparue sur la section genre mais problème sur new movies

http://pastebin.com/zLM3n3HF

**Comment by TmpName** [comment]
Pero, je n'ai pas pu tester, avec le pastebin de 2 post au dessus

>> [PLUGIN] Vstream: Cant import plugin film_streaming_ws

**Comment by mino60** [comment]
essyé la vertion vstream 0.3.2 plus le script film_streaming_ws

http://www.mediafire.com/download/w11wg391u2hv9tq/plugin.video.vstream.zip

**Comment by TmpName** [comment]
Bon en prennant le fichier film_streaming_ws.py de ton archive ca remarche.
Alors pour les poster "print sThumb" donne "http://www.film-streaming.wsinumber-number-streaming.php " ok pas besoin daller loin pour voir l'erreur.
Quand on clique sur un film on a

>> Failed: Couldn't resolve host name(6) for http://www.film-streaming.wscroisades-streaming.php/ 

Manque un "/" dans le lien.

Et plus bas 
>> oHoster = __checkHoster(sHosterUrl)

Y a pas de fonction __checkHoster dans ton code.

J'ai pas eu le temps de regarder plus loin.

**Comment by mino60** [comment]
j'ai réglé le problème des posters son utilisé print sThumbnail, maintenant j'ai utilisé >> Suivant pour le Next page mais ça marche pas, reste la partie la plus délicate showHosters et play video

http://pastebin.com/qcBmvX8Q

**Comment by TmpName** [comment]
Alors pour le next page, je sais pas pkoi mais je n'ai pas exactement le meme code mais j'aurais fait exactement le meme regex que toi, faut verifier si il n'y en a pas plusieurs, moi je n'ai pas cette partie "<a class="btn" quand j'affiche le code.

Showmovies n'est pas terminé.
>> [PLUGIN] Vstream Erreur: Connection Impossible,wolves-streaming.php

Oui il y a moyen d'afficher un clavier pour selectionner la page, c'est pas bete a voir a mettre ca en menu contextuel avec les favoris. Mais perso je ne vais jamais plus loin que la 3/4 eme page.
Apres si tu veuxx reprendre a la 200 eme page .......^^.
Si j'ai le temps v rajouter un truc en menu contextuel sur le "suivant" ou tu pourras choisir la page.

Il y a plus simple que d'utiliser 2 showmovies.
1 - Tu compare les liens eg si il y a le mot 'news' ou juste la racine du site (faut trouver une difference netre les liens

>>if 'blabla' in url:
        spattern = '11111'
else:
        spattern = '222222'

2 - Fusionner les 2 regex, si il y a peu de difference entre les deux, donne moi les  2 regex, je te dirais si je peux.

3 - Methode bourrin. si le premier regex ne donne pas de resultat aResult[0] == false, tu recommence avec le second.

**Comment by TmpName** [comment]
Bon ben le clavier virtuel pour selectionner la page on oubli.
Il faudrait refaire tout les sites avec une fonction speciale, et selon les sites elle risque de piquer pas mal les yeux.

**Comment by mino60** [comment]
voila les deux pattern


http://pastebin.com/QaY9XSQi

page Next

http://pastebin.com/g6JDsLDS

**Comment by TmpName** [comment]
Bon ben je comprend pas moi j'ai pas le meme http://pastebin.com/88DaHcMP
Du coup essaye celui que je te propose, il devrait marcher pour toi et moi, comme ca ca resout le probleme. A voir comme Vstream traite les crochet ">" ou "&gt;"

Pour tes 2 Regex la seule difference c'est un "<\/a>" donc il te suffit de faire (?:<\/a>)* et tu peux meme virer le precedent du coup.
* = 0 ou plus du precedent token
(?:XXXXXXXXX) C'est pour creer "un groupe de token" qui n'apparaitront pas dans les resultats.

**Comment by mino60** [comment]
maintenant c'est bon pour movies news merci pour votre votre aide me serait précieuse , mait toujour connection impossible erreur script pour Next j'ai passé une nuit blanche pour ce probléme
je crois que il manque une partie de l'url est ce que en peu utilisé print comme print sThumbnail
pour le "href"?

http://pastebin.com/h92X9cMw

**Comment by TmpName** [comment]
Next page http://pastebin.com/vyTt3q2u

Tu avais raisons il manquait une partie de l'url

En fait la fonction "print' sert juste a afficher le contenu d'une variable dans le log, en aucun cas ca ne modifi le comportement de ton code.
Si tu avais fais

>>print sNextPage

Ca aurait juste affiché dans les logs "films.php?page=3" tu aurais juste pu voir que l'url etait incomplete, mais ca n'aurait pas corrigé le bug.

**Comment by mino60** [comment]
Next page problème résolu finalement merci pour votre aide cordialement ça  m'a prit beaucoup de temp pour rien au point que je voulai abandonné ce travail.
pour la recherche j'ai le mème probleme avec vkstreamingfilm.fr la recherche affiche la première page du site mais j'ai remarqué que la recherche sur film-streaming.ws mene a la deusième page showHosters direct pour lire la video alors je crois qu'il faut trouvai le regex de showHosters comme sur vanoz?

**Comment by TmpName** [comment]
Je viens de voir que le le site avait chnagé de nom.
Par contre tu peux oublier la recherche, elle ne marche pas sur leur site, essaye avec le mot "dead" qui est dans plusieurs sites, tu n'aura qu'un seul resultat a chaque fois.

Si tu veux quand meme la faire le lien de recherche est "http://www.hd-stream.co/search.php?movie=mot_a_chercher" et non pas "film-streaming.ws/?s="

Et cela n'ouvre pas une nouvelle page mais redirige directement sur le resultat.

**Comment by mino60** [comment]
ça n'a pas l'air très facile tout ça? qu'elle lien à recuperé j'ai pas comprie comment décodé les liens 
au moment où je cherche comment regarder les video de ce site sur kodi?

les liens de ce site ce trouve sur la deuxième page avec l'url des posters
exemple:
 

<script type="text/javascript">
    jwplayer("myElement").setup({
		
	   image: "http://www.film-streaming.ws/thumb/la-planete-des-singes--laffrontement-2.jpg",
            file: "http://debrideur-3.hd-stream.co/mp4/aHR0cDovL3d3dy4xc3QtZmlsZXMuY29tL2w0N3Npcnp0YmVrMQ==-hd.mp4",

sur archive.org j'ai mit quelque films de cette source
j'ai mit le code de la desieme page sur url.enconde.decode.com j'ai une grande page crypté 

est ce que il ya un systeme qui lence la video direct son passé par une deuxieme page?

**Comment by mino60** [comment]
Bon je trouve que le deuxieme site et mieux que le premier et pour cella j'ai crées un nouveau script hd_stream_co.py
http://pastebin.com/dvkR95jp

tout marche bien sauf la partie play video mait il faux utilisé la deuxième pattern du site film-streaming.ws la fonction "else" n'a pas fonctionné pour moi?..

**Comment by TmpName** [comment]
Pour moi te prend pas la tete oubli "film-streaming.ws" j'arrive pas a me connecter dessus, a chaque fois je suis renvoyé sur l'autre, a mon avis dans quelques jours le premier sera fermé.

Tu parles de quels "else", le seul que je vois c'est celui utilisé pour la recherche ?

**Comment by mino60** [comment]
Bonjour ...
mais avec ce script on a les deux site à la fois, la fonction "else" sur shoMovies attention il ya (#) sur regex j'ai regardé le script mangacity il ya boucoup de manip a faire et c'est defficile pour moi de comprendre ce script.

http://pastebin.com/wG35sy75

**Comment by mino60** [comment]
sur full-streamingvk.com la fonction showHosters j'ai une erreur de script sur le log kodi m'indique qu'il ya une erreur sur la ligne 189 (print aResult) je les supprimé maintenant il n'y a pas d'erreur mais les hosters ne saffiche pas?

http://pastebin.com/82yuDa32

**Comment by TmpName** [comment]
Alors pour info suis overbooké pour 1 semaine au moins donc vais pas pouvoir te refaire tout le code, mais deja.
1 - l'erreur du print aresult c'est normal tu fais
>>affiche le contenu de aresult
aresult = contenu

Tu demandes a l'afficher avant d 'y mettre un contenu.

2 - Le probleme du else, perso je lai vu correct, tu n'as pas oublié les espaces a la con (et ouais c'est de la merde le python)
Ca doit ressembler a quelque chose comme ca > http://pastebin.com/ASuCyJaC
Les chaines doivent etre entre guillemets aussi.

3-Tu as virer des trucs indispensable du code, celui que tu as est inutilisable
>> http://pastebin.com/agcyKm8D

**Comment by mino60** [comment]
pour la premier toujour erreur script
aresult = contenu
http://pastebin.com/qBQx5CzM
 (2)
le truc else il marche maitenant mait il manque la pattern 3 pour le deuxieme site section
http://pastebin.com/DUKXKqwh

je crois qu'il vaut mieux d'utiliser un seul site pour eviter les erreurs le site hd-stream.co remplace le premier.

(3)

la fonction showHosters c'est pour vkstreamingfilm.biz je crois ou il y a la qualité
j'ai essyé avec mais toujour erreur script.

**Comment by TmpName** [comment]
Quand je mettais "contenu" c'etait juste pour expliquer, en fait le contenu c'est oParser.parse(sHtmlContent, sPattern) il faut juste inverser les deux lignes, d'abord tu met un contenu dans la variable et apres tu l'affiches pas l'inverse.

Non il te faut refaire le code, le seul code dont tu te sert c'est la fonction unescape() en haut du fichier et les 3/4 ligne d'un de mes precedent post.
Le lien qui se termine par mp4 est invisible c'est pour ca qu'il te faut passer par le site que j'ai donné plus haut aussi pour le voir.

sPattern = (toute la chaine a la con commencant par document.write(unescape"))
aResult = oParser.parse(sHtmlContent, sPattern)

if aresult[0] = true:
       chainedecrypte = unescape(aresult[1][0])
      sPattern = (lien url direct commencant par http et finissant par mp4) 
      aResult = oParser.parse(chainedecrypte , sPattern)

if aresult[0] = true:
     ton lien  = aResult[1][0]

Et c'est fini tu as deja ton lien te faut juste le renvoyer, y a pas de hoster, c'est fini
Ne pas oublier de copier la fonction complete dans ton nouveau fichier

**Comment by mino60** [comment]
j'ai mit ça sur showHosters mais les films ne saffiche pas probablement une erreur python

http://pastebin.com/j7SsetWM

**Comment by TmpName** [comment]
???
Tu vas pas me dire que avec ce pattern
sPattern = '<div class="fstory-video-block" id="(.+?)"><center>.+?<iframe.+?src=[\'|"](.+?)[\'|"]'
Tu arrives a recuperer la chaine crypté avec plein de %%%% ?

chainedecrypte est une variable pas une fonction c'est comme le aResult.

**Comment by mino60** [comment]
j'ai modifier le script et je l'ai mème pas essyé par ce que je suis sure qu'il contien des erreur!

http://pastebin.com/1U8WA3V5

**Comment by mino60** [comment]
pour full-streamingvk.com  
erreur : non définie
if (aresult[0] == True):

http://pastebin.com/1WtQh8WJ

**Comment by TmpName** [comment]
Alors je te file un bout de code fonctionnant mais avant j'aurais 2 3 questions.
>>sUrl = URL_MAIN+str(aEntry[1])
oOutputParameterHandler.addParameter('siteUrl', str(aEntry[2]))

Tu as deja fais un print Aresult, mais tu as deja lu ce que te donnait le debug ? Tu te fais chier a refaire un lien a partir de aEntry[1] et au moment de le donner a la fonction tu lui passes aEntry[2]. En passant c'etait tout faux, le lien etait dans aEntry[0] ca prend 10s chrono pour s'en rendre compte.

Je te vois utiliser ses pattern
>>sPattern = '[src|SRC]=(?:\'|")(http:.+?)(?:\'|")'
sPattern = 'encodeURI\("(.+?)"\)'

Je suppose que tu n'as jamais testé ces 2 regex avec le code html car dedans il n'y pas plus de encodeURI que de SRC.

C'est rapide de faire des copier/coller moi je ne fais que ca aussi, mais quand j'en fais un je retire TOUT le code dont je ne vois pas l'utilité, et je copis pas de code dont je ne comprend pas le but.

>> if 'hd' in sUrl:

Ne marchera plus car now il y a 'hd' dans le host du site.

Lien >> http://pastebin.com/7e4XmkBE

Va voir comment je decode le lien ca prend meme pas 10 lignes et c'est 10 fois plus simple que tes pavé de code. Faut arretter d'avancer a tatons.

**Comment by mino60** [comment]
pour votre question : 
sUrl = URL_MAIN+str(aEntry[1])
oOutputParameterHandler.addParameter('siteUrl', str(aEntry[2])) 

je ne trouve pas cette partie decode sur pastebin , pour les entrées je l'ai ai essayé tout (aEntry[0]), (aEntry[1]), (aEntry[2]) son succès

pour votre dexième question (c'est toi qui ma dit qu'il ya une fonction déjà prêt sur MangaCity) 
sPattern = 'encodeURI("(.+?)")' j'ai pensé que c'est la pattern qui encode l'url

j'ai essyé votre code mais marche pas just sur kodi message Encours puis retour vers le titre de la video.

dés fois la logique ne suffit pas dans le langage python que signifie avoire une base de connaissance informatique qui se procure après des années d'expérience dans ce domaine

**Comment by TmpName** [comment]
"top film" ne marche pas, le seul endroit ou j'ai trouve le film "get hard"
Testes a "film nouveauté"

**Comment by mino60** [comment]
j'ai testé avec le film  "the gambler" erreur script

http://pastebin.com/0SFJrXsK

**Comment by TmpName** [comment]
Essaye ici > http://www.cjoint.com/c/EGhuSoA3FEx

**Comment by TmpName** [comment]
Tu peux essayer celui la > http://www.cjoint.com/c/EGhuSoA3FEx

Mais je vois deja un probleme de codage, je t enverrais le fichier autrment demain.

**Comment by mino60** [comment]
pour une fois j'ai utilisé ma ma cervelle son avancer à tatons!!!... maintenant les hosters s'affiche Mai.ru host qui marche pas tout comme OK.ru vidto fichier introuvable 

log.xbmc full-streamvk.com

http://pastebin.com/zpr2bYAJ

**Comment by TmpName** [comment]
Bon j'ai re-essayé pas de probleme.
Apparement tu as une error 404, essaye de te connecter directement a l'adresse en question pour voir si ce n'est pas le site qui est juste en cours de modification.
h tt p://w w w.hd-stream.co/the-gambler-streaming.php

Pour le probleme de la deuxieme pagen je ne sait pas comment tu as fait ca mais il manque une partie du lien.
Je fais
>> oOutputParameterHandler.addParameter('siteUrl', URL_MAIN + str(aEntry[0]))

Donc il est impossible que la fonction showHosters recoive un lien sans la valeur de URL_MAIN en premier.
Mais dans ton log tu reussi a avoir 
>>siteUrl=the-gambler-streaming.php

Tu es sur de ne pas avoir 2 fichiers et de les croiser ?

Si tu met un 
>>cConfig().finishDialog(dialog)

C'est que a un moment tu as crée un dialog appelle "dialog" sinon tu veut finir quoi comme dialogue ?

Quand on passe par "top film" ca ne marche pas car le regex est foireux, l'image et le lien sont inversé.

**Comment by mino60** [comment]
le log: http://pastebin.com/xxTVmfAq

http://w w w.hd-stream.co/the-gambler-streaming.php mene sur la dexième page ce qui veux dire
http://w w w.film-streaming.ws/the-gambler-streaming.php (sur firefox)
pour la deuxième question je ne sait pas comment j'ai fait ça le script et devenu cuisine chinoise je me rappelle de rien suffe que j'ai modifien quelque lingne dans le regex que je je les ai emprunté de sur mangasity

**Comment by TmpName** [comment]
Essaye avec ca http://pastebin.com/8gMQjMx5 ca va t'afficher plus d'infos

Mais moi quand j'essaye sur firefox je reste sur hd-stream.co je ne bascule pas sur film-streaming.ws.
Tu peux aussi en changeant le host dans les headers si tu bascule a chaque fois.

**Comment by mino60** [comment]
Bon ben merci pour votre aide mais je crois que c'est pas utile vue que le site film-streaming.ws ai offf fermé.
un nouveau site www.hd-streaming.co meme ils on changer leurs code

http://pastebin.com/R5aS4jun

j'ai crees un nouveau script mais je crois que le regex n'ai pas correct

http://pastebin.com/ewjjUhcj

**Comment by mino60** [comment]
j'ai modifier la pattern les titres posters s'affiche maintenant 

http://pastebin.com/nwHsPBqE
log:
http://pastebin.com/Jntx15pQ

**Comment by mino60** [comment]
hd-stream.co    http://pastebin.com/1fpnwKgi

logXBMC:   http://pastebin.com/TaU3ydut

je crois le problème c'est url_main il manque film-streaming.co sur sUrl .

**Comment by TmpName** [comment]
Ben en fait je comprend pas tu as 2 erreurs
siteUrl=http%3a%2f%2fwww.hd-stream.co%2fkundo-streaming.php
et
siteUrl=snow-in-paradise-streaming.php

Le premier cas marche chez moi, y compris sur firefox, ta machine n'est pas sous windows ? Faut voir en rajoutant "http://" devant, mais je pense que la difference vient de nos systemes.

Le second cas, je ne sais meme pas comment tu arrives a le produire. cf 6 post au dessus, mais c'est bien ca il te manque le debut de l'url.

**Comment by mino60** [comment]
tu veux dire que tu as réussi a décrypté le lien et de voire la videos sur kodi? pour le systèm je suis sur Windows7
pour info j'ai mit le script avec le log de chaque cas!!!

**Comment by TmpName** [comment]
Comme source j'ai essayé celle que tu as donné 3 post au dessus, et le premier pattern deconne deja, je n'ai aucun film.

Oui, je suis arrivé a voir la video (enfin avec l'avant derniere version vu que la derniere je n'ai aucun film), la ou toi tu as un error 404, dans le premier cas, pour le second j'arrive meme pas a reproduire ton bug.

**Comment by TmpName** [comment]
Bon alors je confirme, ca marche chez moi mais j'ai du remettre les modifications que je t'avais données, et que tu as retiré encore une fois.

Modif se trouvant dans le meme post cité precedement.

**Comment by mino60** [comment]
tu peux posté ton code ici pour voire comment ça marche en faite sur le site comment ça marche il y a un membre qui ne peux pas voire la video sur hd-stream.co c'est bizarre http://www.commentcamarche.net/forum/affich-31866420-site-s-fiable-s-pour-films-en-streaming

**Comment by TmpName** [comment]
Ben c'est le meme que la https://github.com/LordVenom/venom-xbmc-addons/issues/164#issuecomment-119254356

**Comment by mino60** [comment]
j'ai mit les trois sources pour test sur vstream beta

- hd-stream.co
- full-streamingvk.com
- streamingmy.com

sur streamingmy il y a une nouvelle fonction goto page clavier virtuel pour choisir la page

j'ai trouvé un code pour ça mais je n'arrive pas a le mettre sur le script

http://pastebin.com/GmKW1mbV

        from core import AddonCore
        from xbmcdict import XBMCDict
        from BeautifulSoup import BeautifulSoup, SoupStrainer, Comment
        from favorites import ContextMenu as Fc

AddonCore
 core.py
http://pastebin.com/3eDayxzb

sesting.xml language
http://pastebin.com/0UisR7ET

**Comment by TmpName** [comment]
cf http://pastebin.com/sKsmXYTQ

**Comment by mino60** [comment]
j'ai essyé  mais toujour erreur script !!???..

voici le log : http://pastebin.com/21viSTSu

**Comment by TmpName** [comment]
https://github.com/LordVenom/venom-xbmc-addons-beta/issues/59#issuecomment-121230191

Suis desolé, mais c'est peut etre ta version de kodi qui n'est plus a jour (vielle version de urlib2).

Franchement tu peux te connecter sur le site via firefox mais tu as une erreur 404 avec vstream, je vois pas le probleme.

**Comment by mino60** [comment]
j'ai essué avec kodi 14.2 toujour rien

http://pastebin.com/6PmS3xNS

**Comment by TmpName** [comment]
Il y a une petite protection sur le site (qui justement renvois sur un 404) c'est pour ca qu'il y a autant de code, demain j'essayrais de te faire passer une variante, mais regarde si c'est pas une histoire de reglage dans kodi.

**Comment by mino60** [comment]
j'ai crées le script film-streaming.co direct pour ne pas avoire des erreure helas c'est toujour pareil

script : http://pastebin.com/SvsSfh1B
log : http://pastebin.com/xNXi09L4

remarque sur film-streaming.co c'est le site qui contien les liens du streaming les pages ne son pas disponible pour le moment.

**Comment by TmpName** [comment]
Bon ben bne nouvelle, depuis la fermeture du precedent site, ils ont viré la protection, du coup le code est tout simple, mais si celui la ne marche pas, je n'ai plus d'idees

http://pastebin.com/EqDuFKJD

**Comment by mino60** [comment]
cool le probléme a était résolut merci pour votre aide précieuse j'ai vue le code mais rien a changé par apport a celui d'hier

  http://pastebin.com/DZGjD4fK

ça marche pour moi  ( if 'hd' in sUrl: )

j'ai ajouté Top films a la place de film Nouveautés par contre la recherche ne fonctionne pas

si vous pouvez mettre a jour le script full-streamvk.com je n'arrive pas a le faire sur Beta

http://pastebin.com/Xyt2ZtH4

**Comment by mino60** [comment]
Pour le site film-streaming.co j'ai edité le script qui marche trés bien sauf problème next page je peu aller jusqu'à la deuxième page et la fonction rechrche 

http://pastebin.com/iajW2fBP

est ce que on peu utilisé la fonction goto page avec le code que j'ai posté 9 post on haut?

**Comment by TmpName** [comment]
Alors, jespere que vais repondre dans l'ordre.

Il y a des modifs dans showHosters() (2 lignes a la place de 5/6)

Je t'ai mis a jour le fichier sur la beta pr fullstreamvk mais pour info tu as dedans "import urlresolver" qui ne te sert a rien (ou j'ai pas vu) et qui risque de faire planter si la personne n'a pas la librairie.

Pour le reste je m'y met de suite et j'editerais le post plus tard

**Comment by mino60** [comment]
mais tu na pas repondu sur le problème de next page pour film-streaming.co

j'ai mit ça


    {sPattern = '<a class="btn btn-default" href="([^<>]+?)">[0-9]+<\/a>'}

http://pastebin.com/6tz0VavS

est ce que tu a la section genre sur hd-stream.co

pour les film qui manque sur film-streaming.co 
voila leur code

http://pastebin.com/pusEQsSH

**Comment by TmpName** [comment]
D'apres ton propre log on voit que le lien n'est pas bon
>>09:24:08 T:6968 NOTICE: [PLUGIN] Vstream: Hoster - play ('video4', 'http://vidto.me/embed-pb9qfeo972nq-644x366.html')

ca devrait etre 

>> 09:24:08 T:6968 NOTICE: [PLUGIN] Vstream: Hoster - play ('http://vidto.me/embed-pb9qfeo972nq-644x366.html')

**Comment by mino60** [comment]
on faite le regex était mauvais je les corigé maintenent tout les films s'affiche

http://pastebin.com/jJDXVPFj


ta pas une soluce pour Next page film-streaming.co?

**Comment by mino60** [comment]
j'ai oublier une chause importante le "résumé" j'ai edité la pattern mais ça ne marche pas

{     sPattern = 'document.write\(unescape\("(.+?)"\)\);<p><strong>Synopsis :</strong><span class="std">(.+?)</span></p>'    }

**Comment by TmpName** [comment]
Je veux bien te mettre la correction sur la beta moi meme, mais me faut le pastebin complet et final.
Pour ton bug mail.ru, j'ai essayé le meme lien que dans ton navigateur (cf ton screenshoot) et j'ai eu la video et non pas ton message.

Si tu vois mail.ru deconner dans les sites DEJA PRESENT et non pas en cours de developpement, ca m'interesserais, mais la je n'ai pas encore vu de probleme.

**Comment by mino60** [comment]
full-streamvk : http://pastebin.com/eiVmQe1A

pour suivant j'ai essyé .+? a la place des chiffre mais ça n' a pas résolu le problème!

pour next page voici leurs code : http://pastebin.com/6tz0VavS



mai.ru foctionne sauf quand je clic sur watch video qui ai on bleu sur screenshot

**Comment by mino60** [comment]
est ce que il ya un moyen pour que la recherche sur la source film-streaming.co aboutie directement sur le résulta exemple je cherche le film Winter sleep sur le clavier virtuel pour avoir ce esultat directement?
![sans titre](https://cloud.githubusercontent.com/assets/11494048/8757066/8a804ff6-2cd7-11e5-8f1c-4e089bb6e208.png)

**Comment by LordVenom** [comment]
Je pense pas non il faudrait tout re-coder.

**Comment by TmpName** [comment]
Il y a juste un clik en plus pour acceder au film, c'est pas mortel, surtout si tu cherche un mot comme "dead" ou tu vas obligatoirement avoir plusieurs choix possible.

Avec juste .+? tu vas avoir 50 concordence trouvé sur la page, il te faut un regex moins permissif, utilise le lein que t'as donné Venom et fait un c/c de la page complete dedans pour tester tes regex.

**Comment by mino60** [comment]
Il n'y a pas plusieur choix possible sur se site 

chercher : Ded .....Résultat = Dead or Alive en Streaming HD

il y'a un seul résultat mais quant tu veux voir un film qui se trouve entre la page 457 par exemple il aura un grand boulot à faire sur Next , c'est pour ça la fonction cherche ou goto page ai indispensable, ne pense pas à toi seulement qui ne depasse pas la troixième page don le monde cinema il ya un large public avec une différence de goûts( il y a un public qui aime les vieux film generalement les vieux films son dont les dernière page).

**Comment by TmpName** [comment]
Tu ne trouvera pas plus de vieux film entre la page 457 et 500 que 212 et 230, sinon tu passes plus de temps a regarder les film presentés que de voir le film, c'est pour ca que me sert a de la recherche.
Quand j'allume la machine j'ai 5mn montre en main pr trouver un film a regarder sinon ma copine fini de manger et repart  avant le lancement du film.

Sinon oui tu as raison, me souvient maintenant de ce site, et donc oui on peut faire acceder directement a la page du film du coup vu qu'elle ne peut en afficher qu'une.

Deux possibilitées.
1 - la facile modifier la fonction showSearch pour quelle renvois sur showhoster au lieu de showmovies
2 - la complexe mais plus propre, modifier showmovies pour "re-router" vers showhoster en cas de recherche

**Comment by LordVenom** [comment]
J'ai fait une correction dans 
https://github.com/LordVenom/venom-xbmc-addons/issues/189 Pour pouvoir lire direct.mais ça vire la fonction automatique de marque lu.

**Comment by TmpName** [comment]
Pour la fonction re, ca doit etre de ma faute, il ya tellement de bidouillage sur ce site, la fonction unescape ne sert plus non plus, et la fonction DecoTitle est maintenant obsolette vu que tu as integré la fonction nativement dans Vstream.

**Comment by mino60** [comment]
j'ai mit film-streaming.co sur beta mais son showHosters qui marche avec "cPlayer"
parce que : 
1 - ça vire la fonction automatique de marque lu.
2 - on peut pas faire la fonction recherche.
3 -  on peut pas faire le résumé du film qui se trouve sur la deuxième page.
4 - l'image pour les posters "a" introuvable lors de la lecture de la vidéo 
     http://uploadpie.com/MDlet
     http://uploadpie.com/yKyQA

généralement la source film-streaming.co on est presque fini pour l'avoir prochainement lors de la mise à jour vstream il reste juste : 
- fonction recherche
- résumé du film

**Comment by LordVenom** [comment]
pour film_streaming-co
Rien vue passer par contre moi je les mis et je vient de faire la mise a jour pour la recherche.
ça enlever toujour la fonction lu (automatique) mais c'est pas trés grave je regarderais a l'occasion.

pour film_streaming-ws ça apporte rien de plus si ?

**Comment by mino60** [comment]
trés bon travail la fonction rechercher un film ça marche à merveille merci par contre il manque quelque détails  je les ai ajoutés (sThumbnail sur result search) pour affiché le mini poster sur le lecteur player : http://uploadpie.com/yKyQA) et sur les imports

http://pastebin.com/jgjPXSm8

**Comment by LordVenom** [comment]
Ok corriger par contre j'ai repris que t'est modif sur showhoster le reste et inutile.

**Comment by mino60** [comment]
l'effet  d'avoire une vidéo passer à l'arrière-plan (obtenir les vidéos pour démarrer automatiquement en arrière-plan) j'ai vue cette fonction sur un script qui utilise "cPlayer".
 à vrai dire, je sais pas trop à quoi ça sert exactement .

**Comment by LordVenom** [comment]
Dans ce cas present a rien :)

**Comment by LordVenom** [comment]
Je sais plus qui parler d'un go page j'ai tester sur film_streaming_co. 
pas super simple a faire et pas trés utile pour moi mais bon y a pas d'import de malade tous etait deja pratiquement fait.peux être @TmpName  pourrais tu regarder et améliorer ?

**Comment by mino60** [comment]
j'ai testé la beta maintenant la fonction "goto Page" fonctionne super bien je ne vois pas comment l'améliorer...enfin c just une preference qu'il y a à la place de Entré une page "Goto Page de 1 à xxx
xxx: c'est la dernière page sur le site mais comment trouvé ça?

http://pastebin.com/pADnY13a

**Comment by mino60** [comment]
Erreur Next Page sur full-streamvk.com corigé ; http://pastebin.com/zRRzV0N0

**Comment by TmpName** [comment]
Ben moi non plus je ne vois pas trop comment l'ameliorer, la j'ai fait un changement comme le veut mino60, ca affiche now 25/789.
Mais je trouve ca lourd, quelques idées ?
+Regrouper nextpage et showpage , pour acceler le traitement des regex vu que c'est la meme partie qui nous interesse et mettre le 2/788 sur next page.
+Mettre le selectpage en menu contextuel sur le next page
+Rajouter retour Home, quitte a choisir la page pkoi pas revenir direct au debut (plutot que faire 5/10 fois precedent), ca c'est possible en menu contextuel par exemple et sur toute les sources sans trop de modifs.

**Comment by LordVenom** [comment]
J'y est penser dans la journée aussi, il faut regroupe nextpage et goto page.Pour moi il faut rester dans le gui le context menu uniquement pour les fonctions spécial, en plus par le gui c'est plus simple.Oui pour le retour home.

**Comment by mino60** [comment]
j'ai corriger le problème que j'ai constaté sur la remarque précédente on faite j'ai juste ajouté une étoile à la fin regex pour Go Page son savoir exactement à quoi ça sert mais maintenant les num s'affiche à leur valeur exacte !

{     sPattern = '((?:http://www\.film-streaming\.co/).+?.(?:php))(?:\?page.+?(.?\d*)|)'     }.

**Comment by LordVenom** [comment]
J'ai fait une modif pour tous rassemble, je pense que c'est trop lourd.Pour moi il faut virer le 1/170 trés sympas a voir mais pas a faire.

**Comment by mino60** [comment]
je trouve que la modif ai impeccable du sort quand peut connaitre le nombre de pages de la selection sur le site j'ai fait une modification sur la couleur des nums

http://pastebin.com/Z7P44TbU

just pour info la section genre ne fonctionne pas!.

**Comment by TmpName** [comment]
Les masquer a la recherche 100/100 ok et c'est facile avec sSearch mais j'ai pas trop suivi ce qui a été validé ou pas.
De mettre tout ca en context menu c'est ok ou non ? Je reconnais que peu de gens y penseront mais peu de gens ont besoin de faire defiler 50 pages.
Parce que 2 liens c'est deja lourd, du coup le "retour home" on va pas le rajouter dans le code actuel.
Pour le retour home par contre j'avais prevu de le mettre en standard ( car ca va etre exactement le meme code pour tout les sites)

**Comment by LordVenom** [comment]
Effectivement ont peux tester dans le context menu.

**Comment by LordVenom** [comment]
Bon pour simplifié, je pense qu'il faut pas garder le 1/100 tous les site le gère pas et c'est pas trés utile.

- Dans le context de next page il faut créer une function qui recupere l'url de base de next http://site.com/page=2 par exemple faire un script qui vire 2 et remplacer par le numéro taper dans le dialog. comme ça tous les sites peuvent en profiter sans grosse modif de notre part.

- Dans le context crée un lien Home trés simple a faire et il fonctionneras direct sur toute les sources.

**Comment by TmpName** [comment]
D'accord avec le 1/100, au pire il y a la possibilité de le faire dans le fichier site et non pas le gui, donc faisable au cas par cas.

Bon sinon j'ai commencé mais pas le temps de finir pour ce soir, j'ai mit le debut sur la beta, aucun changement du code actuel, modifs invisibles. En fait j'ai rajouté une fonction Addnextpage juste pour ce lien avec un menu contextuel special.

Et j'ai pas corigé le regex non plus, mais c'est pas le plus long.
