### ISSUE TITLE
Les titres de section n'apparaissent pas dans le plugin

### ISSUE THREAD

**Issue by philippedurocher** [LordVenom/venom-xbmc-addons#165]
Désolé, je voulais pas créer un ticket pour mon problème mais c'est la seule place que j'ai trouvé.

Vstream fonctionne #1 sauf que je ne vois pas les titres des sections (voir l'image)
![image](https://cloud.githubusercontent.com/assets/1459389/8144893/6c180898-11bf-11e5-9184-a142a1a0077c.png)

Merci, super plugin pour du contenu franco.

**Comment by mino60** [comment]
Tu doit selectionné la langue french ( SYSTEM / Apparance / international ).

**Comment by philippedurocher** [comment]
Voilà! Ça fonctionne, c'est super! Merci et désolé d'avoir ouvert un ticket pour ça ;(

**Comment by LordVenom** [comment]
Bonjour, pas de soucis c'est fait pour.Par curiositer quel langue etait séléctionner ?

**Comment by philippedurocher** [comment]
J'étais par défaut à « English »

**Comment by philippedurocher** [comment]
Hier j'ai installé une nouvelle box avec Kodi et j'ai plutôt sélectionné la langue *Français (Canada)* et encore une fois, je ne voyais pas les titres dans vStream.
