### ISSUE TITLE
Nouveau lecteur HTML5 son flash sur Poypi/Zopap.com

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#166]
bonjour le site poypi a mit en service un nouveau lecteur html5 son flash , je croix que maintenent on n'a pas besoin de décrypté le gkplugin!

**Comment by arzaz** [comment]
Bonjour mino60,

Bien vu, depuis hier aucun lien sur Poypi.

**Comment by arzaz** [comment]
Du nouveau concernant Poypi?

Merci

**Comment by poto25** [comment]
Merci pour c'est infos vivement que sa marche

**Comment by TmpName** [comment]
Mise a jour pour poypi et le host google.

**Comment by poto25** [comment]
Personne peut nous mettre zopap.com aussi sur vstream car on peut voir les jaquettes par 50 merci d'avance

**Comment by arzaz** [comment]
Le problème a le host Googlevideo a resurgi, tous les fichiers sont introuvables?

**Comment by TmpName** [comment]
Corrigé sur beta, un probleme de regex.
