### ISSUE TITLE
papystreaming maintenent sur enigma2

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#167]
Bonjour 

Le team vu+ (allemand) a mit une nouvelle source français dans leurs plugin ( MEDIAPORTAL)
cette source c'est papystreaming.com/fr j'ai remarqué qu'il ya multi-hosters (yujitube).
voila leurs code qui marche trés bien sur enigma2

http://pastebin.com/1hWLxS2m

**Comment by TmpName** [comment]
Si je dit pas de connerie c'est des lien cacaoweb, donc limité dans le temps, et ca coupe regulierement en plein millieu du film.
