### ISSUE TITLE
archive.org et upstream.com

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#168]
Bonjour...

sur la section films cinema certain video de plus de 6 Go me demande des jours pour les uploader sur googlevideo ou picasaweb, alors j'ai chercher une autre solution pour avoire des films Blu Ray son passé par google et j'ai trouver la nouvelle plateforme uptostream.com maintenant beaucoup de liens sur la section films cinema son uptostream.com ce dernier ai limité de temp , pour bien profité il faux s'inscrire sur dpstream gratuitement et bénéficier de 50 Go de streaming au lieux de 1 Go.

**Comment by mino60** [comment]
est ce que on peut créer un script ou on remplace l'adresse de la video par le lien de la video
par exemple le film Saw 7 j'ai trouvé son adresse uptostrem.com (http://www52.uptobox.com/stream/8b4zdn83ae/720/0) apré 48 heurs l'adresse n'est plus disponible just un message sur firefox
500-service inavialable ,service temporairment indisponible et ce que on peux mettre une play lists
avec des liens uptostrem (http://uptostream.com/7nc7n9h7wvfr ) et crér un host uptostream on peut choisire la qualité de la video 720p et 1080p.
il ya un plugin e2 qui peut faire ça mais la list et sur le local dans le plugin lui mème

http://pastebin.com/zbfWKYsN

**Comment by LordVenom** [comment]
Bonjour,  si tu a trouver un resolver en python y a pas de raison que ça fonctionne pas sous vstream.Par contre attention au limitation et inscription c'est deux mot que j'aime pas.
