### ISSUE TITLE
Frenchstream.org

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#169]
Y a t-il un problème avec frenchstream?
Impossible d'accéder a ce site.

**Comment by TmpName** [comment]
Testé il y a 30s, fonctionne pr moi.

**Comment by mino60** [comment]
essyé celui de la beta

http://pastebin.com/kuVavYAQ

**Comment by TmpName** [comment]
Ha oui j'ai testé la derniere version par contre, dsl.

**Comment by arzaz** [comment]
Que se passe t-il avec le host videoraj sur Frenchstream? j'ai a chaque fois erreur connexion impossible

**Comment by TmpName** [comment]
Bon ben, la je peux pas dire, pr moi le site est totallement out.
A suivre ^^.
