### ISSUE TITLE
Vstream : Erreur connection

### ISSUE THREAD

**Issue by SuN969** [LordVenom/venom-xbmc-addons#172]
Bonsoir, je ne sais absolument pas pourquoi, mais depuis deux jours c'est devenu un enfer d'utilisé cette application, il marque sans arrêts "Vstream : connection impossible" et suite à ça il se bloque... 

Que dois-je faire pour corriger cela? 

J'ai la dernière version mise à jour de vstream et de openelec sur RaspBerry PI 2

**Comment by mino60** [comment]
Bonsoir ....le problème c'est votre connection internete qui n'est pas stable (verifier le cable de votre connection internet) , j'avais un probleme de connexion et c'était mon amplificateur wifi qui avais un problème d'alimentation et finalement  je l'ai préparé et le message est partie !..

**Comment by SuN969** [comment]
Bonjour, alors j'ai testé le câble, j'ai testé la connexion, tout est bon... 

J'ai changé de RaspBerry, rien n'y fait... 

J'ai donc décidé d'aller fouiller en brutale via WINSCP, et là, surprise ou pas me direz-vous, j'ai trouvé un total de 6 fichiers "vStream.db", c'est pas normal non? Du coup j'ai testé de le désinstaller complétement et du coup il restait 5 fichiers "vStream.db"... Il doit donc s'agir de doublons vu que je peux pas les supprimer en désinstallant l'add-on... 

J'ai tout supprimé brutalement via WINSCP et je l'ai réinstallé, ça semble avoir corrigé les problèmes... 

Mais il serait intéressant de savoir comment cela c'est produit... 

Cordialement
