### ISSUE TITLE
Ajout nouvelle Source

### ISSUE THREAD

**Issue by djendy** [LordVenom/venom-xbmc-addons#173]
Bonjour,

Serait-il possible d'ajouter la source suivante pour que ma femme puisse regarder les épisodes de plus belle la vie s'il vous plaît:

http://www.mamcin.com/non-classe/plus-belle-la-vie-episode-2784/

Merci d'avance,

Andy

**Comment by TmpName** [comment]
Zombi est en train de developper une source pour un autre site mais ou j'ai pu voir certains de episode de cette serie. 
cf https://github.com/LordVenom/venom-xbmc-addons/issues/170
