### ISSUE TITLE
fonction search vkstreamingfilm.biz

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#174]
Bonjour  j'ai ajouté cette source "vkstreamingfilm.biz" sur vstream beta mait j'ai pas trouvé une solution pour la recherche j'ai toujour la premiere page du site au lieu du titre que je veux trouver !.

http://pastebin.com/h5EeYZT7

**Comment by TmpName** [comment]
Une version qui marche, mais les regex en cas de recherche sont a refaire, c'est le premier de la fonction showmovies.

http://pastebin.com/66eevXZL

**Comment by mino60** [comment]
il fonctione ton code mais un text html a coté tu titre!

![sans titre](https://cloud.githubusercontent.com/assets/11494048/8291583/c1ba5cc0-192a-11e5-8032-d1e08e0a88a5.png)

**Comment by mino60** [comment]
c'est bon j'ai corrigé la pattern il reste juste le résumé du film il le script sera totalement fini

http://pastebin.com/vYQ93BMa
