### ISSUE TITLE
bug source full stream serie 

### ISSUE THREAD

**Issue by medzo1602** [LordVenom/venom-xbmc-addons#175]
bonjours je félicite le beau travaille fait mes j'ai un petit soucie quand je rentre dans vstream  serie  full stream  je prend une serie et c'est vide je comprend pas ? ça le fait que pour les serie

**Comment by LordVenom** [comment]
Bonjour,

Si tu parle de full-stream.me pas de soucis pour moi surement corriger dans la bêta et donc bientot dans la mise a jour.

**Comment by medzo1602** [comment]
oui je parle de ça. je me retrouve avec toute les serie video aucun lien video

**Comment by LordVenom** [comment]
Merci pour le rapport ça seras corriger dans la prochaine mise a jour.
