### ISSUE TITLE
Poypi avec un nouveau host 

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#176]
j'ai remarqué c'est dernier jours le site poypi utilise un nouveau hebergeur que je ne connais pas

une addresse du film 2 gung et comme ça : 
https://pdlvimeocdn-a.akamaihd.net/33937/529/384457865.mp4?token2=1435259636_585bd2720e1ab79dcc704da2a26a6580&aksessionid=da518f6cd7525faf&aktimeoffset=0

**Comment by mino60** [comment]
je crois que c'est un lien vimeo sur urlresolver 

vimeo.py : 

http://pastebin.com/estgcCYg

**Comment by TmpName** [comment]
C'est bon Vimeo rajouté sur beta, ne pas oublier de corriger hoster.py

Bon par contre je ne garanti pas que ca va fonctionner dans tout les cas, hoster en rodage.

**Comment by arzaz** [comment]
Avec vimeo, la connexion est plus fluide.
Je ne comprends pas pourquoi avec googlevideo la connexion ces derniers temps est devenue trop lente?

**Comment by TmpName** [comment]
La demande peut etre, un flux HD gratuit est pour moi un grand luxe, vu le prix d'un serveur pr diffuser de la sd pour 50 personnes j'image meme pas a imaginer pour de la HD.

Apres je peux pas te dire me sert jamais de poypi.

**Comment by arzaz** [comment]
Je viens de remarqué un problème de host avec Poypi, tous les fichiers sont introuvables?

**Comment by TmpName** [comment]
Tu as testé avec quel films ?
Tu as bien eu la mise a jour recement ?

Moi ca fonctionne avec googlevideo et vimeo.

**Comment by poto25** [comment]
C'est vrai certains fichier sont introuvable c'est bizarre

**Comment by TmpName** [comment]
Tu peux me donner un exemple stp ? (un titre ?)
