### ISSUE TITLE
Nouvelle source Full-streamingvk.com...

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#177]
Bonsoir une nouvelle source full-streamingvk.com , mais j'ai un probléme dans les entrées

http://pastebin.com/weTtEL9P

**Comment by TmpName** [comment]
J'ai pas trop compris ou est ton probleme mais y a plein de probleme de lien, un coup tu met full-streamvk.com un coup Full-streamingvk.com.

Pour le moment le site est HS, mais je viens de voir que vkstreamingfilm.biz est le meme site que full-streamvk.com/ mais il il n'y a pas les meme films.

**Comment by mino60** [comment]
j'ai deux tâches a résoudre maintenent 

1- les posters ne s'affiche pas sur la deusième page

2- la séction showhosters

http://pastebin.com/Dq4ATv3G

**Comment by TmpName** [comment]
Il y a toujours le probleme
>> URL_MAIN = 'http://full-streamingvk.com'
>> MOVIE_NEWS = ('http://full-streamvk.com/films-streamingvk-vf/', 'showMovies')

Tu vois rien de bizarre ? Tu devrais partir d'une base vierge au lieu de repartir d'une source deja complete,

**Comment by mino60** [comment]
merci pour la remarque j'ai corigé l'url main mais je n'arrive pas à accéder à la page hosters la pattern et juste peut-être un problème d'entré

http://pastebin.com/Q79pqx4t

**Comment by mino60** [comment]
je peu voir les films sur ce site mais avec le plugin nstream seulement avec vidto

je ne comprend pas pourquoi les posters ne s'affiche pas juste un qui commence avec /upload/xxx.jpg

le plugin
http://www.mediafire.com/download/zf76z6gzlgjzegj/plugin.video.nstream(2).zip

![sans titre](https://cloud.githubusercontent.com/assets/11494048/8393800/1b5d6882-1d20-11e5-9bc9-5acb85d5c6fa.png)
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/8393812/989e5518-1d20-11e5-9530-0b3ad4c79a9b.png)

**Comment by TmpName** [comment]
On a pas deja corrigé ces 2 problemes ici ?
https://github.com/LordVenom/venom-xbmc-addons/issues/159

**Comment by mino60** [comment]
j'ai mit full_streamvk_com sur beta mait les hosters la partie showHosters ne fonctionne pas

http://pastebin.com/Q79pqx4t

**Comment by TmpName** [comment]
Je le vois pas sur la beta ?

**Comment by mino60** [comment]
le log xbmc  m'indique rien sauf un problème showHosters!

20:43:39 T:5392  NOTICE: 	[PLUGIN] Vstream: load site full_streamvk_com and call function showHosters
20:43:40 T:5392  NOTICE: Jack Reacher
20:43:40 T:5392  NOTICE: 	[PLUGIN] Vstream Erreur: Connection Impossible,Jack+Reacher
20:43:40 T:5392  NOTICE: (False, [])
20:43:40 T:5392  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:43:40 T:6672  NOTICE: Thread BackgroundLoader start, auto delete: false
20:43:45 T:5312  NOTICE: Previous line repeats 1 times.
20:43:45 T:5312  NOTICE: Thread LanguageInvoker start, auto delete: false
20:43:45 T:5312  NOTICE: -->Python Interpreter Initialized<--
20:43:45 T:5312  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:43:46 T:5312  NOTICE: 	[PLUGIN] Vstream: load site full_streamvk_com and call function showHosters
20:43:46 T:5312  NOTICE: Un voisin trop parfait
20:43:46 T:5312  NOTICE: 	[PLUGIN] Vstream Erreur: Connection Impossible,Un+voisin+trop+parfait
20:43:46 T:5312  NOTICE: (False, [])
20:43:46 T:5312  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:43:46 T:4644  NOTICE: Thread BackgroundLoader start, auto delete: false
20:43:48 T:8128  NOTICE: Previous line repeats 1 times.
20:43:48 T:8128  NOTICE: Thread LanguageInvoker start, auto delete: false
20:43:48 T:8128  NOTICE: -->Python Interpreter Initialized<--
20:43:48 T:8128  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
20:43:49 T:8128  NOTICE: 	[PLUGIN] Vstream: load site full_streamvk_com and call function showHosters
20:43:49 T:8128  NOTICE: Jurassic World
20:43:49 T:8128  NOTICE: 	[PLUGIN] Vstream Erreur: Connection Impossible,Jurassic+World
20:43:49 T:8128  NOTICE: (False, [])
20:43:49 T:8128  NOTICE: 	[PLUGIN] Vstream: Table initialized
20:43:49 T:416  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by mino60** [comment]
Il ne manque pas par hasard une autre pattern pour les hosters ?

http://pastebin.com/1Ar5SiKX

**Comment by TmpName** [comment]
Le probleme ne vient pas de ShosHosters mais de showMovies.
En fait tu essayes de te connecter au  nom du jeu au lieu de l'url. Verifis au niveau du 
>> oOutputParameterHandler.addParameter('siteUrl', str(aEntry[1]))

**Comment by mino60** [comment]
je sais que c'est un problème showMovies et problème d'entrées on particulier comme j'ai dit en sur le premier post j'ai changé les entrées aEntry[1] aEntry[0] aEntry[2] mais toujour connection impossible?!!!...

**Comment by TmpName** [comment]
>> sPattern = '<div class="img-block border-2">.*?<img src="(.*?)" alt="(.*?)".*?<a href="(.*?)" title'
1 entry = image
2 entry = titre
3 entry = url
>>> oOutputParameterHandler.addParameter('siteUrl', str(aEntry[2]))

**Comment by mino60** [comment]
j'ai essyé str(aEntry[2]) et tout les entrées mais ça ne veut pas marcher 
tu peu jetté un coup d'oeil sur le post REGEX film-streaming.ws

**Comment by TmpName** [comment]
Kodi essaye de se connecter sur quoi ? tu as quoi qui s'affiche dans le message d'erreur ?

**Comment by mino60** [comment]
voila le log xbmc

18:07:34 T:7116  NOTICE: 	[PLUGIN] Vstream: load site full_streamvk_com and call function showHosters
18:07:34 T:7116  NOTICE: 	[PLUGIN] Vstream Erreur: Connection Impossible,#
18:07:34 T:7116  NOTICE: 	[PLUGIN] Vstream: Table initialized
18:07:34 T:2648   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showHosters&sCat=1&sFav=showHosters&sId=full_streamvk_com&sMovieTitle=Au%20bout%20de%20la%20nuit&sThumbnail=http%3a%2f%2fwww.full-streamvk.com%2fuploads%2fposts%2f2015-06%2f1435380720_18928230.jpg&site=full_streamvk_com&siteUrl=%23&title=Au%20bout%20de%20la%20nuit
18:07:34 T:2648   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showHosters&sCat=1&sFav=showHosters&sId=full_streamvk_com&sMovieTitle=Au%20bout%20de%20la%20nuit&sThumbnail=http%3a%2f%2fwww.full-streamvk.com%2fuploads%2fposts%2f2015-06%2f1435380720_18928230.jpg&site=full_streamvk_com&siteUrl=%23&title=Au%20bout%20de%20la%20nuit) failed
18:07:34 T:8036  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by TmpName** [comment]
18:07:34 T:7116 NOTICE: [PLUGIN] Vstream Erreur: Connection Impossible,#

Le regex deconne tu as un # a la place du lien web, si tu as bien str(aEntry[2]) a moment des tests, pour ten assurer fais juste un 
>> print aResult
apres le parsing

**Comment by mino60** [comment]
source terminé!.
