### ISSUE TITLE
Rebelotte - Deux Vstream sur Openelec suite à la mise à jour

### ISSUE THREAD

**Issue by SuN969** [LordVenom/venom-xbmc-addons#179]
Bonsoir, 

J'étais déjà venu parler d'un soucis qui survenait lors de la mise à jour automatique de Vstream, lors du passage vers la version précédente, je m'étais retrouvé avec deux vstream installé sur mon HTPC et cela créait de gros bugs rendant l'application extrêmement instable... 

Et aujourd'hui arrivé de la nouvelle version sur ma machine, je me retrouve une nouvelle fois avec deux installation de Vstream... 

Je commence à devenir rôder et je sais exactement où aller pour supprimer chacun des fichiers manuellement, mais je dois à chaque fois recommencer une installation manuelle depuis zéro ce qui est quand même vite handicapant! 

Cordialement

**Comment by LordVenom** [comment]
Bonjour. Merci pour le rapport je vais regarder ça.

**Comment by TmpName** [comment]
Tu utilises quel repository ?

**Comment by SuN969** [comment]
A l'origine celui-ci: 
https://github.com/LordVenom/venom-xbmc-addons/tree/master/repo
Mais maintenant j'installe manuellement l'application et je mettrai à jour manuellement! :P

Date: Mon, 29 Jun 2015 07:56:35 -0700

**Comment by LordVenom** [comment]
Bonjour, tu parle bien de vStream.db et pas de l'addon entier ?

**Comment by TmpName** [comment]
Mais y a un truc que je ne comprend pas, c'est quoi la difference entre les 2 install ?
Le nom du repertoire change ?
Le nom du fichier vStream.db a une difference ?
Sa position dans ton systeme de fichier ?

**Comment by SuN969** [comment]
Oui, c'est celui-là même qui se duplique un nombre incalculable de fois à chaque mise à jour automatique! 😉

En tout cas un grand merci pour ton travail! Ton application est vraiment géniale! Et super pour l'ajout des chaines TV!

Ça m'a vraiment sauvé la mise parce que mon fournisseur téléréseau est tellement nul à chier que dans mon bouquet j'ai que 5 chaines de TV en français!

Cordialement,
Caryl T.
________________________________
De : Lord Venom<mailto:notifications@github.com>
Envoyé : ‎30.‎06.‎2015 13:58
À : LordVenom/venom-xbmc-addons<mailto:venom-xbmc-addons@noreply.github.com>
Cc : SuN969<mailto:caryl.treuthardt@hotmail.fr>
Objet : Re: [venom-xbmc-addons] Rebelotte - Deux Vstream sur Openelec suite à la mise à jour (#179)

Bonjour, tu parle bien de vStream.db et pas de l'addon entier ?

---

**Comment by SuN969** [comment]
Ils se mettent à la même position mais il se duplique et du coup l'application devient totalement instable et ne cesse de planter...
________________________________
De : TmpName<mailto:notifications@github.com>
Envoyé : ‎30.‎06.‎2015 14:05
À : LordVenom/venom-xbmc-addons<mailto:venom-xbmc-addons@noreply.github.com>
Cc : SuN969<mailto:caryl.treuthardt@hotmail.fr>
Objet : Re: [venom-xbmc-addons] Rebelotte - Deux Vstream sur Openelec suite à la mise à jour (#179)

Mais y a un truc que je ne comprend pas, c'est quoi la difference entre les 2 install ?
Le nom du repertoire change ?
Le nom du fichier vStream.db a une difference ?
Sa position dans ton systeme de fichier ?

---

**Comment by LordVenom** [comment]
Je vais cherche mais je te promet rien ça me parle pas du tout dsl

**Comment by SuN969** [comment]
Merci beaucoup, je vais aussi essayer de voir de mon côté et si je trouve quelque chose, je te transmettrai ce que je trouve! ;)

**Comment by TmpName** [comment]
Il se duplique ?
Il y a forcement une difference dans le nom ?

**Comment by SuN969** [comment]
C'est la que je comprends plus à quoi c'est dû... Ils ont exactement le même nom dans le même dossier... Du coup ça plante complétement...

**Comment by SuN969** [comment]
Vu que ça semble se produire à chaque mise à jour automatique, je ferai des captures d'écran sur WinSCP la prochaine fois!

**Comment by LordVenom** [comment]
Tu est sure de pas avoir un problème de droit bizarre.Que le fichier s’écrase oui mais qu'il ce duplique.

**Comment by SuN969** [comment]
J'ai bien pensé qu'il s'agissait de droit manquant à l'application pour supprimer l'ancienne version! 

Openelec supporte la commande "sudo chmod XXX PATH-TO-FILE" en SSH?

**Comment by TmpName** [comment]
Parce la, c'est magique, j'avous avoir vu de tout sous linux (merci windows) mais la ? Qu'il soit possible d'avoir plusieurs fois le meme fichier au meme endroit .....
