### ISSUE TITLE
Bon site pour le streaming HD tvstream.pw

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#180]
Bonsoir  ..

j'ai surfé sur le web et par hazard je suis tombé sur ce site http://tvstream.pw ou j'ai pu voir quelque films qualité HD Blu Ray ça serait cool de l'ajouter sur vstream non?.
exp: http://www.purevid.com/v/341uxpormhkuwrvqs9263/
http://www.turbodebrideur.com/?ref=sghd

http://www.meilleur-debrideur.com/

**Comment by TmpName** [comment]
Ils passent par purevid, donc payant.
Il y a moyen d'utiliser des debrideurs, mais ca deconne tout les 10 jours, donc vraiment pas stable.

**Comment by streamdev** [comment]
@TmpName Je suis admin de turbodebrideur et modo de skiplimite, j'espère bien que t'as vu frameturbo.php dans l'url de l'iframe lol :) c'est pas un vol, le débrideur est sur les serveurs de skiplimite et je gère ça avec mon pote emulee1 :P

**Comment by TmpName** [comment]
Ok, autant pr moi, desolé alors, mais suis pas allé voir si vous etiez partenaire  ou pote, j'ai juste vu l'url comme tu l'as dit.
