### ISSUE TITLE
Site de Replay

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#181]
Bon ben je crois que Venom est bon pour faire une rubrique Replay.

Je viens de completer la source de  FreeFighter77 Replay.py
J'ai chnagé le nom pour mettre le nom du site, c'est pour ca qu'elle ne se voit plus

En attendant celle de ZombiB https://github.com/LordVenom/venom-xbmc-addons/issues/170

tntv_rattrapage.py sur Beta, pas mal de bric a brac dessus.

**Comment by LordVenom** [comment]
C'est noter :)

**Comment by LordVenom** [comment]
Je les mis en home direct comme ça quand ont auras d'autre source ça seras pas trop le bordel.en tout cas bon taff superbe source.

**Comment by TmpName** [comment]
Ben c'est FreeFighter77 qui l'avait commencé https://github.com/LordVenom/venom-xbmc-addons/issues/121
Et j'en ai eu besoin pour une emmission a la con, du coup je l'ai continué.

Je n'ai pas touché a celle de ZombiB car plus recente, j'attend de ses nouvelles ^^.

A propos du "home" je suis le seul  a avoir un regroupement pour les films et les series ? J'ai du recuperer ,le fichier de la beta apres la mise a jour. Tu ne l'as pas validé pour la version officielle ?

**Comment by LordVenom** [comment]
Hum ? tous le monde a un regroupement des films et des series enfin ceux qui ont la derniere version.

**Comment by TmpName** [comment]
Bon ben je comprend rien, en fait durant la mise a jour (qui a eu lieu au meme moment ou je modifiais des fichiers) y a eu un croisement, me suis retrouvé avec de vieux fichiers melangés avec des neufs, Me suis retrouve avec une version a la con que j'ai du mettre a jour par la beta car la version officielle n'avait pas les bon fichiers, et la je compare y a plus de problemes entre les deux versions.

Un mauvais alignement des planetes a du me faire DL des fichiers d'un espace temps parrallele, oublis ce que j'ai dis, je vois plus de soucis.

**Comment by LordVenom** [comment]
Bienvenue dans la 4eme dimension :)

**Comment by zombiB** [comment]
salut les amis , tres bon travail pour la section Replay , pour la source de #170 les hotes utilisés ne sont pas dipsonibles pour le moment comme openload.io  et   vid.me...etc
par contre j'ai commencé cette source http://enquetedereportages.com ici http://pastebin.com/zvNdJ7d7 par contre il manque quelques points : les thumbs ne s'affichent pas / l'hote flashx ne foncitonne pas ( il affiche toujours fichier introuvable ! )  et cette source  documentaires-streaming.com par ici http://pastebin.com/gnAC0fPd par contre j'arrive pas à afficher les videos (videomega.tv comme hote )
j'apprécie toujours votre aide et avis :)

**Comment by TmpName** [comment]
FlashX a eu une petite mise a jour il ya 2/3 jours.
Pour la source https://github.com/LordVenom/venom-xbmc-addons/issues/170 tu es sur de ton coup ?
Moi elle me plaisait pas mal, je viens de tester 2/3 videos dont une sur openload et elle marche (sur firefox).
Tu es sur qu'elle ne vaut plus rien ?

**Comment by zombiB** [comment]
Oui c'est une source interresente mais ce que je voulais dire que vstream
ne peut pas lire ces vidéos  il faut créer les hosters  pour openload etc

**Comment by TmpName** [comment]
Ok, ce soir je n'ai pas le trop le temps, mais demain je jette un oeuil pour openload et flash pour ta seconde source.

**Comment by zombiB** [comment]
Merci bien

**Comment by TmpName** [comment]
Bon j'ai modifie FlashX pour qu'il marche sur ce site, mais j'ai du modifier quelque chose qui je l'espere ne va pas le rendre inoperant sur d'autre site.

Rajout de 2 host opentruc et vid.me

**Comment by zombiB** [comment]
merci @TmpName flashx fonctionne bien mnt , openload aussi , j'ai rajouté les 2 sources à la version beta pour pouvoir les tester
