### ISSUE TITLE
failed to find video url

### ISSUE THREAD

**Issue by lobofi** [LordVenom/venom-xbmc-addons#184]
bonjour
quand je lance vstream je n'ai aucun probleme pour regarder des films ou des series mais lorsque je veux regarder un documentaire j'ai resolve youtube puis un message d'erreur failed to find video url pourtant le addon youtube est installé , je comprends pas pouvez vous m'aider svp
merci d'avance

**Comment by TmpName** [comment]
Je dis peut etre une connerie vu que je n'ai jamais été voir de ce cote la, mais l'addon youtube marche tout seul egalement.
Tu arrives a voir les video en passant par lui directement ?

Ca nous aiderais si tu pouvais nous faire passer une partie des logs au moment de l'erreur par pastebin par exemple.

**Comment by lobofi** [comment]
ça le fait uniquement pour les docs et seulement les docs vraiment bizarre

**Comment by LordVenom** [comment]
Bonjour, Merci de préciser quel source vous pose problème docspot, notreecole etc.. 
et comme le dit @TmpName de nous fournir la partis du log qui contient l'erreur.

**Comment by lobofi** [comment]
toutes les sources sont cochées donc je ne sais pas

**Comment by lobofi** [comment]
en fait je vais dans recherche je tape un theme par exemple foot là j'ai tous les docs sur le foot et quand j'essaie d'en ouvrir un que j'ai un message d'erreur

**Comment by TmpName** [comment]
Je viens de tester sur "docspot" avec la recherche "foot"
"les 20 plus grandes ....."
"Interieur sport...."
Et je n'ai pas eu de problemes.
L'addon youtube fonctionne quand tu te sert de lui directement sans passer par Vstream ?

**Comment by lobofi** [comment]
j'ai testé les sources ceux qui marchent pas c'est docspot et notreécole les 2 premiers en fait

**Comment by lobofi** [comment]
quand je passe par youtube j'ai no results je crois que le probleme c'est youtube

**Comment by lobofi** [comment]
mais quand je vais sur le site de youtube je peux visionner des videos le probleme c'est youtube dans xbmc ou plus exactement l'addon youtube

**Comment by mino60** [comment]
effectivement le probléme c'est votre xbmc sur kodi les dicumentaires marche nickel sur YouTube
je vien de testé docpost.fr le documentaire L'Egipte des pharaons.

**Comment by TmpName** [comment]
Essaye en reinitialisant le pluggin de youtube  sans le reinstaller.

**Comment by mino60** [comment]
alor pour résoudre le problème telecharcher cette outie qui vous permettra édité supprimer colie copie les fichiers sur c : users/xxx/AppData/Roaming/XBMC/addons/

http://www.mediafire.com/download/vluxfr39p8ju3ya/dcc296.rar

dcc2.66 aller sur FTP les dossiers sur la droite c'est tout les dossiers PC

aller sur :  c : users/xxx/AppData/Roaming/XBMC/addons/plugin.video.youtube (clic droit supprimer)

remplaçer le par celui la : 
http://www.mediafire.com/download/xt520wp9ws9xb11/plugin.video.youtube.rar

après extraction de fichier .rar utilisé l'outie dcc2.66 copier coller le fichier youtube dans : 
 c : users/xxx/AppData/Roaming/XBMC/addons/....

lorsque vous voulez voire une video youtube sur docpost.fr documentaires L'Egypte des pharaons suivi l'assitant d'instalation ( list , media info langue "fançais" region france...)
et la video ce lance son problème.

**Comment by LordVenom** [comment]
Vous pouvez faire un retour svp, sujet résolut ou pas ?
