### ISSUE TITLE
Dpstreaming & Frenchstream

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#187]
Impossible de se connecter aux sites Dpstreaming.org et Frenchstream.org?

**Comment by mino60** [comment]
Sur le navigateur firefox
This page ( http://dpstreaming.org/ ) est actuellement déconnecté . Toutefois, puisque le site utilise la technologie de  CloudFlare Toujours Online ™ vous pouvez continuer à surfer sur un instantané du site . Nous allons garder le contrôle dans le fond et , dès que le site revient , vous serez automatiquement servi la version live . Toujours Online ™ est alimenté par CloudFlare | masquer cette alerte

pour frenchstream momentanément indisponible pour le devlopement je crois.

**Comment by LordVenom** [comment]
Pour moi les 2 fonctionnes.
