### ISSUE TITLE
streamingmy.com nouvelle source

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#188]
Bonjour 

une nouvelle source StreamingMy.com films series j'ai un seul problème showHosters connection impossible la recherche pour les series.

http://pastebin.com/mU6ehvkz

log: 
http://pastebin.com/hxH82F3X

**Comment by LordVenom** [comment]
Mino ta participation et impressionnante merci.Pourrais tu stp te concentrer sur ce que manque a l'addon.du sport, des video du net des doccumentaires.

**Comment by mino60** [comment]
il ya une protection sur le site qui change la page , commment résoudre ce problème car les hosts ne s'affiche pas?


http://pastebin.com/QjqtHr1y
