### ISSUE TITLE
New script hd-stream.co 

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#189]
LordVenom/venom-xbmc-addons-beta#59

Suis desolé, mais c'est peut etre ta version de kodi qui n'est plus a jour (vielle version de urlib2).

Franchement tu peux te connecter sur le site via firefox mais tu as une erreur 404 avec vstream, je vois pas le probleme.

j'ai essyé avec kodi 14.2 toujour rien!!!

http://pastebin.com/6PmS3xNS

 pk : j'ai due fermé l'encien topic son faire attention !

**Comment by mino60** [comment]
j'ai désinstaller tout puis j'ai installer kodi 14.2 Helix vertion final j'ai mit à jour kodi apré j'ai installer p.v.vstream.beta cool!!!... c'est le mème problème?.


http://pastebin.com/NSD4Mtd4

**Comment by LordVenom** [comment]
Elle en et ou cette source, j'aime les lien direct :)

**Comment by mino60** [comment]
voila hd-stream.co : http://pastebin.com/UZ6XVcKs

j'ai besoin de testé la section genre si ça marche pas la source film-streaming.co c'est mieux
mais il y'a un problème pour page suivante

http://pastebin.com/MJ3EvJG7

**Comment by LordVenom** [comment]
http://pastebin.com/KrASkE7i

La fonction genre ne fonctionne pas il retourne pas le code html attendu bizard.

**Comment by mino60** [comment]
c'est pas bizard le lien par exemple pour la section Action c'est un lien film-streaming.co les deux sites lier c'est pour ça qu'il faut opté pour le deuxième site c'est à dire film-streaming.co ou son hebergé les video 

j'ai Edité showHosters mais il ya une erreur
oPlayer = cPlayer()
NameError: global name 'cPlayer' is not defined

film-streaing.co : http://pastebin.com/n3uVDLS1

les films genre fonctionne bien just un problème pour next page !.

**Comment by LordVenom** [comment]
Tu tenter d'utiliser une fonction sans appeler la librairie.

from resources.lib.player import cPlayer

**Comment by TmpName** [comment]
Pour info, tu as encore fait une regression, le dernier pastebin est plus vieux que le precedent.

**Comment by LordVenom** [comment]
Voila

Effectivement y a un mélange de tous.Prend ton temp pour faire une source.

http://pastebin.com/he7PA9Lw

**Comment by LordVenom** [comment]
Ajouter a la bêta.
