### ISSUE TITLE
Ajouter source(s)

### ISSUE THREAD

**Issue by Datawolftv** [LordVenom/venom-xbmc-addons#19]
Bonsoir,
Je viens de découvrir vstream, bravo !
J'aimerais (déjà ?) ajouter des sites (comme cinesoir.net)
L'installation du zip ayant échoué (structure incorrecte) j'ai dézippé le repository dans le répertoire addons de xbmc, et j'ai pu télécharger vstream depuis l'interface de xbmc.
Tout ça pour dire que je préférerais que vous me répondiez qu'on peut ajouter des chaines sans refaire le zip ;-)
Merci d'avance.
Laurent

**Comment by stormz85** [comment]
Hello LordVenom ! 
Je viens ici pour la même question, j'ai 2 Source que je voudrais ajouter sur VStream
j'ai vu que Poypi à été renommé et Bovup egalement :) mais je sais pas comment faire car je suis pas codeur, ya un tuto quel que chose ? de pas trop compliquer

Merci d'avance !

**Comment by TmpName** [comment]
Poypi est devenu kepliz et est deja en place, bovup est la meme source.

Pour creer une nouvelle source, il y a un fichier "squelette" ici >> https://github.com/LordVenom/venom-xbmc-addons/blob/master/ajouter_une_source.py

Pour les tutos, il faut fouiller les issues, tu n'es pas le premier, et il y a de forte chance qu'en cas de probleme, la solution ait deja ete donnée, apres tu peux demander de l'aide au meme endoit..
