### ISSUE TITLE
Voirfilms.org

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#192]
Auncun host ne s'affiche pour le site voirfilms.org

**Comment by TmpName** [comment]
J'ai fais une correction mais je n'ai pas pu tester, dsl, donc ca marche chez moi mais j'ai pas tout testé, a surveiller avant de publier.

**Comment by LordVenom** [comment]
lol tu peux l'upload sur la bêta plutôt, je réserve le github de base uniquement au mise a jour public.

**Comment by TmpName** [comment]
Mince, dsl, suis vraiment pas reveillé ce matin.
Annule tout je le met sur le beta.

**Comment by glden8** [comment]
www.vfcine.com
