### ISSUE TITLE
DPStreaming.fr

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#194]
Aucune information avec le site Dpstreaming.

**Comment by TmpName** [comment]
C'est le site qui ne marche plus pour le moment,
Quand un site ne marche pas, verifiez la version en ligne pour savoir d'ou vient le probleme.

**Comment by arzaz** [comment]
Quelle est la différence avec http://www.dpstreaming.eu/

**Comment by TmpName** [comment]
Bonne question, j'ai jeté un oeuil vite fait, il semblerait qie ce soit des sites completements differents, peut etre que l'un profite du nom de l'autre, apres c'est peut etre le meme webmaster ...

**Comment by arzaz** [comment]
Du nouveau concernant DPStreaming.org? error 522 a disparue.
Actuellement j'arrive a accéder au site, mais après 5 secondes voir ci-dessous:

Checking your browser before accessing dpstreaming.org.

This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…
DDoS protection by CloudFlare 
Ray ID: 20fbe9ec398f25d4

**Comment by TmpName** [comment]
Ca a l'air de remarcher ce soir.
Pour ton truc de 5 s, c'est une protection de cloudflare, une saleté que la personne doit desactiver elle meme dans sa configuration (le webmaster), enfin si elle le desire.

En fait elle apparait chez moi sur certains sites, comme mangacity, si tu te connectes trop souvent, elle se met en route, affiche une page web speciale qui demande d'avoir les cookies ET javascript d'activé, dans le cas contraire elle reboucle sur elle meme. Elle sert a a eviter les attaques DDOS, et en passant bloquer les bots scrapper.

Elle est bypassable, mais comme pour le moment je la croise rarement, et qu'il suffit de se connecter sur le site avec un navigateur standard pour la debloquer, j y fais pas trop attention.
