### ISSUE TITLE
Marque page n'affiche pas les items 

### ISSUE THREAD

**Issue by sp06** [LordVenom/venom-xbmc-addons#195]
Bonjour,

je viens de découvrir cet excellent plug-in :oD mais j'ai un petit problème (à priori je n'ai rien trouvé sur ce point sur le net) : lorsque j'utilise la fonction marque page pour mettre de coté un lien (recherche d'une série), j'ai bien le message comme quoi lc'ezt "enregistré avec succès" mais lorsque je vais dans la section "marques-pages", j'ai bien le message "Vous avez 1 marque page" mais rien dans le dossier "Séries" associé (rien non plus dans les autres dossiers au cas où).
J'ai désinstallé Vstream et purgé toute les données du plug-in sous userdata/addon_data puis ré-installé mais le résultat est le même.

J'ai peut-être raté qqch ??? :o(.

Et encore toutes mes félicitations pour ce plug-in.

**Comment by TmpName** [comment]
Ha ?
Ca c'est nouveau, avant de regarder en profondeur, si j'ai bien compris le fonctionnement :
Quand tu affiches le menu contextuel sur l'episode de la serie, cela va dans le repertoire "serie" mais si tu l'affiche sur la liste des saisons par exemple, il risque de partir en divers. Mais dans tout les cas il doit apparaitre quelque part.

Essaye sur une autre source, ou a un autre niveau dans la hierarchie (Nom/saisons/episode/lien), il se peut que ce soit la source qui soit bugguée et pas Vstream.

**Comment by LordVenom** [comment]
Bonjour, perso je recherche la serie flash et la met en marque page sans bug, il faudrait être plus preçis sur le bug quel serie , quel source un maximum d'info que l'on puisse recréer le bug, de plus ton log xbmc nous serais utile.

**Comment by sp06** [comment]
Salut à tous,
@TmpName : dans les marques-pages, ça me dit bien que j'ai <x> marques pages mais je ne les trouve nulle part. Ca me le fait qque soit le niveau de hiérarchie et la source. J'ai pas encore essayé au niveau Film ce soir, la famille regarde une série via vStream ;o)

@LordVenom : j'ai ciblé le la partie du log de 'l'insert et ensuite les erreurs (cf.ci-dessous). Pour info., Kodi 14.2 sur KODIBUNTU 14.04.2 et vStream - Version 0.3.3 - 31.07.2015

Dès que je peux, je fais le test sur les Films. Pas d'urgence non plus, je passe par l'historique des recherches pour garder ce que je veux.

# Ajout d'un marque-page
21:39:01 T:140148012418816  NOTICE: -->Python Interpreter Initialized<--
21:39:02 T:140148012418816  NOTICE:     [PLUGIN] Vstream: SQLITE 3 as DB engine
21:39:02 T:140148012418816  NOTICE:     [PLUGIN] Vstream: load site cFav and call function setFavorite
21:39:02 T:140148012418816  NOTICE:     [PLUGIN] Vstream: SQL INSERT favorite Successfully
21:39:02 T:140148012418816  NOTICE:     [PLUGIN] Vstream: Table initialized


# Tentative d'affichage des marque-pages.
21:39:46 T:140148901652224  NOTICE: -->Python Interpreter Initialized<--
21:39:46 T:140148901652224  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:39:47 T:140148901652224  NOTICE: 	[PLUGIN] Vstream: load site cFav and call function getFav
21:39:47 T:140148901652224  NOTICE: 	[PLUGIN] Vstream: Table initialized
21:39:47 T:140149934024640   ERROR: GetDirectory - Error getting plugin://plugin.video.vstream/?function=getFav&sCat=2&sFav=getFav&site=cFav&title=S%c3%a9ries
21:39:47 T:140149934024640   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=getFav&sCat=2&sFav=getFav&site=cFav&title=S%c3%a9ries) failed

**Comment by LordVenom** [comment]
Bonjour 
dsl réponse tardive, ton log ne m'apprend rien. A tu eu le temp de regarder pour les films il n'y a aucune autre erreur ? j'ai bien tester chez moi impossible de reproduire ce bug. Ne serais ce pas encore un mystère de linux.

**Comment by sp06** [comment]
Ca me fait la même chose pour les Films. Je vais voir ça en montant une plate-forme en parallèle pour voir si j'ai le même pb mais ça m'étonnerais vu que personne ne semble avoir eu ce pb et que tu ne le reproduis pas. Mystère de l'informatique :o)
Je ferme cet "issue".

Et merci à vous encore une fois

**Comment by sp06** [comment]
.
