### ISSUE TITLE
voir flms.org

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons#196]
Ce site est vraiment sympa,mais bcp de hoster h.s sur vstream, j ai essaye de regarder mais en vain ...
il y a netu qui ne fonctionne pas et 2 3 autres (plus les noms) ils sont bien valide via un navigateur ...

**Comment by TmpName** [comment]
Effectivement il y a un soucis dans les hosters.

Ok.ru, je crois que ce n'est plus possible pour certain format
openload corigé sur beta.
zstream/watching nouveau host je suis dessus.
Netu pareil c'est en cours.

**Comment by FreeFighter77** [comment]
beau boulot comme d ab Tmp ,tu fais un boulot immense, si je peux aider ou vous avancer faites moi signe, ce malgre le fait que je sois un peu restreint au niveau connaissance

**Comment by TmpName** [comment]
Creation du hoster Zstream sur beta.
(A suivre)

**Comment by FreeFighter77** [comment]
pour plus de lisibilité sur ce site je voulais rajouter la qualité et si vost ... J'ai fais cette pattern mais impossible de la faire fonctionner erreur de script : 
<div class="imagefilm">.+?<span class="affiche">.+?<span class="(.+?)"></span>.+?<img src="(.+?)".+?<a href="([^<>]+?)".+?titreunfilm" style="width:145px;"> *(.+?) *<\/div>.+?<span class="(.+?)"

**Comment by FreeFighter77** [comment]
Pour le site voirfilms.org j ai voulu rajouté la qualité du film ,ca fonctionne mais la fonction recherche est k.o, je ne vois pas d ou ca vient ... voici le fichier: 
http://pastebin.com/fxfNnFML

**Comment by TmpName** [comment]
J'ai corrigé le next page
Rajout du host Watching.

ok.ru, je pense qu'on va devoir l'oublier, il fragmente les fichiers et utilise un protocole a lui, affaire a suivre.
Netu est reparé mais ne fonctionne pas suite a une modif de la cle de decodage, la je ne suis pas seul sur le coup, soit j'attend que quelqu'un d'autre trouve la cle soit me faudra m y coller, mais lui est recuperable assez facilement.

Pour le coup de la recherche, c'est pour ca qu'il y a deux parties, il faut 2 regex differents car si tu fais une recherche la qualité n'apparait pas, et donc il faut un regex special.

**Comment by FreeFighter77** [comment]
J ai essaye avec ta pattern pour la recherche, mais ca ne marche pas non plus. Je pense faut il faut redefinir title picture ... car il n ont pas la meme postion que la patern avec la qualité.Mais vois pas comment m y prendre

**Comment by TmpName** [comment]
Ca va etre complique a cause des series, pas la peine de se prendre la tete, au pire tu l'affiches sur la seconde page.

**Comment by TmpName** [comment]
Bon netu reparé.
Pour ok.ru je sais pas, j'arrive a recuperer les liens, mais ils ne marchent que si je visualise d'abord le film sur navigateur.

**Comment by arzaz** [comment]
Tous les liens des films sont vides

**Comment by TmpName** [comment]
Nouveau post ouvert ici https://github.com/LordVenom/venom-xbmc-addons/issues/227
