### ISSUE TITLE
poypi.com fonctionne plus

### ISSUE THREAD

**Issue by poto25** [LordVenom/venom-xbmc-addons#197]
bonjour tout le monde voila depuis la mise j'ai erreur du script sur poypi aucun film fonctionne et meme les jaquette s'affiche pas corectement , merci de me répondre

**Comment by TmpName** [comment]
Mise a jour de poy pi sur beta.

**Comment by poto25** [comment]
Vous pouvez faire la mise a jour sur vstream car je regarde les film que sur poypi merci

**Comment by arzaz** [comment]
Merci TmpName pour la mise a jour.

Est-il possible de rajouter la qualité de la video "HD" devant les titres stp comme c'est fait par le passé avant cette mise a jour?

**Comment by arzaz** [comment]
Merci de rajouter svp la qualité de la vidéo "HD" devant les titres

**Comment by arzaz** [comment]
Merci de rajouter la qualité de video "HD" devant les titres stp.

**Comment by poto25** [comment]
vous pouvez faire la mise a jour de poypi sur stream sa fonctionne toujours pas merci d'avance pour votre taf

**Comment by LordVenom** [comment]
Dans la semaine si j'ai le temp et que la bêta reste stable.
