### ISSUE TITLE
Hoster youwatch

### ISSUE THREAD

**Issue by ttrd06** [LordVenom/venom-xbmc-addons#198]
bonjour à toute l'équipe,

tous les films avec youwatch ne fonctionnent plus depuis quelques jours ...
l'erreur est fichier introuvable, peut-être une mise à jour à faire sur le resolver ?

merci et bonne continuation sur ce super plugin !

**Comment by TmpName** [comment]
Effectivement.
J'ai commencé mais si quelqu'un sait comment importer la commande "eval" pour kodi ca m'interesse.

**Comment by LordVenom** [comment]
Dsl je comprend même pas la question eval fonctionne tous seul si je fait print eval("2 + 4") ça fonctionne.

**Comment by TmpName** [comment]
Autant pour moi, faute de frappe.
Mise a jour de youwatch sur beta (recup de urlresolver)

**Comment by ttrd06** [comment]
bonjour à tous,
TmpName: testé la béta mais ne fonctionne pas. Le même code de urlresolver date de 4 mois et ne fonctionne pas non plus sur d'autres addons.
ils ont aussi été informé du bug sur youwatch ...
si vous avez trouvé une solution autre que celle de urlresolver, will be cool ...
bon courage !

**Comment by LordVenom** [comment]
Pour moi ça fonctionne, par contre y avais une erreur sur dpstreaming.org corriger sur bêta.

**Comment by ttrd06** [comment]
bonjour à toute l'équipe,
désolé mais cela ne fonctionne pas:
-j'ai donc pris le code de youwatch beta et mis en remplacement sur le youwatch.py de l'addon (copier -coller)
-j'ai toujours le même soucis: fichier introuvable 
-j'ai testé sur plusieurs films et c'est pareil malheureusement alors que le fichier existe bien en réel: testé sur firefox, puis clique sur pub pour jouer le film
-comme dit précédemment, le nouveau code que vous avez mis correspond à celui de urlresolver qui ne fonctionne plus, ils ont été prévenus
-une autre solution doit être trouvée si vous pouvez bien sur

en tout cas merci encore pour ce merveilleux addons qui est de loin supérieur à ce que j'ai pu voir alors,
bonne continuation les gars !

**Comment by LordVenom** [comment]
J'ai encore tester pour moi dans films/ films nouveautés / frenchstream.org / dark place et host youwatch ça tourne.

Donc tu as du tomber sur un autre bug, sur quel source et quel film fait tu tes test ?

**Comment by ttrd06** [comment]
fait le même test que toi et cela fonctionne ... ?
par contre sur dpstreaming, nada ...
le re.compile au niveau du code à modifier ?

**Comment by ttrd06** [comment]
je viens de remplacer le code beta dpstream sur l'ancien chez moi et tout fonctionne !
désolé pour le dérangement... Bon WE à toute l'équipe !

**Comment by LordVenom** [comment]
Merci pour le rapport et bon Film.
