### ISSUE TITLE
official-film-illimité.fr

### ISSUE THREAD

**Issue by poto25** [LordVenom/venom-xbmc-addons#199]
Bonjour tout le monde je voudrait savoir si vous pouvez le mettre sur vstream .
C'est un site de streaming en HD et en français , c'est le même genre que poypi.

http://official-film-illimité.fr

merci d'avance

**Comment by LordVenom** [comment]
Pas mal oui, mais pourquoi ne pas tenter de la faire c'est une source simple en plus.

**Comment by poto25** [comment]
Salut lordVenom j'aimerais bien mais je c'est pas faire sa .

**Comment by ttrd06** [comment]
bonjour à toute l'équipe,

Le site est pas mal du tout mais pour le parser en python, urllib et urlib2 ne prennent pas les accents sur les noms de domaine.
Astuce: le site indiqué est en réalité http://xn--official-film-illimit-v5b.fr
donc il faudra "replacer" l'url par celle-ci dans le parsage films + séries, après ça fontionne ...

bonne soirée !

**Comment by poto25** [comment]
Salut ttrd06 , oui il est pas mal se serait bien si il serait sur vstream

**Comment by LordVenom** [comment]
Bonjour, je vais le faire.

**Comment by TmpName** [comment]
Par contre pour infos, pour ceux qui ne passe que par poypi ou autres sites HD "parce que sinon ca rend pas sur votre grande TV" vous pouvez repasser, la HD est un gag.
Peu d'hebergeurs, et tres peu de films.

**Comment by LordVenom** [comment]
Effectivement ça depend plus du host que du site internet. si vous ête sur pc quand vous regarder une video presser "O" pour avoir les info sur ça résolution.

**Comment by TmpName** [comment]
En fait j'ai verifié par curiosité, la resolution est bien du 1080p, (videomage converti les videos, tu lui envois du 320*240 il te donne du 1080p, mais tu as juste la resolution pas la qualité).
Mais quand tu regarde les autres donées, debits, ect ... c'est equivalent du mauvais 720p.

**Comment by soraya3** [comment]
Le nom de domaine a changé depuis http://official-film-illimite-hd.com/

**Comment by johngf** [comment]
@soraya3 possible mais pour l'instant il est vide l'autre est hs depuis 2 jours
