### ISSUE TITLE
tv-streaming.ch marche plus

### ISSUE THREAD

**Issue by ttrd06** [LordVenom/venom-xbmc-addons#201]
bonjour à tous !
le site tv-streaming.ch ne fonctionne plus dans l'addon, apparemment ils ont mis une protect cloudflare.
j'ai essayé de chercher comment bypasser cette protect mais sans succès.
une idéé peut-être ?
bonne soirée à l'équipe et bon courage pour ce pb !

**Comment by TmpName** [comment]
Merci pour l'info.
J'avais deja vu cette protection, en general elle disparait assez vite, car trop contraignante, mangacity l'a eu quelques mois.
Il existe meme des librairies deja toute faite pour le bypass et en python comme https://github.com/Anorov/cloudflare-scrape

Je pense que je vais en profiter pour demander a venom pour la mettre en definitif sur Vstream, au cas ou d'autres tordus veuillent s'en servir. (Probleme elle demande une extention python assez lourde pour le javascript)

Je peux rien garantir, mais ca devrait remarcher dans quelques jours, selon mon temps de dispo.

**Comment by ttrd06** [comment]
en effet, tout remarche depuis quelques heures ...! ils ne n'utilisent plus.
cependant, j'avais déjà vu cette librairie mais existe-t-elle sous kodi ?

**Comment by LordVenom** [comment]
@TmpName Je sais pas trop si tout les import de ce script fonctionneront sous kodi mais si tu l'ajoute dans /lib/ j'y toucherais pas :)

**Comment by TmpName** [comment]
Raté ^^.

En fait j'avais prevu une version light pr kodi, c'est la deuxieme fois que j'essaye de la faire, mais le site remarche en general assez vite, car trop contraignante pour le proprietaire du site, beaucoup de users n'ont pas forcement les cookies et le java activé. Je pense qu'elle doit aussi pouvoir s'activer toute seule en cas d'attaque sur le site en question.

Je garde sous le coude du coup, mais oui, si je dois m y remettre ce sera une librairie speciale dans "lib"

Pour en revenir a l'adapatation sous kodi, il faut voir si il y a moyen de se passer de la librairie gerant le javascript, juste en utilisant la commande "eval" de python pour calculer la reponse ,mais la protection changeant regulierement je n'ai jamais pu regarder en profondeur la faisabilité du smilblick.

Tu as une petite explication ici https://www.cryptobells.com/bypassing-cloudflares-layer-7-ddos-protection/

**Comment by spdro** [comment]
Website is working again, [tv streaming](http://tvstreaming.ch/). we change name domain from tv-straming.ch to **tvstreaming.ch**.

**Comment by TmpName** [comment]
Je peux me tromper mais j'ai l'impression qu'ils se sont fait reprendre l'url.
Ils ont chnage d'adresse en htt p://ww w.la-tele-du-web.tv
Et si j'essaye sur ton lien, il marche, mais il y aucun film/serie dessus, que des trucs recent, rien a voir avec l'ancien contenu.

**Comment by Fabiano-1** [comment]
Salut les gars

Je suis le fondateur de Tv-Streaming.ch
Le site me coûtait trop cher j en ai donc refait un autre  http://streaming-serie.co/
tres riches en contenu rare

j ai opter pour des pub version bannière pour ne pas importuner l utilisateur avec cette publicité invasive ce genre de site coûte assez chère et nous essayons de survivre avec la pub
le but c est avant tout le partage

Tv streaming ch est devenu http://streaming-serie.co/  depuis mars 2016
