### ISSUE TITLE
Tv Orange !?

### ISSUE THREAD

**Issue by kenwood76** [LordVenom/venom-xbmc-addons#202]
Bonjour,
j'utilise essentiellement le Plugin pour regarder la tv , via le lien Web tv.
j'aurais aimé récupérer le flux de ma Box Orange lié a mon abonnement,mais cela ne fonctionne pas.
J'ai bien la liste des chaines rapatriée depuis la Box , mais aucune d'entre elles se lancent  ;(
Pouvez m'aider ?

Merci

**Comment by LordVenom** [comment]
Bonjour, 

Je vais deviner que tu est sur pc et même que tu à Vlc test cette url avec rtp://@232.0.9.5:8200

**Comment by kenwood76** [comment]
ooops desole,

mon test a d'abord été fait sur Mac,Kodi 15.1 avec vlc oui , test KO
ensuite j'utilise Kodi et ton plugin essentiellement sur dongle Android
>Tronsmart, Kodi 14.0 , lecteur auto test KO

2015-08-20 14:03 GMT+02:00 Lord Venom <notifications@github.com>:

**Comment by kenwood76** [comment]
nada , avec ton lien ci dessus .
peut être je ne fais pas ce qu'il faut.
j'ai juste copier coller ton lien , je l'ai mis dans vlc , lecteur reseau,
mais rien ne s'affiche .

par avance merci a toi

**Comment by LordVenom** [comment]
Donc ça ne vient pas de vStream.A tu l'option tv chez orange ? faut que tu cherche pourquoi tu ne peux pas lire leur stream.

**Comment by kenwood76** [comment]
oui , bien sur j'ai la tv par adsl sur Orange.
en mettant d'autre lien .m3u que celui que tu m'as donné j'arrive sur vlc a
voir le flux tv, mais pour l’intégrer a ton pluging dans Kodi , je n'ai pas
les compétences nécessaire ^^

Merci

**Comment by LordVenom** [comment]
Partage nous ce m3u et je regarderais ça.

**Comment by LordVenom** [comment]
Plus de nouvelle, tu as abandonner ou tu as résolut le problème ?

**Comment by kenwood76** [comment]
salut
aucun des deux .
j ai essaye de retrouver comme a l époque d autres adresses en .m3u , que
je n'ai pas retrouvé, j'ai donc transmis ton mail a un pote chez orange
aussi , car ayant une Livebox pro , je pensais que le flux tv pour une
raison inconnue pouvait être bloqué , chez mon pote c est pareil ça marche
pas

on fait peut être une connerie.
le lien que tu m as donné c est bien juste a coller dans VLC ???
si c'est le cas cela ne fonctionne pas chez nous  ;(

2015-08-23 11:40 GMT+02:00 Lord Venom <notifications@github.com>:

**Comment by kenwood76** [comment]
lorsque je colle ton lien c est bien ici ? photo jointe

2015-08-23 11:40 GMT+02:00 Lord Venom <notifications@github.com>:

**Comment by LordVenom** [comment]
Vlc media/ouvir un flux reseaux

**Comment by LordVenom** [comment]
Sinon test avec la liste de ce site http://www.m3u.fr/liste-orange-bouquet-tv.php

Note ça marche par email mais ça retourne chez github c'est pas mon email.

**Comment by LordVenom** [comment]
Sinon regarde ici ça a l'air bien compliquer a priori ça ne fonctionne que avec des ip statique

http://engelleben.free.fr/index.php/configurer-la-tv-d-orange-sur-pc

je peux pas tester j'ai pas orange.mais chez free ça fonctionne lolll

**Comment by kenwood76** [comment]
ravi pour toi et merci de ton aide,

sur le lien que tu m a transmis, les chaines se chargent dans vlc
ester les 15 en testées M6 Fonctionne les autres non , voici le lien qui
marche rtp://@232.0.7.33:8200

2015-08-23 12:06 GMT+02:00 Lord Venom <notifications@github.com>:

**Comment by LordVenom** [comment]
Même lien dans l'addon donc pour le moment aucune solution dsl.

**Comment by kenwood76** [comment]
Merci encore... Je le contenterai du lien télévision du Web elles
fonctionnent parfaitement...

**Comment by TmpName** [comment]
Jete un oeuil a "tele du web/LibreTV" liste "touski" il y a pas mal de chaines HD dedans.

**Comment by kenwood76** [comment]
je viens d 'en trouver un Plugin kodi, peut être pourrais tu t'en inspirer
^^
meme tf1 fonctionne , toutes celles que j ai tester marchent, bon peut être
que tu connais déjà ^^

A+
en pièce jointe

2015-08-23 12:46 GMT+02:00 TmpName <notifications@github.com>:

**Comment by TmpName** [comment]
J'ai un probleme avec les pieces jointes (si c'est a moi que tu l as envoyé), mais tu peux passer le lien sur le forum, a moins que ce soit un addon privé, je vois pas le probleme, Venom n'est pas du genre a interdire les liens vers un autre addons ^^.

**Comment by joss-rendall** [comment]
Salut, g le même souci avec vstream et orange tv, alors je passe par iptv et une liste m3u.

**Comment by TmpName** [comment]
"LibreTv" est justement une liste de liste m3u, tu peux meme mettre ca en  'IPTV Simple Client ' tu auras programme TV et tout le reste.

Leur site http://bit.ly/LiBrE-Tv

Et evidement tu peux proposer tes propres liste ou meme un simple lien de flux.

**Comment by LordVenom** [comment]
@kenwood76 tu peux nous poster le lien de l'addon en question, d'avance merci

**Comment by kenwood76** [comment]
hello,

voici le lien , ou tu pourras le télécharger

"
http://atlasweb.net/atlasweb-extension-pour-regarder-les-meilleures-chaines-francaises-arabesanglaisessports/
"

Sur sa page Youtube , j'ai laissé un petit test rapide, indiquant les
chaines qui déconnent.
a ce jour pas de réponse de l'auteur.


A+

2015-08-26 8:55 GMT+02:00 Lord Venom <notifications@github.com>:

**Comment by LordVenom** [comment]
Ok merci je regarde ça.

**Comment by TmpName** [comment]
Ha oui a une epoque je passais par sa liste m3u avant qu'il en fasse un addon.
Mais le truc c'est qu'il y a plus de monde pour maintenir les liste libretv a jour, et franchement le nombre de chaines qui marchent sur l'un et l'autre n'ont rien a voir.

**Comment by kenwood76** [comment]
Écoute je sais pas moi extraire sa liste... Je cherche des addons qui
marchent, et je les cumules afin d'obtenir des chaînes tv dans la chambre
qui reçoit rien 😀

**Comment by TmpName** [comment]
XD, la chambre qui recoit rien ^^
J'imagine une cave amenagée, meme batman dans la batcave recevait des liens exterieurs.

**Comment by kenwood76** [comment]
Mdr, c'est ça la campagne, bon je suis quand même en Vdsl, mais pas de
réception tnt... Donc ça craind.... Donc depuis jme suis dégoté une antenne
wifi Cisco, j arrose toute la maison, et donc kodi est obligatoire dans mon
cas... Tu es d'où ?

**Comment by TmpName** [comment]
Gotham city.

Nope, toulouse, mais j'ai grandi a la campagne amplificateur pour TV obligatoire mais c'etait avant la TNT.
Depuis que j'ai decouvert Kodi (1 semaine avant la decouverte de Vstream) j'ai debranché le decodeur TV. J'ai le reseau, le debit, mais plein le cul des pubs en boucle et des emmissions a la con. j'avais meme prevu de mettre une seedbox sur la meme machine , mais je l'ai jamais demarrée.

**Comment by LordVenom** [comment]
Ok j'ai regarder l'addon, rien a voir avec une source orange.

**Comment by kenwood76** [comment]
ah  ;(
peut pas t'en dire plus  ... je n'ai pas ces compétences ...
et le gars est pas rapide en termes de réponses depuis sa page Youtube.
