### ISSUE TITLE
Mail.ru

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#203]
Bonjour,

Le hoster Mail.ru n'est plus fonctionnel, il est vide.
Vous pouvez faire le test sur le Site --> FrenchStream.org

**Comment by TmpName** [comment]
En fait c'est le site qui se loupe, ils mettent des lien en 1fichier au lieu de mail.ru quand tu cliques dessus.

Ceci dit si ils continuent comme ca il y a moyen de streamer les film de1fifhier depuis peu apparement.
