### ISSUE TITLE
Marquer Lu/Non lu

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#204]
J'ai remarqué avec le site FrenchStream.org, et après avoir décoché Marquer Vu / Non Vu pour pouvoir revoir encore une fois un film, malheureusement celui démarre toujours a la fin du film?  
C'est quoi exactement le problème?

**Comment by TmpName** [comment]
Ha !!! C'etait ca l'astuce !
Quand on decoche "vu" kodi redemarre automatiquement au debut ? Put1 que ca m'a pourri la vie ce truc.

**Comment by LordVenom** [comment]
Bonjour, 

Le faite de marquer lu/non lu n'a pas d’incidence sur la lecture elle même c'est graphique juste.

Pour le problème jamais remarqué, belle trouvaille. Bref c'est régler je passe ça sur le bêta dans la journer, maintenant il vous demanderas si vous voulez reprendre ou pas.

**Comment by TmpName** [comment]
Sinon Arzaz a raison, quand la personne decide de le cocher en "non vu" c'est pas con d'automatiquement le refaire demarrer a zero.

Ca aiderait pour certain host comme netu qui supporte tres mal la reprise, une fois le film arrété en plein millieu c'est mort, impossible de le finir.

**Comment by LordVenom** [comment]
C'est fait.
