### ISSUE TITLE
Ok.ru

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#205]
Je n'arrive plus a visualiser avec le host Ok.ru, j'ai toujours l'erreur "échec de lecture"
J'ai testé plusieurs films dont POKERS sur le site FrenchStream.org

**Comment by TmpName** [comment]
C'est normal, ca fait un petit moment qu'il est HS, en ce moment j'arrive a recuperer les liens mais il me manque "quelque chose" pour les activer avant de les utiliser.

**Comment by TmpName** [comment]
Ok.ru remit en marche sur beta
