### ISSUE TITLE
film-streaming.co ne marche plus !!!!

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#206]
Bonjour...aujourd'hui film-streaming.co ne fonctionne plus j'ai fait un coup d'oeil sur le site qui apparemments à changé le code ils sont viré les liens directe remplacais par un lien crypté "text javascript"
document.write(unescape("%3Cscript......ext)

est ce que il y a une solution pour lire les videos pour cette source surtout qu'il sont en hd bluray 720p.

**Comment by TmpName** [comment]
Je le trouve pas dans la liste des sites ??

**Comment by mino60** [comment]
Referer apré le test n'a pas résolu le problème et il n'y a pas "file" dont leurs code just un lien cryté dont 
document.write(unescap...

**Comment by arzaz** [comment]
Le site film_streaming_co ne s'affiche meme pas dans la liste des sites de films?

**Comment by mino60** [comment]
c'est bizarre!!! moi j'ai copié collé le script sur Adcami_net.py pour faire apparaître film-streaming.co

**Comment by arzaz** [comment]
Bonjour mino60,
Tu peux revenir avec la manip stp? car je n'ai pas bien compris "j'ai copié collé le script sur Adcami_net.py "

**Comment by TmpName** [comment]
J'ai eu le meme probleme, le site est mit a "off" par defaut dans kodi, il faut aller dans les option de Vstream, puis "general" puis "addon on/off"

**Comment by mino60** [comment]
pour testé le script sur beta voila le fichier zip

http://www.mediafire.com/download/w11wg391u2hv9tq/plugin.video.vstream.zip

moit j'ai un problème de lecture probablement due à la connection internet !!!...

**Comment by mino60** [comment]
aujourd'hui j'ai testé et ça fonctionne nickel, je voulai faire apparaitre la dernière page sur le dialog numiric xbmc mai j'échoue à chaque fois (erreur script)
gui.py : 
http://pastebin.com/98qKEnRf
