### ISSUE TITLE
full-streamvk.com un problème pour affiché les posters

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#209]
le site utilise des posters qui son hébergé sur zonne de telechargement et d'autre sources
j'ai suprimé deux lignes pour les faire apparaitre mai

            sThumbnail = str(aEntry[0])
            #if not 'full-streamvk' in sThumbnail:
                  #sThumbnail = 'http://www.full-streamvk.com' + sThumbnail
            #print sThumbnai

mai il y a un problème pour les posters qui son hébergé sur le site comme Cerise, Friends With Kidsl
Terminator Genisys

**Comment by TmpName** [comment]
Mit a jour sur beta

**Comment by LordVenom** [comment]
Tu as vue tu as des droit collaborateur sur ce git aussi un petit résolut et close issues quand tu as fini la conversation :)

**Comment by mino60** [comment]
merci pour vautre aide problème résolut.
