### ISSUE TITLE
Problème d'encodage des caractères sur les appels à os.listdir

### ISSUE THREAD

**Issue by djeman** [LordVenom/venom-xbmc-addons#211]
Yip,

J'ai un gros soucis car le plugin crash en appelant la fonction os.listdir à cause d'un problème d'encodage.

Dans le log de kodi on voit le crash arriver à la ligne 22 de "plugin.video.vstream\resources\lib\handler\pluginHandler.py" et "plugin.video.vstream\resources\lib\handler\siteHandler.py".

Le dossier est bien défini avant l'appel à os.listdir =>
[PLUGIN] Vstream: Sites Folder: C:/Users/jean-François/AppData/Roaming/Kodi/addons/plugin.video.vstream/resources/sites"

Mais la fonction coupe le nom du profil au c cédille:
WindowsError: (3, 'Le chemin d\x92acc\xe8s sp\xe9cifi\xe9 est introuvable', 'C:/Users/jean-Fran\xc3\xa7ois/AppData/Roaming/Kodi/addons/plugin.video.vstream/resources/sites/*.*')

J'en profite pour dire que je trouve votre plugin excellent, je m'en suis même inspiré pour un soft pour ma smart tv.

**Comment by LordVenom** [comment]
Ho grand dieux j'aimais d'accent sur les ordi nom de dossier ou autre.

J'ai bien une fonction qui remplaceras ç par c mais je sais pas si ça vas tourner.J'ai remplacer les 3 fichiers utilisant os.lisdir il faut que tu les remplaces et que tu me dise si ça fonctionne.

https://github.com/LordVenom/venom-xbmc-addons-beta/tree/master/plugin.video.vstream/resources/lib/handler

**Comment by djeman** [comment]
Je n'ai pas de dossier avec accent je les ai banni il y a 15 ans, je fais l'intermédiaire.
En fait je te fais de la pub sur un forum et j'essaye de gérer les problèmes aussi.

Ca enlève bien la cedille ta modification mais ça n'aide pas à trouver des répertoires
WindowsError: (3, 'Le chemin d\x92acc\xe8s sp\xe9cifi\xe9 est introuvable', 'C:/Users/jean-Francois/AppData/Roaming/Kodi/addons/plugin.video.vstream/resources/sites/*.*')

**Comment by djeman** [comment]
Pour t'aider un peu j'ai fais une paire de test sur une vm.

En partant de la release 0.3.4 et pas de la beta j'ai modifié la fonction __getFileNamesFromFolder comme ceci

    def __getFileNamesFromFolder(self, sFolder):
        aNameList = []
        items = os.listdir(unicode(sFolder, 'utf-8'))
        for sItemName in items:
            sFilePath = os.path.join(unicode(sFolder, 'utf-8'), sItemName)
            # xbox hack
            sFilePath = sFilePath.replace('\\', '/')
            
            if (os.path.isdir(sFilePath) == False):
                if (sFilePath.lower().endswith('py')):
                    sItemName = sItemName.replace('.py', '')
                    aNameList.append(sItemName)
        return aNameList

Ca à l'air de le faire, j'ai passé l'addon corrigé à la personne qui à le problème pour qu'il confirme.
Bon bien sûr j'ai pas pris en compte tous les paramètres de compatibilité inter os, juste essayé de t'aider un peu.

Merci pour ta rapidité de réaction.

**Comment by LordVenom** [comment]
Effectivement, ça fonctionne je poste ça direct sur le bêta, jolie trouvaille pour ta 2eme proposition cette ligne n'existe pas dans l'addon.

**Comment by djeman** [comment]
Merci.

Pour l'edit où je parle de la ligne 30 de default.py c'est pour l'addon script.common.plugin.cache qui est une dépendance du tien.
Je me suis dit que c'était sympa de partager le fix en passant car je ne sais pas où joindre le développeur.

Mais même avec l'addon script.common.plugin.cache hors service à part une erreur signalée au démarrage de kodi ça n'avait pas l'air de gêner ton addon.

**Comment by LordVenom** [comment]
Ho ok, je me disais aussi que j'avais du louper un truc :)

Bon encore merci pour la trouvaille et pour la correction surtout, n'hésite pas si tu as d'autre correction. 

Bon Film
