### ISSUE TITLE
Megastream nouvelle source films et series hd

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#213]
Bonjour  j'ai trouvé ce site sur le net avec une qualité haute définition 1080p et 720p multi langue VFF, VFQ, VOSTFR, VO mais il faut s'inscrire pour accéder aux videos j'ai créer un compt "vstream" mot de passe "vstream" j'ai ajouté la fonction getPremiumUser mais les films ne s'affiche pas je ne sais pas si c'est à cause de la Pattern (mauvai regex) ou la connexion avec l'user "vstream"?
h ttp://w ww.megastream.in/films/

http://pastebin.com/rf3yWkj7

**Comment by LordVenom** [comment]
Mauvais pattern 
```<figure class="alignnone project-img">.+?<img src="(.+?)" alt="".+?>.+?class="title"><a href="(.+?)">(.+?)</a></h4>```

Utilise https://regex101.com/#python dans la case ? tu met "gmis"

<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="http://img11.hostingpics.net/pics/573198Capture.jpg" border="0" alt="Hebergeur d'image" /></a>

**Comment by mino60** [comment]
j'ai corigé la Pattern les titrs et les posters s'afiche maintenant puis j'ai ajouté la fonction next page mais j'arrive pas a accéder à la deuxième page qui donne le choix entre telecharger ou regarder la video

http://pastebin.com/0EGHRezG

**Comment by LordVenom** [comment]
Site HS

**Comment by mino60** [comment]
Le site a changé de nom et devenue megastream.pw . Je l'ai trouvé vraiment très intéressant et je crois qu'il sera fort utile mais pour trouvé le regex c'est un peux déficile et pas comme les autres sites!.

http://pastebin.com/PjWBMgRy

**Comment by mino60** [comment]
http://pastebin.com/QTSzd913

la pattern et just mais les titres ne s'affichent pas , je ne sait pas pour quoi? peut etre une erreur dontrée.

**Comment by zombiB** [comment]
salut j'ai essayé avec ce code http://pastebin.com/dNwJfrT8 mais seul le film les minions a fonctionné avec videomega !!

**Comment by mino60** [comment]
merci pour le code mais malleuresement il n'ya pas la fonction pour les posters et il manque les titres sur la première page , peut etre que TmpName ou Nom donne un coup de main sur le regx juste.

**Comment by TmpName** [comment]
Si vous voulez les poster essayez plutot avec cette adresse
ht tp://m egastream.pw/titles/paginate?perPage=18&page=1&order=updated_atDesc&type=movie&minRating=

**Comment by TmpName** [comment]
Site rajoute en todolist
