### ISSUE TITLE
Exashare a été modifié

### ISSUE THREAD

**Issue by djeman** [LordVenom/venom-xbmc-addons#214]
Yop,

Ca fait une paire de jour que exashare a rajouté une redirection ou fausse page comme youwatch.

**Comment by TmpName** [comment]
Mise a jour de exashare, par contre je n'ai pas vu de chnagement pour youwatch ?

**Comment by djeman** [comment]
Merci beaucoup.

Youwatch n'a pas changé, je me suis pas très bien exprimé c'était pour dire qu'il avait rajouté une fausse page avec une iframe exacctement comme ils ont fait sur youwatch il y a 3 semaines.

**Comment by TmpName** [comment]
La j'ai pas tout compris, j'ai bien vu le probleme sur exashare, mais pour youwatch ce n'a eté que momentané ? Car pour le moment tout les liens youwatch ont l'air de marcher ( a part que le serveur est toujours aussi instable)

**Comment by djeman** [comment]
Youwatch fonctionne très bien :)

C'était un renseignement inutile pour donner un maximum d'information :p

Merci pour le fix rapide, tout fonctionne votre addon est au top.
