### ISSUE TITLE
film illimit + openload

### ISSUE THREAD

**Issue by ttrd06** [LordVenom/venom-xbmc-addons#215]
bonjour à toute l'équipe,

juste pour vous dire que dans le hoster film illimit, les liens avec openload ne fonctionnent pas.
voici la solution à implémenter dans le resolver openload.py:

class NoRedirection(urllib2.HTTPErrorProcessor):
  def http_response(self, request, response):
    return response
  https_response = http_response

opener = urllib2.build_opener(NoRedirection)
location = opener.open('METTRE ICI URL DU FILM TROUVEE DANS LE PARSER').info().getheader('Location')

location donnera l'url exacte sans suivre le 302, il faudra juste enlever à la fin "?mime=true" pour avoir le .mp4

Bon WE

**Comment by TmpName** [comment]
Merci, mais tu aurais un film ou cela deconne ?
La je viens d'y trouver un autre probleme sur "rebelle", il ne trouve simplement pas de liens

**Comment by ttrd06** [comment]
oui par exemple iron man 1

**Comment by TmpName** [comment]
Ok, donc c'etait bien mon regex qui etait foireux, ca devrait remarcher avec la nouvelle version, merci.

**Comment by arzaz** [comment]
J'ai toujours le problème avec le hoster openload, "Fichier introuvable"
ttrd06,
Peux tu me transmettre "openload.py modifié"?

**Comment by cloud1250000** [comment]
Openload, il faut maintenant un interpreteur javascript.

**Comment by ttrd06** [comment]
Morning,
arzaz: il faut aller sur la partie béta de vstream et prendre le openload modifié (moteur de recherche en haut et mettre beta)
cloud1250000: la solution donnée plus haut fonctionne car parfois il y a une redirection 302 et la solution s'adapte à ce pb, il suffit juste de la mettre en place dans openload.py. TmpName le fera surement d'ici peu.

**Comment by arzaz** [comment]
Bonjour ttrd06,
J'ai effectué le test avec celui modifié dans la section beta, mais j'ai toujours "Fichier introuvable"?

Peux tu jeter un coup d'oeil sur openload.py modifié s'il est bien paramétré?

**Comment by cloud1250000** [comment]
J'ai regardé le code bêta et je doute fortement qu'il soit fonctionnel.. le lien du vidéo est obfuscated dans la page maintenant. (Le code javascript avec plein de o_ ou quelques choses comme ca)

**Comment by ttrd06** [comment]
oui en effet, ils ont changé les fonctions. peut-être TmpName ou Lord pourront faire quelque chose ...?

**Comment by djeman** [comment]
Je confirme l'url de la vidéo est camouflé en javascript avec jjencode, bonne nouvelle pour vstream il existe des décodeurs en python qui fonctionnent bien je viens d'en tester un à l'instant:
https://github.com/crackinglandia/python-jjdecoder

On peut tester rapidement la lib jjdecode.py à l'aide du fichier jjdecoder_test.py.
D:\Dev\Python27>python "C:\jjdecoder_test.py" "C:\moo.js"

Le résultat est parfait.

**Comment by cloud1250000** [comment]
oh interessant, c'est bien alors!

**Comment by arzaz** [comment]
Bonjour djeman,

Peux tu le rajouter dans la beta stp?

**Comment by LordVenom** [comment]
@djeman Merci je test et poste ça sur la bêta.

**Comment by arzaz** [comment]
Le problème avec "openload" a réapparu j'ai le message "Fichier introuvable"
C'est encore ce problème?

**Comment by djeman** [comment]
Effectivement ça a encore changé ...

Je viens de regarder vite fait et ils ont changé le bout de script, ils ont packé le script camouflé avec jjencode ...

Donc maintenant il faut unpack la fonction (p,a,c,k,e,d) pour retrouver le code à décoder avec jjdecode pour avoir le lien.
Je crois qu'il y a déjà quelque chose dans vstream pour unpack les (p,a,c,k,e,d), je suis pas sûr.

**Comment by mino60** [comment]
je ne sais pas si ça c'es utile: 

http://pastebin.com/tM2cJ6xz

**Comment by LordVenom** [comment]
Oui y a une function pour ça, packer.py y a un exemple dans le host letwatch

**Comment by arzaz** [comment]
Une mise a jour sur beta est la bienvenue

**Comment by arzaz** [comment]
Une solution svp

**Comment by djeman** [comment]
Va falloir que j'apprenne comment fonctionne github ^^

Bon sinon j'ai une solution en mettant à jour packer.py et openload.py :)
packer.py => http://pastebin.com/jpG9Edpr
openload.py => http://pastebin.com/c6ab5wva

Je sais pas ce que ça vaut, ça me semble pas mal.

**Comment by LordVenom** [comment]
Merci trés bon travail, j'ai poster ça sur le bêta avec juste un modeste modif pour pouvoir toujours utiliser le host letwatch.

**Comment by djeman** [comment]
Arf ça ne fonctionne pas sur letwatch ?

Pourtant j'ai testé les 2 et même d'autres pour vérifier que j'avais juste bien amélioré la compatibilité:
http://img11.hostingpics.net/pics/825428mooooo.png

Tu as un ou des liens qui ne passe pas sur letwatch ? Comme ça j'améliore vite fait la regex tant que je suis dedans.

**Comment by LordVenom** [comment]
Dans film illimit pour moi underworld 2 ne fonctionner pas.J'ai corriger en trichant sur _filterargs

**Comment by djeman** [comment]
En fait je m'étais embrouillé les pinceaux et effectivement j'ai pas pris en compte letwatch ^^

Mais vite revu pour faire un code un peu plus simple on peut faire ça => http://pastebin.com/JzuKHksA
Après c'est toi qui voit, merci pour la mise à jour rapide du github.

**Comment by LordVenom** [comment]
Je suis perdu la :), temps que ça marche ont vas laisser comme ça encore merci.

**Comment by djeman** [comment]
De rien c'était un plaisir de voir comment on decode ça sans javascript.

N'empêche le dernier pastebin avec les 2 regex semblent bien fonctionnel et ça évite le paramètre de la source :p

**Comment by LordVenom** [comment]
Ok je les mis sur bêta.

**Comment by cloud1250000** [comment]
djeman, c'est facile a decoder en javascript?

**Comment by TmpName** [comment]
Hello, ca en est ou cette histoire ?
Chez moi le code etait en clair donc j'ai pas vu que ca marchai plus, y a du neuf ?

**Comment by LordVenom** [comment]
Oui c'est résolut. Je close le post.
