### ISSUE TITLE
Sources mangas

### ISSUE THREAD

**Issue by Ronaldonizuka** [LordVenom/venom-xbmc-addons#222]
Bonjour à tous,
Encore merci pour le travail et pour l'investissement !
Grand fan de manga, je rêve d'une source ultime pour ceux ci, mangacity ne fonctionnant plus je recherche une autre source. 
Et je suis tombé sur ce site vostfranime.blogspot.fr, les animes sont sur exashare . 
Je me suis alors dit que j'allais essayer d'ajouter la source moi même... Mais force est de constaté que ce n'est pas.si simple. 
Je travaille sur un support Android et je ne trouve même pas le dossier sites (le dossier de l'addon même). 
Je demande donc de l'aide à une âme charitable pour m'accompagner dans cette entreprise. 

Encore merci pour tout.

**Comment by LordVenom** [comment]
Bonjour, le dossier pour android c'est 

/sdcard/Android/data/org.xbmc.kodi/files/.kodi/

**Comment by TmpName** [comment]
Mangacity ne marche plus ?

**Comment by domtom25** [comment]
MANGACITY es vide que faire merci

**Comment by TmpName** [comment]
Alors je viens de tester, effectivement il y a un probleme, mais qui provoque un message d'erreur, pas de liste vides.
La correction est sur le beta https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons-beta/master/plugin.video.vstream/resources/sites/mangacity_org.py

Le bug se produit si tu passes par "toute les sources" en passant par le menu d’accueil puis "animes" tu ne devrais pas avoir de problemes.

Essaye d'y aller via navigateur, pour voir si ce n'est pas le site qui a un probleme au moment ou tu testes.

**Comment by domtom25** [comment]
OK MERCI

**Comment by TmpName** [comment]
Mais tiens moi au courant stp, je suspecte une protection cloudflare. En fait je l'ai eu une fois, me suis connecté via firefox et je ne l'ai plus jamais eu, et ca fait plusieurs mois que ca dure. Donc je suis incapable de te dire si elle existe, ou si j'ai pas eu de bol cette fois la.
