### ISSUE TITLE
poypi.com fonctionne plus

### ISSUE THREAD

**Issue by poto25** [LordVenom/venom-xbmc-addons#223]
bonjour a tous c'était pour vous signalé que poypi fonctionne plus .
tout les film marche pas sa me dit fichier introuvable 
merci de me répondre

**Comment by TmpName** [comment]
Je pense que tu en est la !
https://github.com/LordVenom/venom-xbmc-addons/issues/212
Je viens de tester les 2 derniers films, ils ont marchés.
