### ISSUE TITLE
OPENLOAD

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#224]
Encore une fois le host Openload nous fait des misères!!!!!
Une solution pour ce problème?

**Comment by djeman** [comment]
Arf mais un gars de openload a repéré vstream ^^

En tout cas je confirme, nouvelle mini fonction dans l'appel à decodeURIComponent pour le paramètre p de la fonction p,a,c,k,e,d ...

**Comment by djeman** [comment]
J'ai un fix mais alors perso je trouve que je pars de plus en plus dans du bricolage :p
http://pastebin.com/WxbSSnKM

C'est surement à améliorer mais bon ça permet de le refaire fonctionner tout de suite.

**Comment by TmpName** [comment]
H

**Comment by djeman** [comment]
Ben la fonction _cleanstr et la regex qui va avec c'est moi qui l'avait ajouté pour openload donc maintenant elle sert plus à grand chose.
Pour le prochain changement il y a tellement de possibilité qu'il faut voir à quel point ils sont tordus ...

Merci pour le compliment de la conversion mais c'est surement du au fait que je connais pas python donc j'ai vraiment cherché à refaire pareil sans aucune idée de comment faire autrement ^^

Merci pour tout ce que vous faites.

**Comment by TmpName** [comment]
Ha ok, dsl j'avais pas suivi l'histoire, donc utiliser les 3 regex ne sert a rien.
Du coup je met a jour avec ton code, on verra comment ca evolu a la prochaine mise a jour de leur cote.

En fait moi j'ai reconnu le codage rol13 (ce qui est debile en plus vu qu'ils avaient la possibilitée de changer la valeur 13) et j'ai recodé la fonction comme un con avec toute les options.

Mit a jour sur beta.

**Comment by djeman** [comment]
Il va falloir que j'apprenne à utiliser github, mais vous faites déjà un super boulot je vois pas trop ce que je peux apporter.
Pour l'instant je 'clone' votre appli sur ma smart tv samsung en javascript avec utilisation du lecteur interne ça me prend pas mal de temps sans parler des demandes que j'ai sur un petit forum où j'ai un grade assez elevé ...

Je connaissais pas le rot13, par contre quand j'ai refait poypi j'ai vu que le gkdecrypter est en fait juste un algo de décryptage AES 128bits standard mode ECB sans padding utilisant une clé de 192bits. Je le dis au cas où vous voudriez faire plus joli que le flash décompilé mais bon vu que ça fonctionne bien aucun interet à modifier.

Mais sinon comme dit au début votre addon est très bon, il remplit très très bien sa fonction à un tel niveau que je le copie pour avoir un soft ressemblant directement sur ma tv :)

http://img15.hostingpics.net/pics/340037mooooo.png
http://img15.hostingpics.net/pics/926257mooooo2.png

**Comment by djeman** [comment]
J'ai de plus en plus de doute sur le fait qu'on nous observe, il suffit qu'on modifie pour voir un fix arriver le lendemain ^^

Il y a un nouveau cryptage très étrange et donc openload hs.

**Comment by TmpName** [comment]
Lol, meme si c'est le cas, ce n'est pas comparable, eux sont payé pour ca, nous on fait ca pour le fun/defi. Tu imagines ce que ca demande comme boulot juste pour bloquer les quelques users qui passent par Vstream, nope je pense soit qu'ils cherchent encore un truc soit qu'ils ont prevu de faire changer la protection automatiquement tout les X jours (ou alors comme tu dis, ils ont un grand malade passioné qui passe tout les jours sur ce site et cherche de nouvelles protections a chaque fois ^^).

Mais dans tout les cas, il y a une solution de trouvée, aucune protection n'est infaillible, c'est juste que eux font le rapport cout/nbre de bypass, et nous interet du site/temps pour trouver.

Je vais mettre le code a jour dans la matinée (la me leve juste, ouais je sais, suis une larve) mais je vais garder tout les anciens codes actifs, plus facile pour les futures modifs et au cas ou ce soit des protections changeantes.

Tu t'y connais en cryptographie, ou tu fais comme moi, tu decouvres a chaques nouvelle protection apres recherche sur le net ?

**Comment by djeman** [comment]
Nope je m'y connais pas des masses en crypto, juste un passionné comme toi depuis mal d'année.
Et à force d'analyser du code désassembler/décompiler certains trucs se voient vite.

Pour l'histoire des regex, pour détecter les trucs encodés avec aaencode on peut utiliser le début et la fin du code obsfusqué c'est toujours le même.
Du coup on peut rajouter une petit fonction is_aaencoded pour voir si c'est bien ça => http://pastebin.com/xMCHDVAM
http://pastebin.com/XU63LRXK

Tu peux le voir sur l'encoder dispo là => http://utf-8.jp/public/aaencode.html

Le dernier coup quand ils ont mis jjencode le premier patch qui a suivi a été le packer dean edward sur le code jjencodé.
Le second patch a ajouté decodeURIComponent sur le premier argument du packer et le troisième patch c'était avec le replace en plus.
Je me demande si ils vont refaire pareil, le coup du cryptage qui change régulièrement est bien possible ... je me sens un peu espionné quand même :p

**Comment by kikimmax** [comment]
Bonjour djeman
S'il vous plaît comment vous avez fais pour avoir vstream sur votre Smart Tv Samsung  directement 
Merci d'avance
Cordialement

**Comment by arzaz** [comment]
Rebelote, le problème à encore une fois fait surface.
C'est le jeu du chat et la sourie

**Comment by TmpName** [comment]
XD, faudrait laisser trainer pour voir si ca change quand meme, ou si vraiment ils nous surveillent ^^.
La je corrige dpstreming qui remarche mais qui deconne, et je vais voir.

**Comment by djeman** [comment]
Yip, effectivement c'est mon decodeur qui foire je vais jeter un coup d'oeil là dessus j'ai pas pu plus tot car j'étais sur une update d'un autre soft pour compiler/désassembler/décompiler du lua en java que j'ai fait un jour où j'étais super motivé :p

La mini fonction en javascript que tu montres c'est une regex utilisant la fonction test:
http://www.w3schools.com/jsref/jsref_regexp_test.asp

Il y a 2 façon de déclarer une regex soit avec l'objet Regexp soit en mettant des slash au début et à la fin du string et sans mettre de guillemets:
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/RegExp

Bon ben je jette un coup d'oeil.

**Comment by TmpName** [comment]
La commande eval() sous jabascript ne marche pas comme celle en python ?
En tout cas c'est bon, ca marche encore ce soir ^^, Gz

Je met a jour sur beta. Et je viens de voir un nouvel hebergeur pour leur dernier film.

**Comment by djeman** [comment]
Si elle fonctionne pareil que celle de python, c'est les mêmes.
Mais une va utiliser l'interpréteur python alors que l'autre va utiliser l'interpréteur javascript et ça ça risque de poser un soucis.

Après si tu veux faire des tests je te retiens pas, moi je fais un décodage assez brut.
Mais mon dernier aadecode.py devrait être assez solide, c'est juste une extension de celui d'avant permettant des sous opérations avec la même table de référence.

**Comment by TmpName** [comment]
Franchement, je n'ai meme pas essayé de comprendre ton code ^^

Apres je pense au evolutions/variations futures de leur codage et dans ce cas c'est sur que ta version sera plus adaptable, on est pas dans un but d'optimisation, c'est juste un lien a decoder de maniere fiable, pas un calcul repetitif.

Mais je suis content que tu l'ai fais, quand je vois le code, me dis que tu m'as epargné au minimum une journee complete de prise de tete. J'aime les defis mais j'apprecis plus le temps gagné :)

**Comment by cloud1250000** [comment]
Possible d'avoir le meme code en javascript? :D

**Comment by djeman** [comment]
En javascript tu peux faire comme le decodeur de tmpname => http://pastebin.com/DifQhu4H

C'est efficace, bon le coup du eval reste dangereux, sinon mon ancien code sans le dernier ajout => http://pastebin.com/CnMsw3xw
C'est simple de passer de python en javascript ou l'inverse.

Tous observés ... on fait une bonne bande de coupable :p

**Comment by mortael** [comment]
I hope you don't mind posting this in English :)

Great work on your aadecode.py djeman, it's way smarter than how I fixed it a few days ago: http://pastebin.com/PcMyxtPX :)

Just some simple replace/regex did the trick for me.

**Comment by djeman** [comment]
Thanks.
A overall decoding is not a bad idea may be better that left to right as my code :)

What you want to say with "you don't mind posting this in English" ? It's on the web, it's open source and if you want to share with others there are no problems.

**Comment by mino60** [comment]
Ce Host marche sur un plugin pour enigma2 son problème, voila le code si cela peut vous aider.

openload.co.py

http://pastebin.com/i95Gn1uX
