### ISSUE TITLE
DPstreaming.org

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#226]
Le site Dpstreaming.org est vide

**Comment by TmpName** [comment]
Pour le moment il faut attendre un poil.
La protection cloudflare vient de s'activer (en general pour quelques heures), mais bizarrement il vient de se faire blackilister sur firefox ?
On va voir comment ca va evoluer.

**Comment by TmpName** [comment]
Bon ca remarche, petite mise a jour sur beta car les images sont manquantes sur le site et du coup les titres n'apparaissent pas sur Vstream.

**Comment by arzaz** [comment]
Beaucoup de films ne marchent pas avec erreur "Echec Vstram"

**Comment by TmpName** [comment]
Et mon dernier regex est deja HS, il y a de gros mouvements en ce moment sur leur site ....

**Comment by TmpName** [comment]
Mit a jour sur beta.

**Comment by djeman** [comment]
Euh je viens d'aller sur dpstreaming et bon il fonctionne encore niquel mais c'était pour prévenir qu'il change de nom de domaine et en même temps de site.

Quand on arrive sur dpstreaming il y a un petit mot provisoire:
"Comme vous avez pu le constater nous avons eu quelques soucis dernièrement à cause de l'alerte malware même si le site est complètement clean et ne représente aucun danger, nous avons décidé de changer complètement le domaine de DpStreaming.org à StreamingK.com
Vous avez peut être pris l'habitude de la simplicité du design de dpstreaming mais ce derniers contient beaucoup de failles de sécurité se qui nous oblige de le remplacer.
Le site continuera son activité quotidienne sur StreamingK.com avec plein de mise à jour comme nous l'avons toujours fait.
Ce pendant Nous comptons sur votre soutiens et votre compréhensions."

Il va y avoir un peu de boulot, on a de la chance le nouveau site utilise un modèle tout fait déjà présent sur d'autres.

**Comment by arzaz** [comment]
Qu'en est-il de l'update? car elle n'est toujours pas sur beta

**Comment by TmpName** [comment]
Effectivement s'est une copie de quel site deja ? Qu'on ait pas a refaire tout le fichier python.

**Comment by TmpName** [comment]
Bon premier jet https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/streamingk_com.py

Reste a rajouter de la couleur et surtout tester, il y a plein de variante selon les fiches, surtout pour les series.
Je pense finir la version finale pour demain.
