### ISSUE TITLE
recherches lentes

### ISSUE THREAD

**Issue by fredo04** [LordVenom/venom-xbmc-addons#228]
Tout d'abord merci pour cet addon, j'ai commencé par un raspberry et maintenant je suis sur une box tv beelink r89. Depuis quelques semaines la recherche de films est tres lente, aucun soucis avec la lecture des films.

**Comment by TmpName** [comment]
La recherche sur un site particulier ou la recherche globale ?
La recherche globale peut mettre du temps car elle recherche sur plusieurs sites, et certains peuvent avoir des ralentissements.

Si c'est un site en particulier, c'est moins normal que le probleme subsiste durant plusieurs semaines.

**Comment by fredo04** [comment]
C'est sur tout les sites, la recherche peut resté figé bien 1 min avant de passer a l'autre site et ainsi de suite.

**Comment by fredo04** [comment]
C'est sur tout les sites, la recherche peut resté figé bien 1 min avant de passer a l'autre site et ainsi de suite.

**Comment by TmpName** [comment]
Ha ?
Alors la, je vois pas, le seul truc qui peut bloquer c'est quand le site est mort et que Vstream attend pour le timeout, certains regex sont lourd mais ce n'est pas normal que ca te le fasse sur tout les sites surtout si ca marchait avant.

**Comment by fredo04** [comment]
Il y aurrait pas une histoire de fichiers temporaire ou de cache qui augmente avec le temps ? J'utilise la dernière version de kodi pour android.

**Comment by TmpName** [comment]
La je ne peux pas trop te dire mais tu as la possibilitée de vider le cache dans les options"outils".
Tu peux tester mais je pense que tu vas perdres quelques infos (films vus, ....)

**Comment by zombiB** [comment]
Tu peux essayer de désactiver la recherche pour certains sites et tester

**Comment by djeman** [comment]
Mon petit frère a eu le soucis aussi, style il devait attendre 10minutes pour faire une recherche ou plus d'1 minute pour seulement afficher un site.

Le problème a disparu quand il est passé de win8.1 à win10 ...

Il avait installé kodi seulement pour vstream et donc il était clean, le problème semblait venir du système utilisé pour les requetes web et de windows car le log ne contenait pas d'erreur et sur un autre pc au même moment c'était très rapide.

**Comment by fredo04** [comment]
Merci djeman mais je suis sur box android lollipop. Apres nettoyage du cache....pas mieux. Je vais faire un essais en flashant pour repasser sous kikat qui est plus stable
