### ISSUE TITLE
bonjour poypi fonctionne toujours pas 

### ISSUE THREAD

**Issue by poto25** [LordVenom/venom-xbmc-addons#229]
Bonjour tout le monde tout est dans le titre poypi fonctionne toujours pas et sa fait quelque semaine quand je clik  sur un film sa me dit fichier introuvable et avec tout les film même  les nouveaux merci de regarder c'est quoi le problème .

**Comment by TmpName** [comment]
Tu as la derniere version ?
Pendant un moment ils avaient des films sur openlo.d qui ne marchaient pas, la je vient de tester, aucun probleme, mais que des films en googlevid.o.

Tu as le titre d'un film qui ne marche pas ?

**Comment by poto25** [comment]
C'est bizarre moi j'ai aucun films qui marche je viens de tester Terminator genisys et il marche pas et j'ai la version 0.3.4 merci de regarder sa me dit fichiers introuvables

**Comment by TmpName** [comment]
Essaye avec la version du site beta, sinon attend quelques jours, ca va etre le jour des mises a jours. Put1 ca en fait des "jours" dans la phrases.

Ps : le film terminator - genisys n'existe plus sur le site Error 404.

**Comment by poto25** [comment]
Le Terminator il vienne de le supprimer ,je viens d'essayer le jurassic world marche pas aussi. Tu veux bien compresser la bêta pour moi et la mètre en lien pour que je puisse la télécharger car je c'est pas fait  sinon j'attendrai la mise à jour merci d'avance

**Comment by mino60** [comment]
voila le fichier beta Add to zip :   

http://www.mediafire.com/download/117rso4u8lbau1y/plugin.video.vstream%283%29.zip

**Comment by poto25** [comment]
merci mino60 pour le zip ,je viens de l'essayer la beta et c'est super sa fonctionne , merci beaucoup mino60 et TmpName

**Comment by TmpName** [comment]
Apres Venom a rajoute une fonction "mise a jour" pour les sources qui aurait pu t'etre utile, mais franchement vu qu'on approche de la fin du mois, je prefere laisser faire une grosse mise a jour vu que ca fait 1 mois qu'on bidouilles les sources dans tout les sens.
Si cela se produit en debut de mois, l'option se trouve dans le menu de configuration, a la fin.
