### ISSUE TITLE
Films VF + Films VOSTFR

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#230]
Bonjour,

Merci pour cette nouvelle mise a jour, mais il est a noter que dans la catégorie Films VF et Films VOSTFR les dossiers sont vides?

**Comment by TmpName** [comment]
C'est possible, me souvient pas d'un site qui propose ce filtrage, en fait il y a eu une grosse mise a jours sur les menus dans le coeur de Vstream, certains ont du etre rajouté pour pouvoir etre programme plus facilement juste en modifiant le fichier site mais pas encore utilisés.
