### ISSUE TITLE
Question sur possibilité d'ajout d'une source

### ISSUE THREAD

**Issue by bobynou** [LordVenom/venom-xbmc-addons#231]
Bonjour,

Je me pose une question, bien que je pense que cela est déjà était tenté. 

Pensez-vous que l'ajout de ce type de source serai possible? 
w w w.fromhot.com

Enfin, plus large l'ajout de sites de streaming sports.

En tout cas, encore bravo pour le boulot.

**Comment by TmpName** [comment]
Heu, alors y a un manque cote sport oui, et faudrait quelques sources aussi, par contre moi j y connais quedale alors j'aurais quelques questions.

1 - Ce site ne propose que des directs ? Car j'ai essayé pause/reprendre et ca reprend plus tard.
2 - Y a un interet a ce genre de site ? bon ok suis pas la reference mais ca interesse du monde le direct chili/hungary en italien ?

Par contre si comme je pense, il ne s agit que de direct, ca ne va etre difficilement possible sur Vstream, car le logiciel gere surtout les flux fixes (je me souvient plus de l'opposé de "direct").

**Comment by bobynou** [comment]
Ce site n'est qu'un exemple en faite, car propose bcp de sport dont certain qui m'intéressent, le but est de pouvoir ajouter à vstream du sport en livestreaming, Evidament le Chili/hungary en italien ne va pas intéresser grand monde, mais la plupart du temps ce ne sont pas des "chaînes" fixes d'un match à l'autre donc pas facile de mettre que des liens Français.

**Comment by TmpName** [comment]
Ben en fait, une site proposant des streams sport seraient interessants.

Mais plutot en différé, et la je sais pas si c'est ce que cherche un fan de sport.
Et plutot FR, ca si la on filtre sur ton site, il n'y aura 90/100 de la journée entre 0 et 2 videos.

Si tu as des liens, tu peux les proposer, tu n'as rien de garanti, mais vu le peu de lien "sport" ca risque de motiver quelqu'un qui gere le python, par contre evites de donner le lien en dur (met des espaces dans le nom  pour cacher l'url c'est plus "discret").

**Comment by zombiB** [comment]
salut @TmpName ,dans le meme conteste est ce que tu peux ajouter le hoster "v-vids.com" dans le beta pour lire les replay sport sur streamzer 
http://pastebin.com/raw.php?i=6ZTVAmyU
merci

**Comment by TmpName** [comment]
Nickel, merci.
En passant j'ai corrigé quelques bugs dans la source qui faisait deconner certaines video de la categorie sport.
