### ISSUE TITLE
FlashX tv-streaming.ch

### ISSUE THREAD

**Issue by Jayrayme** [LordVenom/venom-xbmc-addons#232]
Bonjour,

J'ai une erreur Fichier introuvable sur du Flashx de tv-streaming.ch.

Peut être y a t'il une astuce ?

Merci d'avance !!

**Comment by TmpName** [comment]
Exact, le host a changé, merci pour l'info.
Remplace ton fichier par celui de la beta https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/hosters/flashx.py

**Comment by Jayrayme** [comment]
Merci pour la réponse rapide,

Je teste ce soir !

**Comment by domtom25** [comment]
bonjour je voulais savoir flashx ne marche pas tv-streaming.ch.

que faut il faire merci beaucoup longue vie a ton addon

**Comment by Jayrayme** [comment]
Remplace les fichiers de ton addon par ceux de la beta :

https://github.com/LordVenom/venom-xbmc-addons-beta

**Comment by domtom25** [comment]
peu tu m expliquex comment faire j y suis aller sur ton lien j ai pas compris

merci

**Comment by Jayrayme** [comment]
Clique sur mon lien

tu télécharge le zip (a droite)

tu te connecte a ton Kodi en SSH, (avec le logiciel WinSCP c'est plus simple)

Tu va dans le dossier de l'addon vStream et tu y remplace les fichier par le zip que tu as téléchargé

**Comment by TmpName** [comment]
Sinon tu remplace ton fichier flashx.py par celui la https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons-beta/master/plugin.video.vstream/resources/hosters/flashx.py

**Comment by Jayrayme** [comment]
@TmpName A savoir que ça n'as pas fonctionner chez moi, remplacer ce seul fichier donne encore une autre erreur :
Erreur
Echec du script: vStream

**Comment by domtom25** [comment]
desole j ai du aller au boulot j ai telecharger ton zip connecte addon kodi et apres

**Comment by mino60** [comment]
@domtom25 Le fichier vstream beta

http://www.mediafire.com/download/ya5pocybx2rahxv/plugin.video.vstream.zip

**Comment by domtom25** [comment]
merci mino60 tu es vraiment genial ca marche nickel 
merci a toi
