### ISSUE TITLE
streamingk.com

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#233]
Tous les liens des films sur streamingk.com sont vides?

**Comment by TmpName** [comment]
J'ai mis a jour sur beta, il y a moyen d'utiliser la mise a jour auto pour ce fichier, peut tu me confirmer que c'est bon pour toi avant que je fasse la mise a jour sur la version officielle stp.

**Comment by arzaz** [comment]
C'est nickel TmpName
Il ne reste qu'a rajouter le nouveau site rachat-de.credit a la place film-streaming.co

**Comment by TmpName** [comment]
C'est fait, mais j'esite a le mettre en mise a jour auto vu qu'il risque de rechanger tres vite.

**Comment by arzaz** [comment]
Si c'est les cas il vaut mieux attendre un peu.

**Comment by TmpName** [comment]
Yep, vais deja mettre streamingk et une autre qui a été zappée, on verra dans quelques jours pour celle la.

**Comment by DDstream** [comment]
Simple curiosité est ce que tout cela a un impacte sur le site en question, je veux dire niveau  ralentissement ou trop de charge sur le site au point de trop charger leur serveur ?

Merci

**Comment by TmpName** [comment]
Nope, en fait c'est juste comme si tu y allais avec ton navigateur, kodi est juste un "navigateur" optimisé pour n'afficher que des titres/film/liens. Il n'utilise aucun protocole special, juste le http, et on telecharge la meme page que tu verrais avec firefox ou IE, apres le contenu est "filtré" pour n'en afficher que l'essentiel.
Aucune requete en boucle.

Par contre kodi n'affiche pas les pubs, mais un bon navigateur avec adblock/Greasemonkey ne les affiche pas non plus.

**Comment by arzaz** [comment]
Le site streamingk.com a changé de nom il est devenu http://streamingz.tv
