### ISSUE TITLE
Film-streaming.com

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#234]
Le site film-streaming.co est vide.
Le site a changé de nom il devient: rachat-de.credit

**Comment by TmpName** [comment]
XD, je croyais a une blague, mais non, c'est vraiment le nom officiel.

**Comment by LordVenom** [comment]
Dsl je voie rien sur bêta.

**Comment by TmpName** [comment]
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/film_streaming_co.py

Now le host est devenu URL_MAIN = 'h ttp://w w.streaming-club.com/' et non pas "rachat-de.credit"

**Comment by LordVenom** [comment]
Ok changement de nom pas de mise a jour rapide possible donc.
