### ISSUE TITLE
Raspberry + OSMC ou OpenElec : Demux Error pour 2 films sur 3 - Seul les liens Streamin.to fonctionnent à 100%

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#235]
Bonjour,
Malgré des semaines (sisi!) d'essais je n'arrive pas à faire tourner Vstream sur un raspberry PI2+
1 film sur 3 environ (parfois) ne démarre pas avec un message m'indiquant de consulter mes logs.
Les seuls qui démarrent à tous les coups et très rapidement sont hébergés sur : streamin.to

Je joins mes logs en espérant que vous aurez une petite idée.
Bien sûr j'ai installé les licences pour les codec.
Toute aide sera la bienvenue.
Remerciements anticipés,

http://pastebin.com/RLAe5yGa

**Comment by TmpName** [comment]
Essaye d'editer ton post et de le mettre le log sur pastebin stp, il y a pas mal de liens qui seraient mieux ailleurs que sur github.

Sinon pour en revenir a ton probleme, je note

>>11:41:38 486.201263 T:1515185216 NOTICE: LoadJpeg: unable to load http://s3.postimg.org/7qz42thgj/borderline_tv_affiche_5437b9d84e0bb.jpg

lien qui marchent tres bien chez moi

Sinon tu essaye avec un fichier exashare, qui devrait deconner, tu vas avoir un message du type 11:37:16 224.194351 T:1506796608 ERROR: Open - Error, could not open file ht tp://fs1.exashare.com:8777/p6xknmwbz mm56o m6folcz32uc x4bdwq/v.mp4

Essaye d'ouvrir ce lien dans ton navigateur web, et verifis aussi le lien precedent
>>11:36:39 186.528122 T:1708196928 NOTICE: [PLUGIN] Vstream: Hoster - play ht tp://www.exas hare.com/embed-cctr...0x360.html

**Comment by canopre** [comment]
Merci pour ta réponse mais il n'y a pas de navigateur dans openelec

**Comment by canopre** [comment]
Quand je démarre un lien exashare voila ce que ca donne:

http://pastebin.com/pBq4BhSd

Par exemple : dans les nouveautés de Libre-Stream.org
Le Film : Mad Max : Furry Road : Il y a 5 liens et seulement le dernier fonctionne (watching)

**Comment by TmpName** [comment]
Il y a la possibilitée d'ajouter chromiun ou un truc comme ca, mais tu peux l'ouvrir dans un autre navigateur sur un autre ordinateur, je crois que exashare genere les liens protege par IP.
En fait moi je ne peux pas voir si le lien genere par ton kodi fonctionne ou pas, vu que l'on a pas la meme ip.

Sinon tu peux aussi afficher le menu contextuel et faire "telecharger", puis essaye d'ouvrir le fichier avec kodi.

**Comment by canopre** [comment]
Est-ce qu'un autre addon pourrait géner Vstream car j'ai l'impression que sur une installe neuve ca fonctionne mieux ?

**Comment by canopre** [comment]
si tu as un raspberry 2 sous la main : je peux partager mon image car après tout ce temps je n'y arrive tjrs pas :(

**Comment by TmpName** [comment]
Ben en fait j'ai un raspberry oui, et c'est justement pour cela que ma machine dedié au multimedia est sous windows.

Pour moi ca ressemble plutot a un probleme d'autorisation (les films qui deconnent ont l'air d'etre sur un autre port que le 80) ou de codecs.

C'est pour cela que je te demandais d'essayer le lien sur un autre ordinateur ou de telecharger le fichier via Vstream.

**Comment by canopre** [comment]
sur mon pc windows + kodi : ca marche très bien : c seulement sur le raspberry :(

**Comment by TmpName** [comment]
Donc si tu fais un copier copier du lien du log sur le pc windows, le lien s'ouvre ?
Et pour le telechargement ?

**Comment by canopre** [comment]
un copier/coller de ce lien fonctionne parfaitement dans mon navigateur:
https://openload.co/stream/f0yv9Tc40Bk~1444668352~90.31.0.0~CKdceegq
Et pas dans Kodi / Vstream
Par contre je peux télécharger le film en passant par vstream + télécharger.

**Comment by TmpName** [comment]
Ok donc c'est un probleme de codec, et je pense que si tu essayes de lire le fichier telecharge, ca ne doit pas marcher non plus.
Tu as essayé de bidouiller les options de lecture dans kodi ? (acceleration materielle ect ...)

Pour savoir si cela vient de kodi ou openelec il faudrait essayer de lire le fichier sans passer par kodi, mais la je ne connais pas du tout les outils inclus dans openelec ....

**Comment by canopre** [comment]
Je te remercie pour ton aide.

Je n'ai rien bidouillé du coté de l'accélération matériel : j'ai laissé les réglages par defaut pensant que ct le mieux.

J'ai essayé la solution indiqué ici mais sans succès (je veux dire sans changement notable): 
https://www.assetbank.co.uk/support/documentation/install/ffmpeg-debian-squeeze/ffmpeg-debian-jessie/

Et pour info les films hebergés chez streamin.co fonctionnent tous parfaitement.

Je vais maintenant essayer de lire le fichier chargé.

**Comment by canopre** [comment]
J'ai donc téléchargé un film qui ne fonctionnait pas en streaming et je l'ai lu dans Kodi.
Et là tout fonctionne.
C'est donc clairement un problème de droit...
Ceci étant dis : je ne sais vraiment pas quoi faire pour corriger ce pb....

**Comment by TmpName** [comment]
Je viens de penser a un truc, j'ai aussi ce probleme, et je cherche une solution.
Tu as jeté un oeuil a ton timeout ?
Pour les videos qui ne marchent pas, ca te le dit direct, ou ca mouline 20/30 s avec l'icone qui tourne en bas de l'ecran ?

**Comment by canopre** [comment]
ca mouline 20/30 sec et plus rien ou un message m'indiquant de consulter mes logs.
Pour le time-out je ne sais pas comment le vérifier ou le modifier.

**Comment by canopre** [comment]
effectivement : j'ai mis:
<playlisttimeout>5</playlisttimeout>
et ca semble marcher bcp mieux !

**Comment by canopre** [comment]
C'est un truc de fou : ca a marché pendant 1H : j'ai testé une dixaine de films qui ne marchaient pas avant et tout était OK.

Mais 1 heure + tard : Retour à la situation d'origine : plus aucun de ces films ne démarrent ;(

**Comment by TmpName** [comment]
Par defaut c'est 20, pour 20s, et meme ca c'est limite pour certains hosts comme youwatch ou ca peut mettre 60s ou meme plus.

**Comment by LordVenom** [comment]
Faudrais voir le cache réserver pour c'est petite machine pas certain que le stream sois dans leur fonction de base.

**Comment by canopre** [comment]
Pulsar tourne parfaitement alors je ne crois pas que ca soit un pb de puissance : car c'est du P2P sans doute plus gourmand en ressources ?

**Comment by canopre** [comment]
""Par defaut c'est 20, pour 20s, et meme ca c'est limite pour certains hosts comme youwatch ou ca peut mettre 60s ou meme plus.""

Ducoup je comprends pas trop ? Il vaut mieux mettre 10, 20, 60, + ??
J'ai mis 65 pour essayer mais j'avais un message d'erreur au bout de 30 sec environ..

**Comment by LordVenom** [comment]
Pour le timeout le soucis c'est que c'est une function internet a kodi qui s'ocupe de la lecture @TmpName  et entrain de regarder.Pour le moment ont n'en sais pas plus dsl.

**Comment by canopre** [comment]
Merci merci ! c'est déjà bcp !
Je suis content de trouver un peu d'aide car en vrai ca fait 3 mois que je galère sans me décider à demander du secours.
En fait c'est que ca marche et pis...ca marche plus...alors à chaque fois je me remotive mais sans succès définitif...c'est frustrant... mais je suis une bille en linux et je dois bien me rendre à l'évidence : je vais pas y arriver tout seul...
Alors encore merci d'avoir pris le temps de me répondre et de me donner quelques indications.

**Comment by LordVenom** [comment]
Y a des erreurs plugin://plugin.program.super.favourites/ je pense pas que ça resolve le problème mais pour tester tu devrais désactiver ce plugin.

**Comment by canopre** [comment]
ok merci : je vais essayer.

**Comment by canopre** [comment]
Malheureusement ca ne change rien...

**Comment by LordVenom** [comment]
Dsl je suis a cours d'idée.

**Comment by canopre** [comment]
J'ai déjà essayé 2 Openelec + 2 OSMC + Xbian avec tjrs le meme résultat.

**Comment by TmpName** [comment]
Et en mettant playlisttimeout> 80 </playlisttimeout ??

Par contre ca va tout bloquer pendant 80s .....

**Comment by canopre** [comment]
comme indiqué + haut : J'ai essayé avec 60 mais ca bugge toujours après 20/30 sec.
Ca ne change pas grand chose en fait.

**Comment by canopre** [comment]
Hello,
Je me demandai si une mini box Android dans ce genre pauserait moins de problème ? :
www.amazon.fr/Andoer-Android-Bluetooth-Externe-Antenne/dp/B00W798KEA/ref=sr_1_11?ie=UTF8&qid=1446074052&sr=8-11&keywords=android+pc

Avez-vous déjà testé Kodi sur ces petites machines ?

**Comment by canopre** [comment]
Je vais essayer sur ma petite tablette S8 et je vous dirai si je vois une différence.

**Comment by LordVenom** [comment]
Voila nos installations 

https://github.com/LordVenom/venom-xbmc-addons/issues/190

**Comment by canopre** [comment]
Hello,
Je ne comprends pas pourquoi à certaines heures plus rien ne marche (entre 20H et 6H du mat environ pour la métropole)
Et ensuite presque tous les liens fonctionnent du premier coup sans lag ni délai...
Tous les hosts ne sont pas sur le même abonnement cloud quand même ?

**Comment by bsouhdz** [comment]
Hello,
moi aussi pareille,

Souhila B

**Comment by TmpName** [comment]
XD, suis en train de chercher une solution aussi, mais moi c'est entre 21h et 22h30 tres precisement ou la plupart des hosts rament ou ne marche carrement plus (youwatch et exashare surtout).

En fait je tourne surtout sur flashX et uptostream en ce moment (voirfilms_org a pas mal de sources qui fonctionnent).

Quand je suis obligé de passer par youwatch, je met les fichier en telechargement juste avant.

J'ai pas encore trouvé de solution par kodi et meme par vlc ca ne marche pas, il me faudrait le lancer en mode debug pour trouver le parametre qui manque, mais comme je ne peux le faire que a certains horaires, j'ai pas forcement le temps pour les tests.
