### ISSUE TITLE
Un tri des recherches [idée]

### ISSUE THREAD

**Issue by SuN969** [LordVenom/venom-xbmc-addons#237]
Bonjour/Bonsoir, encore une fois merci pour ce plugin des plus utile! 

Mais je mettrais quand même un petit bémole, serait-il possible de permettre un tri des résultats de recherches sur la qualité? 

Ou un outil de recherche avancé qui nous permettrait de n'afficher que les résultats qui ont 720p ou plus en terme de résolution? 

Merci d'avance et bonne journée/soirée

**Comment by LordVenom** [comment]
Bonjour, 

Il nous et impossible de faire un tris que la source ne fait pas.Exemple si le site internet n'a pas de tris 720 et 1080 nous ont ne peux pas le faire. La qualité tient plus du host que du site oublier donc youwatch.

**Comment by TmpName** [comment]
Surtout que certains site proposent la recherche "720p" ou "HD" alors que c'est n'est pas du tout le cas, ou alors pire de la SD upscalée pour faire de la HD.

D'autres proposent de bonne resolution HD mais du coup rognent sur le taux d'image ou la qualitée, ce n'est vraiment pas un critere a prendre en compte, vraiment pas fiable.
