### ISSUE TITLE
CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.vstream

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#239]
Hello

Pour certains films j'ai une erreur CreateLoader 

Je ne sais pas si the LordVenom peux y faire quelque chose mais je le signale quand même.

http://pastebin.com/YcUe7yMW

**Comment by LordVenom** [comment]
Bonjour, cette erreur et connue mais pour le moment non résolvable de plus c'est un WARNING et non un ERROR ça ne plante pas le pluging.

**Comment by canopre** [comment]
Non ca ne plante pas le plugin mais ca ne lit pas non plus le film.

**Comment by TmpName** [comment]
Je viens d'essayer aussi, ca ne gene pas pour la lecture du film, a moins que ca ne marche pas sur toute tes sources.
Je viens de tester le film, il est tres long a charger sur vodlocker, et si il met plus d'un certain temps a se charger (20s de timeout par defaut) tu te retrouves avec un message d'erreur.
Ca depend surtout de la rapiditée des serveurs (Le pire etant youwatch), essaye en augmentant le timeout dans advancedsettings.xml.
Le mieux etant de passer par un site proposant plus de 5 hebergeurs pour avoir plus de chance d'en trouver un de dispo au moment ou tu veux voir le film.

**Comment by canopre** [comment]
merci pour ces conseils.

**Comment by TmpName** [comment]
Tiens moi au courant si d'augmenter le timeout marche pour toi. Ca fait quelques jours que je suis dessus et j'ai besoin de retour pr savoir si ca vaut le coup.

**Comment by canopre** [comment]
Comme indiqué dans l'autre post ; j'ai modifié le timeout à 60 puis 80 sec mais ca ne change rien pour moi : les films qui ne veulent pas démarrer sont toujours bloqués mais je n'ai pas besoin d'attendre tout ce temps pour que le message d'erreur apparaisse.

**Comment by LordVenom** [comment]
Non cette erreur n'a rien a voir avec la lecture du fichier tu peux voir dans ton log que l'erreur 
ERROR: Open - Error, could not open file 
ce produit bien avant le WARNING qui et en faire un retour au menu aprés une fonction.

**Comment by canopre** [comment]
ok alors ! Comme tu peux le voir j'ai quelques lacunes :)

**Comment by TmpName** [comment]
Wé 80s, c'est quand meme deja pas mal par rapport a 20s.
Quand je teste sur firefox, ca met parfois plus de 80s, mais ca fait long comme bloquage ....

**Comment by canopre** [comment]
ca se lance ou pas. Mais globalement ca va quand meme mieux en augmentant ces valeurs.
Par contre je n'ai jamais à attendre plus de 30 secondes pour que le film se lance...ou pas...
Je veux dire que je n'ai jamais à attendre 80 ou 240 secondes avant d'avoir un message d'erreur, rien dutout ou le film qui démarre.
