### ISSUE TITLE
Activation de l'option "meta données"

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#240]
Bonjour,
Quand j'active l'option "meta données" qui devraient seulement "ralentir l'addon" certaines pages ne sont plus consultables avec l'erreur suivante :

http://pastebin.com/B3aQR8bF

C'est dommage car je ne le savais pas : Cette option affiche également les fanarts en background.

**Comment by LordVenom** [comment]
Bonjour, Mauvais code ça seras réparer a la prochaine mise a jour merci du rapport.

**Comment by canopre** [comment]
Hello.
Juste une petite question : Quand cette mise à jour sera-telle dispo car chez moi c'est tjrs buggé ?

**Comment by LordVenom** [comment]
Bonjour, 

Encore un peux de patience Mise à jour Demain.

**Comment by canopre** [comment]
Super ! Merci pour la réponse.

**Comment by canopre** [comment]
Bonjour,
Avec la dernière mise à jour tout s'affiche bien et sans erreur maintenant.
Sauf pour les séries :  l'affiche visible en grand droite ne s'affiche pas en petit dans le menu de gauche.
Avec-vous le même problème ?

**Comment by LordVenom** [comment]
Bonjour, dsl je comprend pas, quel vue? quel theme?

**Comment by bsouhdz** [comment]
pour moi sur demo Primcub ruby impossible de l'installer tout cour, mais
vstream v0.3.6 marche super bien!

Souhila B

2015-11-12 11:11 GMT+01:00 Lord Venom <notifications@github.com>:

**Comment by canopre** [comment]
Quand je consulte la liste des films : Tout se passe correctement :
- Il y a l'affiche du film, en petit à gauche du titre + un fond d'écran + à nouveau l'affiche du film en grand à droite.

Quand je consulte les séries :  L'affiche de la série qui est bien visible en grand à droite n'est pas visible en petit à gauche sur la même ligne que le titre.

**Comment by canopre** [comment]
Autre petit "bug" concernant les meta données et les fanart :
Certaines sources n'indiquent par les meta pour beaucoup de films : full_stream_me
Je ne pense pas que vous puissiez y remédier.

Mais pour ces films, le fanart de fond d'écran ne s'affiche pas et je me demande si c'est normal ?

**Comment by LordVenom** [comment]
Je vais vérifier ça merci, pour le bug j'ai pas de vue ou il y a le thumb et l'icone en même temps.
Donc je répéte ma question quel thème utilise tu et quel et le nom de la vue ?

**Comment by canopre** [comment]
Désolé : j'utilise Aeon Silvo et je ne sais pas dutout le nom de la vue mais c'est celle par défaut.

**Comment by LordVenom** [comment]
A mon avis ton thème utilise un thumb non télécharger par metahandle.Dsl

**Comment by canopre** [comment]
Mais le thumb apparait bien pour les films et les dessins-animés.

**Comment by LordVenom** [comment]
Utilise le theme par default (confluence) et dit moi sur quel site tu trouve ce bug.je n'installe pas Aeon trop de dependance.

**Comment by canopre** [comment]
Le problème c'est qu'avec Confluence il n'y a pas de vignettes dans la liste des séries.

**Comment by LordVenom** [comment]
J'ai tester aeon nox pas de soucis nom plus ton theme et buguer.

**Comment by canopre** [comment]
Hello
C'est pas impossible que mon theme soit buggé.
Mais quand meme très étonnant que :

- Quand y'a pas de méta : le thumb s'affiche correctement mais y'a pas de fanart.

- Et si y'a les métas : Y'a pas de méta et seulement la

**Comment by LordVenom** [comment]
J'ai même fait l'effort d'installer ton theme, mais serieux !!! j'ai pas la même chose que toi lollll.

http://hpics.li/3a99271

**Comment by canopre** [comment]
c couillon :)
Et pour les films : Chez toi c également les logos des compagnies qui s'affichent à gauche ?
Chez moi c'est l'affiche en petit...
C'est sans doute à cause d'OSMC... Tu utilises quel OS ?

**Comment by canopre** [comment]
Bon ben là d'un coup ca marche niquel : j'ai tous les petits logos qui s'affichent !
J'ai rien fait alors on va dire que c'est vous les gars.
Et pis de toute façon vous méritez bien un grand merci !
Ca dépote de mieux en mieux !

**Comment by titibulle** [comment]
Bonjour. Moi quand je lance les chaînes tv sur vstream ça me met échec de lecture d un ou plusieurs fichiers. Que dois je faire
Merci

**Comment by TmpName** [comment]
Bonjour, il nous faudrait un peu plus d'infos, il s'agit des chaines par fournisseur d'accés, les chaines WEB ou la partie libreTV ?
