### ISSUE TITLE
Petite Question au sujet du fichier settings.xml

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#241]
Bonjour,
Quel est svp la fonction de la valeur "service_time" ?
<setting id="service_time" value="2015-10-18 19:22:57.010206" />
Que se passe t'il si on la trippote ?

**Comment by TmpName** [comment]
Elle sert pour verifier les mises a jours, elle declenche des verifications toutes les 48h.
Si tu la change, tu ne vas voir aucune difference, si tu la met trop vielle, ca va reverifier les mises a jour, trop "futuriste", les verification ne se feront jamais.

**Comment by canopre** [comment]
Merci bcp !
