### ISSUE TITLE
Téléchargement de films sur une cléf USB impossible : OSMC redémarre.

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#244]
Bonjour,
J'essaie de sauvegarder des films sur une cléf USB (8 et 64 gigas) mais c'est impossible : après quelques dizaines de mégas OSMC plante et redémarre systématiquement.
Par contre aucun soucis pour downloader un film de 2 gigas sur la directement sur la carte micro-sd de mon raspberry.

**Comment by LordVenom** [comment]
Bonjour, 

Le téléchargement plante ou la copie ?

**Comment by canopre** [comment]
Kodi redémarre donc le téléchargement ne se finit pas.

**Comment by LordVenom** [comment]
Ok, peux tu fournir ton log qu'on puisse ce faire un idée du problème.

**Comment by TmpName** [comment]
Je vais encore passer pour le troll de service mais j'ai peur que ce soit encore un probleme de "magie linux", il ya pas moyen d'acceder a un terminal sous OSMC pour tester un download en ligne de commande ?

**Comment by canopre** [comment]
les logs de ma dernière tentatives :
http://pastebin.com/uLtserkC

Pour info : Depuis hier j'ai modifié mon cache dans advancesettings.xml et maintenant je peux charger une plus grande partie du film avant que ca plante.

**Comment by TmpName** [comment]
Attend, j'avais mal compris, c'est quand tu telecharge vers la cle usb que ca plante ou juste quand tu deplace un fichier ?

**Comment by canopre** [comment]
C'est seulement quand je télécharge vers une clef.
Quand je télécharge vers la carte SD : Aucun problème.

**Comment by TmpName** [comment]
Par contre je viens de voir un truc que je n'ai pas chez moi quand la video ne marche pas.

>>ERROR: Open - failed to open source <plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=%C3%80.......HQ%29+%5BCOLOR+skyblue%5DYouwatch%5B%2FCOLOR%5D+%5BCOLOR+khaki%5D%5B%2FCOLOR%5D&sHosterIdentifier=youwatch&sTitle=%C3%80+..........%5D&bGetRedirectUrl=False&siteUrl=http%3A%2F%2Fyouwatch.org%2Fembed-n0q4ano3d0ft-580x360.html&sFav=.....

**Comment by LordVenom** [comment]
Ha mais quand tu télécharge normalement ça fonctionne, ou quand tu lis le fichier ça tourne ?
Car la je voie rien de spécial dans le log.

Pour cette erreur quand il n'arrive pas a lire un fichier il retourne sur ça page et la y a une erreur j'ai déjà tenter de réparer ce bug mais j'ai toujours pas trouver.

**Comment by canopre** [comment]
quand je télécharge sur la carte SD du raspeberry tout est OK.
Le problème c'est que quand je sélectionne la clef USB pour sauvegarder le film : au bout d'un moment, variable selon la taille de mon cache, le raspberry redémarre.
Je peux vous montrer mes logs pour un nouvel essai avec un cache bcp + petit.

**Comment by TmpName** [comment]
Je connais pas trop le fonctionnement de kodi mais l'erreur "Open - failed to open source <plugin://plugin.video.vstream/" ressemble a une erreur de chemin, comme un fichier introuvable.
Mais ton log est hallucinant
>> ERROR: Open - failed to open source <https://raw.githubusercontent.com/xoptimus/dexter/master/addons.xml.md5
ERROR: Open - failed to open source <https://plexus.svn.codeplex.com/svn/trunk/Addon/addons.xml.md5>
ERROR: Open - failed to open source <http://localhost:65251/repository/steeve/plugin.video.pulsar/addons.xml.md5

Et j'en passe, tu essayes de te connecter de partout, et y a rien qui se connecte.

**Comment by canopre** [comment]
voici mes logs avec moins de cache et donc plantage plus rapide :
http://pastebin.com/eF44pA88

**Comment by canopre** [comment]
mes prochaines logs : j'ai fait enregistrer vers /dossier personnel/ (c'est à dire sur la carte SD du systeme) et tout va bien se passer

**Comment by LordVenom** [comment]
Je comprend plus la si ça télécharge sur ta sd vStream n'est pas en cause, tu as un problème de permission avec ton system.Tu devrais demander sur le forum de raspberry.

**Comment by TmpName** [comment]
Franchement je ne vois aucune differences entre les deux logs, mais comme le dit LordVenom, je pense que le probleme vient plutot du systeme.
Si tu as le temps essayes carrement avec Raspbian qui est deja assez bidouillé pour avoir le quota de bug.

**Comment by canopre** [comment]
J'ai résolu le problème en mettant un très gros cache et maintenant je peux sauvegarder directement sur la clef USB

**Comment by canopre** [comment]
je voudrai bien essayer raspbian mais la semaine dernière il n'y avait tjrs pas de Kodi 15 pour Raspbian Jessie :(

**Comment by TmpName** [comment]
Ca marche mais tes logs sont quand meme inquietants, il y a vraiment un truc qui cloche quelque part.
