### ISSUE TITLE
Téléchargements : Fenêtre de controle ?

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#245]
Bonjour,
Après avoir lancé un ou plusieurs téléchargements de films : y'a t'il une fenêtre Kodi que l'on peut appeler pour afficher et éventuellement arrêter/mettre en pause les téléchargements en cours ?
Merci d'avance pour vos réponses.

**Comment by LordVenom** [comment]
Bonjour,

Xbmc (kodi) n'est pas fait pour télécharger il n'est donc pas possible de gérer le téléchargement.

**Comment by TmpName** [comment]
Et Vstream ne peut en gerer qu'un.
Par contre qui a deja testé cet addon http://kodi.wiki/view/Add-on:Simple_downloader_for_xbmc_plugins ?

C'est de base integré a kodi, et d'apres la description ca gere la file d'attente.

**Comment by canopre** [comment]
merci : je vais le tester

**Comment by LordVenom** [comment]
Oui ça devrais etre possible mais il faudra encore inclure une dependance.

**Comment by TmpName** [comment]
Vu qu'elle y ait de base dans Kodi, c'est si genant que ca ?
Perso je me vois pas refaire un download manager, et apparement meme combat sur Genesis, ils ont viré le download le temps de trouver un addon externe.
Et vu que la journée, tout les liens marchent tandis que le soir a 22h plus aucun, je pense que ca pourrait etre utile.

**Comment by canopre** [comment]
ca serait cool.
Pour les films qui ne marchent plus à partir de 22H : chez moi ca fait 17H et ducoup la soirée streaming est foutue :(

**Comment by TmpName** [comment]
Je te comprend, la ca me saoule mechament, surtout que si tu es patient au bout de 3/4 mn le film demarre sur un navigateur.

Pour le moment j'ai trouvé une nouvelle option pour augmenter les delais, mais c'est pas encore ca.
>>         <curlclienttimeout>240</curlclienttimeout>  
         <curllowspeedtime>240</curllowspeedtime>

**Comment by canopre** [comment]
je suis patient mais j'ai pas de navigateur sur ma tv : juste un raspberry...

**Comment by canopre** [comment]
""Par contre qui a deja testé cet addon http://kodi.wiki/view/Add-on:Simple_downloader_for_xbmc_plugins ?""

Il est installé par défaut sur mon kodi et je pense que c'est cet addon qui gère les downloads mais je n'ai pas trouvé de fonction pour stopper ou mettre en pause les downloads en cours.

**Comment by TmpName** [comment]
Ben c'est pour ca en fait que j'ai edité un de mes precedents post.
Il est plus puissant (et encore je pense avoir vu mieux), gere plus de format mais a part la file d'attente, il n'a pas grand chose de plus, pas de gestion de la reprise, pas d'interface ....

**Comment by LordVenom** [comment]
Tu as regarder du coter de l'addon JDownloader.

**Comment by TmpName** [comment]
Yep, mais on a besoin de l'application Jdownloader pour s'en servir, application qui est en java.
1 - Ca oblige ls users a installler Jdownloader.
2-  Le java c'est le mal.
3 - Le java est controlé par astaroth
4 - Le Java est une porte vers l'enfer.

**Comment by TmpName** [comment]
Bon le probleme a l'air plus tordu, j'arrive a lire le fichier dans firefox mais impossible dans VLC ou MPC, donc pour le moment bloquage.

**Comment by hawwach** [comment]
ذطzzzzX

**Comment by TmpName** [comment]
Pour info, on cherche des testeurs pour essayer la fonction de tlechargement beta https://github.com/LordVenom/venom-xbmc-addons-beta
Pour ceux qui savent comme l'installer et revenir en arriere en cas de probleme, car on est encore en phase de tests.

**Comment by bsouhdz** [comment]
merci de votre attention oui je v teste et je vous tiendrais au courant de
tt

Souhila B

**Comment by TmpName** [comment]
Si tu as des idées d'amelioration, n'esites pas, c'est le moment on a pas trop de propositions pour le moment.

**Comment by bsouhdz** [comment]
ok


Souhila B

2015-11-17 19:18 GMT+01:00 TmpName <notifications@github.com>:

**Comment by canopre** [comment]
je regarde ca et je vous tiens au courant de mes essais.

**Comment by canopre** [comment]
Houlala : c bcp + compliqué que prévu et je ne sais pas comment installer ce beta add-on.

**Comment by TmpName** [comment]
Lol, c'est pas grave, surtout que en cas d'erreur pour revenir en arriere ca risque d'etre encore plus compliqué.
Tu devrais pourvoir tester en debut de mois prochain dans tout les cas dans la version officielle.

**Comment by bsouhdz** [comment]
OK j'attendrai la version officielle ds 1 mois bon courage


Souhila B

**Comment by canopre** [comment]
Merci d'avance !

**Comment by canopre** [comment]
Bonjour,
J'ai installé le dernière mise à jour de l'addon mais je ne vois pas trop de différence lors du téléchargement d'un film.
Pouvez-vous nous en dire un peu plus au sujet des dernières améliorations ?

Merci d'avance.

**Comment by TmpName** [comment]
En fait avant tu ne pouvais telecharger les films qu'un par un, Maintenant tu peux les rajouter dans une liste d'attente, et mettre une saison complete en telechargement, et il y a meme la possibilité de laisser Vstream passer au fichier suivant quand un est fini.

**Comment by canopre** [comment]
Merci pour ta réponse.
Pour info : on pouvait déjà lancer plusieurs download simultanés mais ils démarrait tous en même temps : il n'y avait pas de file d'attente.
Par contre on ne peut tjrs pas stopper un DL ?

**Comment by TmpName** [comment]
Si, il y a une option pour arretter le download en cours (vu que maintenant il n'y en a qu'un a la fois) dans le download manager.

**Comment by canopre** [comment]
Ok : j'ai trouvé comment arrêter les DL : merci pour les explications et cette nouvelle fonction.

Mais une petite remarque:
- J'ai lancé un DL et comme avant une fenêtre s'ouvre pour m'indiquer la progression du DL.
- Puis je suis allé dans le nouveau gestionnaire de DL et là le DL c'est arrêté et le gestionnaire indique 0mb/270 de téléchargé (alors que 2 ou 3 mb avaient déjà été DL.

C'était mieux avant : la fenetre de progression restait tout le temps apparente ; sauf visionnage d'un autre film et surtout le DL ne s'arrêtait pas quand on naviguait dans l'addon vstream.

Ducoup j'ai cliqué sur "Démarrer la liste" : Rien ne se passe.

Je retourne dans la liste de DL : Il y a marqué "En Cours" en rouge mais je suis tjrs à 0mb / 270.

Je clique sur le film : il démarre tout de suite mais je n'ai tjrs aucune indication de la progression du DL.

Si j'ai pas été assez clair n'hésitez pas à me demander des détails.

Et encore merci pour le super "SAV" :+1: s

**Comment by TmpName** [comment]
Alors ca a plus ou moins l'air normal.
Ce qui semble normal dans la liste de DL que cela reste bloque a 0/270.
En fait a la base ca ne se met a jour que les 10/20/30/40/../100 % (pour ne pas bouffer les ressources de kodi, les telechargement sont egalement ralentis volontairement avec une pause forcée) et sur la page de telechargement ca a été desactivé pr le moment car on ne voyait pas qui pourrait rester sur cette page a surveiller les DLs,
"Demarrer la liste" ne peut demarrer les DL que si aucun DL en cours, donc si tu as un DL marque "en cours", ca active juste l'option pour la fin du DL en cours.

Ce qui n'est pas normal.
La petite fenetre en haut a droite ne devrait pas disparaitre, elle, et elle se met a jour tres rapidement par contre et c'est le plus fiable pour voir l avancé des DLs.

Si vraiment tu as des prbs et que tu vois un DL marque en cours sans la petite fenetre, le plus simple et d'arreter les DL, et de les reprendre,

Ici tu as la derniere version, avec entre autre l'actualisation en direct de la page des telechargements, mais uniquement tout les 10/20/30/../90 %
>> https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/lib/download.py

**Comment by canopre** [comment]
Hello
Merci pour la réponse ultra rapide.
En fait, en retournant naviguer dans mes menus de films de Kodi : la fenêtre de téléchargement a ré-apparu et m'indique à nouveau la progression.
Tout à donc l'air normal.
Je vais tester tout ca + en profondeur !
Encore merci.
