### ISSUE TITLE
Google video avec Poypi

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#246]
Fichier introuvable avec google video sur poypi.
Les films marchent nickel avec le site poypi sur pc.
C'est quoi le problème?

**Comment by TmpName** [comment]
Mit a jours sur beta.

**Comment by LordVenom** [comment]
bug toujour aprés ouverture de la popup de choix du stream le 1ere fonctionne le 2eme non

Print de la variable videos

NOTICE: [('https://lh3.googleusercontent.com/ze5PLO_jKvbdmVcHZ-K5yJz9M0tarHdjw-G4rRdnfw=m18', '268', '640'), ('https://lh3.googleusercontent.com/ze5PLO_jKvbdmVcHZ-K5yJz9M0tarHdjw-G4rRdnfw=m34","height":268,"width":640,"type":"application/x-shockwave-flash"},{"url":"https://lh3.googleusercontent.com/ze5PLO_jKvbdmVcHZ-K5yJz9M0tarHdjw-G4rRdnfw=m35","height":358,"width":854,"type":"application/x-shockwave-flash"},{"url":"https://lh3.googleusercontent.com/ze5PLO_jKvbdmVcHZ-K5yJz9M0tarHdjw-G4rRdnfw=m22', '536', '1280')]

Ya un truc qui vas pas, j'ai pas reusis a corriger dsl.

**Comment by LordVenom** [comment]
J'ai fini par reusir :)

**Comment by TmpName** [comment]
Mince, dsl, j'ai vu ton post apres.
J'ai rajouté une modif du coup la resolution affichée qui prennais height au lieu de width, now la resolution affichée dans la boite de dialogue est plus comprehensible.
