### ISSUE TITLE
Modifier le menu contextuel ?

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#247]
Bonjour,
Je voudrai modifier le menu contextuel pour ne conserver que le bouton "Téléchargement" : Pouvez-vous svp m'indiquer le fichier à modifier ?
J'ai déja essayé pas mal de combinaisons mais comme je suis une bille ca me prend un temps fou.
Merci d'avance pour le coup de main.

**Comment by TmpName** [comment]
De memoire tout est dans le fichier gui.py, mais ca assez bordelique, les liens ne se rajoutent pas en une seule fois.

**Comment by canopre** [comment]
Merci pour l'info : je vais regarder ca mais si TU me dis que c compliqué alors je vais m'arracher  mes derniers cheveux :)

**Comment by canopre** [comment]
Je vous tire mon chapeau les gars pour arriver à y comprendre quelque chose !
Qu'est ce que c'est compliqué comme code !
C'est quoi d'ailleurs comme langage ?
Si vous pouviez m'aider un tout petit peu : je voudrai seulement conserver le lien "Téléchargement" du menu contextuel ?

**Comment by TmpName** [comment]
C'est du python.
Certains sont assez faciles, assez explicites, dans la fonction addMovie met un '# devant les fonctions self.createContexMenuWatch, self.createContexMenuFav, .....
D'autres sont ailleurs, comme le telechargement (de memoire).

**Comment by canopre** [comment]
Merci bcp TmpName pour ton aide : je m'y met de suite !
