### ISSUE TITLE
Mise à jour automatique des sources ?

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#250]
Bonjour,
Encore une petite question : Les sources se mettent-elles à jours automatiquement ou faut-il obligatoirement passer par le menu de configuration + "Mise à jour des Sources" ?
Merci pour votre aide.

**Comment by TmpName** [comment]
En fait c'est juste au cas ou il y est une source qui change radicalement, pour eviter d'avoir a attendre 20jours pour qu'elle refonctionne.
Pour eviter les demandes trop lourde/repetitive pour le serveur, la manipulation est volontairement complexe a effectuer.
Si tout se passe bien pour toi, tu peux eviter de mettre a jour, sinon non la mise a jour n'est pas automatique, pour la meme raison que precedement.

**Comment by canopre** [comment]
Merci pour ta réponse.
Pourquoi ce délai de 20 jours ? c'est la période de mise à jour de l'addon ?

**Comment by LordVenom** [comment]
Le delai et de 48h avant chaque nouvelle requette.

**Comment by bsouhdz** [comment]
bizarrement la source ne marche pas sur mon démodulateur Prismcube Ruby sur
xbmc Gothzn?

Souhila B

2015-11-02 8:28 GMT+01:00 Lord Venom <notifications@github.com>:

**Comment by TmpName** [comment]
La source ?
