### ISSUE TITLE
Openload

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#251]
Le host Openload me donne erreur fichier introuvable sur toutes les sources.
Le film Mission impossible avec le host openload marche nickel sur PC avec le site http://official-film-illimité.fr/

**Comment by arzaz** [comment]
Une solution svp

**Comment by TmpName** [comment]
Lol, 5mn, on est pas a l'usine, y a plein d'autre hosts sur d'autres sites.
Sinon j'ai fait une mise a jour rapide sur le beta, a tester car si ca marche chez moi, ce n'est pas le meme lien que j'ai sur firefox.

**Comment by arzaz** [comment]
Désolé TmpName

Comme j'utilise souvent le site film illimité, qui malheureusement est limité par le nombre de host parfois seulement 01 host qui est openload

**Comment by arzaz** [comment]
Merci TmpName, la mise est jour est parfaite.

**Comment by LordVenom** [comment]
Bêtement je me suis demander combien de mission impossible l'addon trouver dans la recherche.
Je me suis limiter a rogue nation, y a 10 reponses et chaque une a plusieurs host. Bref j'en ai lancer 5 qualiter correcte en moin de 5min c'est quand même bien d'avoir autant de site.

Pour résumer ma penser, merci pour le raport de bug ça nous aide beaucoup, mais pas de up surtout si c'est pas une erreur qui fait tout planter.
