### ISSUE TITLE
download probleme

### ISSUE THREAD

**Issue by sdubois01** [LordVenom/venom-xbmc-addons#252]
salut ,   je me demande pourquoi , quand je download ,  j ai seulement   D:/  que je vois !!!!
y as tu une raison pour pas que je vois mes autres drive ..???

merci

**Comment by LordVenom** [comment]
Bonjour,

La fenêtre d'ouverture de fichier et une fonction propre a XBMC en gros on peux pas modifier ceux qui ce passe dedans.Mais logiquement tu doit pouvoir remonter a la racine.
