### ISSUE TITLE
Compatiblité avec Trakt

### ISSUE THREAD

**Issue by Sheppounet** [LordVenom/venom-xbmc-addons#254]
Bonjour,

Est-ce qu'il serait possible de rendre l'addon compatible avec l'addon de suivi Trakt (https://trakt.tv/). 

Normalement, l'addon de Trakt est capable de reconnaitre les sources en lignes, mais ca ne semble pas fonctionner avec VStream.
Je ne sais pas très bien ce qui lui manque. Des métadonnées peut être, ou le nom de ce qu'on lance qui ne lui convient pas... 
En tout cas, s'il est possible de faire quelque chose en ce sens, ça serait top !

**Comment by TmpName** [comment]
Quelqu'un a deja fait une demande de ce genre, et en fait il y a un probleme. Bon je peux me tromper vu que j'ai aucune idée de la maniere dont fonctionne les meta mais en fait contrairement a Genesis qui part des "metas" pour apres essayer de trouver un film qui y correspond Vstream lui part des fichiers et doit chercher a faire correspondre les metas, donc en fonctionnement normal pas de meta du tout vu qu'il n'y en a pas besoin pour afficher un film.

Trakt a besoin des "metas" pour fonctionner, c'est surement pour ca qu'il ne doit pas du tout etre compatible avec Vstream.
Venom est en train d'augmenter les "connexion" entre fichier et "meta" pour pouvoir afficher plus d'info, il y aura peut etre un moyen d'utiliser son nouveau code pour gerer Trakt en passant, mais honnettement je pense que a ce moment on trouvera d'autres possibilitées plus urgente.

Juste pour info, c'est quoi Trakt ?
C'est juste pour pouvoir afficher sur un site ou sa page facebook les film qu'on regarde ?

**Comment by Sheppounet** [comment]
Ca peut effectivement faire ça aussi, mais sa principale utilité, c'est le suivi de sa médiatèque perso. Ca marque ce qu'on a déjà vu, ce qu'on veut voir, etc... Et avec l'addon Trakt en fond, c'est automatique. On le fait marcher sur LibreTV donc c'est possible (mais on a les metas).

L'intérêt est limité pour les films, mais pour les séries, c'est très pratique pour suivre les épisodes qu'on a vu et ceux qu'on a pas encore vu.

Je code un peu le python, je pourrais jeter un oeil, dès que j'aurais trouvé par où démarrer dans ce code...

**Comment by bsouhdz** [comment]
MOI depuis que j passer a la derniere version pleins de bug


Souhila B

**Comment by LordVenom** [comment]
@bsouhdz , Ont vas pas avancer avec ce genre de messages , plus constructive la critique merci.

**Comment by bsouhdz** [comment]
la critique sur des erreurs fait avancées les choses SVP ces pas mon
attention loin de la ,merci.
bon courage

Souhila B

2015-11-24 11:13 GMT+01:00 Lord Venom <notifications@github.com>:

**Comment by LordVenom** [comment]
Et je suis le premier a remercier les rapport de bug, Mais comme je disais il faut plus d'info, que ça servent a remédier au problème un copier des erreur de ton log par exemple.

**Comment by LordVenom** [comment]
Je préfére http://www.betaseries.com/ qui est français au moins, le soucis reste que vStream ne sais pas dire quel épisode et en lecture. Donc ont pourrais faire un listing des films et séries vue mais un suivis des épisodes faut rajouter du code et des connections.
