### ISSUE TITLE
Film illimté

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#255]
Bonjour,
Merci de verifier svp le site Filmillimité.fr, car depuis hier je trouve des difficultés a visualiser des films.

**Comment by bsouhdz** [comment]
vous voulez dire  http://official-film-illimité.fr/
<http://xn--official-film-illimit-v5b.fr/>


Souhila B

2015-11-23 22:50 GMT+01:00 arzaz <notifications@github.com>:

**Comment by TmpName** [comment]
Je viens de tester, tu aurais un exemple stp ? Perso, je n'ai pas vu de probleme.

**Comment by arzaz** [comment]
Bonjour TmpName,

Tu as bien vu, le souci réside avec le host videomega et surtout le soir.

**Comment by TmpName** [comment]
Videomega corrigé sur beta.
