### ISSUE TITLE
apprendre à programmer

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#257]
bonjour
j'aimerais apprendre à contribuer à vstream.
en particulier, j'aimerais apprendre à ajouter de nlles sources ...

je ne connais pas python, mais j'ai fait pas mal de programmation en c ou c++

que me conseillez vous pour démarrer ?  utiliser vous seulement un éditeur de texte pour modifier les .py, ou bien utilisez vous un outil de programmation ? pour ajouter une source, de quel fichier partir ? "ajouter une source.py" de la beta semble plus récent ... à quoi sert le fichier default.py de la beta ?

merci pour vos conseils

**Comment by TmpName** [comment]
J'ai commencé avec un editeur de texte mais je suis vite passé a notepad ++ qui gere aussi entre autre les xml.
Plein d'options utiles, et ca prend rien en espace disque, et ca ne touche pas a la config systeme, que du bon (contrairement a l'ide Cpp ^^)

ajouter une source.py est le bon fichier pour debuter, tu peux aussi utiliser une sources deja fonctionnelle, mais en general les debutants laisse des bouts de code dedans car ils ne voyent pas si c'est utile ou pas et les resultats sont souvent anarchique. En partant du fichier ajouter une source.py, pas de probleme car le fichier est vide, mais plus de boulot.

Le fichier defaut.py si on parle du meme fait partie du coeur de Vstream, tres souvent appelle, je te deconseille d'y toucher si tu ne sais pas exactement ce que tu fais.

**Comment by chataigne73** [comment]
merci bcp pour ta réponse TmpName :-)
je crois que je vais me lancer

tu utilises quoi comme méthode de debug ? tu te génères des fichiers de logs ?

**Comment by TmpName** [comment]
J'utilise (mais me demande pas ou je l'ai trouvé) "XBMC log analyser" C'est buggué jusqu'a la moelle, ca freeze souvent, mais pratique.

En fait j'utilse ces 3 applis en meme temps, je change le fichier dans notepad++, je passe sous kodi, je clique, puis je passe sous le loggeur pour voir les resulats. Tres rapide.

**Comment by LordVenom** [comment]
Perso j'utilise aussi notepad++ mais j'ouvre direct le log xbmc avec.Pour les paterns utilise https://regex101.com/ ça aide pas mal.

**Comment by TmpName** [comment]
J'espere que ce n'est pas trop tard, mais j'ai commencé a mettre a jour le fichier "ajouter_une_source.py" > https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/ajouter_une_source.py

Si tu trouves une partie trop complexe, previent nous on adaptera cette page pour la rendre plus simple.

**Comment by chataigne73** [comment]
merci pour ça TmpName ....  pas eu trop le temps pour l'instant, mais je me lance cette semaine !

**Comment by chataigne73** [comment]
bon je me suis lancé :-)
le début se déroule bien, mais pour le moment je bloque sur l'utilisation des patterns
pour spatern est mauvais, et donc mon aresult est vide :-(

comment utilisez vous regex101 ???

**Comment by LordVenom** [comment]
1- tu te met en python dans le menu flavor
2- dans regular expression ce qui correspond a la patern dans vStream
3- la case ? tu tape gmis
4- Test string le code source que tu veut tester.

**Comment by chataigne73** [comment]
super merci !
donc maintenant tout fonctionne sur le site que je teste
sauf les hosters ... car ils sont sur plusieurs pages (1 page pour le 1er hosters, puis un lien vers une 2eme page html qui contient le lien vers le 2nd hoster, etc ...)
je sais pas si je m'exprime bien
mais je vais réussir à surmonter ça ... je vais regarder dans les sites existants s'il y a pas un exemple comme ça

**Comment by chataigne73** [comment]
bon,  je m'en suis servi ... grâce à vous !  merci :-)
juste un petit mystere que je capte pas encore concernant les paterns : pourquoi quand je passe de regex101 à mon .py je dois remplacer des .+? par des *, ou mettre des \ devant des /a par exemple ...

bref, ma 1ere source est presque fonctionnelle ... je pourrai bientot la pousser à tout le monde :-)

**Comment by TmpName** [comment]
C'est normal, en fait en passant par ce site il y a des options a activer pour avoir le meme comportement que dans Vstream (notamment pour les sauts de lignes. Vstream t'a indiqué "gmis").
Mais Vstream fait un traitement aux pages web si tu n'utilises pas les fonctions python pures, et egalement lors des parsing regex (regarde le fichier parser.py), c'est pour aider mais quand je galere trop, j'utilise direct les commandes python brutes..

Le '/' s'utilise comme en cpp c'est le caractere "échappatoire" (je sais pas comment on dit en francais) mais si tu veux le caractere '/' il te faut tjours le faire preceder de '\' d'ailleurs si tu ne le fait pas le site te previens avec un message d'erreur.

Par contre remplacer .+? par * la je vois pas pkoi .....

**Comment by LordVenom** [comment]
C'est ecrit sur https://regex101.com/ ( + = 1 ou plus) (* = 0 ou plus) le . etant un caracterer tu devrais en avoir 1 ou plus bizard que ça ne fonctionne pas.

**Comment by chataigne73** [comment]
Je vous donne un exemple: dans presque tous les fichiers .py de sites vous utilisez dans les patern des ' *' entre des balises div et href par exemple :sPattern = '<div class="moviefilm"> *<a href=".+?"> *<img 

Bon c'est pas bien grave c'est juste pour comprendre...

J'ai un pb plus embêtant: j'ai une source qui fait appel à du JavaScript (onclick) pour faire apparaître les liens des hosters (on trouve un lien hosters dans le code source de la page, on click dans la page web, et on voit apparaître un 2eme hosters dans le code source de la page, etc). Comment m'en sortir?

**Comment by LordVenom** [comment]
Le lien de la source pour nous faire une idée.

**Comment by chataigne73** [comment]
sokostream.biz

**Comment by TmpName** [comment]
Il te faut utiliser les requetes POST au lieu de GET avec comme parametre levideo=53333 par exemple a la meme url que la page principale.
Donc il te faut recuperer avec les regex le nom du host et la valeur de levideo et passer ca en POST.

Jete un oeuil au host netu.py il utilse aussi la requete POST.

' *' est assez souvent present dans les regex car il veut dire rien ou plusieurs espaces, et tres souvent le site rajoute un espace aleatoirement dans le code.

**Comment by chataigne73** [comment]
Merci j'ai réussi :-)

**Comment by Arthur-05guid** [comment]
bonjour  j’essaie d'apprendre la programmation mais je ne sais pas comment et je n'ai aucune base

**Comment by sizanic** [comment]
Bonjour @Arthur-05guid ,


Si tu veux faire tes premiers pas sur notre projet, je te conseille ce guide : 
https://github.com/Kodi-vStream/venom-xbmc-addons/wiki/Debugger-avec-Eclipse

Mais il faut avoir des bases que nous ne pourrons pas te donner.
