### ISSUE TITLE
Playlist contains no entries

### ISSUE THREAD

**Issue by bjrobert** [LordVenom/venom-xbmc-addons#260]
Hello, 
When I start Vstream I see no entries displayed (no sources nor categories).
Once in a while after multiple tries the list is displayed but most of the time it is empty.
Other video add-ons display a list of entries to be watched. However, if I launch Vstream first and the list is empty it will be empty too for all other add-ons I launch after. I need to restart Kodi to make other add-ons work properly again.
I'm using a minix neo 8 plus android box (kitkat 4.4.2) with kodi 14.2.
Thank you for explaining what is going wrong.
Regards.

**Comment by TmpName** [comment]
Hi.
I don't know exactly what is "sources" or "categories" in Vstream.
When you go in Vstream you have the home page, after you can select a categorie, then after you select a site, and inside it, un film then a 'source' ?

But I don't see what is the 'list' ?

**Comment by bjrobert** [comment]
Hello,
Thanks for your quick reply.
What I mean to say is that the home page is empty. There is nothing I can select. 
It seems the page is filled in the first place but almost immediately emptied. No matter how long I wait, it remains empty.
I hope I clarified a little bit.

**Comment by LordVenom** [comment]
Peux être un bug de language tester en Kodi en français pour voir si les titres s'affiche.
Sinon la ligne d'erreur de votre log peux nous aider.

**Comment by TmpName** [comment]
LordVenom is right, try to select French as language to try (Vstream is french content).
Try to give us a log with the last 20/30 lines on a pastebin link pls.

I realy don't understand how it can too broke the others addons. It's realy the fist time we have this bug.

**Comment by bjrobert** [comment]
Le langage selectionné dans Kodi est le français. Désolé d'avoir ouvert le blog en anglais au fait. 
Après avoir installé l'add-on "debug log uploader" et activé le debug dans kodi ce matin j'ai essayé de nouveau et miracle tout allait bien. J'ai désactivé le debug et relancé Kodi plusieurs fois et reessayé et chaque fois aucun problème. Je voudrais essayer ce soir encore avant de fermer le blog définitivement car à part l'installation de l'add-on et l'activation du debug je n'ai rien changé. Je n'explique donc pas la résolution du problème. Je vous tiens au courant...

**Comment by TmpName** [comment]
Lol, pas de soucis, c'est une bonne habitude.
Sinon pour le bug, ca m'interesse car assez violent pour aller jusqu'a faire deconner les autres addons.

**Comment by LordVenom** [comment]
Si vous passer par un repository genre super-repo ils ont tendance a mettre bien le bazard.

**Comment by bjrobert** [comment]
Je pense avoir trouvé l'origine du pb. J'habite á l'étranger et pour pouvoir regarder les chaines de France Télévision en direct je lance un vpn. Il semble que le problème se produit quand le vpn est activé.
Malheureusement il m'est impossible de m'envoyer le debug log car une fois que le pb arrive le debug log uploader ne répond plus et je ne peux même pas quitter Kodi de façon normale. Est-il possible que le vpn empêche la mise en page de vstream?

**Comment by TmpName** [comment]
Ben justement, la partie "home" ne demande aucune aucune connexion, sauf de temps en temps pour la verif des mises a jour/changelog, mais j'ai deja testé, a part un message d'erreur, cette page ne peut pas avoir de probleme pour s'afficher (enfin d'apres ce que j'ai vu, la realitée est autre).

Et pour le vpn a part un freeze complet de kodi je ne vois pas ce qu'il peut provoquer comme bug. Ton vpn est sur le systeme (tout ton ordi passe par le vpn, géré par android) ou propre a kodi (un addon) ?

**Comment by bjrobert** [comment]
Ce n’est pas un freeze complet. Seuls les video addons ne marchent plus et aussi donc la possibilité de quitter Kodi. Lá par contre qd j'appuie sur quitter j'ai un freeze. Le seul moyen de reutiliser kodi c'est de killer le proces. Qd le pb se produit je peux utiliser le pvr iptv simple client sans soucis. Ça touche donc seulement les addons video. Le vpn est en effet sur le minix. Je me connecte manuellement et toutes communications passent par le vpn. J'ai retesté et y à pas photos: qd la connexion vpn est active l'écran de vstream reste vide.

**Comment by bjrobert** [comment]
Correction: Le debug log uploader ne marche pas non plus qd le pb se produit.

**Comment by LordVenom** [comment]
Kodi fait un log mode debug activer ou pas.

<data/sdcard/Android>/data/org.xbmc.kodi/cache/temp/kodi.log
or /sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

**Comment by bjrobert** [comment]
Depuis ce matin vstream affiche la home page, vpn activé ou pas. Je pensais vraiment que c'était lié au vpn. Je n'y comprends plus rien. A moins que vous ayez fait une modif mais ça n'a pas l'air. J'essayais de produire des logs avec et sans freeze pour que vous puissiez les comparer mais je n'ai pas eu de freeze!?!? Si le problème se reproduit je vous en ferez part mais maintenant je vais pouvoir profiter de votre excellent travail et regarder des films grace à votre addon. Merci beaucoup. Si vous souhaitez qd même recevoir les logs faites le moi savoir.

**Comment by bjrobert** [comment]
Bonjour,
Le problème est revenu sans aucune explication.
Je vous fais part des logs avec et sans le vpn activé. 
Logs de kodi, vpn non activé et donc vstream fonctionnant correctement: http://xbmclogs.com/pn4z37npk
Logs de kodi, vpn activé et donc vstream ne fonctionnant pas: http://xbmclogs.com/pa4fpc5ub
Si vous pouviez trouver la raison du problème ça serait super.
Merci.

**Comment by TmpName** [comment]
Alors j'ai commencé a jeter un oeuil.
Tout est identique jusqu'au message d'erreur au sujet du md5 (pas important)
>>ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/resources/lib/about.py:9: DeprecationWarning: the md5 module is deprecated; use hashlib instead

et apres quand ca marche on a
>>NOTICE:  [PLUGIN] Vstream: call load methode

et quand ca ne marche pas
>>ERROR: CPythonInvoker(4, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vstream/default.py): script didn't stop in 5 seconds - let's kill it

**Comment by TmpName** [comment]
Essaye de remplacer ton fichier default.py par celui-ci, il ne va rien corriger mais va afficher des lignes en plus dans les logs pour pouvoir tracer le programme.

http://pastebin.com/XswXk4jU

**Comment by bjrobert** [comment]
Merci pour vos réaction rapides.
TmpName j'ai essayé ton default.py mais vstream ne se lance pas et le log signale un 'invalid syntax' dans default.py 93,16 'else:\n'
Ais-je fait qq chose qui cloche?

**Comment by TmpName** [comment]
Non c'est un prbleme de tabulation, le python est galere avec ca.
A la ligne 92, "oGui.updateDirectory()", rajoute des espaces jusqu'a l'avoir au meme niveau que la ligne 91 "oGui.openSettings()", ca doit etre 4 espaces (et surtout pas de tabulation)

**Comment by bjrobert** [comment]
Le fichier default.py est corrigé.
J'ai reproduit le problème espérant que les logs donnent plus d'infos.
Logs de kodi, vpn non activé et donc vstream fonctionnant correctement: http://xbmclogs.com/pia20nozm
Logs de kodi, vpn activé et donc vstream ne fonctionnant pas: http://xbmclogs.com/pfdypdknd
Merci.

**Comment by TmpName** [comment]
Et les autres addons fonctionnent ?
Car la je ne comprend pas, tu essaye de lancer le fichier defaut.py, mais tu n'arrives meme pas a executer la premiere commande.
Il y a un message d'erreur que je ne vois pas dans l'autre version pour le fichier tvguide.xml (smb protocole), mais je ne vois pas le rapport avec Vstream.

Si ce n'est pas le code ca vient des imports.
Tu as plein de lignes (toujours dans le meme fichier au debut)
>>#from resources.lib.statistic import cStatistic
#from resources.lib.gui.hoster import cHosterGui
#from resources.lib.gui.guiElement import cGuiElement
#from resources.lib.favourite import cFav
#from resources.lib.download import cDownload
#from resources.lib.about import cAbout
#from resources.lib.home import cHome
ect ...


Met un # devant toute les lignes, relance kodi, et relance Vstream, tu vas avoir un message d'erreur, c'est normal kodi a besoin de ces imports, mais pas de freeze, les autres addons doivent fonctionner (sans code ni import, c'est comme si tu avais un fichier vide).

Puis tu retires un '#' , et tu essayes de relancer Vstream (sans redemarrer, tant que le fichier n'a pas marché, il sera relu en integralite), tu vas avoir le meme resultat, et quand ca bloquera les autres addons par elimination tu aura trouvé l'import qui fout le bordel.

**Comment by bjrobert** [comment]
Ok. J'ai suivi tes consignes.
Le problème se produit lorsque la ligne suivante est exécutée:
from resources.lib.about import cAbout. la home page freeze. Les autres addons ne fonctionnent plus non plus.
Le log avec les erreurs est ici: http://xbmclogs.com/pqhei7fk1
Les logs après 21:55 sont apparus qd j'ai appuyé sur "quitter" et comme kodi ne reagissait pas j'ai forcé l'arrêt.

**Comment by TmpName** [comment]
Ok, bon ca avance, dsl des manips, mais vu que j'ai pas le bug ...
Effectivement il se passe pas mal de chose dans about.py

Un truc facile a tester. Toujours dans le fichier default.py, tu remet le '#' devant la ligne
>>#from resources.lib.about import cAbout

et tu rajoutes un # a la ligne 83
>>#cAbout()

Avec ca tu devrais acceder a la page home. Vu que tu ne charge plus du tout le fichier about.py

Si ca marche, les deux seules lignes qui peuvent etre bloque par le vpn sont
>>                self.__checkversion()
                    self.__checkupdate('false')

Tu peux mettre des # et reactiver le fichier about pour tester apres (en virant les deux '#' du fichier default.py) mais ca pourrait simplement dire que le site github.com bloque ton vpn mais normallement il y a un timeout (si pas de connection au bout de x seconde, message d'erreur et tout continu comme avant)

**Comment by bjrobert** [comment]
Bon, il plante dans about.py à la ligne 25     "self.__checkupdate('false')".
Je ne suis pas dispo avant le 28/12. Je continuerai mes investigations espérant pouvoir confirmer ou pas le fait que github.com bloque le vpn.
J'espère que cela ne vous ennuie pas que le blog reste ouvert tout ce temps.

**Comment by TmpName** [comment]
Non ca c'est pas un probleme, mais je vois pas trop pourquoi ca bloque, il y a le timeout et si il y a un probleme c'est non bloquant (try/except).

Un fichier 'about.py' bidouillé avec plus de ligne de debug pour tracage via log.

> http://pastebin.com/BmriqTfV

**Comment by bjrobert** [comment]
Bonsoir,

Bonne année 2016 à vous.

Le problème ne se produit plus avec les lignes suivantes présentes dans ton dernier fichier debug about.py que le vpn soit actif ou non.
#sUrl = 'https://api.github.com/repos/LordVenom/venom-xbmc-addons/commits/master'
sUrl = 'https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons/master/updates.xml.md5'
Si je reactive la première ligne le problème se reproduit quand le vpn est activé.
On peut donc conclure que cela vient de github.
Qu'en pensez vous?

**Comment by TmpName** [comment]
Mes dernieres modifs ne changent rien, la ligne avec '#' y est d'origine.
Elle rajoute juste des lignes avec des chiffres dans le fichier log, pour savoir ou ca bloque.
Donc normallement ca devrait bloquer aussi.

En fait dans les log si tu vois ecris "0" puis pas de "1" ca voudra dire que ca bloque entre ces 2 lignes.

**Comment by bjrobert** [comment]
Ok TmpName. J'ai installé la version 0.3.7. Le problème est maintenant résolu.
J'avais la version 0.3.6 et il semble que la version de about.py que j'avais était celle de 0.3.4 puisque la ligne 163 commençait par sUrl='https://api.github.com... J'ai du faire une mauvaise manip. 
Si le vpn est activé alors vstream plante. Je ne comprends toujours pas pourquoi mais je capitule.
Dans la version contenant les lignes de trace cette ligne était désactivée et à la place c'était sUrl='https://raw.githubusercontent.com... comme dans la version 0.3.7. 
Avec la dernièe version Vstream marche vpn activé ou pas.
Merci de ton aide et de ta patience. Je ferme le blog
