### ISSUE TITLE
streamingk

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons#261]
juste pour vous signaler que le regex recupere les filmographies d acteur qui n aboutissent a rien ...
Merci pour votre boulot Lord Venom et TmpName vous etes des bons ;) vraiment bon

**Comment by TmpName** [comment]
Ha oui, merci, je crois que je vais simplement filtrer ces resultats plutot que les rendre fonctionnel, je pense pas qu'ils soient utiles.
