### ISSUE TITLE
Full-streamvk

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#262]
Bonjour,

Merci de verifier le site w ww.full-streamvk.com, car il n'affiche qu'un seul film par page?
Sur pc, le site est devenu ww w.full-streamvk.net (.net au lieu de .com)

**Comment by TmpName** [comment]
Nickel, merci. C'est impressionant les bugs que tu trouves, franchement sur la quantitée de sources, moi je vois presque plus rien.
M'en occupe de suite, en plus Venom fait trainer la mise a jour pour ce mois, du coup ce sera nickel.

**Comment by LordVenom** [comment]
Avec toutes les modifs faite je fait un max de test mais la mise a jour vas pas tarder.Mercredi je pense.

**Comment by arzaz** [comment]
Je ne sais pas si le site lestream.net est en maintenance ou autre, mais rien ne s'affiche depuis hier.

**Comment by TmpName** [comment]
Modifs finie, par contre pour lestream leur site a l'air en congé pour le moment.

**Comment by bsouhdz** [comment]
vous voulez dire http://www.le-streaming.com/


Souhila B

2015-12-06 12:54 GMT+01:00 TmpName <notifications@github.com>:

**Comment by TmpName** [comment]
Ha tiens, il a chnagé de nom de domaine celui la ?
