### ISSUE TITLE
Dependances vstream

### ISSUE THREAD

**Issue by RachidZidouh** [LordVenom/venom-xbmc-addons#263]
Bonjour,

Je tente d'installer la dernière version 3.0.6 sur une vu+ solo2 avec blackhole v3x.
Lorsque je lance l'installation j'ai un message qui me dit que l'appli est incompatible ou bien qu'une dépendance est manquante. Existe t-il une liste de toutes les dépendances nécessaires au bon fonctionnement?
Je n'arrive pas à trouver ce qui cloche, pourriez-vous me donner un peu de support svp?
Merci beaucoup

**Comment by TmpName** [comment]
Alors Vstream n'est as compatible sur tout les support, pour le tiens moi je ne peux pas te dire.
Tu n'aurais pas plus d'infos sur le message d'erreur ? Sinon tu trouveras les dependances dans le fichier addons.xml

>>	<import addon="script.module.metahandler" version="1.0.2"/>
	<import addon="xbmc.python" version="2.1.0"/>
	<import addon="script.common.plugin.cache" version="0.9.1"/>
	<import addon="script.module.parsedom" version="0.9.1"/>
	<import addon="plugin.video.youtube" version="2.9.2"/>
	<import addon="script.module.simplejson" version="2.0.10"/>
	<import addon="script.module.urlresolver" optional="true"/>
 <extension point="xbmc.python.pluginsource" library="default.py">
  <extension point="xbmc.addon.metadata">

**Comment by LordVenom** [comment]
Ou dans le post juste en dessous

https://github.com/LordVenom/venom-xbmc-addons/issues/38

**Comment by RachidZidouh** [comment]
Merci à vous deux pour vos retour, étant donné que je ne suis pas une flèche en info comment puis je installer les dependances manquantes svp?

Merci encore

**Comment by TmpName** [comment]
Ca va dependre des manquantes, la plupart sont dans kodi de base (selon les versions de kodi), deja rien que ca je crois que Vstream a des soucis sur des vielles version de kodi.

Ensuite suffit d'aller dans option/extention/rechercher, taper le nom et l'installer sinon plus sur, google avec le nom complet de l'addon et telecharger le zip et "installer depuis le zip", mais j'ai peur pour ta version de kodi car personnellement toute les dependances se sont installé toutes seules chez moi.

**Comment by RachidZidouh** [comment]
J'ai un peu avancé sur le sujet.
Je n'ai plus de problème de dépendances, mais maintenant lorsque je lance le telechargement du plugin via superrepo Helix le telechargement se bloque a 95 ou 97%. L'installation manuelle du plugin 3.0.6 et meme ceux d'avant ne se font pas, je les lance mais rien ne se passe. Ma version de XBMC est Gotham (seule version tournant sur une enigma blackhole v3 sur une VU+ Solo2)
Je sais plus trop quoi faire la :)

**Comment by TmpName** [comment]
Telecharge ce zip >> https://github.com/LordVenom/venom-xbmc-addons/archive/master.zip

Puis dans kodi installe en passant par "instal from zip".

Il y a un user "Arzaz" qui le fait fonctionner sous Prismcube ruby avec Gotham 13.2

**Comment by RachidZidouh** [comment]
Merci pour le lien

mais malheureusement il ne passe pas, "structure de fichier incorrect..."

**Comment by TmpName** [comment]
Ha ?
Jete un oeuil sur cette video, ca a un peu changé depuis mais ca devrait t aider >> https://www.youtube.com/watch?v=XeACz8uMoxQ

**Comment by RachidZidouh** [comment]
hello

oui je connais le lien, mais peu importe la version du addon que je telecharge quand je le lance rien ne se passe, et quand je passe par le repo de vstream ou helix le telechargement se lance mais se fige a 97 ou 99% et ne va pas plus loin.

Je n'y comprend rien

**Comment by RachidZidouh** [comment]
Le fichier de debug quand je lance le telechargement si qq1 le comprend.

http://redirect.superrepo.org/v7/addons/plugin.video.vstream/plugin.video.vstream-0.3.6.zip.md5
19:37:42 T:1971404800    INFO: easy_aquire - Created session to http://redirect.superrepo.org
19:37:42 T:1580909712  NOTICE: Thread FileCache start, auto delete: false
19:37:42 T:1580909712    INFO: CFileCache::Process - Hit eof.
19:37:42 T:1580909712   DEBUG: Thread FileCache 1580909712 terminating
19:37:42 T:1971404800   DEBUG: ------ Window Deinit (DialogAddonInfo.xml) ------
19:37:43 T:1640002704   DEBUG: FileManager: copy http://redirect.superrepo.org/v7/addons/plugin.video.vstream/plugin.video.vstream-0.3.6.zip -> special://home/addons/packages/plugin.video.vstream-0.3.6.zip
19:37:43 T:1640002704   DEBUG: CurlFile::Open(0x74e65a58) http://redirect.superrepo.org/v7/addons/plugin.video.vstream/plugin.video.vstream-0.3.6.zip
19:38:02 T:1640002704   DEBUG: GetZipList - Processing zip://special%3a%2f%2fhome%2faddons%2fpackages%2fplugin.video.vstream-0.3.6.zip/
19:38:12 T:1718613136   DEBUG: Thread JobWorker 1718613136 terminating (autodelete)
19:38:12 T:1657083024   DEBUG: Thread JobWorker 1657083024 terminating (autodelete)
19:38:13 T:1971404800   DEBUG: SECTION:UnloadDelayed(DLL: special://xbmcbin/system/ImageLib-mips.so)
19:38:13 T:1971404800   DEBUG: Unloading: ImageLib-mips.so
19:38:32 T:1971404800    INFO: CheckIdle - Closing session to http://redirect.superrepo.org (easy=0x236a098, multi=0x1c1aed0)
19:39:00 T:1701835920   DEBUG: ### [Qlock] - Delaying 240 secs
19:41:02 T:1971404800   DEBUG: CAnnouncementManager - Announcement: OnScreensaverActivated from xbmc
19:41:02 T:1971404800   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverActivated
19:41:02 T:1971404800   DEBUG: ------ Window Init () ------
19:41:02 T:1971404800   DEBUG: Alloc resources: 0.02ms  (0.02 ms skin load)
19:41:02 T:1727001744   DEBUG: service.libraryautoupdate-0.9.4 : screen saver on

**Comment by LordVenom** [comment]
Je comprend juste que tu as pourris toute ton installation avec superrepo à ne jamais installer c'est coder avec les pieds.Tu as tenter de deziper et le mettre directement dans le dossier addon de kodi ?

**Comment by RachidZidouh** [comment]
Hello,

Bon je viens de tester en dé-zippant et tout fonctionne parfaitement désormais, je te remercie pour ton aide.
C'était aussi simple que ca, j'aurai pu y penser avant quand même...!
