### ISSUE TITLE
Erreur de connection avec film illimité

### ISSUE THREAD

**Issue by drachub** [LordVenom/venom-xbmc-addons#265]
Merci pour la version béta qui corrige POYPI mais maintenant il y a un problème de connexion avec film illimité.

**Comment by LordVenom** [comment]
Merci pour le rapport, Ils sont en maintenance ont verra si ça dure ou pas.

**Comment by arzaz** [comment]
Film illimité est de retour sur pc mais non pas sur vStream.

**Comment by LordVenom** [comment]
J'ai vue oui mais pour le moment je suis bloquer sur une redirection.

**Comment by chataigne73** [comment]
aie ... pas simple cette protection
peut-être en ajoutant un header pour dire qu'on accepte le javascript ?

**Comment by TmpName** [comment]
Pas compliqué c'est une protection comme celle de cloudflare, un code javascript qui crée un cookie.
Je suis deja dessus, mais le site me repond plus pour le moment.

**Comment by TmpName** [comment]
Edit: bon le code est fini mais pourrais pas tester ce soir, en fait si vous vous connectez sur le site avec le java active et les cookies desactivés, ca lance des requetes en boucles et me suis fait ban.

Du coup plus d'accés pour le moment.

**Comment by chataigne73** [comment]
tu veux qu'on teste ?

**Comment by TmpName** [comment]
Si vous voulez mais ca va etre un peu compliqué.

La premiere protection c'est bon, c'est basique.

Mais ils ont aussi rajouté une seconde protection (qui je pense va etre simplement rajoutée au coeur de Vstream) ils envoient la page zippée, ce qui fait que le code est illisible, ca le fait pour les 4/5 derniers films et meme si j'envois une requete refusant la compression.

Je vais mettre en ligne la version arangée, mais elle demande 2 fichiers pour fonctionner, le fichier site et le fichier sucury.py

Je ne garantis pas le fonctionnement car mon ordinateur est tres permissif, il vaut mieux attendre le test de LordVenom (son ordi est plus strict, plein de trucs fonctionnent chez moi mais pas chez lui).

Vu que la mise a jour est recente, on va surement fusionner les 2 fichiers pour le mois en cours pour permettre l'utilisation de cette source, simplement en la mettant a jour via les options de Vstream, car en l'etat actuel elle ne fonctionnera pas sans le fichier sucury, mais pour les vaillant rien ne vous empeche de modifier/creer les deux fichiers.

**Comment by arzaz** [comment]
Avec la nouvelle mise a jour beta, j'arrive a accéder au site, mais le problème reside avec les hosts "Allvid, Openload et Videomega" aucun d'eux ne marche?

**Comment by LordVenom** [comment]
Pas de soucis pour moi.

**Comment by arzaz** [comment]
Problème rencontré hier soir, mais aujourd'hui tout est ok

**Comment by TmpName** [comment]
J'ai eu des prbs aussi hier avec allvid, j'ai pas pu comparer avec le navigateur par contre pour savoir d'ou ca venait.

**Comment by TmpName** [comment]
Bon nouvelle version en ligne pour mise a jour auto, en 1 seul fichier.

Attention c'est une version speciale de depannage, ce n'est pas la meme que sur le beta.

**Comment by arzaz** [comment]
Un autre problème vient de réapparaitre avec le site. Il actuellement vide

**Comment by TmpName** [comment]
Leur site demenage vers une nouvelle adresse, ca risque de prendre quelques jours.

**Comment by arzaz** [comment]
Bonjour,

Voici la nouvelle adresse: http://official-film-illimite.net et le site est opérationnel sur PC.

**Comment by TmpName** [comment]
Mit a jour, pas contre a tester car apparement ils n'ont pas enocore remit la protection sucuri (qui rique de revenir plus tard).

**Comment by arzaz** [comment]
Le site est out, apparemment ils ont remis la protection sucuri.

**Comment by TmpName** [comment]
Remit a jour sur beta, et mise a jour auto.
