### ISSUE TITLE
proposition modif poypi

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#266]
salut

l'affichage de l'info "HD" ou non ne fonctionne plus dans poypi

dans le fichier site, je propose de modifier

NORMALPATTERN = '<span style="list-style-type:none;" >.+? href="\/rgc\/(.+?)">(.+?)<(?:font|\/a)'
en
NORMALPATTERN = '<span style="list-style-type:none;" >.+? href="\/rgc\/(.+?)">(.+?)<\/a>'

et
#6da9c9
en
#979797

et ça remarche

A+

**Comment by LordVenom** [comment]
C'est remplacer merci.
