### ISSUE TITLE
taille des fichiers

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#269]
salut
le dev d'1 autre plugin a eu l'idée de faire apparaître la taille des fichiers des hosters
je trouve que c'est une super idée, car pour moi la qualité est très importante, et la taille du fichier permet de se faire une bonne idée

ce dev a utilisé

req = urllib2.Request(url)
resp = urllib2.urlopen(req, timeout)
size = int(resp.headers['Content-Length'])
size = ' %.2f GB' % (float(size) / 1073741824)

perso j'ai essayé, et pas moyen de l'implémenter correctement

qu'en pensez vous ?

**Comment by TmpName** [comment]
C'est impossible a mettre en place, imagine pour des hosts comme youwatch ou exashare qui repondent parfois au bout de 30s, multiplie par le nombre de host sur certains sites.
Ca va ralentir l'ensemble de maniere hallucinante.

Je reconnais que la taille du fichier est la seule donnée fiable pour connaitre la qualitée, apres certains sites sont honnêtes et mettent HD quand c'est reellement de la bne qualitée.

Mais demander la taille au serveur, je trouve ca trop lourd.

**Comment by chataigne73** [comment]
Je comprends,...
Merci pour ta réponse TmpName ;-)

**Comment by TmpName** [comment]
Apres c'est juste mon avis, j'aime bien la rapidite, apres c'est comme avec google, j'arrive a faire le tri des resulats assez facillement en fonction des sites des hosts et de l'heure (apres 20h jamais youwatch).

Mais ca demande a Vstream de se connecter sur tout les hosts juste pour demander la taille, c'est pas dur, mais je suis sur de faire plus vite si tu m'affiches une liste de lien avec site et hosts.
