### ISSUE TITLE
recherche poypi KO

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#271]
la recherche dans la source POYPI est KO

voici une nlle pattern qui fonctionne 
  `SEARCHPATTERN = '<fieldset> *<div> *<b><a *href="\/rgc\/(.+?)" *>(.+?)<'`

**Comment by TmpName** [comment]
Nickel merci, je met a jour de suite.

**Comment by arzaz** [comment]
Meme problème avec Film -ilimité

**Comment by TmpName** [comment]
Moi je n'ai pas de prb, tu as bien le dernier fichier ? En mise a jour auto il y a une version qui date de 4 jours.
