### ISSUE TITLE
Bug Marquer vu/Non vu

### ISSUE THREAD

**Issue by jojotango** [LordVenom/venom-xbmc-addons#273]
Bonjour,

Tout d'abord un grand merci à tous ceux qui contribuent à Vstream,
perso je suis fan :)

Je rencontre un petit bug  depuis ma dernière mise à jour ( Vstream 0.3.7 et Kodi 15.2), impossible de marquer une vidéo comme vu ou non vu.
Je suis sous Archlinux et j'ai testé sur deux Pc différents, même problème.

Merci d'avance pour votre attention

Joffrey

**Comment by TmpName** [comment]
Je viens de tester, avec le menu et avec la touche "W", pas vu de probleme, ca viendrait pas des bases de données de kodi ?

Tu as essayé les trucs du genre "vider le cache" (et je sais plus quoi, si quelqu'un se souvient des manips .....), pas de message d'erreur ?

**Comment by jojotango** [comment]
J'ai même essayé de faire une nouvelle installation, en supprimant avant les fichiers de configurations, c'est toujours pareil. Je pense que ça vient de la nouvelle version de Kodi 15.2-2 car même avec la version 0.3.7 de Vstream le problème et toujours là.

En plus de ça je me suis aperçu que des parties du menu ou des vidéos (voir des séries complète) étaient marqués vu alors que je n'ai rien demandé. 

J'essaye actuellement de rétrogradé Kodi avec un paquet antérieur ça permettrais de voir si ça vient de Kodi mais pour l'instant je n'arrive pas à le lancer, je vous tiens au courant si il y a du changement.

**Comment by jojotango** [comment]
Bon je viens de tester sur Mint et Kodi 15.2 du PPA officiel ça fonctionne. C'est bizarre il n'y a que sur Arch que ça plante et mon HTPC est sous Arch ça craint :( .
Par contre désolé TmpName mais je ne vois pas de quel cache tu parles?

**Comment by TmpName** [comment]
En fait les films vu/non vu sont stockés dans une base de données sql, suite a certains bugs, elle se retrouve corrompue et il faut la remettre a zero.
Mais dans ce cas la, tu devrais voir un message d'erreur dans les logs.

**Comment by jojotango** [comment]
Merci,

<code>
22:20:30 T:140455488513792   ERROR: InputStream: Error opening, plugin://plugin.video.vstream/?site=cHosterGui&function=play&title=Madam+Secretary+-+%5BCOLOR+coral%5D+S02E02%5B%2FCOLOR%5D++%5BCOLOR+skyblue%5DEasyVid%5B%2FCOLOR%5D&sHosterIdentifier=easyvid&sTitle=Madam+Secretary+-+%5BCOLOR+coral%5D+S02E02%5B%2FCOLOR%5D++%5BCOLOR+skyblue%5DEasyVid%5B%2FCOLOR%5D&siteUrl=http%3A%2F%2Feasyvid.org%2Fembed-a1b3bcnnatx6-640x360.html&sFav=play&sMediaUrl=http%3A%2F%2Feasyvid.org%2Fembed-a1b3bcnnatx6-640x360.html&sCat=4&sId=cHosterGui&sFileName=Madam+Secretary+-+%5BCOLOR+coral%5D+S02E02%5B%2FCOLOR%5D+
</code>

**Comment by TmpName** [comment]
J'ai pas encore eu le temps de regarder, mais tu pourrais tester avec une film/serie qui aurait un nom d'un seul mot, sasn caracteres special ? (pas besoin de refaire passer un log)

**Comment by jojotango** [comment]
Une capture vos sûrement mieux qu'un long discours :) <a href="https://www.dropbox.com/s/oobbj2144wcrza8/kodi_marquer_vu.ogv?dl=0">voir ici</a>
En premier j'utilise le clique droit de la souris.
En deuxième la touche 'w'.

Pour les saisons déjà cochées ça ne vient pas de moi elles sont cochées même après une install toutes neuve.

Merci pour ton retour.

**Comment by TmpName** [comment]
Le fonctionnement de la touche 'W" est la meme chez moi.
Supprimer les anciennes bases devrait t'aider, mais me souvient plus comment faire, a la brutale il te suffit d'effacer le fichier 'MyVideosXX.db' dans \userdata\Database'.
Mais le probleme c'est que cela n'effacera que celle de la touche 'w', pour celle de vstream c'est dans la config de Vstream.

Toutefois, il y a bien un probleme et la aussi j'attend le retour de LordVenom, en fait Vstream utilise un vieux systeme de marquage qui est maintenant obsolete, en fait on se retrouve avec 2 bases de données differentes pour la meme chose, la touche 'W' utilise celle interne a kodi et Vstream la sienne, il faudrait supprimer la seconde car elles interferent l'une avec l'autre.

**Comment by TmpName** [comment]
J'ai regarde vite fait, il suffirait de remplacer tout le code existant juste par cette ligne 
>>Action(ToggleWatched)

**Comment by jojotango** [comment]
Salut @TmpName, supprimer les DB n'a rien changé.

J'ai regardé un peu dans les DB et dans MyVideosXX.db les tables trucmuche_view sont vides. Par contre dans vstream.db j'ai bien une table watched avec des choses dedans et si je ne me trompe pas dans le code la méthode insert_watched(meta) utilise bien la table watched.

Pour Action(ToggleWatched) tu parles du keymaps.xml ? 
Si tu as besoin que je teste plein de trucs hésite pas j'ai un PC sous Arch avec une installation de Kodi qui ne me sert pas, si ça clache tout je supprime tout est je recommence.

**Comment by LordVenom** [comment]
C'est quoi cette touche W ? chez moi w ajoute a la playlist.Y a pas de raccourcis pour marquer lu/non lu il faut passer par le menu context (clique droit ou C).

Je connais pas Action(ToggleWatched) mais oublie pas que vStream de base ne fonctionne pas avec les meta activer et donc pas de raccourcis pour marque lu ou non lu d'ou la creation d'une base de donner interne.

Pour vider le base de donner une désinstalation ne suffis pas.Merci de passer par les paramètre de l'addon / outils / clear cache addon.

**Comment by TmpName** [comment]
Par defaut la touche 'W' sert a chnager le tag vu/non vu
http://kodi.wiki/view/Keyboard_controls

Je n'ai pas les meta activé chez moi, et la touche 'W' marche tres bien, je refais des test pour verifier.

**Comment by LordVenom** [comment]
A ben pas chez moi lol ça me les foux dans la playlist comme quoi les raccourcis kodi c'est pas terrible.

**Comment by TmpName** [comment]
Lol, mais la commande Action(ToggleWatched) devrait marcher, je crois que c'est la meme que celle du menu contextuel de gauche (celui sur le panneau defilant)

En fait ca supprimerait tout le code gerant watched/not watched, (une base de donnée en moins), et eviterait les conflit.
Mais a tester, chez moi ca marcherait, mais chez toi ....

**Comment by LordVenom** [comment]
A tester oui.Mais je peux pas t'en dire plus dsl je ne sais pas non plus.

**Comment by TmpName** [comment]
Ok, je fais un fichier de test pour vous deux, si ca marche on part la dessus.
Donnez moi un peu de temps.

**Comment by TmpName** [comment]
Bon alors apres quelques tests, je suis arrivé a une conclusion, c'est vraiment le bordel ...

Le systeme interne a kodi ne marque pas les repertoires mais les fichiers, donc
1 - bordel sur certains site avec architecture speciale comme filmstreamingco (pas de repertoire principal)
2 - A chaque fois que vous essayez de mettre en vu un repertoire, il scanne tout son contenu, resulat parfois ca bloque, parfois ca lance un film (si film direct), parfois ca marche aussi.
3 - si tout le contenu est 'vu' le repertoire ne le sera pas (ben oui c'est pas un contenu fixe).

Donc pour le moment, je cherche pour le bug de @jojotango mais on reste sur la base interne a Vstream et meme si possible on bloque celle de Kodi.

**Comment by TmpName** [comment]
Bon toujours pas de news. Je sais comment bloquer les flag de Vstream, mais pas ceux de Kodi, tout a l'air géré en interne.
Il suffirait de supprimer directement l'info dans la base interne de kodi a chaque fois que l'user fait une manip sur le vu/non vu dans Vstream, c'est possible avec une commande cf http://forum.kodi.tv/showthread.php?tid=229951&highlight=watched+flag

Mais pour le moment quelqu'un aurait un utilitaire pour visualiser les fichier db de kodi plus puissant qu'un lecteur de texte ? Et sans avoir a se faire chier avec des lignes de commandes SQL.

**Comment by jojotango** [comment]
Il y a <a href="http://sqlitebrowser.org/">Sqlitebrowser</a> qui semble pas mal

**Comment by TmpName** [comment]
J'ai teste le premier (le second etant trop lourd pour ce que je voulais faire)  et c'est parfait, leger, portable et ca marche tres bien, il va finir dans ma caisse a outil celui-la.
Bon pour le moment j'ai pas trouvé ou kodi stocke ses infos vu/non vu, mais ca devrait aller, merci.

**Comment by jojotango** [comment]
Salut @TmpName , 
Excuse moi si je dis des conneries je débute en programmation et les Bd j'ai pas encore étudier ça.

On dirait que MyVideos93.db sert à stocker les infos de la bibliothèque de Kodi.
Par contre les methodes "insert_watched et del_watched" fonctionnent très bien car je retrouve bien dans la table watched de vstream.db "addon_id, title et site" quand je marque Vu/non Vu et ils sont bien effacés si je refais l'opération (Par contre je n'ai pas la petite <a href="https://fortawesome.github.io/Font-Awesome/icon/check/">icône<a>).

Pour ce qui est des autre vidéos (séries, ou films) qui sont signalé comme vu par cette petite icône, je ne les ai retrouvé dans aucunes Bd. Après c'est une supposition de newbie mais est ce que ça vaudrait pas le coup de chercher par là. Je n'ai pas trouvé la fonction qui ajoutait cette icône dans l'interface.

**Comment by TmpName** [comment]
En fait le probleme ne vient pas de Vstream mais de kodi.
Je peux mettre ce que je veux avec Vstream, le resultat va dependendre des tables de kodi.
Lance Vstream met une serie en favoris (avec la touche W) et tu va la retrouver dans la table "files" de la base MyVideos93.db de kodi.

D'ailleurs si tu effaces les entrees de cette table, le marquage via Vstream (sans passer par W) remarche chez toi ?

**Comment by jojotango** [comment]
Oui effectivement ça me l'ajoute dans la table "files", par contre même après suppression ça ne change rien.

**Comment by TmpName** [comment]
Meme en virant les entree de la table "files" de les marquer en vu/non vu ne marche pas en passant par le menu contextuel de Vstream ?

**Comment by jojotango** [comment]
Nan j'ai toujours messages d'erreur dans les logs:
<code>
setWatched
14:24:45 T:140280745416448  NOTICE: The Expanse - [COLOR coral]Saison 1[/COLOR]
14:24:50 T:140280745416448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: database is locked
                                            Traceback (most recent call last):
                                              File "/home/joffrey/.kodi/addons/plugin.video.vstream/default.py", line 142, in <module>
                                                main()
                                              File "/home/joffrey/.kodi/addons/plugin.video.vstream/default.py", line 31, in __init__
                                                self.parseUrl()
                                              File "/home/joffrey/.kodi/addons/plugin.video.vstream/default.py", line 55, in parseUrl
                                                if (isGui(sSiteName, sFunction) == True):
                                              File "/home/joffrey/.kodi/addons/plugin.video.vstream/default.py", line 117, in isGui
                                                exec "oGui."+ sFunction +"()"
                                              File "<string>", line 1, in <module>
                                              File "/home/joffrey/.kodi/addons/plugin.video.vstream/resources/lib/gui/gui.py", line 644, in setWatched
                                                cDb().insert_watched(meta)
                                              File "/home/joffrey/.kodi/addons/plugin.video.vstream/resources/lib/db.py", line 127, in insert_watched
                                                self.dbcur.execute(ex, (title,site))
                                            OperationalError: database is locked
                                            -->End of Python script error report<--
14:24:50 T:140281205946112  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
</code>

**Comment by TmpName** [comment]
Ca ce n'est pas les memes message d'erreur que avant ?
La ca indique que la database de Vstream est lockee, peut etre deja ouverte dans une autre application.

**Comment by jojotango** [comment]
Oui t'as raison elle était ouverte avec DB broswer

**Comment by TmpName** [comment]
??? encore mieux.
Et ce bug tu ne l as que en bidouillant la base interne a kodi ?

Edit: Tu supprimé l'entree de la base ou toute la table "files", je te dis ca car le message
>> ERROR: AddFile unable to addfile ()
>> ERROR: SQL: SQL error or missing database

Me laisse a penser que c'est la table complete que tu as viré.

**Comment by jojotango** [comment]
oui j'ai viré toute la table

**Comment by TmpName** [comment]
Arf, et kodi fonctionne encore ?? ^^
Tu as fais un backup ?, il faut juste supprimer la ligne ou tu fais tes essais, outout le contenu de la table mais surtout pas la table elle-meme. Si c'est bien fait en redemarrant kodi devrait en refaire une, vierge, donc ca devrait corriger le probleme (enfin j'espere, la j'ai plus trop d'idees)

**Comment by jojotango** [comment]
oui c'est ce que j'ai fais supprimer la Db et redemarrer Kodi ça m'a recréé un DB mais on revient au point de départ même en suppriment les entrée rien ne change

**Comment by TmpName** [comment]
Donc meme en ayant:
1 - une table "files" dans "MyVideos93.db" vierge
2 - une table "watched" dans Vstream vierge

Tu as toujours des icones 'v' qui apparaissent a des endroits et en passant par le menu "marquer vu/non vu" de Vstream rien ne se rajoute ou ne se supprime ?

**Comment by jojotango** [comment]
C'est ça j'ai toujours des icones "v" à des endroits, avec Vu/non Vu c'est bien ajouté à la table watched de vstream mais pas d'icone "v"

**Comment by TmpName** [comment]
La je vois pas, ou est ce que Kodi/Vstream va pecher les infos pour savoir si il doit mettre l'icone ou pas ?
Tu as les metas activés ?

**Comment by jojotango** [comment]
Les paramètres sont par défaut donc je pense que oui, j'ai pas vu dans les paramètres Activer/Désactiver les métadonnées

**Comment by jojotango** [comment]
Bonjour @TmpName .

Est ce que tu as des news pour le bug. Je comprend bien que c'est un projet open-source et que vous faites ça sur votre temps libre donc je veux surtout pas que vous pensiez que je mets la pression.
Veux tu que je parle du problème à la communauté ArchLinux?
- Peut être qu'il y a une libraire différente entre Kodi Arch et les autres distribs?
- Un problème de dépendance?

**Comment by TmpName** [comment]
En fait, je ne vois pas comment kodi pourrait marquer un lien comme vu, avec toute les bases de donnees a zeros.

Le probleme c'est que si ca ne le fait que avec Vstream, c'est que le bug vient de chez nous donc les autres communautes ne vont pas pouvoir trop t'aider.

Une difference de librairie ou dependance, je ne pense pas car kodi utilise ses bases et Vstream les siennes, si les deux sont a zero je ne vois pas qui decide de marquer le lien en "vu".

LordVenom vient de revenir, peut etre que lui aura une idée ou une bidouille a tester, mais moi je tape en touche.

Les metas de Vstream sont dans le premier onlglet "general" des parametres de Vstream. Par defaut a off.

**Comment by jojotango** [comment]
Ok merci, pour info je viens de tester avec genesis et il y a pratiquement le même bug, tout est marqué comme vu et impossible de changer quoi que ce soit. Je continue à fouiner de mon côté.

**Comment by TmpName** [comment]
Ok alors la ca ma rassure, ca vient peut etre donc de ta version, et ca vaudrait le coup de voir avec la com ArchLinux, ca te fait un argument pour justifier que le probleme vient peut etre de leur cote.

**Comment by LordVenom** [comment]
Rien a ajouter vous avez fait toutes les recherches, je dit comme @TmpName  voir l'installation d'xbmc.

**Comment by benjarobin** [comment]
Bonjour, j'ai trouvé ce qui déclenche le bug, mais pour faire court, le bug n'est pas dans ce plugin. On dirait bien un bug dans Kodi, ce qui est bizarre c'est qu'il ne peut pas être reproduit chez tout le monde pour une même version...

Si on supprime la ligne `self.__aItemValues['Title'] = self.getTitle()` https://github.com/LordVenom/venom-xbmc-addons/blob/master/plugin.video.vstream/resources/lib/gui/guiElement.py#L359 alors le bug n'est plus reproduisible
Par contre on n'a bien sûr plus le titre quand on demande plus d'information sur un film

**Comment by TmpName** [comment]
Ha ??
Comment tu as decouvert ca ?
Juste pour info tu pourrais tester
>>self.__aItemValues['Title']='Spiderman'

et
>>tmp = self.getTitle()

Pour savoir de quel cote de la ligne ca deconne stp.

**Comment by jojotango** [comment]
Merci @benjarobin effectivement ça bloque le bug

**Comment by benjarobin** [comment]
@TmpName Comment j'ai découvert cela : Un peu de chance, un peu de rigueur et un peu d'analyse :-)
Dans la fonction `createListItem()`, j'avais remplacé la ligne `oListItem.setInfo(...)` par `oListItem.setInfo('video', { 'playcount` : 1})` et là cela fonctionnait bien, puis j'ai creusé un peu plus...

**Comment by TmpName** [comment]
Mais ca reste encore obscur pour moi, meme si kodi compare le nom avec quelque chose pour voir si il est vu ou pas, avec quoi ?????

Ou alors c'est justement la requete sql qui deconne et qui retourne toujours positif.

**Comment by benjarobin** [comment]
Non, aucun souci avec la requête SQL, il suffit de jouer avec playcount (en matchant sur un titre particulier) sans tenir compte de la requête SQL. Le bug est très certainement dans kodi, mais pourquoi ??? Désolé je n'ai pas le temps de regarder, je n'utilise même pas ce plugin

**Comment by TmpName** [comment]
Y a pas de soucis, je ne peux rien y faire non plus, c'est juste par curiosite. Ca m'a l'air quand meme assez flagrant comme bug pour que d'autres bossent deja dessus.

**Comment by jojotango** [comment]
Après ça coûte rien de le signalé à la team Kodi. Je veux bien le faire mais mes explications risques de ne pas être très claire.

**Comment by jojotango** [comment]
Problème résolu depuis la mise à jour de Kodi 16.0

**Comment by TmpName** [comment]
Lol, j'avais completement zappé cette histoire, en tout cas bne nouvelle.
