### ISSUE TITLE
peu de résulta de recherche sous windows 8.1

### ISSUE THREAD

**Issue by deadsoul69** [LordVenom/venom-xbmc-addons#274]
Je viens d'installer Kody Isengard sur un ordinateur sous windows 8.1, et lorsque j’effectue une recherche pour une série, je n'ai que très peu de résulta, alors que la même recherche sur un autre ordinateur sous windows 7 m'en donne 3 x plus, et même chose sur mon raspberry pi  sous open électric. Est ce qu'il y a une solution?

**Comment by TmpName** [comment]
Ha ? tiens c'est rigolo ca, tu pourrais faire un screen de la meme recherche sur 2 systemes differents (une vielle serie si possible). Tu as essayé d'aller directement sur le site qui ne donne pas de resultats avec un navigateur pour voir si ce n'est pas une histoire d'ip bloquée.

**Comment by deadsoul69** [comment]
Ah non ça je n'ai pas essayer, je vais essayer sa au retour du boulot et je vais essayer de sortir les screen par la même occasion... Je me doute que sa vient plus de windows que de vstream, 8,1 étant dans la même ligné que windows 10 coté validation et vérification des page web visité...

**Comment by deadsoul69** [comment]
Effectivement sa venait de la machine et non de l'application, désolé du dérangement.
J'ai ajouter les site ou vstream fait ces recherche au liste blanche de l'antivirus et autre anti- adware et tout est rentré a la normal... Merci de la piste, et en espérant que sa aide quelqu'un d'autre...
