### ISSUE TITLE
limiter résultats de recherche

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#276]
Bjr

même si je sais que TmpName n'y est pas favorable, j'aimerais vraiment pouvoir limiter le nb de résultats de recherche pour chaque site.

je vais donc faire le codage moi-même : TmpName, comment t'y prendrais tu ?  perso je ne vois pas d'autre solution que de faire des modifs dans chaque fonction showmovies de chage fichier de site .py

**Comment by TmpName** [comment]
Yep, pas d'autres solutions, chaques fichiers site a sa propre partie dans showmovies.
Mais avant de te lancer la dedans, regarde comment le dev de genesisfr galere pour ca, et regarde ce que cela va t'apporter,

Comment vas tu filtrer une recherche sur un film/serie de 1 ou 2 lettres ?
Beacoup de bon resultats vont se retrouver filtres dans tout les cas.
Comment vas tu gerer les fautes de frappes ?

**Comment by TmpName** [comment]
Si ca tinteresses j'ai diminué le nombre de faux resultats sur fullstreamorg
>> https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/full_stream_org.py

Une simple option oubliée dans les options de recherches.....
