### ISSUE TITLE
Ok.ru KO

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#277]
Salut
Ok.ru est visiblement KO :-(

**Comment by TmpName** [comment]
Meme le derniere version du beta ?
J'ai fais une mise a jour il y a 6 jours
>> https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/hosters/ok_ru.py

**Comment by chataigne73** [comment]
j'avais pas vu, ca marche avec ta maj
tes un chef !

**Comment by TmpName** [comment]
Desolé mais en fait la mise a jour ne marche que pour les sites, pour les hosts, faut attendre le mois d'apres, ou faire les bidouilles soit-meme.
