### ISSUE TITLE
Kodi sur le nouveau vu+ solo 4k

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#278]
Marusys a présenté au salon ANGACOM à Cologne son nouveau décodeur VU+ SOLO 4K pour la réception de chaînes Ultra HD.

Le VU+ Solo 4K est livré avec un double tuner 4K fixe DVB-S2 et un double tuner détachable (S2 / C / T / T2). 

Le récepteur prend en charge la nouvelle technologie de compression HEVC / H.265, il est donc compatible avec la réception de chaînes diffusées en 4K Ultra HD. La résolution d'image maximale est de 3840 x 2160 pixels.

Broadcom BCM7251 processeur Cœur est le nouveau chipset. C est un processeur ARM dual core 10k DMIPS avec une vitesse de 1500 MHz. A cela s ajoute 2 Go de RAM et 4 Go de mémoire Flash .

Le nouveau combiné est alimenté par une version modifiée Linux Enigma 2 et ,selon certaines  les versions Android de XBMC / Kodi.

Côté connectique, on a un port HDMI (version 2.0), deux ports USB 3.0 et un 2.0, une sortie audio numérique optique S / PDIF, Ethernet (Gigabit), RS-232 (dans une f
![image](https://cloud.githubusercontent.com/assets/11494048/11903065/ba46e620-a5b6-11e5-891f-43cf84a05047.png)
orme inhabituelle) et l'alimentation (12V 5.0A ) . Il est possible d'installer un disque dur amovible SATA 2,5 pouces.

![image](https://cloud.githubusercontent.com/assets/11494048/11903160/8fbd3688-a5b7-11e5-9f01-61af09d535a1.png)

![image](https://cloud.githubusercontent.com/assets/11494048/11903170/9f4ab4c2-a5b7-11e5-8193-7086c4cb64f3.png)

![image](https://cloud.githubusercontent.com/assets/11494048/11903050/a4c5796a-a5b6-11e5-8127-1d1c9152514b.png)

![image](https://cloud.githubusercontent.com/assets/11494048/11903190/ae75340e-a5b7-11e5-9570-15f79eeb5bdd.png)

**Comment by TmpName** [comment]
Et tu regarde la TV sur l'ecran en facade ?

ok, je sors ....

**Comment by mino60** [comment]
Il existe quelques sites web qui diffusent gratuitement du contenu 4K, pour le plus grand plaisir des yeux.

On y trouve ainsi des films d’action, de science-fiction, des documentaires, des comédies, des thrillers…le tout en qualité d’image et de son irréprochables.  Il faut toutefois préciser que l’ultra HD nécessite au minimum, une connexion de 16 Mbits/s. Une vitesse inférieure  diminuera la qualité de l’image.

Voici à présent, les sites web proposant des films en streaming 4K  :

Streamiz4K
Lien: http://streamiz4k.net/tags/streaming4k/

Full-StreamvK
Lien: http://www.full-streamvk.com/tags/Streaming+4k/

Streaming-4k
Lien: http://streaming-4k.net/

**Comment by LordVenom** [comment]
Du 4K en stream quel rigolade deja que du vrais 1080 en stream local c'est pas top alors ça.

**Comment by TmpName** [comment]
Moi la ou j'habite, j'ai du 4k en streamant en 3g via mon tel.

(ok, vais prendre mes pillules)
