### ISSUE TITLE
Problème manga city

### ISSUE THREAD

**Issue by lmarjot** [LordVenom/venom-xbmc-addons#279]
Bonsoir,

Tout d'abord félicitation pour votre addon.
Alors voila, ce qui m’amène ici est un problème avec mangacity. Depuis quelques temps lorsque je fait une recherche sur un anime que je regardais, la recherche ne trouve plus rien. Et lorsque je passe par anime, sources, mangacity, je le retrouve bien mais lorsque je clique sur un épisode la liste des vidéo est vide.

**Comment by TmpName** [comment]
J'ai mis la source a jour.
Tu peux la trouver ici > https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/mangacity_org.py
Ou en passant par la mise a jour automatique.

Si ton anime n'apparait tjours pas, donne moi le nom stp.

**Comment by lmarjot** [comment]
J'ai désinstallé et réinstallé vstream depuis le vStream Repository mais ça ne fonctionne toujours pas. Sinon l'anime c'est hunter x hunter mais j'ai l'impression que ça le fait pour tout les anime, j'en ai testé d'autres et même résultat.

**Comment by TmpName** [comment]
Ca ne marchera pas par le repository, la modif n'est pas encore officielle.
Soit tu remplaces uniquement le fichier, soit tu passes par la mise a jour auto.
Chez moi la recherche a marché, j'ai testé la version 2011, la version phantom rouge et une autre, les sources se sont affichées, j'ai pas testé si les liens etaient mort ou pas par contre.

**Comment by lmarjot** [comment]
Ok, je vois pas ce que tu appel la mise à jour auto, quand je vais sur les "paramètre" de l'addon mise à jour est grisé, sinon je veux bien remplacer le fichier mais je ne sais pas dans quel répertoire il se situe, j'ai une installe OSMC sur raspberry.

**Comment by lmarjot** [comment]
C'est bon j'ai fini par trouver le répertoire ou sont les sources, j'ai remplacer le fichier et ça fonctionne, merci !

**Comment by TmpName** [comment]
En fait (bon ok, j’avoue, c'est bien cache) dans les options de Vstream (tu peux avoir ce menu avec la touche 'c' dans Vstream), tu as plusieurs onglets ( recherche/acceuil/ect ..) et le dernier s'apelle 'outil', dedans tu as une option pour faire une mise a jour mais uniquement sur les fichier sites.
