### ISSUE TITLE
PROBLEME TV STREAMING

### ISSUE THREAD

**Issue by domtom25** [LordVenom/venom-xbmc-addons#280]
bonsoir probleme tv streaming quand je vais sur leur site il s affiche 

SORRY!
If you are the owner of this website, please contact your hosting provider: webmaster@tv-streaming.ch
It is possible you have reached this page because:

si c es possible de voir le probleme merci a vous et votre addon

**Comment by TmpName** [comment]
Le site est HS, a voir si ca dure ou si c'est provisoire.

**Comment by domtom25** [comment]
merci tout remarche bonne fetes fin d annee 
addon vstream continu longtemps merci a tous
