### ISSUE TITLE
Tuning regex

### ISSUE THREAD

**Issue by ced-a** [LordVenom/venom-xbmc-addons#281]
Bonjour 

Tout d abord, félicitation pour votre superbe plugins.

Le code de vos recherches peut être amélioré.
Remplacer
  sPattern = '\<li>\<a href="([^<]+)">.+?\<span class="bold">(.+?)\</span></p>'
par
   sPattern = '\<li>\<a href="([^\"]+)">.+?\<span class="bold">([^<]+?)\</span></p>'

Explication: 
1. Attraper tout ce qui n'est pas des guillemets "
2. Attraper tout ce qui n'est pas des <

Le code html étant très libre vous pouvez avoir des chaines du style
\<a href="toto" qqch="titi">
==>
Les regex tel que vous les avez ecrit recupérera
toto" qqch="titi

Même chose, 

title=".+?" href="(.+?)">(.+?)<
==>
title=".+?" href="([^\"]+?)">([^"]+?)<

De manière général, 
"(.+?)" ==>  "([^\"]+?)"

Bonne continuations

**Comment by TmpName** [comment]
Merci.
Ca me fait penser qu'il faudrait qu'on rajoute un tuto de 10 lignes sur les regex dans le fichier pour creer des sources.
