### ISSUE TITLE
faire une mise a jour certain site

### ISSUE THREAD

**Issue by domtom25** [LordVenom/venom-xbmc-addons#282]
salut

pour vous gagne du temps j ai verifier tout les sites sur votre addon 

j ai remarquer 

streamzzz.com les sources sont vides pour les series

regarder.films   les sources sont videsfrenchstream.com series et animes les sources sont vides

merci a vous vous faites du bon boulot longue vie

**Comment by TmpName** [comment]
Merci, la ca fait beacoup, y a vraiment des sites qui sont plus visitées que d'autres.
M'en occupe dans le week end.

**Comment by TmpName** [comment]
Bon les deux premiers c'est fini, le codage des serie/episode apparaitra a la prochaine mise a jour mais tout devrait fonctionner. (mise a jour de exashare et allvid pour ces 2 sites d'ailleurs)
Pour le troisieme ca fonctionne mieux mais pour le moment les lecteurs pour les series sont HS sur leur site.
