### ISSUE TITLE
Bonjour j'arrive pas a ajouté une source dans le plugin

### ISSUE THREAD

**Issue by patoche2025** [LordVenom/venom-xbmc-addons#283]
Bonjour tout d'abord good job pour le plugin.

J'ai vue qu'il avait moyen d'ajouté des source par nous même j'ai essayé de le faire mais quand je fais une recherche il m'a fiche pas le nouveau site qui sokrostream.biz puis-je vous l'envoyer pourque vous regarder un œil vite fait  

Merci d'avance

**Comment by TmpName** [comment]
Oui, pas de soucis, passes par pastebin, par contre avec les fetes la reponse risque de prendre du temps et moi je bosse en deplacement pour 1 jours ou deux).
Quand tu passes par "toutes les sources" et que ta nouvelle source n'apparait pas ca vient en general d'une faute de frappe ou d'un erreur dans le fichier. Kodi n'affiche pas d'erreur, c'est normal, en fait Vstream scanne les pluggins, et en cas d'erreur le saute au lieu d'afficher un message d'erreur.

**Comment by patoche2025** [comment]
Bonjour Merci pour votre rapidité, J'ai essayé de le refaire mais toujours le même résultat dans la recherche apparait sokrostream.biz mais pas de résultat  

bref voici le lien :  http://pastebin.com/uw4PHuVh

**Comment by TmpName** [comment]
J'y jete un oeuil, vais editer ce post au fur et a mesure, pour pas oublier.

ligne 26 faute de sysntaxe manque un '
ligne 28 faute de syntaxe manque deux '
ligne 77 il y a un espace en trop, pour python c'est un mauvais indent (oui je sais, c'est con le python).

Sans message d'erreur c'est assez dur a reperer, utilise une application avec coloration syntaxique pour editer tes fichiers, ca m'a prit 20s pour les 2 premieres erreurs. (Style Notepad +, pas lourd, existe en version portable).

Nouvelle version, avec le premier regex pour afficher les films et le lien next page fonctionnant
http://pastebin.com/UfJanqtD

Bonne continuation.

**Comment by chataigne73** [comment]
Salut
Voici ma version pour ceux intéressés http://pastebin.com/fnDwVxDG

**Comment by TmpName** [comment]
J'ai testé vite fait, ca marche nickel.
Un petit probleme dans les series, qui affiche plus que ta serie, mais c'est pas mechant.

Ce que je te propose, c'est de mettre ton nom en deuxieme ligne ( tres peu y pense)
 et de la mettre en ligne sur le beta >> https://github.com/LordVenom/venom-xbmc-addons-beta/tree/master/plugin.video.vstream/resources/sites
Sinon je peux le mettre moi meme dessus si tu me donnes ton accord.

Je vais surement y repasser dessus pour l'integration dans Vstream (comme pour les couleurs) mais elle devrait pouvoir etre  officiellment a la prochaine mise a jour.

**Comment by chataigne73** [comment]
tu peux les mettre avec plaisir dans la beta ... j'avoue ne pas savoir comment le faire moi-même

si tu es intéressé, j'ai également fait 2 autres sources:

http://pastebin.com/N4kkbnSW    film_streamiz_net.py   pas mal pour le HD
http://pastebin.com/bJ0NA0Lh     libertyland_tv.py    gros site très connu
les 2 marchent pour les films, mais pas trop testé pour les séries

**Comment by TmpName** [comment]
En fait LordVenom evite l'abondance de sources, car la recherche donne beacoup (trop) de resultat, et la plupart ne sont jamais verifiés. Donc il y a une grosse selection pour les sites.

Moi je recheche
2 vieux films, style blade runner ou brazil
2 films rares, interstalla ou cypher
je regarde le nombre de host par film (youwatch et exashare ne comptent pas)
Je ne regarde pas la qualitée, car en general c'est un gag, sauf si vraiment HD, mais en france .....

La vais reformater soko et surement liberty, donne moi un peu de temps, mais normalement tu as accés au site beta si tu veux faire toi meme des modifs.

En tout cas merci, et bonne année now que j'y pense.

**Comment by chataigne73** [comment]
bonne année toi aussi :-)

**Comment by neochris23** [comment]
Salut a vous et meilleurs voeux ....

J'ai une question bete je ne voit pas ou mettre ma source .pi car pour la mettre sur mon raspberry pi 2 le seul moyen que j'ai c'est via ssh mes il y a trop de dossier a ouvrir avant de trouvé le bon.
Pouvez vous m'indiqué le chemin ? merci

**Comment by TmpName** [comment]
Sur linux ca devrait etre
>> ~/.Kodi\addons\plugin.video.vstream\resources\sites

**Comment by neochris23** [comment]
Ok merci pour la rapidité 
je vais regarder ca après la sieste de ma fille

**Comment by TmpName** [comment]
Et si tu as openelec
>>/storage/.kodii/addons/plugin.video.vstream/resources/sites

**Comment by patoche2025** [comment]
Tout D'abord bonne année à tous un tout grand merci pour avoir corrigé les fautes @TmpName 

Bien à toi
Patrice

**Comment by patoche2025** [comment]
re-bonjour je viens juste de mettre à jour le pluggin avec la source sokrostream mais quand je fais une recherche comme jurassic world la recherche se fait bien mais quand je clique sur le film aucun lien me permet d'ouvrir le film est ce que c'est normal?

d'avance merci @TmpName ou @chataigne73

**Comment by TmpName** [comment]
Je viens de tester, quand je clique sur le resultat de la recherche, je tombe direct sur les sources.
Je viens de relire la source, je n'ai rien vu de special propre a la version beta.
Pas de messages d'erreur ?

**Comment by TmpName** [comment]
Ha wi je crois comprendre, tu dois tester la version que je t'ai corrigée, elle n'est pas finie, la version complete est celle de chataigne73 >> https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/sokrostream_biz.py

**Comment by patoche2025** [comment]
Bonjour @TmpName et @chataigne73 tout d'abord un tout grand merci pour m'aider avec ma source j'ai pris la version de @chataigne73 et maintenant j'arrive à faire des recherches et je vois bien les source sauf que quand je clique sur le lien il m'affiche toujours une erreur et le film ne se lance pas j'ai fait une capture d'écran pour vous montrer 
![erreur01](https://cloud.githubusercontent.com/assets/16462265/12138506/c0fa48f2-b459-11e5-99d3-1147957e6a82.jpg)

Est ce que vous avez le même problème, je suis vraiment désolé de vous embêter avec ça!

**Comment by TmpName** [comment]
Si c'est shokrostream qui te donne ca, il y a un probleme, pour le meme film j'ai 5/6 hosts proposé et toi un seul.

**Comment by TmpName** [comment]
Je viens de tester pour le meme film, ca a mit 30s a demarer mais ca a marché.
La source allvid a été mise a jour il y a 11 jours, et ne se met pas a jour de facon auto, c'est surement pour ca que ce site ne marche pas chez toi.

Il va te falloir attendre la mise a jour du mois de janvier (qui devrait pas tarder) ou mettre toi meme le fichier a jour.
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/hosters/allvid.py

**Comment by patoche2025** [comment]
Bonjour, mille merci pour ta patience avec moi @TmpName je comprends mieux maintenant grâce à tes explication.

Je vais mettre à jour le fichier et je vais tester les autres sources

Un tout grand merci pour tout

Bien à toi
Patrice

**Comment by LordVenom** [comment]
Bonjour, 

Si tu bidouille un peux installe la bêta plus souvent mise a jour.
