### ISSUE TITLE
Résultat de recherche

### ISSUE THREAD

**Issue by anomia76** [LordVenom/venom-xbmc-addons#284]
Bonjour,

Cool l'application, vraiment au top !!! merci

En comparant avec la recherche sur les sites comme POYPI, on remarque que des résultats n'apparaissent pas dans VSTREAM, test fait avec le mot clé "La isla" sur Poypi nous avons un résultat sur Vstream rien.

Ai-je loupé quelques chose dans la configuration ?

Merci

**Comment by TmpName** [comment]
Salut, tu as sur d'avoir une version a jour ?
Je viens de faire le test en passant par la recherche generale, puis "toute les sources" / "poypi" / "Recherche" et j'ai absolument tout les resultats.

**Comment by anomia76** [comment]
J'ai bien la dernière version à jour. Je viens de refaire des tests pas moyen de trouver le titre sur VSTREAM alors qu'il est bien présent que POYPI.

Sur Vstream je vois bien POYPI dans la liste des résultats mais pas de résultat.
J'ai aussi des résultat avec French Streaming Co et après sélection rien ne se passe ;(

Pour info mon Vstream tourne sur OSMC.

**Comment by anomia76** [comment]
Même en passant par toutes les sources puis Poypi, pas moyen test fait avec "la isla"

**Comment by anomia76** [comment]
Par contre dans la recherche par genre "thriller" on le trouve... :(

**Comment by TmpName** [comment]
En fait il y a eu une mise a jour de poypi il y a 21 jours.
La mise a jour n'apparait pas officiellement (pas visible par repo ou kodi).
Il te faut soit mettre le fichier a jour toi meme, soit passer par la mise a jour auto dans les parametres de Vstream, onglet "mise a jour", normalement si c'est le cas tu devrais avoir dans la page d'acceuil de Vsteam une icone "mise a jour dispo"

**Comment by anomia76** [comment]
Yep, effectivement it works ! en modifiant les fichiers manuellement.
Par contre pas d'onglet mise à jour auto, c'est dans les options de configuration que tu trouves ça ?

Merci pour les retours ! TOP TOP

**Comment by TmpName** [comment]
C'est l'onglet "outil", le dernier, puis dedans tu verras une option "Recherche mise a jour", ca sert a mettre les fichiers sites (et uniquement eux) a jour.

**Comment by LordVenom** [comment]
C'est ma phaute dsl, la mise a jour des sites a besoin d'une mise a jour de updates.xml.md5 c'est un simple md5 que tu peux modifier n'importe comment, le but etant de juste pas être le même que l'ancien sinon pas de mise a jour pour lui ça a pas changer.
