### ISSUE TITLE
Openload

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#285]
Merci de verifier le host Openload, j'ai a chaque fois erreur fichier introuvable.
Je profite de l'occasion de vous souhaiter une très bonne 2016 et une longue vie a vStream.

**Comment by TmpName** [comment]
Bonne annee a toi aussi :).

Mit a jour sur beta.

**Comment by arzaz** [comment]
Merci beaucoup TmpName,

Maintenant avec ce host j'ai echec de lecture? Peux tu essayer chez toi stp.

**Comment by TmpName** [comment]
Ben je viens d'essayer avec antigang sur fililllimite sans problemes.
Tu essayes ou? parait que dans certains cas il y a un captcha mais j'en ai jamais vu.

**Comment by arzaz** [comment]
Je viens de faire le test sur filillimite; Seul sur Mars + Snister 2 toujours echec de lecture
Avec le site voirfilms, meme chose avec le film Seul sur Mars?
Je me souviens une fois tu as effectué une mise a jour sur beta par rapport a firfox ou quelque chose comme ça.

**Comment by TmpName** [comment]
Je viens de retester, tout est bon chez moi, tu as essayé via ton navigateur ?
C'est peut etre openload qui bloque au bout d'un moment, ou qui te propose un captcha si tu telecharge trop, mais la moi je n'ai aucun probleme.

Si jamais ca te demande un captcha, surtout ne le rentre pas, je te ferais passer un code pour me recuperer quelques infos, vu que moi je ne l'ai jamais eu.

**Comment by arzaz** [comment]
Chez moi avec ma box Prismcube rien ne marche avec Openload j'ai toujours cette erreur!!

**Comment by TmpName** [comment]
Essaye ce lien directement sur un navigateur
ht tps://openload.io/embed/FFpPtJ3UBn0/

**Comment by arzaz** [comment]
Oui ce lien marche sur mon navigateur.

**Comment by TmpName** [comment]
Directement ? sans captcha ?
Il y a pas eu un rattage quand tu as mis a jour le fichier openload ?

**Comment by arzaz** [comment]
Je ne comprends rien ca marche 1/10 mais a 99% je reçois cette erreur echec de lecture.....

**Comment by TmpName** [comment]
Ca doit venir du serveur, mais ca m'aiderais si tu pouvais me faire passer les 10 dernieres lignes de logs

**Comment by arzaz** [comment]
Ci-joint le log file.
[xbmc.log.txt](https://github.com/LordVenom/venom-xbmc-addons/files/76002/xbmc.log.txt)

**Comment by TmpName** [comment]
Alors la vais pas pourvoir t'aider, ca vient bien du systeme, Vstream fonctionne, le lien est bien decodé mais apres ca deconne.

>>19:35:18 T:734580736   DEBUG: Loading: libopenmaxil.so
19:35:18 T:734580736   ERROR: Unable to load libopenmaxil.so, reason: libopenmaxil.so: cannot open shared object file: No such file or directory
19:35:18 T:734580736   DEBUG: Dll libopenmaxil.so was not found in path

A voir si ton install est correcte.

Puis il essaye d'une autre maniere, (a voir si tu peux specifier un lecteur par defaut sur ta machine)
>>19:35:19 T:831939680   DEBUG: CurlFile::Open(0x33f060e0) htxxxtps://openxxxload.co/stream/xxxxx
19:35:20 T:831939680   DEBUG: Open - probing detected format [mov,mp4,m4a,3gp,3g2,mj2]
19:35:31 T:831939680   ERROR: ffmpeg[31966460]: [mov,mp4,m4a,3gp,3g2,mj2] error reading header: -541478725

Il arrive a lire le fichier mais pas a determiner le format.

Peut etre que quelqu'un aura une idée mais moi le monde merveilleux des bugs linux, et e leurs forums completements mort quand tu as besoin d'aide, j'ai deja donné.

**Comment by arzaz** [comment]
Merci quand meme TmpName

J'espère que quelqu'un d'autre aura une réponse a ce problème.

**Comment by arzaz** [comment]
Je ne sais si c'est le cas chez vous, mais chez moi j'ai l'erreur Fichier introuvable.

**Comment by TmpName** [comment]
Chez moi tjours pas de prbs, personne d'autre n'a de prbs ?

**Comment by zburdure** [comment]
Bonjour, j'ai aussi l'erreur fichier introuvable quand je cherche un film sur Vstream installé sur freboox mini 4 k. Par contre je ne suis pas un expert dans le domaine comme vous semblez l'être.

**Comment by TmpName** [comment]
Et uniquement avec openload ?

**Comment by LordVenom** [comment]
Chez moi ça tourne faudrait ce renseigner sur libopenmaxil.so voir l'installer manuellement.

**Comment by TmpName** [comment]
Apres j'ai vu que certain lien openload etaient protege par captcha, mais j'en ai encore jamais vu.

**Comment by jukeee** [comment]
Hello,

j'ai eu la même erreur, comme suggéré par TmpName, tout est revenu en ordre lorsque j'ai installé la bêta : https://github.com/LordVenom/venom-xbmc-addons-beta/archive/master.zip

Pour l'installation, j'ai du dézipper le contenu du zip et le zipper à nouveau sur système linux (directement sur mon raspberry de mon côté, le zip sous mac ne fonctionnait pas..).

Merci TmpName pour la correction :+1:  :+1:  !
et merci énormément pour votre énorme travail.

**Comment by abdydog** [comment]
Merci Merci TmpName

**Comment by arzaz** [comment]
Avec le host Openload j'ai depuis cet après midi echec de lecture? Merci de confirmer si c'est le cas chez vous.

**Comment by TmpName** [comment]
Teste sur man up  sur filmillimte, pas de soucis pour moi.

**Comment by abdydog** [comment]
j'ai tout désinstaller et réinstaller tout est ok
sans doute un bug de kodi.

Merci encore

2016-01-30 13:11 GMT+01:00 TmpName <notifications@github.com>:

> Teste sur man up sur filmillimte, pas de soucis pour moi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LordVenom/venom-xbmc-addons/issues/285#issuecomment-177163573>
> .
>



-- 
"The secret to creativity is knowing how to hide your sources." --Albert
Einstein
