### ISSUE TITLE
Informations sur les films

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#286]
Hello,

Quand j'essaye la fonction du menu "Information" sur un film.

A chaque tentative j'obtiens la réponse :
Could not find item at moviedb

Pourtant la toute première fois j'ai bien obtenu une présentation différente qui permettait d'avoir le résumé des films mais ca n'a fonctionné qu'une seule fois.

Toute aide sera la bienvenue.
Remerciements anticipés.

**Comment by canopre** [comment]
Pour être sûr j'ai créé un compte sur moviedb que j'ai ajouté à la config d'Extend Info Script mais ca n'a rien changé.

**Comment by TmpName** [comment]
Ha, la c'est moi qui ait un probleme, je dois avoir un mix de version, chez moi information ne marche plus du tout.
Tu pourrais me passer le nom du film et le site sur lequel tu as fais le test stp ?

Par contre de memoire Vstream ne passe pas par "'Extend Info Script" pour afficher ses/ces  infos.

**Comment by canopre** [comment]
Je vais dire : Films  / Nouveautées / Voirfilms.org / Seul sur Mars.

Mais comme indiqué + tot : Ca ne fonctionne sur aucun film.

**Comment by TmpName** [comment]
Ok, pas de prb chez moi, essaye avec un film ayant le meme nom en anglais et francais  pour voir si c'est pas un prb de langue.
Demain j essayerais d'installer la meme extension pour voir.

**Comment by canopre** [comment]
J'ai essayé avec Womb et c'est pareil : je n'ai rien d'autre que le message d'erreur 'Extend Info Script".

Pour info c'est quand j'ai cliqué la première fois sur "Information" que Kodi a demandé l'activation de "Extend Info Script"

Mais il y a également eu un message d'erreur de moviedb mais je ne l'ai pas noté.

Ce qui est dommage c'est que ca a marché 1X et après plus rien.

Pour rappel : je suis sur raspberry + OSMC

**Comment by TmpName** [comment]
Bon, suis dsl mais meme apres avoir installe ExtendInfo Script, pas vu de problemes, tu as quelque chose de special dans les logs ?.
En desactivant cette extension (si kodi te le permet), cela remarche ?

**Comment by LordVenom** [comment]
Quel theme utilise tu ?
