### ISSUE TITLE
Proposition Source Vidéo du net

### ISSUE THREAD

**Issue by jojotango** [LordVenom/venom-xbmc-addons#288]
Bonjour à tous,

Je vous propose cette source vidéo <a target="_blank" href="https://www.dropbox.com/sh/9q9ibchdv0adx7d/AACtyzw243mBPPYKq34-F37Ga?dl=0">spi0n</a>

J'ai filtré le contenu pouvant choquer, pour désactiver le filtre il suffit de changer la valeur de la variable SPION_CENSURE à False dans "spion_com.py", pour afficher les nouveautés et les genres j'ai du modifier le fichier "home.py" et ajouter la fonction "showNets".

S'il y a des erreurs n'hésitez pas à me les transmettre.

**Comment by TmpName** [comment]
Merci, je la rajoute de suite sur le beta, pas vu de bugs, Je corrige egalement la page home avec ton code.
Juste 2 remarques:
- Pensez a mettre vos nom en deuxieme ligne.
- Youtube deconne mais ca viens de notre coté, c'est deja reparé sur le beta et chez vous a la prochaine mise a jour.

Et meilleurs voeux en passant ^^.

**Comment by jojotango** [comment]
Cool! Meilleurs vœux et bonne continuation.

Par contre je ne me suis pas occupé de la partie XML pour la traduction français/anglais c'est écrit en dur dans le home.py .
<code>
<string id="00000">Vidéos Nouveautés</string>
<string id="00000">Vidéos Genres</string>
</code>

**Comment by TmpName** [comment]
Pas grave, y en a partout des chaines codées en dur, le code a vraiment besoin d'un nettoyage.

**Comment by LordVenom** [comment]
Trés bonne source en plus d'en un catégorie un peux vide Merci.
