### ISSUE TITLE
Seriesenstreaming.tv

### ISSUE THREAD

**Issue by kevin465** [LordVenom/venom-xbmc-addons#291]
salut tout d'abord j'adore ton plug in c'est vraiment super ! mais depuis 1 semaine j'ecoute better call saul sur seriesenstreaming.tv mais maintenant les épisodes ne s'affiche plus... ?

Je suis sur apple tv 2 kodi 14.2

**Comment by TmpName** [comment]
Mis a jour sur beta et mise a jour auto.
