### ISSUE TITLE
Installer une source

### ISSUE THREAD

**Issue by noox63** [LordVenom/venom-xbmc-addons#293]
Comment fait on pour installer une source en plus sous Kodi openelec pour raspberry ? J ai tenté de faire une source pour stream-down.org mais je ne trouve pas le dossier ou l'installer.. Je suis pas très bon desolé

**Comment by jojotango** [comment]
@TmpName  l'a marqué dans une autre issue:
<quote>/storage/.kodi/addons/plugin.video.vstream/resources/sites</quote>

Il faut placer ta source.py dans le dossier "sites"

**Comment by noox63** [comment]
J'ai bien vu ce post mais si à la racine avec le dossier sur et Var etc j ai bien un dossier storage il n y a pas de dossier qui permet d'accéder à à Kodi et au plugin vstream.

**Comment by jojotango** [comment]
Il y a un point devant "." devant le répertoire kodi, c'est un dossier caché c'est pour ça que tu ne le vois pas. Après Openelec je connais pas tu devras attendre la réponse des chefs.

**Comment by LordVenom** [comment]
Android	Android/data/org.xbmc.kodi/files/.kodi/addon/
iOS	/private/var/mobile/Library/Preferences/Kodi/addon/
Linux	~/.kodi/addon/
Mac	/Users/<your_user_name>/Library/Application Support/Kodi/addon/
OpenELEC	/storage/.kodi/addon/
Windows	Start - type %APPDATA%\roaming\kodi\addon\

Puis plugin.video.vstream\resources\sites\mettre ton .py

**Comment by noox63** [comment]
Merci @jojotango.  je viens de contourner le problème en mettant à jour le plugin. J'ai pu intégrer les données directement dans le zip à installer. A priori cela fonctionne sauf le doc que j'ai fait pour stream-down. Je vais regarder cela quand j'aurai plus de temps.

**Comment by noox63** [comment]
Merci @LordVenom. Et félicitations pour ce plugin qui fonctionne plutôt bien sûr mon raspberry B. Mon grand regret c'est qu'elle ne fonctionne pas sur ma Xbox 1ère génération sous Kodi xbmc4xbox.

**Comment by jojotango** [comment]
C'est pas une solution très pratique de l’intégrer au zip car si ta source ne marche pas tu vas devoir effectuer plusieurs testes et vérifier les erreurs dans les logs. Il faut pouvoir l'éditer directement.

Si on suppose que tu es sous Windows le protocole que tu utilises pour accéder à ton Rasberry Pi est Samba que je ne connais pas. Si effectivement dans le répertoire "storage" tu ne vois pas les fichiers cachés il va falloir configurer Samba. Voici  un <a href="http://media-passion.fr/tutoriels-openelec/%28tuto%29-acceder-au-repertoire-cache-xbmc/">tuto</a> trouver sur google, garde une copie du fichier de configuration d'origine "samba.conf.sample" et remplace "xbmc " par "kodi".
