### ISSUE TITLE
Probleme Vstream sur VU Duo 2

### ISSUE THREAD

**Issue by donmickael** [LordVenom/venom-xbmc-addons#295]
Bonjour à tous, voila aprés avoir installer Xmbc sur mon Vu Duo 2 je vais dans paramètre, extension, installer depuis un zip, mais a chaque fois je rencontre l"erreur : DEPENDANCE INSATISFAITE CONTACTEZ L'AUTEuR DE L'EXTENSION.
Quelqu'un aurait il une solution merci.

**Comment by LordVenom** [comment]
Bonjour, il y a déjà une conversation avec toute les dépendances a toi ensuite de cherche celle qui te manque.

https://github.com/LordVenom/venom-xbmc-addons/issues/38
