### ISSUE TITLE
problemes de recherche

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#296]
salut
je me lance dans une grande campagne de test des fonctions de recherche ... car c'est selon moi ce qui pêche le plus pour que notre addon soit au top !

1er exemple:
je recherche "un jour sans fin" (un de mes films cultes) dans le site filmstreamingz_fr --> plein de résultat, dont le film recherché en 1er
je fais la même recherche, mais via la fonction recherche globale+catégorie films (search1) --> aucun résultat sur filmstreamingz_fr ...   il semble que le pb vienne du formatage des espaces en %20

je posterai d'autres dysfonctionnements dans cette issue au fur et à mesure que j'en trouverai

A+

**Comment by chataigne73** [comment]
la recherche au sein du site libertyland fonctionne, mais pas la recherche libertyland via la fonction recherche globale+catégorie films (search1)

**Comment by chataigne73** [comment]
pourquoi la source fulls-stream n'est elle pas utilisée pour les recherches via la fonction recherche globale+catégorie films (search1) ?

**Comment by TmpName** [comment]
filmstreamingz_fr je m'en occupe de suite.
Pour les autres c'est normal, elles ont été rajouté apres la derniere mise a jour, donc pas encore rajouté au coeur de de Vstream. Dans les options tu peux activer/desactiver tel ou tel site, et les dernieres sources n'y apparaissent pas encore.

**Comment by chataigne73** [comment]
Curieux pour fullstream, et moi libertykand est dans la recherche, mais c'est peut être moi qui l'avait activé...
 sinon, un site intéressant avec pas mal de sources http://www.streamingclic.net
Et enfin une petite URL à garder http://nextwarez.com/classement-meilleurs-sites-streaming/

**Comment by TmpName** [comment]
En fait LordVenom a fait une mise a jour que j'ai raté, je reteste.

https://github.com/LordVenom/venom-xbmc-addons-beta/issues/86

**Comment by TmpName** [comment]
Mise a jour de libertyland

**Comment by Turk182es** [comment]
Salut,

Puisque l'on est dans les problèmes de recherche voici le mien:

Lorsque je recherche une serie, il semblerais que la recherche ne prend pas en compte le serveur TV Streaming.ch. J'ai fait plusieurs essais et toujours aucune series trouvées pourtant je suis certain qu'elle y ai car en allant de page en page je la trouve manuellement.

Par exemple hier, je voulais revoir le magnifique short de Linda Carter dans Wonder Woman et impossible de la trouver par la fonction recherche/serie. Je suis donc allé dans le serveure tv Streaming.ch / Series VF et après une laborieuse recherche manuelle je l'ai trouvé.

J'ai vérifié les paramètres de recherches et sur TV Streaming.ch tout est coché.

Voila, j'espère apporter mon petit grain de sable avec cette erreur.

Cordialement

**Comment by TmpName** [comment]
Merci, j'avais fais une modif la-dessus, mais en fait c'est pire.
Source corrigée et en bonus filtre de recherche en place (moins de resultats parasites)

Elle sera en place en MAJ auto dans le soiree, le je corrige aussi shokro.

**Comment by Turk182es** [comment]
super merci (encore) :-))
