### ISSUE TITLE
Film Illimité

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#298]
Désolé de revenir encore une fois avec le souci de ce site car ca fait plus de 02 heures maintenant qu'il est vide "Aucune information" alors que sur PC le site marche sans problème?
C'est la première fois qu'un site marche bien sur PC mais non pas sur vstream?

**Comment by abdydog** [comment]
changement de nom pour le site

**Comment by TmpName** [comment]
Chez moi toujours aucun problemes, tu es sur d'avoir la derniere version ?

**Comment by arzaz** [comment]
Oui c'est bien la dernière version qui est installée mais parfois et durant plusieurs heures j'ai Aucune information? C'est ça qui m'intrigue le plus. 
Actuellement j'ai accès au site.

**Comment by Kodigoal** [comment]
Idem , parfois aucune info ,  mais même si ca liste par exemple les
nouveautés ou par genre , le 'next' pour passer à la page suivante ne fonctionne jamais
par contre. 
J'ai bien la dernière version, je reteste ce soir.

**Comment by TmpName** [comment]
Mise a jour, pour corriger le bug du "next page".

**Comment by Kodigoal** [comment]
:-) Merci
