### ISSUE TITLE
Pb full-stream

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#299]
salut

il y a apparemment un pb avec la source full-stream : tous les films qui s'affichent sur le site web ne sont pas trouvés par le plugin
il semblerait que le regex ne trouve pas tout

**Comment by chataigne73** [comment]
le pb vient de là : 
`sPattern = 'fullstreaming">.*?<img src=".+?src=(.+?)(?:&.+?)*".+?<h3.+?><a href="(.+?)">(.+?)<\/a>.+?(?:<a href=".quality.+?">(.+?)<\/a>.+?)*<span style="font-family:.+?>(.+?)<\/span>'`

en particulier dans `<img src=".+?src=(.+?)(?:&.+?)*"`   regex que je ne comprends pas d'ailleurs, car j'aurais bêtement écrit `<img src=".+?src=(.+?)"`   (et après test ça marche d'ailleurs)

**Comment by TmpName** [comment]
Alors la, me souvient plus du tout ^^. Devait bien y avoir une raison vu qu'il a marché lors de la modif mais pkoi ce regex ... ?

En fait ce site a plusieurs "mise en page possible" donc un regex trop generaliste ne marche pas. Me refaut faire des tests. Vais voir si je trouve une raison dans l'historique des mises a jour.

**Comment by LordVenom** [comment]
Pour chaque catégorie moi j'ai 21 élément afficher, 20 sur le site puis 1 pour le next.Alors Quel page ne fonctionne pas chez toi ?

**Comment by chataigne73** [comment]
toutes mes excuses LordVenom, je n'utilisais pas la dernière MAJ du 15/01
tout fonctionne parfaitement à présent

**Comment by chataigne73** [comment]
par contre les liens MyStream semblent ne pas fonctionner

**Comment by TmpName** [comment]
Je jete un oeuil a Mystream par contre openload pas de problemes.

En fait quand ca mouline pendant 30s et que ca t'affiche pas de fichiers trouvés, c'est un probleme de timeout, y a un topic qui traine la dessus sur le forum (surtout a cause de Youwatch).
Il y a des delais a augmenter, j'ai testé les 2 liens openload de la version VF de 007, le premier a demarré direct le second au 3 eme essais.

**Comment by TmpName** [comment]
Mystream mit a jour, vivement la prochaine mise a jour, elle va pas etre inutile ...

**Comment by chataigne73** [comment]
comment fais tu TmpName pour mettre à jour aussi vite les hosters ???  je suis sur le cul...

**Comment by TmpName** [comment]
XD, j'ai pris le html en seconde langue.

**Comment by LordVenom** [comment]
Oui ce week end la mise ajour.

**Comment by Kodigoal** [comment]
Pêtre est ce normal, mais je n'ai aucune affiche de film sur les listages nouveautés ou par genre.

**Comment by TmpName** [comment]
Ca y est me souviens pkoi le regex ressemblait a ca les lien des images sont comme ca.:
/img/full-stream.php?src=http) in /img/full-stream.php?src=http://full-stream.org/uploads/posts/covers/9360ef345bc4b6cf85dbcd1dae5bfaa5.jpg&h=360&w=270.

**Comment by geo525** [comment]
J'arrive pas a telecharger vstream(librement.tv) un coup de main sera sympa.je suis novice sur kodi.

**Comment by TmpName** [comment]
Salut, j'ai pas tout compris c'est Vstream que tu n'arrives pas a DL ou tu as des prbs sur un des fichiers sites ?

Normallement tu as des videos explicatives sur la page d'acceuil du github.

**Comment by geo525** [comment]
Slt,non c pas vstream.j'ai telecharger vstream mais rien ne marche.pour les
films 1 source sur 10 qui marche,pour la tv  rien juste arte.merci pour
votre patience

**Comment by TmpName** [comment]
Ha ok, tu parles de libreTV, le ce n'est pas nous qui geront cette partie. Je viens de faire un test et c'est un peu a l'abandon effectivement. A "aujourd'hui" et "ce mois ci" , j'ai rien trouve mais a "anterieur" y a une liste qui date de plusieurs mois qui fonctionne encore.

Sinon juste avant a "TV du web" (Ca c'est nous) j'ai pu faire tourner m6 france2 et NRJ12, et j'ai pas tout testé, mais y en a pas mal qui marche encore. Vstream se focalise surtout sur le stream donc j'avous que j'oubli souvent cette partie, et elle demande beacoup de taff pour etre tenue a jour.

**Comment by TmpName** [comment]
Ha ok, tu parles de libreTV, le ce n'est pas nous qui geront cette partie. Je viens de faire un test et c'est un peu a l'abandon effectivement. A "aujourd'hui" et "ce mois ci" , j'ai rien trouve mais a "anterieur" y a une liste qui date de plusieurs mois qui fonctionne encore.

Sinon juste avant a "TV du web" (Ca c'est nous) j'ai pu faire tourner m6 france2 et NRJ12, et j'ai pas tout testé, mais y en a pas mal qui marche encore. Vstream se focalise surtout sur le stream donc j'avous que j'oubli souvent cette partie, et elle demande beacoup de taff pour etre tenue a jour.

LordVenom a fait une mise a jour la bas depuis moins d'un mois.
