### ISSUE TITLE
Pb film-illimit

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#300]
avec la nouvelle version MAJ il y'a 2 heures, j'ai une différence entre le site web et le plugin sur la liste des nouveautés film
1er film dans le plugin : chair de poule
1er film sur le site : le garçon invisible

j'espère cette fois-ci ne pas avoir donnée une fausse erreur

**Comment by TmpName** [comment]
Lol, pas grave pour les fausses erreurs, la ca fait vraiment un moment que date la MAJ, tout les jours j'ai un probleme de version.

Bug corrigé sur beta en bientot en MAJ auto.

**Comment by chataigne73** [comment]
ça marche, mais je comprends pas pourquoi :-(

tu as modifié le regex pour mettre `<div class="item"><a href="` à la place de `<div class="item">.+?<a href`

et pourtant dans la page html il y a une ligne entre les 2 : 
`<div class="item">
<a href="http://official-film-illimite.net/invisible-boy-en-streaming-hd-1080p/">
`
même avec un regex testeur online ça marche pas

tu peux m'expliquer stp ?

**Comment by TmpName** [comment]
En fait c'est simple quand tu passes par le parser integré a VStream, il effectue un traitement en plus, c'est pour ca que dans certains cas je passe par re.findall() a la place car les traitement me cause plus de problemes qu'autre chose dans certains cas.

Un des traitements est qu'il supprime justement tout les saut de lignes, mais faut le savoir.

Mefis toi du regex .+? car il peut faire 50 lignes. Il trouve la partie d'avant a la seconde ligne de la page, et la partie de droite tout a la fin. Et un autre probleme c'est qu'il demande plus de calcul, sur certains site de regex tu as le nombre de 'step' que prend ton regex a etre calculé, et ca peut aussi vite devenir bloquant.

**Comment by chataigne73** [comment]
ah je vois !
tu parles de ça dans parser.py : 
`def __replaceSpecialCharacters(self, sString):
        return sString.replace('\\/','/').replace('&amp;','&').replace('\xc9','E').replace('&#8211;', '-').replace('&#038;', '&').replace('&rsquo;','\'').replace('\r','').replace('\n','').replace('\t','').replace('&#039;',"'")
`

**Comment by TmpName** [comment]
Exactement.

**Comment by chataigne73** [comment]
nouveaux changement sur film-illimit ...   décidemment  :-(

**Comment by chataigne73** [comment]
oula non il semble que ce soit un peu plus compliqué que cela ...
des modifs aussi à faire dans showhosters

**Comment by TmpName** [comment]
Chez moi ca a marché juste avec ta modif, j'ai mis la version que j'utilise sur la beta.
Apres ils sont en rodage, donc ca risque de bouger tout les jours, cette modif avait deja été faite, puis retirée, puis remise.

**Comment by Kodigoal** [comment]
Merci,
sinon pour Vkstreamingfilm.biz ,
Lister les nouveautés n'a pas l'air de fonctionner,
par contre par Genre ca liste bien.
Impression que même en passant par le site , les nouveautés s'affichent pas
comme il faudrait...

**Comment by TmpName** [comment]
Yep, c'est bizarre, j'ai meme une connexion impossible via kodi alors que le lien marche sous navigateur, on va attendre de voir si ils corrigent le site , mais y a un truc bizarre.

Par contre je fais un nouveau tread pour ce bug, pour cloturer celui la.

cf https://github.com/LordVenom/venom-xbmc-addons/issues/302
