### ISSUE TITLE
Poypi

### ISSUE THREAD

**Issue by otho78** [LordVenom/venom-xbmc-addons#301]
Bonjour,

Merci pour l'excellent travail que vous faites.
C'est pour vous signaler que le site poypi à changer de nom, c'est Kepliz et son url est:
http://www.kepliz.com/moftrytvbc1xccvds0g1df5c48/
Bien à vous,
Otho

**Comment by TmpName** [comment]
Salut.
C'est deja en place sur la beta, tu devrais avoir la mise a jour ce WE.

**Comment by otho78** [comment]
ok, merci...

2016-01-21 16:54 GMT+01:00 TmpName <notifications@github.com>:
