### ISSUE TITLE
Pb sur Vk streaming film

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#302]
Site a surveiller, la page d'acceuil de leur site est en defaut mais reaction bizarre sous kodi.

**Comment by Kodigoal** [comment]
Sur la page d'acceuil: 
http://www.vkstreamingfilm.biz/
on voit bien la liste des films nouveautés

Mais si on teste le lien dans le code .py qui liste les nouveautés:
http://www.vkstreamingfilm.biz/films/
La liste s'affiche plus sur leur site...ca va pêtre revenir.

donc j'ai testé en changeant dans le code:

MOVIE_MOVIE = ('http://www.vkstreamingfilm.biz/', 'showMovies') 
MOVIE_NEWS = ('http://www.vkstreamingfilm.biz/', 'showMovies')

Ca refonctionne, en attendant de voir si ca bouge de nouveau du côté du site.
ps: film-illimité depuis cet fin d'aprem erreur...

**Comment by Kodigoal** [comment]
Sur la page d'acceuil du site,
on voit bien la liste des films nouveautés

Mais si on teste le lien dans le code .py qui liste les nouveautés:
url/films/
La liste ne s'affiche plus sur leur site...ca va pêtre revenir.

donc j'ai testé en enlevant dans le code le /films/ 

MOVIE_MOVIE = ('url site', 'showMovies') 
MOVIE_NEWS =  ('url site',' showMovies')

Ca refonctionne, en attendant de voir si ca bouge de nouveau du côté du site.
ps: film-illimité depuis cet fin d'aprem erreur...

**Comment by TmpName** [comment]
J'ai mis a jour avec ta modif, vu que tout marche avec, je pense que ca suffira en attendant.

Par contre film-illimité fonctionne chez moi, toujours l'erreur ?

**Comment by Kodigoal** [comment]
merci ,
Oui  ca remarche depuis film-illimité.
ca  m'est deja arrivé de temps à autre  que ca ne liste plus rien avec erreur, mais ca
revient à la normale après quelques heures, malgré qu'en allant directement
sur le site, tout a l'air o.k.

**Comment by arzaz** [comment]
Actuellement le site film-illimité ne liste rien sur vstream

**Comment by Kodigoal** [comment]
ils ont réactivés la sécu sucuri , j'ai testé en remettant la sécu dans le code et ca fonctionne.
J'ai fait 2 sources , 1 sucuri activé / 1 non , comme ca si ils changent tous les 5 min , toujours 1 source qui fonctionne.

**Comment by arzaz** [comment]
@Kodigoal, elle est ou la 2ème source? Je ne la trouve pas sur beta

**Comment by TmpName** [comment]
Tu peux laisser la protection securi 24/24 7/7, c'est d'ailleurs ce que je vais faire sur la beta et la MAJ forcée, merci de l'info, je l'avais pas vu.

Dans 5 mn.

**Comment by Kodigoal** [comment]
@arzaz  non je l'ai fait chez moi pour les 2 fichiers sources.
mais vu qu'on peut laisser la protection activée, 1 suffit :)

**Comment by Kodigoal** [comment]
je post ici juste pour signaler site film-streaming.co
ya plus de videos qui s'ouvre sur  streaming-clu b . co m
donc idem dans vstream.
Par contre sur fil m-streamin g .co , videos ok.
Remis url main sur l'ancien et par contre revoir le regex 'next' fin de page ( j'ai fait
chez moi mais à l'arrache , ca fonctionne quand meme )
Et il mette plusieurs fois le même film , bug ou différentes version qualité ....

**Comment by TmpName** [comment]
Alors jj'ai corrigé l'url et le nextpage, par contre je n'ai pas vu le bug des films en double ?

**Comment by Kodigoal** [comment]
si on regarde par exemple dans la catégorie Genre Guerre , on  a plusieurs fois les mêmes films sur
leur site ( première page Genre Guerre:  ya 4x Kamikaze , 3x Patrol , 3x Opération Artic , 2x Alliés )

**Comment by TmpName** [comment]
Ha oui, et c'est vraiment les memes liens en plus.

**Comment by Kodigoal** [comment]
oui à surveiller si streaming-club les videos reviennent , même si ya des double- triple , on a accès aux films , c'est l'essentiel :-)
