### ISSUE TITLE
 nouvelle source

### ISSUE THREAD

**Issue by byronwat** [LordVenom/venom-xbmc-addons#304]
bonjour
pour les series quebecoises qui semble etre difficile de trouver, cette source semble etre efficace.
filmstreamvk.com
je suis encore trop pourri pour créer une nouvelle source, si quelqu un pense pouvoir le faire facilement...
aussi le template semble être assez courant.
y a surtout besoin de pouvoir faire des recherches, peut etre pas besoin de créer toutes les catégories.

**Comment by TmpName** [comment]
Je viens de le tester et je n'ai pas vu de difference avec la version FR, tu as un exemple de serie quebecoise ?
Il y a assez peu de sources, c'est pour ca que je te demande son "plus" par rapport aux autres sites.

**Comment by byronwat** [comment]
j ai installé et configuré abondamment kodi pour pousser ma copine à lacher le cable et ainsi économiser 40$. donc j en était rendu à rechercher les séries qu elle regarde. deux exemples, Yamaska(7 saisons), Au secours de Béatrice (2 saisons), j ai eu quelques difficultés que ce soit avec genesis qui montre bien les episodes mais manque de sources, ou vstream qui ne trouve pas les dernieres saisons. et sur internet je suis tombé sur ce site filmstreamvk.com qui semblait être le plus à jour concernant les séries québecoises. me suis dis que s'était peut être une bonne source de contenu quebecois. mais honnetement si tu penses que ca vaut pas la peine ou qu'une autre source est plus pertinente c ok.

**Comment by byronwat** [comment]
j ai recherché une autre serie qc, les beaux malaises, et il l a aussi.

**Comment by TmpName** [comment]
Ok, vendu, vais m'en occuper dans la semaine.
Juste une question c'est un site typiquement quebecois, ou plus original que les standards ?
Pour savoir si je le laisse "Standardl" ou taggué "Quebec".

**Comment by TmpName** [comment]
Ou sinon, donne moi quelques series rares que je fasse quelques tests stp.
Franchement je prefere un site avec des series/films rares, qu'un avec des blockbusters que tu trouves partout en pseudo HD.

**Comment by TmpName** [comment]
Fichiers en place.
En test.
