### ISSUE TITLE
Tv Streaming.ch Fichier introuvable

### ISSUE THREAD

**Issue by Turk182es** [LordVenom/venom-xbmc-addons#306]
Salut,

J'ai l'erreur "Fichier introuvable" sur toutes les series de ce serveur.

J'ai remplacé tout mes fichier par ceux de la beta mais rien y fait.

J'ai loupé quelque chose ? Merci pour votre aide.

**Comment by Kodigoal** [comment]
Testé quelques séries , ca fonctionne.
Je crois ya que le hoster FlashX pour les séries... ( enfin j'ai vu que flashX sur mes tests la)
Donc pêtre maj FlashX.py de la beta dossier Hosters

**Comment by Turk182es** [comment]
Ben justement j'ai bien copie tout les fichiers de la bêta dans mon add-on 

Tu me confirmes que chez toi le FlashX fonctionne ?

**Comment by Kodigoal** [comment]
Oui les videos s'ouvrent bien avec lien FlashX.
En allant sur le site directement, tu arrives à voir les vidéos?

Par contre, je viens de remarquer sur le dernier site rajouté : Filmstreamvk
Lien des series hoster Netu:
Par vstream:
ip normal : fichier introuvable.
Vpn ip :  lecture ok.

Par le site
ip normal/ vpn : tous les 2 ok.

En allant sur hqq. tv ip normal , access denied error 16
Avec vpn ,  ok.
Je comprend pas pourquoi avec mon ip normal je peux voir les videos
lien netu sur le site directement , et par par vstream..
bizarre.

**Comment by Turk182es** [comment]
En fait j'utilise OSMC ... Donc je ne vais pas sur le site directement.
Je vis en Espagne, un problème de IP ? C'est bizarre car jusqu'à il y a quelque jours ça marchait parfaitement... La je sèche ...

**Comment by Kodigoal** [comment]
oui mais tu peux pas tester avec un pc d'aller sur le site directement
pour vérifier si les vidéos s'ouvrent?
je ne sais pas pour l'ip sinon , si FlashX bloque ...
j'ai retesté serie/nouveautés/tv streaming.ch / serie Mom , ca se lance

**Comment by Kodigoal** [comment]
edit:
En fait, même en allant directement sur filmstreamvk testé les series hoster Netu avec ip normal,
(donc lien video hqq.tv) , j'ai le message access denied error 16 , bloquer par Incapsula..
Ban ip temporaire ou Geo ip restriction ....

**Comment by Kodigoal** [comment]
http://play.cdn06.fx.fastcontentdelivery.com/luq4af6jmhixexzw6umlfj4wrk4wzy5rhnwu5uddfgkpzoibpe275jw4gztq/normal.mp4

Si t'arrive à ouvrir ce lien directement d'une série sur tv streaming ch FlashX,
ou si ca bloque aussi.

**Comment by Kodigoal** [comment]
http://www.flashx.pw/fxplay-pfmrerhrz4g2.html

http://play.cdn06.fx.fastcontentdelivery.com/luq4af6jmhixexzw6umlfj4wrk4wzy5rhnwu5uddfgkpzoibpe275jw4gztq/normal.mp4

Si t'arrive à ouvrir ses liens directement d'une série sur tv streaming ch FlashX,
ou si ca bloque aussi.

**Comment by Turk182es** [comment]
Yep! Le lien s'ouvre, donc le problème est dans mon plugin ... Pourtant j'ai bien mis la dernière version ... Tout les Trash ont été copié ... Je pige vraiment pas :-(

**Comment by TmpName** [comment]
FlashX a été mit a jour il y a 11 jours, tu n'aurais pas les 5/10 lignes de log au moment ou kodi cherche le host ?
Le je pars dejeuner mais plus tard si tu n'as rien dans les logs je te ferais passer une version avec plus d'infos de deboguage.

**Comment by Turk182es** [comment]
Je voudrais tout d'abords vous remercier pour votre aide, c'est rare de nos jours de rencontrer des gens qui s'impliquent autant pour aider un inconnu :-)

Alors je viens de regarder mon log de Kodi et rien  :( apparemment lorsque l'erreur se produit il ne la loggue pas ..

Si il y a autre chose que je peux faire n’hésitez pas. J'ai vraiement envie de retrouver mes vieilles series des années 80 :-))

**Comment by TmpName** [comment]
Essaye avec ce fichier flashX, tu peux utiliser un simple editeur de texte, mais fais un copier/coller du "raw paste data".

Normallement ton log devrait ressembler a 
14:17:46 T:2832  NOTICE: 	[PLUGIN] Vstream: Hoster - play http://flashxxxxx.html
14:17:47 T:2832  NOTICE: packed
14:17:47 T:2832  NOTICE: (True, [('hxxp://play.cdn14.fx.fastcontentdelivery.com/luxxxhwq/normal.mp4', '360p')])
14:17:49 T:2832   ERROR: EXCEPTION: XBMC is not playing any media file
14:17:49 T:2832  NOTICE: 	[PLUGIN] Vstream: Table initialized
14:17:50 T:1724  NOTICE: DVDPlayer: Opening: hxxp://play.cdn14.fx.fastcontentdelivery.com/xxxxxx3h24kt5pumaowf

Edit : tu as quelle version de Vstream ?

**Comment by Turk182es** [comment]
ÇA MARCHE !!!!

Vraiment super merci ! Vous êtes tous vraiment sympas ici, c'est rare de nos jours!

Encore bravo pour le plugin !

**Comment by TmpName** [comment]
Bon alors si ca marche c'est que ton fichier n'etais pas a jour, ou que flashX etait en panne au moment de tes tests, car j'ai juste rajoute quelques lignes de debogage, pas de changement de code.
Enfin bon le principal c'est que ca remarche.

**Comment by Turk182es** [comment]
C'est possible mais bizarre. Par contre pour le savoir pour une prochaine fois, comment puis je actualiser mes fichier ? Ce que j'ai fais c'est copier l’intégralité de la version beta directement dans ma Raspberry à l'aide de WinSCP.

Dois je m'y prendre autrement ?

**Comment by TmpName** [comment]
En fait, pour ca bonne nouvelle, la prochaine version aura une mise a jour "auto" fonctionnelle. C'est a dire que quand il y aura des fichiers mit a jour, une nouvelle icone apparaitra dans la page d'acceuil et tu pourras mettre a jour les fichiers site et les fichiers hosts juste en cliquant dessus.

Pour le moment tu peux mettre les fichiers site a jour dans les parametres de Vstream, mais pour les fichiers hosts, actuellement le plus sur c'est l'editeur de fichier texte et le copier/coller.

La version beta, est pour les bidouilleurs, en copiant l'integralité des fichiers ca peut etre encore pire que la version de base.

**Comment by Turk182es** [comment]
Ok, je comprends,. Bon l'essentiel c'est que ça marche ;-)

Encore merci pour votre aide!

**Comment by saraFR2** [comment]
Now [Tv Streaming](http://tvstreaming.ch/) is working again.

**Comment by saraFR2** [comment]
**_ÇA MARCHE [tvstreaming.ch](url)_**

**Comment by TmpName** [comment]
Ce n'est pas le meme, quelqu'un a du recuperer l'adresse, leur site est maintenant h ttp://w ww.la-tele-du-web.tv
