### ISSUE TITLE
Openload does not work anymore

### ISSUE THREAD

**Issue by NizarAloui** [LordVenom/venom-xbmc-addons#308]
Please check openload hoster it seems that it does not fetch any link anymore.

**Comment by TmpName** [comment]
It's corrected, but you need to update files yourself, no update in this part up to the next official complete update.

openload.py update > https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons-beta/master/plugin.video.vstream/resources/hosters/openload.py

aadecode.py update >> https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons/master/plugin.video.vstream/resources/lib/aadecode.py

**Comment by NizarAloui** [comment]
Hello, 

The aadecode.py file seems to be the same as the one on the master branch and it does not resolve the issue .

Thanks,

**Comment by TmpName** [comment]
Yep sorry, I have updated the previous link.

**Comment by NizarAloui** [comment]
Thanks, it worked like a charm now :)
