### ISSUE TITLE
nouvelle mise a jour

### ISSUE THREAD

**Issue by domtom25** [LordVenom/venom-xbmc-addons#309]
merci pour tout ce que vous faite

mais je tien particulierement au site tv streaming complet sur tout les domaines mais tout leur lien qu il utilise sont flashx 

si c es possible si vous plait de mettre a jour pour corrige le probleme 

longue vie a votre site et merci encore

**Comment by TmpName** [comment]
Ha oui je me souvient, c'etait toi qui trouvais pas le fichier.
Et tu as essayé carrement de faire une recherche sous windows avec le fichier "flashx.py"

Car la version en beta marche, je vient de la tester.

Sinon les mises a jour se font en debut de mois. A la prochaine mise a jour les fichiers hebergeurs se mettront a jour tout seul. Mais la, pas le choix, je suis dsl mais soit tu fais toi meme la MAJ soit au moins 15 jours a attendre.

**Comment by domtom25** [comment]
TU ME DONNE LA VERSION BETA a telecharger je ne la trouve pas merci beaucoup

**Comment by LordVenom** [comment]
Si vous n arriver pas a le faire vous même . je vous conseil d attendre la mise a jour. Écrire en maj revient a crier merci de ne pas CRIER.

**Comment by TmpName** [comment]
Je te deconseille d'installer la version Beta, comme son nom le dit, c'est juste une beta, pas un produit fini.

Ouvre juste ton fichier flashx.py avec un editeur de texte et remplace la par celui la
https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons-beta/master/plugin.video.vstream/resources/hosters/flashx.py

**Comment by Kodigoal** [comment]
Juste pour signaler,
Ya un soucis avec le hoster VideoMega je crois, si pas temporaire , les liens
sont introuvables.

**Comment by TmpName** [comment]
Je vient de tester, et le je peux pas encore repondre, soit ils ont modifie la syntaxe du lien, soit ils ont un prb serveur, j'ai un peu tout testé et au mieux j'ai une erreur 403. Pas vu un site de streaming avec videos fonctionnant.

**Comment by Kodigoal** [comment]
oui , impression que les liens doivent etre sous la forme videomega. tv/?ref=
au lieu de /view.php?ref= ou /iframe.php?ref et cie.
Et encore parfois , ca fonctionne pas.
Et vu le code videomega.py, je suis largué :-) ca a l'air plus complexe que ca.
Sinon sur voirfilms , le 'next' ne fonctionne plus.
Là aussi, j'ai essayé de corriger mais j'arrive pas.
Le sUrl retourné pour le parse dans la partie du code pour checker le 'next'  est l'url du dernier film de la liste et non genre voirfilms/comedie_1 ...

**Comment by TmpName** [comment]
Voirfilm corrigé.

Je jete un oeuil sur videomega (ca a l'air de remarcher) et je rajoute leur nouvelle source en passant.

**Comment by TmpName** [comment]
Bon videomega mit a jour, pour la mise a jour manu 2 fichier a mettre a jour megavideo.py et packer.py a trouver sur beta.

Mise a jour auto impossible.

**Comment by Kodigoal** [comment]
Même chez speedy , c'est moins rapide.
Merci :-) et en plus on apprend ^^ top

**Comment by Kodigoal** [comment]
Je crois que t'as laissé un [0] en trop pour le soucis du 'next' voirfilms.
car le 'next' liste la page home du site encore et si on met:
return URL_MAIN + aResult[1][0]
c'est ok.
si ca vient de là ^^

**Comment by Kodigoal** [comment]
Au tour de spiOn out.
Changer les 2 pattern et c'est ok mais à l'arrache donc ca doit pas être vraiment optimisé dans les régles de l'art :D

pour showMovie:

sPattern = 'class="post clearfix"><a href="([^<]+)" title="(.+?)".+?<img src="(.+?)"'
pour le 'next': ( virer aussi aResult si false, sert plus je pense)
sPattern = '<div class="nav-previous"><a href="(.+?)"'

et pour les genres : on a /category/ qui se rajoute.
ex : http: // www spi0 n com/category/animaux/

**Comment by Kodigoal** [comment]
Au tour de spiOn out.
Changer les 2 pattern et c'est ok mais à l'arrache donc ca doit pas être vraiment optimisé dans les régles de l'art :D
pour showMovie:
#sPattern = 'class="post clearfix"><a href="([^<]+)" title="(.+?)".+?<img src="(.+?)"'#
pour le 'next': ( virer aussi le aResult si false, sert plus je pense)
#sPattern = '<div class="nav-previous"><a href="(.+?)"'#

et pour les genres : on a /category/ qui se rajoute.
ex : http: // www spi0 n com/category/animaux/

**Comment by Kodigoal** [comment]
Au tour de spiOn out.
Changer les 2 pattern et c'est ok mais à l'arrache donc ca doit pas être vraiment optimisé dans les régles de l'art :D

pour showMovie:

> sPattern = 'class="post clearfix"><a h ref="([^<]+)" title="(.+?)".+?<im g src="(.+?)"'
pour le 'next': ( virer aussi le aResult si false, sert plus je pense)
> sPattern = '<div class="nav-previous"><a h ref="(.+?)"'

et pour les genres : on a /category/ qui se rajoute.
ex : http: // www spi0 n com/category/animaux/

**Comment by Kodigoal** [comment]
Au tour de spiOn out.
Changer les 2 pattern pour test et c'est ok mais à l'arrache donc ca doit pas être vraiment optimisé dans les régles de l'art :D
http://pastebin.com/jReZx0J7
Et pour les genres : on a /category/ qui se rajoute.
ex : http: // www spi0 n com/category/animaux/

**Comment by TmpName** [comment]
Et merd2, tant pis pour voirfilm, je corrige, mais je ne vais pas la mettre en MAJ auto. Je pense pas que depuis hier il y en ait trop qui aient fait la MAJ.

Pour spion m'en occupe de suite merci.

**Comment by Kodigoal** [comment]
ca a l'air de fonctionner pour le next.
Par contre, depuis les 5 dernières vidéos publiées, le pattern change.
Le lien vidéo se trouve après:
<div class="video_tabs">
Pêtre faire 2 parse , si il trouve pas de résultat pour le pattern actuel,
passer le nouveau pattern.

**Comment by Kodigoal** [comment]
ca a l'air de fonctionner pour le next.
Par contre, depuis les 5 dernières vidéos publiées, le pattern change.
Le lien vidéo se trouve après:
div class="video_tabs"
Pêtre faire 2 parse , si il trouve pas de résultat pour le pattern actuel,
passer le nouveau pattern.

**Comment by TmpName** [comment]
C'est exactement ce que j'ai fais, merci ^^.
On aurait pus utiliser un regex avec "dailymotion" vu que toute leurs videos ont l'air de venir de la bas, mais chez moi ca met meme pas 1s a s'afficher donc pour le temps de calcul, on s'en fout un peu.

Pour info, tu peux corriger toi meme directement sur le site de la beta, selon tes accees tu auras besoin de validation ou pas, mais tu peux y aller tranquille, elle est la pour ca, il n' y aucun risque.

**Comment by Kodigoal** [comment]
oui lien youtube & dailymotion , en tout cas niquel et parse rapide oui,  merci.
Vu mes pattern quand j'essaye de corriger par rapport aux votres , je m'abstiens de toucher xD
Même si ca fonctionne , c'est pas top, donc je m'en tiens  à signaler quand je rencontre
un problème.

**Comment by Kodigoal** [comment]
bon  , je sais pas si vient seulement de chez moi, 
mais  les liens youtube ( des nouveaux articles là) s'ouvrent pas.
Ils sont sous la forme :
vidéo Femme qui a dressé son  chien qui miaule: 
y outube com/watch?v=ivtE-dwbiAo
Est ce qu' il faudrait pas le transformer  comme les anciens liens avec un replace:
youtube com/embed/ivtE-dwbiAo
Ou ca vient d'ailleurs qu'il ouvre pas les /watch?v= ( invalid parameters message erreur).
rend gaga ce site xD

**Comment by TmpName** [comment]
Lol, en fait on utilise un pluggin externe pour les liens Youtube, normallement c'est a lui de gerer les liens.
Mais vais voir ce que tu dis, reformater les liens.

Par contre c'est bizarre, mais avant quand la syntaxe des liens passé au pluggin etait mauvaise, y avait un message d'erreur, la rien du tout.

**Comment by Kodigoal** [comment]
ah ok , le plugin va que garder le videoID au final. j'avais mis le replace dans le spio n .py xD
Pour le nouveau système de maj , c'est bien pensé , donc ca devrait le faire^^
