### ISSUE TITLE
Ajouter un Source/Site dans VStream

### ISSUE THREAD

**Issue by stormz85** [LordVenom/venom-xbmc-addons#311]
Hello LordVenom ! 
Petite question, j'ai 2 Source que je voudrais ajouter sur VStream
j'ai vu que Poypi à été renommé et Bovup egalement :) mais je sais pas comment faire car je suis pas codeur, ya un tuto quel que chose ? de pas trop compliquer

Merci d'avance !

**Comment by TmpName** [comment]
Poypi est devenu kepliz et est deja en place, bovup est la meme source.

Pour creer une nouvelle source, il y a un fichier "squelette" ici >> https://github.com/LordVenom/venom-xbmc-addons/blob/master/ajouter_une_source.py

Pour les tutos, il faut fouiller les issues, tu n'es pas le premier, et il y a de forte chance qu'en cas de probleme, la solution ait deja ete donnée, apres tu peux demander de l'aide au meme endoit.

Un point de depart ici https://github.com/LordVenom/venom-xbmc-addons/issues/257

**Comment by stormz85** [comment]
Je te remercie ! pour cette réponse ;) 
quand tu dis que Bovup est la même source, tu veux entends par la que Bovup ou Kepliz même source en arrière plan?

et Merci pour le lien !

**Comment by TmpName** [comment]
C'est les meme liens qui sont proposé dessus, en fait il genere a chaque fois plusieurs sites de 5 lettres generees au hazard, mais au final tu ne trouveras pas plus de films, c'est les memes.

**Comment by cocoboy31380** [comment]
Bonjour j'aimerai bien que l'on ajoute www.streamcomplet.com, streamay.com (il a un classement par date et par origine si on peut aussi l'ajouter ca serait genial mais bon pas obligé ^^) et http://papystreaming.com/fr/ ou http://papystreaming.com/

**Comment by cocoboy31380** [comment]
Et je suis désolé mais je ne connais rien à la programmation, j'ai essayé de le faire moi-même, ben sur les 3 sources cités au-dessus, seul streamcomplet est apparu dans la liste "source" mais nul par ailleurs, et quand j'ouvrais le site, aucune liste ne s'affichait ....

**Comment by TmpName** [comment]
@cocoboy31380 tu tourne avec quelle version de Vstream ?

Sinon streamay est en todo list, il ya meme un user qui est deja sur le coup.
Le premier je viens de le rajouter en todolist.
Papy n'y sera jamais par contre, la connexion est limitée (ca coupe au bout d'une certaine durée).

**Comment by cocoboy31380** [comment]
ah ok ^^ c'est cool et je l'ignorai pour papy merci pour l'info ^^. En tout cas se plugin c'est le graal ! ^^

**Comment by cocoboy31380** [comment]
D'autre sites que j'ai découvert : http://www.skstream.com, http://www.films-regarder.com, http://r-streaming.com/, http://seriezone.com, http://www.filmze-streamiz.net. Il se peut que certains site soit présent, je me suis basé sur la liste fournit par l'addon lorsque j'ai choisi "toutes les sources".

**Comment by TmpName** [comment]
Je t'avous que certains sites m'en rappelent d'autres, ils finissent par tous se ressembler ^^.
En tout cas merci j'en ai rajouté 2 en todolist.

**Comment by cocoboy31380** [comment]
cool ^^

**Comment by yokoya06150** [comment]
bonjour comment on ajoute sur vstream

**Comment by yodidon** [comment]
> Quand j'ajoute une source elle ne s'affiche pas dans les source de vstream

c'est à dire ?

**Comment by lesueurnicolas27** [comment]
Merci beaucoup

**Comment by airfmessoual** [comment]
> > Quand j'ajoute une source elle ne s'affiche pas dans les source de vstream
> 
> c'est à dire ?

J'ai créé le fichier.py du site en question et je les copiés vers le répertoire site du vstream et quand je vais sur toute les sources dans vstream ma source (le site que j'ai ajouté) ne s'affiche pas parmi les autres.

Je suis sous Android.

**Comment by yodidon** [comment]
L faut aussi que tu l’ajoute dans le fichier site.json

**Comment by yodidon** [comment]
> > > Quand j'ajoute une source elle ne s'affiche pas dans les source de vstream
> > 
> > 
> > c'est à dire ?
> 
> J'ai créé le fichier.py du site en question et je les copiés vers le répertoire site du vstream et quand je vais sur toute les sources dans vstream ma source (le site que j'ai ajouté) ne s'affiche pas parmi les autres.
> 
> Je suis sous Android.

Si tu veux on en parle sur discord

**Comment by airfmessoual** [comment]
> L faut aussi que tu l’ajoute dans le fichier site.json

Je les ajouter , c'est pareil,

**Comment by yodidon** [comment]
> > L faut aussi que tu l’ajoute dans le fichier site.json
> 
> Je les ajouter , c'est pareil,

Passe sur discord , ça sera plus simple
