### ISSUE TITLE
Problème Exashare

### ISSUE THREAD

**Issue by Mystikal57** [LordVenom/venom-xbmc-addons#312]
Salut à tous,

Bravo pour le travail effectué, c'est vraiment super ! 
J'ai l'impression qu'il y a un soucis depuis quelques jours avec Exashare ? Quelqu'un peux confirmer ?

**Comment by TmpName** [comment]
Confirme, merci
Mit a jour sur beta https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons-beta/master/plugin.video.vstream/resources/hosters/exashare.py

**Comment by Mystikal57** [comment]
C'est plus de la réactivité c'est de la proactivité ! :-) merci !
