### ISSUE TITLE
Fichiers introuvables

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#313]
Hello,

Je ne sais pas si vous avez le même problème mais je ne peux accéder à aucun film avec à chaque fois la même erreur : fichier introuvable :(

J'ai essayé les nouveautés avec 6 ou 7 sources sans aucun succès.

Je joins mes logs en espérant que vous pourrez m'aider à comprendre le problème.

Remerciements anticipés,

Florent

h ttp://pastebin.com/Y7PhYpif

**Comment by TmpName** [comment]
Alors il ya un epu de tout.
En partant de la fin, les 4 derniers liens sont mort.
Ensuite legend sur easyvie fonctionne chez moi.
Le chasseur de sorciere sur full_streamvk_net a les 4 liens mort, mais dans tout les cas tu as un probleme de parser, tes liens sont mauvais.
Les rois du monde ont fonctionné au moins sur 2 hosts, mais pareil tu as des liens foireux
>>Connection Impossible,http://fxxxxxxxx/2287-les-rois-du-monde.html"+class="full-link+border-2">Les+Rois+du+monde</a></h5>++++<div+class="clr"></div></div><div+class="short-film">++++<div+class="img-block+border-2">++++++++<

Tu recuperes trop de contenu, tu es sur d'avoir la derniere version, essaye de mettre a jour les fichiers sites en passant par les parametres de vstream puis outils.

**Comment by canopre** [comment]
Je viens de faire un premier essai avec libre_stream_org et c'est pas bcp mieux.

Pour moi qui n'y connait rien y'a même des choses bizarres à la fin de mes logs : 

http://pastebin.com/Ttg85GCk

Je vais essayer avec un autre fournisseur.

**Comment by canopre** [comment]
Quelques essais guère plus concluants sur voir_films_org

http://pastebin.com/Dzr8DLCR

**Comment by canopre** [comment]
J'ai finalement remarqué que VStream n'était pas à jour.

J'ai donc corrigé ce problème, puis à nouveau mis à jour les hosts comme indiqué plus haut.

Mais le résultat n'est vraiment pas convaincant : toujours que des erreurs "Fichier Introuvable" et tout un tas de caractères bizarres dans les logs :

http://pastebin.com/9eH8sjbE

Merci d'avance pour votre aide.

**Comment by TmpName** [comment]
OUi ^^, les caractere bizarre c'est a cause de openload, je t ai mit le lien plus haut, il y a 2 fichiers a mettre a jour openload.py et aadecode.py

Les deux dernier lien videomega sont mort aussi,

Le lien easyvid a marché chez moi.(voyage arlo)
Exashare aussi.
Pour ces deux la par exmple il te suffit d aller ici https://github.com/LordVenom/venom-xbmc-addons-beta/tree/master/plugin.video.vstream/resources/hosters
Choisir le host, cliquer sur "RAW", faire un "copier" de la page, ouvrir le fichier sur ton systeme et coller le tout dedans.
Si tu ne t es pas loupe dans exashare ligne 122 il y a un "*" en plus.

Pour youwatch la c'est bizarre, il n' y aucune MAJ dessus, et tes liens sont bon, a voir du cote du timeout, en l'augmentant (youwatch peut mettre jusqu'a 1 mn pour lancer le film dans le pire des cas)

**Comment by canopre** [comment]
Bonjour,

Comme indiqué : j'ai bien suivi ta procédure pour  openload.py et aadecode.py.

Pour les autres liens qui marchent pas : j'avais déjà signalé pas mal de pb avec un Raspberry : plein de liens qui marchent pas.

Pour le TimeOut : je l'ai mis à 4mn mais ca n'a jamais rien changé.

**Comment by TmpName** [comment]
Peut etre un prb de codec, openload et exashare refonctionnent ?

**Comment by canopre** [comment]
Bonjour Et merci pour ton aide.

Je viens de tester 3 films sur ces 2 hosts et aucun n'a démarré :(

http://pastebin.com/KLm76c4C

**Comment by TmpName** [comment]
Il y a forcement un rattage (pour openload) dans ton copier/coller, je viens de tester, pas de soucis.
Regarde ton fichier aadecode.py ligne 11 si tu as juste
>>self.encoded_str = aa_encoded_data

C'est que ce n'est pas le bon fichier.

**Comment by canopre** [comment]
Bon bon après de nombreux tests : je pense que le problème venait principalement d'une mise à jour d'osmc qui était pas bien passée.

Je suis revenu en arrière et tout est rentré dans l'ordre.

Mais merci beaucoup pour l'aide et les détails : tout est un peu plus clair pour moi maintenant.

**Comment by cocoboy31380** [comment]
Bonsoir, problème avec youwatch, impossible de visionner le moindre lien, je pensais que ca venait de ma co, mais non, pourtant sur le site adkami je n'ai aucun soucis pour visionner les videos. Pourriez-vous m'aider svp ? merci beaucoup. Pour info j'ai supprimé vstream, téléchargé la version 0.3.9 que j'ai installé (je sais pas si il y a un cache à vider ou autre. Si quelqu'un a une idée ça serait super à moins que ça ne soit vraiment les serveurs de youwatch, mais dans se cas là je ne comprend pas pourquoi ca ne marche pas depuis kodi (j'ai kodi avec Vstream sur mon smartphone en 3G pas d'acces non plus a youwatch) Merci beaucoup

**Comment by cocoboy31380** [comment]
Je tiens à préciser que je n'y connais absolument rien au python et à la moindre forme de programmation ...
J'ai essayé, le site apparaissait dans "source" mais nul part ailleurs et quand j'allais dessus, tout était vide ...

**Comment by TmpName** [comment]
Ha mon avis vu ton precedent post sur l'autre topic, trop peu de sources fonctionnelle, ca doit etre une histoire de bloquage serveur.
Avec la derniere version, tu ne devrais avoir que 2 sources(sites) non fonctionnelles.

**Comment by cocoboy31380** [comment]
bah full-stream.org ne marche plus apres je sais pas pour les autre je dois avouer que j'ai pas fait attention. Et pour le bloquage serveur du coup on ne peut rien y faire ?. En tout cas MERCI aux createurs et aux personnes qui aident a ameliorer l'addon c'est vraiment de l'excellent job et evite pas mal de soucis ^^

**Comment by TmpName** [comment]
Yep ce site fait parti des 2 HS. Mais a part un site "HD" tout les autres tournent sans prbs.
Si il y a un bloquage je n'ai aucune idée de comment tournent les sites, il y a moyen de faire croire que tu es un vrai navigateur au lieu d'un mobile, si ils bloquent via ce systeme, mais du coup tu n'auras plus le meme contenu si ces memes sites proposent un autre contenu au mobiles.

Il y a aussi des sites qui proposent du stream mais pas sur mobiles, dont il y a  bien un moyen de faire la distinction.

**Comment by cocoboy31380** [comment]
bah sur facebook il y a une astuce pour recupérer les vidéos hébergées par le site, il suffit de remplacer le "https://www" par "m" du coup on a la version mobile du site sur notre navigateur puis de faire clic droit et enregistrer la cible sous. Donc faut espérer qu'une solution de se type puisse etre mise en place ^^ et vous faites partie des développeurs de l'addon ?

**Comment by cocoboy31380** [comment]
Ou alors coupler cette addon avec web viewer ou un truc dans le genre ?

**Comment by TmpName** [comment]
J'y ai pensé, utiliser les site d'archives web, mais dans tout les cas, ca ne durera pas et il y a peu de chnace que le site sans entierement memorise, donc ca va demander du boulot, pour quelque chose qui sera out dans quelques semaines ou plein de liens mort.
Par contre je connaissais pas le coup de la version mobile. chez moi ca ne marche pas, je dois me louper quelque part.

**Comment by cocoboy31380** [comment]
je sais pas j'ai vue ça sur se site http://www.matvpratique.com/video/26172-comment-telecharger-une-video-facebook-sans-logiciel et j'ai pu récuperer deux ou trois trucs sympa ^^
Du coup je me demande si faire passer kodi pour un navigateur mobile

**Comment by TmpName** [comment]
Exactement, 1 fichier par site et un autre par hebergeur,  plus facile a gerer.

Le probleme de passer par leur facebook, c'est la recherche de fichier, et que le catalogue n'a rien a voir avec le site original.

**Comment by cocoboy31380** [comment]
ah oui non  je ne dis pas de passer par facebook, mais d'utiliser la solution que le mec a trouver pour telecharger les videos de facebook pour passer par la version "mobile" du site en esperant que cela soit possible et applicable. Les firefox version mobile et autres navigateur pour tablette et smartphone doivent bien envoyer un signal qui indique que se sont des navigateurs mobile.

**Comment by TmpName** [comment]
Oui, il envoie un header appelle "user-agent" en fait ca permet de te faire passer pour ce que tu veux.
On l'utilise beaucoup dans les fichiers hosts, car certains sites justement te bloque si ils ne recoivent pas celui qu'ils veulent.

J'ai un addon de replay qui uilise justement ce systeme, le site mobile est plus facile a traiter, et donc il passe par la version mobile, Par contre les video ne sont que au format "mobile" donc la qualitée ....

Mais Vstream est tres performant pour recuperer les liens, rassure toi, c'est pas d'obtenir les liens d'une page web qui est un probleme pour lui. C'est plutot de choisir la bonne source(site) pour trouver les liens.

**Comment by cocoboy31380** [comment]
Oh je ne suis pas inquiet du tout ^^ j'aimerai juste trouver une solution pour youwatch et d'autre serveur qui pourrait poser probleme. En tout cas je suis impressionné par les capacité de cet addon et de Kodi aussi au passage car sa gestion des differents type de serveurs domestique est vraiment excellente, avec une facilité pour inclure ou exclure des sous dossiers etc etc alors avec vstream et genesis, c'est la perfection.

**Comment by TmpName** [comment]
Maintenant que tu m'y fais penser je sais pas si on a testé ca, de faire passer un faut user-agent a youwatch dans le cas ou kodi passe celui de ton telephone.

Essaye d'editer le fichier youwatch.py
ligne 167
>> return True , aResult[1][0][0]

a remplacer par
>> return True , aResult[1][0][0] + '|User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0'

**Comment by cocoboy31380** [comment]
je viens d'essayer ca marche pas. Par contre je me demande si il n'y aurai un truc a modifier dans le resolver. j'ai modifié le fichier present dans appdata/roaming/kodi/addons/plugin.video.vstream/ressources/hosters c'est bien celui la ?

**Comment by TmpName** [comment]
Oui, mais c'etait juste pour tester, si c'etait ca le probleme, tu ne pourrais pas non plus lire une video youwatch en passant par ton navigateur.

**Comment by cocoboy31380** [comment]
Ok purée que c'est compliqué ^^. dommage que je ne puisse pas aider plus ...

**Comment by TmpName** [comment]
Lol, pas de soucis, y a plein de chose a faire, ou a apprendre sur ce plugin.

**Comment by cocoboy31380** [comment]
ah ben ca serait avec plaisir mais j'y connais rien du tout en programmation ...

**Comment by TmpName** [comment]
C'est l'occasion d'apprendre, le code est tres simple, moi j'ai decouvert le python sur Vstream, et parfois c'est juste un lien qui change, et il y a un fichier squelette pour creer ses propres sources.

Apres il y a plein d'autre chose utile a faire, trier les sites qui marchent plus, trier les plus interessants, chasser les bugs, repondre aux users perdus sur les issues, ....

**Comment by cocoboy31380** [comment]
j'ai essayé de créer mes propres sources a partir du squelette pour streamay ... mais ça n'a pas marché idem pour streamcomplet (lui il est apparu dans la liste des sources contrairement a streamay)

**Comment by cocoboy31380** [comment]
J'ai mis a jour Kodi isengard (15.0) vers jarvis (16.0) le plugin Vstream m'a proposé une mise à jour pour deux sources et youwatch, et depuis youwatch refonctionne. Merci à la team pour cet excellent boulot, du coup j'aimerai savoir quel était le soucis avec youwatch svp merci

**Comment by TmpName** [comment]
Ils ont rajoute une "protection" qui regarde le "referer" (un autre header comme le User-Agent dont on a parlé 5/6 posts au dessus), le page d'ou tu provient en arrivant sur le lien de la video. Il m'a simplement suffit de rajouter au lien de la video un faux referer (et j'ai pris le lien de la page HTML tout simplement).

**Comment by cocoboy31380** [comment]
ah ah du coup j'étais pas très loin XD, content que la solution ait été trouvé et merci à vous d'avoir pris le temps de répondre. ^^
