### ISSUE TITLE
Frenchstream

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#314]
Le site Frenchstream ne s'ouvre plus il me donne l'erreur Vstream script.

**Comment by TmpName** [comment]
Leur site est HS.
Mais j'y ai pas touché car ils viennent d'ajouter deadpool, qui est assez recent, donc je ne pense pas qu'il vont fermer leur site.
Pour le moment j'attend de voir, pas d'infos pour un nouveau hebergeur ou autre.

**Comment by Kodigoal** [comment]
De mon côté , ca fonctionne , mais il liste pas la même chose que sur le site.
Si on liste les  nouveautés, il se base sur la liste complete main url + /films/.
Les derniers films rajoutés sont sur l'acceuil , a voir pour faire comme cinemay
une fonction à part.
Et si on veut laisser comme ca  , il reste un soucis, il ne liste pas les
films de qualité 1080 , car dans le pattern il capture seulement 3 chiffres ,
donc les 1080 passe à la trappe :(
div class="film-list-quality"   span ((.+?)p)
J'ai mis ca à la place et ca liste bien , mais le regex ya pêtre mieux à faire xD

**Comment by TmpName** [comment]
Ha oui, ca remarche juste a l'instant.
Par contre la je me sauve, donc je pourrais rien faire avant demain.

**Comment by Kodigoal** [comment]
Ca presse pas^^
Bon après les nouveautés on peut laisser comme ca , je pense page accueil,
c'est plus genre derniers films 'box office'  rajoutés en fait, on les retrouve dans le listage actuel.
Ya juste le soucis des films 1080 qui sont pas listés.

**Comment by TmpName** [comment]
Bon site encore HS chez moi, en attente.

**Comment by arzaz** [comment]
Que se passe t-il exactement avec ce site sur vStream? Car ca marche nickel sur PC

**Comment by TmpName** [comment]
Il remarche juste a l'instant chez moi ^^, en fait il n'est pas stable du coup pas moyen de le mettre a

**Comment by TmpName** [comment]
Bon probleme avec urllib, si quelqu'un arrive a se connecter sur ce site via une ip ou un autre host je suis prenneur.

**Comment by Kodigoal** [comment]
C'est ok avec ip maj.
Sinon si on veut être pointilleux , on peut pour les nouveautés mettre
URL_MAIN + 'son-eklenen-filmler/'
pour virer les 6 films incontournables qui sont listés en fin de page sur la Home xD
Je fais un pull mais a voir après si c'est génant ou pas pour vous ce petit hic.

**Comment by TmpName** [comment]
Site encore out pour moi ^^, bon vais attendre qu'ils achetent un vrai serveur.

**Comment by Kodigoal** [comment]
salut,
ya 2 sites k.o.
full st ream org : admins tribunal.
film str eaming co :  a voir pour remettre hd stream in

**Comment by TmpName** [comment]
Oui, j'ai vu pour les premiers, j'espere que ca s'arranger.
M'occupe du second de suite, merci.

**Comment by arzaz** [comment]
J'ai toujours le problème avec le site film streaming co malgré l'avoir remplacé par celui de la beta "hd stream in"? c'est toujours vide

**Comment by TmpName** [comment]
Teste a l'instant, pas de prb chez moi.
Regarde la ligne 23 de ton fichier pour etre sur.

**Comment by arzaz** [comment]
Voici la ligne 23: 
URL_MAIN = 'http://www.hd-stream.in/'
Mais c'est toujours vide?

**Comment by TmpName** [comment]
Bizarre, et ca marche via navigateur chez toi ?
Pas de message d'erreur dans les logs ?

**Comment by arzaz** [comment]
Oui ca marche très bien via le navigateur et je n'ai aucun message d'erreur, mais via vstream aucun film ne s'affiche c'est complètement vide?

**Comment by TmpName** [comment]
Dans toutes les categories ?

**Comment by arzaz** [comment]
Après test:
Films Nouveautés --> Vide
Films Genres --> Vide
Films Sources --> Accès a tous les films
C'est vraiment bizarre j'arrive seulement a avoir la liste des films que par la catégorie Films Sources? Peux-tu corriger ce probleme

**Comment by TmpName** [comment]
??
J'ai pas "films sources", le seul qui marche pas chez moi c'est "Films le plus vus"

**Comment by arzaz** [comment]
Comme déjà expliqué un peu plus haut, c'est ok avec "toute les sources" mais pourquoi pas avec Films nouveautés et films genres?

**Comment by TmpName** [comment]
Mais tu passses par ou ?
Home/Film/film sources/site
ou
Home/toute les sources/site 

Car moi je n'ai pas "Film sources" dans les menu du site en passant par "toutes les sources"

**Comment by arzaz** [comment]
Quand j'accede a Films j'ai plusieurs rubriques voir le screen shot
![screenshot000](https://cloud.githubusercontent.com/assets/9026875/13549142/39db7b22-e300-11e5-8b13-eb73155f3742.png)

**Comment by Kodigoal** [comment]
Ca liste de mon côté par Films/Films Nouveautés/, pas de bug.

**Comment by Kodigoal** [comment]
Ca liste de mon côté par Films/Films Nouveautés/, pas de bug.
Edit:  le site f ilm-str eaming co est de retour en ligne ... :p ancienne version du fichier a l'air ok encore.

**Comment by TmpName** [comment]
Le prb c'est que la mise a jour a été lancé, je pense que je vais juste laisser une ligne a activer/desactiver pour passer de l'un a l'autre en 5s.

**Comment by Kodigoal** [comment]
Ok merci.
sinon tu as décommenté pour tes tests la petite partie qui
crée un fichier test, mais sous android ca fait erreur en voulant lister.
Je sais pas si tu en as encore l'utilité?

**Comment by TmpName** [comment]
Mer2.
Je corrige de suite, je compte pas le nombre de fois ou LordVenom a du me virer ces lignes.

**Comment by TmpName** [comment]
C'est j'ai trouve pour frenchstream, en fait les DNS resolver courant ont du recevoir une demande pour bannir son ip, du coup on arrive sur une page d'erreur.

Python permet de donner soi meme l'ip plutot que de le demander aux serveur dns.
