### ISSUE TITLE
marques pages

### ISSUE THREAD

**Issue by fredo04** [LordVenom/venom-xbmc-addons#315]
Bonjours.
Depuis la dernière mise à jours je n'ai plus accès aux marques pages que ça sois pour les films les séries et tout le reste. Quand je clic sur marque pages film rien ne se passe. Si j'en rajoute ils sont bien comptabilisé et ça me dis bien que ça était rajouté mais quant je vais dans la section marque page film ça tourne en boucle et puis plus rien. Je suis sur box Android et spmc.m

**Comment by TmpName** [comment]
Ha ?
Ca c'est bizarre, il n' y a eu aucune modification dans cette partie depuis plusieurs mois.
Si tu n'as pas de trucs importants, tu as essayé de "reseter" la database de VStream ?

Tu n'aurais pas un message d'erreur dans les logs ?

Si je te fais passer un fichier bidouille, tu serais capable de remplacer un des tiens par celui la ?

**Comment by TmpName** [comment]
Ha oui, il se peut que sur certains sites les favoris ne partent pas au bon endroit donc verifi bien dans toutes les categories.

**Comment by fredo04** [comment]
Bon ben du coup j'ai tout désinstallé et réinstallé ( spmc sur box Android). Favoris bien pris en compte. Maintenant j'ai un nouveau problème, les résumés sont pratiquement tous en anglais ou alors ils sont manquants. J'ai bien réglé en français dans les options des métadonnées.

**Comment by TmpName** [comment]
Tu trouveras les infos ici > https://github.com/LordVenom/venom-xbmc-addons/issues/317#issuecomment-194539669

**Comment by fredo04** [comment]
Ok merci. Grâce à ça tout marche merci.
