### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by Hrxn** [LordVenom/venom-xbmc-addons#316]
Hi,

very interesting project, thank you! 

Just one thing: Under which license is the source covered?

Just to avoid any future misunderstandings ;-)

**Comment by TmpName** [comment]
Good question, the license isn't in all files but you can find this file at the root, the name isn't COPYING but LiCENSE
https://github.com/LordVenom/venom-xbmc-addons/blob/master/plugin.video.vstream/license.txt.

The owner can confirm that, but for me all the project was on GPU rules. IDK what you want to do, but like for other open source code from kodi addon, I don't think you can have misunderstandings if you use the GPU rules.

**Comment by LordVenom** [comment]
Oui. En gros cette licence autorise la copie, la modification, seul limite d usage si vous distribuer une copie modifie elle doit être en licence GNU donc gratuite.
