### ISSUE TITLE
info metahandler

### ISSUE THREAD

**Issue by spcxsat** [LordVenom/venom-xbmc-addons#317]
Bonjour,

J'ai refait mes installation sur mon PC Windows 10 et sur ma box Android Nvidia Shield tv

Le soucis sais que je n'es plus les info des films en fr, j'en quelque une en anglais mais plus rien en fr et j'ai toujours cette erreur dans kodi

19:35:25 T:8844  NOTICE: metahandler: No SQLite rows requiring update
19:35:25 T:8844   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized

Pourtant j'ai l'impression que je les bien configurer je ne comprend pas si vous pouvez m'aider sa serais super sympa

    <setting id="db_address" value="" />
    <setting id="db_name" value="video_cache" />
    <setting id="db_pass" value="" />
    <setting id="db_port" value="" />
    <setting id="db_user" value="" />
    <setting id="meta_folder_location" value="special://profile/addon_data/script.module.metahandler/" />
    <setting id="tmdb_backdrop_size" value="original" />
    <setting id="tmdb_language" value="Français (fr)" />
    <setting id="tmdb_poster_size" value="w342" />
    <setting id="tvdb_language" value="Français (fr)" />
    <setting id="use_remote_db" value="false" />

**Comment by TmpName** [comment]
La je ne peux pas te dire, essayes sur le forum de kodi, mais tu n'est apparement pas le seul
http://forum.kodi.tv/showthread.php?tid=260741

Vu leur reactivite, tu peux aussi essayer de changer le scrapper, prend en un autre que TMDB.

Chez moi il passe en anglais quand il ne trouve pas en francais.

**Comment by spcxsat** [comment]
Tous d'abord merci pour ta réponse. 

Et comment on fait pour changer le scrapper ? 

Car vstream n'es pas configurer pour fonctionner avec metahandler par défaut il y a un fichier à modifier à un endroit car si non TMDB fonctionne très bien avec mes fichier local sais juste avec vstream que sa déconne. 

Merci pour vos réponses.

**Comment by TmpName** [comment]
Ha ok, j avais pas compris, si ca fonctionne avec tes fichiers locaux, c'est que le bug ne doit pas venir de metahandler.
En attendant, je viens de tester, meme probleme que toi, par contre j'ai jamais touche aux metas donc peux pas encore te dire si c'est normal ou pas.

**Comment by TmpName** [comment]
Edit j'ai trouvé
 >>{"status_code":10,"status_message":"Suspended API key: Access to your account has been suspended, contact TMDb."}

**Comment by spcxsat** [comment]
Ah OK et il y a une façon de modifier ça ou de corriger le souci ?

**Comment by TmpName** [comment]
Ca je sais pas, j'ai pas lu tout le post, certains parlent d'une mise a jour du plugin, mais y en a toujours un chez qui ca ne marche pas .... Et vu leur reactivité, perso je m'attend pas a du mieux avant 2/3 mois.

**Comment by spcxsat** [comment]
Il y a t'il dans vstream une façon de changer metahandler et de le remplacer direct par tmdb qui lui pour nous nous intéresse plus vue que les résumer sont en Fr et de plus il es activer en native dans kodi. 

Si tmdb peu nous donner résumer jaquette et fafa..  pour les fichiers locaux peu t'il le faire pour ceux de vstream 

Car choisir un film sans résumer et jaquette sais pas toujours évident quand on suis pas les sortie lol. 

Merci d'avance pour le temps et les essais pris.

**Comment by TmpName** [comment]
Meme sans les meta activée tu peux avoir les resumé (et surtout les jaquettes) sur pas mal de sources. Change l'affichage pour tester.
Tu as aussi la focntion "information" en menu contextuel, mais ca doit etre en anglais aussi maintenant.

Pour le bug, je dis peut etre une betise, vu que c'est pas mon cote, mais en fait Vstream utilise une librairie fournie dans kodi a la base, donc Vstream est dependant de elle, elle ne doit pas etre la meme que celle utilisée par Kodi pour ses meta a lui. Je sais comment changer celle de kodi mais pour Vstream a mon avis c'est mort.

**Comment by spcxsat** [comment]
OK merci beaucoup vais regarder comme tu dit si sa peu dépanner.

**Comment by LordVenom** [comment]
Kodi a même supprimer cette extention de leur repo trop utiliser par des addons "dont il ne veulent pas entendre parler".

**Comment by spcxsat** [comment]
Peut-être pour ça que cela ne fonctionne plus.

**Comment by LordVenom** [comment]
Juste leur ID c'est fait bannir de TMDB, j'ai pas trouver de nouvelle version et impossible de modifier leur ID depuis vStream.

**Comment by spcxsat** [comment]
OK.
Peut-être réfléchir si il y a une possibilité de changer de client qui fonctionnerait, si sais possible bien sûr.

**Comment by TmpName** [comment]
Ha oui je suis con, la solution est simple.
Tu t inscrit toi meme sir le site de TMDB et tu prend une cle pour toi, il te suffira de remplacer la leur par la tienne, j'ai pas été voir mais je pense que c'est gratuit. LordVenom a la sienne pour la partie de Vstream "recherche visuelle"

**Comment by spcxsat** [comment]
Heu OK je veux bien essayer. 

Mais cette clé, Je la place où dans quelle fichier la je suis un peu paumer.

En tous cas merci si ça peu être une solution.

**Comment by spcxsat** [comment]
Voilà je me suis inscrit et j'ai eu mon API key 

Maintenant quoi en faire lol, Je suis pas une bête en développement.

**Comment by TmpName** [comment]
Dans Kodi\addons\script.module.metahandler\lib\metahandler
Fichier metahandlers.py
ligne 96

Je peux me tromper mais si il y a le meme nombre de characteres ca doit etre celle la.

**Comment by spcxsat** [comment]
Ok je suis au taff le je regarderais ca ce soir ou demain matin

la keys fait 32 characteres elle es en hexadécimal

**Comment by spcxsat** [comment]
Yes sa fonctionne c'étais bien celle-ci

franchement mille merci, je trouve ça super pratique pour avoir le résumer sur tous les films

**Comment by TmpName** [comment]
Mais normallement, tu devrais avoir le resume sans ca sur plus de la moitier des sites.

**Comment by spcxsat** [comment]
Oui je sais bien mais comme ça je les es sur tous :).

Tien un autre petit bug t'en que l'on y es qui concerne les méta.

Je sais pas si je devrais ouvrir un deuxième poste pour ça ou non. 

Depuis la version de Kodi 16 que sa soie sur Windows ou Android on peu plus configurer les préférence pour les méta,  quand on clique dessus dans les paramètres ça ce grise et on ne rentre plus sans le menu alors que ça fonctionne très bien avec kodi 15.2

Enfin sais pas très grave sais juste pour info.

**Comment by TmpName** [comment]
Ha j'avais pas vu, suis encore sous kodi 15.2.

**Comment by LordVenom** [comment]
Ha mince faut vraiment trouver un autre client, je suis aussi en Kodi 15.2.

**Comment by spcxsat** [comment]
Enfin ça fonctionne quand même avec la version 16 de Kodi ou même la 17 qui es en alpha. 

Il suffi juste d'éditer les fichier à la main, sais juste que l'on peu plus les configurer direct de l'interface de vstream.

**Comment by TmpName** [comment]
Lol, on va laisser le topic en "bug" pour memoire, le premier qui passe sous kodi 16 jettera un oeuil.

**Comment by fredo04** [comment]
slt Spcxsat, j'ai le même souci que toi. Je viens de m'inscrire sur imdb. Comment récupérer la clé api ?

**Comment by spcxsat** [comment]
Hello,

sais sur TMDB qu'il faud s'inscrire tu va dans ton compts et tu fait la demande de l'API KEY

tu donne le nom d'une application bidon que tu developpe pas url car biensur en developpement et tu valide

et voila il te la donne de suite

**Comment by fredo04** [comment]
Ça y est, compte sur tmdb ouvert et clé api modifiée dans Kofi. Nickel tout fonctionne. Merci pour cette astuce.

**Comment by LordVenom** [comment]
Problème résolut pour le moment sur la bêta.Reste le bug pour la version 16 de Kodi.

**Comment by fredo04** [comment]
Quelle serait la version de Kofi la plus compatible pour vstream ?

**Comment by TmpName** [comment]
Le but du jeu, c'est de faire en sorte que la meilleure soit la derniere.
La cle de l' API ne marche plus sur toute les version, a voir si la team kodi va corriger ca, ou si c'est a nous de refaire cette partie de notre cote.
Pour le moment corriger cette partie pour la V16 ne servirait a rien car la team kodi n'a toujours rien fait pour le probleme de cle.

**Comment by TmpName** [comment]
Alors je vient de passer a kodi V16, et je peux acceder aux metahandler en cliquant sur "parametres des metadonnées", je sais pas si il y a eu une MAJ depuis, mais le menu fonctionne chez moi du moins.

**Comment by spcxsat** [comment]
Hello, 

Ba je sais pas moi j'ai toujours le même problème...  peut-être un bug de chez moi, mais bizarre que ça me le face sur mes deux installation

**Comment by TmpName** [comment]
Ben en fait c'est bizarre, quand tu cliques y a un freeze, tu te deplaces vers la droite ou la gauche et le menu chnage.

**Comment by spcxsat** [comment]
Mais sais rien on peu configurer metahandler direct dans les extension de kodi 
Après on l'active avec vstream et ça marche
