### ISSUE TITLE
Ajout Uptobox/uptostream

### ISSUE THREAD

**Issue by Snammx** [LordVenom/venom-xbmc-addons#318]
Salut à tous,

Est-il possible d'ajouter la source uptobox/uptostream?. J'ai un compte premium et j'aimerais faire le lien avec Kodi et mon compte. J'utilise déja Cloudstream en phase de beta test mais pour l'instant il fonctionne uniquement sur PC et non sur Android/Android TV.

Vu que c'est du stream je me permet d'ouvrir un post ici^^.

Merci de vos réponses et votre plugin!

**Comment by TmpName** [comment]
Alors oui et non.
Uptostream est deja en place, on est deja en train de bosser sur les sources de DL comme uptobox, onefichier mais le probleme c'est quelles ne vont marcher que en version limite, on a pas encore rajoute les systemes d'authentification pour les enregistrés.
Apres a 10 euro pour un an j'avou que Upto est tres interessant.

Par contre Cloudstream ne marche que pour l'audio non ?

**Comment by Snammx** [comment]
Non il fonctionne pour les vidéos aussi, la dernier version est compatible avec uptobox/uptostream. Testé OK sur WIN 10. Mais j'aimerais l'avoir sur Android TV aussi mais la ça fonctionne sur mon tél android en 3G/4G mais pas en Wifi... je sais pas pourquoi. Sur l'android tv (freebox mini 4K) ça marche pas du tout. J'ai posté pour prévenir.
En tout cas merci pour la réponse.
J'espère pouvoir faire le lien un jour avec mon compte Upto/Kodi/Scrapper Cine-passion le rêve!...

**Comment by TmpName** [comment]
Honnetement je ne peux rien te garantir, mais un autre user qui bidouille a un projet proche du tiens, et d'ici un mois tu auras peut etre une version avec authentification pour uptostream mais pour "power user" tu vas devoir toi-meme rentrer tes identifiiants dans le fichier python.

Si ca aboutit, je te mettrais une alerte dans ce topic pour tester.

**Comment by Snammx** [comment]
Ok merci!

**Comment by TmpName** [comment]
Avant que j'oublis, tu as le topic ici https://github.com/LordVenom/venom-xbmc-addons-beta/issues/103

Mais pour le moment c'est uniquement si tu as des bases pour bidouiller kodi.

**Comment by Snammx** [comment]
Super merci je vais voir ça! je vais essayer de participer! merci

**Comment by sebi0606** [comment]
bonjour quand je fais streamong uptobox vers uptostream le son est en 2.0 au lieu de 5.1 c'est normal ?

**Comment by TmpName** [comment]
Oui, uptostream baisse la qualitee (video et audio) pour pouvoir le streamer plus facilement.
Mais meme en gratuit uptobox fonctionne, seul probleme si tu changes d'avis en cours de visionnage, il te faut attendre plusieurs minutes pour pouvoir redemarrer un film.

**Comment by sebi0606** [comment]
Merci pour ta réponse

**Comment by huitcentsix** [comment]
Salut à tous, alors voilà, c'est peut être anodin pour vous mais je suis novice et tourne sur un Ras pi3 / XBMC / LibreELEC / Vstream (dernières versions pour tout). Tout fonctionne à merveille et voici ma question, après acharnement sur google sans réponses... 

Comment fait-on pour entrer son compte UPTOBOX pour ne plus avoir les contraintes de limitation alors que je paye un compte ! Faut il un addon via kodi ? ou dans les setting ? (pas trouvé)  .. Bref je ne comprends pas grand chose c'est sûr et je m'en excuse. Je veux juste profiter de mon pi3 / Vstream / zone telechargement sans limites (comme sur pc) :) 

Merci (si c'est possible)

**Comment by TmpName** [comment]
cf ici > https://github.com/LordVenom/venom-xbmc-addons/issues/455
