### ISSUE TITLE
Ajout mega-stream.fr

### ISSUE THREAD

**Issue by Snammx** [LordVenom/venom-xbmc-addons#319]
Salut,

Pouvez-vous ajouter la source http://mega-stream.fr/ svp ? Il y a beaucoup de contenu et sourtout HD sur openload. Çà serait top! Merci!

**Comment by TmpName** [comment]
Il est deja repere et mit en todolist https://github.com/LordVenom/venom-xbmc-addons/issues/319

Mais la pour le moment pas de nouvelles sources prevues.
