### ISSUE TITLE
Mise à jour film-streaming.co 

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#320]
bonjour.... je suis de retour après quelque mois d'absence sur le github, j'ai reçu ma première boite 4k Vu+ solo il y a deux semaines aprés les tests rien à dire que c'est une merveille est un monstre en même temps j'ai pu accéder au contenu de vstream grâce a l'addon xbmc launcher l'interface graphique le menu le zapping incroyable!..

j'ai corrigé la source film-streaming.co maintenant tout les lien marche
et j'ai ajouter l'option aller a la page 
les liens son crypter par un document texte unescape
pour lire la video j'ai just ajouter une ligne aprés la Pattern:

http = 'https'

http://pastebin.com/f6GN3iAn

http://pastebin.com/NP69r0L9

Xbmc.log

About JW Player 6.12.4956 (Pro édition)

01:36:01 T:3948  NOTICE: -->Python Interpreter Initialized<--
01:36:01 T:3948  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
01:36:01 T:3948  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
01:36:01 T:3948  NOTICE: 	[PLUGIN] Vstream: Hoster - play h ttp://debrideur-4.film-streaming.co/mp4/aHR0cDovL3VwdG9ib3guY29tL2s0YTFlam9jYmxmYg==-hd.mp4|Referer=ht tp://www.hd-stream.in/standoff-streaming.php
01:36:01 T:3948   ERROR: EXCEPTION: XBMC is not playing any media file
01:36:01 T:3948  NOTICE: 	[PLUGIN] Vstream: Table initialized
01:36:05 T:1704  NOTICE: DVDPlayer: Opening: h ttp://debrideur-4.film-streaming.co/mp4/aHR0cDovL3VwdG9ib3guY29tL2s0YTFlam9jYmxmYg==-hd.mp4|Referer=h ttp://www.hd-stream.in/standoff-streaming.php
01:36:05 T:1704 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
01:36:05 T:6280  NOTICE: Thread DVDPlayer start, auto delete: false
01:36:05 T:6280  NOTICE: Creating InputStream
01:36:06 T:6280  NOTICE: Creating Demuxer
01:36:06 T:1284  NOTICE: Thread FileCache start, auto delete: false
01:36:35 T:6280  NOTICE: Opening stream: 0 source: 256
01:36:35 T:6280  NOTICE: Creating video codec with codec id: 28
01:36:35 T:6280  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
01:36:35 T:6280  NOTICE: Creating video thread
01:36:35 T:6280  NOTICE: Opening stream: 1 source: 256
01:36:35 T:6280  NOTICE: Finding audio codec for: 86018

**Comment by TmpName** [comment]
Merci, mais mauvaise nouvelle, le precedent site, vient de se remettre en marche.
Et comme j'ai pas envis de devoir rechnager tout le code a chaque fois, je vais faire comme sur poypi avant, y aura juste une ligne a changer pour passer de l'un a l'autre, je vais fusionner les 3 codes.

Par contre je risque de faire sauter ta modif pour le next page, car je ne sais pas si c'est la meme sur les deux sites, et la j'ai pas le trop le temps de m y pencher.

**Comment by arzaz** [comment]
Bonjour mino60

Tu as installé quoi comme image sur ta boite 4k (Blackhole, VTI, OPENATV ou autres)
Peut-on installé Kodi 16 sur cette boite? Autrement tu as quoi comme version XBMC ou KODI?
Merci de m’éclairer car je suis très intéressé par cette machine.

**Comment by mino60** [comment]
@arzaz Bonjour j'ai installé l'image Black Hole 3.0.1F j'ai la vertion xbmc 13.2 pré installé sur l'image
pour installer kodi 16 il faux attendre je crois.

**Comment by cocoboy31380** [comment]
J'ai un galaxy S3 et une mini box TV androïd sur lesquels j'ai installé Kodi 16 et 17 l'addon Vstream fonctionne à la perfection, le soucis c'est que sur la version 16 installé aussi sur mon pc on me propose une mise à jour de certains scripts et de certains sites, de cette façon youwatch à pu refonctionner normalement, le soucis c'est que cette proposition de mise à jour ne s'affiche pas sur mon telephone et mon boitier TV, savez-vous d'oùu cela peut-il venir ? (j'ai pu mettre à jour les deux à la main, mais bon si on pouvait lancer directement le téléchargement ca serait beaucoup plus pratique ^^). Merci beaucoup

**Comment by TmpName** [comment]
C'est normal, et c'est fait expres pour eviter l'abus de requete sur Github, C'est un site gratuit, tres efficace, sans pubs, donc a respecter, et d'ailleurs dans le cas contraire LordVenom peut se faire bloquer son compte.

Vstream vérifie les mises a jour tout les 3 jours, la mise a jour de Youwatch s'est faite hier, donc dans max 2 jours tu l'auras aussi sur l'autre plateforme.

**Comment by cocoboy31380** [comment]
OK merci pour les infos ^^ et je confirme pour l'efficacité et le sans pub ^^.
