### ISSUE TITLE
Retour de DPstreaming

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#321]
le site dpstreaming.org et devenu dpstreaming.tv alors pas de Gros Changement don la source, le scripte fonctione trés bien juste une erreur sur la ligne 413 sur showHoster

http://pastebin.com/A77ceF9s

**Comment by TmpName** [comment]
Ha yes bien vu, en plus je l'aimais bien ce site moi, je rajoute de suite.
