### ISSUE TITLE
Youwatch

### ISSUE THREAD

**Issue by ttrd06** [LordVenom/venom-xbmc-addons#322]
Bonjour à l'équipe,

Je viens de voir depuis quelques jours que le resolver youwatch ne fonctionne plus quelque soit les sites proposés. Avez-vous remarqué aussi cette erreur de votre coté ?

Merci

**Comment by TmpName** [comment]
Confirme chez moi, je jete un oeuil

**Comment by ttrd06** [comment]
merci TmpName et bonne journée ! Toujours aussi réactif !
