### ISSUE TITLE
Tv.streaming.ch erreur

### ISSUE THREAD

**Issue by Turk182es** [LordVenom/venom-xbmc-addons#323]
Salut,

Depuis l'actualisation d'aujourd'hui le serveur TV.streaming.ch donne une erreur lorsque j'essaye d'accéder à Tvshow/série VF.

Je crois avoir eu la même erreur lors de la dernière actualisation.

Cordialement 
Stephane

**Comment by TmpName** [comment]
Leur site est HS en ce moment, a suivre.

**Comment by TmpName** [comment]
De nouveau en fonctionnement a ce jours.
