### ISSUE TITLE
Affiche des Films

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#324]
J'ai un problème avec les affiches des films sur la plus part des sites voir ci-dessous:
1/ Zone telechargement
![screenshot000](https://cloud.githubusercontent.com/assets/9026875/13825649/dd229ee4-ebb3-11e5-9eef-fb76b356da37.png)
2/ VoirFilm
![screenshot001](https://cloud.githubusercontent.com/assets/9026875/13825648/dd2003a0-ebb3-11e5-9ca3-1c44ae9e5f57.png)
Kepliz
![screenshot002](https://cloud.githubusercontent.com/assets/9026875/13825647/dd1b07ba-ebb3-11e5-8de3-f4a7c5b2fe3a.png)
C'est quoi exactement le problème?

**Comment by TmpName** [comment]
Pour kepliz, c'est normal, il n y a pas les vignette sur la premiere page (comme sur le site)
Pour voirfil m, la c'est bizarre, les vignettes mettent plus de 20s a apparaitre, et en general ca marche de facon bizarre, je vais jeter un oeuil, mais je pense pas pouvoir faire grand chose.
Pour ZT, le code n'est pas finalise et change plusieurs fois par jour, donc attend un peu, mais pour le moment ca marche chez moi, mais je sais pas si on a le meme fichier (vu le nbre qu'il y a)

**Comment by TmpName** [comment]
Bon j'ai fais quelques test pour voirfilm, leur serveur propose une option pour ne pas retelecharger l'image si elle se trouve deja dans le cache, je pensais que ca venait de la, mais si on selectionne un poster qui ne s'affiche pas, l'image apparait, et re-disparait si on arrette de la selectionner.

Donc soit c'est encore kodi qui deconne, soit on a raté un truc dans Vstream, mais je ne vois aucun message d'erreur, et je ne vois pas ou dans kodi on peut donner 2 images, une pour selectionnée et une autre pour non selectionnee.

**Comment by mino60** [comment]
apparamment tu a un problème de connexion internet on géneral avec une vitesse 2 Mo soi une vitesse de telechargement entre190kb/s et 235kb/s tout les image s'affiche et tu peux lire une vdéo 1080p

http://uprapide.com/images/invite/sans-titre4.png

**Comment by arzaz** [comment]
Bonsoir mino60,
J'ai une connexion de 8 Mo et j'arrive a lire facilement les videos 1080p, mais le problème c'est celui des posters qui ne s'affichent pas?
Pour info je suis sous gotham 13.2 avec la box Prismcube.

**Comment by mino60** [comment]
Par contre moi j'ai kodi16 win7 dell i3  avec 2Mo et je ne trouve aucun problème d'affichage

**Comment by arzaz** [comment]
Par contre avec le site streamzer j'arrive a avoir tous les posters des films.
C'est bizarre?

**Comment by Kodigoal** [comment]
Bonsoir,
testé de mon côté , pas de soucis d'affiches sur voirFilm ou streamzer,
affichage quasi instantanée.

**Comment by TmpName** [comment]
Mais l'histoire du debit, c'est pas bete, pas forcement veant du debit internet, mais de la maniere  dont kodi recupere les images.
Car certaines images mettent plus de 20 a venir, alors que via navigateur c'est direct pour moi.
Kodi 15.1

**Comment by TmpName** [comment]
Et je vient de tester sur Exodus, meme probleme, donc ca me rassure c'est pas Vstream ^^

**Comment by TmpName** [comment]
J'ai peu etre une solution a tester pour toi.
Va dans "addon_data" et supprime (ou change le nom) du repertoire "script.module.metahandler", ferme tout et redemarre.

**Comment by arzaz** [comment]
Je viens de faire le test, mais sans aucun résultat toujours le meme problème.

**Comment by TmpName** [comment]
Ha ?
Chez moi ca a marche, c'est dans ce repertoire http://kodi.wiki/view/Userdata ?
Teste avec zonetelechrgment.
