### ISSUE TITLE
source ZOPAP

### ISSUE THREAD

**Issue by raslittle** [LordVenom/venom-xbmc-addons#325]
Bonjour,

ZOPAP.COM est une très bonne source de film HD.
Y a-t-il possibilité de le rajouter?

**Comment by arzaz** [comment]
ZOPAP = KEPLIZ

**Comment by raslittle** [comment]
Thank and Sorry ;)

**Comment by TmpName** [comment]
Lol, pas de soucis, mais ses sites ont tellement de clones qu'on voit le meme post toute les semaines.
