### ISSUE TITLE
Venom ?! ce message est pour toi ?! que va t'il devenir de VStream ?!

### ISSUE THREAD

**Issue by stormz85** [LordVenom/venom-xbmc-addons#326]
Hello mec !!

je viens de tombé sur cette news !! va tu te tourner vers cette nouvelle application ? 

http://www.phonandroid.com/kodi-android-abandonne-spmc-releve.html

**Comment by stormz85** [comment]
Re,

alors j'ai testé l'application du mec ;) c'est la même que Kodi sauf qu'il est dans sont coté désormais.
donc VStream ca devrais passé sans soucis.

Voila le site en question si tu veux tester.
http://spmc.semperpax.com/

je suis au boulot la , je peut pas trop tester.

**Comment by LordVenom** [comment]
Bonjour, Pour moi vstream n'est pas fait pour android, je cible plus les pc et mini pc de salon qui sont pour moi plus performant mais merci pour la news.
