### ISSUE TITLE
flashx h.s ?

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons#327]
Bonjour juste pour signaler que le hoster semble h.s

**Comment by FreeFighter77** [comment]
Bon j'ai trouve changement d adresse de .cc a .host,le met a jour sur la beta ;) Ptit coucou a venom et tmpName :)

**Comment by TmpName** [comment]
Hello ^^
J'avais prevu ca quand j'ai fais le code mais le lien passe de flashx.tv a www.flashx.tv a www.flashx.host.
3 redirections pour le meme lien .....
En tout cas merci
