### ISSUE TITLE
Recherche avec Zone telechargement

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#328]
Avec la nouvelle version 4.0 at après avoir coché dans le menu vStream recherche zone téléchargement, mais malheureusement quand je lance une recherche d'un film tous les sites affichent le résultat mais non pas zone téléchargement? S'agit-il d'un bug?

**Comment by TmpName** [comment]
Ben, je crois que de memoire, on a pas prevu ca ^^.
En fait il y a une recherhce differente pour films / serie / animes, donc ca marche via la source, mais pas code pour la recherche generale.
Je jete un oeuil de main.

**Comment by TmpName** [comment]
Corrige (normalement), mais ce ne sera pas les memes resultats que en passant par les recherches de la source.
