### ISSUE TITLE
hd stream in

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#329]
Merci de verifier pourquoi le site hd stream in est vide dans Films nouveautés?
Par contre les films s'affichent dans la rubrique Films HD

**Comment by mino60** [comment]
effectivement il ya deux Pattern il faux ajouté: 
if et else:

essayé ce script

http://pastebin.com/xkGFHzz6

pour info dpstreaming.org fonctionne toutjour

**Comment by TmpName** [comment]
Moi j'ai pas de prbs, tu passe par ou ?
Moi, "toute les sources" "film nouveautee"

**Comment by arzaz** [comment]
@mino60 je viens de faire le test, mais toujours le meme problème c'est vide

@TmpName voici ce que j'ai comme menu:
![screenshot000](https://cloud.githubusercontent.com/assets/9026875/14151188/a919de9a-f6a4-11e5-9e8e-f8ab80e08c26.png)
Merci de voir c'est quoi le problème?

**Comment by arzaz** [comment]
@TmpName 
J'ai déjà eu le meme problème avec Frenchstream, mais je ne sais pas comment tu as pu réglé le problème? Voir ci-dessous:



Après test:
 Films Nouveautés --> Vide
 Films Genres --> Vide
 Films Sources --> Accès a tous les films
 C'est vraiment bizarre j'arrive seulement a avoir la liste des films que par la catégorie Films Sources? Peux-tu corriger ce probleme

 



@TmpName 


  Add your reaction  
Collaborator 
TmpName  commented 25 days ago  




Edit:
 Passes par "toute les sources", le derniere icone, pour tester.
 La je suis desole, mais ca marche chez moi, et sans message d'erreur je ne vois pas du tout ce qui deconne chez toi.



@arzaz 


  Add your reaction    
   
 
arzaz  commented 25 days ago  




Comme déjà expliqué un peu plus haut, c'est ok avec "toute les sources" mais pourquoi pas avec Films nouveautés et films genres?

 



@TmpName 


  Add your reaction  
Collaborator 
TmpName  commented 25 days ago  




Mais tu passses par ou ?
 Home/Film/film sources/site
 ou
 Home/toute les sources/site 

Car moi je n'ai pas "Film sources" dans les menu du site en passant par "toutes les sources"



@arzaz 


  Add your reaction    
   
 
arzaz  commented 25 days ago  




Quand j'accede a Films j'ai plusieurs rubriques voir le screen shot
screenshot000

**Comment by TmpName** [comment]
Essaye en redemarrant le smilblick, je sais que (pour avoir deja galere avec) la page home, ne se remet jamais "a zero" toute seule une fois chargee, peut etre que sur ton systeme c'est aussi le cas pour le second menu.

Tu n'as rien dans les logs ?
Pour nouveautee
>>[PLUGIN] Vstream: Load Plugin: full_stream_org
[PLUGIN] Vstream: Load Plugin: hd_stream_in
[PLUGIN] Vstream: Load Plugin: kepliz_com
......
[PLUGIN] Vstream: Load Plugin: seriefr_com

**Comment by arzaz** [comment]
Ci-joint le log.

[Log.txt](https://github.com/LordVenom/venom-xbmc-addons/files/196136/Log.txt)

**Comment by TmpName** [comment]
Franchement je ne vois rien d'anormal a part ca
>>DEBUG: Saving fileitems [plugin://plugin.video.vstream/?function=movieNews&sFav=movieNews&site=cHome&siteUrl=http%3a%2f%2fvenom&title=%5bCOLOR%20red%5dFilms%20Nouveaut%c3%a9s%5b%2fCOLOR%5d]

Moi j'ai rien qui ressemble a ca sur ma machine.

Ca ressemble vraiment a une memorisation, tu as essayé de vider les caches, et de redemarrer ?

**Comment by mino60** [comment]
@arzaz attention il ya deux sites relier entre eux hd-stream.in et film-streaming.co
1_ sur hd-stream.in il ya juste deux section qui marche sur ce site
Top film = films les plus vus
les film = tout les films
sur le site quand tu clic sur genres ou nouveauté tu ai dirigé sur le deuxième site
mème le streaming ce fais sur le site film-streaming.co

essayé ce script avec j'ai les deux section hd-stream.in top film et les film

http://pastebin.com/g8hYzKa4
