### ISSUE TITLE
Option : Dossier de Téléchargement

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#330]
Hello,
D'abord je voudrais vous remercier pour tous les efforts que vous faites pour maintenir cet Add-on à jour.
Ensuite je voudrais bien faire un don pour participer un peu alors merci d'avance de me communiquer votre adresse Paypal.
Et pour finir : Une petite remarque perso : Précédemment les options du plugin permettaient d'indiquer la destination par défaut des download : Ce n'est plus possible et c'est bien dommage :)
A bientôt et encore merci
++

**Comment by TmpName** [comment]
Ha ?
Moi je l'ai encore, dans "outils", avec une faute de frappe en plus.

**Comment by mino60** [comment]
pour faire un don symbolique ici

https://github.com/LordVenom/venom-xbmc-addons#faire-un-don
Faire un Don!

PayPayl donate button

Bon Film ++

**Comment by canopre** [comment]
"Moi je l'ai encore, dans "outils", avec une faute de frappe en plus."

Désolé : Ch'ui vraiment une burne !
Il est bien là !

Ducoup j'ai aussi envoyé ma petite participation et j'en profite également pour vous remercier pour votre super ré-activité : Vous assurez les gars ! Thanks again !

**Comment by LordVenom** [comment]
Merci, du coup il faudrait aussi que @TmpName  y mette aussi sont paypal.

**Comment by TmpName** [comment]
C'est tres sympa merci, mais meme si a force de temps j'ai deja du modifier plus de la moitie du code, cela reste ton projet, ce qui m'interesse c'est le code, et la "maintenance", je prefere te laisser gerer tout ce qui est "administratif".

Ceci dit, la je me tate vraiment pour prendre un compte sur uptobox, donc si vraiment un jour tu as un exces de dons, y a moyen de s'arranger ^^.
Par contre Paypal n'est pas accepté sur ces sites, ca coute de l'argent de refaire transferer de l'argent d'un compte paypal vers un compte bancaire ?

**Comment by LordVenom** [comment]
Dsl de l'attente, je sais pas je crois pas mais tu verras bien donne ton paypal tu verras ceux que tu peux faire ensuite :)

https://www.paypal.com/fr/webapps/mpp/paypal-fees

**Comment by TmpName** [comment]
Bon laisse tomber la galere, en fait j'avais mon vrai Nom Prenom qui apparaissaient, donc du coup j'ai refais un compte avec mon pseudo d'ici.
h ttps://ww w.paypal.me/TmpName
Par contre c'est juste pour toi, tu en fais ce que tu veux, mais je tiens pas a rajouter un bouton perso en acceuil, sinon dans quelque temps ton github va ressembler a la page d'acceuil d'amazon.

**Comment by LordVenom** [comment]
Bizarre github me dit qu'il y a un nouveau message mais y en a pas ?

**Comment by TmpName** [comment]
Wé lol, c'est surement moi, j'ai voulu te passer mon paypal, mais apres j'ai vu que ca donnait le vrai nom, prenom et ville.
Donc j'ai voulu en faire un juste pour ici, puis j'ai laissé tomber.
Ca aurait ete marrant que le temps que je passe ici me serve pour me payer quelques downloads, mais vu que tous refusent paypal, c'est moins interessant.

En tout cas merci pour la proposition, mais j'ai pas envie de mettre en place une usine. C'est juste des dons de remerciement, c'est pas comme si tu gerais une multinationale.
C'est tres sympatique, mais l'ambiance actuelle me convient, pas envie de me prendre la tete.

PS: je deconne, je viens de me faire embaucher a plein temps sur Exodus.

**Comment by TmpName** [comment]
Pour ceux qui reflechissent trop, bien sur je deconne pour exodus
