### ISSUE TITLE
problème liste vide mangacity

### ISSUE THREAD

**Issue by danielpfi** [LordVenom/venom-xbmc-addons#331]
Salut,

Super application et fellicitatio ,
Depuis quelques jours sur la source mangacity, il y a plus de source pour paw patrol. J'arrive bien aux épisodes mais dedans il y a aucun lien. 

Cordialement

**Comment by danielpfi** [comment]
Je suis en version 0.3.9

**Comment by TmpName** [comment]
Tu n'as pas un lien dans la page d'aceuil de Vstream pour une mise a jour des sources ?
La je viens de tester la v 4.0 et j'ai a chaque fois un lien pour allmyvideos fonctionnel.
Par contre le lien vers openload lui n'apparait pas.

**Comment by danielpfi** [comment]
La MAJ des sources Ok, mais j’ai la version 3.9.

Et j’ai toujours pas de lien.

 

 

De : TmpName [mailto:notifications@github.com] 
Envoyé : dimanche 3 avril 2016 16:56
À : LordVenom/venom-xbmc-addons
Cc : danielpfi
Objet : Re: [LordVenom/venom-xbmc-addons] problème liste vide mangacity (#331)

 

Tu n'as pas un lien dans la page d'aceuil de Vstream pour une mise a jour des sources ?
La je viens de tester la v 4.0 et j'ai a chaque fois un lien pour allmyvideos fonctionnel.
Par contre le lien vers openload lui n'apparait pas.

**Comment by TmpName** [comment]
Ben meme avec la 3.9, la derniere MAJ date de 6 jours, donc normallement on devrait avoir les memes fichiers.
Je viens de faire une MAJ qui va te rajouter les liens openl oads, mais elle risque de mettre quelques jours a apparaitre chez toi.
Tu peux essayer de remplacer toi meme le fichier.

Ca te le fait a tout les episodes ? En fait moi j'en ai testé juste 4/5 au hazard.

Sinon la V4 ne marche pas chez toi ?

Edit : ha oui le host allmyvideo n'a été rajoute il n'y a que 11 jours donc avec la V4, ce host n'est pas present sur la V3.9.

Installe plutot le repo, comme ca, Vstream se mettre a jour tout seul.
>> https://github.com/LordVenom/venom-xbmc-addons/blob/master/repo/repository.vstream/repository.vstream.zip

**Comment by danielpfi** [comment]
Je vais installer la v4 et je te tiens au courant

 

De : TmpName [mailto:notifications@github.com] 
Envoyé : dimanche 3 avril 2016 19:36
À : LordVenom/venom-xbmc-addons
Cc : danielpfi
Objet : Re: [LordVenom/venom-xbmc-addons] problème liste vide mangacity (#331)

 

Ben meme avec la 3.9, la derniere MAJ date de 6 jours, donc normallement on devrait avoir les memes fichiers.
Je viens de faire une MAJ qui va te rajouter les liens openl oads, mais elle risque de mettre quelques jours a apparaitre chez toi.
Tu peux essayer de remplacer toi meme le fichier.

Ca te le fait a tout les episodes ? En fait moi j'en ai testé juste 4/5 au hazard.

Sinon la V4 ne marche pas chez toi ?

Edit : ha oui le host allmyvideo n'a été rajoute il n'y a que 11 jours donc avec la V4, ce host n'est pas present sur la V3.9.

Installe plutot le repo, comme ca, Vstream se mettre a jour tout seul.

https://github.com/LordVenom/venom-xbmc-addons/blob/master/repo/repository.vstream/repository.vstream.zip
