### ISSUE TITLE
Realdebrid

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#332]
Bonjour serait-il possible de mettre realdebrid dans vstream pour pouvoir l'utiliser avec zone de telechargement ? Merci d'avance pour votre réponse

**Comment by TmpName** [comment]
Franchement je sais pas.
A voir si il y a moyen de faire un truc rapide avec juste une option a activer et utiliser la librairie urlresolver, donc ce ne serais pas nous qui gererions le smilblick.

Car perso, c'est toujours en panne, beacoup de taff a maintenir, et suis pas fan, c'est assez cher et vu qu'on utilise pas purevid (c'est celui qui est le plus souvent HS sur RD) un abonnement a uptobox est plus pratique, moins cher (meme pas 1 euro par mois) marche tres souvent et est a chaque fois present dans la liste d hebergeur.

A voir.

**Comment by sebi0606** [comment]
Merci pour ta réponse, justement si tu peux faire un truc rapide avec urlresolver ça serait génial pour ceux possédant déjà un compte real debrid merci encore pour tout le boulot

**Comment by mino60** [comment]
Moi j'ai un compte sur uptobox (user inscrit)  j'ai suivi une astuce pour devenir premium et du coup j'ai gagné 10 pts on deux minute maintenant je suis primium pendant un mois sur uptobox

https://www.youtube.com/watch?v=FQi0Xfdwz2k

**Comment by TmpName** [comment]
Bon j'ai rajoute sur la beta (pas contre faudra DL tout le paack, y a des fichiers partout), dans la partie premium une case a cocher pour passer par UrlResolver.
Tu coches la case et configure l'UrlResolver, donc tu pourras utiliser les Debrideurs.

Par contre Vstream ne gere pas du tout cette partie, eg Youwatch n'a pas l'air de marcher.

**Comment by sebi0606** [comment]
Merci TmpName pour ce rajout ;)
Par contre je n'arrive pas à installer la bêta message d'erreur à chaque fois

**Comment by TmpName** [comment]
C'est pour les bidouilleurs, dsl, pas de methode standard, faut etre bourrin.
Le plus simple, telecharge l'archive complete au format ZIP et extrait la par dessus celle de Vstream officielle.

**Comment by sebi0606** [comment]
j'ai fait la manip que tu m'as expliqué mais toujours le message d'erreur 
J'attendrai que tu passes l'option urlresolver en finale pour pouvoir en profiter merci en tous cas

**Comment by TmpName** [comment]
C'est quoi le message d'erreur ? Une erreur d'installation ou de fonctionnement ?
J'ai pu zapper un truc.

Le soucis c'est que j'aimerais bien que quelqu'un la teste avant de faire ca en officiel.

**Comment by sebi0606** [comment]
quand je lance le zip j'ai le message échec de l'installation de l'extension à partir d'un fichier

**Comment by TmpName** [comment]
Le zip ne se lancera pas, il faut l'extraire et remplacer les anciens fichiers par les nouveaux.

**Comment by sebi0606** [comment]
C'est ce que j'ai fait j'ai mis les nouveaux fichiers de la bêta dans le zip de la version stable mais j'ai quand même le message d'erreur

**Comment by TmpName** [comment]
ha ?
Me faudra faire un test complet alors des que j'aurais fais le tris des miens.

**Comment by sebi0606** [comment]
En cas si tu peux me mettre sur un lien Dropbox la bêta que je peux installer sans le message d'erreur je te ferais les retours par rapport à urlresolver

**Comment by sebi0606** [comment]
TmpName j'ai réussi à faire fonctionner la bêta 
J'ai utilisé Winzip sur Mac je test realdebrid et je te dit si ça fonctionne ^^

**Comment by sebi0606** [comment]
eh bien bravo realdebrid fonctionne parfaitement 
Chapeau tu peux le passer dans la version finale c'est un gros plus pour l'extension ;)

**Comment by TmpName** [comment]
Ok, merci.
Je rajoute la mise en forme, et je valide.
Par contre, pour quelques jours, evite de faire des mises a jour via l'icone du menu d'acceuil de vstream, sinon ca va te remplacer certain fichiers de la beta par ceux de l'officielle, et provoquer des bugs.
C'est le temps que je finisse et transfere le fichier en question

**Comment by sebi0606** [comment]
No problemo merci à toi

**Comment by sebi0606** [comment]
Pour info apparement si compte realdebrid sans etre premium les streams 1Fichier
AllMyVideos 
Cloudtime 
HugeFiles 
Mediafire 
Mega Mega
Megashares 
NowDownload 
NowVideo 
Oboom 
SoundCloud 
Uplea 
Uploadable 
UploadC
Uptobox 
Youtube 
Zippyshare 
Sont gratuit à vérifier

**Comment by TmpName** [comment]
Pour le peu que j'en ai vu, il ne sont gratuit que durant les happy hours, alors que pas mal sont gratuit tout le temps, ou avec des limites de temps.
Honnêtement, pour moi ces debrideurs sont juste une arnaque, a moins de passer sa vie sur certains sites tournant a coup de purevid par exemple.

**Comment by sebi0606** [comment]
Je pensais comme toi mais je dois dire que depuis que j'utilise en compte premium realdebrid je ne pourrais plus m'en passer
