### ISSUE TITLE
Serie zone de telechargement 

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#333]
Bonjour certaines series exemple buffy contre les vampires saison 4 les épisodes sont regroupés derrière un lien dlprotect mais impossible de les lires 
J'ai vérifié ils sont bien là mais ne se lancent pas 
Merci d'avance pour votre réponse

**Comment by TmpName** [comment]
Ha oui, il y a un probleme ici, 2 meme.
1 - uptobox est HS en ce moment
2 - on affichait uniquement les liens premium car pour les gros fichiers les lien non premium etaient des morceaux  de film au format rar, mais dans ce cas c'est l'inverse, les rars sont dans les liens premiums

**Comment by sebi0606** [comment]
Exactement les épisodes sont dans 1 fichier par épisode et ce pour beaucoup de serie
d'où l'intérêt aussi de voir à intégrer real debrid car uptobox efface souvent les fichiers aussi plus que 1 fichier.com ou uploaded...
Merci pour ta réponse

**Comment by TmpName** [comment]
uptobox efface rarement les fichiers, j'ai fais des tests sur plusieurs sites, dans 95/100 des cas il y a toujours le lien uptobox.
Sinon je suis en train de rajouter une option pour passer par l'urlresolver, juste une case a cocher, et Vstream passera par le resolver (et donc tout les debrideurs inclus avec), mais par contre on ne gerera plus rien.

Sinon je viens de mettre a jour ZT (uniquement sur la beta pr le moment), pour les films j'affiche que les premiums et les serie tout sauf les premiums.
Je laisse en test quelques jours avant de passer la modif. Mais ca marche pour buffy.

**Comment by sebi0606** [comment]
Merci pour cette réactivité et pour ce superbe Addon
