### ISSUE TITLE
Idée d'amélioration

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#334]
Hello,
J'ai une idée qui permettrait de simplifier l'utilisation de l'Addon : Ma Doudou galère avec toutes les options du Menu Contextuel :

Elle utilise juste "Information" et 'Telecharger"

J'ai essayer de modifier ce menu mais c'est imbitable pour une truffe de mon genre.

Alors je me demandais si dans les options ca ne serait pas possible de configurer ce menu contextuel pour n'afficher que les options utiles ?

Merci d'avance pour votre réponse,

Florent

**Comment by TmpName** [comment]
Information marche encore ? je croyais que depuis que metahandler etait HS ca ne devait plus marcher ?
Apres je peux t'expliquer comment modifier toi meme le menu, mais a chaque mise a jour tu vas devoir refaire les manips.

Sinon faire un menu contextuel a la carte demanderait beaucoup de boulot, et pas sur que beaucoup de monde en ai besoin.
On peut Changer quelques couleurs, mais LordVenom est contre les addons arc en ciel (et je le comprend), donc si c'est modere (il y a deja 3 couleurs sur le menu)

**Comment by canopre** [comment]
Salut
Oui chez moi les informations fonctionnent parfaitement.
J'ai galéré car j'utilisais le template Aeon Nox Silvo et là les infos ne fonctionnaient pas.
Mais je suis retourné à Aeon Nox (de base) et les infos fonctionnent correctement :
- Y'a pas les photos des acteurs.
- Le lien vers le Trailer fonctionne pas.
Mais sinon tout est OK.

Sinon pour le menu contextuel : Je pense vraiment que ca serait une chouette fonction de pouvoir masquer certains éléments alors je vais attendre tranquillement : Je suis presque sûr qu'un jour ca sera disponible car tout le reste de l'addon déchire.

**Comment by canopre** [comment]
Je repensais à mon idée de menu contextuel sur mesure et je me demandais si c'était vraiment si compliqué que ca de rajouter la possibilité de simplement masquer des items du menu contextuel ?

Sinon y'a t'il une possibilité de maper une touche de ma télécommande directement sur les items "Information" ou "Télécharger" du menu contextuel ?

En dernier recours : un peu d'aide pour modifier le code afin de masquer certaines lignes seraient vraiment appréciée : J'ai fait quelques tentatives mais sans aucun résultat : je ne suis pas dutout codeur mais simplement un utilisateur averti.

Merci d'avance. :)

**Comment by TmpName** [comment]
Pour le coup de la telecommande, c'est pas idiot, j'ai commence a jeter un oeuil, il y a moyen d'editer un fichier pour regler les commandes de la telecommande et parmis la liste il y a la possibilite de lancer des script ou des addons.
http://kodi.wiki/view/Keymap

Il y a meme un addon pour faciliter ca, mais je doute qu'il ait l'option http://kodi.wiki/view/Add-on:Keymap_Editor

En attendant, pour editer le menu "hoster" le dernier, celui avec l'option telecharger (fichier hoster.py), il te suffit de mettre des # au debut des lignes
>>L61 oGui.createContexMenuWatch(oGuiElement, oOutputParameterHandler) (menu vu/pas vu)

>> L64 a L71 pour la playlist

>> L94 oGui.createContexMenuFav(oGuiElement, oOutputParameterHandler) (favoris)

>> L97 oGui.CreateSimpleMenu(oGuiElement,oOutputParameterHandler,'cLibrary','cLibrary','setLibrary','[COLOR teal]Ajouter a la librairie[/COLOR]') (favoris)

**Comment by canopre** [comment]
1000 Mercis : je regarde ça en détail asap !

**Comment by canopre** [comment]
J'ai essayé de suivre les instructions suivantes :

> Deux possiblitees
           elif cGui.CONTENT == "tvshows":
                self.createContexMenuWatch(oGuiElement, oOutputParameterHandler)
                self.createContexMenuinfo(oGuiElement, oOutputParameterHandler)
                self.createContexMenuFav(oGuiElement, oOutputParameterHandler)
devient
           elif cGui.CONTENT == "tvshows":
                pass
                #self.createContexMenuWatch(oGuiElement, oOutputParameterHandler)
                #self.createContexMenuinfo(oGuiElement, oOutputParameterHandler)
                #self.createContexMenuFav(oGuiElement, oOutputParameterHandler)
> 

Mais j'ai l'impression que cela supprime la ligne "Information" du menu contextuel alors qu'au contraire c'est la seule que je souhaiterais conserver du menu contextuel.

Désolé d'être aussi mauvais mais vous êtes bien savants de comprendre ce code qui me dépasse complétement :).

D'avance merci pour votre aide.

**Comment by TmpName** [comment]
Ha wi mince essaye plutot
>>elif cGui.CONTENT == "tvshows":
#self.createContexMenuWatch(oGuiElement, oOutputParameterHandler)
self.createContexMenuinfo(oGuiElement, oOutputParameterHandler)
#self.createContexMenuFav(oGuiElement, oOutputParameterHandler)

En faisant gaffe aux espaces en debut de ligne, la mise en page est galere sur github, en fait y a juste 2 # a rajouter (pas de "pass")
