### ISSUE TITLE
Vstream Android Tv

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#335]
Bonjour,
Je viens d'installer vStream sur Android Tv box "Wetek Core" mais je n'arrive pas a configurer les Paramètres des Métadonnées car le menu est grisé? Comme les informations des films sont en Anglais Je veux configurer TMDB (movie) en Français.
Merci de votre aide

**Comment by TmpName** [comment]
Je crois que les meta donees ne marche plus, faudrait que quelqu'un confirme.
Aux dernieres news on en etait la
https://github.com/LordVenom/venom-xbmc-addons/issues/317

**Comment by TmpName** [comment]
Pour reactiver le boutton meta data, 2 fichiers a prendre de la beta about.py et setting.xml.

**Comment by LordVenom** [comment]
Les meta fonctionne j'ai corriger le bug en 0.4.0.
