### ISSUE TITLE
Zone téléchargement et visionnage.

### ISSUE THREAD

**Issue by marcmarcmarcmarcmarc** [LordVenom/venom-xbmc-addons#336]
Bonjour.
Un grand merci pour avoir mis zone téléchargement .
Mais quand j'essaie de visionner un film par le biais d'uptobox j'ai le message "connexion premium réussi " puis un semblant de chargement et il ne se passe plus rien .
Est ce que je suis le seul à avoir ce problème ou est-ce vstream qui doit ètre peaufiné ?
( j'ai essayé la version béta qui a aussi le meme problème.)

Merci et bonne continuation.

**Comment by TmpName** [comment]
Tu tombes a pic ^^.
1 - Peux tu aller voir sur le site original, si le film est bien un film et non une archive rar
2 - Peux tu refaire le test en augmentant ton cache.
Au hazard dans advancedsettings.xml
>><advancedsettings>
<network>
<buffermode> 1 </buffermode>
<readbufferfactor> 1.5 </readbufferfactor>
<cachemembuffersize> 104857600 </cachemembuffersize>
</network>
</advancedsettings>
3 - Si tu pouvais me faire passer les 10 lignes de logs qui se sont ecrite a ce moment STP.

En fait ce probleme peut se produire, mais pas plusieurs fois de suite, enfin si quelqu'un peut me le confirmer ...

**Comment by marcmarcmarcmarcmarc** [comment]
Salut TmpName........je vais t'éviter du travail ...je voulais réessayer la version béta pour essayer tes conseils mais immédiatement tout s'est mis à fonctionner sur pour Zone télechargement.
Ca faisait deux jours que je ne pouvais pas revoir hurlement et maintenant plus de probléme . Tous les films sont ok en Sd ou en HD. J'ai essayé aussi en décochant l'utilisation du compte premium et en fait Vstream corrrige de lui méme et coche l'option quand c'est utile.
C'est donc avec surprise que je peux dire que ca marche nickel . (Mais pourquoi que maintenant ?)

**Comment by marcmarcmarcmarcmarc** [comment]
J'ai trouvé ce qui cafouille pour moi :  Aucun probléme avec zone telechargement quan j'utilise un acces direct vers internet. Mais quand je demande à Vstream de passer par un VPN zone telechargement ne marche plus. Les autres sites fonctionnent correctement .....ce n'est peut-etre pas vstream le responsable....il faudrait savoir si quelqu'un d'autre à le mème problème avec un compte premium sur 1fichier.

**Comment by sebi0606** [comment]
ça marche pour moi vpn activé et compte 1 fichier premium

**Comment by marcmarcmarcmarcmarc** [comment]
On progresse :  Avec le méme VPN et un compte premium 1fichier trouvé sur le net ca marche.
Pour le meme film , le même VPN et un compte premium uptobox valide ca ne marche pas.
Ou il ya incompatibilité entre mon vpn et uptobox premium ou ca vient de vstream pour l'acces au streaming uptobox sous VPN.
Quelqu'un àt-il réussi avec un VPN et un compte uptobox premium ?

**Comment by sebi0606** [comment]
Moi je passe par vyprvpn si ça peut t'aider

**Comment by TmpName** [comment]
Tu as testé en passant directement par le site de uptobox ? via et hors vpn ?

**Comment by marcmarcmarcmarcmarc** [comment]
Bon conseil TmpName. 1ere surprise : impossible d'acceder à zone telechargement par le biais de mon VPN avec mon pc. 2ieme surprise : toujours avec mon pc , le lien direct uptobox en streaming fonctionne avec le VPN sans ètre déclaré premium.
Je n'avais jamais essayé avec mon pc donc c'est peut-ètre normal.
En tous cas on ne peut pas se fier à ce que j'obtiens car visiblement il ya un problème entre mon VPN (skyssh) et zone telechargement.
Inutile de chercher plus loin si je suis le seul avec ce problème.
Merci  pour l'aide apportée et bonne continuation.

**Comment by TmpName** [comment]
Les lien uptobox marchent sans etre premium, le seul probleme c'est que tu ne peux telecharger que 1 fichier toute les 30mn ou 1h, donc si tu changes d'avis et ferme le film, le prochain ne redemarrera pas de suite.

Uptobox est vraiment bien foutu meme pour les free users.

**Comment by mino60** [comment]
Sur le net il ya un site de streaming français qui utilise une extension google chrome ZenMate pour les telechargerment et le streaming via upttobox, est ce que il ya un moyen d'd'utiliser cette option sur vstream?

**Comment by TmpName** [comment]
Houla, je connais pas la moitie des appellations que tu utilises, c'est quoi le lien que j'aille voir ?

**Comment by marcmarcmarcmarcmarc** [comment]
Zenmate est un VPN gratuit. Il esixte un addon firefox que j'utilise pour aller sur le net mais la communication est ralentie... et pas qu'un peu !   mino60 as-tu déja essayé de voir un film en entier en utilisant zenmate  et l'as-tu vu dans de bonnes conditions ?.....

**Comment by mino60** [comment]
Oui effictivement sur le site http://www.fullstreamingcinemas.com/

**Comment by sebi0606** [comment]
Même problème depuis hier soir avec vstream et vstream bêta impossible de lire un fichier sur zone de telechargement avec ou sans vpn
