### ISSUE TITLE
FLASHS 

### ISSUE THREAD

**Issue by domtom25** [LordVenom/venom-xbmc-addons#337]
bonjour 

merci pour votre super travail 

juste pour signale le probleme de flashx qui fonctionne pas

mille merci longue vie a vous

**Comment by mino60** [comment]
le bug et corrigé sur la beta  : 
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/hosters/flashx.py

juste pour info j'ai remarqué un bug sur la recherche kepliz.com

**Comment by TmpName** [comment]
Comme le dit mino60, ca a été corrigé il y a 3 jours, et comme Vstream verifie les fichiers tout les 3 jours tu devrais avoir une icone pour mettre a jour le fichier sur la page d'acceuil de Vstream.

Pour kepliz j'y jete un oeuil de suite.
