### ISSUE TITLE
streamcomplet

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#338]
Voilà une nouvelle source streamcomplet.com  juste une erreur sur showhoster

http://pastebin.com/ZkRKbELW

**Comment by TmpName** [comment]
Merci, je l'ai mise direct sur la beta
>> https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/streamcomplet.py

Je l'ai fait fonctionner pour quelques hosts, mais j'ai rien testé du tout.
