### ISSUE TITLE
sync de librairie

### ISSUE THREAD

**Issue by korail** [LordVenom/venom-xbmc-addons#339]
Bonjour/bonsoir

avant toute chose je tien a vous remercier pour l'énorme boulot que vous faites,

je vous expose mon petit soucis en espérant trouver solution a celui si, Merci d'avance pour l'intérêt que vous pourrait portez a mon message

j'ai Vstream et Kodi installer sur différentes pièces de la maison ( salon, chambre, ..), j'aimerais s'avoir si il était possible de reprendre une vidéo ( issue de vstream ) sur un autre appareil et si oui comment pourrais je m'y prendre

je vous souhaite une agréable soirée

cordialement

**Comment by TmpName** [comment]
Oui, il y a plusieurs moyen.

Si ce n'est que des PC tu peux simplement utiliser le partage de fichiers.

Plus evolue jette un oeuil du cote UPnp/DLNA, tu pourras l'activer dans les services de kodi, c'est un protocole de communication entre appareils, je m'en suis servi a une epoque pour lire depuis ma box internet des fichiers se trouvant sur un PC avec kodi.
Evidement ca marche pour des fichier locaux, j'ai pas testé pour des fichiers externes, mais je vois pas pquoi ca marcherait pas.

Regarde "kodi dlna stream" sur google.
