### ISSUE TITLE
9docu site très intéressant 

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#340]
Bonjour pourriez vous ajouter ce site " 9docu.com " à vstream source très importantes de documentaires et d'émissions tv 
Merci d'avance

**Comment by TmpName** [comment]
Le site est pas mal, il n'y a qu'un seul host en streaming a chaque fois. mais j'ai pas trouve de lien mort.
En plus il est pas complique, si il y a des motives ....

**Comment by sebi0606** [comment]
Si chataigne veut bien si coller ça serait cool ^^

**Comment by sebi0606** [comment]
Chataigne73 désolé

**Comment by TmpName** [comment]
Lol, t'inquietes pas, il y a peu de sites de docu, donc il va surement sortir, mais par contre la y a pas mal de monde occupe pour le captcha de google.

**Comment by sebi0606** [comment]
;) en tout cas content de vous avoir fait découvrir ce site de docus

**Comment by TmpName** [comment]
Meme LordVenom devrait etre interessé, je crois que tout les sites de docus vienne de lui.

**Comment by sebi0606** [comment]
vraiment hâte de le voir intégré à vstream merci @TmpName

**Comment by jojotango** [comment]
Bon du coup j'ai fait la source à la va vite, je l'ai pas vraiment tester.
Il faudra attendre la mise à jour du home.py pour les nouveautés et genre.

Par contre il y a une partie catégories dans le site, @TmpName est ce que tu veux que j'essaie de l'ajouter au home.py ?
Pour l'instant je l'ai mis dans les genres.

Pour les curieux voici la source <a href="http://pastebin.com/EYjvTv7G">neuf_docu_com.py</a> . Demain j'aurai un peu de temps pour la tester et l'améliorer.

**Comment by sebi0606** [comment]
Merci @jojotango

**Comment by TmpName** [comment]
Ce serait quoi la DOC_CATES ? Si c'est categories, en genre ca va tres bien.
Mais la je galere Kodi m'a memorise ma page home, et quoi que j'y fasse comme modifs, il m'affiche toujours la meme, impossible de faire une MAJ.

**Comment by jojotango** [comment]
Oui ça serait pour les catégories.
C'est bizarre car pour le home par ce que je l'ai édité directement chez moi.

**Comment by TmpName** [comment]
Ca y est ca remarche, j'ai du supprimer tout le cache de kodi, pas moyen de faire autrement, depuis que je suis passe a la v16, j'ai que des emmerdes.

Categories ou genres c'est pareil, pour la telerealite ou les chaines de tv c'est pareil, on va pas chipoter ^^.

Du coup je jete un oeuil a tes sources.

**Comment by TmpName** [comment]
C'est bon, mit en ligne.
Pour ce qui est du regex, l'amelioration on s'en fout un peu, moi je les raccourcis car plus facile a lire, mais le plus important c'est les iterations (affiche en haut a droite sur regex 101) c'est le nombre de boucles que fait l'algorythme, si y en a trop, ca met trop de temps a calculer et meme parfois ca rate.

Pour a=45
a=".+?" demandera plus de test que a=[^"]+" ou a = "[0-9]+"

**Comment by sebi0606** [comment]
Bonjour je viens d'installer la bêta avec 9docu merci encore pour le rajout 
Serait-il possible d'afficher plus de 5 résultat quand on va dans les catégories où la recherche par nouveautés 
Merci d'avance

**Comment by TmpName** [comment]
Nope, car le site n'en propose que 5 par page, c'est d'origine.

**Comment by sebi0606** [comment]
ok merci @TmpName
