### ISSUE TITLE
Zone de telechargement hs 

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#341]
Bonsoir Zone de telechargement hs sur vstream dès que l'on essaie un lien un message d'erreur de vstream apparaît

**Comment by mino60** [comment]
ça fonctionne trés bien chez moi essayé la version beta ; 

http://www.mediafire.com/download/w11wg391u2hv9tq/plugin.video.vstream.zip

**Comment by sebi0606** [comment]
Je confirme ne marche plus apparement dl protect ont changé leur système de captcha

**Comment by sebi0606** [comment]
Effectivement ça marche sur mon Mac mais plus sur box Android je ne comprend je n'ai rien installe de plus ????

**Comment by sebi0606** [comment]
Bon problème résolu j'ai utilisé fresh start et ça remarche je ne sais pas ce qui a pu se produire

**Comment by sebi0606** [comment]
Ça ne remarche plus à nouveau

**Comment by sebi0606** [comment]
Help me j'ai tout réinitialiser même ma shieldtv toujours le même problème sur zone de telechargement quand je veux ouvrir un fichier erreur vstream alors que je n'avais aucun problème avant ??

**Comment by LordVenom** [comment]
oupps double message 

https://github.com/LordVenom/venom-xbmc-addons-beta/issues/129

**Comment by TmpName** [comment]
Oui j'ai vu, rien de mechant, ils ont juste change le captcha.
Le nouveau captcha est deja gere par pas mal d'addon, me faut juste l'adapter pour Vstream.

**Comment by mino60** [comment]
a la place de captcha chiffres et lettres Pour prouver à dl-protectque vous n’êtes pas un robot, il suffira de cliquer sur un bouton
http://postimg.org/image/m51j9un25/full/

**Comment by TmpName** [comment]
La je suis en train de bosser sur un code de shani08.
J'arrive a afficher les 9 vignettes, et les selectionner, et a valider.
Seul probleme : la question a afficher, je sais ou se trouvent toute les questions me reste juste a savoir comment trouver la bonne.
La je suis en train de tester un debogger de javascript et j'ai deja plante firefox 4 fois, mais vu le monde sur le coup, ca ne devrait pas durer longtemps.

**Comment by TmpName** [comment]
Alors je cite Chataigne73
>>vous pouvez contourner le pb en allant sur ZT avec un navigateur et en ouvrant un lien dl-protect ... votre ip sera alors mémorisée, et ce nouveau captcha ne sera plus demandé ... cela refonctionnera alors correctement dans KODI

**Comment by sebi0606** [comment]
Salut TmpName j'ai installe la dernière bêta que tu as mis à jour toujours le même message d'erreur pour moi sur zone de telechargement

**Comment by TmpName** [comment]
Yep, j'ai pas encore mis en places mes modifs vu que non fonctionnelles.
La j'ai finis tard et je vient juste de finir de manger, donc y aura pas de neuf pour ce soir, mais par contre comme l'a dit chataigne, je me suis connecté hier sur ZT, j'ai donné 1 captcha et 24h apres il ne me le redemande pas encore.

**Comment by sebi0606** [comment]
salut TmpName oui moi aussi c'est à peu près toutes les 7 ou 8 demande de fichiers que l'on est pas embêté par l'erreur du au nouveau système de dlprotect donc pas d'urgence ^^

**Comment by mino60** [comment]
j'ai modifier dl_protect mait le lien uptobox ne s'affiche pas


http://pastebin.com/ndd2p532

http://pastebin.com/iRAGYv17

**Comment by chataigne73** [comment]
@TmpName : as tu une adresse email où je pourrais t'envoyer des infos intéressantes ?

**Comment by TmpName** [comment]
C'est normal mino60, pour le moment le code pour ce cpatcha n'est pas fini, j'ai juste mis en ligne mon code, pour les moteurs de recherche, pour que d'autres le lisent et cherchent dessus.

@chataigne73 c'est assez delicat sur github vu que tout le monde pourrait la lire, mais c'est confidentiel comme infos ?
La je suis en train de regarder un code de InsideReCaptcha, mais depuis 3 jours j'ai meme finit d'installer python sur l'ordi ^^

**Comment by sebi0606** [comment]
Vous avez pas Twitter ? En cas par dl sur Twitter

**Comment by TmpName** [comment]
Non plus ^^.
C'est vrai que il n'y aucun moyen sur github pour passer un message perso.

**Comment by TmpName** [comment]
Quelqu'un ici aurait python sur une machine sous linux et si possible en 32 bit ?

**Comment by chataigne73** [comment]
@TmpName : c'est parce que j'ai gentiment obtenu le code source d'un outil qui supporte dl-protect, et je me dis que ça pourrait t'être utile ... mais les développeurs ne souhaitent pas que ce soit public

**Comment by TmpName** [comment]
Ben si ca supporte le recaptcha de google, c'est sur ca m'interesse, le probleme c'est que c'est pour Vstream, donc ca va forcement etre public, enfin peut etre pas tout leur code, mais la partie qui nous interesse, je vais pas avoir le choix ....

Pour le moment je suis sur le botguard avec un code qui est sense marcher, mais pas sur toute les configs, et evidement win x64 fait parti du lot ....

Et j'ai pas envie de l'installer sur mon raspberry, linux me donne des malaises.

**Comment by chataigne73** [comment]
@TmpName : je viens de t'envoyer qqc sur ton adresse email d'inscription à github

**Comment by mino60** [comment]
Il semble qu'il n'y ait aucun moyen de résoudre ce captcha par ce que Ils ont bloqué l'URL de repli qui montre des images sur leur clé de site 
j'ai trouvais le meme probleme sur le site: 
https://forums.tvaddons.ag/shanis-addon-repository/24190-release-livestreamspro-139.html

**Comment by TmpName** [comment]
@mino60 Il a deja trouve comment contourner ca, son dernier code est plus avance (je suis parti du sien)
En fait en utilisant cette astuce cela permettait de bypasser la protection antibot (botguard) de google.
C'est la ou je bute en ce moment, mais ce We je reinstalle le raspberry pour tester le code que j'ai trouve.

@chataigne73 , je m'attendais pas a ca, ce n'est pas du tout ce que je connaissais, mais son code marche encore ? Apparement il utiliserait une faille du site pour remplir un formulaire sans passer par le captcha de google.
Par defaut on utilise "g-recaptcha-response" et lui utilise le parametre 'i'.

Tu es sur que son code marche encore depuis la derniere MAJ de dl-protect ?

**Comment by chataigne73** [comment]
@TmpName : j'attends que le recaptcha me soit redemander pour tester, mais le dev m'a dit que oui

**Comment by Drakod** [comment]
salut ,

juste pour info le captcha sur dl-protect.com ( sur zone telechargement ) me le demande systématiquement , c'est normal ou il ya une astuce qq part ?

merci pour vos retours

**Comment by TmpName** [comment]
Normallement il le demande une fois, et en cas de succes (si tu accedes aux liens) il ne te le redemande que au bout d'une dizaines d'affichage de liens.

**Comment by Drakod** [comment]
en effet je trouvais ca bizzarre mais  il me le redemande vraiment a chaque fois que ce soit sur PC "kodi jarvis" ou sur openelec kodi Isengard , et meme en direct sur une page Firefox a chaque nouvelle video sur (uptobox ou autre) il m'affiche le capchat systématique

**Comment by TmpName** [comment]
Tu passes par un proxy ?

**Comment by Drakod** [comment]
Nan aucun proxy , tu na pas le phenomene de ton cote ? Si tu ne la pas cest qui ya un soucis avec mon ip qui doit le considere comme un spam cest assez etrange

**Comment by TmpName** [comment]
Ha oui, tu as raison, j'allais te dire que c'etait une histoire de cookie mais non ca fonctionne par IP. Si dans firefox tu donnes le bon captcha, ca ne te le redemande pas sous kodi.

Donc oui, doit y avoir un prb avec ton IP.

**Comment by shawnmike** [comment]
Bonjour tout le monde, je ressort un dossier d'il y a un an haha!

Je tente de régler ce même problème avec le dl-protect. Je suis sur pc et ça me donne cette même erreur, alors que lorsque je le fais via mon cellulaire je n'ai aucun problème. 

Peut-être pourrez vous m'aider à régler le tout.
Merci d'avance!

**Comment by Arias800** [comment]
Il y a une issue plus recente  qui parle de problème par rapport a DL protect donc plusiuer solution ont été trouvé https://github.com/Kodi-vStream/venom-xbmc-addons/issues/1619
