### ISSUE TITLE
Probleme Telechargement

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#342]
Je ne sais pas ce qui ce passe mais il est impossible de télécharger actuellement avec vstream?

**Comment by TmpName** [comment]
Je viens de tester sur un lien youwatch , j'ai pas eu de problemes.
Tu as essaye sur plusieurs hosts ? Chnage aussi de films, il se peut que le probleme vienne de la premiere lettre du film, je rigole pas, j'ai deja eu ce bug.

Sinon j'ai deja corrige netu et streamingto, et la je m'attaque a okru.

**Comment by arzaz** [comment]
Ah...
J'ai fait le test avec le film la 5ème vague sur KEPLIZ host googlevideo et ZT host uptobox, mais avec ce dernier impossible même de visualiser le film.

**Comment by TmpName** [comment]
Bien vu.
J'ai corrige pour kepli z, fichier a mettre a jour "util.py"
