### ISSUE TITLE
Zone-Telechargement Series

### ISSUE THREAD

**Issue by noipo** [LordVenom/venom-xbmc-addons#343]
Serait-il possible d'ajouter zone telechargement comme source dans les series ?
Merci

**Comment by TmpName** [comment]
Ca, c'est a toi de configurer.
Dans les parametres de Vstream, "pluggin on/off 3/3", "Zone t e elchargement", coche "recherche 2" (par defaut si tu as rien change, la recherche 2 correspond aux series)

**Comment by noipo** [comment]
Merci je savais pas !
