### ISSUE TITLE
Fullstreamingcinemas.com

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#345]
je travail sur cette source depuis deux jours mais le regex que j'ai mis ne fonctionne pas erreur 147: 
    aResult = oParser.parse(sHtmlContent, sPattern)

http://pastebin.com/tSgZw9nC

**Comment by TmpName** [comment]
Utilise regex101
http://www.hostingpics.net/viewer.php?id=695193son.png

Et y a une erreur dans l'url, il y a un '/' a la fin qui provoque une erreur.

**Comment by mino60** [comment]
j'ai corrigé l'erreur mais il y a un problème sur les posters juste un qui s'affiche et une icone pour les autres

![sans titre](https://cloud.githubusercontent.com/assets/11494048/14586880/10cc5a4e-04a7-11e6-886e-310d3a20d3e4.png)

![Uploading Sans titre1.png…]()

http://pastebin.com/rkJJckG2

**Comment by TmpName** [comment]
Deja y a un autre probleme, tu affiches les liens a la place des titres.
Et pour le bug des images, je viens de verifier sur le screen, c'est les bon titres qui s'affiche dans regex101.

**Comment by mino60** [comment]
j'ai corrigé le bug des images mais il reste de trouver la fonction showHoster remarque le lien "href"
ne mène pas à la page de telechargement et le streaing il faux cliqué sur voir ici sur le site.
le next page ne fonctionne pas
http://pastebin.com/kBWLuncH

**Comment by TmpName** [comment]
Le "print aResult" donne quoi dans Showhoster ?
Essaye aussi un "print sUrl" pour voir l'url.

**Comment by mino60** [comment]
J'ai essayé print aResult le log me donne ça: 

http://pastebin.com/2Am3cVx9

**Comment by mino60** [comment]
j'ai corrigé le script pour les titres
http://pastebin.com/JA5NaSeT
http://pastebin.com/rP3e4eP8

je crois qu'il manque une partie de l'url (fullstreamingcinemas.com/)?

**Comment by TmpName** [comment]
Bien vu, c'etait bien ca, les titres a la place des urls
now >> ValueError: unknown url type: -rec--4.ws, l'adresse n'est pas complete, essaye un truc du genre

oOutputParameterHandler.addParameter('siteUrl', str(URL_MAIN + aEntry[1])) #sortie de l'url

Rajoute un '/' a la fin de l'url
URL_MAIN = 'http://fullstreamingcinemas.com/*'

**Comment by mino60** [comment]
j'ai ajouté cette ligne mais je suis sur une page vierge!?..

http://pastebin.com/qXsRh6eE

**Comment by mino60** [comment]
Pour uptostream uptobox j'ai trouvé cette Pattern : 
    sPattern = '<iframe width=".+?" height=".+?" src="(.+?)" scrolling="no" frameborder="0"><\/iframe>'
pour vidloker openload speedvideo youhatch
     #sPattern = '<iframe src="(.+?)"'

**Comment by TmpName** [comment]
sPattern = '<iframe[^<>]+src="(.+?)"'

**Comment by mino60** [comment]
Pour les series est ce que il faux mettre la fonction showSeries
et comment mettre deux regex pour la fonction next page 

http://pastebin.com/hd53WKtE

**Comment by TmpName** [comment]
Ce serait plus facile pour toi, comme ca tu aurais une partie Showmovie qui fonctionne direct et une partie Showseries qui va gerer saisons et episodes
Par contre les liens series sont protegees, rien de mechant je pense que c'est contournable.

Par contre pkoi 2 regex pour next page ? J'ai ete voir pour les films et les serie nouveautees, c'est la meme fleche. Y a un truc different quelque part ?
