### ISSUE TITLE
Vstream insallation impossible sur openelec raspberry pi3

### ISSUE THREAD

**Issue by Didj67** [LordVenom/venom-xbmc-addons#346]
Bonjour, j'ai depuis quelques temps installé un raspberry pi 3 en media center chez moi, dans un premier temps en installant osmc sur lequel j'avais rajouté vstream avec succes et j'ai énormément aprécié cet extension mais depuis quelques jours j'ai changé de système pour passer à openelec et depuis je n'arrive plus à installer vstream. 
Pouvez vous me donner une explication à ce problème et une solution pour que je puisse à nouveau profiter de cette super extention?

Merci.

**Comment by TmpName** [comment]
Salut, tu essaye de l'installer a partir de quoi ?
Quel repo ?
Quelle version ?
Tu as un message d'erreur ?

**Comment by LordVenom** [comment]
Bonjour, j'utilise aussi openelec sans soucis, mais je suppose que tu a résolut le problème vus que tu donne plus de nouvelle.

**Comment by Didj67** [comment]
Merci à vous pour vos reponses et désolé pour la réponse plus que tardive. J'ai en effet résolu mon problème, après avoir fait un redémarrage du raspberry l'installation s'est déroulée sans soucis.
Merci encore et désolé d'avoir encombré le forum inutilement.
Et encore bravo et merci pour ce super addon.
