### ISSUE TITLE
4 sources pour tester

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#347]
Je travail sur 4 source mais j'ai besoin d'aide pour les finirs

(1) -- lookiz
http://pastebin.com/3ePEvYXM

(2) -- streamingwatching
http://pastebin.com/fxb6mphM 

(3) -- streamay.com
http://pastebin.com/n6AZyUsF

(4) -- filmzenstreaming
http://pastebin.com/zwxqhKKg

pour le future

h ttp://adocine.siteblogs.net/#
h ttp://www.fullstream.in/

**Comment by TmpName** [comment]
En plus facile y a https://github.com/LordVenom/venom-xbmc-addons/issues/340

**Comment by LordVenom** [comment]
Des Films et des series ont en trouve sur vStream mais y a d'autre source du sport, des concerts, des spectacle y encore des catégorie a peaufiner.
