### ISSUE TITLE
Script.extendedinfo

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#348]
Est-il possible d'adapter le script.extendedinfo a vstream?

**Comment by LordVenom** [comment]
J'y est penser mais comme pour les hosts ont tente de dépendre le moins possible d'autre script.La raison est simple la compatibilité. J’ai retoucher un peux la fenêtre d'info qui buguer avec d'autre skin que celui par defaut.

**Comment by arzaz** [comment]
Actuellement j’utilise le skin AEON MQ 7 et il m'est impossible d'avoir plus d'information avec la fonction Extended info.
Qu'ent est du script skin helper service?

**Comment by LordVenom** [comment]
Dsl je comprend pas ceux que tu veut dire.Pour vStream menu context information ouvre un popup avec les info de tmdb.

**Comment by canopre** [comment]
+1

**Comment by TmpName** [comment]
Pour info LordVenom a craque, il a mit quelque chose en place pr cet addon
https://github.com/LordVenom/venom-xbmc-addons/issues/375
