### ISSUE TITLE
un problème sur kepliz

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#349]
Bonsoir j'ai remarqué un petit problème sur la recherche kepliz le film les huit salopards le film s'affiche mais pas les liens de streaming google sur le site je peux visualiser le film son problème?!!...

**Comment by TmpName** [comment]
Corrige.
Par contre j'espere qu'il n'est pas le seul a utiliser ce systeme, ce me foutrait les boules d'avoir code ce monstre juste pour 1 film.

**Comment by Kodigoal** [comment]
Salut,
non ca déconnait pour plusieurs films ses derniers temps et là c'est bon merci :)
