### ISSUE TITLE
Zone-telechargement

### ISSUE THREAD

**Issue by Brahimbaz** [LordVenom/venom-xbmc-addons#350]
Salut à tous. Je vous explique mon problème. J'ai installé vstream sur ma box android pour accéder au source de zone-telechargement et tout marche parfaitement. Malheureusement sur mon pc Windows sur la source zone-telechargement sur les série par saison je n'est que le fichier en .rar et non les épisode par episode alors que sur ma box tout y est! Sur le pc de ma soeur et mon beauf ça marche nikel aussi. Auriez vous un retour et comment corriger cela? Merci d'avance pour vos réponses

**Comment by TmpName** [comment]
Ce ne serait pas un probleme de version ?
Normallement le coup des fichiers rar etait un bug d'une vielle version, je pensais que c'etait corrige.
Apres parfois ils ont 3/4 pages differentes pour la meme serie, avec pas forcement les memes fichiers.
Il n'y a pas de raisons pour que sur 2 PC different les resultats ne soient pas les memes. C'est soit une version differente, soit une page de leur site differente (les differences sont parfois subtiles) et donc ils nous faudraient corriger le code.

**Comment by Brahimbaz** [comment]
Merci de ta réponse. Et pourtant c'est bien le cas sur 2 pc sur 5 que j'ai eu l'occasion d'installer vstream il y a ce problème en testant sur toute les saison qu'il propose j'ai essayé d'installer la version bêta mais elle ne s'installe pas ça me dit erreur
