### ISSUE TITLE
Nouvelle source "les-docus.com"

### ISSUE THREAD

**Issue by jojotango** [LordVenom/venom-xbmc-addons#351]
Bonjour à tous,

Je viens de terminer l'ajout d'une nouvelle source "les-docus.com".
Pas vu de bug... Mais des fois que hésitez pas.

La source <a href="http://pastebin.com/XvBP0vFU">les_docus_com.py</a>

Le <a href="http://pastebin.com/vJLc3n0p">home.py</a>
modifié pour pouvoir utiliser les variables "DOC_GENRES", "DOC_NEWS" (ajout des fonctions showDocs, docGenres et docNews)
dans la source et avoir un affichage des nouveautés et genres dans la catégorie documentaire.

Bon visionnage :)

**Comment by TmpName** [comment]
Elle va plaire a LordVenom ^^.
Par contre je galere pour installer la page home, j'arrive pas a mettre a jour la page, meme apres un redemarrage, doit y avoir un cache a la con sur la V16.

Du coup j'ai pas fini de tester ta sources, mais j'ai vu un bug, 2 eme page manque le film "La faille de San Andreas", la j'ai pas trop le temps, mais je le met en ligne demain sans fautes.

**Comment by Kodigoal** [comment]
Petit problème dans le regex, la valeur  dans le height='180'
Pour ' La faille de San Andreas' elle est de '149'.
Vaudrait mieux enlever toutes les valeurs  du regex:
Petite correction vite faite ( on peut le simplifier plus le regex je pense) 
http://pastebin.com/JhBSLEby

**Comment by jojotango** [comment]
Oui effectivement ce regex suffirait
<code><div class="post-header"><a href="([^<]+)" title="([^<]+)"><img width=".+?" height=".+?" src="([^<]+)" class=".+?" alt=".+?" /></a><p.+?">(.+?)</p></code>
On même pas besoin du style dans la balise <p>.

Peut-être que l'on peut encore l'améliorer.

**Comment by TmpName** [comment]
C'est bon mit en ligne, pas vu de prbs.
Par contre fait attention j'ai chnage le nom, j'ai vire l'extension, pour ce type de source ca sert a rien mais en general il chnage souvent d'hebergeur et donc d'extension, c'est juste une habitude que j'ai pris.

**Comment by LordVenom** [comment]
Merci @jojotango, oui j'aime les documentaires lol
