### ISSUE TITLE
www.MangaCity.co Fix

### ISSUE THREAD

**Issue by yepmouidriss** [LordVenom/venom-xbmc-addons#354]
Dans le site via le browser les animes forctionnent bien mais dans vs stream les dossiers d'episodes apparaisent vides. vstream ne retrouve pas les liens openload et streamin du site w ww.mangacity.co

..

**Comment by TmpName** [comment]
Exact, je jete un oeuil de suite.

**Comment by yepmouidriss** [comment]
Nicky Larson, Ranmha 1/2 et autres

**Comment by TmpName** [comment]
Ok, donc c'est bien, j'ai teste pas de problemes.
Normallement sur la page d'acceuil de vstream tu devrais avoir une icone avec une fleche intitulee "mise a jour dispo", si tu cliques dessus, ca va mettre a jour tes fichiers sites.

Vstream verifi les MAJ tout les 3 jours, comme elle date de 5 jours tu devrais l'avoir.

**Comment by yepmouidriss** [comment]
je ne voir pas cette icone sur mon vstream

**Comment by TmpName** [comment]
Tu as installe Vstream il y a moins de 3 jours ?
Tu as bien la derniere version ?

**Comment by yepmouidriss** [comment]
oui j'ai reinstalle aujourd'hui.

**Comment by TmpName** [comment]
Alors je crois que Vstream commence a verifier 3 jours APRES l'instal (mais la je me souvient plus), triche sur la date pour voir si tu as les mises a jours qui apparaissent.

**Comment by yepmouidriss** [comment]
J'ai remplacé les fichiers de l'extension par copier/coller avec la version
bêta et là sa fonctionne accès bien. MERCI.
