### ISSUE TITLE
Soucis avec la recherche

### ISSUE THREAD

**Issue by hermfr** [LordVenom/venom-xbmc-addons#355]
Bonjour,

tout d'abord un grand bravo pour votre travail.
Je voulai juste vous remonter un dysfonctionnement sur la recherche, j'ai un raspi sous osmc et faire une recherche n'aboutit plus et plante osmc, idem recherche visuelle.
J'ai mis à jour de la 0.3.9 à la 0.4.0 mais le soucis ne s'est pas résolu.

Cordialement.

**Comment by TmpName** [comment]
Tu aurais pas un message d'erreur avec un probleme de cache ?

**Comment by hermfr** [comment]
Oui, j'ai vu un message parlant de la mémoire cache.
J'ai alors pensé que c'était un soucis de tampon pour le stream.
Merci pour ta réponse et ta réactivité, sais tu si il existe une fonction pour vider le cache.

Cordialement.

**Comment by TmpName** [comment]
Bon ben j'espere que tu lis l'anglais car pas moyen de trouver de l'aide en francais.
Apparement c'est un probleme courant sous raspberry, il faudrait augmenter la taille de ton cache
http://kodi.wiki/view/HOW-TO:Modify_the_video_cache
Apres, pas moyen de trouver un mec qui donne un exemple de valeur a mettre, ou si il parle du cache de de lecture ou du cache des pages, vive l'exotisme ....

Sur Vstream dans les parametres y a une option pour vider le cache, la c'est facile, mais il y a de forte chance que cela vienne de kodi, et la a part effacer soit meme les fichiers a la main, je sais pas ou c'est.
Tu as les metas activés ? Si oui, je pense que c'est plutot le cache des metas qu'il te faudrait vider.

**Comment by Kodigoal** [comment]
Même soucis .. mais en désactivant 'FullMoviz' dans les paramêtres de Vstream ( plugin 2/3) ,
ca refonctionne ..

**Comment by hermfr** [comment]
J'ai vidé le cache de l'addon et celui de XBMC en allant dans la config de l'extension onglet "outil"
et ça ne fonctionnait pas mieux, j'ai désinstallé Vstream redémarré le  Pi et réinstallé et maintenant cela fonctionne à nouveau! Je vois une erreur de connexion pendant la recherche, mais il ne plante plus.
Merci à tous.
