### ISSUE TITLE
probleme avec les menus "recherche"

### ISSUE THREAD

**Issue by ballost** [LordVenom/venom-xbmc-addons#356]
Bonjour
j'utilise vstream sur kodi 16.0 sur une tv android et aucun pb jusqu'à hier
pb avec les menus recherche et recherche visuelle
a chaque fois la recherche commence, on voit bien qu'il charge des infos puis reste bloqué avec curseur "en cours" en bas à droite tournant sans nous donner la liste des sources /liens
il faut forcer l'arrêt voir redémarrer la tv pour debloquer kodi

Par conte aucun soucis si on passe par le menu film et que l'on choisi par source et ensuite un lien sur une source
auriez vous une idee de la cause et une solution

D'avance Merci
Cdlt

**Comment by Kodigoal** [comment]
Essaye de désactiver dans les paramêtres de Vstream ( plugin 2/3) la source 
'FullMoviz' en attendant.

**Comment by ballost** [comment]
Bonjour Kodigoal
Merci pour ton retour
en effet la desactivation de cette source dans les parametres permet à nouveau les recherches
par contre ce matin mise a jour vstream faite et toujours le pb si cette source est activé
merci encore pour le retour et le boulot fait :)

PS : quand tu parles de mise a jour de cette source, la mise a jour vstream suffit ou y a t'il une autre manip a faire

Cordialement

**Comment by LordVenom** [comment]
Bonjour, Fichier envoyer en mise a jour auto.

**Comment by Kodigoal** [comment]
Soit tu peux mettre à jour le fichier  fullmoviz_org.py dispo sur la Beta par toi même sur ta box android
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/fullmoviz_org.py
Soit il faut attendre que le fichier soit vérifié et Maj sur la version Vstream officielle pour 
l'avoir en Maj disponible.

**Comment by Kodigoal** [comment]
oups, Merci :)

**Comment by LordVenom** [comment]
Merci  a toi pour la correction :)

**Comment by ballost** [comment]
RE a vous deux et encore merci pour votre Job :)
pour info et faire avancer 
comme je l'avais dis dans un précèdent comm même apres mise a jour en ligne de vstream ce matin si cette source est activée, la recherche par nom plante
j'ai donc laissé desactivé cette source et tout baigne

Cdlt

**Comment by TmpName** [comment]
Mais c'est quand meme bizarre ce bug, Y a personne qui pourrais faire passer les logs ?

**Comment by Kodigoal** [comment]
Je pense que la Maj disponible dans Vstream ce matin que tu as faites ne comprenait pas encore
la source Fullmoviz.
LordVenom a maj le fichier sur la version officielle par après.
Donc soit tu attends 3 jours ( délai pour que Vstream vérifie à nouveau si ya des Maj à faire).
Soit tu peux avancer la date de 3 jours de ta box android , lancer kodi puis Vstream et 
il vérifiera les Maj  et normalement la source Fullmoviz devrait être dispo pour Maj.
Ou modifier le fichier fullmoviz_org.py toi même comme précisé avant.

**Comment by ballost** [comment]
ok merci Kodigoal pour la précision des 3 jours c plus clair maintenant
en effet modif date TV relance kodi et vstream et MAJ fullmoviz OK
et apres reactivation source les recherches sont OK

Merci encore vous êtes des boss

**Comment by Kodigoal** [comment]
@TmpName 
A voir si ca deconne que sous Android , pas testé sous windows/linux.
En lancant une recherche Film par exemple  'red' , la recherche a l'air de tourner dans le vide
au moment ou il recherche sur Fullmoviz ( qui ne fonctionnait plus vu le petit changement dans le code html du site ).
Pour le log ya rien de special , et pour ma part je suis obligé de stopper la recherche et ensuite
relancer kodi car tout bloquer.
http://pastebin.com/kPWk1yGT
Mais si je faisais une recherche visuelle , film populaire et je lancais le film 'star wars 7' , la recherche marchait xD mais en lancant par exemple ' le livre de la jungle' , ca bloquait au même moment 
ou il arrive sur Fullmoviz.
Je testerais sur Windows/Linux  si ca donne la même chose de mon côté.

**Comment by TmpName** [comment]
Un bug de regex peut etre ?
Je ne vois que ca pour bloquer kodi (et put1 que ca m'arrive souvent quand je teste les regex)

**Comment by Kodigoal** [comment]
Oui ca doit être ca , c'est marrant que sur certains titres de films , ca passe Fullmoviz  sans soucis.
Pas encore testé sous windows/linux si il fait pareil en utilisant l'ex fichier Fullmoviz.
