### ISSUE TITLE
Problème pour trouver un résumé en français

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#357]
Tout les résumé son en englais sur tout les sources

sur kepliz par exemple j'ai remplacé :  
sComm = cUtil().unescape(aResult[1][0][0])

par  

sTitle = aResult[1][0][0]

le résumé remplace le titre sur showHoster
![sans titre](https://cloud.githubusercontent.com/assets/11494048/14763775/ef4ceef2-09a0-11e6-9385-aba3b3eac14b.png)

est ce que il y a une solition pour ce problème et merci.

**Comment by Kodigoal** [comment]
Salut,
Tu as bien configuré Vstream pour qu'il affiche les résumés en francais si dispo ?
ici: http://i.imgur.com/vUeDve4.jpg

**Comment by mino60** [comment]
Merci pour l'info ça marche maintenant trés trés bien

**Comment by TmpName** [comment]
Les resumes pris en direct sur le site ne fonctionnent que si les metas sont desactives.

**Comment by mino60** [comment]
pour quoi les résumés sur zone-telechargement ne fonctionne pas remarque il existe un site similaire de ZT  free-telechargement.org

**Comment by TmpName** [comment]
Ils n'apparaissent pas car, il ne sont que sur la seconde page WEB. Et je ne sait pas comment les faire apparaitre sur la page actuelle de kodi (suis meme pas sur que ce soit possible).
En fait je pourrais les faire apparaitre sur la 3 eme page (mais la ca sert plus a rien)

**Comment by Kodigoal** [comment]
Mais sur la plupart des sources , on peut lancer par le menu contextuel 'information' quand on
est sur un titre de film , ca recherche l'info sur TMDP pour les films je crois.
Ya quelque chose à mettre en place dans le code de la source pour activer
cette fonction ? 
Car effectivement sur zt, on a le menu 'information' qu'au moment des liens hosters , mais
ca n'a pas l'air de trouver le résumé/film.
Je pensais simplement que le titre  du film est envoyé sur TMDP et il nous retournait les infos/resumés
ou ca fonctionne autrement ? ou ici sur zt le titre est 'mal envoyé' et donc pas d'infos?
Un peu perdu xD

**Comment by TmpName** [comment]
Ha oui, exact.
En fait pour filtrer les titres Vstream retire tout les tags [] (), et dans cette source les tags n'y sont pas.
Il faut faire un filtrage des titres dans sTilte sans le faire dans sDisplayTitle.

En fait il renvoit aussi BDRIP FRENCH et ca fausse le resultat.

**Comment by Kodigoal** [comment]
Ok merci pour tes précisions :)

**Comment by TmpName** [comment]
Je viens de faire une MAJ sur la beta, (2 fichier a mettre a jours gui.py et config.py), qui devrait resoudre ton probleme, par contre j'espere que cela ne va pas foutre la bordel dans le reste.

**Comment by LordVenom** [comment]
J'ai pas compris pk modifier gui et config quand c'est le site qui envoi pas les bonnes information ?

Normalement sTitle retourne le titre full avec les balises dvdrip ext
sFileName retourne le titre seul.

Je me doute qu' avec tous les changements ça doit plus être partout pareil, ont verras bien.

**Comment by TmpName** [comment]
En fait y a pas de prb avec TMDB, testes avec ZT.
J'ai fais 2 modifs.
La premiere pr le bug des titres, now Vstream utilise sFilename au lieu de sTitle. Now il cherche "titre du film" et pas "titre du film [color]RIP...."

La deuxieme c'est que en titre de la recherche on trouvais le nom nettoye, et du coup a cet endroit je remet sTitle a la place de sFilename.

**Comment by Kodigoal** [comment]
Merci, tout est ok sur ZT.
En fait , comme je garde toujours l'affichage sur 'liste' , j'avais jamais remarqué que les résumés étaient pris sur certains sites directement xD je pensais que tout venait de TMDP pour les films..

**Comment by mino60** [comment]
Merci @TmpName pour la MAJ qui contient  la solution pour ce petit problème
juste une une dernière question, pourriez vous m'éclairer à ce sujet?
tu dit que c'est impossible d'affiché le résumé sur la première page c'est a dire sur showMovies
mais sur l'image on voit bien don un cadre est ce que c'est un flach ou app java
![sans titre](https://cloud.githubusercontent.com/assets/11494048/14902766/50f8ed4a-0d9d-11e6-93ff-e2b27a8041eb.png)

**Comment by TmpName** [comment]
Nope, tu as raisons, c'est bien du html, me souvient plus pkoi j'etais parti sur la seconde page, me souvient plus ca pkoi ca a ete fait comme ca sur ce site, peut etre les calculs du regex etait trop long. A retester.
