### ISSUE TITLE
Idée 3D

### ISSUE THREAD

**Issue by spcxsat** [LordVenom/venom-xbmc-addons#358]
Bonjour,

Serait t'il possible de rajouter dans les genre la catégorie 3D car je voie comme sur zone de téléchargement il y en a de très bonne qualité et avec un son en 5.1 franchement sais top.
Si on pourrais avoir quelque chose pour faciliter les recherche pour ce genre de film ca serait super.

Merci d'avance

**Comment by TmpName** [comment]
Ben vu que je crois que c'est la seule source qui en possede, rajouter une section "3d" directement dans la source, ca prendrait 5 mn.

**Comment by spcxsat** [comment]
Franchement si vous pourriez le faire et si vous avez le temps ca serais vraiment top.

Merci d'avance

**Comment by TmpName** [comment]
Mit en place, mais sur la beta uniquement, pour eviter de forcer une MAJ juste pour un rajout de lien.

**Comment by spcxsat** [comment]
Merci beaucoup, sais nickel pour les recherches.

**Comment by spcxsat** [comment]
Tien t'en que l'on y es on pourrais aussi rajouter la section
HDlight
Pour cette source ca peu être pas mal pour ceux qui on pas trop de débit.
Franchement elle es nickel cette source merci pour votre travail.

**Comment by TmpName** [comment]
Mit en place. (sur beta)

**Comment by spcxsat** [comment]
Merci beaucoup, sais cool.

Un très bon plugin et en plus des développeur super sympa.

**Comment by Xiaomisenz1** [comment]
Tout d'abord salut, et un énorme merci pour votre travail, c'est vrai que c'est une très bonne idée de rajouter la catégorie HD Light et 3D, quelle est la date de sortie des mises à jours ? Tout les mois ?

**Comment by TmpName** [comment]
Yep, prochaine d'ici ce WE je pense.

**Comment by Xiaomisenz1** [comment]
Bonjour, j'ai une petite question, sur uptobox avec la source zt, quelle est la différence entre 'passer en streaming (via uptostream) et rester en direct (via uptobox)? Merci

**Comment by spcxsat** [comment]
Hello,

La différence tu va surtout la voir si tu a un home cinéma car les 3/4 des film en direct on un son en 5.1.

**Comment by TmpName** [comment]
Yep, c'est ca, tu aura une meilleure qualitee si tu reste en direct, mais c'est plus lourd a mettre en oeuvre, et si tu es en gratuit, je te conseille de passer par uptostream, (si tu annules ton film apres l'avoir lance, tu as un temps d'attente qui differe)
