### ISSUE TITLE
Nenu réglage différent

### ISSUE THREAD

**Issue by fredo04** [LordVenom/venom-xbmc-addons#359]
Bonjour. Mes résumés de films redeconne, en français avec des caractères bizarres et sur certains   cite aucun résumés. Lorsque je veux régler la langue dans paramètre des métadonnées je met sur français dans plugin on/off (1/3) idem pour plugin on/off (2/3) je valide sur OK. Quand je reviens pour vérifier si ça bien été pris en compte c'est revenu sur anglais. Je me suis aussi aperçu que mon menu de réglage de metahandler ne ressemble pas à ça http://i.imgur.com/vUeDve4.jpg. Je n'est pas c'est 3 onglets, à la place j'ai metahandler, plugin on/off (1/3) et plugin on/off (2/3).

**Comment by TmpName** [comment]
Alors beacoup de prbs ^^.
Avec les metas desactivées :
1 - Pas de resume : tout les sites n'ont pas de resume.
2- caracteres bizarres, la ca m'interesse, on peut corriger, on a du zapper un truc, tu aurais pas les sites ?

Avec les metas actives, tu devrais avoir 90/100 des resumes, mais la derniere version de kodi (je penses que tu as du mettre a jour) fout la merde, la correction sera en place a la prochaine mise a jour (d'ici le WE). Sinon il te faut chercher toi meme le reglages des metas.

Systeme/Extensions/systeme/dependances/metahandler

**Comment by fredo04** [comment]
Merci pour la réactivité.
Je viens de régler les metas comme indiqué (Systeme/Extensions/systeme/dependances/metahandler) et toujours caractères bizarres, voici une capture d'écran   faite sur cinemay...http://hpics.li/3595c9e
Il y a aussi des sites où pas de résumé, une capture d'écran faite sur filmillimit.......http://hpics.li/f8a09f5

**Comment by TmpName** [comment]
C'est normal, une fois regle il te faut les activer dans Vstream, premier onlget "rechercher les meta-donnnes", si je me souvient bien.
A ce moment la Vstream ne lira plus les resume sur le site mais passera par TMDB.

filmillimit fait parti des site sans resume
cinemay c'est un bug, je corrige de suite.

**Comment by fredo04** [comment]
Bon j'ai poussé les essais plus loin. Les résumés manquent à l'appel sur plusieurs sites.
Filmstreaming.cc et streamingserie.TV
Filmsteamvk
Filmvostft
Full-streamvk et sûrement d'autres.
Les metahandler bien réglé dans kodi (v16.1) et activé dans vstream.
Choses bizarres aussi, lorsque je règle les metahandler sur kodi en anglais et que je reviens sur vstream les résumés sont toujours en français.
À quoi sert le réglage des métadonnées (activées évidemment) de vstream ? Ont ils une utilité vus que cela se règle dans kodi. Quand je regle les métadonnées de vstream en français le réglage n'est pas conservé et reviens en anglais.http://hpics.li/ca97207

**Comment by TmpName** [comment]
Pour les sites sans resumes, c'est normal, tout les sites n'ont pas le resume "pris sur le site" car pas encore mit en place, ou tout simplement car pas affichés sur le site WEB.
Sinon en menu contextuel, tu peux faire afficher les infos, avec le resumes.

Par contre avec les metas activés, c'est Kodi qui va chercher les infos sur d'autres sites, donc tu les auras sans problemes sur Filmsteamvk, je viens de tester.
Il n'y a pas de reglages metadonnes/metahandler sur Vstream, c'est juste un raccourcis vers le plugin de Kodi.
Il faut donc les regler en francais (dans kodi ou vstream, c'est les memes) et de les activer dans Vstream, option "Recherche les metadonnees".

PS1 : Si le pluggin metahandler ne trouve pas le resume en francais, il va l'afficher en anglais.

PS2 : Tout ceci est valable si il n'y pas de bug, car tu n'es pas le seul a voir des prbs, cf https://github.com/LordVenom/venom-xbmc-addons-beta/issues/134

Mais si les reglages ne sont pas conserves, ou si tu n'as pas les memes options en passant par Vstream et par Kodi, je pense que tu as 2 versions de metahandlers qui doivent se battrent entre elles.

**Comment by fredo04** [comment]
OK merci. Du coup j'ai tout réinstaller et tout est rentré  dans l'ordre.
