### ISSUE TITLE
zone-telechargement et compte premium

### ISSUE THREAD

**Issue by teddy72** [LordVenom/venom-xbmc-addons#360]
Bonsoir, tout d'abord un grand bravo pour le boulot que vous faites, c'est vraiment top !
 D'après ce que j'ai pu lire, il semblerait que l'on puisse accéder au lien premium de Z-T (avec compte payant chez un débrideur), depuis la dernière mise à jour , seulement vu que ce n'est pas une m-a-j officielle, je ne sais pas comment l'installer ... Pourriez,svp, m'indiquer la procédure ?
           D'avance merci ....

**Comment by TmpName** [comment]
La mise a jour officielle aura lieu a la fin du mois.
Si tu es pressé tu peux installer la beta, par contre faut etre bourrin, telecharge le zip et extrait le au meme endroit que la version officielle de vstream, par dessus pour ecraser les fichiers.
Le zip >> https://github.com/LordVenom/venom-xbmc-addons-beta/archive/master.zip

**Comment by teddy72** [comment]
Perso , je n'arrive pas à installer la béta, ce n'est grave, je vais attendre bien sagement l'officiel...
Merci pour la réponse aussi rapide ...
