### ISSUE TITLE
Nouveau site

### ISSUE THREAD

**Issue by otho78** [LordVenom/venom-xbmc-addons#361]
Bonjour,

J'ai vu dernièrement sur "Vstream" que vous avez ajouter le site "zone-telechargement", j'ai pensé que vous pouvez peut être faire de même pour le site "www.cpasbien.cm".

Merci d'avance à toute l’équipe pour votre travail remarquable.

Que Dieu vous bénisse.

Otho

**Comment by TmpName** [comment]
Nope, pas possible, car c'est des liens torrents, il est possible de les streamer mais ce n'est plus du tout le style de fonctionnement de Vstream, plutot de pop corn.

**Comment by spcxsat** [comment]
Bonjour.

Yes sais ce que je me suis dit en voyant le site.
Par contre celui-ci correspondrait plus, pas mal de série et de film en HD je le servais de celui-ci principalement avent de connaître vsteam.

http://www.streaming4iphone.fr

**Comment by TmpName** [comment]
Ben en fait la je trouve qu'on commence a crouler sous les sources. Je pense que a partir de maintenant avant de rajouter une source, la question va etre "qu'est ce qu'elle apporte a Vstream qui n'y ait pas deja ?"
Et pour le moment tant que ZT fonctionnera, je connais 1 seul site qui peut faire mieux que lui.

**Comment by otho78** [comment]
Hi,
Could please added "FStram.ONE" as server on Vstream.
Best regards.
Otho

**Comment by sizanic** [comment]
Bonjour,
Ce site sera ajouté prochainement, tel que dit dans cette discussion : https://github.com/Kodi-vStream/venom-xbmc-addons/issues/4226
