### ISSUE TITLE
vstream et les ddl

### ISSUE THREAD

**Issue by teddy72** [LordVenom/venom-xbmc-addons#362]
J'ai découvert vstream il y a peu de temps , et je trouve cette addon excellente .
Par contre, vous etes essentiellement centrés sur les sites de streaming , hormis zone-téléchargement récemment .
Perso, je pense que le ddl apporterait un réel plus à vstream ,particulèrement pour la HD , car ce qui manque c'est une vraie bonne qualité d'image. Pas mal de vos sources de streaming en ligne propose de la HD, mais qui n'en est pas vraiment , ce qui donne une qualité d'image assez moyenne ...
Plusieurs sites de liens de ddl couplés à un débrideur , et là , ce serait le top .
Après , il doit y avoir des contraintes techniques tels que les dl-protect qui doivent rendre la mise en oeuvre compliquée ...
ex. de sites : extreme-download,emule island(ddl),planet-series ...
Qu'en pensez-vous ?

**Comment by TmpName** [comment]
Alors ce n'est pas moi le createur du projet mais sans trop m'avancer je pense que:

1 - Vstream est une appli de streaming pas de DL, pour telecharger des fichiers il y a beaucoup mieux.
2 - Vstream se focalise sur le gratuit, donc sans debrideur.
3 - Je ne pense pas que la HD soit le but de LordVenom, la notion de qualitee est subjective, tu en croiseras qui appelleront du 720p "HD", perso moi m'en fou un peu, la plupart des trucs que je regarde n'existent meme pas en HD, et y a 3 ans ca manquait a personne. Ce serait plutot la diversite, ou la rarete. En resume, plutot une serie obscure que le dernier box office americain.
4 - Vstream comporte deja trop de sources, moi je veux bien rajouter une source du meme genre que ZT mais il faut qu'elle apporte quelque chose de plus, des films qui ne sont pas sur ZT par exemples, et a l'heure actuelle ZT est un monstre. Le jour ou ZT ne marchera plus sur Vstream, on verra pour d'autres sources, mais pour le moment elle suffit largement (quantite, qualite, et beacoup de liens valides)

Pour le debrideur, tu l'auras sur Vstream dans quelques jours.

**Comment by teddy72** [comment]
Mais quelle réactivité!
Je comprends bien ta vision de vstream, et il est vrai que ZT réference déjà beaucoup de liens ddl.
Perso , j'ai un compte chez un débrideur et je verrai bien dans quelques jours ce que cela donne.
Par contre, est-ce normal d'avoir accès au lien ZT uniquement en passant par "toutes les sources" ?
En tout cas, merci à LordVenom et à toi  pour le boulot que vous faites ...

**Comment by TmpName** [comment]
Lol, c'est ma semaine de conges en fait, donc tant que je bouge pas, suis pas loin de l'ordi.

LordVenom te donnera son avis, mais a mon avis si tu recherches l'abondance de video Full HD, il vaut mieux te tourner vers GenesisFR. Le crenau de Vstream c'est plutot le resultat, si tu cherches le dernier "reine du shopping" ou "les beaux malaises", tu l'auras, par contre pour ces 2 exemples ca m'etonnerait que tu les trouves en "HD".

Pour ZT, je peux pas trop te dire, vu que je tourne avec la future version que tu peux trouver sur le site beta, si tu veux tester les debrideurs avant la version officielle. Chez moi ZT apparait un peu partout actuellement, il se peut qu'il ne soit pas active pour les recherches, jetes un oeuil au menu de configuration de Vstream "plugin on/off 3/3"

Pour planet-serie, je le garde sous le coude, il viennent de me trouver des sources pour 2 series introuvables sur ZT.

**Comment by LordVenom** [comment]
Bonjour,

Je sais pas trop comment résumer ma penser, Mais : 
- Oui un addon sous kodi ne feras jamais mieux que les newsgroups ou les torrents
- Oui le stream gratuit a c'est limite en partis du au host qui gratuitement ne fournisse pas le debit suffisant ou encore l'espace de stockage.

Bref disont juste que vStream n'est pas fait pour le grand cinéma ou c'est beau et que le son vous transporte. Non vStream et le compagnon de tout les jours, 
- Celui qui vous évites 1h de pub sur un film de 1h30 (Merci M6), 
- Celui qui vous évites la pub intrusive (Merci tous les sites de streaming) 
- Celui qui vous organise les pages (certain site devrais vraiment fermer tellement leur code source et vilain lol)
- Celui qui vous trouve la série que vous aimez le vieux film que vous adorez. 

Il fait sont job et il le fait bien.Quand je regarde un film mes yeux brille pas parce que c'est beau mais que c'est gratuit.

J'ai absolument pas répondu a une question la :)

**Comment by teddy72** [comment]
Personnellement, je pense sincèrement que les ddl  occuperont de plus en plus de place dans le streaming ,particulièrement couplés à un média center branché sur un petit home cinéma de salon, et ceux pour plusieurs raisons :  
    
- tout d'abord une vrai qualité d'image (oui je sais , je me répète ...) , c'est ce qui manque à l'heure actuelle ,on peut en trouver via torrents , mais avec un temps d'attente de téléchargement  du début du film, ce qui m'ammène au 2° point :  
   - la rapidité du visionnage , couplé à un compte premium chez un débrideur (- de 3 E /mois),on a accès quasi instantanément au début du film.
 -cela répondra à un certain besoin pour certains qui aiment se mater un film sur home cinéma dans de bonnes conditions.
 
Après , il y a des inconvénients:
    -à part zone-telechargement sur vstream, je n'ai pas trouvé d'addon avec lien ddl français , alors qu'on en trouve des tas en anglais.
 -les ddl restent bien moins dispo qu'un torrent,d'ou les difficultés de trouver certains vieux fichiers en ddl.
-le tout gratuit n'existe plus, nécéssité de passer par un débrideur payant (pour les torrents aussi,on est quasi-obligé  de passer par un vpn payant).

Malgré cela, je suis convaincu qu'un addon intégrant plusieurs sites de ddl en lien serait très attendu.
Peut- etre qu'un programmeur pensant comme moi sortira un addon uniquement ddl (un jour , peut-etre),à moins que je me mette au boa, mais là c'est pas gagné...(oui je sais ,elle est nulle ...)

Merci en tout cas pour le boulot que vous faites les gars,tout en étant à l'écoute des utilisateurs , chapeau !

Ps: sérieux TmpName, tu crois qu'en meme pas que je veux me mater  "les reines du shopping" !!!

**Comment by TmpName** [comment]
XD, nope, c'etait un exemple a la con, assez con justement pour ne pas se se trouver ailleurs que sur Vstream.

Pour moi, ta qualite de streaming, sera banale, ..., dans quelques années, le temps que tout évolue, mais a ce moment la, il y en a aura pour demander du 4k parce que que la Real HD c'est moche.

GenesisFR est plus base HD/debrideurs (et les emmerdes qui vont avec) que Vstream, surtout si ce que tu cherches c'est les deniers box-offices.
Le creneau de Vstream c'est les derniers points decrit par LordVenom, quantitee de sources, ergonomie, facilitee et gratuitee. Pour la qualitée on fait au mieux.
Moi cela me convient plus que GenesisFR car je me fout d'avoir tout plein de jaquettes qui apparaissent pour choisir le dernier film encore a l'affiche en Full HD. Je prefere plutot regarder une vielle serie qui en est a la 8 eme saison et que je viens juste de decouvrir, surtout que pr les films, je vais au cine regulierement.

Apres le "tout gratuit", c'est un autre point de vue, tu as ce que tu payes, plus tu veux de la qualitée, plus ca coute, et 3 Euro par mois pour ton exemple, c'est plus que honnette quand le vois les abonnements mensuel de certain bouquet TV.

@LordVenom pour le cote PUB, c'est simple j'ai jete la TV, 5 jours apres avoir installe kodi, je peux plus supporter ca.

Et fais gaffe au serpent.

**Comment by teddy72** [comment]
Merci pour ta réponse , j'attends ce week-end  la MAJ ,pour voir si j'arrive à me connecter avec mon débrideur.
 Sinon, je viens d'essayer genesisFR, et il n'y a pas une seule source ddl , uniquement du streaming en ligne . D'après ce que j'ai trouvé sur le net, vous etes les seuls avec des liens ddl  ,du moins dans les addons français ...
      Bon week-end et bon courage pour la reprise la semaine prochaine ...

**Comment by TmpName** [comment]
Tu as utilise quoi comme hebergeur sur genesisfr ?
La derniere fois que j'ai teste, il n' y avait qu'une source, et ce n'etait que des liens de telechargement.

**Comment by teddy72** [comment]
Dans les paramètres de genesisFR , les sources dispo sont: fullstream,librestream,streamingclic,poypi et zmoviealterista ...

**Comment by TmpName** [comment]
Ha oui merde dsl, c'est ExodusFr maintenant, genesis est mort.

**Comment by teddy72** [comment]
T'as raison , exodusfr référencie des liens ddl, en passant par téléchargementzstreaming ...
Sinon, je viens de faire la mise à jour de vstream et , je dois etre tout bete , mais je ne trouve pas ou me connecter à mon compte realdebrid pour pouvoir accéder aux liens ddl de ZT ...

**Comment by TmpName** [comment]
Lol, nope, ca c'est justement pour les gratuit.
Dans les options, onglet premium, en bas, tu actives "urlresolver" et tu le configures, de la meme maniere que les metadatas.

**Comment by teddy72** [comment]
Je ne pensais pas que le problème venait de là ,car j'avais déjà paramétré url résolver auparavant , mais là je me rends compte qu'une fois authentifié sur real debrid  device , il ne garde pas l'authentication comme avant , des petites étoiles dans les paramètres real debrid de url résolver , quelq'un saurait d'ou viens le problème ? Merci ...

**Comment by TmpName** [comment]
Essaye ca > h ttp://atlasweb.net/configure-real-debrid/

**Comment by teddy72** [comment]
C'est comme ça que je paramétrai urlrésolver , mais ça ne fonctionne  plus ...

**Comment by TmpName** [comment]
Le je peux pas te dire, tu as essaye le "reset" dans les options de l'UrlResolver ?

**Comment by teddy72** [comment]
Oui, j'ai essayé plusieurs fois le reset , sans succès... "les petites" étoiles étaient là quand urlresolver était connecté à  realdébrid, comme un mdp enregistré ...

**Comment by TmpName** [comment]
Il n'y a plus de mot de passe, moi quand j'ai voulu tester, me suis connecte sur internet avec mes mots de passe, puis j'ai lance l'urlresolver qui ma donne un lien, copie dans firefox (puis valide), puis j'ai clique sur "suivant" ou "ok" dans kodi et c'etait fini.

**Comment by teddy72** [comment]
C'est bien ce que je faisais , ensuite il  s'ouvre une fenetre dans kodi "real-debrid resolver authorized".
Mais cela ne fonctionne pas ...
urlresolver est en version 3.0.3 ...

**Comment by TmpName** [comment]
Meme version pour moi.

**Comment by TmpName** [comment]
Ha oui, moi j'ai teste avec la V16 de kodi.

**Comment by teddy72** [comment]
Salut, je viens de tout réinstaller  , et ça fonctionne nickel !
 Merci pour ta patience et bon week-end ...
