### ISSUE TITLE
Ajouter vstream dans meta.

### ISSUE THREAD

**Issue by mac1202** [LordVenom/venom-xbmc-addons#363]
Bonjour j'essaie de rajouter vstream comme source dans l'addon [meta](http://forum.kodi.tv/showthread.php?tid=263065) mais je n ai clairement pas les compétences pour y arriver.
Est ce que quelqu'un de plus compétent aurait une idée de comment y arriver.
Si c'est hors sujet comme question merci de fermer ce rapport de bug.

**Comment by LordVenom** [comment]
Dsl aucune idée de quoi tu parle et je ne comprend pas l'anglais.

**Comment by mac1202** [comment]
c est un addon qui permet de chercher un film ou une série simultanément dans tous les addons disponible sur ton install de kodi. Pour cela il faut écrire un petit fichier json pour indiqué a méta comment communiquer avec les addons vidéo. Il y en a plusieurs dispo ici https://github.com/OpenELEQ/unofficial-meta-players en inspirant de ceux dispo j'ai essayé d'en écrire un pour vstream mais je n'arrive pas a trouver la bonne syntaxe.

**Comment by TmpName** [comment]
Je crois que ca marche avec les librairies, les fichiers strm, et comme sur Vstream c'est encore en beta ....
