### ISSUE TITLE
Voir marque page, nombre pas de soucis mais...

### ISSUE THREAD

**Issue by flowtime** [LordVenom/venom-xbmc-addons#364]
Bonjour, 
Le nombre de marques pages est bien indiqué mais en rentrant dans n'importe quel catégorie "en cours" s'affiche rapidement et rien. J'ai effacé les caches, réinstaller, ça marche une fois et ça recommence.
Je n'ai que 6 marques pages difficile pour retourner dans les menus des sites à chaque visionnage 😀
Merci

**Comment by LordVenom** [comment]
Bonjour, il nous faut ton log au moment ou ça bloque.Impossible pour moi de reproduire le bug

**Comment by flowtime** [comment]
Je vais voir ça je me demande si ça vient pas de kodi depuis la mise à jour openelec

**Comment by TmpName** [comment]
Si tu as bien efface le cache de Vstream, dans les option de Vstream, normallement tu ne devrais plus avoir de marque pages.

**Comment by flowtime** [comment]
J'ai effacé à nouveau le cache. Cela refonctionne. Le soucis apparaît à nouveau quand dans film HD et HD-stream.in j'ajoute le film directement sans rentrer dans "lien direct. Dommage il ne faut pas faire l'erreur...  Faudrait mettre le lien directement dans la liste des film ou empêcher l'ajout de marques pages si on ne rentre pas.

**Comment by flowtime** [comment]
Je viens de retenter avec HD-STREAM.IN même avec lien direct les marques pages ne fonctionnent plus

**Comment by Kodigoal** [comment]
Testé sous (kodi15.2/Android) , pas de soucis sur hd-stream.in pour 1 marque page  Film ou lien direct,
et rajout sur série et autres , ca fonctionne aussi.
Effacer le cache Vstream , ca remet bien à zero les marque pages.
Bon je tourne sur la beta alors
pêtre attendre la nouvelle version Vstream pour voir, t'as pêtre un bug quelque part.

**Comment by TmpName** [comment]
Teste aussi sur la beta, pas de soucis, doit y avoir un truc dans le chemin qui plait pas a linux, tu n'as rien sur les logs ?

**Comment by bk66300** [comment]
bonjour
J'ai aussi se bug sous (kodi16.1/Android 4.4) quand je rentre des lien tv .

**Comment by TmpName** [comment]
C'est quoi que tu appelles liens TV ?
Je viens de tester pour "M6" le lien se met en favoris, mais ca ne marche que 10s (je corrige ca demain).

Sinon pour info, il y a eu une mise  a jour pour les favoris sur la beta, mais qui ne concerne pas ce bug, (pas arrive a le reproduire).

**Comment by bk66300** [comment]
bonjour
Je me suis mal exprimé ,c'est quand je sélectionne une chaine  TV  "libretv.me" opérationnelle ,et  que je la sélectionne comme marque page.Ce marque page s’ajoute aux autres mais bloque quand on veux développer les sous menu "vidéo,série,tv...)  La rien ne s'ouvre.
pour info je suis sous (kodi16.1.ARM/Android 4.4).
Si tu a la solution je veux bien tester.

**Comment by TmpName** [comment]
Bon c'est bon, j'ai finis les maj pour les favoris, dans ton cas mettre a jour la source freebox devrait suffir, mais au vue le nbre de modifs, je te conseille plutot d'ecraser ta version de VStream par la version beta, tu ne perdras aucun fichiers, ni configuration.

**Comment by bk66300** [comment]
## **Bug Résolu**
Effectivement avec ta modificatif la version beta fonctionne parfaitement,plus de soucis avec les marques pages.
Merci.
