### ISSUE TITLE
zone-telechargement 4K

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#365]
Bonsoir  j'ai ajouté quelque ligne sur le script Z-T films 4K et deux pour la musique video en HD et 4K une pour documentaires 4k
en plus de ça j'ai aj 3 section qui manque sur tout le sport pour voire les derniers match foot la section concerts et autoformation video  des leçon sur html5 et python....

http://pastebin.com/86iMAYhK

 certaines section les liens ne s'affiche pas je crois qu'il faux modifier showHostrs!

**Comment by spcxsat** [comment]
Yes très bonne idée jm bien pour les concert, vivement que ca fonctionne bien

**Comment by TmpName** [comment]
Mise a jour du code de mino60 sur la beta.
