### ISSUE TITLE
ajout de site

### ISSUE THREAD

**Issue by andykimpe** [LordVenom/venom-xbmc-addons#366]
bonsoir serait il possible d'ajouter le site h ttp://planet-series.tv

certain animée ou série ne sont disponible que sur ce site

ex : le tour du monde en 80 jours (dessin animée)

merci d'avance

**Comment by TmpName** [comment]
Bonne question, j'avous que ce site est vraiment complet, mais il propose plutot du ddl que du streaming. J'ai souvent eu le meme probleme que toi et j'ai finis sur le meme site.

Sinon pour info, j'ai trouve ta serie sur la source tv-streaming-ch.
