### ISSUE TITLE
Question Zone-téléchargement 

### ISSUE THREAD

**Issue by patoche2025** [LordVenom/venom-xbmc-addons#367]
Bonsoir à tous,

Je viens de remarqué que vous avez rajouté zone-téléchargements.com je viens de tester un film est voici ce qu'il me m'est comme message ATTENTION, Pas de streaming sans premium. Pour voir le film passer par l'option"DL et Visualiser" du menu contextuel jusque là tout va bien je comprends le message ma question est je possède un compte sur real-debrid.com premium comment je peux faire pour l'utiliser dans Kodi du moins est ce que c'est possible déjà, d'avance je vous remercie.

Et pour un info voici un autre site que je connait qui fonctionne comme zone-téléchargement que vous pouvez peut être rajouter voici le lien : ex-down.org

Bien à vous
Patrice

**Comment by TmpName** [comment]
Si tu as la derniere version oui, c'est possible, dans les options de Vstream, l'onglet "premium", en bas tu peux activer UrlResolver, et le configurer pour utiliser RealDebrid.

**Comment by patoche2025** [comment]
Merci pour l'info, je vais tester la solution des que je rentre chez moi ;-).

Et est ce que vous allez mettre ex-down.org aussi dans Vstream ?

Bien à vous

**Comment by TmpName** [comment]
Nope, je pense pas, enfin pas pr le moment. ZT etait vraiment une exception, Vstream se focalise surtout sur le streaming.
Il y a peu de source mieux que ZT, est ce que tu as vu un film sur ex-down qui n'est pas deja sur ZT.
Je pense que si on doit refaire une source de ce genre, ce sera quand ZT ne fonctionnera plus ou peut etre planet serie.

**Comment by patoche2025** [comment]
Hello, 

C'est génial de discuter avec vous car vous très réactif bref, oui un exemple concret http://www.ex-down.org/films-hd/bluray-1080p/31408-les-huit-salopards-multi-avec-truefrench-bluray-1080p.html 

les 8 salopards en truefrench maintenant je suis sur que dans 1 jour ou 2 il va arriver l'autre côté ici c'était juste pour donner un site en plus au cas où hi hi hi.

**Comment by TmpName** [comment]
Ce film est deja sur ZT et depuis plus d'un mois au moins d'apres les coms ^^.

**Comment by patoche2025** [comment]
Autant pour moi alors lol

**Comment by Drakod** [comment]
salut tout le monde 
deja un grand merci pour cet Addon vraiment genial ,

en parlant de compte debrid , je vois que le simply debrid ne fonctionne pas (il me dit a chaque fois fichier introuvable pourtant il sont bien là exemple avec 1fichier )
log kodi:
ERROR: URLResolver: ResolverError Error - From: Simply-Debrid Link: ttps://1fichier.com/?w76azz9roc: SD Resolve: Exception: SD Resolve Failed: Link invalid or not supported

, qq'un a ce probleme aussi ?

@patoche2025 avec realdebrid ca fonctionne chez toi ?

merci pour vos retour

**Comment by patoche2025** [comment]
Bonjour @Drakod avec beaucoup de retard et je m'en excuse pour répondre à ta question oui ca fonctionne même très bien

Bon dimanche
