### ISSUE TITLE
series zone de telechargement 

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#368]
Bonjour @TmpName il semblerait que zonedetelechargement change sa façon de mettre les series en ligne exemple Marseille tout les fichiers premium sont derrière dlprotect dans le meme tiroir ce qui fait que par le biais de vstream impossible de voir les épisodes 
Merci d'avance

**Comment by TmpName** [comment]
Normallement c'est géré, j y jete un oeuil dans la journée, ca devrait remarcher ce soir.

**Comment by sebi0606** [comment]
Merci @TmpName toujours aussi réactif bon week end
