### ISSUE TITLE
Live TV et comment choisir la langues?

### ISSUE THREAD

**Issue by patoche2025** [LordVenom/venom-xbmc-addons#369]
Bonjour comment allez vous,

C'est encore moi déslé de encore vous embêter mais voilà, j'habite en Belgique du coup le live TV ne fonctionne pas alors je me demander si je passe par un VPN est ce que ca pourrait marcher? 

Autre question qu'elle est la démarche a faire pour changer la langues d'un film quand on prend un film ou il y est marqué Multilingue

Merci d'avance

**Comment by TmpName** [comment]
Heu, tu es sur de parler de Vstream ?
De memoire je n'ai jamais vu ni de choix de langue !

Sinon pour le coup du VPN, c'est possible, certain fournisseurs geolocalisent leur services, cela depend des fournisseurs TV.

Pour la langue, il ya plusieurs moyens, moi j'affche le menu et en bas a droite il y a une icone d'haut parleur dans un rond, dedans tu peux choisir le flux audio.

**Comment by LordVenom** [comment]
@TmpName  Ha perso j'ai regarder des manga sur ZT, marquer français et ça parler asiatique j'ai du modifier la langue via l'icone audio dans la barre de lecture.

**Comment by TmpName** [comment]
Ha ?
Moi suis un fou, j'ai cru que c'etait normal, et je traduisais en direct avec le dictionnaire Japonais/Francais sur les genoux.

Jamais eu ce cas encore, faut dire que je passe pas souvent par ZT.

**Comment by patoche2025** [comment]
Mille merci pour les renseignements
