### ISSUE TITLE
Réduire le nombre de clics

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#371]
Salut
Force est de constater que vstream est maintenant devenu un outil super puissant et fiable ... donc chapeau bas.
A la maison, les principaux utilisateurs sont ma femme ou mes enfants ... et tous me remonte le même reproche : il y a trop de clic pour parvenir au lancement d'un film
exemple:
lancement vstream --> choix toutes les sources --> choix site --> recherche du film --> choix hébergeur --> éventuellement choix streamin ou qualité originale (uptobox)

Je vous soumets donc ce souhait d'évolution : diminuer le nombre de clics

ma 1ere proposition : dans les options donner le choix à l'utilisateur de choisir un hébergeur préféré, qui ne serait donc plus demandé par la suite mais sélectionné automatiquement (particulièrement intéressant pour ceux disposant d"un premium)

ma 2eme proposition : pour uptobox, donner le choix à l'utilisateur de choisir entre streaming et qualité originale, et donc ne plus demander ce choix au lancement de chaque film

merci pour vos avis

**Comment by TmpName** [comment]
Tu n'est pas le seul a faire cette remarque. Mais c'est assez complique pour convenir a tout les usages.

1 - lancement vstream
Bon la pas le choix.

2 - choix toutes les sources
3 - choix site
4 - recherche du film
Pour ca tu peux directement passer par la recherche globale, en desactivant ou activant les sources que tu preferes, tu peux meme faire comme LordVenom qui s'est fait 2 recherches persos "film recent" et "vieux films" mais ca risque de bugger pour certains sites ou il y a une recherche pour les series et une pour les films (la aussi c'est un truc a appronfondir)

5 - choix hébergeur.
La je prefere afficher tout les hebergeurs, car si tu n'en affiche qu'un et que celui la deconne, tu te retrouves avec une page vide ou un lien ne fonctionnant pas alors que tout le reste peut fonctionner.

6 - le choix pour uptobox
La on peut desactiver le choix "streaming" si la personne est premium, je vois pas pkoi elle voudrait le choix version stream ?

Apres si il y en a qui ont des idees pour l'ergonomie ca m'interesse.

**Comment by LordVenom** [comment]
Salut, 

Pour afficher uniquement les sources - paramètre de vstream / général / (afficher l'accueil par catégorie)

Perso si je sais quoi regarder j'utiliser la recherche global si je sais pas la recherche visuel.

**Comment by chataigne73** [comment]
oui merci Lord, j'ai vu ça  ;-)

maintenant j'aimerais bien une option pour démarrer vstream directement sur un site donné ;-)

**Comment by spcxsat** [comment]
Pour ce qui es des type d'affichage pour zone de téléchargement comment ce fait t'il que nous avons pas tous les type comme pour les autre site?

Et pour ce qui es de la recherche visuel quand je change le type d'affichage, il ne le garder pas en mm mémoire comme pour les autres site aussi ☺

Merci

**Comment by TmpName** [comment]
C'est le choix du createur du code pour ce site, j'ai laisse tel quel, mais si ca te derange je peux te dire comment corriger cela, juste une ligne a commenter.

La recherche visuelle, c'est le meme combat, le but de cette fonction, c'est de fonctionner via vignette, donc le mode d'affichage est choisit par Vstream (pour afficher les affiches).

**Comment by spcxsat** [comment]
Ah ok.

Mais yes je veux bien connaître la ligne à commenter ou à rajouter ou je sais pas ☺ et où la placer.

Merci beaucoup

**Comment by TmpName** [comment]
ligne 277
>>xbmc.executebuiltin('Container.SetViewMode(500)')

Tu la remplace par 'pass', en ne rajoutant/supprimant surtout aucun espaces.

**Comment by spcxsat** [comment]
Il faut la remplacer comment,

xbmc.executebuiltin('pass')

Ou juste comme cela

pass 

'pass'

Car j'ai essayer mais sa ne change pas j'ai certainement mal fait lol

**Comment by TmpName** [comment]
oui juste
>>pass

**Comment by spcxsat** [comment]
Ok merci,

Je vais tester ca dans l'après midi la je suis au taf

**Comment by spcxsat** [comment]
Re,

Bon j'ai teste éditer comme ceci, pour zone de téléchargement

    #tPassage en mode vignette sauf en cas de recherche globale
    if 'index.php?q=' not in sUrl:
        pass
     
    if not sSearch:
        oGui.setEndOfDirectory()

Mais je n'arrive toujours pas a avoir certaine vue comme "information du média 1 / 2 / 3"

**Comment by TmpName** [comment]
En fait tu as juste supprime la ligne ou Vstream force l'affichage en mode vignette, now c'est a toi de selectionner celui que tu veux, a moins que tu ais deja teste et qu'il te manque des modes ?

**Comment by spcxsat** [comment]
et je mes quoi ou si je voudrais par exemple

information du média 3

**Comment by TmpName** [comment]
En fait quand tu changes le mode directement dans kodi via le menu de gauche, ca va etre memorise, il va te falloir le faire plusieurs fois pour le "page suivante" par contre.
Sinon si tu veux le forcer directement dans l'addon il te faut juste modidier le '500'
A l'epoque j'avais recupere ca : 
>>#<views>551,504,503,508,515,50,51,500,550,560,501,572,573,574,570,571,505,511</views>
#viewmode = 500 Film
#viewmode = 503 Film + Information
#viewmode = 50  Liste

**Comment by spcxsat** [comment]
Hello,

le probleme c'est justement que dans le menu de gauche, je n'ai pas information du média 3, mais juste que pour zone de téléchargement, c'est ça que je trouve bizzare alors que je les ai bien pour les autres sites.

C'est comme si dans ce scrypte il manquait des infos pour pouvoir avoir tt les vues que nous avons avec les autres sites 

En tous cas merci pour votre aide c'est sympa

**Comment by TmpName** [comment]
Ha oui tu as raison, je viens de comprendre.

Mais la aussi c'est un choix du createur de la source, il affiche les films comme des repertoires au lieu de sources, il utilise oGui.addDir au lieu de oGui.addTV/oGui.addMovie.

La modif est plus complexe la, car selon que ce soit des films ou des serie, Vstream ne marche pas pareil, donc sa solution est tres bonne. Je n'ai pas teste oGui.addMisc mais je pense que tu auras moins de problemes en laissant tout par defaut.

**Comment by spcxsat** [comment]
Yes je pense que je vais laisser tomber pour l'affichage lol.
On dirais que ca devient un peu compliquée la pour les modif.

Merci quand même de m'avoir consacré de votre temps

**Comment by TmpName** [comment]
J'ai une mauvaise nouvelle @chataigne73 je fais un retour arriere pour uptobox, tu vas avoir un clic de plus le temps de trouver un autre moyen.

Il y en a (et j en fais parti) qui passe par le stream meme si il sont premium. Donc soit on trouve une solution, soit faut rajouter une option pour ce host dans la config.
