### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by spcxsat** [LordVenom/venom-xbmc-addons#372]
Bonjour,

Je voulais savoir quel es l'addon qui permet dans KODI d'afficher l'image du captcha ex sur zone de téléchargement.

Car sais vrais que sous les version 16.1 de KODI et moins il s'affiche mais pour les version en alpha 17 le clavier sort bien mais l'image n'apparaît pas donc un peu compliquée pour taper la solution.

Me suis dit que peut-être il manquerait l'addon pour le faire s'afficher l'installer et nickel

Merci d'avance

**Comment by TmpName** [comment]
C'est possible, mais j'attend que la version 17 soit officielle, elle risque de changer (et c'est sur qu'elle va etre modifiee) avant de faire les modif de mon cote, si ca se trouve le probleme vient de son cote.

**Comment by spcxsat** [comment]
Oui certainement que le problème vient de leur côté.
Bien pour ca que je demandais si il y avais une extension bien précise qu'il fallait avoir dans KODI pour pouvoir le voir. Me suis dit qu'elle y était peut-être pas installer par défaut.

**Comment by TmpName** [comment]
Nope, ce ne sont que des fonctions python de base, mais ca ne les empeches pas de modifier leurs actions sur kodi, c'est fort possible qu'il faille modifier le code a la V17, mais vu qu'ils risquent encore de changer le code d'ici la ....

**Comment by spcxsat** [comment]
Ok je comprend mieux maintenant

**Comment by spcxsat** [comment]
J'aurais bien une solution si non mais je sais pas si sais applicable.
Moi qui utilise urlresolver par exemple, on pourrais pas par exemple faire que si on l'utilise le code es gérer par celui-ci, comme ca plus besoin de le taper

**Comment by TmpName** [comment]
Tu veux dire utiliser un code qui lira le captcha a ta place ?

Mais rassure toi, quand la V17 sera officielle on corrigera le probleme pour qu'il s'affiche.

**Comment by spcxsat** [comment]
Oui voila car il me semble que urlresolver le fait et vue que je l'utilise avec un débrideur, sa aurait été nickel

**Comment by TmpName** [comment]
Je l'ai pas vu dans UrlResolver, apres il y a des sites qui propose ce systeme, ou alors des sites collaboratif ou tu aides les autres pour tes captcha et eux en retours t'aident pour les tiens mais franchement ca demande a mettre en place une usine qui n'est pas forcement fiable.

**Comment by spcxsat** [comment]
Pourtant il en parle bien dans urlresolver du captcha



Et on trouve la dernière version 3.0.4 ici.

https://offshoregit.com/tvaresolvers/tva-common-repository/raw/master/zips/script.module.urlresolver/

**Comment by TmpName** [comment]
J'ai pas vu mais "Add support for recaptcha V2" veut dire qu'ils gerent la v2 du captcha de google, ca t'affiche des images a selectionner.

**Comment by spcxsat** [comment]
Ok merci des précisions

**Comment by spcxsat** [comment]
Re,

Bon j'ai teste éditer comme ceci, pour zone de téléchargement

    #tPassage en mode vignette sauf en cas de recherche globale
    if 'index.php?q=' not in sUrl:
        pass
     
    if not sSearch:
        oGui.setEndOfDirectory()

Mais je n'arrive toujours pas a avoir certaine vue comme "information du média 1 / 2 / 3"
