### ISSUE TITLE
Dl protect

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#373]
Bonsoir @TmpName souci avec dl protect depuis ce soir malgré le captcha demandé rentré on arrive sur rien 
Captcha rentre sur l'ordinateur c bon ça marche si tu peux jeter un œil 
Merci d'avance

**Comment by TmpName** [comment]
Tu as un exemple pour tester ?
De mon cote pas de probleme, tu es sur que tu n'etais pas tombe sur un captcha illlisible ?
Tu n'as pas kodi V17 Beta ?

**Comment by sebi0606** [comment]
Non je suis sur kodi 16 je refais des tests aujourd'hui je te tiens au jus

**Comment by sebi0606** [comment]
ça marche désolé @TmpName
