### ISSUE TITLE
Sources émission TV 

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#374]
Hello
Je ne sais pas si vous connaissez cette source ou si c compliqué de l'ajouter mais il y a bcp films, séries et émissions de tv.
htt p://w ww.cocostreaming.com/tv-spectacles-en-streaming-4/5-1-0-0.html

**Comment by Drakod** [comment]
salut ,

je viens de tester cest pas mal du tout merci canopre

**Comment by TmpName** [comment]
Le site est pas mal mais moi personnelllement je ne me lance dans la creation de source uniquement si tu trouves un film dessus qui n'est pas deja sur Vstream (ou avec plus de sources, meilleure qualitée, ect ...)

**Comment by canopre** [comment]
Je comprends et comme il y a bcp d'émissions TV sur cette source je trouvais intéressant de vous le signaler.

**Comment by TmpName** [comment]
Ha oui mince, j'avais juste teste les films et series.
Dsl, je le rajoute en TODO list, j y jetterais un oeuil plus tard, merci.

**Comment by canopre** [comment]
Y'a pas d'urgence : C'était juste pour essayer de se rendre utile :)

**Comment by Drakod** [comment]
Salut 

Dans la même ligné voici un site sympa pour les replay récent toute chaînes 

http://mareplaytv.fr/


Si ça peux servir
Ciao

**Comment by TmpName** [comment]
Moi je le trouve pas mal ce site.

**Comment by TmpName** [comment]
Sinon je pense qu'on pourrait revoir la partie Replay.
De memoire il y a plein de site avec une partie replay, mais sur la page home quand on va dans replay il y a juste 3 sites.

Puis j'ai voulu les tester avec une recherche globale, et me suis retrouve comme un con : Serie ? Documentaire ?

Ca generait si on regroupait la recherhce des documentaires avec celle des replays ?

Apres j'hesite encore entre les 2 sources de ce topic, la premiere ne fait pas que les replay, mais le second le fait mieux.

**Comment by TmpName** [comment]
Mareplay a finir > https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/trash/mareplaytv.py

A peu pres tout doit fonctionner, prbs dans les "genres".
