### ISSUE TITLE
Petits Problèmes Information Film & Acteur

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#375]
Hello

Avez-vous le même problème :

- Quand je sélectionne "Information" sur un film : J'obtiens bien une fenêtre d'info avec le résumé du films et la liste des acteurs.

- Mais la photo des acteurs ne s'affiche pas

- Et quand je clique sur un acteur j'ai ce message d'erreur suivant : "Aucun résultat trouvé."

- J'ai essayé d'installer extended.info.script mais comme vstream est pas compatible : ca ne va pas non plus.

Dans la fenêtre "Information" j'ai également un problème avec les Boutons "Lire" et "Bande-Annonces" qui ne fonctionnent pas :

Quand je fais "Lire" ça mouline quelques secondes et ça fait...rien.

Quand je fais "Bande Annonce" : Ça ouvre Youtube mais les vidéos proposées ne correspondent pas au film en question et il y a un message d'erreur quand je veux quitter youtube pour revenir à vstream. 

J'utilise le skin aeon.nox.silvo.

Remerciements anticipés pour votre aide

**Comment by LordVenom** [comment]
Bonjour,

- La requête ne retourne pas les photos donc impossible de les afficher.
- Aucun control non plus sur les boutons et sur la bande annonces retourner.

Pour extended.info.script je sais pas si ça vaut vraiment le coup de l'ajouter quand vous serais plus de 100 a le demander il seras intégrer :)

**Comment by TmpName** [comment]
Il te reste a ouvrir 99 autres comptes ^^.

Sinon pour tes problemes, c'est l'addon metahandler qui gere cette partie, pas Vstream.
J'ai fais des tests avec d'autres addons.
Cliquer sur un acteur ne marche pas.
Boutton "lire" a reparer c'est un probleme de chemin
Pour la bande annonce, j'ai pas encore pu tester, pas trouve de film avec, mais ca lance la video indiquee sur TMDB, par contre ca devrait revenir sans bugs, donc a reparer.

Sinon pour la bande annonce, moi aussi ca commmence a me manquer, je commence a me dire que de faire une option en menu contextuel qui prend la premiere video sur youtube pourrait etre utile, a part la langue, j'ai toujours trouve la bne video en recherche directe, reste a savoir si on utilise l'api de google (faudrait aveoir une cle) ou le scrapping classique (juste pour un film ca devrait suffir)  ?

**Comment by canopre** [comment]
**"Il te reste a ouvrir 98 (j'ai vu arzaz) autres comptes ^^."**

Je sais pas qui c Arzaz mais j'ai déjà pas bcp de temps de dispo, j'en consacre un peu à faire le béta testeur : je voudrais pas en + passer pour un Troll...

**Comment by spcxsat** [comment]
Bonjour,

Excuser moi de rajouter un commentaire.

Si sais KODI qui gère ca, comment ca ce fait que des addonsz comme Genesisfr les gère complètement par exemple, il utilise peut-être un autre fournisseur d'information alors.

En tous cas Vstream surpasse tous les addon que j'ai pu tester, les info sais la cerise en plus, mais sais vrais que quand tous es parfait sais hummm génial

**Comment by TmpName** [comment]
@canopre lol, c'est la seconde personne qui a fait la meme demande que toi, donc plus que 98 et LordVenom sera force de le mettre en place.

Sinon plus serieusement pour vous repondre a tout les deux, Vstream fonctionne de deux maniere.

Sans metas, et la c'est Vstream qui gere les infos quand vous faites "info" en menu contextuel, ce menu la est gere a 100/100 par Vstream (et il est plus petit parce qu'on est feneant), et on peut rajouter X options en plus (comme notre propre systeme de bande annonce)

Avec les metas activés, la c'est kodi qui gere en fonction de VOS reglages (choix des scrappers, ect ..) on fait just appel a des fonctions internes a kodi. En fait c'est le meme systeme qui est utilise pour vos fichiers locaux sur votre disque dur.

C'est un choix de LordVenom, je suis d'accord avec lui, je prefere une version de Vstream plus legere et rapide, je vais rarement chercher des infos sur un film et ca me generais de devoir attendre pour rien.

La version sans metas, me permet d'avoir des infos mais uniquement si je le desire, et d'afficher les films plus rapidement.

En fait si la personne veut la version rapide > sans metas mais infos gere par Vstream
Si elle veut la meme chose que pour ses films locaux > version avec metas.

Faut voir avec le chef, mais ca m'etonnerait qu'il veuille alourdir Vstream (a mon avis le coup des 100 users vient de la ^^). Du coup pour la version avec Meta, je prevois pas trop de changement.

Par contre je peux ameliorer les infos sans meta active, je cherche un moyen leger de mettre ca en place (pas envie de prendre une cle API pour youtube juste pr ca), mais normallement on devrait avoir les bande annonces gerées a 100% par Vstream.

**Comment by TmpName** [comment]
J'ai commence a mettre en place les Bandes annonces, pour le moment elles marchent avec le menu 'information", la ou lui apparait le menu "bande annonce" aussi juste dessous.

En test sur beta, je sais pas encore mettre en place le smilblic.

**Comment by spcxsat** [comment]
Yes cette addon fonctionne bien pour les films en local

mes quand les films sont en streaming comme avec vstream elle es pas dans le menu contextuel

**Comment by TmpName** [comment]
Nope, c'est pas le lien vers l'addon lui meme, c'est juste un fichier python justement pr pouvoir le rajouter en menu contextuel dans VS.

**Comment by spcxsat** [comment]
ah ok je les pas trouver celui-ci

**Comment by LordVenom** [comment]
Faudrait pouvoir passer l'info au bouton de la popup information comme ça ont gagne une place dans le menu context et ça reste logique.
Pour extended, 2 solution l'importer a l'install de vStream ou permettre la popup extend seulement si l'addon et installer.

**Comment by TmpName** [comment]
Ca c'est possible, mais ca ne marchera que pour ceux qui ne passent pas par les metas, eux auront la version de kodi, qui n'est pas forcement presente ou mauvaise et non gerable.
C'est pour ca que j'esite pour savoir quoi en faire. Au pire je fais ca pour la version sans meta, y aura juste un lien de plus pr ceux qui veulent les metas.

L'importer a l'install de Vstream, suis pas pour, c'est tres lourd comme addon et peu de gens s'en serviront, par contre l'utiliser si il est present ca doit ete possible avec 3/4 lignes dans le fichier config.py vers la ligne 223 et en utilisant le code du lien que j'ai donne un peu plus haut.

**Comment by spcxsat** [comment]
Yes ca serais cool ca.

Vous pourriez svp nous faire ca pour la version bêta, je pourrais vous en dire des nouvelle car l'addon es déjà installé sur tt mes installation de vstream. Et si j'ai bien compris il faudra désactiver les meta pour ne pas faire de requête avec metahandler.

Merci beaucoup en tous cas surtout si vous vous ne vous en servez pas.

**Comment by TmpName** [comment]
Lol, c'est juste pour memoire, personne a dit qu'il allait se pencher dessus, moi j'ai juste fais les bandes annonces, rien a voir avec l'addon.

Et la je corrige en priorite les favoris.

**Comment by canopre** [comment]
Pour revenir rapidement sur le sujet " extendedinfo" il est installé avec tous les thèmes Aeon : Ca fait quand même du monde :)
Et pour ma part je le trouve vraiment très class : n'hésitez pas à le tester à l'occasion : Ca vous motivera peut-être de l'inclure en option pour ceux qui sont équipés.

En tout cas merci pour votre réactivité : Si je pense à d'autres petites améliorations : je n'hésiterais pas à vous en faire part.

Bon week end à tous !

**Comment by spcxsat** [comment]
Hello,

moi je me pose une question,

Pourquoi nous avec Vstream on utilise pour les meta metahandler pour les infos

Alors que KODI lui utilise The Movie Database qui lui fonctionne très bien pour les fichier local, les info sont complete, les miniature pour les acteur sont présente, enfin bref a l'aire de mieux fonctionner avec l'interface de KODI

**Comment by TmpName** [comment]
Metahandler utilise TMDB et IMDB, mais meme pour les fichiers locaux, si je demande a kodi de tout faire tout seul, il deconne parfois, il faut qu'il me propose des choix quand il n'est pas sur pour avoir de bon resultats.

**Comment by LordVenom** [comment]
Bon on vas l'aisser le menu context bande annonce impossible de modifier le dialog info avec meta.

**Comment by TmpName** [comment]
Non c'est clair, j'ai essaye aussi, c'est vraiment pas l'ideal le dialog integre a kodi, tu ne peux absolument rien toucher.

**Comment by canopre** [comment]
Merci pour vos efforts :+1:

**Comment by spcxsat** [comment]
Ok merci pour vos réponsse

**Comment by LordVenom** [comment]
C'est la misère avec nos propre info. Avec meta activer:

1) ont peux modifier toutes les bandes annonces mais il faut toutes les chercher en meme temp trop lourd

2) ont peux dire a metahandler de faire une mise a jour d'une bande annonce mais on doit recharger la page complète de tout les films pour qu'il le prenne en compte.

Je continue de chercher mais j'ai un doute la.

**Comment by LordVenom** [comment]
@canopre  extended.info.script mise en place une option permet de l'utiliser a la place de la popup d'information classique.a découvrir à la prochaine mise a jour officiel dans 15jours.

**Comment by spcxsat** [comment]
Yes cool ca.

**Comment by canopre** [comment]
Yes c top ca ! J'ai hate de le tester :)
Merci bcp !

**Comment by TmpName** [comment]
Ha bon ? Tu as deja trouve les 98 users qui manquait ?

Ou alors ils sont directement venu chez toi pr frapper a ta porte ?

**Comment by LordVenom** [comment]
Lol non mais qu'ont recherche sur metahandler ou sur extended.info.script y pas une grande différence, mais comme ont peux s'en passer je l'active pas a l'installe de vStream.

**Comment by TmpName** [comment]
Ha ? ca je savais pas ?
extended.info.script possede son propre scrapper ?

**Comment by canopre** [comment]
Au sujet de extended.info.script : je ne sais pas si vous avez vu mais dans la config on indique l'addon video à utiliser pour la lecture des vidéos ?
Il doit donc y avoir un bout de code à lui fournir pour que vstream soit proposé en choix d'option ?

**Comment by LordVenom** [comment]
@TmpName , Oui le script recherche les infos a partir du non comme metahandler.

@canopre , J'ai pas vue cette option et pour lire quoi ? chez moi ça donne juste des information sur le film et quelques video youtube qui ce lance sans soucis.

**Comment by canopre** [comment]
Il y a également un lien pour lire les films.

**Comment by canopre** [comment]
Bonjour à tous,
vStream vient de se mettre à jour et c'est vraiment sympa de pouvoir utiliser extended info pour afficher les infos des films.
Mais quand j'affiche les infos d'un film avec extended info: il y a un gros bouton "App Integration" et vStream ne fait pas partie de la liste : ducoup la recherche de film et le bouton lecture ne fonctionne pas.

Avez-vous svp la possibilité d'intégrer vtsream à la liste des addons compatibles ?

Je n'ai aucune notion du temps et des efforts que cela nécessite mais je vous remercie d'avance d'y penser car ca finaliserai vraiment la navigation dans vstream avec un rendu vraiment chouette!

++ et bonne fin de we.

**Comment by LordVenom** [comment]
Dsl toujour pas de bouton chez moi 

http://www.hostingpics.net/viewer.php?id=481899screenshot000.png

**Comment by canopre** [comment]
Hello Lord,
Merci pour ton aide.
Pour ma part j'ai 2 boutons de +
1 bouton play qui ne fonctionne donc pas
+ 1 bouton "AppIntegration" qui quand je clique dessus me sort une liste d'addon video dans laquelle je ne retrouve pas vStream.

Je joins 2 copies d'écran correspondantes :
http://hpics.li/6e32b9b
http://hpics.li/1d3f8ea

Ca serait chouette que vStream soit intégré et que ducoup les liens vers les films fonctionne quand on fait une recherche par acteur.

Au fait : Comment tu trouves extended.info ? C'est pas mal comme présentation ?

**Comment by LordVenom** [comment]
Je pense que l’intégration et fait pas extend mais je vais vérifier.
Oui c'est pas mal sauf quand ont utilisent la souris ça bug un peux quand même.

**Comment by canopre** [comment]
Merci d'avoir intégré  extended.info.script aussi rapidement : C'est vraiment sympa !
