### ISSUE TITLE
Page de recherche : Lien Recherche Alluc.ee

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#376]
Bonjour,
Quand je fais une recherche, sous les liens de Recherche de Films, Séries, Animés, Documentaires, et avant l'historique,

Il y a un lien de recherche qui s'appelle Alluc_ee, qui donnent des résultats mais dont les liens vers les vidéos ne fonctionnent pas.

Il sert à quoi ce lien ? Comment le supprimer ?

Merci d'avance pour votre aide.

**Comment by TmpName** [comment]
Ha oui, je corrige de suite.
En fait c'est une recherche speciale sur le site alluc.ee, c'est un moteur de recherche tres performant meme si vu le nbre de sources gerées par Vstream, il a peu de resulats nouveaux.

Mais il est tres rapide, plus que la recherche de VStream.

Pour le supprimer, faut encore modifier le code, mais je le met a jour, il va remarcher bientot.

**Comment by TmpName** [comment]
Alluc mit a jour.
