### ISSUE TITLE
Problème liens Sokrostream

### ISSUE THREAD

**Issue by bast12** [LordVenom/venom-xbmc-addons#377]
Bonjour et merci pour ce fabuleux travail. Depuis hier j'ai un problème avec Sokrostream je ne vois qu'un lien pour chaque film alors qu'auparavant il y en avait 4 ou 5 sur plusieurs hébergeurs différents.

Merci encore pour l'addon.

**Comment by TmpName** [comment]
Confirme, je repare ca dans la soiree.

**Comment by TmpName** [comment]
Mit a jour, fichier a modifier sois meme, ou mise a jour chez toi en auto dans max 3 jours.

**Comment by bast12** [comment]
Merci

**Comment by bast12** [comment]
j'ai réessayé après la modif ça remarche normal :+1:
