### ISSUE TITLE
Afffichage des marques pages 

### ISSUE THREAD

**Issue by nexcom92** [LordVenom/venom-xbmc-addons#378]
Tout d'abord je voulais vous féliciter pour ce plugin qui est tout simplement extraordinaire.  
J'ai un petit souci avec les marques pages.. J'ai ajouté des films à partir de la liste des meilleurs films de themoviesdb. 
Le nombre de favoris est bien indiqué en jaune a l'entrée du menu marques pages mais je ne les retrouve dans aucun dossier.
Il y a t'il une possibilité de les afficher?
Merci encore pour votre travail et votre disponibilité .

**Comment by TmpName** [comment]
Ha yes, c'etait la le bug.
Put1 je cherchais partout, sans trouver, merci, effectivement y a un gros soucis ici. Je corrige ca dans la journee et je te tient au courant.

**Comment by TmpName** [comment]
Bon grosses modifs.
Si tu veux tester par contre, il n y a qu'un moyen c'est d'ecraser ta version par la beta, trop de fichiers bidouillees.

En plus de la correction du bug, maintenant il y a le nombre de favoris par section qui apparait, j'ai rajoute une section pour la recherche visuelle, et une section pou les liens bugges (pour pouvoir les supprimer)

**Comment by nexcom92** [comment]
Bravo pour cette modif aussi rapide. Encore un grand bravo pour le boulot et la réactivité.
Pour écraser ma version par la bêta j'ai copier le dossier du zip directement dans mon dossier addon (j espère que c’est la bonne manip) et miracle, ça marche parfaitement. J avais supprimer la DB et les réglages  donc je suis bon pour me retaper la liste et les configs mais ça fonctionne c'est le principal.
J'ai bien le nombre de MP par sections entre parenthèses et je les retrouvent dans "recherche visuelle". 
Dernier petit truc mineur, quand je navigue dans la liste de films ou de séries, certaines d’entre elles n'ont pas les bonnes infos ni les bons fanart . Est ce possible de choisir les bonnes infos un peu comme dans les films telechargés sur le HDD. Merci

**Comment by TmpName** [comment]
Tu aurais pu garder la DB, en fait j'ai prevu le truc et tout les liens "perdus" vont se retrouver dans une categorie speciale qui n'apparait que en cas de probleme.
Tu ne perd aucun reglage en ecrasant les fichiers car toute la config est dans un autre repertoire.

Pas les bonnes infos, tu veux dire hors recherche visuelle et avec meta actives ?
Comme les films telecharges c'est les scrappers qui gerent le truc, plus ou moins precisement, par contre je ne sais pas comment les "corriger", mais se serait un boulot de titan pr toi, car les liens ne sont pas fixes (les sources web changent).
Si tu les rajoutes en librairie, la c'est peu etre possible car c'est gere comme des fichiers locaux. Mais pareil un jour ou l'autre ton lien ne sera plus valide.

**Comment by nexcom92** [comment]
je pensais que c’était ma config qui merdait alors j ai tout essayé avant de poster.
Pour les métadonnées, c'est au niveau de la recherche via themoviesdb (j utilise les meileurs films) vu qu'il prend les infos sur le site je ne comprends pas pourquoi les infos ne correspondent pas. Mais c'est juste un détail vu que c'est le bon film qui est recherché en fin de compte. 
Encore une fois merci. Si il y a un paypal pour payer une bière balance moi ca.

**Comment by TmpName** [comment]
En fait c'est le mode de fonctionnement de Vstream.
Les autres addons partent du bon film selectionne d'apres les bases online, donc tu as le bon artwork, le bon resume, les bonnes affiches ect ... et apres ils le cherchent sur internet.
Vstream fait l'inverse, il trouve d'abord le film sur internet et apres avec le nom il essaye de retrouver le film pour avoir les artwork et ect ..

Les autres ont les bonnes images mais pas forcement le bon film ou meme pas de film du tout.
Vstream aura le bon film (et plein de faux resulats en passant) mais pas les bonnes images.

Quand tu n'as pas les bonne images/resume fait un test directement sur TMBD, tu veras ce n'est pas fiable a 100/100, souvent a cause d'un article ou d'une faute de frappe.

Apres Vstream est capable de trouver les bonnes affiches et le bon resume pour au moins 80/100 des sites si tu desactives les metas (mais y aura moins de bonus, artwork/acteurs/ect ..)

**Comment by nexcom92** [comment]
Au moins tu as pris les choses dans le bon sens, le but étant de voir le bon film et de ce coté la je n'ai encore eu aucun souci. Merci encore

**Comment by TmpName** [comment]
Ha oui par contre, vu que tu as installe la beta, je crois que tu risque d'avoir des prbs sur ZT, j'ai mis en ligne un mauvais fichier, mais dans 3 jours max tu auras la correction chez toi sur la page d'acceuil de Vstream.

**Comment by TmpName** [comment]
Ha oui, par contre, j'ai fais une boulette, j'ai mit en ligne un mauvais fichier pour ZT sur la beta, donc si tu as des problemes c'est normal, MAJ chez toi sur la page d'acceuil de Vstream dans max 3 jours.
