### ISSUE TITLE
zone-telechargement 4K section film ?

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#379]
Bonjour à tout..j'ai remarqué dernièrement qu'il n'existe pas des films blu ray en 4k sur z-t car un film 4k ultra hd de deux heurs  son volume et de 100 Go à 160 Go (mkv) 10-15 Go si il est converti en mp4 Ce qui est sur, c’est que steamer ou télécharger 100 Go pour un film, ça fait beaucoup (en place et en temps).
YouTube proposent déjà des films et séries et video à streamer en 4K ultra hd.je crois qu'il reste quelque mois pour voire des films 4k sur z-t par contre en peux crée une section 4k sur YouTube

remarque tout les titres des films comme blabla(720p)HD pas de problème pour voir leurs liens
cependant les titres des films ultra hd ou hd comme blabla1080p- leurs liens ne s'affiche pas ?!..

sur mon Vu+ solo 4k j'ai les films on format 16/9 est ce n'ai pas le cas sur pc est ce que il ai possible de regler la résolution d'écran sur kodi ?.

**Comment by TmpName** [comment]
Exact, j'avais meme pas calcule pour le 4k, a la prochaine modif je vire le lien.

Sinon je viens de retester, sur "creed' tout les liens marchent chez moi, tu aurais un exemple ? Tu as bien la derniere version ?

Oui sur kodi il y a gave d'option pour regler la resolution, il y a meme une option pour deformer l'image pour reduire les bandes noires. Mais le soucis c'est qu'il y en a partout. Si tes options sont bonnes, le plus simple c'est dans la barre de lecture en bas a droite il y a un raccourcis pour des reglages d'ecran.

Mais pour moi si kodi n'affiche pas la meme resolution que si tu regardes le fichier directement sous windows tu as un rattage dans ta config de kodi. Et la c'est direct dans les options.

**Comment by mino60** [comment]
par exemple sur section musiques hd le titre : Emission Featherfly - Tell Me What You Want (2015) HD 1080 ne fonctionne pas tout les titres après marche (720p)HD en rouge sur l'écran

**Comment by TmpName** [comment]
C'est bon j'ai mis en ligne sur la correction sur la beta.
