### ISSUE TITLE
Librairies (Béta)

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#380]
Hello
J'ai tenté quelques essais de la fonction "Librairie Beta"

Quelques remarques pour aider au développement de cette fonction :

- Les films ajoutés à la Librairie n'affichent pas les affiches ni les fond d'écran : Ducoup on ne peut pas trop utiliser cette fonction pour ajouter un widget sur la page d'accueil de Kodi.

La fonction "Marque Page" le permet (de faire un chouette widget) mais pour être vraiment pratique il faudrait que les films marqués soient sauvegardés dans un fichier Sql différent de l'historique des recherches.

Ce n'est que l'avis d'un utilisateur régulier mais qui n'a aucune connaissance en codage donc pas la moindre idée de la complexité des améliorations demandées :)

Bon week end à tous.

**Comment by TmpName** [comment]
En fait quand tu rajoutes des fichiers dans la librairie, il te faut la scrapper avec kodi comme si c'etait un repertoire normal, mais normallement ca se fait par defaut.

Il y a une option "mise a jour a chaque ajout" dans les parametres, elle est cochee chez toi ?

**Comment by canopre** [comment]
Oui elle est bien cochée.

**Comment by TmpName** [comment]
Ok, bon alors pas de bol, c'est que le scrapper n'a pas trouve, tu as un exemple stp ? Si c'est batman vs superman, j'ai deja teste.

**Comment by canopre** [comment]
non c pas batman.
J'ai testé 3/4 films et ca n'a jamais fonctionné.

**Comment by TmpName** [comment]
Alors la y a un probleme, tu es sur d'avoir fini la configuration ?
Je viens de tester, quand je rajoute le film en librairie, ca m'affiche en haut "recherche sur TMDB" et le film se rajoute sur la page d'acceuil en section film, et si je passe dessus j'ai toutes les infos.

Il faut egalement rajouter le repertoire selectionne dans les options de Vstream, dans la mediatheque.
Video > fichiers>  ajouter une source, selectionner le repertoire + le scrapper.

**Comment by kareem225** [comment]
Bonjour
Navré pour l'intrusion je me suis dis que j'allais essayé  de creuser tout seul concernant un petit soucis mais là j'en peux plus 
Brièvement et pour rejoindre votre conversation oui l'ajout de film à la libraire se fait, du moins dans mon cas, sans problème,  mais là où ça coince c'est lors d'un ajout de série, je n'ai pas le choix ajout à la librairie dans le menu contextuel en cliquant sur une serie ou une  saison par exemple. Pour avoir ce fameux ajouter à la librairie il faut que ça soit un seul et unique épisode, le but étant d'avoir un beau raccourcis à une serie ou une saison.
En tout cas bravo pour vos efforts malgré toutes les contraintes

**Comment by kareem225** [comment]
Pour illustrer l'ajout à la librairie peut concerner une série ou une saison sur Genesis

**Comment by TmpName** [comment]
Normallement sur Vstream, tu rajoutes l'episode et Vstream cree un repertoire du nom de la serie et place dedans les epidodes et les saisons.

Donc dans ta biblioteque tu as le nom de la serie qui apparait, et si tu cliques dessus ca t'affiche les saisons, puis les episodes.

PS: Sa n'affiche les saisons uniquement si il y en a plusieurs dans le repertoire.

Ca ca marche, je viens de tester , apres cette partie n'etait pas finie donc je ne sais plus ou ca deconnait

**Comment by kareem225** [comment]
Bizzard j'y arrive pas bon peut être car je suis novice ca m'affiche un seul episode (test sur arrow nouveaute.fullstream dernier épisode ), je vais réessayer c clair j'ai raté un truc. Ca aurait été plus pratique d'ajouter ajout librairie mais derrière je peux comprendre qu'il faut tout un travail. Merci en tout pour la rapidité et bon courage

**Comment by TmpName** [comment]
Regarde dans les options de la seconde page quand tu crees la source >> "option d'analyse de contenu".
Je viens de tester sur la meme source, pas de soucis, je suis sous confluence je vais dans "serie TV", la j'ai la liste de mes serie, je prends "arrow" et la j'ai l'episode 1.

**Comment by canopre** [comment]
Pour le coup j'ai pas compris grand chose aux réponses : faut que j'approfondisse le dossier... Mais merci pour toutes vos réponses. :+1:

**Comment by kareem225** [comment]
Le 25 juin 2016 09:56, "canopre" <notifications@github.com> a écrit :

>

> Pour le coup j'ai pas compris grand chose aux réponses : faut que
j'approfondisse le dossier... Mais merci pour toutes vos réponses. 👍
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
<https://github.com/LordVenom/venom-xbmc-addons/issues/380#issuecomment-228527850>,
or mute the thread
<https://github.com/notifications/unsubscribe/ASjBJ7tC-RWdZW6vdeDn1MYk2wZgY-Z7ks5qPPs6gaJpZM4Iet2C>
.
