### ISSUE TITLE
Petit Problèmes avec les Metas

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#381]
Bonjour, Bonjour,

Pour ma part j'active les métas car je trouve que c'est beaucoup + sympa même si on perd quelques secondes lors du chargement des listes.

Cependant, et je ne sais pas si c'est un bug ou tout simplement une absence d'information sur la source mais certains films n'affichent pas la catégorie à laquelle appartient le film.

Et quand la catégorie n'est pas affichée : Le fond d'écran du film ne s'affiche pas non plus.

Une solution ?

Je reste à votre disposition pour tous les détails.

++

**Comment by TmpName** [comment]
Tu aurais un exemple de film/site que je puisse voir si ca vient de la database en ligne ou de kodi ?

**Comment by canopre** [comment]
Par exemple : Batman vs Superman dans les nouveautés de voirfilms_org

**Comment by TmpName** [comment]
Bon j'ai fais les test sur "vkstreamingfilm" car il apparait pas sur voirfilm.
Mais c'est un exemple typique, sur le site le film s'appelle "Batman v Superman: L'aube de la justice". J'ai teste sur TMDB.
Batman v Superman: L'aube de la justice > pas de resultat
Batman v Superman aube justice > pas de resultat
Batman v Superman de la justice > ok

Comment tu peux deviner que c'est le mot 'aube 'qui fout le bordel ? Franchement je vois pas de solution.

**Comment by canopre** [comment]
C'est malheureusement pas moi qui vais pouvoir t'aider :)

Mais merci d'avoir regardé.

**Comment by TmpName** [comment]
Ni moi, la franchement c'est mort, si leur moteur de recherche est pas plus efficace, a moins d'avoir un addon devinatoire, c'est foutu.
