### ISSUE TITLE
soucis sur Kepliz

### ISSUE THREAD

**Issue by Kodigoal** [LordVenom/venom-xbmc-addons#383]
Bonsoir,
Sur certains films , on a droit à un nouveau format du lien
showHosters.
Exemple :  film 'San Andreas' ( yen a d'autres)
iframe src=/kepliz/player.php?id=
On avait déja mis en place le FramePattern2 pour le format:
iframe src="/kepliz3/player.php?id=

Bon, j'arrive pas à trouver un regex pour prendre en compte les 2 formats...
Ou sinon si il faut rajouter un Framepattern3 dans le code? ca je peux
eventuellement faire si ya pas le choix.
Merci.

**Comment by TmpName** [comment]
J'ai mis une nouvelle version en ligne, elle marche pr San andreas, pas eu le temps de tester a fond.
Elle est uniquement sur beta, si c'est bon je la passe en off demain.

**Comment by Kodigoal** [comment]
Merci pour l'explication,  j'arrivais pas avec le " si présent ou pas, à une Etoile prêt xD
Ca fonctionne bien ^^
