### ISSUE TITLE
ajout planet-series.tv

### ISSUE THREAD

**Issue by andykimpe** [LordVenom/venom-xbmc-addons#384]
serait il possible d'ajouter h ttp://planet-series.tv/

dans vstream svp merci

**Comment by TmpName** [comment]
Decidement, suis sur qu'il y a plus de demande pr ce site que pour ZT.
Le soucis c'est que c'est plus une source de DDL que de streaming, si ZT est present c'est vraiement un concours de circonstance.

Je sais pas si le chef va autoriser une seconde derive, en tout cas moi j'ai pas trop le temps pr de nouvelle source, par contre je peux regarder pour passer les 2 multihosts de leur site.

Mais juste par curiosite qu elle est la serie que tu as trouve sur leur site et pas sur Vstream ?

**Comment by andykimpe** [comment]
et bien par exemple

Sakura, chasseuse de cartes vf (seulement en vostfr sous vstream)

http://www.planet-series.tv/sakura-chasseuse-de-cartes/

le tour du monde en 80 jours (il y a bien des version différente mais pas la même)

http://www.planet-series.tv/le-tour-du-monde-en-80-jours/

ont peut trouver des épisode de série comme plus belle la vie, ou encore Joséphine ange gardien, etc qui n'ont pas encore étais diffuser en France

les épisode sont enregistrer sur les belge (rtbf) ou suise (rts)

qui sont en avance sur la diffusion par rapport a la France

autre avantage les upload sont ouvert a tous et chaque utilisateur est informer lorsque un lien est mort ce qui permet de réup

**Comment by TmpName** [comment]
Alors deja merci tu m'as trouve du boulot pour plus tard ^^.
Sakura est sur mangacity en VF mais dure a trouver me faut reparer la recherche.
Elle est aussi sur adkami mais me faut rajouter un host

le tour du monde en 80 jours est sur tv-streaming.ch, j'ai juste regarde l'image mais de memoire (et j'ai adore cette serie aussi) c'est vraiment la meme.

**Comment by andykimpe** [comment]
le tour du monde en 80 jours est sur tv-streaming.ch,

oui mais les lien sont hs enfin en dirait vstream erreur : fichier introuvable

et en puis se n’était que des exemple si ont cherche bien on en trouvera d'autre

je croit que je vais te redonner encore du travail libertyland les lien ne fonctionne pas

comme non d'hébergeur c'est afficher ??? est impossible d'ouvrir les liens

**Comment by TmpName** [comment]
Yep, flashX etait HS, remit a jour hier donc les liens vont remarcher dans 2 jours max chez toi.
C'etait juste par curiosite, moi aussi suis comme toi, ya plein de serie que je n'ai trouve que chez eux, la derniere une vielle version derivee de ghostbuster.

Liberyland tourne chez moi, tu as teste quel film ?

**Comment by andykimpe** [comment]
j'ai tester la maj depuis le master beau boulot

flashx ok

manga city ok

pour libertyland c'est tout le site qui ne marche pas peu importe les liens

 tu as la même erreur

**Comment by TmpName** [comment]
Non, et tu m'inquietes, tu as un message d'erreur, quelque chose dans les logs ?
Je viens de relire le code, je ne vois pas pkoi ca bloquerait today.

**Comment by TmpName** [comment]
Si il y a un motive, j'ai rajoute une lib pr les multihosts
>>from resources.lib.multihost import cJheberg
list = cJheberg().GetUrls('ht tp://w ww.jheber g.net/xxxxx/')

Et vous avez direct une liste de lien valides, meme fonctionnement pour Multiup

**Comment by TmpName** [comment]
Bon ben la c'est regle, le site vient de fermer, action en justice.
Affaire a suivre ..
