### ISSUE TITLE
hqq.tv

### ISSUE THREAD

**Issue by justdigger** [LordVenom/venom-xbmc-addons#385]
Bonjour,

J'aimerais savoir si c'est possible d'utiliser votre décodeur pour hqq.tv pour notre addon, en même temps savoir si il est fonctionnel?

Merci

**Comment by TmpName** [comment]
Il fonctionne, par contre ce n'est pas le code de hqq.py (qui ne sert plus) mais netu.py.
Ce n'est pas moi le "proprietaire" du code, mais a mon avis tu peux te servir sans probleme de tout ce qui traine dans Vstream, tout est sous license GPL
>>https://github.com/LordVenom/venom-xbmc-addons/issues/316

Par contre, selon ce que tu prend comme code, essaye de citer l'auteur dans les commentaires, un user de Vstream a créé le code aadecode.py, tu le trouves partout, meme dans le code officiel de UrlResolver, et tu ne vois que le pseudo du mec qui a prit le code, alors que avec les dates tu peux verifier que c'est bien lui qui a créé le code.

Pour celui de netu, la plus grosse partie n'est meme pas de nous, et je n'ai jamais mis l'auteur car impossible de trouver le premier createur, donc la tu n'as meme pas a avoir de scrupule vis a vis de nous.

**Comment by justdigger** [comment]
Merci beaucoup!

**Comment by justdigger** [comment]
Comment je fais un appel a hhq.py?

goodurl =  hqq.cHoster.parseNETUTV(url)

?

**Comment by TmpName** [comment]
Tu viens de me mettre le doute, ta video est sur un site russe ou asiatique ?
En fait durant une periode il y a eu une transition et tout les liens HQQ sont devenu des liens netu.
Je peux me tromper mais normalement si tu lances la video et que tu cliques sur une des icones qui apparaissent tu vas te retrouver sur netu.tv.

Tu vas devoir modifier le code pour ton addon, la classe a ete concue pr Vstream. Elle est totallement inutilisable pour toi en l'etat (il y a meme des appels a d'autres libs de VStream) mais pour nous cela ressemble a
setUrl(www.netu/xxxxx) < fonction pour initialiser
goodurl = getMediaLink() < fonction qui recupere l'url

Les seules fonctions utiles pour toi sont __getMediaLinkForGuest() et toutes celles qui sont hors de la classe.

Apres si tu arrives sur le site asiatique, j'aimerais bien avoir le lien de la video stp.

**Comment by justdigger** [comment]
voila
http://hqq.tv/player/embed_player.php?vid=11Y2W5NK1NB8

**Comment by TmpName** [comment]
Erreur 404 chez moi. Il marche chez toi ?
Mais tu serais encore sur l'asiatique.

Honnettement je ne connais aucun lien sur HQQ (non netu) fonctionnel sur des sites de streaming FR. C'est pour cela que le code de hqq ne sert plus.

**Comment by justdigger** [comment]
c'est le code que je décrypte du site internet de libertyland

**Comment by justdigger** [comment]
mais je crois que c'est normal si tu y va directement avec le url que ça ne fonctionne pas, il faut le décrypter ....

**Comment by TmpName** [comment]
Il n'est pas crypte, c'est juste que en direct il lui manque des infos (referer) et donc il ne mache pas si il n'est pas "embed" (je sais plus comment on dit en francais).

Mais tu peux le tester sur Vstream, le resolver onctionne.
