### ISSUE TITLE
Probleme de marque page

### ISSUE THREAD

**Issue by nico77410** [LordVenom/venom-xbmc-addons#387]
J'ai un gros bug sur Vstream, lorsque je sélectionne des séries dans le marque page au bout de 17 séries dans le marque page. Je ne peux plus ouvrir le marque page. Comment peux-t-on les supprimer et Pouvez-Vous corriger le bug. Je suis sous KODI16.

**Comment by TmpName** [comment]
Je viens de tester, je pense plutot qu'il ya eu un bug sur la 17 eme serie.
Sinon vu que je ne pense pas que tu regardes 17 series en meme temps, tu peux les supprimer au fur et a mesure avec le clic droit.

Sinon dans ton cas, je vois plusieurs solutions.
1 - ecraser ta version de Vstream par la beta, aucune perte de donnees/config, Il y a pas mal de modifs sur la gestion des favoris en cours, mais il se peut que ce soit trop tard, si le bug est dans la base de donnee, mais tu as rien a perdre elle sera officielle dans 1 semaine.
2 - effacer le cache de Vstream, dans les parametres, ca va remarcher mais tu vas perdre tout tes favoris.
3 - Si tu t 'en sens capable, me faire passer les logs avec le message d'erreur, que je puisse te faire un patch rapide pr debloquer, mais tu vas devoir bidouiller toi meme les fichiers de Vstream.
4 - utiliser une appli de gestion de base de donnée, pour aller fouiller dans celle de vstream.

Sinon, le message d'erreur des logs m'interesserait quand meme pour connaitre le bug, histoire d'etre sur qu'il soit corrige dans la future version.

**Comment by nico77410** [comment]
Bonjour merci pour votre réponse
J'ai supprimé le cache et c'est reparti mais j'ai perdu les marques pages. Ce n'est pas grave.
J'espère lors de la prochaine mise à jours de Vstream réglera le problème.
Vous avez créé un excellent add-on. Félicitation
La plus heureuse est ma femme

**Comment by TmpName** [comment]
Lol, merci.
