### ISSUE TITLE
cache plein

### ISSUE THREAD

**Issue by drahub** [LordVenom/venom-xbmc-addons#389]
Bonjour à tous.
Parfois j'ai le message : Cache plein insuffisant pour une lecture fluide.
Comment accede-t-on dans vstream au réglage du cache ?
( je pense que j'ai une vitesse adsl insuffisante pour une lecture fluide mais j'aimerai essayer d'augmenter la capacité du cache pour voir ce qu'il se passe).
Merci pour votre aide.

**Comment by TmpName** [comment]
Ce n'est pas le cache de Vstream mais celui de kodi
je n'ai jamais pu trouver la manip en fr, mais tu geres l'anglais > http://kodi.wiki/view/HOW-TO:Modify_the_video_cache.

**Comment by LordVenom** [comment]
Des nouvelles ?
