### ISSUE TITLE
TV orange

### ISSUE THREAD

**Issue by mickou35** [LordVenom/venom-xbmc-addons#390]
Merci pour ce travail d'équipe.
Toutefois je n'arrive pas a accéder a la TV d'Orange 
j'ai une LB et un décodeur Orange

Je m'y prend peut être mal
Merci de votre aide

**Comment by TmpName** [comment]
Pourrais tu me dire si ca marche via navigateur chez toi sur ce site > ht tp://vlc-media-player.org/m3u/orangetv.m3u.
Il te faut evidement etre chez orange et avoir vlc d'installe.

**Comment by mickou35** [comment]
Merci pour ton retour.
flux FW ouverts
fichier m3u téléchargé
ouverture du fichier sur VLC
Aucunes des chaines ne fonctionne

**Comment by TmpName** [comment]
Je n'ai pas orange, donc je ne peux pas te repondre.
Sur ce site tu as quelques infos > ht tp://www.porciello.com/inventel/tv_vlc.htm

Le probleme c'est que ce site est tres vieux et surement plus a jour, Orange a completement change son mode de fct depuis qu'il propose un acces aux videos via leur portail.

**Comment by LordVenom** [comment]
Je pense aussi que c'est une histoire d'option a cocher tient nous au courant merci.

**Comment by TmpName** [comment]
C'est clair que ca m'interesse aussi, mais a mon avis c'est mort.
J'ai regarde vite fait les forum de orange la seule solution que je vois c'est "installe l'appli d'orange" ou " passe par le portail orange".

Si tu bidouillles il y a http://www.forum-orange.com/viewtopic.php?id=73916
