### ISSUE TITLE
Ajout www.tarevi.com

### ISSUE THREAD

**Issue by wilrib** [LordVenom/venom-xbmc-addons#391]
Bonjour,

Nickel cet addons fonctionne parfaitement ! C'est super cool et tres bon boulot !
Est il possible d'ajouter en source ce site htt p://ww w.tarevi.com/ ? car il propose des films en HD et fonctionne super bien meme avec une  mauvaise connexion comme chez moi

MErci

**Comment by TmpName** [comment]
Il y est deja, il s'appelle kepliz.

**Comment by wilrib** [comment]
Ah oui en effet ! Merci de ta réponse en tout cas !
