### ISSUE TITLE
recherche visuelle ou similaire

### ISSUE THREAD

**Issue by spcxsat** [LordVenom/venom-xbmc-addons#393]
hello,

il n'y aurais pas un probleme avec la recherche visuelle ou similaire, je n'ai plus de lien qui apparaisse pour zone de telechargement.
Pourtant tout est bien coché dans les paramètres pour celle-ci dans plugins on/off 3

si vous pourriez regarder au cas ou cela viendrais de mon instal.

**Comment by TmpName** [comment]
Exact j'ai une erreur bizarre
"Attempt to use invalid handle 103 "
Le probleme c'est que ca le fait aussi pour la recherche globale, donc gros probleme.

**Comment by TmpName** [comment]
C'est bon j'ai trouve le coupable c'est streamcomplet qui foutait le dawa.
C'est corrige mais je corrige en passant la recherche de voirfilmorg et frenc hstrea m avant de valider la MAJ auto.

**Comment by spcxsat** [comment]
Yes sais cool, merci pour la modif.
apres pour le zip a vous de voir

**Comment by Xiaomisenz1** [comment]
Salut, je voudrais savoir comment pouvoir regarder une série via zone téléchargement que part uptobox, par exemple sur uplea ou 1 fichier 
Merci

**Comment by TmpName** [comment]
Uniquement par uptobox ?
Tu as un compte premium chez eux ou pas ?
Si tu as un compte, vas dans les options de Vstream / premium, sinon en gratuit uplea ne fonctionnera pas, les autres si mais en limite, normallement tu ne devrais pas avoir de problemes.

**Comment by spcxsat** [comment]
Pour info le bug es revenu.....

**Comment by TmpName** [comment]
Cette fois moi j'ai pas le bug ^^.
J'ai teste recherche de film "taken" et ca a marche.

**Comment by spcxsat** [comment]
Yes lol j'ai trouver zone de telechargement n'etais plus cocher dans les parametre pour la recherche lol dsl
