### ISSUE TITLE
Classement

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons#395]
Je pense a réorganiser un peux vStream voici le résultat vos commentaire sont les bienvenues, 

http://hpics.li/c844621

Bon films

**Comment by TmpName** [comment]
Pour le moment ca va, y a pas de changement brutaux, sobre.

Sinon y a 2 choses a modifier peut etre: 
1 - afficher la page home en mode "miniature" (forcage), je pense qu'il y a en a qui vont demander a mettre cette option partout, mais je pense que au moins sur la page home, c'est plus agreable et on pourra enfin virer le systeme de couleur de depart (et il y a pile 15 icones avec celle de mise a jour)

2 - faire quelque chose pour les sources, y en a trop, afficher un "*" de couleur a cote du nom pour indiquer si active ou pas, ou autre chose, je suis sur que sur cette partie y a plein de trucs a faire.

**Comment by LordVenom** [comment]
Pourquoi le forcer surtout que kodi a une mémoire des vues si tu le met en miniature par default il le mettra toujours comme ça.

Pour les sources elle sont forcement activer sinon elle ne sont pas afficher.

**Comment by TmpName** [comment]
Yep, c'est ce que j'ai fais, mais je trouvais pas mal de le proposer a la base en premiere install.

Pour les sources, je parlais de "toutes les sources" en home page.

**Comment by LordVenom** [comment]
Ben même réponse si il sont désactiver elle ne sont pas visible.

**Comment by LordVenom** [comment]
J'ai envoyer un peux de changement, je met pas a jour les fichier site car j'ai modifier les context aussi.
