### ISSUE TITLE
Openload

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons#396]
Source HS affiche une video de pigeon c'est trés drole mais pas regardable lol

**Comment by LordVenom** [comment]
Mise a jour et envoyé en mise a jour auto

**Comment by Pyanne** [comment]
Toujours les pideons malgré la mise à jour.

**Comment by TmpName** [comment]
XD, wé j'ai trouve ca marrant les pigeon aussi.
Sinon moi ca remarche avec la mise a jour, tu as le soucis sur quel site Pyanne ?

**Comment by arzaz** [comment]
J'ai toujours ces pigeons malgré la mise a jour.
Testé sur le site Film illimite
C'est quoi le problème?

**Comment by Kodigoal** [comment]
Bonsoir,
Plus de pigeons en vue, Merci :)
Par contre sur film illimité plus aucune vidéo ne s'ouvre par les liens openload ...
Si j'utilise le  openload.py avant maj , ya les pigeons.
Par le site , les vidéos fonctionnent par openload.
J'ai regardé un peu le binz  mais je sais pas si ca peut venir du fait de remplacer  le /embed/  par /f/,il trouve pas la vidéo ... ou si le problème est que chez moi.
Sinon pour @arzaz , sur VoirFilm , testé quelques films ca fonctionne aussi.
la vidéo..

**Comment by Kodigoal** [comment]
Bonsoir,
Plus de pigeons en vue, Merci :)
Par contre sur film illimité plus aucune vidéo ne s'ouvre par les liens openload ...
Si j'utilise le  openload.py avant maj , ya les pigeons.
Par le site , les vidéos fonctionnent par openload.
J'ai regardé un peu le binz  mais je sais pas si ca peut venir du fait de remplacer  le /embed/  par /f/,il trouve pas la vidéo ... ou si le problème est que chez moi.
Sinon pour @arzaz , sur VoirFilm , testé quelques films ca fonctionne aussi.

**Comment by arzaz** [comment]
Sous le système IOS j'ai l'erreur fichier introuvable avec le site Film illimité mais ca fonctionne sur Voirfilm.
Par contre avec Android, les pigeons apparaissent toujours avec le host openload quelque soit le site?

**Comment by LordVenom** [comment]
Merci du raport j'ai regarder un peux mais c'est chaud la a voir si c'est pas le aacode qui a changer j'ai pas trouver encore. Quelqu'un a fait une mise a jour si @TmpName passe par la ça peux peux etre l'aider.

https://github.com/Zanzibar82/plugin.video.streamondemand/blob/master/servers/openload.py

**Comment by TmpName** [comment]
Nouvelle version en ligne pour les ennemis des pacifistes pigeons.

Pas encore mit en of, j'attend les resultats de quelques tests.

**Comment by arzaz** [comment]
C'est parfait TmpName
Tout est ok maintenant

**Comment by LordVenom** [comment]
Lol pauvre pigeons

**Comment by TmpName** [comment]
C'est clair, pauvre betes. Sinon, moi je trouve ca excellent comme parade, le nbre de personnes qui ont du halluciner en voyant les pigeons avec cette musique digne de Eric Serra.

**Comment by Kodigoal** [comment]
Merci.
Adieu ' You got rick rolled ' version pigeon ^^

**Comment by spcxsat** [comment]
Yes avec la mise a jour ca fonctionne nikel

**Comment by arzaz** [comment]
Aujourd'hui j'ai a chaque Fichier introuvable?

**Comment by TmpName** [comment]
Lol, je suis dessus. Et je viens de tomber sur cette variable
>>{type:vt,src:M[welikekodi_ya_rly]});})

XD.

**Comment by LordVenom** [comment]
Le retour des pigeons

**Comment by TmpName** [comment]
Haaaaa, wééééé, vais voir XD.

**Comment by LordVenom** [comment]
lol c'est un wééé de joie ou de colère :)

**Comment by TmpName** [comment]
De joie, j adore leur mentalitee.
Correction faites, je met a jour.
