### ISSUE TITLE
TV SFR

### ISSUE THREAD

**Issue by Pyanne** [LordVenom/venom-xbmc-addons#397]
Aucune chaine ne fonctionne sur le module de TV SFR.

**Comment by TmpName** [comment]
Peux tu me dire si celle si fonctionne sur VLC.
h ttp://ww w.m3u.fr/liste-sfr-bouquet-tv.php

Normallement c'est la meme dans Vstream, pas trouvee de plus recente, a mon avis comme orange, ce service est fini sur cet operateur.

**Comment by polyglotte** [comment]
J'ai tésté sous Jarvais: 
-connection fibre de Free aucune chaine disponible
-connection adsl Bouygues aucune chaine disponible

**Comment by TmpName** [comment]
Bouygues je confirme, deja teste ca ne marche pas.
Pour free par contre c'est pas normal.
Je pense vraiment qu'on devrait supprimer cette section, a part free, je suis sur a 90/100 que les autres ne marcheront plus.

**Comment by Pyanne** [comment]
Effectivement pour SFR, ça ne fonctionne pas non plus avec VLC.

**Comment by TmpName** [comment]
Moi je propose de desactiver cette partie, je ne vois pas comment la refaire fonctionner.

**Comment by LordVenom** [comment]
J'avais penser faire des grab de site iptv faut trouver les bons sites aprés pour l'utilisateur ça vas être au petit bonheur la chance, mais c'est déjà le cas avec libretv, les liens iptv sont très instable.

**Comment by TmpName** [comment]
Yep, mais ca c'est la "tv par le web" qui marche plutot pas mal chez moi, nope ce que je pensais desactiver c'est celle via les fournisseurs d'acces, orange est out, bouygue aussi, now sfr, ...

**Comment by LordVenom** [comment]
Nop la tv du web sont des liens tester mais si on grab par exemple http://www.tvonlinestreams.com/bis-televisions-france-tv/ ont auras beaucoup plus de lien mais bon beaucoup ne fonctionne pas pour ça il faut trouver un site qui maintient correctement sa base de donnée.

**Comment by TmpName** [comment]
J'ai jamais vu, et vu le taff que cela demande, ca m'etonnerait qu'ils nous laissent pomper leurs liens comme des porcs.....

Mais par contre, histoire d'eviter de voir des gens demander pkoi la partie "orange/sfr/bouygue" ne marche pas, moi je la virerais tout simplement.
