### ISSUE TITLE
Ajouter mangavost.com comme source

### ISSUE THREAD

**Issue by rcxcob2016** [LordVenom/venom-xbmc-addons#398]
Je trouve que ça serait bien de rajouter mangavost.com comme source. Mais la seule question serait de savoir dans quel catégorie allez-vous mettre "dessins animé"?

Merci!!

**Comment by rcxcob2016** [comment]
Car, dans le site il y a une catégorie manga et une catégorie dessin animé...

**Comment by TmpName** [comment]
J'ai teste (assez vite j 'avous), mais j'ai pas vu ce quelle apporte de plus ?
1 seul host a chaque fois, et suis pas sur d'y trouver une video non presente sur un autre site ?

**Comment by rcxcob2016** [comment]
J'avous mais la seule raison pourquoi je trouve qu'elle devrait etre ajouter, c'est parce que c'est le seul site de streaming qui propose le dessin animé Gumball qui est une émission très drole meme pour un adulte, ils ont meme tout les saisons. Donc, ils ont surement dautre emissions que les autres sites ont pas. C'est pour ça que je lai proposer...

**Comment by TmpName** [comment]
Je confirme, y a des exclues. Site facile a rajouter en plus.

**Comment by LordVenom** [comment]
Tout les lien series sont en youwatch, 1 seul host et le pire en plus dsl.

**Comment by TmpName** [comment]
Lol, mince, je viens juste de la finir et mettre en ligne
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/mangavost.py

La qualitee est vraiment pourave, mais il y a des raretees dessus, au pire laisse la en ligne le temps que @rcxcob2016 la recupere, ou passe la dans le dossier trash.
