### ISSUE TITLE
Ajouter skstream.net comme source

### ISSUE THREAD

**Issue by rcxcob2016** [LordVenom/venom-xbmc-addons#399]
Je trouve que ça serait bien de rajouter skstream.net comme source.

Merci!

**Comment by TmpName** [comment]
Bon la y a a la toque de sources, mais site qui n'a meme pas 1 an, j y ai trouve de vieux films mais m'etonnerait qu'il y ait trop d'exclus.

D'autres avis ?

Perso si j'ai le temps ce week end, je me pencherais plutot sur ta precedente proposition.
