### ISSUE TITLE
Sous-titre et multilangue

### ISSUE THREAD

**Issue by fredkerm** [LordVenom/venom-xbmc-addons#401]
Merci beaucoup pour le super boulot fournit !
Certaines vidéos contiennent du multi-langue et/ou  des sous-titres, malheureusement ceux-ci ne sont pas proposés lors du streaming (hébergeur uptostream).
Y-a-t-il un moyen de contourner ce problème ?

Merci

**Comment by LordVenom** [comment]
Bonjour, Tu peux pas modifier la langue par le menu du lecteur/audio? sinon merci d'être plus precis quel site quel film tester?

**Comment by fredkerm** [comment]
Bonjour,
Merci pour la réponse rapide.
Après vérification il semble que le comportement ne soit pas forcément le même pour tous les fichiers.
Par exemple 
http://uptostream.com/5wy5cr39pkqk
Sur le site: 2 langes et 2 types de sous titre
Dans le lecteur audio : Pas de 2 eme langue proposée et un seul sous-titre proposé

http://uptobox.com/yoe8edop0mt4
Sur le site : 1 langue & 1 sous-titre
Dans le lecteur audio : Pas de sous titre proposé

Merci

**Comment by TmpName** [comment]
En fait je peux me tromper mes les sous titre ne sont pas integre a la video, ils sont dans un fichier anexe qui est utilise ou pas par leur lecteur, kodi lui, lit juste le fichier de la video d'ou pas de sous titre.

**Comment by fredkerm** [comment]
C'est curieux car si je dépose le fichier MKV sur le disque dur, le lecteur gère bien la langue et les sous-titres et il n'y a bien qu'un seul fichier.

**Comment by LordVenom** [comment]
Pour moi avec http://uptostream.com/5wy5cr39pkqk j'ai bien 2 langue un french 5.1 et anglais stéreo et 2 sous titre french. Mais pour ça dans la popup d'uptobox il faut que je passe par Direct en Stream donc par Uptostream y a pas d'option.

**Comment by fredkerm** [comment]
Effectivement je n'avais pas pensé à faire ce test. C'est surement la solution mais malheureusement chez moi les liens direct ne fonctionnent pas. J'ai le message "Fichier introuvable" alors que le même lien fonctionne en stream ...

**Comment by TmpName** [comment]
Le je comprend moi quand je lance une video ca me lance le fichier
h ttp://ww w3.uptostream.com/XXXXXXX/720/0

Et si je veux les sous titre ca rajoute le fichier sous titre
h ttp://ww w3.uptostream.com/subtitles/xxxxxxxxxxxxx.srt

Mais avec ou sans sous-titre j'ai le meme fichier.

**Comment by fredkerm** [comment]
J'ai mis un P.J un fichier avec les logs pour l'ouverture d'un fichier en direct et du même fichier en streaming.
[kodi.txt](https://github.com/LordVenom/venom-xbmc-addons/files/323333/kodi.txt)
Il y a des messages en WARNING je ne sais pas si ça peut venir de ça:
CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.vstream

Pour info Kodi est installé sur un systéme Linux (raspbian)
Merci encore pour le coup de main

**Comment by TmpName** [comment]
Tu as desactive les telechargements direct sur ton compte premium ?

**Comment by fredkerm** [comment]
Non rien de désactiver.
Et j'ai le même comportement avec les autres hébergeurs

**Comment by LordVenom** [comment]
J'ai pas les même lien perso pour Kung Fu panda 3 HDLIGHT 1080 multilangue quand je prend stream

http://www3.uptostream.com/1kb1lzr23bc/1080/0

Quand je prend direct

http://www50.uptobox.com/d/XXXXXXXXX/XXXXXXXXXXXXXX.mkv

**Comment by TmpName** [comment]
Tu as essayes en desactivant ton compte dans les parametres de Vstream pour tester en free user ?
Si tu passes par un navigateur WEB, tu as bien une page normale avec un lien a cliquer pour lancer le DL ?

Franchement il n'y rien de bizarre sur ton log, au pire si mes precedentes idees ne donnent rien je te ferais un fichier special qui donnera plus d'infos en log.

**Comment by fredkerm** [comment]
C'est vrai que les 2 hébergeurs que j'ai testé étaient avec un compte premium.
Je teste ça vendredi.
En ce qui concerne les URL, pour créer le fichier de logs j'ai fait mon test sur une autre source d'où la différence d'url

**Comment by TmpName** [comment]
Ok, tiens nous au courant, si vraiment ca deconne encore je te ferais un fichier special qui va logguer toute les etapes, on aura plus d'infos, parce que la, a part "fichier introuvable", ca aide pas trop ^^.

**Comment by fredkerm** [comment]
En lisant un autre post j'ai compris le problème, il faut désactiver téléchargement direct et le SSL.
Maintenant ça marche au top !
Merci
