### ISSUE TITLE
Zone Téléchargements

### ISSUE THREAD

**Issue by Bigups23** [LordVenom/venom-xbmc-addons#403]
Bonjour, et encore merci pour ce formidable addon pour commencer, je pense d'ailleurs faire un don d'ici peu, sachant que les addons FR de qualités se font rares Messieurs.

Je voulais savoir quand je choisis films il ya la possibilité de lire tout le catalogue de ZT impressionnant, ce que je trouve dommage, c'est pourquoi que pour les séries, ça ne fait pas pareil ?

Ce serait juste formidable !!

merci

**Comment by spcxsat** [comment]
ca fonctionne aussi avec les series.

va sur tt les source en bas et prend ZT la tu pourra choisir pour les series

**Comment by Bigups23** [comment]
ah bon ? je ne le vois pas apparaitre sur les séries pourtant étrange ! sur les films je le vois il apparait en un espèce de rose ,, je vais regarder voir à nouveau !

**Comment by spcxsat** [comment]
Quand tu lance Vstream tu ne va pas sur film ni série
Tu va tous en bas sous

Voir Marque page
Téléchargement
Librairie bêta
Toutes les sources  # magique il es la

La tu prend zone de téléchargement tu devrais le reconnaître il es de couleur différente normalement

J'espère que ce coup si tu ma compris

**Comment by Bigups23** [comment]
Oui oui lol, j'ai très bien compris, c'est pas non plus marqué autiste ^^

Je le dis juste au-dessus qu'il est de couleur différente, je disais aussi que la fonction recherche à gauche n'est pas très au point

**Comment by spcxsat** [comment]
Si tu parle de recherche ou avec recherche visuel quand tu lance Vstream il faut l'activer dans l'onglet 3 des option faut tous cocher pour zone de téléchargement

**Comment by Bigups23** [comment]
D'accord, message bien reçu, merci encore à toi ! ;)
