### ISSUE TITLE
Premium uptobox KO

### ISSUE THREAD

**Issue by chataigne73** [LordVenom/venom-xbmc-addons#404]
Salut la compagnie.
Depuis hier soir chez moi, ZT+ uptobox premium, en choisissant rester en direct et nom pas regarder en streaming, ça reste bloqué sur ouverture du flux, et puis plus rien 
Qqn d'autre a le même symptôme ?

**Comment by TmpName** [comment]
Yep > https://github.com/LordVenom/venom-xbmc-addons/issues/401

**Comment by chataigne73** [comment]
Tu disposes d'un compte premium pour tester TmpName ?
Pour moi ça plante (ou plutôt ne démarre jamais) que pc, Android (mon smartphone) et sur mon pi.
D'après mes 1eees recherches, c'est la fonction gethtml de premiumhandler qui bloque
Que puis je faire de plus investiguer? 😕

**Comment by TmpName** [comment]
En fait je teste avec un compte gratuit.

http://pastebin.com/9gf6KVQ2
J'utilse cette version du fichier modifiee, elle affiche quelques lignes de logs en plus et sauve le resultats du telechargement des pages dans c:/

Le probleme c'est que chez moi j'ai vire toute les securitees, il risque de te falloir modifier le chemin d'acces pour enregistrer les fichier upto1 et upto2.

Si tu passes par un navigateur et tapant le lien tu as encore une page web ou ca telecharge le fichier direct ? (comme onefichier)

**Comment by chataigne73** [comment]
Tu m'as mis la puce à l'oreille : dans mon compte uptobox j'avais activé "téléchargement direct pour que les download se lance automatiquement via navigateur, ainsi que téléchargement ssl
J'ai désactivé les 2et tout est rentré dans l'ordre
