### ISSUE TITLE
KEPLIZ

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#405]
Kepliz change de nom et devient Grudal.com 
http://w ww.grudal.com/fg4fd87r84cdfgdffddsfd/

**Comment by mino60** [comment]
Oui effectivement c'est pour ça que j'ai modifier le script avec Kodigoal mais il reste un peux de travail
https://github.com/LordVenom/venom-xbmc-addons-beta/issues/124

 Poploz Le bon élève

**Comment by TmpName** [comment]
Update pr kepliz
