### ISSUE TITLE
Tous lecteurs non disponible? et HD?

### ISSUE THREAD

**Issue by clyde005** [LordVenom/venom-xbmc-addons#406]
Bonjour,
Je découvre Vstream depuis 1 semaine et c'est magique!
Les questions que j'ai envie de poser sont les suivantes:

1) Est- ce normal que j'ai beaucoup de lecteur qui ne se lance pas (ecran noir avec fleche et au bout de quelques secondes "END" s'affcihe en haut a droite).
Par ex impossible d'ouvrir un fichier avec youwatch?

2) Impossible de voir un film/séries en HD? Ou ai-je raté quelque chose dans la config?

Je précise être sous Enigma2

Merci de votre aide.

**Comment by LordVenom** [comment]
Je ne connais pas enigma et vStream n'est tester que sous pc ou htcp voici une liste de nos installation
https://github.com/LordVenom/venom-xbmc-addons/issues/190

Pour enigma va voir ce post.

https://github.com/LordVenom/venom-xbmc-addons/issues/125

Note : Si quelqu'un du forum http://www.dzsat.org/ passe par la, qu'il m'explique voir même me fournisse les fichiers ou lien nécessaire au bon fonctionnement de la chose :)

**Comment by TmpName** [comment]
Pareil, je ne peux pas trop te dire mais :
1 - Youwatch peux mettre jusqu'a 1 mn pour "resoudre" le lien et encore 1 mn pour demarrer la video, selon les reglage de ta machine (le timeout) cela peut aboutir a une annulation simple du visionage pour fichier introuvable.

2 - Pour la HD, faut chercher, de memoire kepliz/megastream/librestream, sans tester tu ne peux pas savoir, certain mettent "HD" en titre mais en realite seule 1 source est en hd (generallement openload) et les autres en sd. ZoneTelechargement et sure a 100/100 pr du HD, mais en gratuit il est plus limite.
Y en un qui propose 2 lien netu a chaque fois, 1 en SD un en HD, mais tu ne peux pas differencier les deux.

**Comment by clyde005** [comment]
Re bonjour,
Merci pour les pistes....j'ai réussi a lancer mon 1er film en HD!! Il faut un peu chercher mais c'est top.
Le time out dont tu parles on peux régler cela?

Et enfin, Pouvez vous me dire comment faire pour changer l'affichage d'un film....ils sont tous en plein ecran et moi j'aimerai avoir les bandes noires ;-)

**Comment by TmpName** [comment]
Sur kodi faut modifier le fichier advancedsettings.xml pour le timeout.

Et pr l'affichage quand la video tourne, y a un menu (dont je ne me souvient jamais du nom) avec des icones en bas a droite, y en a une qui est un raccourcis pour les parametres videos.
La tu as tout les reglage, conversion de tailles, agrandissement, ect ...
Apres si tu as un ecran panoramique ca peut etre normal de ne pas avoir de bande noire, ecran 16/9 et film 16/9 pas de bandes noires.


Mais suis sur kodi classique.

**Comment by clyde005** [comment]
advancedsettings.xml? il va falloir le trouver celui là ;-)
Si tu as un petite explication pour faire cela je ne dit pas non.

Et pour les bandes noires, c'est dommage mais sous enigma2 lorsque la video tourne il n'y a pas d'icones ou de menus apparent...la video prend tout l'écran.

En tous les cas merci pour la réactivité!!!

**Comment by clyde005** [comment]
TmpName,
Tu peux me dire ou trouver advancedsettings.xml dans la structure de Kodi....j'ai vraiment cherché mais pas trouvé?
Merci.

**Comment by mino60** [comment]
Bon soir je suis un membre du forum DZsat pour enigma2  (systèm lunix) il ya un membre qui à réussie de faire fonctionner vstream sur enigma2 mais seulement sur un ancienne version 0.21 il n'y a pas jusqu'à présent une version à jour vstream ce lance grâce a un intermédiaire TSMEDIA le jumeau de Mediaportalle plugin multimedia
![grab](https://cloud.githubusercontent.com/assets/11494048/16286701/7ba7d6b6-38de-11e6-9a2a-38925d55e7c4.jpg)
![grab](https://cloud.githubusercontent.com/assets/11494048/16286709/85696bec-38de-11e6-95da-bf9ea7565888.jpg)
![grab](https://cloud.githubusercontent.com/assets/11494048/16286720/9078386a-38de-11e6-9990-eddb3eff610f.jpg)

![grab](https://cloud.githubusercontent.com/assets/11494048/16286733/9f6fc0ea-38de-11e6-9340-a273b5b41e66.jpg)

il faudrait modifier juste le fuichier seting.xm

http://www98.zippyshare.com/v/25XqTdFb/file.html

par contre avec les nouveaux démodulateur enigma2 compatible avec les fichiers arm  on peut utiliser kodi et vstream avec leur dernière version comme vu solo 4k plus simple et plus rapide qu'un PC sur windows.

**Comment by clyde005** [comment]
Un membre de Dzast!! Je le suis aussi...
J'ai installé BH 3.0.2 qui intègre Kodi et je fait tourner la dernière version Vstream 0.4.2 sans problème.
Concernant les bandes noires j'ai "contourné" le problème en utilisant l'option "Calibration vidéo et de cette façon j'ai réduit un peu mon écran pour avoir des bandes noires!
![photo 1](https://cloud.githubusercontent.com/assets/20064977/16292816/1a929bcc-3915-11e6-9fdc-93b6ef5b237b.JPG)
![photo 2](https://cloud.githubusercontent.com/assets/20064977/16292817/1c00f88c-3915-11e6-8b07-1ff02164873c.JPG)


Ensuite concernant le temps de réponse j'ai trouvé cela...est-ce la même chose? Car en modifiant le nombre je ne remarque pas de changement....youstream se met toujours en "END" après quelques secondes.
![photo](https://cloud.githubusercontent.com/assets/20064977/16292845/53d8253c-3915-11e6-88cb-b957efe4d83a.JPG)

Sinon je ne sais pas où modifier ce paramétre, j'ai parcouru tous les dossier et sous dossier!!!

**Comment by LordVenom** [comment]
Merci de visiter : c'est un fichier qu'il faut créer http://kodi.wiki/view/how-to:modify_the_video_cache

**Comment by clyde005** [comment]
Je vais tenter l'addon...en esperant pouvoir ouvrir les youstream après ça.
Je vous dis quoi ;-)

**Comment by LordVenom** [comment]
<< hé ben qu'il a bien le dossier en main>>, << Oui c'est ça je vous appelle de la bas et je vous dit quoi>> 

Ok j'arette les références.

**Comment by chataigne73** [comment]
pour moi le temps d'attente du lecteur n'a rien a voir avec le fichier advancesettings qui règle le cache video
donc c'est bien sur le paramètre dans vstream qu'il faut jouer

**Comment by clyde005** [comment]
He bien c'est un sacré défi ça!
Que je change dans les paramètres ou que je fasse l'addon avec ses réglages....
Cele ne change rien quand je lance un youstream,il met toujours une petite fleche blanche avec écran noir et au bout de quelques secondes "END"...sniiiiiiif

**Comment by TmpName** [comment]
En fait c'est simple, si le lecteur ne mouline pas au moins 1 mn avant d'afficher le message d'erreur c'est que ca vient du timeout.
Apres ou cela se regle sur enigma ??? Sur kodi il y a une seule facon c'est le fichier xml.
>><advancedsettings>
<playlisttimeout>60</playlisttimeout>
</advancedsettings>

Apres j'ai jamais teste l'option dans vstream, mais chez moi j'ai 2 attente, 1 quand le lien est "decode", la ca dure 1mn et tout est bloque, puis le truc rond se met a tourner en bas a droite et c'est reparti pour 1 mn.

**Comment by mino60** [comment]
ben ça m'intéresse ce sujet, surtout pour visionner les films de Film-streaming.co quand la vitesse de ma connexion est tres lente la video ne se lance pas méme aprés modification sur les paramètres vstream  concernant le temp d'attente  pour lire une video
![sans titre](https://cloud.githubusercontent.com/assets/11494048/16325364/c4e906a8-39bd-11e6-8b17-1d5f6f012833.png)

par contre je nais pas ce probléme sur un autre plugin enigma2 

![screenshot](https://cloud.githubusercontent.com/assets/11494048/16325739/f921d5dc-39c0-11e6-88da-9a3c4d11bba0.jpg)
![screenshot1](https://cloud.githubusercontent.com/assets/11494048/16325749/13e02888-39c1-11e6-9a38-6496ba9db759.jpg)
![scenshote3](https://cloud.githubusercontent.com/assets/11494048/16325759/2e015a16-39c1-11e6-903c-2d25cfe8be9d.jpg)
![4097_0_0_0_0_0_0_0_0_0](https://cloud.githubusercontent.com/assets/11494048/16325765/38c5a164-39c1-11e6-800f-724171a83d68.jpg)

j'ai seulement choisie de ne pas arrêter le lecteur et après quelque secondes la video ce lance normalement je précise j'ai ce probléme seulement quand la connexion n'est pas stable

**Comment by clyde005** [comment]
Bon j'ai de quoi tester ce week-end....dommage que je ne trouve pas ce fichier "advancedsettings.xml" dans enigma2....J'ai bien trouvé des dossier "Kodi" mais rien qui ressemble à ça dedans.

**Comment by mino60** [comment]
@clyde005  tu n'a pas suivi les explications de LordVenom  tu doit suivre la video le lien ci-dessus 

![sans titre1](https://cloud.githubusercontent.com/assets/11494048/16329853/7bd93faa-39e5-11e6-8429-a630213d0c87.png)

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16329860/8f1370ae-39e5-11e6-87b9-1e2e00d65668.png)



https://www.youtube.com/watch?feature=player_embedded&v=vuukV3sS32I

**Comment by clyde005** [comment]
Héla mino60,
Je suis un bon élève tu sais, comme je l'avait déjà posté un peu plus haut:

_**"He bien c'est un sacré défi ça!
Que je change dans les paramètres ou que je fasse l'addon avec ses réglages....
Cele ne change rien quand je lance un youstream,il met toujours une petite fleche blanche avec écran noir et au bout de quelques secondes "END"...sniiiiiiif"**_

...j'ai déjà fait ces changements...mais toujours pas de youstream ;-)

**Comment by mino60** [comment]
c'est bizarre le changement des paramètre n'aboutit à rien !!!?...
par exemple sur la source film-streaming.co section tout les films : le film Pixels avant ou après changement des paramètre ou avec les valeurs par défaut  j'ai toujour ce message et  timeout au bout de 20 seconde chrono quelque soit les paramètre.

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16330587/a6f1caea-39ea-11e6-93f0-97ac3d9a51c5.png)

**Comment by clyde005** [comment]
Je confirme....même après les changements le temps avant d'avoir l'erreur reste le même chez moi aussi.
C'est comme si rien ne change??!!

**Comment by LordVenom** [comment]
Attention même sur leur site les films film-streaming.co ne fonctionne pas.

**Comment by clyde005** [comment]
Oula oula...on détourne mon sujet!!
Moi c'est youstream que j'essaye de faire fonctionner....Et sur leurs sites cela focntionne bien ;-)

**Comment by mino60** [comment]
j'ai oublié que tu ai sur enigma2 Vu+ solo2 comme moi avec Vu+ solo 4k quand je voi "une petite fleche blanche avec écran noir et au bout de quelques secondes "END"...sniiiiiiif" il sufi que je clic sur ok et la video se lance normalement.

**Comment by clyde005** [comment]
T'es sérieux??? Faut absolument que je teste cela en rentrant ce soir! 
Alors ça règlerai tous mes soucis ;-)
Si effectivement après "END" je clique ok et ca fonctionne, alors tu es mon sauveur mino60!!!

**Comment by LordVenom** [comment]
Curieux d'avoir des nouvelles :) sinon autre tester mettre la source en playlist avec le menu context ( ajouter a la playlist), c'est pas le même façon de lire le fichier alors avec un peux de chance.

**Comment by clyde005** [comment]
@mino60 
Es-tu sur dzsat ou autres?

@LordVenom 
Cela me fait penser que j'ai constaté un autre petit bug.
Lorsque je sauve une source dans la "Playlist Beta" parfois il m'arrrive que le lien ne s'ouvre pas, alors qu'il s'ouvre bien dans la source d'origine?!

**Comment by mino60** [comment]
Alors tu à le mème probléme que moi connexion faible debit 4 Mo et non stable si tu étais au japon avec 20 Go vitesse de la connexion la video se lance on quelque milliseconde!...
je suis sur dzsat et sat-universe défois.

**Comment by clyde005** [comment]
Ce que je trouve bizarre c'est que (par ex) j'ai 4 films sauvé dans la librairie, mais seulement 1 ne veut plus se lancer de là? Les autres sont toujours ok...

**Comment by LordVenom** [comment]
- J'ai ouvert un autre sujet pour la playlist sinon ont si perd, 
- J'ai installer une lecture direct voir si ça aide mais j'ai un doute (dispo dans la mise à jour la semaine prochaine) en gros vStream lance la lecture par xbmcplugin sauf dans le cas ou la source est en playlist la c'est xbmcplayer directement, maintenant vous pourrais forcer xbmcplayer pour la lecture de base.

**Comment by clyde005** [comment]
Encore une chose que je me demandais...j'aivu ça qu'il va y avoir une mise à jour prochainement.
Je me demande comment va réagir Enigma2 avec ça?? Wait and see ;-)

**Comment by TmpName** [comment]
De memoire pour moi les options a changer sont "curlclienttimeout" et "curllowspeedtime"

**Comment by mino60** [comment]
Pour changer les paramètre setting (curlclienttimeout , curllowspeedtime , stop buffering...ext) on peut utiliser c'est deux programmes : Ares Wizard et Xuntytalk Mantenance.


https://www.youtube.com/watch?v=KOnrlOlOtsk

**Comment by LordVenom** [comment]
Bonne question tous depend du repository utiliser si c'est un spécial faut que eux proposer la nouvelle version si c'est le notre c'est automatique et si la 0.4.2 fonctionne y a pas de raison que ça tourne pas.

Notre repository : https://github.com/LordVenom/venom-xbmc-addons/releases/tag/Repository

**Comment by clyde005** [comment]
Bon je reviens vers vour car j'ai remarqué la chose suivante:
Lorsque j'ouvre un youstream il ne s'affiche pas (petite fleche suivi de END), apparement c'est le lecteur E2player(enigma2) qui ne gere pas youstream.
Si je sauve le lien dans ma librairie je peux avec bouton "menu" et "lire avec" choisir les lecteur présent dans le systeme:
![photo 1](https://cloud.githubusercontent.com/assets/20064977/16356419/23d861da-3ad7-11e6-826f-db41f89c499b.JPG)
![photo 2](https://cloud.githubusercontent.com/assets/20064977/16356420/2a1764a6-3ad7-11e6-9a2f-4f6db6fc824f.JPG)

Et bien en choisissant DVDplayer les lien youstream se lance....MAIS pas de son.
![photo 3](https://cloud.githubusercontent.com/assets/20064977/16356424/4ca1c96c-3ad7-11e6-9d05-74b7f1ccd1ec.JPG)
![photo 4](https://cloud.githubusercontent.com/assets/20064977/16356427/527b26ee-3ad7-11e6-94df-41abcb1eb651.JPG)
En cliquant sur l'option son, il est bien mis "Flux Audio - Inderterminé !!"

Si je pouvais régler ce problème de son ce serait parfait....ou alors installer un lecteur media qui gère tous les liens différents??

Qu'en pensez vous?

**Comment by clyde005** [comment]
Je rajouterai que dans le système paramétres...
Je n'ai aucun "Peripherique de sortie audio"??
![photo](https://cloud.githubusercontent.com/assets/20064977/16356597/8b7de024-3ade-11e6-9cd2-1d0620aaf9dd.JPG)

**Comment by mino60** [comment]
Apparemment et c'est sans doute problème du son de l'AC3 tu à besoin d'un home cinema ou un amplification du son dolby digital avec un cable SPDIF optique si non avec la telecommande clic sur la touche audio et choisie  MPEG .

**Comment by clyde005** [comment]
Mon téléviseur est de 2015.... J'ai vérifié et il est full HD.
C'est fou ce truc! ;-)

**Comment by TmpName** [comment]
Y a pas une option qui traine quelque part dans kodi ou vstream, pour chsoir le lecteur par defaut justement ?
J'ai deja vu ca mais me rappelle plus ou !

**Comment by clyde005** [comment]
Si si.... Ça je peux faire.
Mais mon problème est que seul le lecteur dvdplayer ouvre les youstream....mais sans son!
Actuellement le E2player ouvre d'autres sources (très peu) et youstream se trouve sur quasi tous les liens.

**Comment by LordVenom** [comment]
Tu n'a aucune periphérique audio tu peux même pas lire un film télécharger ? y a un bug la vStream n'a pas le pouvoir de modifier les périphériques lol

**Comment by clyde005** [comment]
Je n'ai ce problème qu'avec le lecteur dvdplayer....le reste j'ai du son.
Je crois que c'est une bonne idée d'attendre le mise a jour en espérant que ce problème soit pris en compte.
Merci a tous pour votre patiente.

**Comment by LordVenom** [comment]
Tente de desactiver le passtrough.

**Comment by mino60** [comment]
Peux tu me dire ou se trouve le lien youstream ou nous donné le nom du film ou serie le quelle vous avez se problème du son j'ai installer la mème image que toi Black Hole 3.0.2 Kodi 16.1

**Comment by clyde005** [comment]
Zut et zut!! Je suis déjà au boulot...je regarde cela ce soir, mais je pense que c'est general pour tout les liens que j'essaye d'ouvrir avec le lecteur DVDplayer.
Toi tu as aussi le E2player comme lecteur par défault? Si oui tu peux essayer d'ouvrir n'importe quel lien youstream...petite fleche et ...END. Meme si j'appuye sur ok ensuite rien ne se passe.

Donc je sauve le lien (youtream) dans mes favoris...ensuite je vais dans mes" favoris beta" je me place sur le lien...---->"Menu" (telecommande) ---->"ouvrir avec" et là je choisi DVDplayer.

Le lien youstrem se ance très bien mais pas de son.
Dans "Paramètres-Systéme-sortie audio-....Le periphérique de sortie audio est aussi grisé chez toi?

ps: Heureux que tu puisses faire le test sur la même image que moi!!!!!

**Comment by mino60** [comment]
j'ai essayé avec youwatch ça marche pas avec zootopie par contre j'ai pas trouver un host qui resomble à youstream sur hosters.py tu peux voir les film avec des hosts plus rapide et fluide comme google video nowvideo ntu flashx ....ext , tu peux essayé la version beta avec le lecteur contenu après timeout, pour sélectionné le lecteur don les paramètre on peut choisir Dvdplayer ou MDplayer Enigma2player xbmcplayer

http://www41.zippyshare.com/v/rObyZWA1/file.html
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/16397169/ffe6097e-3cc2-11e6-9da8-aaa36343c763.png)

**Comment by clyde005** [comment]
Merci Mino pour ton temps!
Tu me dis _**"la version Beta avec le lecteur contenu après timeout"**_...il s'agit du lien que tu as mis? Perso j'utilise le 0.4.2 le dernier je pense?
Mais quand je vois ta copie d'écran cela ressemble à autre chose que chez moi.
Sous quel menu tu trouve cette page avec les lecteurs?

Le tunnel est long mais j'entrevoie un peu de lumière! ;-)
Merci!

**Comment by jeromebvb** [comment]
Bonjour chez moi tous fonctionner nickel et du jour au lendemain j'ai que la source NETU qui fonctionne.
et j'ai créer le fichier advancedsettings.xml avec la config la:
<advancedsettings>
  <network>
    <buffermode>1</buffermode>
    <cachemembuffersize>157286400</cachemembuffersize>
    <readbufferfactor>20</readbufferfactor>
  </network>
</advancedsettings>
et je l'ai mis dans le dossier la %APPDATA%\kodi\userdata (sur PC)
que ce soit sous windows ou android j'ai le même problème

et je n'ai pas l'extension  Easy Advanced Settings dans kodi.

**Comment by TmpName** [comment]
Et sans le fichier advancedsettings.xml ca ne marche pas non plus ? Perso je ne vois rien d'anormal dans ta config.
Moi j'ai ca dans le mien (une grosse partie est desativee).
      \<network>
\
         \<curlclienttimeout>60\</curlclienttimeout>
         \<curllowspeedtime>60\</curllowspeedtime>
        \
         \<disableipv6>true\</disableipv6>
     \</network>

Mais pour n'avoir d'une source qui fonctionne, soit tu es sur un site qui n'a que des liens morts, soit ta maison est en train de passer sous un tunnel.

**Comment by clyde005** [comment]
Etant novice comment faire pour activer urlresolver?
Il faut installer quelque chose?

**Comment by TmpName** [comment]
Nope, dans les options de vstream, juste une case a cocher. Apres tu peux aussi le configurer mais juste lactiver devrait suffir pr les tests.

**Comment by jeromebvb** [comment]
J'ai toujours le meme probleme j'ai la version KODI 15.1
j'ai essayer sans le fichier advancedsettings.xml.les sources ne fonctionnent toujours pas.
j'ai essayer avec le fichier advancedsettings.xml avec la config suivante:
<network>

<curlclienttimeout>60</curlclienttimeout>
<curllowspeedtime>60</curllowspeedtime>

<disableipv6>true</disableipv6>
</network>
ça ne fonctionne pas non plus
et enfin avec urlresolver j'ai une erreur vstream rouge en bas a droite.
il y a quelques jours avec mon fichier advancedsettings.xml tout fonctionner même pas de mise en cache qui bloquer la video toutes les 30 secondes.les videos fonctionner sans coupure.

et pourtant je n'est rien toucher.
je ne comprend d'ou ça peut venir.

**Comment by mino60** [comment]
@clyde005 sur le menu de vstream beta ( la version 0.4.2 avec des changement , des fichiers modifier ou ajouter pour testé avant la sortie de la version 0.4.3 fin du mois.)

@jeromebvb problème de connexion internet comme le robinet si l'eau dan le tuyau et fort tu peux remplire le verre d'eau en quelque secondes et c'est toujours pareil avec les flux internet a forte debit par contre si l'eau et faible pression insuffisante tu mais beaucoup de temp pour avoir une gorgé d'eau don le verre pareil avec mise en cache.
essayé avec la dernière version de kodi 16.1 jarvis
activer urlresolver
essayé de trouver le lien qui ne marche pas et le testé
le tester sur le navigateur
nettoyer sa ram
desinstaller les logiciel unitile pour avoir un PC plus rapide et léger..

**Comment by clyde005** [comment]
@mino60 
Ben moi je n'ai le chois qu'entre 2 lecteurs.... Dvdplayer,Mplayer et mode Auto.
Toi tu as tous ces différents lecteurs dans ton Vu+?

**Comment by clyde005** [comment]
Oeps mauvais bouton ;-)

**Comment by jeromebvb** [comment]
Bonjour
ça re fonctionne chez moi.
C'était bien un probleme de débit internet.
Comme je partage ma livebox avec mon lieu de travail (j'habite sur place)et que mon associé fait tourner des cameras ip non stop.c'est les cameras ip qui pomper tout le debit internet.
maintenant tout fonctionne nickel.
merci pour votre aide a tous.
et longue vie a vstream
