### ISSUE TITLE
Tipee pour ou contre

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons#407]
Je cherche un moyen simple de nous motiver et donc je tombe sur ça

extrais de la page https://www.tipeee.com/about

> 
Pourquoi donner pour un contenu que j'aurai gratuitement ?

D'abord parce que vous pensez que le créateur concerné le mérite, tout simplement !

Ensuite, parce que vous souhaitez l'encourager à continuer et lui donner les moyens de le faire dans de bonnes conditions. Les contenus de qualité demandent de la motivation et du temps. Les promesses de Tips sont une excellente motivation face à ces deux contraintes :)
> 

Je trouve ça plutôt cool des pourboires. Aprés je suis pas sure qu'il accepte vStream mais d’abord je voulais votre (ressentis) sur la question.

**Comment by denseye73** [comment]
salut Lord
personnellement,  je pense que vous mériteriez des dons de la part des utilisateurs (pour toi et Tmpname qui passez bcp de temps sur ce formidable projet)
après, sous quel forme ...  je ne sais pas (tipee, paypal, ...)

**Comment by TmpName** [comment]
Sur la page d'acceuil, il y a la possibilitee de faire des dons.
Moi perso je trouve que cela fait trop usine pour un projet bricole par des passionnes.
Je prefere le concept du "pay me a beer" que tu commences a retrouver sur plein de projet (ce que tu as deja mit en place d'ailleurs), paypal gere tres bien le truc.

Apres meme si Vstream n'a rien d'illegal, suis pas sur que ce soit un projet qui ait besoin de publicite.
Mais surtout l'inconvenient de tipee, c'est que tu prend des engagements, vis a vis de ton projet, des resulats, des promesses. Avec la formule actuelle, zero engagement, personne n'a a se plaindre, tu fais ce que tu veux, personne ne peut rien te dire.

Et je suis un gros fan du zero prise de tetes.

**Comment by denseye73** [comment]
> Sur la page d'acceuil, il y a la possibilitee de faire des dons.

> 
de quelle page d'accueil parles tu ?

**Comment by TmpName** [comment]
Lol, celle la https://github.com/LordVenom/venom-xbmc-addons

Faudra que venom le mette en haut de la page ^^.

**Comment by TmpName** [comment]
Moi l'anglais je le trouve pas dominant sur la page de Vstream, par contre je connaissais pas le site beerpay, et je le trouve excellent aussi, mais par contre c'est vrai que vu que c'est en anglais, et en dollar, ca freine, c'est con c'est un bon concept.

Cote paypal y a le www.paypal.me, qui est plus friendly que le paypal classique.

**Comment by LordVenom** [comment]
Ok c'est fait paypal.me/vstream 

note : Bonjour les modifs quand tu crée la page depuis ton compte y a nom prénom adresse faut créer une societer modifier l'adresse pour avoir quelque chose d'a peux prés anonim.

**Comment by TmpName** [comment]
Put1 Vstream est devenu une societe !
Vstream corporation & co, previens nous quand tu passes en bourse qu'on prenne des actions ^^.

**Comment by LordVenom** [comment]
lol

**Comment by onnlinetool** [comment]
========>>>>>>>>>>>> Telecharger Crack ici

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t
