### ISSUE TITLE
Hoster favori

### ISSUE THREAD

**Issue by denseye73** [LordVenom/venom-xbmc-addons#408]
salut
une idée pour réduire le nombre de clics :-)

pensez vous qu'il serait possible d'ajouter dans les options un hoster favori (uptobox, youwatch, ...) qui serait automatiquement choisi lors du choix du hoster d'un film/série ?

merci

**Comment by TmpName** [comment]
Pour moi ca te rajouterais des clics au lieu d'en supprimer ^^.
Y a de vielles series ou les liens youwatch fonctionnent mais pas les uptostream, jamais de youwatch apres 20h.

En au bout d'un moment tu sais quel hosters choisir en fonction de l'heure ou de la serie, si ca demarre tout seul, tu es bon pr attendre les 2mn, te retrouver avec fichier introuvable, repartir en arriere pr en choisir un autre.
