### ISSUE TITLE
Nouvelle source

### ISSUE THREAD

**Issue by Ronaldonizuka** [LordVenom/venom-xbmc-addons#41]
Salut LordVenom, 
Je te propose cette nouvelle source suite à la recherche sur vstream du film le pianiste (il y a 3 liens qui ne fonctionnes pas) sur ce site http://www.film-streaming.wf/ propose des nouveautés en bonne qualité.
Bon courage.

**Comment by LordVenom** [comment]
je regarderais merci.

**Comment by LordVenom** [comment]
Re, Pas mal mais trop de source en Netu et j'ai toujours pas réussis a faire un resolve pour ce serveur.

**Comment by Europe57** [comment]
Salut, je sais pas si sa marche, mais j'ai trouver sa sur une extention espagnol. Elle date de 2013, mais peut être sa marche encore.

https://github.com/CarlosCondor/pelisalacarta-xbmc-plus/blob/master/servers/netutv.py

Comme je connais pas trop c'est chose, je préfère que tu test ;)

A+

**Comment by LordVenom** [comment]
Nop ça ressemble plus a un truc du genre 

https://github.com/kodi-czsk/script.module.stream.resolver/blob/master/lib/server/neturesolver.py

le tout basé sur du codage 64bit, c'est pas pour rien que même script.module.urlresolver ne la pas ajouté.

**Comment by Europe57** [comment]
Ok ;)

**Comment by LordVenom** [comment]
cela entent dit  je suis toujour a la recherche de bonne source ce site et bien coder vraiment dommage je le garde sous le coude.

@Europe57  : vive la Moselle :)

**Comment by Europe57** [comment]
En parlant de source, j'ai quelque sources que j'avais utiliser pour des séries introuvables et avant de connaitre vstream.

- http://serie-streaming-vf.com/
- http://dpstream.net/ (la souvent c'est des liens purevid, je sais pas si ta un resolver pour sa)
- http://www.k-streaming.com/category/serie (pour les séries)
- http://www.k-streaming.com/ (pour les films)
- http://streamay.com/ (jamais utiliser mais on me la conseiller pour regarder certain film rare, ou série)

Normalement je doit encore avoir d'autres sources sur mon PC portable avant d'avoir un boitier multimédia sous android pour ne plus bloquer le PC portable pour XBMC, je te les donnes aussi si c'est des inédits, quand j'aurais le temps de fouiller dedans.

@LordVenom Aussi mosellan ?

A+

**Comment by LordVenom** [comment]
Merci je regarde ça, et oui le monde est petit lol

**Comment by Dimiria** [comment]
Salut,
J'utilise votre add on qui est just parfait!
Mais petite question, est il possible d'ajouter l'un de mes site web de streaming preferet?
Ce site web est tres complet( serie et film) voici l'url:
www.streaming4iphone.fr

Merci par avance!
Dimitri.

**Comment by LordVenom** [comment]
Merci c'est noté.

**Comment by Ronaldonizuka** [comment]
Je ne comprend pas trop mais c bien dommage :)
Bon courage !
Encore merci pour ta réponse et bonne année
