### ISSUE TITLE
Problème pour avoir le résumé du film!!!..

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#410]
Depuis quelque jours l'option information sur le film ne fonctionne pas et cela dont la plupart des sources?
le journal kodi.log:
http://pastebin.com/0DSYpQ64

**Comment by TmpName** [comment]
Ha merde, c'est pas toi qui a une vielle version de kodi a cause de ta machine ?

En fait, on utilise un code pr verifier si un addon est present sur ta version de kodi, chez nous ca marche mais chez toi, c'est erreur direct, donne moi 10 mn, je vais te faire passer un code a tester.

**Comment by mino60** [comment]
Non c'est pas mois j'ai Vu+ solo 4k

![24599](https://cloud.githubusercontent.com/assets/11494048/16352975/bce02386-3a73-11e6-8316-07f6e83f73c3.jpg)
![sans titre](https://cloud.githubusercontent.com/assets/11494048/16352984/cecce9c6-3a73-11e6-92f8-224210359f5f.png)
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/16352992/e4e2cc08-3a73-11e6-9e9c-3444fa4664c8.png)
![sans titre2](https://cloud.githubusercontent.com/assets/11494048/16353004/11f4dd80-3a74-11e6-9887-a9571749fdb6.png)

après le test avec le nouveau fichier config.py le résumé n'ai pas on français mais on anglais

![sans titre3](https://cloud.githubusercontent.com/assets/11494048/16353105/bc94c772-3a75-11e6-83d1-4deb340ace15.png)

Zone-telechargement
![sans titre4](https://cloud.githubusercontent.com/assets/11494048/16353112/dda1bb14-3a75-11e6-8bda-bcaa1b21187c.png)

**Comment by LordVenom** [comment]
j'ai oublier le try: Pfff , Donne nous le log quand tu a le message d'erreur ou au moin la ligne qui cause l'erreur.

**Comment by TmpName** [comment]
Ha oui merde, je viens de voir que moi aussi j'avais cet addon installe ( a cause d'un skin) c'est pour ca que j'avais pas le message d'erreur, je croyais que c'etait la version de @mino60 qui deconnait.
