### ISSUE TITLE
Widget vStream

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#411]
#Est que c'est possible d'avoir une image des posters on plein écran sur vstream?

**Comment by LordVenom** [comment]
Tu parle du Fanart ? oui en activant le metadonnée ou en passant par la recherche visuelle.

**Comment by mino60** [comment]
Est ce que on peux lancé Zone -telechargement son ouvrir vstream sur la section blue ray juste on sélectionnant le dossier video sur kodi, chataigne73 a posé la meme question il ya quelque jours
comme sur Pulse

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16393080/8a8f236c-3caf-11e6-9942-891a0b85b7fc.png)

lecture du film direct son passé par plusieurs étapes:

![sans titre1](https://cloud.githubusercontent.com/assets/11494048/16393231/2ec35a2a-3cb0-11e6-9850-ff0f361555af.png)

**Comment by LordVenom** [comment]
Oula non, je sais que le thème Mimic propose ça mais ça n'a jamais fonctionner.Perso le seul moyen que je connais c'est de créer une playlist presque tous les thémes propose de mettre une playlist en acceuil.

-Video/liste de lecture/ créer la tu ajouter une regle qui dit que le chemin et celui du dossier de vstream.

![screenshot006](https://cloud.githubusercontent.com/assets/4380112/16410006/b6d658ca-3d20-11e6-910a-130c243964a4.png)


Ensuite tu ajouter a la librairie les sources de vstream et tu peux lancer un film direct depuis l'accueil.

**Comment by LordVenom** [comment]
A si ça fonctionne avec Mimic

![screenshot007](https://cloud.githubusercontent.com/assets/4380112/16410851/afb9f854-3d24-11e6-84b9-5ebe7a9ddacd.png)

**Comment by mino60** [comment]
j'ai réussie de faire fonctionné zone-telechargement directement avec un fichier qui se trouve don ares wizard (programe) Browse Build new entries  install contien le skin Aeon Nox5: SILVO on peut parametrer et configurer le skin

![sans titre2](https://cloud.githubusercontent.com/assets/11494048/16429912/69288702-3d79-11e6-90e7-e1fa68ecdbd4.png)
![sans titre](https://cloud.githubusercontent.com/assets/11494048/16429924/7ab6eda6-3d79-11e6-8953-ad5797e4299e.png)
![sans titre3](https://cloud.githubusercontent.com/assets/11494048/16429942/8d133568-3d79-11e6-9271-8739ab61f6a9.png)
![sans titre4](https://cloud.githubusercontent.com/assets/11494048/16429955/a3c4acce-3d79-11e6-875f-680e992437f2.png)
![sans titre6](https://cloud.githubusercontent.com/assets/11494048/16429971/b06547b8-3d79-11e6-9202-bbc840b84a36.png)

le résumé  du film n'ai pas on français comment supprimé farnat  qui et on vert et avoir les information sur le film .

**Comment by LordVenom** [comment]
Je suis Dsl mais j'ai rien compris

>j 'ai réussie de faire fonctionné zone-telechargement directement avec un fichier qui se trouve don ares wizard (programe) Browse Build new entries install contien le skin Aeon Nox5: SILVO on peut parametrer et configurer le skin

>

**Comment by mino60** [comment]
Il faut installer Ares Wizard (voir la video) ensuite sur le menu de Ares Wizard sélectionner  Browse Builds  après New Entries puis on va choisir Pulse-Aeon-Nox un fichier de plus de 300 Mo vas être telecharger et installer , sur le system  apparence on peut configurer zone-telechargemon sett ( widget)

https://www.youtube.com/watch?v=KOnrlOlOtsk

Skin Aeon-Nox -silvo
https://www.youtube.com/watch?v=JXW2BJ6OIzU

**Comment by TmpName** [comment]
Les information n'apparaissent pas sur Vstream directement car cela est trop lourd pour ce site.
Par contre en passant par le menu contextuel, il s'affiche sans probleme normallement.

**Comment by mino60** [comment]
@LordVenom on a pas besoin de changer tout le système il suffit d'installer le skin Aeon-Nox 5:SiLVO
pour avoir les widgets


![sans titre](https://cloud.githubusercontent.com/assets/11494048/16476843/ec03a25c-3e8b-11e6-8fd5-200a45dc41f2.png)
![sans titre](https://cloud.githubusercontent.com/assets/11494048/16476849/fdff8656-3e8b-11e6-91d6-a9236b202be6.png)
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/16476858/0c962e0e-3e8c-11e6-988f-223035351d0b.png)
![sans titre2](https://cloud.githubusercontent.com/assets/11494048/16476864/1a23fd44-3e8c-11e6-931e-d4efe6a6553c.png)

**Comment by mino60** [comment]
J'ai installer le skin Aeon Nox 5: SiLVO pour les widgets qui me permet d'avoir vstream et Zone-telechargement sur la page d'accueil de kodi, on suite j'ai paramétré les métadonnées TMDB et TVDB on langue française sur les paramètre vstream maintenant j'ai les information sur les films on français appartement l'adresse de TMDB a changer (themoviedb.org/fr), mais le problème c'est comment avoir les informations sur les films sur la page d'accueil de kodi, remarque pour la source kepliz j'ai pas eu ce problème, je crois que le problème se trouve dan les entreés (titre image et url)
sur le script Zt.

![sans titre](https://cloud.githubusercontent.com/assets/11494048/16515725/f317d67e-3f73-11e6-8439-61bc5e5fa8c4.png)
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/16515741/0bde9940-3f74-11e6-9338-bc2649bd8e4e.png)
![sans titre2](https://cloud.githubusercontent.com/assets/11494048/16515753/2b41f958-3f74-11e6-9af8-9bac5eeda3d4.png)
![sans titre4](https://cloud.githubusercontent.com/assets/11494048/16515775/42bed43e-3f74-11e6-9b1a-e8e8123256f8.png)

**Comment by TmpName** [comment]
Ca marche pr kepliz et pas ZT ?
J'ai rien suivi du tout, je debarque juste, mais si le scrapper fait en fonction du nom du film, ca peut venir de ca, les nom venant de ZT doivent etre plein d'infos parasites, mais le soucis c'est que je n'ai aucune idee de comment fonctionne cet addon ....

**Comment by partouch** [comment]
Bonjour, 
Petite question comment ajouter la "source" ZT à une play list?
J'ai bien tenter d'ajouter un favoris mais ça ne semble pas être ça, le fichier zone_telecharg...._com.py non plus ...
je me sent tout bête sur le coup 

Un peut d'aide svp :)
