### ISSUE TITLE
TV du Web

### ISSUE THREAD

**Issue by X-ardion** [LordVenom/venom-xbmc-addons#413]
Bonjour Venom, depuis plusieurs jours, les chaînes M6 et 6Ter ne fonctionnent pas dans la catégorie TV du Web.

Merci.

**Comment by LordVenom** [comment]
#412 mise a jour.

**Comment by X-ardion** [comment]
Bonjour Venom, désolé de te déranger encore avec cela, mais M6 et 6Ter ne fonctionnent toujours pas dans TV du web. J'ai le message suivant qui apparait "Retrouvez M6 sur 6play disponible sur le site Internet www.6play.fr". Je précise que je ne suis pas en France métropolitaine et le réseau de mon fournisseur d'accès internet local n'est pas aussi stable qu'en France (cela varie entre 1mega et 4 mégas). Je regarde beaucoup ces chaines, et vu mon réseau, cela me conviens, même si ce n'est pas de la HD.
J'ai essayé FramaPad, mais c'est encore en version beta, ça coupe beaucoup (même après avoir suivi ta manipulation). Donc TV du web est une alternative pour avoir ces chaines.

Merci de ta compréhension et de ton super travail (ainsi que celui de tes collaborateurs: TmpName etc ..).

**Comment by TmpName** [comment]
Pas encore trouve de liens plus fiable, pour le moment ce que j'ai vu de mieux c'est les liens de framapad, la ca tourne sans coupure, mais comme le dit LordVenom, ces liens la n'etant pas officiel, on ne peut pas garantir la stabilite.
Des que quelqu'un trouvera mieux, ils seront mit a jour, mais pour le moment pas encore trouve.

**Comment by X-ardion** [comment]
Je vais patienter en attendant les nouvelles mise à jour.  Merci pour ta réponse.
