### ISSUE TITLE
Connexion sur Zone telechargement

### ISSUE THREAD

**Issue by Bigups23** [LordVenom/venom-xbmc-addons#414]
Bonsoir,

J'ouvre vstream toutes les sources ZT, et là j'ai bien toutes les affiches qui sont là cependant, quand je clique sur un titre, connexion impossible !!

Une idée ?

**Comment by henri4bis** [comment]
Bonjour.
N'utiserais-tu pas un vpn ou un proxy ?

**Comment by TmpName** [comment]
Le site etait out cet apres-midi, ca ne remarche tjours pas chez toi ?

**Comment by Bigups23** [comment]
Non toujours pas, oui le site a été coupé cet après-midi un certain temps mais là il est de retour mais ma box droid n'arrive pas à chopper le truc

Non pas de VPN pas besoin de ça

**Comment by TmpName** [comment]
Et ca marche en passant par navigateur ?

**Comment by Bigups23** [comment]
Bonjour,

Quand j'arrive sur la page http://prntscr.com/bmggr7 impec

Quand je clique sur un film http://prntscr.com/bmggyv  j'ai ça

possibilité d'avoir mon IP bloquée, je vais attendre qu'elle change, je suis en IP dynamique on verra
au prochain changement !
