### ISSUE TITLE
Film 3d sur zone téléchargemnt.

### ISSUE THREAD

**Issue by henri4bis** [LordVenom/venom-xbmc-addons#415]
Bonjour à tous.

Je ne sais pas si c'est faisable mais serait-il possible d'ajouter les films 3d dans le menu de choix pour zone téléchargement ?
(pour un novice c'est seulement une ligne à ajouter au menu mais j'imagine que pour un programmeur c'est peut-ètre infaisable )
En tous cas merci pour la qualité de vstream

**Comment by TmpName** [comment]
Ca n'y est pas deja ?
Je le vois dans le code, 8 eme icones.

**Comment by spcxsat** [comment]
si si il y es deja je confirme

**Comment by henri4bis** [comment]
Bonjour.
Merci pour vos réponses mais pour moi le problème persiste ; j'essaye de l'expliquer plus clairement 
J'utilise la derniere version de vstream avec une box ANDROID.
Pour zone télechargement les icones vont de ACTION jusqu'a WESTERN .
Il n' y a rien concernant les films 3D.
D'ailleurs je n'ai jamais pu choisir un film en 3d avec vstream . C'est pour cela que je pensais que c'était infaisable.
Quelqu'un pourrait-il préciser les differentes actions à mener pour aller dans ce menu 3d que je suis incapable de trouver.
Merci à tous.

**Comment by TmpName** [comment]
Il te faut aller sur la premier page de ZT, la ou tu as les icones pour faire les recherches. La premiere icone etant pr la recherche de film.

**Comment by henri4bis** [comment]
Merci TmpName.
J'ai compris ton explication et je confirme que ça marche .
Je n'avais jamais trouvé la bonne méthode.
En tous cas c'est effectivement RESOLU.
Merci et bonne continuation.
