### ISSUE TITLE
Uptostream

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#416]
Erreur: Fichier introuvable avec le host Uptostream

**Comment by TmpName** [comment]
Alors la, je sais pas ce qui c est passe, mais c'est bon normallement c'est corrige.

**Comment by arzaz** [comment]
Le problème persiste, je viens de faire le test sur zone téléchargement et j'ai toujours erreur fichier introuvable.

**Comment by arzaz** [comment]
J'ai installé le host manuellement, mais ça ne fonctionne pas sur Zone-telechargement

**Comment by TmpName** [comment]
Ha wi merde, je l'ai oubli celui la, en fait pour ZT c'est uptobox qui gere tout pas uptostream.
Je corrige de suit.
