### ISSUE TITLE
Besoin d'aide pour Framapad

### ISSUE THREAD

**Issue by patoche2025** [LordVenom/venom-xbmc-addons#417]
Bonjour tout le monde,

Je viens vers vous pour Framapad quand je clique dessus il me met un message d'erreur j'ai la dernière version de vstream je crois que c'est dû au fait que je suis en belgique pourtant j'utilise Cyberghost pour que mon adresse IP soit une IP Française mais voilà ca ne marche est ce que vous pouvez m'aider ou me donner des tuyaux (je sais que j'ai déjà posé cette question mais je trouve pas de solution)

D'avance je vous remercie

**Comment by LordVenom** [comment]
Merci pour le rapport c'est corriger

**Comment by patoche2025** [comment]
Re effectivement ca fonctionne sauf que quand je clique sur l'une des chaines rien se passe que puis-je faire pour que ca fonctionne ?

**Comment by LordVenom** [comment]
C'est encore en bêta mais le vrais but et que vous pouvez modifier vous même les lien sans connaitre python.J'ai fait une mise a jour.

**Comment by patoche2025** [comment]
Oui super j'ai vue alors maintenant tu vas dire que je suis chiant mais quand je clique sur une chaîne n'importe laquelle j'ai l'image mais que 13 sec après ca se coupe et je dois re-cliquer sur la chaîne est ce que tu as ça aussi ou il y a moyen de mettre la chaîne en lecture loop?

**Comment by LordVenom** [comment]
Oui j'ai vue je suis dessus mais ça vient pas de vStream mais des iptv je cherche, je cherche...

**Comment by LordVenom** [comment]
Nouvelle liste même problème peux etre résolut par cette solution.

1- Lancer la chaine
2- Stopper la chaine
3- allez a la liste de lecture actuel 
![screenshot008](https://cloud.githubusercontent.com/assets/4380112/16495250/e4a9dd12-3eec-11e6-92bb-1cabd1b8117f.png)
-4 Mettre la répétition sur TOUT
![screenshot009](https://cloud.githubusercontent.com/assets/4380112/16495264/fa959684-3eec-11e6-88a0-63e04e2f433a.png)

La chaine vas ce relancer une foix ou 2 puis fonctionner normalement.

**Comment by X-ardion** [comment]
J'ai commencé à faire un listing des chaines qui fonctionnent, et celles qui ne fonctionnent pas. J'en ai testé une cinquantaine avec environ 30 qui fonctionnent correctement (dont TF1 HD et M6HD). Je viens de re-tester 4 heures après et ces 2 chaînes ne fonctionnent plus.
Je précise que les tests ont été effectués sur un Raspberry 2, à l'étranger.

**Comment by TmpName** [comment]
Ca doit dependre des heures et de l'affluence, la suis en train de tester, pas de soucis, mais comme le dit LodVenom ce genre de lien n'est pas officiel et donc non fiable. Ca va dependre des liens que les gens vont trouver, suis dls, mais dans tout les cas ce sera tres aleatoire.

**Comment by TmpName** [comment]
Pour les coupures c'est un probleme de buffer.
Appuyez sur "o" durant la video, deuxieme ligne aq XX%c'est votre tampon, quand celui ci arrive a zero, plus de flux.
Il y a moyen d'augmenter la memoire tampon,, la video demarrera un peu plus tard le temps de la mise en tampon, mais si a aucun moment votre debit ne remonte, c'est foutu.
Eg si vous mettez 30s de mise en tampon, kodi pourra encaisser pendant 30s un debit de 0, pendant 1mn un debit de 50%, ect .... mais si ca ne remonte jamais, ca va couper dans tout les cas. il faut voir si au boiut de quelques secondes/minutes, le debit se stabilise.

**Comment by X-ardion** [comment]
Merci pour ta réponse, j'utilise actuellement un raspberry 2 sous openelec et je me demandais comment augmenter la mémoire tampon?
Merci

**Comment by sebi0606** [comment]
@X-ardion utilise advancedsettings tu trouveras toutes les infos là https://www.tvaddons.ag/kodi-addons/show/plugin.program.advancedsettings/

**Comment by TmpName** [comment]
Yep mais j'ai peur que cela ne serve a rien, j'ai refait des test, a certains moment impossible d'avoir un flux constant donc a moins de mettre une mise en tampon de 1h, c'est dur d'avoir plus de 2mn d'emmission.

**Comment by X-ardion** [comment]
De : sebi0606 <notifications@github.com>
 À : LordVenom/venom-xbmc-addons <venom-xbmc-addons@noreply.github.com> 
Cc : X-ardion <daunassansraanui@yahoo.fr>; Mention <mention@noreply.github.com>
 Envoyé le : Samedi 2 juillet 2016 8h47
 Objet : Re: [LordVenom/venom-xbmc-addons] Besoin d'aide pour Framapad (#417)
   
@X-ardion utilise advancedsettings tu trouveras toutes les infos là https://www.tvaddons.ag/kodi-addons/show/plugin.program.advancedsettings/—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  
Merci pour le tuyau sebi0606, j'étais justement en train de l'essayer quand j'ai reçu ton message. Mais cela n'a pas changé grand chose.
Je vais essayer d'écumer les forums pour tenter de trouver une autre solution.
Mais merci pour ton aide.

**Comment by X-ardion** [comment]
Ok merci pour l'info. Ensuite pour moi, impossible de mettre 1h de tampon sur mes raspberrys ou sur ma box android. 

      De : TmpName <notifications@github.com>
 À : LordVenom/venom-xbmc-addons <venom-xbmc-addons@noreply.github.com> 
Cc : X-ardion <daunassansraanui@yahoo.fr>; Mention <mention@noreply.github.com>
 Envoyé le : Samedi 2 juillet 2016 22h54
 Objet : Re: [LordVenom/venom-xbmc-addons] Besoin d'aide pour Framapad (#417)
   
Yep mais j'ai peur que cela ne serve a rien, j'ai refait des test, a certains moment impossible d'avoir un flux constant donc a moins de mettre une mise en tampon de 1h, c'est dur d'avoir plus de 2mn d'emmission.—

**Comment by TmpName** [comment]
Je te rassure, c'est impossible pour tout le monde. Surtout que ca voudrait dire que quand tu veux voir quelque chose, il te faut demarrer la machine 1h avant.

**Comment by X-ardion** [comment]
Merci.

**Comment by henri4ter** [comment]
Bonjour.
J'ai déja eu ce problème avec des listes IPTV.
Il faut remplacer  chaine.ts par chaine.m3u8
