### ISSUE TITLE
Vstream ne fonctionne pas avec OSMC

### ISSUE THREAD

**Issue by vozerpa** [LordVenom/venom-xbmc-addons#418]
Bonjour,

J'essaie d'installer vsream sur OSMC qui est sur un PI 3 et ça ne fonctionne pas....
Il y un message d'erreur concernant youtube 2.9.9 mais pas le temps de tout lire.

J'ai essayé avec le dépot mais apres installation il reste a la version 0.0.1 et me dit qu'il n'y ap as de mise a jour.

J'ai testé aussi depauis un fichier zip depuis la version 3.8 de vstream.

Une idée ? Mon osmc est mal installé ?

Merci d'avance.

**Comment by LordVenom** [comment]
Il faut installer vStream depuis le repo : normal que le repo soit en version 0.0.1

- Système / Extention / installer depuis un dêpot / Venom depot ou vStream depot je sais plus lol

**Comment by vozerpa** [comment]
Merci de la réponse rapide !
Non ça ne fonctionne pas mieux depuis le dépot...
Finalement j'avais une mise à jour de osmc et j'ai réussi à l'installer depuis le zip 4.2

Donc voila c'est résolu !

Et merci pour ton travail.
