### ISSUE TITLE
Pas de mise à jour proposée

### ISSUE THREAD

**Issue by mmtest1** [LordVenom/venom-xbmc-addons#419]
bonjour,
voici mon problème : j'ai installé la mise à jour proposée il y a quelques jours via Vstream pour pouvoir utiliser la nouvelle fonction framapad mais celle-ci me renvoyée une erreur à chaque lancement, j'ai donc nettoyé le cache de kodi, de l'addon et désinstallé puis réinstallé Vstream en v0.42. Depuis je me retrouve en version de base 0.42 et les mises à jour ne me sont plus proposées alors qu'avant un popup me prévenez de la disponibilité d'une mise à jour à chaque lancement de l'addon. Il y a-t-il un moyen pour forcer la recherche de mises à jour ou la sortie prochaine d'une v0.43 réglera le problème ? Cela touche la nouvelle fonction beta framapad mais plus ennuyeux encore les mises à jours des sources dont un grand nombre deviennent inaccessibles. 
Je vous remercie pour votre excellent travail et sa mise à disposition en version libre.

**Comment by LordVenom** [comment]
Bonjour.

Avance la date de ton PC de 4jour

**Comment by mmtest1** [comment]
merci pour la réponse rapide,
je tourne sous raspberry b+ + OSMC et je n'ai pas de clavier pour quitter kodi et modifier la date sous raspbian, je peux me connecter en ssh mais je maîtrise très moyennent la ligne de commande, je pense qu'il ne me reste plus qu'à attendre quelques jours pour qu'elle me soit à nouveau proposée.....
Merci pour le suivi
