### ISSUE TITLE
Problème de lancement de film Kodi 17 Alpha 2

### ISSUE THREAD

**Issue by spcxsat** [LordVenom/venom-xbmc-addons#421]
Bonjour,

Je sais que vous tenez pas beaucoup d'importance à cette version qui es une Alpha.

Cependant, depuis la mise à jours en 0.43 les lien ne fonctionne plus quand on clique dessus on a le message de 

Échec de lecture d'un ou plusieurs fichier. Consulter le journal pour plus d'information sur ce message

Et ceci sur tous les site et tous les lien alors que avec la 0.42 ca fonctionne très bien.

Si je doit vous fournir un log, je veux bien faut juste me dire où il ce trouve pour que je vous le donne.
Mon installation es sous Android une nvidia sheild tv

Pour info si non avec la version 16.1 ca fonctionne du tonnerre comme d'habitude du super boulot.

**Comment by TmpName** [comment]
Non, rien ne presse, les captcha non plus ne fonctionnent pas sur la V17, mais on ne peut pas savoir si ils vont remodifier le code d'ici la sortir officielle, donc pour le moment moi j'attend.

En fait soit elle est bugguée jusqua la moelle, soit ils ont encore tout modifie de leur coter juste pour faire chier les devs.

**Comment by spcxsat** [comment]
Ok no probleme, c'etais juste pour vous informer que cela fonctionnais avec la 0.42 mais plus depuis la 0.43 alors que si je remais la 0.42 sais ok
il y a surement eu une modif entre la 0.42 et la 0.43 de vstream pour le lancement des liens sais tous ;)

**Comment by TmpName** [comment]
Ha la 0.42 marche mieux que la 0.43 dans kodi V17 ????
Put1 je sens qu'on va en chier quand elle va passer officielle, deja que la precedente freeze tout les 2 jours chez moi alors que la V15, pas un seul bug.

**Comment by spcxsat** [comment]
Yes elle fonctionne comme un charme la 0.42,  juste le problème des captcha mes sais tous

**Comment by mino60** [comment]
effectivement la version 0.4.3 nouveaux :  intégration du plugin xbmc player modification sur le fichien config.py
essayé sur paramètres le dvdplayer

**Comment by spcxsat** [comment]
Je vient d'essayer même mplayer ou auto et ca ne fonctionne pas lol.
Même en changeant le fichier seting.xml avec celui de la 0.42 même soucis
Merci quand même
Il a du avoir des changement récemment car avec la bêta savait commencer à deconner il y a une semaine environ voir un peu plus m'en rappel plus très bien

**Comment by spcxsat** [comment]
Voilà j'ai trouver ce qui fonctionnait mal.

J'ai juste remplacer le fichier player.py de la 0.43 par celui de la 0.42 et tous es ok sous la dernière alpha  de kodi

**Comment by TmpName** [comment]
Ha ? ca ca va interesser LordVenom, vu qu'il a fait de grosses modif dessus recemment, Mais a mon avis, comme moi il attend la version off avant de se prendre la tete.

**Comment by spcxsat** [comment]
Yes,
C'était juste l'histoire de voir d'où sa deconnais
Vue que ca fonctionnais bien avec la 0.42.
Perso j'utilise beaucoup SPMC sous Android qui es une version 16.1 de kodi un peu modifier et la version 17 sais surtout pour voir les nouveauté et sais vravais que franchement sais beau et ca fonctionne bien à par pour les captcha

**Comment by LordVenom** [comment]
Y a pas tant de modif que ça dans le player je sais pas il me faut le log. je vais devoir installer la v17 pour tester mais ça c'est pas pour tout de suite.

Pour trouver le log: 

https://github.com/LordVenom/venom-xbmc-addons/wiki/Dossier-log

**Comment by spcxsat** [comment]
Voici mon log, je sais pas si ca pourra aider
[kodi.zip](https://github.com/LordVenom/venom-xbmc-addons/files/345005/kodi.zip)

**Comment by LordVenom** [comment]
Pk tu n'est pas en auto ? dans les préférences tu as l'aisser xbmc.pluging ?

13:41:44 T:1461492016   DEBUG: 	[PLUGIN] Vstream: playertype from config: dvdplayer
13:41:44 T:1461492016   DEBUG: 	[PLUGIN] Vstream Erreur: Fichier introuvable
13:41:44 T:1461492016   DEBUG: 	[PLUGIN] Vstream: Table initialized

**Comment by spcxsat** [comment]
On va dire, que j'ai essayer de modifier tt les config pour le lancement avec le lecteur mais cela ne fonctionnait pas.
Il te faudrait un autre log en auto?

**Comment by LordVenom** [comment]
J'installe Kodi 17 a l'instant. je revient vers toi aprés quelque test.

**Comment by LordVenom** [comment]
Peux tu tester avec ce fichier

https://raw.githubusercontent.com/LordVenom/venom-xbmc-addons-beta/master/plugin.video.vstream/resources/lib/player.py

a remplacer par ton player.py dans plugin.video.vstream\resources\lib

**Comment by LordVenom** [comment]
Pour info ont ne plus plus forcer le DVDPlayer sous Kodi 17 ou c'est un bug qu'il doivent réparer.

**Comment by spcxsat** [comment]
Ok pour la précision.
Donc la je vient de placer ton fichier et j'ai remi il me semble les réglage pas défaut.
Xbmcplugin(recommandé) pour lecture par défaut et pour le vidéo player en auto même si griser.
En tous cas la ca fonctionne pour le lancement des film. Bravo tu a trouver le bug.
Faut avouer qu'elle es sympa quand même cette Alpha je sais pas si tu a testé un peu plus.
