### ISSUE TITLE
Problème lecteur depuis mise à jour 

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#422]
Bonjour à tous depuis la mise à jour problème de lecture video avec les vidéos de Spion avec résolve qui tourne en boucle à la fin de la video et les vidéos ne vont pas jusqu'à la fin et sur les vidéos  zone de telechargement à la fin d'un film ou d'une serie le lecteur met à nouveau en résolve en boucle j'ai regarder sur liste de lecture je suis bien en répéter non 
Merci d'avance

**Comment by TmpName** [comment]
Tu as regarde quel lecteur tu avais dans les options de Vstream, sur le premier onglet quand tu affiche les parametres ?
Moi j'ai teste un film sur uptobox et une video sur star wars sur Spion, pas vu de prbs.

**Comment by LordVenom** [comment]
Je suis pas sure mais a mon avis tu as regarder une chaine tv avant.Pour faciliter la lecture TV j'ai Forcer la répétition mais j'ai pas ajouter de désactivation vérifie que la playlist n'est pas en répétition.Je corrige ça dans la semaine.

**Comment by sebi0606** [comment]
j'ai bien vérifié et je ne suis pas en répétition sur la liste de lecture c'est bien sur non mais effectivement si tu peux désactiver la répétition merci d'avance

**Comment by LordVenom** [comment]
Tu n'a pas répondu a TmpName quel lecture utilise tu ?

**Comment by sebi0606** [comment]
j'utilise spmc 16.3 et le lecteur par défaut de vstream j'ai aussi utilisé le mplayer et le dvdplayer 
Avec le même souci pour les 3 lecteurs

**Comment by LordVenom** [comment]
J'attend encore un retour d'un autre poste et je fait une mise a jour.

**Comment by sebi0606** [comment]
Ok j'essaie ce soir et je vous tiens au courant 
Merci en tous cas

**Comment by sebi0606** [comment]
Nickel pour moi @LordVenom merci encore bonne soirée
