### ISSUE TITLE
The digital theater

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#423]
Bonsoir j'ai une demande un peu particulière à vous faire pourriez vous ajouter ce site http://thedigitaltheater.com/ site qui propose toute les intros dolby et les bandes annonces en qualités nickel avec le son en flac 
Merci d'avance

**Comment by TmpName** [comment]
Mais Il y a du Fr dessus ? ou sous titre ?

**Comment by sebi0606** [comment]
oui mais c'est pour pouvoir utiliser les intros dolby dts et thx en cinéma expérience

**Comment by mac1202** [comment]
Pkoi ne pas juste les télécharger en les stocker en local ?
