### ISSUE TITLE
Démarrage rapide des films. 

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#424]
J'ai apporté quelques modifications sur la source film-streaming.co " Le seul site de streaming en HD 720p 100% Gratuit " affin de pouvoir lire les vidéo films en direct et en quelque secondes juste sur la page d'accueil de kodi grâce à l'option widget en peut avoir un démarrage rapide des films on plus l'option choisir page et mème la recherche.

http://pastebin.com/TTewp7ZG

![sans titre6](https://cloud.githubusercontent.com/assets/11494048/16552062/23f6b610-41be-11e6-8085-7b83ea9e4629.png)

2 secondes : 
![sans titre3](https://cloud.githubusercontent.com/assets/11494048/16552929/30b8b734-41c5-11e6-9a60-0ba28887bdae.png)

en 3 secondes la lecture du film démarre : 
![sans titre4](https://cloud.githubusercontent.com/assets/11494048/16552952/6bccdf94-41c5-11e6-9c55-6e8918fd5faa.png)

sur kepliz
![sans titre1](https://cloud.githubusercontent.com/assets/11494048/16552118/a4427598-41be-11e6-93a4-250340b7b6c4.png)

Zt :  toujour pas d'information mème si les métadonnées son activer !...
j'ai modifié les entrée le lien (adresse image) à disparue mais ça na pas résolu le problème ?
![sans titre](https://cloud.githubusercontent.com/assets/11494048/16552537/2059106c-41c2-11e6-96de-be08b7d22483.png)
![sans titre2](https://cloud.githubusercontent.com/assets/11494048/16552662/1d102c32-41c3-11e6-848e-da5e4846d09d.png)

**Comment by LordVenom** [comment]
Tu force la lecture au lieux d'afficher le hoster ok ça fonctionne mais c'est pas bon il faut une condition 

Par exemple: si je vient du plugin widjet alors je lance la lecture sinon j'affiche le hoster.
