### ISSUE TITLE
Un problème sur Themoviedb/vstream recherche.

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#426]
Bonjour ....
bug don la recherche streamcomplet, un autre problème la fonction recherche  à travers themoviedb/vstream?
exemple: le film " Thé au sahara " le film existe sur film-sttreaming.co mais le moteur de recherche vstream ne le trouve pas juste un film "sahara" sur cette source, par contre la fonction recherche sur la source elle mème pas de problème le film on question il ai bien trouvé!!!.

**Comment by TmpName** [comment]
J'ai pas vu de probleme avec la recherche sur streamcomplet.
Par contre pr le second probleme, c'est a cause de l'accent, on est oblige de le virer, et si tu fais la recherche avec the au lieu de thé ben ca marche plus ...., La par contre je suis dsl mais je pense que cela va rester comme ca.

**Comment by LordVenom** [comment]
J'ai tester avec Batman Superman L'Aube de la Justice effectivement les caractères ne passe pas j'ai donc fait des teste dans showhoster de tmdb.

http://pastebin.fr/47204

Faite des testes et dite moi

**Comment by TmpName** [comment]
C'est quoi le test avec batman ? il n y pas d'accent dans le titre ?
Si il n'y que ce site qui deconne, il vaut mieux laisser sans accents, c'est plus a leur moteur de recherche de focntionner sans que nous a faire avec, on aura moins de probleme a faire les recherches sans que avec, jamais d'accents en informatique.

**Comment by LordVenom** [comment]
Tu imagine bien que si c'etait ça j'aurais pas toucher lol, non tout les titre avec caractère spéciaux ne passe pas

**Comment by TmpName** [comment]
Je viens de faire le test avec "hotel transylvanie" avec l'accent a la con sur le "o" et j'ai devant les yeux plus d'une dizaine de resulat, il n'y aucun probleme avec les caracteres accentues, un site bien fait doit marcher sans les accents.
Par contre tu as fais quoi comme test avec batman ? il n' y pas de caractyeres accentue dans "Batman Superman L'Aube de la Justice" ?

**Comment by LordVenom** [comment]
Ben si le l' :)

**Comment by TmpName** [comment]
Serieux meme les apastrophes ??
Tu te prend la tete pr rien, sur sokro, il te faut tout les mots exacts et dans le bon ordre (pire que le tierce) "superman batman" >> pas de resultat

Par contre, tu as raison l'apostrophe met le bordel car il est supprime et pas remplace, c'est a cause de la convertion unicode au debut du nettoyage.

J'y jette un oeuil de suite, ca devrait aller mieux meme en virant les accents.

**Comment by TmpName** [comment]
Ligne 568
>>sMovieTitle = unicodedata.normalize('NFD', sMovieTitle).encode('ascii', 'replace').decode("unicode_escape")#vire accent et '\'

igniore > replace

Avec cette modif l'apostrophe est remplacee par un '?' et 3/4 ligne plus bas elle va etre remplacee par un espace, le resultat est beacoup mieux.

**Comment by LordVenom** [comment]
Ben j ai tester en encodant les caractères ça marcher pas mal tu as tester mon bon de code ?  Je continue les teste dans la semaine

**Comment by TmpName** [comment]
Ha non, pas de soucis ca marche tres bien, j'ai teste avec plein de nom a la con comme "L'age de glace" avec un accent sur le A dont je ne sais meme pas ou c'est sur mon clavier.

"Le garçon et la bête", c'est bon aussi.

**Comment by LordVenom** [comment]
J'ai envoyer le fichier sur bêta et aussi limiter la recherche sur kepliz c'est pour ça que j'avais pas de réponse au dessus de 20 caractère il en veut pas. Je continus les tests.
