### ISSUE TITLE
Installation en mode commande

### ISSUE THREAD

**Issue by ceeeeb** [LordVenom/venom-xbmc-addons#427]
Bonjour,

Est ce qu'il es tpossible d'installer l'addon vstream en mode commande (ssh) sans passer par le menu Systeme ?

Merci

**Comment by TmpName** [comment]
Jamais teste, c'est plus ou moins possible, a confirmer mais si tu l'as deja installe une fois, oui c'est possible, il te suffit d'extraire un zip au bon endroit, mais lors de la premiere install Kodi fait des verifications que ne se feront pas si tu passes uniquement par ce systeme.
