### ISSUE TITLE
Résumé marques pages

### ISSUE THREAD

**Issue by fredo04** [LordVenom/venom-xbmc-addons#428]
Bonjour. Lorsque je mets un film dans marques pages et que je vais dans celui ci, le film est bien présent mais pas de résumé alors qu'il y était avant de le mettre en marques pages.

**Comment by TmpName** [comment]
C'est normal, le marque page ne recupere que le nom, le site, la fonction, et l'image.
Pour moi c'est normal, si je rajoute un film en marque page c'est pour pouvoir le voir plus tard, pas pour avoir son resume.

**Comment by fredo04** [comment]
Ok, merci.
