### ISSUE TITLE
Proxy et anonymat avec KODI

### ISSUE THREAD

**Issue by henri4ter** [LordVenom/venom-xbmc-addons#429]
Bonjour à tous.
J'utilise Kodi sous android  avec l'option proxy coché dans les paramètres internet.
J'utilise un proxy sock ssh qui peut tunneler tout le traffic internet et je pensais donc etre anonyme .
Cependant c'est loin d'etre le cas car en ne faisant pas tourner le serveur proxy voici ce qui se produit avec VSTREAM :
 Les sites de streaming sont accessibles et affichent le nom des derniers film ajoutés (mais on n'a pas l'image qui correspond) donc le site a notre véritable IP puis mon abonnement à 1fichier premium réussi donc la aussi notre IP est enregistrée. En revanche la visualisation du film en streaming est impossible tant que le serveur proxy n'est pas en marche.
J'ajoute que Simple IP TV fonctionne sans passé du tout par le proxy donc ceux qui ont récupéré des adresses iptv piratées ont leur IP enregistrée par ces sites qui diffusent canal plus illégalement.
Bref....il n'y a pas d'anonymat possible pour l'instant.
Ne serait-il pas possible de reprogrammer l'option proxy pour que tout le traffic puisse - etre tunneler via le proxy ?
Ou alors existet-il une apk qui pourrait obligé KODI a passé par un proxy (ca existe sous windows ).
Merci d'avoir eu la patience de me lire
Bonne soirée.

**Comment by TmpName** [comment]
Apres un rapide coup d'oeuil sur leur forum le proxy de kodi est un gag.
Vstream n'etant pas illegal, moi perso j'ai pas prevu de compliquer le systeme.
Pour toi la meilleure solution c'est de faire passer tout ton systeme par le proxy, pas juste un logiciel, comme ca tu es tranquilles.

**Comment by henri4ter** [comment]
Merci pour ta réponse TmpName.
J'ai pu vérifier que le proxy de KODI ne sert à rien.
Tu as raison c'est mieux de faire passer tout les flux réseaux par un proxy et j'ai trouvé PROXYDROID qui le fait très bien.
J'ai vérifier qu'on était complétement anonyme méme pour l'IPTV.
A noter que ZoneTéléchargement refuse la connexion quand on passe par un proxy.
Bonne continuation.
