### ISSUE TITLE
Quelques idées comme ça...

### ISSUE THREAD

**Issue by canopre** [LordVenom/venom-xbmc-addons#430]
Hello
Tout d'abord un grand merci pour la toute dernière release qui régle bien des problèmes.

J'ai 2 ou 3 petite idées que je vais vous soumettre pour la suite :)

Je ne sais pas si je dois ouvrir un post pour chacune alors pour l'instant je les groupe ici :

1 - Certaines sources demandent de choisir la qualité de la vidéo : Ca serait chouette de pouvoir le régler dans les options : En fonction de sa connexion ou de son périphérique, on pourrait régler par défaut : Min / Medium / Max.

2 - La nouvelle rubrique TV : C juste génial ! Mais peut-être que vous ne savez pas que les Raspberry ont bcp de mal à gérer les flux en .ts (dans ce cas il faut 3mn pour afficher la chaine) alors que le même flux renommé en .hls passe tout seul : Ca serait bien d'avoir le choix dans les options.
Au sujet de la TVIP : j'ai vu récemment un ancien post demandant un peu d'aide : Je suis dispo si on m'explique ce que je dois faire.

3 - Widget : Quand on utilise vStream pour afficher des vidéos en widget sur la page d'accueil : Ca serait bien de masquer la boite de dialogue avec la barre de progression : j'utilise bcp d'autres addon videos pour afficher des widget et je ne sais pas pourquoi : il n'y a que vstream qui affiche cette boite de progression et pendant ce temps on ne peut rien faire : Au minimum il faudrait qu'elle n'apparaisse qu'une fois et pas tous les 2 mn quand on navigue dans les menus.

Je me dis que j'ai peut-être un cache qui n'est pas activé car la liste des films sur les sources n'est pas mise à jour si souvent : Un cache de quelques heures serait certainement bien pratique.

Voilà, si y'a d'autres trucs qui me viennent je vous en ferais part et si j'ai dis une connerie ou que j'utilise mal vstream : toutes vos remarques sont les bienvenues :)

++

**Comment by TmpName** [comment]
1 - Moi suis pas pour, toi ca te demande juste un clic de plus, mais si on met ca par defaut, ca peut gener bien plus. Dans les serie, parfois je me perd, donc je lance au hazard en basse resolution, et quand j'ai retrouve ou je m'etais arrete je lance en meilleure resolution, a 3h du matin, si tu as une connexion de merde tu as plus de chance d'avoir du debit qu'a 20h, donc tu repasse par les parametres de Vstream 2 fois par jours, selon si c'est la nuit ou pas.

2 - Je savais pas du tout, mais je trouve bizarre que ce soit juste une histoire d'extension, tu es sur que c'est le meme format ?

3 - La y a une team widget qui traine dans le coin ^^, moi je les ai meme pas installe.

**Comment by canopre** [comment]
2 -  tu as raison : c'est pas exactement ca mais voici un exemple concret :

La même playlist contenant des sources en .ts

Si elle est chargée avec cette option : il faut 3 minute chrono pour que la source démarre :

http://xxxxxxxxx.net:8080/get.php?username=xxxxxxx&password=xxxxxx&type=m3u&output=mpegts

Mais si la playlist est appelée avec cette option :

http://xxxxxxxxx.net:8080/get.php?username=xxxxxxx&password=xxxxxx&type=m3u&output=hls

Ca démarre immédiatement.

Je ne sais pas pourquoi mais il y a des tonnes de discussions sur le sujet.

**Comment by TmpName** [comment]
Ha oui, pas bete, c'est toi qui demande le format au serveur directement, donc oui c'est facielment modifiable.

**Comment by LordVenom** [comment]
1 - Comme @TmpName je suis pas pour.

2 - Tu parle de Framapad en bêta avec un avenir plus qu' incertain pour le moment.

3 - Alors la boite de dialog c'est un choix oui ont peux faire autrement mais Kodi a des difficulté à stopper un script qui bloque, comme les sites sont parfoix modifier et que ça créer des bugs je préfère une fenêtre qui permet de stopper kodi.

**Comment by canopre** [comment]
2 - Si je peux aider à mettre à jour certaines sources : je suis dispo si on m'explique.

3 - Y aurait'il une solution pour mettre en cache la liste des films pour ne pas avoir à la recharger trop souvent ?

**Comment by LordVenom** [comment]
Si c'est de l'IPTV faut trouver des liens les tester et les copier dans framapad.
Pour le cache j'avais tester un truc sans succès je replongerais dedans un jour mais pas de suite.

**Comment by TmpName** [comment]
Pour le cache, il y a encore le code que j'avais commence pour libreTV dans le fichier en bas (qui sauvegarde les fichier m3u), jamais active car ca ne servait pas.

Mais c'est si long que ca pour lire la liste  ?

**Comment by canopre** [comment]
Pour TmpName :

Je pensais à un cache pour la liste des films : pas pour l'iptv : Quand on utilise vstream comme source de widget il y a trop souvent DialogProgress.xml qui vient par dessus pour mettre à jour la liste des films alors que ca a déjà été fait 2 mn plus tot.

Pour LordVenom :

Je veux bien essayer si tu as des sources fiables : personnellement j'ai jamais trouvé de lien gratuits qui fonctionnaient + de 48H.

**Comment by canopre** [comment]
Je crois bien que j'ai trouvé la solution pour les widget : en utilisant que la "recherche visuelle" pour faire des widget : il n'y a plus la fenetre de rafraichissement.

**Comment by LordVenom** [comment]
@canopre  Si j'en avais trouver il serais dans framapad :)

**Comment by canopre** [comment]
Pour TmpName :

Un système de cache des listes de films serait vraiment un + pour améliorer la rapidité de l'interface quand on utilise vstream pour faire des widget.

**Comment by TmpName** [comment]
@canopre tu parles aussi de la progressbar ?
Car normallement si je dis pas de connerie, le cache se fait tout seul via metahandler.

**Comment by canopre** [comment]
Surtout pour l'affichage des films dans les widget : si on utilise la "recherche visuelle" pour faire le widget  : il n'y a pas de progress bar : mais qu'est ce que c'est long à chaque fois pour afficher la liste alors que c la même que 5mn plus tot.

**Comment by TmpName** [comment]
C''est bizarre ca ? Bon je vais pas encore re installer les widget mais quand je teste directement dans Vstream, la premiere fois ca prend 2/3s mais si je quitte et si je reviens sur la meme page c'est instantane.
