### ISSUE TITLE
Je relance...problèmes des players

### ISSUE THREAD

**Issue by clyde005** [LordVenom/venom-xbmc-addons#431]
Bonjour,
Vu qu'on a fermer mon précedent post...je relance.
Je cherche toujours à savoir comment faire fonctionner les liens youwatch avec un lecteurs compatible.

Je rapelle que youwatch ne semble pas vouloir s'ouvrir avec le lecteur par défault E2player.
Par contre il s'ouvre bien avec le lecteur DVDplayer...mais sans son.
J'arrête de chercher pourquoi, mais j'aimerai savoir si on peut rajouter un lecteur VLC (ou autre) afin de faire fonctionner ces liens?
Merci!

**Comment by LordVenom** [comment]
J'ai fermer le post car a mon niveaux y a plus rien a faire dsl. Il faut demander a google je t'aide un peux quand même ça a voir avec le fichier playercorefactory.xml. Bon courage.

**Comment by clyde005** [comment]
Un petit peu plus?? ;-)

Concernant ce fichier playercorefactory.xml
Je t'en remercie!

**Comment by LordVenom** [comment]
Ben tu vas t'arracher les cheveux

http://media-passion.fr/support-windows/external-player-utiliser-le-playercorefactory-xml/

**Comment by clyde005** [comment]
Ha oui quand même, c'est pas rien.
Dis moi juste si tu crois que mon problème est plutôt Kodi, Vstream ou le système que j'utilise (enigma2)?

**Comment by LordVenom** [comment]
J'ai pas de soucis avec vstream et mon xtreamer. Je penche pour enigma2 mais pure déduction rien de concret.

**Comment by clyde005** [comment]
Bon je m'en fait une raison...tans pis!
Je te remercie pour tes explications...tu peux fermer ;-)

**Comment by clyde005** [comment]
Je constate que les liens "Exashare" s'ouvrent parfaitement donc je m'en contenterai largement!
