### ISSUE TITLE
Kepliz + Googlevideo

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#432]
Merci de verifier pour le host googlevideo ne s'affiche pas avec Kepliz (Grudal)

**Comment by mino60** [comment]
C'est corrigé : http://pastebin.com/NRqsCdHY
on attendant le retour de @TmpName pour la mettre sur bêta .

**Comment by mino60** [comment]
merci de bien vouloir ajouté : section film 2016 et films oscars 2016 sur frenchstream

MOVIE_OSC = (URL_MAIN + 'mots-clefs/oscars-2016/', 'showMovies')

    
    oOutputParameterHandler = cOutputParameterHandler()
    oOutputParameterHandler.addParameter('siteUrl', MOVIE_OSC[0])
    oGui.addDir(SITE_IDENTIFIER, MOVIE_OSC[1], 'FilmS OSCARS 2016', 'news.png',   oOutputParameterHandler)
    

    liste.append( ['2015',URL_MAIN + 'films-annees/2016/'] )

**Comment by TmpName** [comment]
Merci.
Jai fais la MAJ pour Frenchstrm, mais j'ai pas vu le prb dans Kepliz ni la modif sur ton fichier ?

**Comment by mino60** [comment]
Il y avait un problème sur la ligne 131 et j'ai modifier quelques lignes?? Mais maintenon il nya pa eu d'erreurs sur le script.

**Comment by TmpName** [comment]
Le site devait avoir un prb alors, le soucis c'est que du coup je vois pas comment ta modif repare mon code, et je peux plus tester vu que le site remarche

**Comment by mino60** [comment]
Je n'ai pas complété la liste maintenant c'est parfait merci de bien vouloir corrigé la liste

**Comment by TmpName** [comment]
M'en manque encore ?
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/frenchstream_org.py
