### ISSUE TITLE
Nowvideo

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#433]
Le host Nowvideo ne marche plus

**Comment by TmpName** [comment]
Par contre j'arrive pas a trouver un site qui fonctionne avec ?
A chaque fois j'ai le message "the video is being transfered", ou alors le site a vire les liens NV.

**Comment by mino60** [comment]
voila une modification sur le hoster: Nowvideo 

http://pastebin.com/W4H6Q66M

nowvideo.ch /.eu/sx et en pagne mais si en les remplaces par co ça fonctionne et tu peut lire les films

**Comment by arzaz** [comment]
Meme problème avec la modification --> Erreur fichier introuvable

**Comment by mino60** [comment]
effectivement que ça marche pas " fichier introuvable" mais on réalité il éxiste il faut juste de chercher un moyen pour édité le lien de streaming et changé "ch" par "co" c'est alors seulement  qu'on peut voir les videos.

**Comment by TmpName** [comment]
Meme en *.co ca deconne chez moi
>h ttp://ww w.nowvideo.co/video/6a70dcb875c92

**Comment by mino60** [comment]
ça marche avec moi sur libertyland titre de film : Usual Suspects streaming j'ai mème vue ce film sur nowvideo!...

**Comment by TmpName** [comment]
Pareil marche pas chez moi > video is being transfered.

**Comment by TmpName** [comment]
Edit MAJ, marche pour toutes les extension de 2 lettres maintenant, merci.

**Comment by arzaz** [comment]
Le problème persiste avec l'erreur --> Echec de lecture

**Comment by TmpName** [comment]
Je viens de retester, c'est aleatoire, mais ca fonctionne.
Leur site doit avoir un prb, meme en passant par le navigateur a certains moments me faut 7/8 essais (avec les pubs qui vont avec) pr que ca demarre.

**Comment by TmpName** [comment]
Tjours des prbs avec ce host ?

**Comment by mino60** [comment]
Le  host fonctionne chez moi ( avec urlresolver) mais j'ai toujour ce message et quand je clic sur annuler la video se bloc ?
![sans titre](https://cloud.githubusercontent.com/assets/11494048/16715788/3e3d6ccc-46ea-11e6-9cd0-8e4342f9be52.png)

**Comment by LordVenom** [comment]
J'ai aucun bug moi avec le host de vstream ou urlresolver.

**Comment by TmpName** [comment]
Et sans urlresolver ?
Normallement c'est ta modif que j'ai mis en place, si ca marchait au 3 eme post pour toi, ca devrait marcher maintenant encore.
Mais le hoster est capricieux n'hesite a faire 4 /5 essais.

**Comment by mino60** [comment]
marche toujour chez moi avec ou son urlresolver..

**Comment by TmpName** [comment]
Je parlais de ton dernier bug, la fenetre qui apparait.
Tu l'as avec et sans urlresolver ?
