### ISSUE TITLE
Live tv

### ISSUE THREAD

**Issue by Alexuu** [LordVenom/venom-xbmc-addons#435]
Bonjour à vous,

Merci pour votre travail ça sauvé des vie lorsqu'on vie à l'étranger :)

J'ai 2 questions. 
Live tv : Je voudrais savoir si la bêta de la live tv sera amélioré bientôt. La qualité de l'image est parfaite mais toutes chaînes freeze toutes les 20 sec et il est plus possible de relancer une autre chaîne une fois qu'une chaîne freeze.

**Comment by Alexuu** [comment]
Serait-il possible d'avoir une catégorie "Film Français" pour les films et séries. Il est souvent long pour naviguer dans les sélections de films et trouver un film français. 

Merci 

Alexandre

**Comment by LordVenom** [comment]
Bonjour,

- Tu parle de Framapad toujours en bêta je compte plus sur les utilisateurs que le faire nous même.
- Tu arrive pas a trouver un film français ??? y a pas que ça dans vStream, pour les séries y a une section VF (Version Française).

**Comment by Alexuu** [comment]
Bonjour et merci pour votre réponse.
- je parle de la tv en Live, elle frezze, ferme et reouvre la page environ toutes les 20 secondes. Souvent après on ne peut plus la remettre en marche.-- désolé framapad je ne connais pas. 
- Dans la section "film" tous les films sont mélangés, est ce qu'on pourrait avoir une catégorie Français pour faciliter la recherche des films français. Ou il y aurait une sub catégorie genre/année/etc..  
Merci pour votre travail et aide. 
Alexandre 
Get Outlook for iOS

		_____________________________

**Comment by LordVenom** [comment]
Pour avoir une organization passe par la recherche visuelle tu cherche parmis une liste de film par genre nouveauter ect.. puis l'addon te permettra de recherche sur toute les sources de vstream.

**Comment by Alexuu** [comment]
Concernant le Live tv, est ce qu'il y aura des améliorations concernant l'instabilité ?

Get Outlook for iOS




On Mon, Jul 11, 2016 at 1:43 PM +0400, "Lord Venom" <notifications@github.com> wrote:












Pour avoir une organization passe par la recherche visuelle tu cherche parmis une liste de film par genre nouveauter ect.. puis l'addon te permettra de recherche sur toute les sources de vstream.

**Comment by TmpName** [comment]
Au lieu d'aller dans framapad tu peux aller dans le lien de dessous "TV du web", ces liens la sont plus officiels et plus stables.

Pour framapad un user a trouve une solution, mais j'ai pas pu tester, moi j'ai meme pas droit aux 20s ....

**Comment by mino60** [comment]
Il veux dire film d'origine français c'est pour ça je veut crée une nouvelle source topimdb pour les films top pour la langue française : 

h ttp://www.imdb.com/search/title?title_type=feature,tv_movie&num_votes=100,&production_status=released&languages=fr%257c1&sort=moviemeter,asc&count=40&start=1

**Comment by TmpName** [comment]
Haa !
Effectivement de memoire j'ai jamais vu un site (a pars celui de mino60) qui propose un filtre made in Fr.

**Comment by Alexuu** [comment]
Merci beaucoup pour vos efforts. 
Alexandre 

Get Outlook for iOS




On Tue, Jul 12, 2016 at 9:21 PM +0400, "TmpName" <notifications@github.com> wrote:












Haa !

Effectivement de memoire j'ai jamais vu un site (a pars celui de mino60) qui propose un filtre made in Fr.

**Comment by Xarros** [comment]
Bonjour,
Tout d'abord un TRES GRAND MERCI pour tout votre travail!
C'est vrai qu'une section pour classer les films par origine serait vraiment géniale!

Bon courage!

**Comment by TmpName** [comment]
La, j'ai un peu decroche, donc je ne sais pas ou en est le projet de mino60, mais en attendant certaines sources proposent le classement par nationnalitée.
