### ISSUE TITLE
urlresolver et Zone-telechargement

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#437]
Salut...est ce que avec urlresolver on peut voir les films premium son limite de temps grace aux multi debrideur de urlresolver? ?
si c'est oui alors on a pas besoin d'un compte premium uptobox?!!...

**Comment by sebi0606** [comment]
Oui si tu as un compte real debrid tu peu. Tout voir sans aucunes limites de temps 
Et non du coup pas besoin d'un compte premium uptobox

**Comment by spcxsat** [comment]
Yes ca fonctionne bien 

J'en es un chez https://real-debrid.com
J'es aussi un Uptobox mais franchement avec real-debrid ca fonctionne mieux.

**Comment by TmpName** [comment]
Real debrid marche mieux que Uptobox ?

**Comment by sebi0606** [comment]
Oui @TmpName je confirme les dures de @spcxsat ça marche mieux ne me demande pas pourquoi je ne sais pas du tout mais le meme fichier avec un compte premium uptobox lag par moment chez moi avec ma connection mais pas en passant par urlresolver avec compte real debrid

**Comment by TmpName** [comment]
C'est bon a savoir aussi, mais je ne comprend pas pkoi ? C'est anti commercial a crever pour eux a crever ca.

**Comment by chataigne73** [comment]
moi j'ai un premium uptobox et ça marche  tout le temps nickel (au max de ma bande passante)

**Comment by spcxsat** [comment]
Oui je dit pas que ca fonctionne pas.
Mais parfois certain lien ne fonctionne pas avec uptobox et comme ca permet d'aller sur les autres.
Donc pour moi un seule abo pour tous

**Comment by chataigne73** [comment]
en effet, real-debrid est super bien pour s'affranchir du choix des hosters ...  par contre je trouve ça trop cher

**Comment by TmpName** [comment]
Pareil (bon j'ai aucun compte premium mais bon ....), franchement uptobox est toujours present dans la liste de hoster, et ca m'etonnerait que tu tombes souvent sur des liens morts, et pour 10 euros par an, il y a vraiment pas photo.

**Comment by spcxsat** [comment]
Oui je confirme sais très très rare que les lien sont HS.
Et l'avantage sais que quand on a pas beaucoup de débit avec uptobox sais que l'on peu changer pour passé en streaming et non en direct.
Moi j'ai pris Real debrid pour tester, car j'avais déjà un compte uptobox.
Sais juste que je pensais que urlresolver allais gère les capchat sans les taper, ce qui n'es pas le cas.
