### ISSUE TITLE
Script pour contourné les limites de temps des sites de streaming 

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#438]
Est ce que on peut crée un script "sh" auto-exécutable programmer sous windows a chaque 120 mn

exécuter: 
 cmd/..
ipconfig/release
ipconfig/renew (nouvelle ip)

et cela afin de desactiver la limite du temps de 120 mn uptobox sur Zone-telechargement ??..

**Comment by TmpName** [comment]
Plutot un script *.bat ?

Les shell script ne marchent pas par defaut sous windows, (dans kodi oui, mais c'est une autre histoire).
Mais c'est peu puissant, moi j'utilise des script autoit (il faut aussi installer une appli, mais c'est moins contraignant que d'utiliser des fichiers shell)

Mais ca marche ca comme methode ? je croyais que ca changeait juste ton ip locale ?
