### ISSUE TITLE
Problème unicode/accents

### ISSUE THREAD

**Issue by djeman** [LordVenom/venom-xbmc-addons#439]
Yip,

Ca fait un bout de temps que je ne suis pas passé mais votre plugin est toujours au top :)

Bon sinon je viens vous signaler un horrible bug introduit sur la dernière release concernant encore ces chemins de dossiers contenant accents et autre bizarreries que les français aiment bien mettre.
En fait il a une cédille dans son prénom et il a mis son prénom comme nom de profil windows ^^

Stop racontez ma vie, le bug c'est tout simplement un crash sur la fonction geticon de guielement.
Le chemin unicode du dossier n'aime pas qu'on ajoute la fin avec un +, ça le fait crasher le log reste vide et les liste de sites dans le soft aussi.

J'ai fait un fix comme j'ai pu en faisant ça => http://pastebin.com/aTMYujin
Tout semble bien fonctionner à première vue.

Voila voila je crois que tout est dit :)

**Comment by LordVenom** [comment]
Yop, 

Un rapport de bug avec la correction hoooooo je t'aime toi :), modification envoyer sur la bêta.
