### ISSUE TITLE
J'ai essayé de rajouter www.exdown.net

### ISSUE THREAD

**Issue by patoche2025** [LordVenom/venom-xbmc-addons#440]
Bonjour à tous,

Je viens vers vous car j'ai essayé de rajouter comme site ww w.exdown.net c'est un site comme zone-telechargement.com vous allez me dire pourquoi rajouter un site qui est similaire à zone tout simplement que je trouve qu'il peut être complémentaire à zone quand on trouve pas son bonheur. Bref,  j'ai pris le code zone-telechargement pour essayer de l'adpater pour le site exdow.net sauf que je suis pas programmeur et que quand j'ai fini bah ca n'a pas marché dans Vstream du coup je l'ai mis en lien sur pastebin si quelqu'un plus doué que moi pourrait corrigé les erreurs se serai gentil de votre part (comme @chataigne73 qui a fait celui de zone ou de quelqu'un d'autre of course)

D'avance Merci!!!! et vive Vstream lol

http://pastebin.com/18hHscfu

**Comment by TmpName** [comment]
Je l'ai stocke sur la beta pour les motives, pastebin efface les codes au bout d'une periode.
> https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/trash/exdown_com.py

**Comment by patoche2025** [comment]
Super un tout grand merci, j’espère que quelqu'un travaillera dessus car c'est un chouette site

**Comment by chataigne73** [comment]
j'hésite à m'y mettre, mais j'ai un doute que ce site comporte des films ou séries qui ne sont pas sur zone-telechargement
si tu me prouve que c'est le cas, pourquoi pas ;-)

**Comment by sebi0606** [comment]
Salut @chataigne73 hardcore Henry par exemple en vf et HD 1080p

**Comment by patoche2025** [comment]
Ou encore des séries des années 1980 (comme mission impossible, 20 ans après) et ou encore plus récent le film avec robert de niro Dirty Papy sur extreme donw il est en truefrench depuis des mois et sur zone encore la VFQ qu'est ce que tu en dis @chataigne73  :-)

**Comment by chataigne73** [comment]
malheureusement toutes les releases sont compressées avec winrar, donc pas possible de les streamer :-(

**Comment by patoche2025** [comment]
Salut @chataigne73 tout d'abord merci d'avoir pris le temps de regarder, dommage pour les releases mais bon on a zone c'est déjà bien :-)

**Comment by LordVenom** [comment]
Je sais que xbmc peux lire les .rar, les streamer je suis pas sur mais certain host sont déjà dans vStream et utiliser par ZT donc c'est possible a mon avis.

**Comment by TmpName** [comment]
Ha bon ? Xbmc peut lire les rar ? Ca doit dependre de beaucoup de chose alors, car justement quand on etait sur Vstream ca ne bloquait, ou alors y avait le son et pas l'image.
