### ISSUE TITLE
Problème Mangavost

### ISSUE THREAD

**Issue by domtom25** [LordVenom/venom-xbmc-addons#441]
j ai le souci les categories apparaissent mais ca me mais erreur quand j y rentre merci

longue vie a votre site et a votre travail

**Comment by TmpName** [comment]
Le site est out, a surveiller si c'est provisoire ou definitif.

**Comment by X-ardion** [comment]
Il faut peut être aussi retirer le lien qui apparait aussi quand on fait une recheche de films (derniers ajouts).

**Comment by TmpName** [comment]
Encore OUT.
https://github.com/LordVenom/venom-xbmc-addons-beta/issues/151
