### ISSUE TITLE
Film illimite

### ISSUE THREAD

**Issue by spcxsat** [LordVenom/venom-xbmc-addons#442]
Bonjour.

Film illimite ne fonctionne plus dans dernier ajouts.
Dans Qualité HD ou autres ca fonctionne, sûrement un problème du script.

Merci

**Comment by TmpName** [comment]
Mit a jour, par contre j'ai du virer la recherche alphabetique, car plus en place sur leur site.

**Comment by spcxsat** [comment]
Merci beaucoup
