### ISSUE TITLE
Impossible d'ouvrir framapad

### ISSUE THREAD

**Issue by Nevrdid** [LordVenom/venom-xbmc-addons#443]
Bonjour,
Framapad ne s'ouvre plus chez moi, j'ai tenté quelques trucs sans succès alors voila le log de l'erreur si quelqu'un a une idée :

18:18:57 T:8404   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\###\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 169, in <module>
                                                main()
                                              File "C:\Users\###\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 31, in __init__
                                                self.parseUrl()
                                              File "C:\Users\###\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 81, in parseUrl
                                                exec "plugin."+ sFunction +"()"
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\###\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\sites\freebox.py", line 110, in showWeb
                                                for track in playlist:
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:18:57 T:1616   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?function=showWeb&sFav=showWeb&site=freebox&siteUrl=https%3a%2f%2fannuel.framapad.org%2fp%2fvstream%2fexport%2ftxt&title=FramaPad%20(B%c3%aata)
18:18:57 T:1616   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?function=showWeb&sFav=showWeb&site=freebox&siteUrl=https%3a%2f%2fannuel.framapad.org%2fp%2fvstream%2fexport%2ftxt&title=FramaPad%20(B%c3%aata)) failed

**Comment by TmpName** [comment]
Je viens de faire 2 correction
1 sur le fichier frmapad, il doit toujours commencer par la ligne "#EXTM3U"

Et une autre pas importante, qui affiche un message d'erreur dans la liste au lieu de provoquer ton bug.

**Comment by henri4ter** [comment]
Bonsoir.
TmpName il y avait encore une erreur EXT,M3 U . J'ai corrigé . Est-ce une mauvaise frappe de ta part ou alors quequ'un s'amuse à saboter la liste ?
De toutes façons la liste est hors service depuis aujourd'hui.
J'essaye de corriger dans qques minutes

**Comment by henri4ter** [comment]
Quelqu'un a ajouté une nouvelle liste mais apparemment elle est déja HS.J'en ai ajouté une au dessus  qui est fonctionnelle pour l'instant. Ca explique qu'il y a maintenant des doublons.

**Comment by TmpName** [comment]
Yep c'est ce que je suis en train de verifier dans l'historique.
Y a eu un rattage, mais la ca tourne, enfin les liens que j'ai teste.
Mais faut dire que ca risque d'etre la guerre a surveiller vu que n'importe qui peut les modifier ^^.

**Comment by TmpName** [comment]
A voir de rajouter la balise #EXTREM: avec un commentaire du genre "mise a jour le XX/XX/XX merci d'attendre au moins 24h avant de le remodifier.

Mais faudra modifier le code avant Vstream ne gere pas ce tag.

**Comment by henri4ter** [comment]
Le problème c'est que certaine liste ne tiennent pas plus de qques heures ( parfois moins d'une heure car les revendeurs surveillent les liens publiques ou coupe quand on accéde avec plusieurs ip différentes et le mème pseudo.

**Comment by Nevrdid** [comment]
Un petit script auto qui fait un ping sur les liens et delete si besoin pourrait pas s'occuper de nettoyer regulierement ?

**Comment by TmpName** [comment]
Hein ? Si ca ne tient que quelques heures c'est pas la peine de prendre celles la, trop de boulot.
On va pas aller nettoyer la liste toutes les heures.

**Comment by Nevrdid** [comment]
Pour ca que je parle de script pour gérer ca automatiquement. Le problème comme dit henri c'est qu'il y a peu de liens iptv leakés qui durent longtemps et même s'ils ont les a en exclu grace a un utilisateur de vstream ils finiront surement par être inaccessible assez vite. La méthode communautaire le plus fiable selon moi est de faire rentrer un maximum de liens et de les filtrer régulièrement. Je n'ai jamais touché a un addon kodi donc je ne pourrait pas aider mais je verrais bien l'addon virer un lien de la liste si il est inaccessible. Et pourquoi pas le remplacer par un autre si il y a dans la liste plusieurs liens pour la même chaine.

**Comment by TmpName** [comment]
Oui mais si les liens ne durent que quelques heures, si ca ne servirait a rien.
A 10h tu as 20 liens , a 11h apres le filtrage plus que 2.
Nope le meilleure systeme c'est de trouver des listes plus viables
eg ht tp://opentostream.com/embed.php?vid=63045076e pr M6

**Comment by Nevrdid** [comment]
Il faut allors trouver 120 personnes ( si on veut un bon bouquet tv) ou une trentaine en se limitant a la tnt qui soit prêt a enregistrer non stop une chaine et ayant le matos nécessaire. Et c'est risqué pour eux. C'est pour ca qu'on trouve facilement les chaines populaire facilement mais pour les autres c'est plus difficile. Et certains abandonnent finalement. Ensuite il y a les fournisseurs de bouquets iptv qui filent des listes souvent leakés mais les entretiennent mais ont le control sur les accès.
Pour ton exemple, tu as trouvé m6 pour commencer mais bonne chance pour trouver la chaine science et vie par exemple.
