### ISSUE TITLE
Revenir en 0.4.2...

### ISSUE THREAD

**Issue by clyde005** [LordVenom/venom-xbmc-addons#444]
Bonjour,
Après la mise a jour automatique vers le 0.4.3 je ne peux plus ouvrir vstream.
Comment puis je revenir en arrière manuellement?
Ou alors si je réinstalle le 0.4.2 sur le 0.4.3 est ce que cela fonctionne?
Merci.

**Comment by TmpName** [comment]
Oui ca devrait marcher.
Si tu veux etre sur, tu efface carrement le repertoire "plugin.video.vstream" et tu extrais le zip dedans.
Mais si la V0.4.3 ne marche pas, il y a de forte chance que la V0.4.2 non plus. Il vaut mieux chercher pkoi elle ne marche pas, car de memoire il n'y a pas eu de modification pouvant empecher l'ouverture de Vstream dessus.

**Comment by clyde005** [comment]
Mission accomplie....
J'ai été dans les propriétés et refait "mise a jour".
J'ai relancé...et tout refonctionne!
Merci de ton aide.

**Comment by patoche2025** [comment]
Bonjour Comment faut-il faire pour que l'add-on vstream se met automatiquement à jour moi je le fais manuellement, désolé c'est sans doute une question idiote

**Comment by LordVenom** [comment]
Il faut installer le Repository

https://github.com/LordVenom/venom-xbmc-addons/releases/tag/Repository
