### ISSUE TITLE
FlashX

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons#445]
Flashx et out, tester sur la catégorie sport Tv-streaming.ch les liens flashx ne fonctionne pas mais sur le site pas de soucis.J'ai regarder vite fait un soucis de cookie peux être ?

**Comment by TmpName** [comment]
J'ai commence a faire une modif sur le beta.
Ca marche mais c'est tres lourd. Le prb c'est que a cause de spammer leur site, j'ai plus la page qui me demande de rafraichir ^^.
Donc me faut attendre.
