### ISSUE TITLE
Planet streaming

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#446]
Le site planet streaming est vide, merci de voir c'est quoi le probleme

**Comment by jojotango** [comment]
Dans le sPattern le ce n'est plus :
<code><strong>Version<\/strong></code> mais <code><strong>Qualité<\/strong></code>
Si je ne me trompe pas...

**Comment by TmpName** [comment]
C'etait bien ca merci. Pour info j'ai mis un \<strong>(?:Qualité|Version)\<\/strong> pour eviter les faux positifs, mais ca marchait aussi.

**Comment by arzaz** [comment]
Le problème a réapparu le site est vide

**Comment by TmpName** [comment]
Ha ?
Ca deconne encore ? Moi a cette heure ci pas de soucis, enfin du moins pr les films testes.

**Comment by arzaz** [comment]
Le site Planet streaming est vide

**Comment by arzaz** [comment]
Du nouveau svp?

**Comment by TmpName** [comment]
Ca y est ca deconne pr moi aussi, j y jette un oeuil.

**Comment by TmpName** [comment]
Mit a jour.
