### ISSUE TITLE
Film-streaming.co

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#449]
Le site film-streaming.co est vide

**Comment by TmpName** [comment]
Mit a jour, non teste.

**Comment by ballost** [comment]
Hello TmpName

juste pour info depuis MAJ sur mes 2 kodi hier la recherche de film se lance mais arrête rapidement
et en désactivant les sources une à une il s'avère que c'est celle de ce topic qui stoppe la recherche

après désactivation la recherche continue bine sur les autres sources

Cordialement

**Comment by TmpName** [comment]
Elle se bloque ?
Moi j'ai ce probleme sur hd-stream-in, mais ca se debloque au bout de 30s.

**Comment by TmpName** [comment]
?? Bizarre en plus quand une source deconne elle est ignorée, donc ca ne bloque pas, mais on a deja eu ce probleme, me faut retrouver l'issue.

**Comment by ballost** [comment]
hello en effet pas le même soucis

pour info suite nouvel essai je confirme que avec la source Film-streaming.co, la recherche s'arrete et n'affiche que trois sources et sans la recherche affiche toutes les sources
(pc sous W10 Kodi 16.0 et même phenomene sous android TV Kodi 16.1)

Par contre apparement sur le pc suis en Vstream 0.3.9 et même en changeant la date du pc pour forcer la mise a jour aucune mise a jour proposée

et sur TV suis en vstream 0.4.2 (ou 0.4.3 suis plus sur)

**Comment by ballost** [comment]
RE

petit up : mise a jour en 0.4.4 en manuel sur PC et réactivation source Film-streaming.co 👍 recherche OK
par contre en effet elle bloque un peu sur hd-stream-in puis continue

cdlt

**Comment by TmpName** [comment]
Alors une petite info sur les MAJ.
Il faut installer le repo de Vstream, pas Vstream lui meme, de cette meniere il se mettra a jour tout seul.
Une fois par moi LordVenom fait une MAJ du coeur de Vstream.
Les sites changent regulierement donc on a la possibilite de mettre a jour uniquement ces fichiers, tout les 4 jours Vstream verifie ces fichiers et uniquement ceux la, le probleme c'est que si le coeur de Vstream n'est pas a jour, V0.4.4 actuellement, meme si il met a jour les fichiers sites, ca risque de deconner car il va manquer des fonctions dans le coeur.

**Comment by ballost** [comment]
Hello

Ah ok merci je comprend mais comme j'avais les MAJ , je pensai que tout ce mettait à jour
je vais installer le Zip du repo

Merci encore pour ces précisions et pour le taf

Cordialement
