### ISSUE TITLE
Openelec 5 sur Pi B+

### ISSUE THREAD

**Issue by fawado** [LordVenom/venom-xbmc-addons#45]
Bonjour,
Tout d'abord félicitation pour ce plugin, qui est juste, ce qui m'a fait basculer sur Kodi, et m'acheter ma petite installation a base de raspberry.... Je l'avais testé sur Windows et ca fonctionne nikel, donc j'ai acheté un raspberry et j'en viens a mon probleme.
un raspberry PI B+ j'y ai installé OpenElec 5.0 donc avec Kodi, et au moment d'ajouter le fichier zip il me marque "structure de l'extension incorrecte", j'ai essayé le repository, et le dernier plugin 0.2.6 et ca me fait la meme chose "structure de l'extension incorrecte".
Si tu as une piste, je prend volontier...

Un grand Merci, encore pour ce plugin.
Steph

**Comment by fawado** [comment]
Je me répond a moi-meme, je telechargais a travers le reseau ca lui plaisait pas, donc j'ai mis le fichier repository sur mon raspberry et ca marche donc désolé pour cet issue qui sert a rien.
Encore felicitation

**Comment by LordVenom** [comment]
Bonjour, tu télécharger à travers le réseaux ? pour installer le repository oui il faut télécharger le fichier sur son disque dur.Si ça bug toujours y a toujours la solution de dézipper le repo direct dans le dossier addon d'Xbmc, Kodi.

Content que ça fonctionne maintenant et merci pour les encouragements, bon film :)
