### ISSUE TITLE
Vstream : Erreur connection 

### ISSUE THREAD

**Issue by merlin19744** [LordVenom/venom-xbmc-addons#450]
Bonsoir j'ai télécharger le zip vstream 0.4.3 sur ma recalbox et lorsque je fais une recherche il y a marqué "vstream erreur connection impossible" pourriez vous m'aider à résoudre ce petit soucis s'il vous plait  ? 

Merci de votre aide

**Comment by LordVenom** [comment]
Il a marquer ça et puis il et passait au site suivant? c'est juste qu'un site de la liste est HS.

**Comment by merlin19744** [comment]
Bonjour,oui après ça fonctionne,comment savoir quelle site ne fonctionne pas ?
Merci de ton aide

**Comment by TmpName** [comment]
En regardant les logs, mais le site peut etre HS juste pour quelques heures, si ca se trouve demain il refonctionnera.
