### ISSUE TITLE
openload HS

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/venom-xbmc-addons#451]
tester avec film/films HD / filmillimite : fichier introuvable sur le site ça fonctionne.

**Comment by TmpName** [comment]
Ok j'ai finalement trouve le code en question, demain je le convertis en python.

**Comment by TmpName** [comment]
Bon ca est, j'ai commence a mettre en ligne, il faut 2 fichiers, openload et png.py, je n'ai pas encore pu tester, soit le site est out, soit il me bloque.

Mais je recupere le lien, pour le moment.

**Comment by TmpName** [comment]
Ca y est, en exclu le dernier resolver pr openload.
Il marche mais a optimiser encore.

**Comment by LordVenom** [comment]
Je confirme ça tourne, encore un travail titanesque de notre @TmpName  national :)

**Comment by kenbest69** [comment]
Sa ne fonctionnait pas non plus sur le serveur mega-stream alors que sur le site tout fonctionne parfaitement. 
Je ne sais pas si ce resolver résous le problème ou pas.
Je ne m'y connais pas assez pour me lancer dans l'aventure ^^

**Comment by TmpName** [comment]
Je viens de le mettre an MAJ auto, dans max 4 jours tu l'auras fonctionnel chez toi.
Teste sur mege-stream, ca remarche.

J'attend leur future MAJ pour corriger le code, il m'a pris assez de temps, et la je passe a autre chose.

**Comment by kenbest69** [comment]
Ok, Merci vous êtes vraiment super et longue vie à Vstream

**Comment by BernardJeremy** [comment]
Hello ! 
@TmpName , tu serais en mesure de me dire comment Openload fait de son coté pour parser ce PNG ? Je suis sur un projet perso (en NodeJS en l'occurrence, pas en python ^^) et j'aimerai bien récupérer leur code JS qu'ils utilisent pour ça... mais impossible de le trouver malgré trois bonne heures de recherche !

**Comment by TmpName** [comment]
Leur code decode donne
  var parsed = document.getElementById("linkimg");
  var buff = document.getElementById("canvas").getContext("2d");
  /** @type {Array} */
  var subscribers = [];
  /** @type {Array} */
  var _0x456cx4 = [];
  $(document).ready(function() {
    buff.drawImage(parsed, 0, 0);
    var subscriptions = [].map.call(buff["getImageData"(0, 0, parsed["width"], parsed["height"]).data, function(deepDataAndEvents) {
      return String.fromCharCode(deepDataAndEvents);

linkimg etant une image au format png code en base64 "data:image/png;base64"
Apres j'y connais rien en javascript, donc j'ai pu me louper sur la syntaxe, je decode ca a coup de copier coller.

Le code se trouve dans le fichier final.js

**Comment by BernardJeremy** [comment]
Merci beaucoup pour cette réponse, avec même la version décodé, c'est vraiment cool !
Ta syntaxe est quasi-nickel, pas de souci.

**Comment by johngf** [comment]
de nouveau h.s
