### ISSUE TITLE
Uploaded

### ISSUE THREAD

**Issue by kenbest69** [LordVenom/venom-xbmc-addons#453]
Bonjour, je suis en mode premium chez uploaded et j'ai rentrer mes identifiants dans les paramètres. 
Mais à chaque fois que je lance un lien uploaded (exemple : dans le serveur zone telechargement) sa me marque en premier "décodage en cours" ensuite je clique sur le lien et la "premium mode : authentification réussie" mais rien ne se lance et une boite de dialogue s'ouvre avec le titre "Échec de lecture"
Peut importe le fichier sa me met la même chose à chaque fois.

**Comment by TmpName** [comment]
La je ne pas t'aider, ce site ne marche que avec premium.
Tu as teste en activant l'urlResolver ? Dis nous si le leur fonctionne.
Tu as quelque chose de special dans les logs ?
Les hebergeurs proposent parfois une option qui permet le telechargement direct ou une page affichant le lien a cliquer, selon ton choix le resultat est different.

**Comment by kenbest69** [comment]
Alors je viens de tester en activant l'urlResolver et toujours pareil.
Je regarde au log ce soir et met se post a jour pour vous dire quoi.
Cette hébergeur ne propose ni de telechargement ni de lien comme uptobox.

**Comment by TmpName** [comment]
Dans le log normallement si tu vas a la fin (tu peux te reperer avec l'heure) tu devrais reconnaitre a quel moment il essayes de se connecter, tu vas pouvoir y lire le lien uploaded, les messages de vstream ect ..

Il y a de forte chance qu'il n'y ait rien de special, mais je pourrais te faire une version speciale du fichier avec plus d'infos pour nous aider.

Surtout que je ne pense pas que le createur du fichier repasse si vite ....
