### ISSUE TITLE
'Streaming-series.xyz' enlever un click ?

### ISSUE THREAD

**Issue by jojotango** [LordVenom/venom-xbmc-addons#454]
Bonjour, 
Serait il possible dans la source 'Streaming-series.xyz'
de lancer directement la vidéo après le décodage?
Ça permettrai d'enlever un click.

**Comment by TmpName** [comment]
Lol, decidement, c'est bien ca fait depenser des calories en plus.

Sinon, pour la reponse je sais pas. Dans kodi il y a 2 sorte de contenus, ceux qu'on peut lire et ceux que l'on ne peut pas.
Avant le decodage on ne connais pas le host, donc on affiche en mode non "playable". Puis le lien est decode et on l'affiche dans le mode "playable".

En fait, c'est realisable mais du coup on ne passe plus du tout par le systeme de hoster de Vstream, tu ne verras meme plus l'hebergeur, il est affiche avant mais c'est l'info du site, si il decide d'appeller ca "pompe a velo" c'est ce que tu liras, rien a voir avec la seconde page ou les infos dependent du lien.
Plus moyen non plus de passer par UrlResolver (vu que c'est la partie hoster de vstream qui gere ca.
Plus de menu hoster, (telechargement, mise en librairie, ect ....) car ce menu n'appparait que sur le lien final.
Juste pour pouvoir poser la telecommande 5s plus tot.

J'avoue ca fait une etape en plus qui sert a rien, mais je vois pas comment la supprimer, sans poser encore plus de problemes.

Si quelqu'un a une solution ...

**Comment by jojotango** [comment]
Lol, non pas de soucis si ce n'est pas faisable avant de mettre ce post j'ai essayé des trucs bizarres en cherchant dans la librairie xbmc, sans succès.
Du genre:

if (oHoster != False):
    xbmc.Player().play(sHosterUrl)

Bonne continuation.

**Comment by TmpName** [comment]
Tu es tombe en plein dessus ^^.
En fait la librairie oHoster, est LA librairie qui gere les liens finaux, et elle fait tout du debut a la fin, donc on ne peut pas l'utiliser juste a moitie. Soit on passe entierement par elle, soit on ne l'utilise pas du tout.
