### ISSUE TITLE
compte UPTOBOX

### ISSUE THREAD

**Issue by huitcentsix** [LordVenom/venom-xbmc-addons#455]
Salut à tous, alors voilà, c'est peut être anodin pour vous mais je suis novice et tourne sur un Ras pi3 / XBMC / LibreELEC / Vstream (dernières versions pour tout). Tout fonctionne à merveille et voici ma question, après acharnement sur google sans réponses...

Comment fait-on pour entrer son compte UPTOBOX pour ne plus avoir les contraintes de limitation alors que je paye un compte ! Faut il un addon via kodi ? ou dans les setting ? (pas trouvé) .. Bref je ne comprends pas grand chose c'est sûr et je m'en excuse. Je veux juste utiliser mon compte et profiter de mon pi3 / Vstream / zone telechargement sans limites (comme sur pc) :)

Merci (si c'est possible)

**Comment by TmpName** [comment]
2 possibilitées.
Dans les parametres de kodi, onglet "premium/login".
Soit tu le configure ici juste pour Vstream, et ca suffira.
Soit tu le configures dans urlresolver en l'activant, la ca marchera pour tous les addons utilisant urlResolver, si tu n'as que Vstream, la premiere solution est plus simple.

**Comment by huitcentsix** [comment]
Merci pour ta réponses, j'avoue être... mauvais ?
 
J'ai pourtant cherché partout dans les paramètres de kodi l'onglet premium/login en vain.. J'ai l'apparence "confluence" de base...(interface en français) à moins que ça soit ailleurs je ne trouve pas d'onglet ou d'endroit pour "login/premium". J'ai l'impression d'être nul :(  
(c'est plus qu'une impression..)

J'avais déjà mis URLresolver avec la config qu'on peut trouver partout sur internet (propriété à 90 etc) mais ça ne marche pas non plus... Sur mon ordi (j'ai un compte) je dois sélectionner les liens pour les débrider.. sur le KODI PI3 bin je ne sais pas comment ça marche. Je pensais que c'était automatique. Tout est activé dans urlresolver pourtant, même uptobox :'( 

En tout cas Vstream est vraiment énorme !

**Comment by TmpName** [comment]
C'est normal ^^, ce n'est pas dans les parametres de kodi, mais les parametres de vstream.
Lances Vstream et quand tu es sur la page d'acceuil de Vstream appuis sur "C".
Tu peux te passer de l'urlResolver si tu galeres avec.

**Comment by huitcentsix** [comment]
...

**Comment by huitcentsix** [comment]
hahaha enfait (je rigole comme un con) j'utilisais QUE la souris et je viens de me rendre compte qu'on pouvait faire défiler les onglets avec le clavier... je pensais que ça s'arrêté à "plugins on/off (3/3)  ... ^^

(du coup je suis curieux de savoir comment fonctionne urlresolver :/ )  

Merci beaucoup !! (honteux)

**Comment by huitcentsix** [comment]
Rectification, tout marche bien navette. Du coup j'ai vu l'option Urlresolver dans les parametres de vstream !!! c'est nickel, pour une fois que tout fonctionne :) 

Encore merci pour tout ^^

**Comment by TmpName** [comment]
Mais honnettement pour ton usage, j'eviterais urlresolver et passerais juste par les options de Vstream (mot de passe/ user / et cliquer sur activer)
C'est moins lourd, et gere a 100% par Vstream, urlresolver est une usine et ce n'est pas nous qui la mettons a jour.

**Comment by huitcentsix** [comment]
oui merci ! pour l'instant je testouille un peu puis je verrais l'evolution de mon utilisation :) 
Mais je penses rester sur un simple abonnement uptobox
