### ISSUE TITLE
9docu vide

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#456]
Bonjour à tous 
@TmpName la source 9docu est vide ils ont dû changer un truc si tu peux voir merci d'avance

**Comment by jojotango** [comment]
@TmpName j'ai modifié  "__checkForNextPage et showMovie" je pense que tu peux raccourcir le pattern dans "showMovie".
Autrement tout mes testes sont fonctionnels.
http://pastebin.com/mJXMCNxw

**Comment by TmpName** [comment]
Lol, put1, j'ai du passer juste 10mn avant que tu postes ca, du coup j'ai commence pr rien, ton code fonctionne tres bien, merci, moi j'avais vire le resume par flemme, du coup je recupere ton regex.
Je l'ai un peu modifie mais c'est juste parce que je suis maniaque, ton code tourne tres bien.

Je mets en ligne tes modifs dans 2 mn, beta et off.

Tu as l'acces direct a la beta pour les modifs ?

**Comment by sebi0606** [comment]
Merci les gars ^^

**Comment by jojotango** [comment]
À mince désolé, nan je ne pense pas avoir accès à la bêta.
Après mes connaissances sont limitées en programmation donc il faut que quelqu'un vérifie après.

**Comment by TmpName** [comment]
Aucun danger, la beta est la pour ca. Ca n'aura aucune incidence sur la version que possede les autres.

**Comment by jojotango** [comment]
Ha Ok cool ben je veux bien un accès alors

**Comment by TmpName** [comment]
Par contre, soit suis trop con pour trouver comment faire, soit il n'y a que LordVenom pour pouvoir te filer les acces.
Suffit d'attendre son passage.
Mais franchement, la beta est la pour se lacher, en plus il y en a qui la teste regulierement, c'est pratique pour valider des modifs, beacoup plus simple que pastebin.
Et LordVenom fait generallement une verif d'ensemble avant de valider les fichiers en version off.

**Comment by LordVenom** [comment]
C'est fait :)

**Comment by jojotango** [comment]
Super merci!
