### ISSUE TITLE
Manga City

### ISSUE THREAD

**Issue by stormz85** [LordVenom/venom-xbmc-addons#459]
Hello LordVenom tu va bien ?

Petite question que je ne comprends pas, quand je vais sur le site Manga City sur mon PC je trouve que je désire pour mon petit

http://www.mangacity.co/watch.php?stream=dA0y2mpGVpQB2xY4H2vx2831PLWhoztVcMmqyK
Paw Patrol

sur Vstream j'ai également le MangaCity mais impossible de trouver le même dessin animé normal ? 

Merci d'avance pour ta réponse.

**Comment by TmpName** [comment]
Effectivement il y a plein de prbs sur ce titre.
Donnes moi un peu de temps, je corrige ca.

**Comment by stormz85** [comment]
aucun soucis !! j'attends sa ;) merci beaucoup pour ton taff !

**Comment by TmpName** [comment]
C'est bon mit a jour.
Pour forcer la MAJ avance la date de ton ordi de 4 jours avant de lancer Vstream.

**Comment by TmpName** [comment]
Petite correction pour les liens openload, now tout fonctionne.

**Comment by stormz85** [comment]
Merci les gars !!! <3

2016-08-11 7:15 GMT+02:00 TmpName <notifications@github.com>:
