### ISSUE TITLE
Fanart animées synopsis

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#460]
Salut à tous 
@TmpName pourrais tu voir si il y'a moyen notamment pour zone de telechargement quand on regarde un film en streaming d'avoir en utilisant un skin sur kodi qui permet d'avoir les fanarts animés c'est fameux fanart en gros de faire en sorte que le fichier est en local pour voir c'est fanart ou poster animés 
Merci d'avance

**Comment by TmpName** [comment]
Hurr ^^, alors la tu demandes pas a la bonne personne.
On m'a deja demande d'ameliorer l'integration dans les widgets, et la moi je n'ai ni widget, ni skin special, je ne sais ni comment ca marche, ni comment c'est mit en place.
Mon crenau c'est plutot le scrapping, l'ergonomie ....

**Comment by sebi0606** [comment]
En fait c'est du scrapping quand tu as un film sur le disque dur ca récupère le fanart animé mais quand c'est en streaming ca utilise l'affiche mis sur le site le but serait de faire croire que le fichier lu est en fait sur le disque dur. creer un dossier temporaire dans kodi pour que le scrapper récupére le fanart animé je sais pas si je m'explique assez bien ^^

**Comment by TmpName** [comment]
Mais c'est quoi comme animation ? C'est juste un montage fait a partir d'une image fixe ? ou il y a des sites qui proposent des fan art animes ?

**Comment by sebi0606** [comment]
Selon le skin utilisé sur kodi ça récupére avec des scrapers particulier 
Voilà un exemple pour les affiches
http://forum.kodi.tv/showthread.php?tid=215727

**Comment by TmpName** [comment]
Yep mais sur quel site sont recuperes ces fichiers ? Je n'ai jamais vu le scraper pour ces affiches.
D'apres les commentaires, ce n'est pas au point non plus comme systeme.

Et dans ton lien ce n'est pas une histoire de skin, c'est juste que l'image est un gif anime au lieu d'un jpeg. donc ca a toujours marche ce truc.

**Comment by sebi0606** [comment]
tu prend le skin aeon mq5 ça marche mais quand tu as ton film sur disque dur et ca utilise des scrapers à eux

**Comment by LordVenom** [comment]
Tu as vraiment une grosse machine et une bonne connexion pour faire tourner ça lol perso je peine a charger les images quand y a trop de lien sur vstream alors de l'animer même pas en reve.

**Comment by sebi0606** [comment]
J'ai une nvidia shield tv ^^
