### ISSUE TITLE
ZT - Non reconnu comme 'source'

### ISSUE THREAD

**Issue by mcallew** [LordVenom/venom-xbmc-addons#461]
Bonjour,

Serait-il possible que Zone-Telechargement soit considéré comme une source FILMS, SERIES, ... ? 
Actuellement il n’apparaît pas dans les sources de chaque catégorie mais uniquement par "voir toutes les sources".

Cordialement ! 

Mathieu

**Comment by TmpName** [comment]
Exact, il y a plein de serie ou il n'apparait pas, faudrait modifier par exmple SERIE_VF par SERIE_VFS.
Pour le motives, les mots cles exacts sont dans https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/lib/home.py a partir de la ligne 293

**Comment by mcallew** [comment]
Ok ! Ceci est-il lié au fait que si rajoute un marque-page sur une série dans ZT, il est ajouté à la catégorie 'films' ou je crée une autre issue ?

**Comment by mcallew** [comment]
Pull request créé pour régler cela 
https://github.com/LordVenom/venom-xbmc-addons/pull/462

**Comment by TmpName** [comment]
D'abord merci pour la correction ^^.
Sinon pour info, les modifs se font plutot sur la beta https://github.com/LordVenom/venom-xbmc-addons-beta
A cause des mise a jour auto.

Pour le prb de marque page, je recupere ta version et je corrige de suite, j'ai vu le prb.

**Comment by mcallew** [comment]
OK je note ça pour la suite :). Excellent boulot en tout cas

**Comment by TmpName** [comment]
En fait sur la premiere page on utilise addMisc() car cela peut etre aussi bien des film que des series.
Par contre sur la seconde page il y avait encore addMovie() au lieu de addTV().

Normallement le marque page va marcher pour les series, mais apres avoir clique sur l'affiche de la serie.

**Comment by mcallew** [comment]
Votre version bêta est l'équivalent d'une branche develop ?

**Comment by TmpName** [comment]
Je pense, en fait, toute les modifs se font la bas, et passent sur la version officielle apres les tests en debut de mois (sauf ugences comme site ou host HS)

**Comment by LordVenom** [comment]
Oui bêta nous et utile surtout pour tester des nouveaux code après chaque mois je fait un rapide controle des nouveaux fichier et j'effectue les changement dans le setting quelque test et je fournis une copie exacte de ce qui tourne sur mon ordi.

**Comment by mcallew** [comment]
Juste pour ma curiosité, quel est l'apport par rapport à une branche develop?

**Comment by TmpName** [comment]
Ben c'est beacoup plus simple a gerer.
Pour les acces, n'importe qui peut avoir un acces sur le beta, suffit de demander
Pour les fausses manips, on est sur a 100% que le github original ne sera pas impacte
Chaque github a ses propres issues.
Pour les manipulations de fichiers, ce n'est pas juste une copie ou fusion de fichier d'un github a l'autre, ils sont retouches (et surtout completes, la version beta est pr les bidouilleurs, eg: les modifs d'options se font a la dure en editant les fichiers par exemple) avant d'arriver sur la version off.
Si on voulait utiliser la fusion, il faudrait tout tester, le completer, updater la branche et fusionner, plus simple de tout mettre a jour avec la version du disque dur, surtout qu'une seule personne finalise tout a chaque fois.
Pour le debutant, certains users decouvrent github on va pas compliquer le smilblic juste pour modifier une adresse web qui a changée, et j'imagine meme pas en cas de conflit.
C'est invisible a l'user lamba qui vient sur le github officiel qui n'en as rien a foutre.
