### ISSUE TITLE
Seriefr.com

### ISSUE THREAD

**Issue by johngf** [LordVenom/venom-xbmc-addons#465]
Seriefr.com est down depuis plusieur semaines changement de nom de domaines ?

**Comment by TmpName** [comment]
Ben la je comprend pas, le site a l'air out, mais appparement un moteur l'aurait teste il y a 1h avec succes ...
On peut acceder au site pour voir une image
http://w ww.seriefr.com/images/series/the_walking_dead.jpg

Mais pas le site.
A surveiller, peut etre un blocage FAI.

**Comment by TmpName** [comment]
Toujours out a cette date.

**Comment by TmpName** [comment]
Toujours OUT
>https://github.com/LordVenom/venom-xbmc-addons-beta/issues/151
