### ISSUE TITLE
A propros du cache?

### ISSUE THREAD

**Issue by clyde005** [LordVenom/venom-xbmc-addons#466]
Bonjour,
Je reviens avec une question concenrnant le cache...
Je me rend compte qu'à force d'utilisation mon appareil se ralenti avec Vstream.
Pouvez vous me dire si l'on peux vider son cache et encore mieux me donner le chemin ou il le sauve?
Merci.

**Comment by mcallew** [comment]
Tu sais vider le cache dans les options du plugin. Pour le reste je laisse répondre qui saura :-)

**Comment by TmpName** [comment]
Yep, pour Vstream c'est dans les parametres de l'addon, pour kodi 
Pour kodi je crois que l'option dans video/mediatheque fonctionne sinon methode bourrin, dans  kodi/userdata/Sa‌​tabase/ supprimer tout les fichiers MyVideosXXX.db, mais c'est violent, tu risques de perdre des donnees.

**Comment by clyde005** [comment]
J'ai trouvé cela sur le net...fiable?
http://www.kodisimplified.com/how-do-i/clear-your-cache/

**Comment by TmpName** [comment]
Oui, celui la ou un autre, il  y a plein d'addons qui font ca, mais si tu le fais a la main ca marche aussi, et Vstream peut vider son cache tout seul, donc pour l'utilite de ce genre d'addon ...

**Comment by clyde005** [comment]
Super ça..mais peux-tu me dire comment faire pour que vstream vide son cache tous seul?
Merci!

**Comment by TmpName** [comment]
Me suis mal exprime ^^, je voulais dire que c'etait possible sans passer par kodi.
Dans les parametres de Vstream ya juste un boutton a cliquer pour vider le cache, mais normallement c'est assez rare d'en avoir besoin.

**Comment by clyde005** [comment]
Ok parfat merci pour vos réponses!
