### ISSUE TITLE
otakufr.com

### ISSUE THREAD

**Issue by johngf** [LordVenom/venom-xbmc-addons#467]
bonjour , il serait possible d'ajouter comme source anim otakufr.com?
j'ai essayé avec le fichier ajouter une source mais sans succès.

**Comment by TmpName** [comment]
Moi perso je ne rajoute plus de sources sans avoir un bon argument, eg episodes non trouvable ailleurs, qualitée HD, ect ..
A part qu'il utilise Youtube je n'y ai pas trouve beacoup d'interet.

Au pire, tu en es ou avec ton essais et le fichier ajouter_une_source ?

**Comment by johngf** [comment]
je n'arrive pas a recevoir la liste catalogue anime comme le fait la source adkami ou mangacity (je pense a cause sPattern).
en faite cette source dispose de plusieurs lien par episode souvent sur adkami et mangacity ce n'est plus le cas et diffuse les anim licensié

**Comment by TmpName** [comment]
Adkami, j avoue j'ai souvent des prbs avec.
Mangacity propose tjours 1 lien openload et 1 second lien.
Il y a aussi fullstream qui propose des animes, et libertyland (en panne me faut le reparer en premier).

Fais passer ton code non fonctionnel sur pastebin, que j y jette un oeuil.

**Comment by johngf** [comment]
pour l'instant j'ai juste essayé d'afficher la liste catalogue anime (j'ai mis des # sur les 2 modif movies news et spattern de showmovies) ca affiche la liste

http://pastebin.com/Bg1ZHWjc

**Comment by johngf** [comment]
pour l'instant j'ai juste essayé d'afficher la liste catalogue anime (j'ai mis des # sur les 2 modif movies news et spattern de showmovies) ca affiche la liste

http://pastebin.com/Bg1ZHWjc

**Comment by TmpName** [comment]
Je te l'ai continue.
Si tu vas dans nouveaute, tu as la liste des nouveautees.
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/trash/otakufr_com.py

**Comment by johngf** [comment]
merci. par contre je l'ai modifié pour afficher la 3e colonne de vidéo qui ne s'affiché pas et j'ai rajouté la function page suivante mais je n'arrive pas à avoir le nom et numero de l'épisode après le click sur un élément de la liste (probleme avec (seriesHosters() et spattern je pense)

http://pastebin.com/7YU0cb9v

**Comment by TmpName** [comment]
https://github.com/LordVenom/venom-xbmc-addons-beta/blob/master/plugin.video.vstream/resources/sites/trash/otakufr_com.py

**Comment by johngf** [comment]
merci bien je venait juste de reussir avec un morceau de code de akami mais ta version est meilleur

**Comment by johngf** [comment]
bonjour, je sèche avec un problème pour récupérer certaines thumbnail elle ne s'affiche pas dans kodi  à cause d'espace dans l'URL > (%20) une petite aide serait bienvenue .
<img src="(.+?)" >>fonctionne sur les urls sans espace.
ex: www.otakufr.com/wp-content/anime/cover/tbn/akagami no shirayuki-hime_250x0.jpg" >>fonctionne pas

**Comment by johngf** [comment]
bon apparemment ça fonctionne  avec Sthumb = re.sub('\s+', '%20', Sthumb)
mais si il y a un regex équivalent je suis preneur.

**Comment by TmpName** [comment]
Nope ton regex est bon. C'est juste que tu as besoin d'un traitement pr le lien.
Il y a une fonction python qui convertit tout les liens mais si tu as juste l'espace qui deconne il y a la fonction replace
string = string.replace(' ',%20')
moins lourd que les regex.

**Comment by johngf** [comment]
merci ça va m'être utile pour récupérer le synopsis aussi qui a le meme probleme d'espace

**Comment by TmpName** [comment]
Essaye >([^<]+)<
