### ISSUE TITLE
ajout de site 

### ISSUE THREAD

**Issue by sebi0606** [LordVenom/venom-xbmc-addons#468]
Salut à tous 
@TmpName pourrais tu voir ce site il est pas mal pour ceux ayant une faible bande passante notamment pour les series en hd h ttp://official-film-illimite.net/ 
Merci d'avance

**Comment by TmpName** [comment]
Il y est deja, il s'apelle 'Film illimite'

**Comment by sebi0606** [comment]
C'est parfait merci ;) et lol je suis blond des fois

**Comment by TmpName** [comment]
Lol, pas de soucis, ca commence a etre la jungle dans les sources.

**Comment by sebi0606** [comment]
Par contre pour cette source quand je vais dans serie pour film illimite il y'a les series sauf que quand je clique sur une serie aucuns liens dedans 
Si tu peux jeter un œil merci d'avance

**Comment by TmpName** [comment]
A cause d'un nouvel host, je viens de faire une MAJ, mais elle n'est que sur la beta, il faut modifier des fichiers non mit a jour automatiquement.

**Comment by sebi0606** [comment]
Merci @TmpName toujours aussi réactif
