### ISSUE TITLE
Can you help

### ISSUE THREAD

**Issue by emailradhesh** [LordVenom/venom-xbmc-addons#469]
Sorry for creating issue. I thought of contacting authors this way.

I want to watch some hqq.tv videos on Kodi available at topbestsite.com website.

I'm new to Python and got some idea from netu.py and reached until getting vkcache URL.

Can you help me to get the actual video URL assuming I have ht tp://hqq.tv/player/embed_player.php?vid=241246259258255264242222236227264240194271217261258&amp;autoplay=no URL.

**Comment by TmpName** [comment]
Take a look on the netu (we are calling it netu.py and not hqq.py) resolver we are using for this site.
All the code is free to use, but pls let credits.

**Comment by emailradhesh** [comment]
Thanks, I've been working on it. Let me share what I understand in a few days time.

**Comment by emailradhesh** [comment]
Hi,

I've extracted from netu.py and it looks like [hqq](https://github.com/emailradhesh/topbestsite/tree/master/hqq). I'm not getting idea on how to pass my URL. Also when function GetIP is used. Can you help me.

**Comment by emailradhesh** [comment]
Hi,

I added test.py to repos [hqq](https://github.com/emailradhesh/topbestsite/tree/master/hqq). Can you verify for me please.

**Comment by TmpName** [comment]
You don't need to make so complicated.
Parser.py is useless for you, you can just use re library.
50% of the hqq.py is useless too.

If you want to use all the Vstream core, it's easier for you making a new site file and use it into Vstream.

This is made for use in Vstream, you can just take the usefull fonctions and make a stand alone script.

**Comment by emailradhesh** [comment]
Thanks for the update. I'm debugging it. I've come until this stage. It will be of great help if you can guide/help me to know which are the functions necessary. Basically, in first stage I look forward to give input hqq url with ID and then get output exact video URL to play in VLC or Kodi.

As a big picture I would like to add topbestsite.com into Vstream. Before that, I've to learn and play with Python. Hence started with netu.py file.

**Comment by TmpName** [comment]
In the file hqq.py, the usefull fonctions are _decode _decode2 and the fonction __getMediaLinkForGuest, no more.
Optional one are __getIdFromUrl

**Comment by emailradhesh** [comment]
Thank you very much. It helped to get contents of playlist. Now need to figure out what is the prefix URL to each file fragment.

**Comment by emailradhesh** [comment]
May I ask help again. I got the contents of playlist or m3u8 file. It contains names of fragments. What is the URL to prefix for each fragment. Can you let me know. Sorry for the trouble. It's new learning for me.

**Comment by emailradhesh** [comment]
Oops I got the idea from commented line. Let me figure out next steps.

**Comment by emailradhesh** [comment]
I thank you for all the help you gave. May I close and comment.
