### ISSUE TITLE
problème recherche (accent?)

### ISSUE THREAD

**Issue by hadesjack** [LordVenom/venom-xbmc-addons#47]
Bonjour
je n'ai pu faire de recher car ca plante, je me demande si ca viens pas de l'accent dans le nom de l'utilisateur car ca fonctionne très bien sur un autre PC.

l'utilisateur est Céline.

Je vous enverrais un autre log plus tard car chaque tnetative de source provenant de youwatch a finni en erreur

21:56:03 T:5112  NOTICE: Thread LanguageInvoker start, auto delete: false
21:56:04 T:6936  NOTICE: PVRManager - starting up
21:56:04 T:5924  NOTICE: -->Python Interpreter Initialized<--
21:56:04 T:4068  NOTICE: Thread PVRManager start, auto delete: false
21:56:04 T:6368  NOTICE: Running the application...
21:56:04 T:4960  NOTICE: Thread PVRClient start, auto delete: false
21:56:04 T:6368  NOTICE: ES: Starting event server
21:56:04 T:3084  NOTICE: Thread EventServer start, auto delete: false
21:56:04 T:7104  NOTICE: Thread TCPServer start, auto delete: false
21:56:04 T:1096  NOTICE: Thread RSSReader start, auto delete: false
21:56:04 T:3084  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
21:56:04 T:7140  NOTICE: -->Python Interpreter Initialized<--
21:56:04 T:3084  NOTICE: UDP: Listening on port 9777
21:56:04 T:3088  NOTICE: -->Python Interpreter Initialized<--
21:56:04 T:5992  NOTICE: Previous line repeats 2 times.
21:56:04 T:5992  NOTICE: AxelProxy Downloader Starting - 127.0.0.1:45550
21:56:04 T:7472  NOTICE: Thread FileCache start, auto delete: false
21:56:04 T:5992  NOTICE: Press CTL break to stop.....
21:56:04 T:3088  NOTICE: 1Channel: Service: Installed Version: 2.5.55
21:56:04 T:4960  NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 100 channels.
21:56:05 T:3088  NOTICE: 1Channel: Loading sqlite3 as DB engine
21:56:05 T:6392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named StorageServer
                                            Traceback (most recent call last):
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\script.common.plugin.cache\default.py", line 40, in <module>
                                                run()
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\script.common.plugin.cache\default.py", line 31, in run
                                                import StorageServer
                                            ImportError: No module named StorageServer
                                            -->End of Python script error report<--
21:56:05 T:4388  NOTICE: Thread LanguageInvoker start, auto delete: false
21:56:05 T:4388  NOTICE: -->Python Interpreter Initialized<--
21:56:05 T:3088  NOTICE: 1Channel: Service: Resetting...
21:56:05 T:3088  NOTICE: 1Channel: Service: starting...
21:56:05 T:4388  NOTICE: CommonFunctions-2.5.1
21:56:05 T:4388   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Céline\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.genesis\TVShows\
21:56:06 T:5920  NOTICE: Thread PVRGUIInfo start, auto delete: false
21:56:06 T:4068  NOTICE: EPG::CEpgContainer::Start - EPG thread started
21:56:06 T:6212  NOTICE: Thread EPGUpdater start, auto delete: false
21:56:06 T:6212   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file 'http://www.kazer.org/tvguide.zip?u=591wu7mx54mnx':  file is missing or empty. :1th try.
21:56:09 T:6212   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file 'http://www.kazer.org/tvguide.zip?u=591wu7mx54mnx':  file is missing or empty. :2th try.
21:56:11 T:6212   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file 'http://www.kazer.org/tvguide.zip?u=591wu7mx54mnx':  file is missing or empty. :3th try.
21:56:11 T:6212   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file 'http://www.kazer.org/tvguide.zip?u=591wu7mx54mnx':  file is missing or empty. After 3 tries.
21:56:13 T:4352  NOTICE: Thread BackgroundLoader start, auto delete: false
21:56:28 T:5516  NOTICE: Thread JobWorker start, auto delete: true
21:56:31 T:6700  NOTICE: Thread LanguageInvoker start, auto delete: false
21:56:31 T:6700  NOTICE: -->Python Interpreter Initialized<--
21:56:33 T:6700  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:56:33 T:6700  NOTICE: 	[PLUGIN] Vstream: call load methode
21:56:33 T:2056  NOTICE: Thread BackgroundLoader start, auto delete: false
21:56:37 T:8080  NOTICE: Thread LanguageInvoker start, auto delete: false
21:56:37 T:8080  NOTICE: -->Python Interpreter Initialized<--
21:56:38 T:8080  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:56:38 T:8080  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function showSearch
21:56:38 T:8080  NOTICE: 	[PLUGIN] Vstream: Table watch_history initialized
21:56:38 T:3804  NOTICE: Thread BackgroundLoader start, auto delete: false
21:56:40 T:5644  NOTICE: Thread LanguageInvoker start, auto delete: false
21:56:40 T:5644  NOTICE: -->Python Interpreter Initialized<--
21:56:40 T:5644  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:56:40 T:5644  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function searchMovie
21:56:40 T:5644  NOTICE: 	[PLUGIN] Vstream: Root Folder: C:\Users\Céline\AppData\Roaming\Kodi\addons\plugin.video.vstream
21:56:41 T:5644  NOTICE: 	[PLUGIN] Vstream: Sites Folder: C:/Users/Céline/AppData/Roaming/Kodi/addons/plugin.video.vstream/resources/sites
21:56:41 T:5644   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: (3, 'Le chemin d\x92acc\xe8s sp\xe9cifi\xe9 est introuvable', 'C:/Users/C\xc3\xa9line/AppData/Roaming/Kodi/addons/plugin.video.vstream/resources/sites/*.*')
                                            Traceback (most recent call last):
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 118, in <module>
                                                main()
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 27, in __init__
                                                self.parseUrl()
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 52, in parseUrl
                                                if (isHome(sSiteName, sFunction) == True):
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 114, in isHome
                                                exec "oHome."+ sFunction +"()"
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\home.py", line 283, in searchMovie
                                                aPlugins = oHandler.getAvailablePlugins(sDisp)
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\rechercheHandler.py", line 69, in getAvailablePlugins
                                                aFileNames = self.__getFileNamesFromFolder(sFolder)
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\rechercheHandler.py", line 22, in __getFileNamesFromFolder
                                                items = os.listdir(sFolder)
                                            WindowsError: (3, 'Le chemin d\x92acc\xe8s sp\xe9cifi\xe9 est introuvable', 'C:/Users/C\xc3\xa9line/AppData/Roaming/Kodi/addons/plugin.video.vstream/resources/sites/*.*')
                                            -->End of Python script error report<--
21:56:41 T:6368   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=cHome&siteUrl=http%3a%2f%2fvenom&title=Films
21:56:41 T:6368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=cHome&siteUrl=http%3a%2f%2fvenom&title=Films) failed
21:56:41 T:7612  NOTICE: Thread BackgroundLoader start, auto delete: false
21:57:06 T:6412  NOTICE: Thread LanguageInvoker start, auto delete: false
21:57:06 T:6412  NOTICE: -->Python Interpreter Initialized<--
21:57:07 T:6412  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
21:57:07 T:6412  NOTICE: 	[PLUGIN] Vstream: load site cHome and call function searchMovie
21:57:08 T:6412  NOTICE: 	[PLUGIN] Vstream: Root Folder: C:\Users\Céline\AppData\Roaming\Kodi\addons\plugin.video.vstream
21:57:08 T:6412  NOTICE: 	[PLUGIN] Vstream: Sites Folder: C:/Users/Céline/AppData/Roaming/Kodi/addons/plugin.video.vstream/resources/sites
21:57:08 T:6412   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: (3, 'Le chemin d\x92acc\xe8s sp\xe9cifi\xe9 est introuvable', 'C:/Users/C\xc3\xa9line/AppData/Roaming/Kodi/addons/plugin.video.vstream/resources/sites/*.*')
                                            Traceback (most recent call last):
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 118, in <module>
                                                main()
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 27, in __init__
                                                self.parseUrl()
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 52, in parseUrl
                                                if (isHome(sSiteName, sFunction) == True):
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 114, in isHome
                                                exec "oHome."+ sFunction +"()"
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\home.py", line 283, in searchMovie
                                                aPlugins = oHandler.getAvailablePlugins(sDisp)
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\rechercheHandler.py", line 69, in getAvailablePlugins
                                                aFileNames = self.__getFileNamesFromFolder(sFolder)
                                              File "C:\Users\C�line\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\rechercheHandler.py", line 22, in __getFileNamesFromFolder
                                                items = os.listdir(sFolder)
                                            WindowsError: (3, 'Le chemin d\x92acc\xe8s sp\xe9cifi\xe9 est introuvable', 'C:/Users/C\xc3\xa9line/AppData/Roaming/Kodi/addons/plugin.video.vstream/resources/sites/*.*')
                                            -->End of Python script error report<--
21:57:08 T:6368   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=cHome&siteUrl=http%3a%2f%2fvenom&title=Films
21:57:08 T:6368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?disp=search1&function=searchMovie&readdb=True&sFav=searchMovie&site=cHome&siteUrl=http%3a%2f%2fvenom&title=Films) failed
21:57:08 T:4024  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by LordVenom** [comment]
Bonjour et Merci, je regarde ça
