### ISSUE TITLE
Impossible d'ouvrir les liens openload

### ISSUE THREAD

**Issue by natzen** [LordVenom/venom-xbmc-addons#471]
Bonjour ,chez moi impossible d'ouvrir les liens openload ? y'a t-il se probleme chez tout le monde ou dois je faire une manipulation?
Merci

**Comment by TmpName** [comment]
Nope, ils ont fait une MAJ, je m'en occupe de suite, ils ont pas ete chercher bien loin.

**Comment by TmpName** [comment]
Mit a jour, dans max 4 jours chez toi, sinon avances la date de 4 jours avant de lancer kodi.

**Comment by natzen** [comment]
c'est possible ça ? merci beaucoup en tout cas

**Comment by TmpName** [comment]
Yep, et tu vas avoir une option sur la page d'acceuil de Vstream pour mettre a jour certain fichiers, une fleche verte.

**Comment by natzen** [comment]
nickel merci beaucoup !

**Comment by arzaz** [comment]
Les pigeons sont de retour.

**Comment by TmpName** [comment]
Oui lol, mais cette fois ils ont fait un vrai codage.
La j'ai pas trop le temps, mais ca devrait revenir au plus tard en debut de semaine.

**Comment by TmpName** [comment]
Mise en place d'un "patch" pris sur le code d'un autre addon.
Mais je ne pense pas que ca va durer.

**Comment by TmpName** [comment]
Nouvelle version en ligne depuis quelques jours, et pas de retours.
