### ISSUE TITLE
Serie en continu

### ISSUE THREAD

**Issue by nicolas77410** [LordVenom/venom-xbmc-addons#472]
Bonjour
Lors de la fin d'une serie ou film en streaming, elle ne s'arrête pas. La lecture ne se termine pas,je suis obligé de l'arrêter manuellement sinon elle continue.
Pouvez-vous m'indiquer la procédure pour retirer ce bug.
Cordialement

**Comment by TmpName** [comment]
Alors la, ca c'est original, aucune idee.
Ca te le fait sur tout les sites, tous les hebergeurs ?
Uniquement avec Vstream ?

**Comment by Brahimbaz** [comment]
Salut TmpName. 
Pour moi c'est la même chose. Que sur vstream. Sur libretv ca ne me le fait pas.

**Comment by TmpName** [comment]
Et vous avez quoi comme machine ?

**Comment by Brahimbaz** [comment]
Pour ma part c'est la freebox 4k

**Comment by nicolas77410** [comment]
Hello,
Pour résoudre le problème, j'ai été dans l'onglet configuration de Vstream et j'ai change le lecteur video puis sur auto.
J'ai redemarrre kodi et plus de probleme de double lecture des séries.
Je pense que c'est dû au mise à jour. En écrasant les anciennes mise à jour.
Il faudrait supprimer l'ancienne et installer la nouvelle.
Je suis sur un minipc asrock.
Par contre, je n'ai pas rencontré de probleme sur l'installation de la chambre.

Merci à tous

**Comment by TmpName** [comment]
Les mises a jour suppriment les anciens fichiers, mais ne touchent pas forcement aux vielles configs, c'est peut etre ca, mais je t'avourais que le moteur de lecture de Vstream est un cote obscur de Vstream pr moi, c'est surtout LordVenom qui bidouille cette bete.

En tout cas, merci pour l'infos, car la je ne vois pas du tout comment corriger ca.

**Comment by Brahimbaz** [comment]
Merci problème corrigé !!!
