### ISSUE TITLE
Toujours 0.4.2...

### ISSUE THREAD

**Issue by clyde005** [LordVenom/venom-xbmc-addons#473]
Bonjour,
Lorsque je fait une mise à jour manuelle depuis Vstream dans Kodi, je remarque bien qu'il fait cette mise à jour..mais il ne change jamais la version de Kodi, c'est toujours 0.4.2?
J'ai raté un truc là?
Merci!

**Comment by TmpName** [comment]
Utilises la Mise a jour auto en installant le repo, il se mettra a jour tout seul a chaque nouvelle version.

**Comment by clyde005** [comment]
Merci patron ;-)
