### ISSUE TITLE
problème avec youwatch

### ISSUE THREAD

**Issue by hadesjack** [LordVenom/venom-xbmc-addons#48]
Bonjour,

je n'arrive à acceder à aucun contenu issue de youwatch et tester sur  pc différent.

Voici un exemple de log

23:54:32 T:6908  NOTICE: Thread JobWorker start, auto delete: true
23:54:32 T:4916  NOTICE: Thread LanguageInvoker start, auto delete: false
23:54:32 T:4916  NOTICE: -->Python Interpreter Initialized<--
23:54:32 T:4916  NOTICE: CommonFunctions-2.5.1
23:54:32 T:4916   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Hades HTPC\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.genesis\TVShows\
23:55:09 T:6528  NOTICE: Thread JobWorker start, auto delete: true
23:55:09 T:6584  NOTICE: Thread LanguageInvoker start, auto delete: false
23:55:09 T:6584  NOTICE: -->Python Interpreter Initialized<--
23:55:09 T:6584  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
23:55:09 T:6584  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
23:55:10 T:6584  NOTICE: 	[PLUGIN] Vstream: Hoster - play http://youwatch.org/embed-c9nzhhgr6aqd-580x360.html
23:55:10 T:6584  NOTICE: 	[PLUGIN] Vstream: playertype from config: auto
23:55:19 T:1992  NOTICE: DVDPlayer: Opening: http://fs36.youwatch.org:8777/t7vpz5igd6oax3ptx3oyjvvrvnccssrl6krjtpjty6dajwkmzt3tojd3na/video.mp4
23:55:19 T:1992 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
23:55:19 T:1992  NOTICE: DXVA::CProcessorHD::PreInit - The Direct3d device doesn't support DXVA-HD.
23:55:19 T:1992  NOTICE: CWinRenderer::Preinit - could not init DXVA-HD processor - skipping
23:55:19 T:760  NOTICE: Thread DVDPlayer start, auto delete: false
23:55:19 T:760  NOTICE: Creating InputStream
23:55:29 T:760   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://fs36.youwatch.org:8777/t7vpz5igd6oax3ptx3oyjvvrvnccssrl6krjtpjty6dajwkmzt3tojd3na/video.mp4
23:55:37 T:760  NOTICE: Creating Demuxer
23:55:37 T:1060  NOTICE: Thread FileCache start, auto delete: false
23:55:49 T:6208   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file 'http://www.kazer.org/tvguide.zip?u=591wu7mx54mnx':  file is missing or empty. :1th try.
23:55:51 T:6208   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file 'http://www.kazer.org/tvguide.zip?u=591wu7mx54mnx':  file is missing or empty. :2th try.
23:55:53 T:6208   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file 'http://www.kazer.org/tvguide.zip?u=591wu7mx54mnx':  file is missing or empty. :3th try.
23:55:53 T:6208   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load EPG file 'http://www.kazer.org/tvguide.zip?u=591wu7mx54mnx':  file is missing or empty. After 3 tries.
23:56:07 T:760   ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file http://fs36.youwatch.org:8777/t7vpz5igd6oax3ptx3oyjvvrvnccssrl6krjtpjty6dajwkmzt3tojd3na/video.mp4
23:56:07 T:760   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
23:56:07 T:760  NOTICE: CDVDPlayer::OnExit()
23:56:07 T:1992   ERROR: Playlist Player: skipping unplayable item: 0, path [http://fs36.youwatch.org:8777/t7vpz5igd6oax3ptx3oyjvvrvnccssrl6krjtpjty6dajwkmzt3tojd3na/video.mp4]
23:56:07 T:1992  NOTICE: CDVDPlayer::CloseFile()
23:56:07 T:1992  NOTICE: DVDPlayer: waiting for threads to exit
23:56:07 T:1992  NOTICE: DVDPlayer: finished waiting
23:56:07 T:1992  NOTICE: CDVDPlayer::CloseFile()
23:56:07 T:1992  NOTICE: DVDPlayer: waiting for threads to exit
23:56:07 T:1992  NOTICE: DVDPlayer: finished waiting
23:56:07 T:6148  NOTICE: 1Channel: Service: Playback Stopped
23:56:07 T:6148  NOTICE: 1Channel: Service: Resetting...
23:56:14 T:6584   ERROR: EXCEPTION: XBMC is not playing any file
23:56:14 T:6584  NOTICE: 	[PLUGIN] Vstream: Start Player Impossible
23:56:14 T:1992   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?bGetRedirectUrl=False&function=play&sCat=4&sFav=play&sFileName=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement&sHosterIdentifier=youwatch&sId=cHosterGui&sMediaUrl=http%3a%2f%2fyouwatch.org%2fembed-c9nzhhgr6aqd-580x360.html&sThumbnail=http%3a%2f%2fi.imgur.com%2fwrKzai4.jpg&sTitle=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement&site=cHosterGui&siteUrl=http%3a%2f%2fyouwatch.org%2fembed-c9nzhhgr6aqd-580x360.html&title=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement%20%5bCOLOR%20skyblue%5dYouwatch%5b%2fCOLOR%5d%20%5bCOLOR%20khaki%5d%5b%2fCOLOR%5d
23:56:14 T:1992   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?bGetRedirectUrl=False&function=play&sCat=4&sFav=play&sFileName=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement&sHosterIdentifier=youwatch&sId=cHosterGui&sMediaUrl=http%3a%2f%2fyouwatch.org%2fembed-c9nzhhgr6aqd-580x360.html&sThumbnail=http%3a%2f%2fi.imgur.com%2fwrKzai4.jpg&sTitle=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement&site=cHosterGui&siteUrl=http%3a%2f%2fyouwatch.org%2fembed-c9nzhhgr6aqd-580x360.html&title=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement%20%5bCOLOR%20skyblue%5dYouwatch%5b%2fCOLOR%5d%20%5bCOLOR%20khaki%5d%5b%2fCOLOR%5d) failed
23:56:14 T:4872  NOTICE: Thread BackgroundLoader start, auto delete: false
23:57:35 T:1124  NOTICE: Thread JobWorker start, auto delete: true
23:57:35 T:4192  NOTICE: Thread LanguageInvoker start, auto delete: false
23:57:35 T:4192  NOTICE: -->Python Interpreter Initialized<--
23:57:35 T:4192  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
23:57:35 T:4192  NOTICE: 	[PLUGIN] Vstream: load site cHosterGui and call function play
23:57:36 T:4192  NOTICE: 	[PLUGIN] Vstream: Hoster - play http://youwatch.org/embed-c9nzhhgr6aqd-580x360.html
23:57:36 T:4192  NOTICE: 	[PLUGIN] Vstream: playertype from config: auto
23:57:45 T:1992  NOTICE: DVDPlayer: Opening: http://fs36.youwatch.org:8777/t7vpz5igd6oax3ptx3oyjvvrvnccssrl6krjtpjty6dajwkmzt34kj33na/video.mp4
23:57:45 T:1992 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
23:57:45 T:1992  NOTICE: DXVA::CProcessorHD::PreInit - The Direct3d device doesn't support DXVA-HD.
23:57:45 T:1992  NOTICE: CWinRenderer::Preinit - could not init DXVA-HD processor - skipping
23:57:45 T:7072  NOTICE: Thread DVDPlayer start, auto delete: false
23:57:45 T:7072  NOTICE: Creating InputStream
23:58:03 T:7072  NOTICE: Creating Demuxer
23:58:03 T:2876  NOTICE: Thread FileCache start, auto delete: false
23:58:33 T:7072   ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file http://fs36.youwatch.org:8777/t7vpz5igd6oax3ptx3oyjvvrvnccssrl6krjtpjty6dajwkmzt34kj33na/video.mp4
23:58:33 T:7072   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
23:58:33 T:7072  NOTICE: CDVDPlayer::OnExit()
23:58:33 T:1992   ERROR: Playlist Player: skipping unplayable item: 0, path [http://fs36.youwatch.org:8777/t7vpz5igd6oax3ptx3oyjvvrvnccssrl6krjtpjty6dajwkmzt34kj33na/video.mp4]
23:58:33 T:1992  NOTICE: CDVDPlayer::CloseFile()
23:58:33 T:1992  NOTICE: DVDPlayer: waiting for threads to exit
23:58:33 T:1992  NOTICE: DVDPlayer: finished waiting
23:58:33 T:1992  NOTICE: CDVDPlayer::CloseFile()
23:58:33 T:1992  NOTICE: DVDPlayer: waiting for threads to exit
23:58:33 T:1992  NOTICE: DVDPlayer: finished waiting
23:58:34 T:6148  NOTICE: 1Channel: Service: Playback Stopped
23:58:34 T:6148  NOTICE: 1Channel: Service: Resetting...
23:58:41 T:4192   ERROR: EXCEPTION: XBMC is not playing any file
23:58:41 T:4192  NOTICE: 	[PLUGIN] Vstream: Start Player Impossible
23:58:41 T:1992   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vstream/?bGetRedirectUrl=False&function=play&sCat=4&sFav=play&sFileName=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement&sHosterIdentifier=youwatch&sId=cHosterGui&sMediaUrl=http%3a%2f%2fyouwatch.org%2fembed-c9nzhhgr6aqd-580x360.html&sThumbnail=http%3a%2f%2fi.imgur.com%2fwrKzai4.jpg&sTitle=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement&site=cHosterGui&siteUrl=http%3a%2f%2fyouwatch.org%2fembed-c9nzhhgr6aqd-580x360.html&title=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement%20%5bCOLOR%20skyblue%5dYouwatch%5b%2fCOLOR%5d%20%5bCOLOR%20khaki%5d%5b%2fCOLOR%5d
23:58:41 T:1992   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vstream/?bGetRedirectUrl=False&function=play&sCat=4&sFav=play&sFileName=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement&sHosterIdentifier=youwatch&sId=cHosterGui&sMediaUrl=http%3a%2f%2fyouwatch.org%2fembed-c9nzhhgr6aqd-580x360.html&sThumbnail=http%3a%2f%2fi.imgur.com%2fwrKzai4.jpg&sTitle=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement&site=cHosterGui&siteUrl=http%3a%2f%2fyouwatch.org%2fembed-c9nzhhgr6aqd-580x360.html&title=La%20Plan%c3%a8te%20des%20singes%20%3a%20l%27affrontement%20%5bCOLOR%20skyblue%5dYouwatch%5b%2fCOLOR%5d%20%5bCOLOR%20khaki%5d%5b%2fCOLOR%5d) failed
23:58:41 T:840  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by LordVenom** [comment]
Bonjour,

J'ai remarquer ça aussis mais sur certaine video seulement le temps d'attente et tellement long que Xbmc abandonne.

**Comment by hadesjack** [comment]
Pour ma part, j'avais déjà essayé la semaine dernière sur une 10ene de source et idem ce week-end, je n'ai jamais réussi à faire tourner une seule video de youwatch, toutefois la semaine dernière l'erreur apparaissais bien plus vite.


Si c'est aléatoire et venant de youwatch ne tenais pas compte alors de l'anomalie, je souhait essayer de remonter ce que je penses être des anomalie pour améliorer l'application, toutefois  je veux aussi vous remercier pour cette superbe application, de votre disponibilité.

merci et courage

**Comment by LordVenom** [comment]
Difficile de trouver l'erreur, je suis passer par plusieur pc et via vlc pour voir ça, de plus j'ai coder un petit truc pour passer par l'addon resolver même chez eux ça veut pas, c'est vlc qui ma surpris en affichant la video avec 10mn de recherche. Pour notre bonheur a tous youwatch doit mourir lol

**Comment by Kodigoal** [comment]
lol #youwatchRip

Moi les liens en général fonctionne , mais genre je liste par exemple un film en 720p et comme
host ya youwatch , il me l'ouvre toujours en sd , et si je l'ouvre par un host
genre openload  c'est bien en 720p ...
c'est normal ?

**Comment by TmpName** [comment]
Yep ^^.
Youwatch toujours SD
Openload generalement "HD" (si on peut appeller ca de la HD.

Si tu passes par un debrideur ou si tu es enregistré sur youwatch, je crois que tu as de la meilleure qualité mais j'ai jamais testé (et pour le moment Vstream ne gere pas les login)

**Comment by Kodigoal** [comment]
ok merci TmpName pour ses précisions :-)
