### ISSUE TITLE
Zone téléchargement  lecture de film impossible bloqué sur " en cours "

### ISSUE THREAD

**Issue by mako83** [LordVenom/venom-xbmc-addons#480]
Bonjour ,
J'ai test de mater un film sur zone dl et cela bloqué sur en cours et cela avec tout mes appareil et magres un retelechargement de l'extension.

**Comment by driteur** [comment]
Même problème chez moi...

**Comment by Phobos1337** [comment]
C'est bizarre cela fonctionne très bien chez moi, vous pouvez préciser le problème ? ^^

**Comment by driteur** [comment]
Je viens d'avoir une maj à l'instant et le problème semble corriger.

**Comment by driteur** [comment]
Tout semble fonctionner sauf quand je clic sur dernier documentaire il me met une erreur^^

**Comment by Phobos1337** [comment]
Oui je vois c'est surement un problème d'encoding avec python ^^

**Comment by Phobos1337** [comment]
J'ai envoyé une petite modification ça devrait régler le problème ^^ #481

**Comment by lemoine34** [comment]
Impossible de lire un film sur zone de téléchargement bloqué sur en cours

**Comment by Phobos1337** [comment]
Il faut faire la mise à jour ^^

**Comment by lemoine34** [comment]
aucune mise a jour possible via vstream
comment il faut faire ? merci d'avance

**Comment by LordVenom** [comment]
Bonjour,

@Phobos1337 : Merci pour la correction mais c'est plus un problème de variable mal placer de plus je t'encourage à poster les modifications sur la version bêta plus simple pour nous https://github.com/LordVenom/venom-xbmc-addons-beta.

@lemoine34 : Il faut trois jour a vstream pour proposer les mise à jour.

**Comment by TmpName** [comment]
La je suis un peu perdu, avec tant de modif en meme temps, Ca marche la ou pas, avec la derniere version officielle ?

Sinon officieusement pr forcer les MAJ, il te suffit d'avancer la date de ton ordi de 3 jours avant de lancer Vstream.

**Comment by TmpName** [comment]
Bon j'ai fais une boulette, j'ai encore confondu la beta et le off.
Donc merci de me dire si ca marche ou pas car j'ai vire une correction de LordVenom, du coup si ca marche pas, ca va bloquer completement ZT.

**Comment by Phobos1337** [comment]
Beaucoup de boulette xD A priori je pense qu'après la mise à jour cela refonctionne ^^

**Comment by TmpName** [comment]
Lol, c'est clair, mais faut dire que c'est parti dans tout les sens ce soir.
C'est bien, ca fait plaisir de voir qu'il a une communaute sur le projet, le truc c'est qu'on est habitue a passer par le beta, pour eviter les boulettes justement, alors la je cumule, suis deja a 3 dans la soirée.

**Comment by Phobos1337** [comment]
Tu as passé le cap des "jamais deux sans trois" c'est déjà ça lol

**Comment by TmpName** [comment]
XD, bon la me sauve, j 'espere pas me faire lyncher quand vais revenir.

**Comment by Phobos1337** [comment]
Je croise les doigts pour toi xD

**Comment by mako83** [comment]
Chez moi ça ne marche toujours pas car j'arrive pas à appliquer la dernière maj sinon comment faites vous pour installer la beta

Merci de votre boulot !

**Comment by LordVenom** [comment]
Faut vraiment arrêter avec le github beta j'ai créer une nouvelle branche (beta)et ont vas essayer de faire marcher ça comme c'est prévus moin simple au debut mais ont finiras par y arriver lol.

Donc officiellement beta et Off le temps pour moi de mettre de l'ordre la dedans.

**Comment by TmpName** [comment]
XD.
J'avoue hier, j'ai galere comme un porc. Go pour la nouvelle branche.

**Comment by mako83** [comment]
Salut, merci des infos :) de la correction du bug ! Super team 

Continuez comme ça !
