### ISSUE TITLE
Mise à jour automatique de la playlist FreeboxTV

### ISSUE THREAD

**Issue by Europe57** [LordVenom/venom-xbmc-addons#49]
Salut,

J'ai remarquer que la playlist pour la télévision via Free, n'est pas à jour, plusieurs chaines HD sont apparu, et d'autre on disparu sur la playlist officiel.

C'est possible d'ajouter un système de mise a jour automatique en prenant par exemple la playlist officiel et non une copie sur un site internet ? Ou sa provoque des bugs ?

Adresse officiel de la playlist : http://mafreebox.freebox.fr/freeboxtv/playlist.m3u

A+

**Comment by LordVenom** [comment]
Bonjour, faudrait que je regarde mais je pense pas la structure n'est pas la même.
