### ISSUE TITLE
frenchstream_com is blocking search

### ISSUE THREAD

**Issue by netwoof** [LordVenom/venom-xbmc-addons#498]
Hi,

It looks like this source time out when requested to search a movie. Is there a way to edit preferences to remove this source ?

Regards,

**Comment by netwoof** [comment]
Désolé, j'avais pas vu que toutes les issues étaient en français, donc pour faire plus simple, une recherche de stream bloque un paquet de temps (ça ressemble fortement à un timeout) lorsqu'on appelle cette source. Est-ce configurable qqpart ?

Merci beaucoup, et bon boulot, cette appli devrait remplacer android TV sur les box :)

**Comment by netwoof** [comment]
Et du coup, j'ai trouvé la réponse ici : #458 . Merci encore :).

**Comment by TmpName** [comment]
Mais ce site fout souvent le bordel, a voir pour y mettre un timeout plus court, juste pour lui.
