### ISSUE TITLE
VideoMega.tv

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#50]
Bonsoir LordVenom,

Tous les liens avec VideoMega sont introuvable?

S'agit-il d'un bug?

**Comment by LordVenom** [comment]
C'est noter merci je regarde ça.

**Comment by arzaz** [comment]
Bonjour LordVenom,

Merci pour cette nouvelle mise a jour 2.7, mais  le problème de VideoMega n'est toujours pas réglé?

Merci encore.

**Comment by LordVenom** [comment]
Bonjour, Impossible a résoudre l'hote sera supprimer dans la prochaine mise a jour.
