### ISSUE TITLE
vstream extension sur raspbian kodi probleme

### ISSUE THREAD

**Issue by tanguyarm** [LordVenom/venom-xbmc-addons#52]
bonjour,
j'ai un probleme de dependence quand je veux installer l'extension vstream (plugin.video.vstream-0.2.6.zip) et impossible d'installer (venom-xbmc-addons-master.zip).
je suis sur raspberry pi B+ 
et 
xbmc/kodi de chez (deb http://archive.mene.za.net/raspbian wheezy contrib)

**Comment by LordVenom** [comment]
Bonjour, voici la liste des librairies utiliser par vStream.

https://github.com/LordVenom/venom-xbmc-addons/issues/38
