### ISSUE TITLE
adkami

### ISSUE THREAD

**Issue by Sam201501** [LordVenom/venom-xbmc-addons#53]
Bonjour,

D'abord merci pour ce magnifique addon, je l'ai découvert récemment avec plaisir !

Je remarque juste que pour la plupart des vidéos de adkami (dans la section "animés VF"), je reçois une erreur de script.

Merci

**Comment by LordVenom** [comment]
Bonjour, C'est le gros soucis d'AdKami, beaucoup de lien son mort.

**Comment by Sam201501** [comment]
Merci d'avoir pris le temps de répondre vite.

Je me suis aussi dis que cela venait peut-être de liens mort, c'est pour cela que j'ai fait quelques test sur leur site. Et par exemple si je prends "Inazuma Eleven", sur leur site, j'arrive à visionner le premier épisode. Mais pas avec cet addon.

Merci

**Comment by LordVenom** [comment]
Tu parle de ce lien http://www.adkami.com/index.php?page=manga&id=476&episode=001&version=1&genre=1

Chez moi ça tourne dsl

**Comment by Sam201501** [comment]
Merci pour l'info.
Je vais essayer à nouveau ce soir. 
Je l'avais pourtant testé sur un android avec xbmc 13.2 et un Windows 8 avec kodi 14.0.

**Comment by Sam201501** [comment]
Bonsoir,
J'ai réinstallé l'addon, mais j'ai toujours le même problème : dans la section animes vf de adkami,je sélectionne un épisode et je reçoit error script vstream. Je n'ai cela que pour adkami, quelque soit le dessin animé choisi.

Y-a-t-il autre chose à installer ?

**Comment by LordVenom** [comment]
Il faudrait me fournir un log, merci.

**Comment by Sam201501** [comment]
Bonjour,

J'ai pu activer le log, je pense que la partie qui correspond à l'erreur est celle-ci:

11:28:47 T:7560   DEBUG: Thread BackgroundLoader 7560 terminating
11:28:48 T:2016   DEBUG: CImageLoader::DoWork - took 149 ms to load special://masterprofile/Thumbnails/4/42c7d2ae.png
11:28:49 T:5760   DEBUG: CApplication::ProcessMouse: trying mouse action leftclick
11:28:49 T:5760   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.vstream/?bGetRedirectUrl=False&function=play&sCat=4&sFav=play&sFileName=Episode%20001%20vf&sHosterIdentifier=dailymotion&sId=cHosterGui&sMediaUrl=http%3a%2f%2fwww.dailymotion.com%2fembed%2fvideo%2fxoyx0e%3flogo%3d0&sThumbnail&sTitle=Episode%20001%20vf&site=cHosterGui&siteUrl=http%3a%2f%2fwww.dailymotion.com%2fembed%2fvideo%2fxoyx0e%3flogo%3d0&title=Episode%20001%20vf%20%5bCOLOR%20skyblue%5dDailyMotion%5b%2fCOLOR%5d%20%5bCOLOR%20khaki%5d%5b%2fCOLOR%5d)
11:28:49 T:5760   DEBUG:   ParentPath = [plugin://plugin.video.vstream/?function=showHosters&sFav=showHosters&sMovieTitle=Episode%20001%20vf&site=adkami_com&siteUrl=http%3a%2f%2fwww.adkami.com%2findex.php%3fpage%3dmanga%26id%3d476%26episode%3d001%26version%3d1%26genre%3d1&title=Inazuma%20Eleven%20%3a%20Puissance%20foot%20-%20Episode%20001%20vf]
11:28:49 T:2016   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin vStream('plugin://plugin.video.vstream/','6','?bGetRedirectUrl=False&function=play&sCat=4&sFav=play&sFileName=Episode%20001%20vf&sHosterIdentifier=dailymotion&sId=cHosterGui&sMediaUrl=http%3a%2f%2fwww.dailymotion.com%2fembed%2fvideo%2fxoyx0e%3flogo%3d0&sThumbnail&sTitle=Episode%20001%20vf&site=cHosterGui&siteUrl=http%3a%2f%2fwww.dailymotion.com%2fembed%2fvideo%2fxoyx0e%3flogo%3d0&title=Episode%20001%20vf%20%5bCOLOR%20skyblue%5dDailyMotion%5b%2fCOLOR%5d%20%5bCOLOR%20khaki%5d%5b%2fCOLOR%5d')
11:28:49 T:2016   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the vStream (id=7) plugin...
11:28:49 T:5328  NOTICE: Thread LanguageInvoker start, auto delete: false
11:28:49 T:5328    INFO: initializing python engine.
11:28:49 T:5328   DEBUG: CPythonInvoker(7, C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): start processing
11:28:49 T:5328  NOTICE: -->Python Interpreter Initialized<--
11:28:49 T:5328   DEBUG: CPythonInvoker(7, C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): the source file to load is "C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py"
11:28:49 T:5328   DEBUG: CPythonInvoker(7, C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): setting the Python path to C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream;C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\script.common.plugin.cache\lib;C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\script.module.addon.common\lib;C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\script.module.metahandler\lib;C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\script.module.myconnpy\lib;C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\script.module.parsedom\lib;C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\script.module.simplejson\lib;C:\Program Files\Kodi\system\python\DLLs;C:\Program Files\Kodi\system\python\Lib;C:\Program Files\Kodi\python27.zip;C:\Program Files\Kodi\system\python\lib\plat-win;C:\Program Files\Kodi\system\python\lib\lib-tk;C:\Program Files\Kodi;C:\Program Files\Kodi\system\python;C:\Program Files\Kodi\system\python\lib\site-packages
11:28:49 T:5328   DEBUG: CPythonInvoker(7, C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): entering source directory C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream
11:28:49 T:5328   DEBUG: CPythonInvoker(7, C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py): instantiating addon using automatically obtained id of "plugin.video.vstream" dependent on version 2.1.0 of the xbmc.python api
11:28:49 T:5760   DEBUG: ------ Window Init (DialogBusy.xml) ------
11:28:50 T:5328  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
11:28:50 T:5328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: dictionary update sequence element #8 has length 1; 2 is required
                                            Traceback (most recent call last):
                                              File "C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 118, in <module>
                                                main()
                                              File "C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 27, in __init__
                                                self.parseUrl()
                                              File "C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\default.py", line 30, in parseUrl
                                                oInputParameterHandler = cInputParameterHandler()
                                              File "C:\Users\Administrator.lapbe200916\AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\lib\handler\inputParameterHandler.py", line 9, in __init__
                                                aParams = dict(part.split('=') for part in sys.argv[ 2 ][ 1: ].split('&'))
                                            ValueError: dictionary update sequence element #8 has length 1; 2 is required
                                            -->End of Python script error report<--
11:28:50 T:5760   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
11:28:50 T:5328    INFO: Python script stopped

Merci à toi pour ton aide :)

**Comment by LordVenom** [comment]
Apparemment il cherche une variable qui ne reçoit rien dont ça plante.Mais comme j'ai tous changer ou presque, pour la prochaine version, je retrouve pas les même info j'ai bien peur que tu doivent faire avec pas de solution pour le moment. dsl

**Comment by Sam201501** [comment]
Je comprends tout à fait 
Bon courage pour ta nouvelle version

**Comment by Sam201501** [comment]
Grâce à ta dernière version 0.2.7, cela fonctionne maintenant 
Un grand merci à toi :)

**Comment by mor17** [comment]
Merci infiniment pour ce travail est-ce que vous avez un compte PayPal pour faire des dents.
Cordialement

**Comment by LordVenom** [comment]
Merci pour le retour. Pour faire un don un lien a été ajouter sur l'accueil en bas de page.

[![PayPayl donate button](https://img.shields.io/badge/paypal-donate-yellow.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2KQZ5AUFYJW64 "Donner pour ce projet en utilisant Paypal")

**Comment by mor17** [comment]
Voila c'est fait...MERCI

**Comment by LordVenom** [comment]
Merci a vous, les remerciement sont une grande source de motivation mais l’argent reste la plus grande :)

**Comment by mor17** [comment]
😊...
