### ISSUE TITLE
Vstream script failed

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#54]
Bonjour LordVenom

Depuis hier, je n'arrive plus a lancer Vstream, j'arrive a accéder au menu "Recherche, Nouveau Films...etc" mais il suffit que je lance par exemple Nouveau Films j'ai le message d'erreur "Vstream script failed"?

Voici le debug log file: http://xbmclogs.com/show.php?id=405390

Merci de voir s'il te plait c'est quoi exactement le problème.

Salutations

**Comment by LordVenom** [comment]
C'est un problème de connection reseaux ça a du ce resoudre tous seul non ?

**Comment by arzaz** [comment]
Bonjour LordVenom,

Toujours le même problème, a chaque fois que la gateway de mon FAI change, je n’accède pas aux différentes rubriques de Vstream?  
Merci de revenir avec le lien correspondant a une rubrique par exemple "Nouveau Films" afin de la soumettre a mon fournisseur d’aces internet.

Salutations

**Comment by LordVenom** [comment]
Bonjour, dsl j'ai pas compris la.

"Merci de revenir avec le lien correspondant a une rubrique par exemple "Nouveau Films" afin de la soumettre a mon fournisseur d’aces internet."  ???

**Comment by arzaz** [comment]
Bonjour LordVenom,

Je voulais dire quand je lance Vstream j'ai les rubriques suivantes: "Recheche, Television, Films Nouveautes, ......" Par exemple quand je lance "Films Nouveautes" y a t-il un lien correspondant a cette recherche : http://........
Merci

**Comment by LordVenom** [comment]
Bonjour,

Je ne sais pas d'ou ça peux venir. quel et ta version d'xbmc et sur quel support et tu windows. linux ?

**Comment by arzaz** [comment]
Bonjour LordVenom,

Version XBMC: Gotham 13.2
Support: Prismcube "Hybrid Linux STB" http://prismcube.com/

Salutations
