### ISSUE TITLE
Echec du script

### ISSUE THREAD

**Issue by mir540** [LordVenom/venom-xbmc-addons#55]
Bonsoir,
Merci beaucoup pour cet énorme Add-on, vraiment excellent :)
Depuis deux jour j'ai échec du script au lancement de n'importe quelle rubrique, Recherche, Série, Film ...
J'utilise XBMC sur Raspberry, et mon accès à Internet est opérationnel,

Merci de m'orienter :)

**Comment by menad88** [comment]
Moi aussi, j'ai le même problème, sauf que si je me connecte avec la 3G, ça marche. Mais avec l'ADSL non. Peut-être, il faut configurer quelque chose sur le routeur.
j'ai KODI 14.1 (win7) et (android).
