### ISSUE TITLE
exashare aucun liens

### ISSUE THREAD

**Issue by Soundmanbe** [LordVenom/venom-xbmc-addons#56]
Bonjour, pour info,
Sur la derniere version 15..... kodi android....pour exashare, le seul message obtenu est : fichiers introuvables.
Bonne journée

**Comment by LordVenom** [comment]
Bonjour,

Merci, ce bug et connu et seras résolut dans la prochaine version.

**Comment by Soundmanbe** [comment]
Génial, merci pour le suivi et le bon boulot.

**Comment by Soundmanbe** [comment]
Was working for 3 days.... same problem again.
Just for info.
