### ISSUE TITLE
Full-Streaming

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#57]
Bonjour LordVenom,

Le lien Full-Streaming est mort.
Quand est prévue la prochaine mise a jour de Vstream?

Merci

**Comment by LordVenom** [comment]
Bonjour,

Pour le moment il vous suffis de le désactiver dans les paramètres du module.
Je ne sais pas pour la prochaine version l'addon et encore instable j'ai beaucoup de test à faire encore.
