### ISSUE TITLE
proposition d'une nouvelle source "FIFOSTREAM.TV"

### ISSUE THREAD

**Issue by menad88** [LordVenom/venom-xbmc-addons#59]
Bonjour, je vous remercie pour le travail que vous faites.
Je voulais vous proposer la source "fifostream.tv", c'est la meilleure des meilleures, il y a absolument tout dedans.
j’espère que vous pourriez la rajouter sur Vstream.
Merci beaucoup pour tout ce que vous offrez.

**Comment by LordVenom** [comment]
Merci, c'est noter mais ce site et trop "usine a gaz"
