### ISSUE TITLE
Problème si on regarde deux épisodes à la suite sur un même hoster

### ISSUE THREAD

**Issue by leblanc2000** [LordVenom/venom-xbmc-addons#61]
Bonjour,

J’ai remarqué un problème si on regarde deux épisodes à la suite sur un même hoster.
Je m’explique exemple je regarde le 1er épisode de Blue Bloods sur exashare et j’arrête la lecture avant le générique de fin (soit 30s avant la fin)
Et ensuite je lance le 2eme épisode sur exashare aussi, mais ce coups si la lecture de démarre 30s avant la fin de l’épisode 2 a lieu de partir a début de l’épisode.
A+

**Comment by LordVenom** [comment]
Bonjour, Problème connue et deja resolut dans la prochaine version
