### ISSUE TITLE
Lestream + Vk-Filmz

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#62]
Bonjour Lordvenom,

Dans Films Nouveautés les 02 liens Lestream & Vk-Filmz sont vides?
Par contres dans Séries Nouveautés sauf Vk-Filmz qui es vide?
Merci de voir c'est quoi le problème.

Salutations

**Comment by LordVenom** [comment]
Bonjour, Pas de soucis pour lestream, pour Vk le problème seras résolut dans la prochaine version.Merci

**Comment by arzaz** [comment]
Bonjour Lordvenom,

Avec la nouvelle mise a jour 2.8, le problème avec Lestream n'est toujours pas résolu?
Faut-il attendre la version 2.9?

Merci

**Comment by LordVenom** [comment]
Re,

Chez moi le liens n'est pas vide. Si je remarque un soucis je corrigerais.

**Comment by arzaz** [comment]
Re,

Chez moi le problème avec lestream est apparu seulement aujourd'hui? 

Merci
