### ISSUE TITLE
playback failed

### ISSUE THREAD

**Issue by jurgenjak** [LordVenom/venom-xbmc-addons#65]
salut chaque fois que j'essaie de faire fonctionner une chaine tv (excepté sou tv du web) j'ai le message "playback failed" suivi de "one or more items failed to play check the log file for details".
merci d'avance pour ton aide

**Comment by LordVenom** [comment]
Bonjour,

Les autres liens sont uniquement pour les bouquets, chez quel opérateur êtes vous et que retourne le log d'xmc?

**Comment by jurgenjak** [comment]
Ok merci.
Je m'en  suis rendu compte.
Je n'ai aucun de ces bouquets puisque je ne désire pas en Europe.
Encore merci c'est un excellent travail que vous avez fait là.
