### ISSUE TITLE
WebTV sous KODI (android)

### ISSUE THREAD

**Issue by glelan** [LordVenom/venom-xbmc-addons#66]
Bonjour,
je revient sur l'utilisation de ton Addons car TéléFr ne marche plus.
j'ai toujours un soucis sur les sources du groupe M6 en https qui ne marche pas sous Kodi mais bien sous VLC.
Une idée?
Merci beaucoup ;-)

**Comment by LordVenom** [comment]
Bonjour, Pas du tout jamais tester vStream sous android.Vous avez tester en modifier le lecteur par defaut dans les préférences de l'addon ?

**Comment by glelan** [comment]
Bonjour,
je vais voir ce soir dans les options... mais c'est étrange que VLC sur mon
android arrive à afficher le flux et pas Kodi..
Est-ce qu'il y a un fichier log à vous envoyer qui pourrait aider ? (si oui
où il est ?)

J'ai le meme soucis avec IPTV client simple, j'ai créer une play liste en
local avec le liens vers M6 en https et je n'arrive pas à l'afficher, Arté
marche bien, j'ai la chaine de la série Kaamelott aussi...mais ni M6 ni W9.

Est-ce que dans vos sources TF1 et les autres sources de chaines sont
géobloquer? je ne suis pas en france et je voudrais utiliser votre Addons
uniquement pour regarder les chaines française de temps en temps...
merci du coup de main.
Bonne journée
Greg

**Comment by LordVenom** [comment]
Bonjour,

Je ne sais pas si elle sont géolocaliser ou pas.Ce sont des sources trouver ici et la sur le web je ne suis pas le serveur de ces sources.
