### ISSUE TITLE
Guide des Programmes xmltv

### ISSUE THREAD

**Issue by MathieuG61** [LordVenom/venom-xbmc-addons#68]
Bonjour,
Je rencontre pas mal de soucis avec le guide des programmes qui ne s'affiche pas sur Kodi l'URL du fichier XMLTV est le suivante "http://kazer.org/tvguide.xml?u=rgyamjgsph9gx" serait-il possible de changer l'URL
Cordialement

**Comment by LordVenom** [comment]
Bonjour,
Trouver un guide IPTV français et gratuit et plus compliquer qu'ont pourrais penser, je regarderais quand même. Merci pour le rapport.

**Comment by MathieuG61** [comment]
Bonjour,
Pourquoi ne pas héberger le fichier .xml sur ton github et le mètre à jour toutes les semaines ?
si comme moi tu n'arrives pas à télécharger ce fichier voici deux sites qui l'hébergent
"http://pierre.kwaoo.me/programme.php"
"https://kodigeek.shost.ca/category/tutoriels/tutoriels_kodi-xbmc/"
Cordialement

**Comment by LordVenom** [comment]
Merci je regarderais ça.

**Comment by MathieuG61** [comment]
Bonjour,
Voici un guide IPTV français et gratuit http://xmltv.dtdns.net/alacarte/ beaucoup plus stable que Kazer
Cordialement
