### ISSUE TITLE
echec de la lecture d'un ou plusieurs elements

### ISSUE THREAD

**Issue by gatoune** [LordVenom/venom-xbmc-addons#69]
BOnjour,

tout d'abord merci pour le super addon. C'est génial.
Cependant j'ai souvent un souci et en parcourant le web je vois que nous sommes plusieurs à avoir le même, c'est le message "echec de la lecture d'un ou plusieurs elements" lorsque j'essaie de lancer des videos.
Pour le moment je ne vois pas de solution.
Pouvons-nous se pencher sur ce pb svp ?

Merci

**Comment by Apache84** [comment]
Bonjour, 
Ici aussi le même problème, 90% des streams de films ne fonctionnent pas.
Je tourne sous Win7 64 bits / Kodi version 14.2 / Vstream 0.2.8

J'ai l'impression que les liens des streams sont cassés, voici le log :

20:47:08 T:9952   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
20:47:08 T:9952   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
20:47:08 T:9952   ERROR: XFILE::CFileCache::Open - failed to open source <http://fs41.youwatch.org:8777/6dvpzby2nwoax3ptxycilbpr6vmncttbqprtetsftdqwihr5okqcesdipa/video.mp4>
20:47:08 T:9952   ERROR: CDVDPlayer::OpenInputStream - error opening [http://fs41.youwatch.org:8777/6dvpzby2nwoax3ptxycilbpr6vmncttbqprtetsftdqwihr5okqcesdipa/video.mp4]

Merci.

**Comment by Apache84** [comment]
Il semblerait que ce problème est récurent sur les hébergeurs Youwatch et Exoshare en particulier.
Je cherche toujours une solution, je me demande s'il ne faudrait pas ouvrir certains ports sur la box intrernet.

LordVenom, je me demande si le problème est réellement lié à Vstream mais j'ai du mal à interpréter les logs, pour moi ça viendrait plutôt des hébergeurs que j'ai cité plus haut. Si tu pouvez nous éclairer ça serait très sympa.

**Comment by LordVenom** [comment]
Bonjour,

Youwatch à pas mal de soucis, j'ai tester plusieurs solution pour le moment j'ai rien trouver de concluant parfois en insistant ça ce lance.

**Comment by Apache84** [comment]
Merci pour ta réponse et ton aide.

J'ai l'impression que Exashare aussi a quelques difficultés mais en effet en insistant ça finit par marcher.

**Comment by gatoune** [comment]
Merci pour vos commentaires. 
Je ne sais pas si j'ai un souci avec mon ordi, ou avec ma connexion ou alors avec vstream mais énormément de lien ne fonctionnent pas chez moi.. 
@lordvenom, tout fonctionne nickel de votre côté ?
