### ISSUE TITLE
Mise en cahe 0% Nowvideo + Vodlocker

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#70]
Bonjour LordVenom,

Le seul souci avec cette nouvelle mise a jour est la mise en cache des 02 hotes "Nowvideo" et "Vodlocker" qui bloque a 0%? 
Aucun problème avec les autres hotes.

Merci de voir c'est quoi le problème.

Salutations

**Comment by LordVenom** [comment]
Bonjour,
Pour moi il suffis de cliquer play et d'avoir un bon cache.
