### ISSUE TITLE
Structure de l'extension incorrecte à l'installation 

### ISSUE THREAD

**Issue by Biofx** [LordVenom/venom-xbmc-addons#74]
Bonjour, 
Je viens de découvrir cette extension qui me paraît très intéressante mais sur OpenELEC kodi 14.2 le repo refuse de s'installer. 
Structure de l'extension incorrecte. 
Une idée ?

**Comment by LordVenom** [comment]
Bonjour, Installer directement le dossier désipper dans votre xbmc.

**Comment by Biofx** [comment]
Mercedes ça fonctionne Impec.  Possibilité d'avoir des replay ? Genre chaîne 23 ou autre ? Ou bien existe t il un plugin spécifique pour les replay ? 

Merci encore et quel boulot !  Respect

**Comment by LordVenom** [comment]
Bonjour. Pour le moment le replay n est pas au programme. D autre addon savent le faire oui.

**Comment by koodycity** [comment]
Bonsoir à tous, 
J'ai la même erreur de structure lors de l'installation du fichier zip sous kodi ( raspberry). Je ne vois pas où je peux déposer le fichier dézippé dans les dossiers et sous dossiers du raspberry sous openelec. Pourriez-vous m'aider svp.
Merci d'avance

koody

**Comment by TmpName** [comment]
Tu as des videos sur la page d'acceuil, je n'ai pas ton systeme mais apparement il suffit de penser a le dezipper, l''endroit ou tu le met n'a pas d'importance, il te faut juste selectionner le chemin apres dans kodi.
