### ISSUE TITLE
zone-telechargement.com

### ISSUE THREAD

**Issue by menad88** [LordVenom/venom-xbmc-addons#75]
Bonjour Lord,
Je voulais proposer une nouvelle source, "www.zone-telechargement.com". Comme il y a toutes les nouveautés et puis, ça propose des liens UPTOBOX. Et dernièrement sur UPTOBOX, on peut soit télécharger soit regarder directement en streaming.
ça serait vraiment super de rajouter cette source.
Merci Lordvenom pour tout ce que vous faites et puis, bon courage.

**Comment by LordVenom** [comment]
Merci, c'est noter.
