### ISSUE TITLE
Idées ou question a propos d'android TV et de la new freebox

### ISSUE THREAD

**Issue by fawado** [LordVenom/venom-xbmc-addons#76]
Salut LordVenom,

J'ai une question qui changerait encore plus ma vie que ton plug la change deja (j'aime l'exagération lol) mais sérieusement ton plugin m'a fait acheter un PI et Kodi (et pas le contraire) bref...

Je vois arriver la nouvelle box de Free sous Android TV, et je sais qu'il est un peu tot pour demander, mais as-tu deja tester ton plug sur kodi/android ? Si oui ca marche bien ? et question en avance sur son temps, as-tu tester sur la nouvelle box Free sous android TV (bon je sais que c'est pas possible, c'est juste pour te dire de regarder dans ce sens dans l'avenir)... car la je pense juste que ce serait une véritable révolution de fou, une seule box et télécommande pour gérer les chaines tradi, les replays de chaines, youtube, vimeo,... kodi et bien sur et l'essentiel... Vstream. Si dans les mois qui arrive, on peut le faire je pense que tu aurais un truc de fou... meme si je ne suis pas certain que cela soit réellement positif pour toi pour le coup (populaire et suite)...

Voila donc meme si il n'y a pas vraiment de question, ni de remarque dans mon message, encore félicitation pour tout ton taf.

**Comment by Europe57** [comment]
Salut fawado

Vstream fonctionne sur Andoid, après la différence entre Android et AndroidTV je la connais pas, mis je pense que sa sera compatible, faut plutôt se demander si XBMC/Kodi est compatible AndroidTV, si il est compatible, sa sera compatible avec Vstream, d'après la doc de Kodi, oui (Google Nexus Player qui est sous AndroidTV "source : http://kodi.wiki/view/Android#Device_specific_info").

Personnelement, j'utilise un boitier (http://www.amazon.fr/gp/product/B00KNOF8JG?psc=1&redirect=true&ref_=oh_aui_detailpage_o00_s00) sous Android (4.4), et Vstream fonctionne sans problème, j'ai aussi tester Vstream sous un Galaxy Note 3 et 2 ainsi qu'un S5 et j'ai aucun soucis dessus.

Mais si ta moyen de tester et de nous faire un retour, sa serais super pour les autres utilisateurs.

A+
