### ISSUE TITLE
Rajouter hosts

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#77]
Salut, tout d'abord tres bonne idee de rendre le projet ameliorable par la communaute, donc j'ai trouve le fichier "ajouter_une_source.py" et je suis en train de me faire dpstream.net.

Probleme :  toutes leurs video sont sur PureVid. Donc j'ai commencé a me faire mon propre pluggin host (vu que la pas de possibilitées pour rajouter les siens) et je bloque sur la procedure pour recuperer le lien direct.

N'y aurait il pas un moyen pour pouvoir utiliser directement le pluggin URLResolver ?

**Comment by TmpName** [comment]
Histoire de ne pas pourrir tout le fil, je vais continuer mes changement ici.

Pour le site http://www.adkami.com
Au lieu de
    sPattern = '<li style.+?>(.+?)</li>|<li title=""><a href="([^<]+)">([^<]+)</a></li>'
Mettre
    sPattern = '<li style.+?>(.+?)<.li>|<li title=".*?"><a href="([^<]+)">([^<]+)<.a><.li>'

Ca evite de sauter la premiere ligne, il maque systematiquement les premier fichiers.

**Comment by TmpName** [comment]
Bon pour info, j'ai presque fini le pluggin dpstream.net, il marche nickel pour les recherches mais je galere encore pour les hosts, j'ai du me faire 2 hosts 1 pour purevid et 1 pour streamin.to.
Les deux fonctionnent mais utilisent utlresolver.

**Comment by LordVenom** [comment]
Bonjour, il et pour le moment impossible d'utiliser UrlResolver pour garder un maximum de compatibilité, Aprés pour faire un host personnaliser vous pouvez regarder le dossier Hosters qui contient les resolver du pluging et le dossier gui/hoster.py qui résout les urls.

**Comment by TmpName** [comment]
Ben en fait c'est que j'ai fais, j'en ai deja au moins rajouté 3 tous utilisant l'api UrlResolver. Mais mon probleme c'est que cela n'est pas officiel donc a la prochaine mise a jour il me faudra tout refaire. car j'ai modifié pas mal de fichiers officiels (Y a aussi un xml a editer pour rajouter l'API)

Ce serait utile de prevoir le meme systeme pour les hosts que que pour les sites : L'integration automatique.
Ou si Vstream possede son resolver ok, sinon il passe par URLResolver.
