### ISSUE TITLE
Serveurs inaccessible ou qui freeze

### ISSUE THREAD

**Issue by mrbinr** [LordVenom/venom-xbmc-addons#79]
Bonsoir, tout d'abord bravo pour ton travail ...

Depuis cet am je n'ai plus accès à cloudy (fichier introuvable) et youwatch provoque un freeze du raspberry pi pendant presque 30 secondes, puis mouline dans le vide.
J'utilise openelec 5.0.6. (mise à jour aujourd'hui ou hier) et vstream 0.2.8

Pour cloudy, j'ai pris l'url que j'ai trouvé dans les logs et dans un navigateur ça fonctionne correctement ... 
D'autre part dans les logs j'ai pas mal de message du genre :

[PLUGIN] Vstream: cant import plugin: adkami_com
[PLUGIN] Vstream: cant import plugin: __init__
[PLUGIN] Vstream: cant import plugin: fifostream_me
...etc...

Log lors du clique sur cloudy :
21:54:55 T:1665610816  NOTICE: Thread LanguageInvoker start, auto delete: false
21:54:56 T:1665610816  NOTICE: -->Python Interpreter Initialized<--
21:54:56 T:1665610816  NOTICE:  [PLUGIN] Vstream: SQLITE 3 as DB engine
21:54:57 T:1665610816  NOTICE:  [PLUGIN] Vstream: load site cHosterGui and call function play
21:54:57 T:1665610816  NOTICE:  [PLUGIN] Vstream: Hoster - play https://............

et rien d'autre et par contre à l'écran "Fichier introuvable"

Voilà ...
Merci.

**Comment by TmpName** [comment]
Pour YouWatch c'est normal, cet hebergeur ne vaut rien, en fait Kodi ne teste la validité du fichier qu'un temps puis se deconnecte "ping timeout" tu peux voir le fichier sous firefox ou vlc mais il se lance au bout de plusieurs minutes parfois, Kodi lache l affaire avant.
Je dirais meme que cela depend de la taille des fichiers, sur de petites series Youwatch demarre de suite mais pour les films .....

**Comment by mrbinr** [comment]
Merci pour ta réponse,
mais du coup avec Cloudy qui est inaccessible et Youwatch qui n'est pas terrible, il n'y a plus vraiment le choix ... dommage

**Comment by TmpName** [comment]
Ben tu utilses quel site pour la recherche ?
Je ne suis pas encore tombe une seule fois sur cloudy ?
Mais youwatch j avous il sort tres souvent comme herbergeur.

**Comment by mrbinr** [comment]
En fait je passe par "Série Nouveauté" Puis je fais frenchstream et ensuite je clique sur la Série et là il est écrit que le serveur c'est Cloudy

**Comment by TmpName** [comment]
Ha oui, meme probleme pour moi cloudy HS et ils utilisent aussi un autre hebergeur "http://watching.to" non geré par l'addon.

**Comment by LordVenom** [comment]
Bonjour et Merci pour le moment pas de solution mais je regarderais ça.
