### ISSUE TITLE
Fenêtre ouverture du flux reste au premier plan figée à un certain pourcentage

### ISSUE THREAD

**Issue by guillaumetell** [LordVenom/venom-xbmc-addons#80]
Bonjour,
Excuse moi de réitérer ma question car je ne peux plus utiliser cet addons que j'adore, mais depuis quelques jours sur mes 3 KODI 14.1 (1 Apple TV2, Windows 7 sp1, Android TV) j'ai ce problème, la fenêtre ouverture du flux reste ouverte au premier plan et est par exemple à 83% ou 95% mais le film fonctionne quand même en arrière plan, que puis-je faire pour résoudre celà, j'ai la Version 0.2.8 installée ?

Merci beaucoup pour une réponse et bravo pour ce super addon

**Comment by LordVenom** [comment]
Bonjour, La fenettre de flux ? vous parler de la popup du changelog ? télécharger le changelog 

https://github.com/LordVenom/venom-xbmc-addons/blob/master/plugin.video.vstream/changelog.txt

et remplacer le votre par celui la.

**Comment by LordVenom** [comment]
Bonjour, Reinstaller le pluging je ne voie que ça, je ferais des tests prochainement.
