### ISSUE TITLE
DPstream.net

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#81]
Bon une source beta pour le site dpstream.net.
http://pastebin.com/8v01u1QD

Attention elle est la a but de developement, elle fonctionne pour les recherches et pour "Serie VF" pas la peine de raler si elle marche pas chez vous.

Elle n'est pas trop utilisable car la plupart de leurs videos sont hebergées sur purevid. Elle marche chez moi mais j'utilise des fichiers host maisons.

J'attend donc un signe du dev pour savoir ce qu'il a prevu pour les fichiers hosts.
En faire un ou pas pour purevid ?
Utiliser urlResolver ou pas ?

**Comment by LordVenom** [comment]
Bonjour, Merci pour votre participation, si urlResolver peux décoder l'url vStream le pourras pour le moment je voudrais éviter que vstream soit lier a un addon.Pour les Host je vous et donner une piste dans votre autre message. Avant d'inclure votre source je la contrôlerais et ferais les modification ou ajout nécessaire.

**Comment by LordVenom** [comment]
Bonjour, Impossible de voir la source dans Kodi, je regarderais plus en profondeur plus tard merci pour votre partage.
