### ISSUE TITLE
zdstream.org nouvelle source

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#82]
BONJOUR LordVenon j'ai crée une nouvelle source zdstream classé numero un des sites de streaming
http://tooply.com/top/ZFCC2482

qui marche trés bien sur le plugin vstream, j'ai mis un corectife de la source full-streaming.net qui devenu full-streaming.me je utilise vstream 0.2.1 qui fonctionne avec enigma2 après modification sur le fichier setting.xml

j'ai crée une list de plus de 3000 films vf urllist avec tous les liens novamov marche avec le plugin 1channel de subixonfire enigma2 en 2 seconde je peu voir un film de cette list est ce que tu peux ajouter ce fichier url.txt sur vstream

https://ia601408.us.archive.org/30/items/urllist_201412/

vstream avec le site zdstream_org.py

http://www.mediafire.com/download/zh8qbd7qxvg4mjo/plugin.video.vstream.rar

**Comment by LordVenom** [comment]
Merci. Je regarde ça au plus vite

**Comment by mino60** [comment]
http://pastebin.com/CkmBHFx3

**Comment by LordVenom** [comment]
Merci pour votre participation le fichier full_stream_me.py et ajouter pour zdstream_org il reste un bug aucune source dans les séries.

Pour votre liste je suis désoler pour le moment j'ai pas le temps de faire un système qui lis les listes.

**Comment by LordVenom** [comment]
Ok tous les liens de serie sont en netu pas de resolver pour c'est source.Votre source et mis en attente pour le moment.

**Comment by mino60** [comment]
désolé LordVenon mais c'est seulement la serie The Walking Dead qui a tous les liens en netu les autres series son en exashare youwatch

**Comment by LordVenom** [comment]
Perso j'ai vue aucun lien dans serie, je regarderais de nouveaux.

**Comment by TmpName** [comment]
Pour netu / HQQ j'ai commencé un resolver (vu que non present sur URLResolver mais j'ai laché l'affaire.
J'arrive a avoir le bon lien mais ca ne marche pas, j'ai tout testé, les headers, les cookies, ...
Les sniffers de paquets me donne le meme resultat, mais ca marche pas.

Pour les motivés, ou pour celui qui aurait une piste http://pastebin.com/s7X6E75M

**Comment by TmpName** [comment]
Ok, bon j'ai une bonne nouvelle, je suis en mesure de recuperer le flux netu/hqq (code ici http://pastebin.com/XZK2xrNs ) Mais il me faut passer un Referer, celui la de preference "Mozilla/5.0 (iPhone; CPU iPhone OS 5_0_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A405 Safari/7534.48.3"

Le seul probleme, je ne connais pas assez kodi ou cet addon pour trouver comment passer un referer au player qui va lancer la lecture.

En fait il y a une protection, sans referer le meme lien donne sur une page 404.

Sinon je viens de voir un fichier hqq.py, il fonctionne celui la ? Il y a des bouts de code mais n'a pas l'air complet.

**Comment by TmpName** [comment]
Bon ben bne nouvelle j'ai reussi a faire tourner un host pour HQQ/netu.
Par contre j'ai trouvé un ficher appelle hqq.py, il y a un debut de code dedans, il fonctionne ?

Code ici http://pastebin.com/D3RNzY04

**Comment by LordVenom** [comment]
Bonjour,

Votre fichier et toujours en attente 2 problème a résoudre si vous le voulez bien.

1 - il y a 2 fonction showMovies() ?
2- Les poster ne s'affiche pas.

**Comment by mino60** [comment]
voilà j'ai corigé la fonction showMovies() ?

http://pastebin.com/nstLdknK

par contre les poster s'affiche normal

http://uprapide.com/images/invite/zdstream.png


le probleme c'est le system qui lie les liens de la section serie

**Comment by LordVenom** [comment]
Désactive les metadonner tu verras y a pas de poster.
