### ISSUE TITLE
Probleme avec le parser

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#83]
Je rencontre pas de probleme avec ton parser
    oParser = cParser()
    aResult = oParser.parse(sHtmlContent, sPattern)

Il ne me detecte pas tout mes regex, si je teste sur le site http://www.regexr.com/ ca marche sans probleme. de meme si je fais
     aResult = re.findall(sPattern, sHtmlContent)

Si tu veux tester > http://pastebin.com/c3j8mMWs

Il semblerait que le probleme vient de la gestion du saut de ligne \n.

**Comment by mrbinr** [comment]
salut,

essai avec une regexp comme : 
deepest mod-box">.+?<a href="([^"]+)" title="([^"]+)" data-overlayer=.+?<img src="([^"]+)"
je testé vite fait et ça semble mieux fonctionner

**Comment by TmpName** [comment]
Et nope, en fait le "." remplace n'importe quel caractere sauf le saut de ligne justement (entre autre) dans certains cas je suis meme oblige de faire (.|\n)+? mais il y a un traitement quand on passe par sa fonction qui perturbe les regex.

**Comment by mrbinr** [comment]
Perso je trouve étrange href="([^<]+)" qui à mon sens devrait être limité à href="([^"]+)" de façon a être certain de n'avoir que ce qui se trouve entre les "" ...
Sinon j'ai retesté de mon côté et ça fonctionne, c'est bizarre que pour ton cas ça ne fonctionne pas

**Comment by LordVenom** [comment]
Perso j'aurais fait deepest mod-box">.*? je voit pas ceux que tu veut faire avec ton data-overlayer="(.|\n) .

J'utilise http://pythex.org/ pour tester mais reg et j'utile pas les saut de ligne ça marche jamais d'un site a l'autre.

**Comment by TmpName** [comment]
Ben le probleme c'est que sur certain site au code bien pourris comme dpstream.net, selon l'age de la page le code est different, un coup tout se tient, un coup tu as un espace, et parfois un saut de ligne.
D'autre site tu as le lien vers l'image sur une autre ligne, et d'utiliser le saut de ligne ca allege le code.

le regex mod-box">.*?<(.+?)><fin>
marche sur
mod-box"><je veux recuperer ca><fin>
mais pas
mod-box">
<je veux recuperer ca><fin>

**Comment by mino60** [comment]
regarde ici si ça peu t'aider

http://pastebin.com/cGctWvfp

**Comment by TmpName** [comment]
Ha pas mal, ca va m'aider, merci, par contre d'ou vient ce code ?
Enfin bon pour le moment j'ai laissé ma version beta en attente pour dpstream.net sur ce github, je l'ai fait uniquement pour les series (j'en ferait une seconde version pour les films) car je n'ai pas trouvé comment utiliser la recherche pour les series OU les films mais pas les deux en meme temps.
Mais la mon probleme c'est pas de recuperer le code, c'est les hosts, ils utilsent Purevid en grande partie, et sans ce host l'addon perd en utilité.

**Comment by mino60** [comment]
ici tu trouve le plugin

http://dpstream.eric-lafontaine.com/index.php

https://code.google.com/p/xbmc-dpstream/downloads/detail?name=plugin.video.dpstream%288%29.zip&can=1&q=
