### ISSUE TITLE
site de streaming multi-plateforme

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#84]
bonjour LordVenon je vous propause cette source avec Nombre de films trouvés: 457.962 résultas
multi-plateforme des liens de streaming qui dépasse par fois 1000 liens pour une video

http://www.fifostream.tv/

**Comment by TmpName** [comment]
Il y est deja et il fonctionne, et je confirme il est tres bon, il m'a trouvé de vieux film comme blade runner, il fait plus que les film de moins de 1 an.

**Comment by mino60** [comment]
C'est pas le meme regarde les images par exemple le film lucy j'ai trouver 789 liens de streamig multi-plateformes

http://upload-pics.org/viewer.php?file=20937960336226211190.png

http://upload-pics.org/images/51984056146304092962.png
