### ISSUE TITLE
Nouvelle source http://www.voirfilms.org

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#85]
Le code ici http://pastebin.com/P9C4YjMa

Ce site est assez complet (il m'a trouvé blade runner et interstella 5555).

La recherche fonctionne.
Les nouveautées aussi (sauf le lien "suivant") mais c'est le site qui deconne
Les genres , la le lien "suivant" fonctionne.
Avec vignette

Sinon a inclure dans la wishlist
+ faire une categorie "film" tout court ou "films VF" comme pour les series car il y a des sections qui ne sont ni nouvelles, ni plus vues, ni plus commentées, ....
+ Faire en sorte que l'option pour activer/desactiver les sites repere toute seule les nouveaux fichiers

**Comment by LordVenom** [comment]
Merci, je regarde ça bientôt.

**Comment by mino60** [comment]
j'ai regler le probleme de next page et j'ai ajouté 2 section Tout les films ? Films par Alphabet de (0,9)
et de AaZ un seul problème pour le next page sur les films par num
par contre je n'ai pas trouver une soluce pour la recherche

http://pastebin.com/5Nh4gN4h

**Comment by TmpName** [comment]
Correction recherche+affiche+prb VK > http://pastebin.com/3YMmh2sZ

**Comment by mino60** [comment]
Comment ajouter les information sur une video sur voirfilms.org son metadata

j'ai trouvai sur le code source de la page html

<img src="img/green_tag.png" alt="Tags" border="0" height="16" width="16">
Tags: Regarder film complet Le Pont de Cassandra en streaming vf et fullstream vk, Le Pont de Cassandra VK streaming, Le Pont de Cassandra film gratuit, en très Bonne Qualité vidéo [720p], son de meilleur qualité également, voir tout les derniers filmze sur cette plateforme en full HD.
