### ISSUE TITLE
frenchstream.org amelioré

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#86]
Bonjour LordVenon , j'ai mis une amelioration sur la la source frenchstream.org en ajoutant de nouvelles options films par categorie ( années de 1925 jusqu'à 2015, par Qualité 720p BDRip BRRip ...ext, par Pays 96 pays , par langue french vo vostfr, par plateforme 37plt voila le py du site
marche bien sur enigma2
http://pastebin.com/4j55DuAj

Si vous pouver ajouter des host comme Cloudy.es NETU turbovideo VidLocker et merci

**Comment by LordVenom** [comment]
Merci du partage

**Comment by LordVenom** [comment]
Bonjour, Votre source seras ajouter a la prochaine mise a jour, merci
