### ISSUE TITLE
Problème

### ISSUE THREAD

**Issue by AxelBriche** [LordVenom/venom-xbmc-addons#87]
Salut, je viens à peine d'installer l'addon et de lancer au hasard 5/6 films et un seul a fonctionné, il serait bien de faire un trie, virer tout ce qui ne marche pas, car actuellement, c'est plus que chiant de trouver quoi que ce soit, surtout qu'en plus on ne trouve que de la SD et pas de 720p pour la grande majorité.

**Comment by LordVenom** [comment]
Bonjour, vStream cherche les url sur les sites de streaming il ne peux donc pas faire le ménage.C'est vrais le 720p et trés rare sur tout les sites de stream mais les connection pouvant stream du vrais 720p le sont aussi.

**Comment by AxelBriche** [comment]
Il faudrait crawler plus souvent les sites alors, par exemple virer les liens qui ne sont plus trouvé après un nouveau passage :)

Pour le 720p, ce n'est plus rare aujourd'hui, j'ai une des pire connexion internet que l'on trouve en france (3méga par satelite) et même avec ça j'arrive à stream du 720p sur youtube, après il faut voir s'il ne faut pas un débrideur selon les sites.
