### ISSUE TITLE
meilleur site de streaming HD 2015

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#88]
Bonjour à tout...

je vous propause cette source  présent comme  le meilleur site de streaming en 2015, permettant de charger un film en HD en moins de 10 secondes avec une connexion moyenne et surtout gratuitement !

Ce site s'appelle Vanoz et ce trouve grace au lien suivant :
http://www.vanoz.com/twona/

il y'à aussi 

bbstreaming.com

**Comment by LordVenom** [comment]
Merci pour le partage

**Comment by mino60** [comment]
pour le host googlevideo pour la source vanoz 


def google(self, data):
	stream_url = re.search('"fmt_stream_map".*?\|(.*?)\|', data, re.S)
	if stream_url:
		self._callback(stream_url.group(1).replace("\u003d","=").replace("\u0026","&"))
	else:
		self.stream_not_found()

**Comment by TmpName** [comment]
Fichier site pour Vanoz > http://pastebin.com/PFHL5uXp
En fonctionnement :
Film nouveautée
Film par genre
Recherche (pas terrible mais ca vient de leur site).

1 seul hebergeur a chaque fois Google Video, mais tres stable, et tres bon debit, pas encore vu de liens morts, tres bon site.

Ne fonctionnera pas sans installer ce fichier un host pour googlevideo utilisant UrlResolver
>> http://pastebin.com/59tb9a8V

Apres pour l'installer ca risque de piquer pour le moment, vu que les hosts persos ne sont pas gérés nativement.

**Comment by mino60** [comment]
merci pour ton travail tout marche bien j'ai le chois de lire le film on 720p et 480p
mais une erreur data pour lire la video je suppose qu'il ya une erreure sur le fichier host.

**Comment by TmpName** [comment]
Oui.
La manip est assez galere, je pense que ce sera surtout utile  dans une future version de son appli, sinon de memoire, il te faut
- mettre le fichier pastepin renomme en "googlevideo.py" dans le repertoire hoster
- modifier le fichier lib/gui/hosters.py en rajoutant
>>        if ('googlevideo' in sHosterUrl):
>>            return cHosterHandler().getHoster('googlevideo')    
>>        if ('picasaweb' in sHosterUrl):
>>            return cHosterHandler().getHoster('googlevideo') 

- modifier le fichier addon.xml pour rajouter 
>> 	<import addon="script.module.urlresolver" version="2.8.0"/>

**Comment by mino60** [comment]
j'ai fait tout ce que tu m'a précisé mais toujour il ya un problème pour lire la video avec googlevideo


http://uprapide.com/images/invite/favelas.png

**Comment by TmpName** [comment]
Ha ?
Je viens de retester pour le meme film, normallement si tu cliques sur un des deux lien tu devrais avoir une nouvelle page pour lancer le fichier avec googleVideo ecrit en bleu a droite du nom. Si tu n'as pas ca c'est la modif du fichier hosters.py qui n'est pas bonne, ou le nom du fichier "googlevideo.py", pas de majuscules, ca vient du monde linux pour eux A c'est pas la meme lettre que a.

Et la ca te redemande quelle qualitée tu desires. Et si c'est apres que ca merde c'est le fichier xml qui doit pas etre bon, il y a des signes superieur/inferieur a mettre, mais ils disparaissent quand je les tapes. Normallement c'est la meme syntaxe que la ligne precedente.

Il faudrait que tu jete un oeuil sur le fichier log, j'ai tellement modifié les fichiers que je ne me souvient plus trop de mes modifs.

**Comment by mino60** [comment]
voilà mon vichier vstream et regarde ou ai le problème

http://www.mediafire.com/download/w11wg391u2hv9tq/plugin.video.vstream.zip

**Comment by TmpName** [comment]
Il te manque la derniere ligne dans le fichier vanoz.py

 oGui.setEndOfDirectory()

**Comment by mino60** [comment]
ça fonctionne maintenant nickel merci beaucoup pour votre aide et pour les fichiers de la source venoz.com

**Comment by mino60** [comment]
ajout de la section Documentaires Animation et Spectacles sur la nouvelle source vanoz:


http://pastebin.com/xhcZJ7E1

**Comment by mino60** [comment]
Bonjour ...quand je regarde une video HD 720p  j'ai constaté que quand je veux revoir la mème video
je trouve que le choix 480p je suis entré dans parametre general vstream et cliqué sur clear addons pour avoir le choix 720p de nouveau.

**Comment by spaniish83** [comment]
Bonjour merci bien pour cette magnifique source , mais j'ai un soucis sur kodi via pc sa fonctionne parfaitement mais via kodi android quand je lance les films sa me dit erreur de script ?

**Comment by spaniish83** [comment]
Edit : j'ai mis KODI 15.0 sur android box et cela fonctionne mille merci a vous j'ai essayer de crée la source fetnop mais je n'y parvenais pas merci merci

**Comment by TmpName** [comment]
"Bonjour ...quand je regarde une video HD 720p j'ai constaté que quand je veux revoir la mème video
je trouve que le choix 480p je suis entré dans parametre general vstream et cliqué sur clear cache addons pour avoir le choix 720p de nouveau."

C'est normal, j'ai aussi ce probleme ailleurs, en fait kodi est reglé par defaut pour ne pas afficher les films que tu as deja vu. C'est a virer car ca me provoque chez moi 2 problemes:
1 - la disparition de certains liens
2- l'impossibilité de lancer certaines video, ca me met a 2s de la fin (sans me demander mon avis contrairement aux films, ca je sais pas pkoi) et evidement ca ferme 2s apres avant que j'ai pu reagir.

**Comment by spaniish83** [comment]
J'ai un soucis tout fonctionner parfaitement jusqua aujourdhui maintenant le message fichier inttouvable apparais a tout les film

**Comment by TmpName** [comment]
Normal, il y a eu un changement, la je n'ai pas le temps de m'en occuper ce soir mais il y a moyen de faire son propre host (sans passer par url resolver)

Mes recherches on donné ca.
On part du lien que recupere vstream
>> https://picasaweb.google.com/108235257980439830364/Im7?authkey=Gv1sRgCI_gm_jCtoPtnQE#6132970461365535586

ceci amene sur une page ou on peut trouver 
{"url":"https://lh3.googleusercontent.com/uhV0iwh39D6i5xtq1GMVfpGXtF13zpcEowAHrjHZ0g=m18","height":360,"width":640,"type":"video/mpeg4"}

Ce lien ramene directement a 
Redirect to: https://r20---sn-25ge7nl7.googlevideo.com/videoplayback?id=fc81bdb3b29985da&itag=22&source=picasa&requiressl=yes&mm=30&ms=nxu&mv=m&pl=17&gir=yes&clen=751925273&dur=4799&lmt=1427945436481320&mime=video/mp4&mt=1427993554&ip=31.38.252.7&ipbits=0&expire=1428022403&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,ms,mv,pl,gir,clen,dur,lmt,mime&signature=B24BFA370D2F277A73971D200FE4D17908B80B20.B216DD61853125E1147AF2C7EFA81B3BF8913A9E&key=ck2

Et la on a le lien direct a ouvrir

**Comment by spaniish83** [comment]
Lol je vais paraitre bête mais je n'ai pas compris ou vous récuperer le fichier que vstream ouvre ^^

**Comment by TmpName** [comment]
Lol, c'est normal c'etait au cas ou quelqu'un veuille se pencher sur le host

Nouveau host pour googlevideo > http://pastebin.com/G2HAKsuf

Il resous le probleme et du coup il marche sans urlresolver vu qu'ils sont aussi reactif que des huitres pour maintenir leur pluggin a jour (Y avait juste une ligne a corriger). Par contre je ne l'ai pas tester pour l'ancienne version, mais vu que j'ai gardé leur code doit pas y avoir de probleme.

**Comment by spaniish83** [comment]
Mille merci je part essayer

**Comment by mino60** [comment]
merci TmpName vous etes un boss!!!..,ça marche nickel maintenant ou meme mieux qu'avant avec urlresolver , si vous pouvez trouver une solution pour la source "lopav" similaire de "vanoz.com" don la section nouveauté la liste des films ne s'affiche pas (car c'est sites change d'adresse par fois).
une remarque sur la source vanoz la fonction recherche ne fonctionne pas un message d'erreur de script vstream s'affiche on bat de l'écran voilla le log.kodi
http://pastebin.com/qAGBLaJH
site lopav_com.py :
http://pastebin.com/6RhAS1wS

http://uprapide.com/images/invite/lopav.png

**Comment by TmpName** [comment]
Correction pr la recherche vanoz > http://pastebin.com/Q2EPztju

**Comment by spaniish83** [comment]
Merci man

**Comment by mino60** [comment]
Il ya eu un changement sur vanoz.com ils sont integré un lecteur medea vanoz player 

vanoz ne marche pas avec moi sur kodi
le lien de lecture que j'ai que j'ai récupéré avec idm:


https://r9---sn-hgn7zn7d.googlevideo.com/videoplayback?id=5d27400420555f1c&itag=22&source=picasa&requiressl=yes&mm=30&ms=nxu&mv=m&pl=19&gir=yes&clen=1395439499&dur=6824&lmt=1426763124155771&mime=video/mp4&mt=1428272929&ip=105.111.32.239&ipbits=0&expire=1428301802&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,ms,mv,pl,gir,clen,dur,lmt,mime&signature=8E71D8820530EBBBE2F47FB8B975DABAC63A3E97.638FBDA5BFD71763FCCD69485AB4B2BA2978D288&key=ck2

**Comment by spaniish83** [comment]
en passant par le site vanoz les film marche maintenant sous android plus besoin de passer via vstream

**Comment by TmpName** [comment]
Ok, alors pour resoudre ce probleme, editer le fichier gui/hosters.py
Rajouter
        if ('vkontakte' in sHosterUrl):
            return cHosterHandler().getHoster('vk')

**Comment by TmpName** [comment]
Mise a jour de vanoz et du host google dans https://github.com/LordVenom/venom-xbmc-addons/issues/99

**Comment by monicacr** [comment]
try this http://streamcomplet.bz/
