### ISSUE TITLE
Petite modif sur Adkami.com

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#89]
Trois fois rien, en fait si on cherche un animé FR 50% des lien sont desactivés car animé licencié, mais les lien sont encore present.
Cette modif affiche en rouge "animé licencié" au lieu des liens habituel pour eviter de se retrouver avec des listes vide juste apres.

http://pastebin.com/ZQa1Vgfc

Petite question, pour les images on peut rajouter des poster et des vignettes. Il n' a pas moyen de changer le fond d'ecran complet ?
En fait adkami ne propose pas d'image a part un truc gigantesque en 1000*300, impossible a utiliser en vignette mais en fond d'ecran .....

**Comment by LordVenom** [comment]
Bonjour et Merci, votre nouveaux fichier seras inclus dans la prochaine mise a jour.
