### ISSUE TITLE
Nouveau host mail.ru

### ISSUE THREAD

**Issue by TmpName** [LordVenom/venom-xbmc-addons#90]
Bon encore en but de dev, inutilisable tel que.

http://pastebin.com/KEiHr58d

Hebergeur proposé par voirfilm.org par exemple, je ne l'ai pas vu dans URLResolver ni dans Vstream. Il propose un dialog avec la qualitée desirée.

Par contre j'ai fais une modif perso dans hoster.py

 def checkHoster(self, sHosterUrl): 
       sHosterUrl = sHosterUrl.replace('.','')
       if ('novamov' in sHosterUrl):

Car certains hebergeurs ont des noms trop courts et de rajouter l'extension ca evite les fausses detections, "Mail" me donnait plus de probleme que "Mailru"

**Comment by mino60** [comment]
merci pour le nouveau host Mail.ru  j'ai remarqué que  tout lies liens de http://www.full-streaming.com 
on mail.ru

**Comment by LordVenom** [comment]
Merci, le hoster seras inclus dans la prochaine mise a jour.
