### ISSUE TITLE
full stream et autres flux

### ISSUE THREAD

**Issue by shortcutter** [LordVenom/venom-xbmc-addons#92]
Bonjour,

full-stream.net ne marche plus, mais il a été remplacé par full-stream.me (simple changement d'adresse.)
Je sais pas trop comment s'ajoute des flux, mais j'en connais un autre(séries uniquement) découpé en deux : http://streamzzz.com/ , et au bout d'un certain temps, les series passent sur http://www.regarder-film-gratuit.com/

**Comment by shortcutter** [comment]
le nouveau full-stream (j'ai laissé le .net dans le nom, à vous de voir si il faut le changer ...)
A priori tout fonctionne
http://pastebin.com/bzmUuUwR

**Comment by LordVenom** [comment]
Merci la nouvelle source seras inclus dans la prochaine mise a jour.
