### ISSUE TITLE
host Netu

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#93]
pour le dev

nouveau host Netu

http://pastebin.com/S1VrCE3t

**Comment by TmpName** [comment]
XD, ou tu l'as retrouvé celui la ?
C'est le copier/coller de celui que j'ai fini y a meme pas 5 jours ici > https://github.com/LordVenom/venom-xbmc-addons/issues/82 et a pars un forum de URLResolver completement mort je l'ai mit nulle part.

**Comment by mino60** [comment]
Bonjour ... c'est pour Mediaportal plugin enigma2 je les essaye mais il ne fonctionne pas j'ai du loupé quellqe chose.

**Comment by TmpName** [comment]
Ben il marche sur Vstream en tout cas, en rajoutant quelques ligne dans hosters.py

        if ('hqq' in sHosterUrl):
            return cHosterHandler().getHoster('hqq_netu')
        if ('netu' in sHosterUrl):
            return cHosterHandler().getHoster('hqq_netu')

**Comment by mino60** [comment]
En rajoutant c'est ligne dans hoster.py (recourses/lib/gui/hoster.py) il ya une erreur du script pour lire ou affiché les hostes et quand je remet le fichier comme il était pas de problème

**Comment by LordVenom** [comment]
Bonjour, Effectivement ça a l'air de fonctionner cool, normal que ça plante au debut 

#import urlresolver vStream n'utilise pas urlresolver.
