### ISSUE TITLE
Telecharger-films.ws

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#94]
Bonjour LordVenom,

J'ai remarqué avec cette nouvelle mise a jour 2.9 le nouveau lien "Telecharger-films.ws" mais malheureusement ce lien me donne a chaque fois l'erreur "Echec du script!: vstream"?
Pour info ce lien ne figure pas dans "plugin on/off et recherche des parametres de Vstream?

S'agit-il d'un bug?

**Comment by LordVenom** [comment]
Erreur de fichier il ne devrais pas ce trouver la.
