### ISSUE TITLE
problème avec speedvideo

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#96]
j'ai modifier quelque fichiers pour le host speedvideo ( remarque speedvid c'est pas le mème speedvideo) , mais je ne peu pas voir la video il ya un message qui me dit speedvideo fichier introuvable, et ça malgré que le fichier existe sur le site frenchstream.org

http://uprapide.com/images/invite/speedvideo.png

**Comment by arzaz** [comment]
Meme cas ave le host Cloudy

**Comment by FreeFighter77** [comment]
salut j'ai crée speedvid,il fonctionne impec sur serie fr,et en effet il y a un autre hoster semblable ou le meme c pas trop c speedvideo

**Comment by TmpName** [comment]
Un host pour speedvideo http://pastebin.com/A5Fn4rG9
Je me suis pas fais chier j'ai repiqué le code de URLResolver vu que le dev ne veut pas l'utiliser.
Par contre pour la partie qui verifi les host il faut faire quelque chose pour ne pas confondre les 2 hosts

**Comment by mino60** [comment]
merci pour le host mais ça na pas fonctionnée toujour le message fichier introuvable

**Comment by TmpName** [comment]
Tu as fait aussi des modif dans le fichier hosters.py ?
Si il essaye de se connecter avec speedvid ca marchera jamais.

**Comment by mino60** [comment]
Oui effectivement j'ai modifier le fichier hoster.py 

http://pastebin.com/KWqXwLXn

**Comment by TmpName** [comment]
Ok, je viens de comprendre.
Cet hebergeur propose au moins 2 types de presentation
http://speedvideo.net/embed-jowuy1x63x13-730x410.html marche tres bien
http://speedvideo.net/embed-fjq8gt5ripj9-607x360.html ne marche pas avec Vstream, mais au moment de mes test, elle ne marche pas non plus sur firefox.
J'ai commencé a modifier le code, mais vu qu'elle ne marche pas sur navigateur, je ne peux pas la tester.

**Comment by TmpName** [comment]
Bon en fait me chier pour rien, la plupart des video seraient en court d'upload (depuis 24 h ???)
Sinon pour faire fonctionner les autres, truc tout simple

dans le fichier hoster.py
        if ('streamingentiercom/videophp?type=speed' in sHosterUrl):
            return cHosterHandler().getHoster('speedvideo')

Faire gaffe, moi je supprime les "." a adapter selon ton code
En fait l'adresse est de la forme src="http://www.streamingentier.com/video.php?type=speed&code=fjq8gt5ripj9&w=660&h=400" 
Rien a voir avec du speedvideo.com

On pourrait convertir le lien comme pour vk mais ca demanderait a charger une page de plus.

**Comment by FreeFighter77** [comment]
Le probleme est que ce n'est pas applicable a streamzer.net ou speedvideo a cette forme : 
http://speedvideo.net/embed-ig2op91ndh8y-640x391.html

**Comment by FreeFighter77** [comment]
Probleme resolu tt simplement comme toi dans gui/lib/hosters.py
c lignes : if ('http://speedvideo.net/embed' in sHosterUrl):
            return cHosterHandler().getHoster('speedvideo')
               if ('http://www.speedvid.net/embed-' in sHosterUrl):
            return cHosterHandler().getHoster('speedvid')

**Comment by TmpName** [comment]
Retesté, c'est fonctionnel.
Testé avec 24h chrono Saisons 9 ep 12.
Si tu veux jetter un oeuil sur mon fichier hosters.py > http://pastebin.com/CkiJzvZx
Mais evite le copier/coller, il y a des trucs qui ne fonctionneront pas chez toi.

Attention : je supprime les "." en debut de fichier (meme si ca sert a rien je sais)

Il faut soit faire attention a l'ordre, soit au nombre de lettres (c'est pour ca que je colle l'extention)
Si tu met speedvid avant speedvideo les video speedvideo ne marcheront pas
