### ISSUE TITLE
Host Netu avec la version 2.9

### ISSUE THREAD

**Issue by arzaz** [LordVenom/venom-xbmc-addons#97]
![xbmc log](https://cloud.githubusercontent.com/assets/9026875/6882495/0f6efcd8-d587-11e4-9cd6-cae021d44c54.png)

Problème avec le host Netu avec l'erreur "Eche de la lecture de un ou plusieurs éléments"

Ci-joint le log.

Film essayé "Imitation game"

Merci de voir c'est quoi le probleme.

**Comment by TmpName** [comment]
Le log n'est pas lisible.
Tu pourrait pas me dire sur quel hebergeur tu as testé ? Moi je vient de refaire un test sans soucis, j'ai du louper un truc.

**Comment by FreeFighter77** [comment]
Le host netu ne fonctionne pas du tout chez moi,le log m affiche: CVideoInfoTag::GetDurationFromMinuteString <runtime> should be in minutes. Interpreting '' as 0 minutes (tester sur toutes les series dpstreaming.org)

**Comment by mino60** [comment]
Bonjour , ça fonctionne pour moi 

host netu.py:

http://pastebin.com/gVcPURfa

hoster.py :+1: (resources/lib/gui/hoster.py)

http://pastebin.com/mvpTZrcj
 
addon.xml (moi je utilise urlresolver) sur vstream

http://pastebin.com/vfi6h9na

**Comment by FreeFighter77** [comment]
a ui,mais moi parle uniquement de la mise a jour de venom brut.Lui a retiré urlresolver du xml ^^

**Comment by arzaz** [comment]
Bonjour mino60,

Faut-il que je remplace les 03 fichiers "host netu.py + hoster.py + addon.xml" pour que ca marche?

Merci

**Comment by TmpName** [comment]
C'est bizarre justement, il a validé netu car celui ci n'utilise pas URLResolver, je viens de regarder le code, il devrait marcher sans modifs, je reteste.

**Comment by FreeFighter77** [comment]
http://pastebin.com/sVCQbRJu

**Comment by mino60** [comment]
arzaz # pas forcément tu peux essayer avec c'est fichiers pour voir ,remarque moi je utilise kodi-15-0-alpha-1-road-to-isengard.

**Comment by TmpName** [comment]
Bon ben je comprend pas, j'ai essayé les liens de ton log, j'ai pu les ouvrir sans problemes
Ca pourrait pas venir du player ?
C'est quoi le fim/serie et site ?

**Comment by FreeFighter77** [comment]
frenchstream.org tt les liens netu de tt les films ^^

**Comment by TmpName** [comment]
Alors j'ai testé le premier "les heritiers", c'est celui de ton lien, ca marche 5mn puis ca coupe, j'ai testé sur firefox pareil, donc c'est le fichier qui deconne.
Puis j'ai testé "les enquetes du departement V" et la ca tourne encore.
Tu as essayé en selectionnant le second lecteur dans les options de l'addon ?

**Comment by mino60** [comment]
voilà tout les fichier vstream avec  modification de quelque fichiers si tu veux tester les liens netu

http://www.mediafire.com/download/w11wg391u2hv9tq/plugin.video.vstream.zip

**Comment by FreeFighter77** [comment]
J ai tout teste vidé le cache xbmc et vstream,les lecteurs rien n y fait.Sur dpstreaming french stream etc netu ne marche pas pour moi.Jai gotham 13.2 windows et ds le log une erreur ERROR: CDVDDemuxFFmpeg::Open - Error, could not open file http://c7.vkcache.com/secip/1/YKiqxwtvx8DAdiLfZbeLnQ/NzguMjQwLjE1NC4xNTQ=/1427684400/hls-vod-s3/flv/api/files/videos/2015/03/29/14275866177d850?socket=
18:53:02 T:6288   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
18:53:02 T:6288  NOTICE: CDVDPlayer::OnExit()
18:53:02 T:6288  NOTICE: CDVDPlayer::OnExit() deleting input stream
18:53:02 T:6100   ERROR: Playlist Player: skipping unplayable item: 0, path [http://c7.vkcache.com/secip/1/YKiqxwtvx8DAdiLfZbeLnQ/NzguMjQwLjE1NC4xNTQ=/1427684400/hls-vod-s3/flv/api/files/videos/2015/03/29/14275866177d850?socket=|User-Agent=Mozilla/5.0 (iPhone; CPU iPhone OS 5_0_1 like Mac OS X)]
18:53:02 T:6100  NOTICE: CDVDPlayer::CloseFile()
18:53:02 T:6100  NOTICE: DVDPlayer: waiting for threads to exit
18:53:02 T:6100  NOTICE: DVDPlayer: finished waiting
18:53:02 T:6100  NOTICE: CDVDPlayer::CloseFile()
18:53:02 T:6100  NOTICE: DVDPlayer: waiting for threads to exit
18:53:02 T:6100  NOTICE: DVDPlayer: finished waiting
18:53:02 T:8356  NOTICE: 	[PLUGIN] Vstream: Table initialized
18:53:02 T:8356  NOTICE: 	[PLUGIN] Vstream: SQL INSERT watched Successfully
18:53:02 T:10160  NOTICE: Thread LanguageInvoker start, auto delete: false
18:53:03 T:8356   ERROR: EXCEPTION: XBMC is not playing any media file
18:53:03 T:10160  NOTICE: -->Python Interpreter Initialized<--
18:53:03 T:10160  NOTICE: 	[PLUGIN] Vstream: SQLITE 3 as DB engine
18:53:03 T:10160  NOTICE: 	[PLUGIN] Vstream: load site frenchstream_org and call function showHosters
18:53:04 T:10160  NOTICE: 	[PLUGIN] Vstream: Table initialized
18:53:04 T:10160 WARNING: CVideoInfoTag::GetDurationFromMinuteString <runtime> should be in minutes. Interpreting '' as 0 minutes
18:53:04 T:8992  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by mino60** [comment]
Les liens sur le log c'est des liens vk et pas netu!?..

**Comment by FreeFighter77** [comment]
http://pastebin.com/rDZiv3Qi

**Comment by FreeFighter77** [comment]
Bon apres mettre bien battu,le probleme vient de gotham 13.2 sur et certain.pour le hoster netu il faut kodi 14.2 ^^ voilou voilou

**Comment by arzaz** [comment]
Une solution svp pour gotham 13.2
