### ISSUE TITLE
Un souci avec Vk Player

### ISSUE THREAD

**Issue by mino60** [LordVenom/venom-xbmc-addons#98]
J'ai ajouter un host vkme apprêt j'ai cherché une video qui marche avec vk.me j'ai trouver un film sur voirfilms.org section arts martiaux titre : la 14ème lame mais ça n'a pas marché avec Vk Player j'ai eu un message "fichier introuvable" pourtant le fichier existe sur la plateforme vk.me

vkme.py:

http://pastebin.com/nETWvRjJ

**Comment by TmpName** [comment]
Le host vk existe deja, il faut juste faire une modif dans le fichiers hosters.py

Par contre pour le site voirfilms ils volent les lien d'autres sites ce qui fait que le lien s'est retrouvé etre mauvais, pour le reparer >> http://pastebin.com/URMVuamP

Il n'y qu'une ligne a rajouter, mais comme je ne sait pas ou en sont les modifis de fichiers, je te met tout le pavé c'est la ligne avec streamingenteier.

Cela marche directement, sans modif dans vk.py, je ne sais pas pkoi ce host n'est pas activé ?????
