### ISSUE TITLE
Centralisation de fichier .py terminé ou corrigé

### ISSUE THREAD

**Issue by FreeFighter77** [LordVenom/venom-xbmc-addons#99]
Je crée cet issue pour que lord venom s'y retrouve facilement,je propose de mettre ici des fichiers terminé et testé pour etre sur qu'il n'y est pas de bug a la prochaine mise a jour.

Correction de cloudy (juste la récuperation de la key qui buggait),testé sur frenchstream.org fonctionne nickel.

http://pastebin.com/hE3bVQVJ

**Comment by arzaz** [comment]
Merci pour cette initiative FreeFighter77

Après téléchargement du fichier, Je dois le renommé comment? Cloudy.py?

**Comment by LordVenom** [comment]
Merci freeFighter, Ne vous inquiéter pas j'ai un peux de mal a suivre manque de temps mais si tous le monde continue à participer ainsi (merci a tous) je ferais un repo beta ou tous le monde pourras directement faire c'est modification.

**Comment by arzaz** [comment]
Bonjour LordVenom,

Il ne faut pas oublier de régler le problème du host Netu pour gotham 13.2.

Merci

**Comment by FreeFighter77** [comment]
hello je rajoute des hosters pour Frenchstream.org (ce site est un regale pour les films bcp de hosters,par contre je pense qu il faut annuler pour les series car un seul lien a chaque fois et souvent mort) 
voici les hosters(tous testé et fonctonnel sur frenchstream.org:

-videoraj: http://pastebin.com/9WxAspm4
-videohut: http://pastebin.com/gziC56iT
-onevideo: http://pastebin.com/EAHe2ySM

voilou

**Comment by FreeFighter77** [comment]
également correction de full.streaming.net qui recupere mal les pochettes+ajout de la qualité

http://pastebin.com/9qnNrfdd

**Comment by TmpName** [comment]
Petite modif pour seriefr.com
Rajoute la recherche
>> http://pastebin.com/n6KNjJcC

**Comment by arzaz** [comment]
Bonjour,

Merci de spécifier svp si les modifications tournent avec KODI ou GOTHAM?

Comme j'utilise gotham 13.2 sur PRISMCUBE RUBY, je galère a faire tourner ces modifications.

A titre d'exemple seul le host cloudy a fonctionné sur ma machine autrement ni vanoz, ni Netu et ni la dernière correction de full.streaming.net n'a marché!!!!

Merci encore

**Comment by arzaz** [comment]
Bonjour FreeFighter77

Pour les hosters ci-dessous , faut-il changer hoster.py? car je ne les trouve nulle part avec la source Frenchstream.org 
-videoraj: http://pastebin.com/9WxAspm4
 -videohut: http://pastebin.com/gziC56iT
 -onevideo: http://pastebin.com/EAHe2ySM

Merci

**Comment by mino60** [comment]
arzaz # oui si tu veux les ajouter don hoster.py il te faut les configurer don : recources/lib/gui/hoster.py

ajouter c'est lingnes:
http://pastebin.com/sJ1Rn28e

**Comment by arzaz** [comment]
Merci beaucoup mino60

**Comment by TmpName** [comment]
Voirfilms.com: Correction recherche+affiche+prb VK > http://pastebin.com/3YMmh2sZ
Vanoz.com : Correction recherche > http://pastebin.com/Q2EPztju

**Comment by FreeFighter77** [comment]
TmpName je me permet de rajouter ici le hoster que tu as crée googlevideo: http://pastebin.com/G2HAKsuf (il va bien avec la source vanoz.com ;) )

**Comment by FreeFighter77** [comment]
correction hoster rutub: http://pastebin.com/HZEGUqZ4  (testé sur adkami.com,pas trouvé sur d autre source)

**Comment by arzaz** [comment]
Bonjour,

Malgré avoir rajouter la source "Voirfilms.com": Correction recherche+affiche+prb VK > http://pastebin.com/3YMmh2sZ dans le dossier sites du plugin vstream, mais dernière ne s'affiche pas? Est ce que j'ai omis quelque chose?

**Comment by TmpName** [comment]
Normallement il n 'y a rien d'autre a faire pour une version de kodi a jour. Regarde bien le fichier si il n'a pas de tabulation a la place des espaces ou si il ne te manque pas une ligne.

Nouveau host "VideoTT" pour la source http://www.regarder-film-gratuit.com/ par exmple
>> http://pastebin.com/fWXvJZaU

**Comment by arzaz** [comment]
Bonjour TmpName,

J'ai téléchargé le fichier http://pastebin.com/3YMmh2sZ, que j'ai renommé en "voirfilms_org.py"

Mais la source ne veut pas apparaître!!!!!! c'est bizare

Est-il possible d'avoir ton fichier plugin.vstream.zip?

Merci

**Comment by TmpName** [comment]
Nouveau host PlayReplay tjours pour le meme site regarder-film-gratuit.com
> http://pastebin.com/G4UzsW0B

Et non je ne peux pas faire passer le repertoire complet car avec le nbre de modifs qu'il y a dedans ca va etre encore pire pour toi pour t y retrouver.

Je viens de refaire le test, telechargement du fichier, renommage, copiage dans le repertoire "site", je retourne dans kodi, je vais a "Toutes les sources" et il apparait. Tu as bien la derniere version de Kodi ?

**Comment by arzaz** [comment]
Désolé, j'ai oublié de mentionner que je suis toujours sous gotham 13.2, car ma box "PRISMCUBE" n'accepte pas encore Kodi.

**Comment by FreeFighter77** [comment]
Un host pour speedvideo http://pastebin.com/9tRg4Yfi (fonctionnel teste sous streamzer.net) crée par tmpName !!
Et pour qu il ne bug pas avec speedvid (seriefr.com),il faut c lignes dans hosters.py:
if ('http://www.speedvid.net/embed-' in sHosterUrl):
            return cHosterHandler().getHoster('speedvid')
if ('http://speedvideo.net/embed' in sHosterUrl):
            return cHosterHandler().getHoster('speedvideo')

**Comment by TmpName** [comment]
Mise a jour de Vanoz > http://pastebin.com/5QeVZXKL
Mise a jour du host google video (pour Vanoz) > http://pastebin.com/aHQcZjPj
J'ai du desactiver les lien picassaweb car je n'ai aucun lien pour tester le host

**Comment by spaniish83** [comment]
Merci

**Comment by mino60** [comment]
malgré la mise a jour du site vanoz.com ça ne fonctionne pas?!!..

**Comment by FreeFighter77** [comment]
pour vanoz.com dans lib/gui/hoster.py ajouter ca: (de tmpname)
if ('googlevideo' in sHosterUrl):
            return cHosterHandler().getHoster('googlevideo')
        if ('picasaweb' in sHosterUrl):
            return cHosterHandler().getHoster('googlevideo')
        if ('googleusercontent' in sHosterUrl):
            return cHosterHandler().getHoster('googlevideo')

**Comment by spaniish83** [comment]
sa

**Comment by TmpName** [comment]
Ha oui mince, y a plus de validation de selection sur la derniere etape, je vais essayer de m'en occuper dans la semaine.

**Comment by mino60** [comment]
j'ai trouver la solution pour la source vanoz.com , le site à intégrer vanoz player a la place de google video , j'ai crée un host vanoz avec les données google video et picasaweb et du coup ça marche
host vanoz.py :
http://pastebin.com/Y5x1JU37

source vanoz_com.py

http://pastebin.com/cLyy1kRV

        #if ('googlevideo' in sHosterUrl):
            #return cHosterHandler().getHoster('googlevideo')
        if ('vanoz' in sHosterUrl):
            return cHosterHandler().getHoster('vanoz')
        if ('picasaweb' in sHosterUrl):
            return cHosterHandler().getHoster('vanoz')  
        #if ('googleusercontent' in sHosterUrl):
            #return cHosterHandler().getHoster('googlevideo')

**Comment by TmpName** [comment]
Marche pas ma derniere modif ?

**Comment by mino60** [comment]
ça marche avec moi il faut mettre les fichiers que j'ai mit :+1: 

images:

http://upload-pics.org/images/78765914378847674401.png
http://upload-pics.org/images/09798318565032766579.png
http://upload-pics.org/images/14858425274639227861.png
http://upload-pics.org/images/51880792174833526868.png
http://upload-pics.org/images/48201820107711122676.png

**Comment by FreeFighter77** [comment]
TmpName ca fonctionne vanoz du ghitub beta,il y a bien les 2 qualités avec hoster googlevideo

**Comment by mino60** [comment]
j'ai ajouter vanoz.com vertion 0.2.9 don master TmpName-author-update
il est sur vstream beta

**Comment by FreeFighter77** [comment]
TmpName faudra que tu reportes t es modif dans la beta,moi ca y est j ai tt transferé,j ai transferé aussi seriefr.com, mais je m arrete la pour plus de transparence.
Toi il te reste speedvideo,googlevideo,vodlocker,videott,playreplay en host ;) bonne chance 
Par contre vu que y a pas lib/gui/hoster.py comment consigne pour: vkontakte.speedvid,speedvideo,videott:

http://pastebin.com/2bizj0FH

**Comment by TmpName** [comment]
Heu, bon ben je reteste, je viens juste de voir les nouveaux fichiers, si dans 1 heure ca apparait tjours pas c'est que me serais pendu.

Sinon oui l'absence du dossier lib est assez contraignante vu les modifs qu'on y fait, mais pour le moment j'essaye deja les hosts.

A de suite.

**Comment by FreeFighter77** [comment]
googlevideo.py apparait dans pullrequest c bon,moi ca donnais pareil que toi,je pense que seul venom peut merge ... Il est passe dans la journée est a mergue mes fichiers voila tt

**Comment by TmpName** [comment]
Ok, alors je continu.

**Comment by FreeFighter77** [comment]
au pire on peu lui mettre dans issue du github beta,car par exemple pour ton videott tjs pas compris marche seulement si rajoute:   sHosterUrl = sHosterUrl.replace('.','')

**Comment by FreeFighter77** [comment]
d'ailleur a propos de videott fonctionne nickel sur regarder-films.com,mais pas sur streamzzz.com, la source a cette forme:   http://www.video.tt/e/Q7MsT7cqV

**Comment by TmpName** [comment]
Essaye avec ca http://pastebin.com/1yhsWE94
Il teste avec et sans le www
Avec /embed/ et /e/

**Comment by FreeFighter77** [comment]
purée suis vraiment nul depuis tt a l heure j essaye (?:embed|e),bref merci pense a le modifier ds le github beta avant que venom merge
